
<div dir="rtl" style="text-align: right; line-height: 2; font-size: 16px;">

# المرحلة الثالثة — بناء وتقييم نظام الاسترجاع RAG باستخدام ChromaDB إلزامياً

هذا النوتبوك يمثل المرحلة الثالثة من مشروع:
<span dir="ltr" style="display:inline-block;">Arabic AI Voice Agent for Saudi Labor Law using RAG</span>

في هذه النسخة تم جعل <span dir="ltr" style="display:inline-block;">ChromaDB</span> جزءاً إلزامياً من خط سير العمل، بحيث يتم بناء قاعدة متجهات مستمرة، ثم تنفيذ الاسترجاع الدلالي من ChromaDB مباشرة. بعد ذلك تتم مقارنة الاسترجاع الدلالي، والاسترجاع اللفظي، والاسترجاع الهجين، والهجين مع إعادة الترتيب.

الهدف من هذه المرحلة هو إنهاء طبقة الاسترجاع بالكامل قبل الانتقال إلى المرحلة الرابعة الخاصة بنموذج اللغة الكبير <span dir="ltr" style="display:inline-block;">LLM</span>.

</div>

<div dir="rtl" style="text-align:right; line-height:2; font-family:Tahoma, Arial; font-size:16px; border-right:6px solid #1f4e79; padding:12px; background:#f7fbff;">

## ملاحظات النسخة المعدلة للمناقشة الأكاديمية

تمت مراجعة هذا النوتبوك بحيث يعتمد على مخرجات Notebook 02 النهائية:

- `rag_knowledge_base_dataset_experiment_no_leakage_active_law_only.csv`
- `rag_retrieval_evaluation_dataset_valid_only.csv`
- `rag_chunks_structural_legal_experiment.csv`
- `rag_chunks_fixed_size_experiment.csv`

كما تم إضافة فحوص حماية إضافية حتى لا تظهر نتائج مضللة بسبب:
تسريب بيانات التقييم، مراجع ذهبية غير موجودة في الفهرس، مقاطع فارغة، مواد ملغاة، أو ملف مراجعة يدوي غير مكتمل.

</div>

> ## ⚠️ تنبيه تشغيل مهم
>
> شغّل هذا النوتبوك دائمًا من القائمة: **Kernel → Restart & Run All**.
>
> لا تشغّل خلية بمفردها، لأن المتغيرات مثل `df_eval` و`CORPORA` تتكوّن في خلايا سابقة.
>
> تشغيل خلية وحدها قبل ما تشتغل الخلايا التي تسبقها يسبب خطأ `NameError`.

In [1]:
# =========================================================
# Stage 01 - Environment, Project Paths, and Reproducibility
# =========================================================

from pathlib import Path
import os
import re
import json
import time
import math
import hashlib
import warnings
from collections import Counter, defaultdict

import numpy as np
import pandas as pd

warnings.filterwarnings("ignore")

RANDOM_SEED = 42
np.random.seed(RANDOM_SEED)

# ---------------------------------------------------------
# Locate project directory created in Stage 02
# ---------------------------------------------------------

def find_project_dir():
    candidates = [
        Path.cwd() / "saudi_labor_law_voice_agent_project",
        Path.cwd().parent / "saudi_labor_law_voice_agent_project",
        Path.home() / "saudi_labor_law_voice_agent_project",
    ]
    for c in candidates:
        if c.exists():
            return c
    # fallback: create inside current directory
    return Path.cwd() / "saudi_labor_law_voice_agent_project"

PROJECT_DIR = find_project_dir()
CLEAN_DIR = PROJECT_DIR / "02_clean"
FINAL_DIR = PROJECT_DIR / "03_final"
CHUNKS_DIR = PROJECT_DIR / "04_chunks"
REPORTS_DIR = PROJECT_DIR / "05_reports"
FIGURES_DIR = REPORTS_DIR / "figures_stage03"
VECTOR_DIR = PROJECT_DIR / "06_vector_db"
CACHE_DIR = PROJECT_DIR / "07_embedding_cache"
STAGE03_DIR = PROJECT_DIR / "08_stage03_rag_results"

for d in [REPORTS_DIR, FIGURES_DIR, VECTOR_DIR, CACHE_DIR, STAGE03_DIR]:
    d.mkdir(parents=True, exist_ok=True)

# ---------------------------------------------------------
# Runtime information
# ---------------------------------------------------------
try:
    import torch
    CUDA_AVAILABLE = torch.cuda.is_available()
    GPU_NAME = torch.cuda.get_device_name(0) if CUDA_AVAILABLE else "CPU"
except Exception:
    CUDA_AVAILABLE = False
    GPU_NAME = "Unknown / CPU"

print("Project directory:", PROJECT_DIR)
print("CUDA available:", CUDA_AVAILABLE)
print("Runtime device:", GPU_NAME)
print("Stage 03 outputs:", STAGE03_DIR)

Project directory: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project
CUDA available: True
Runtime device: NVIDIA GeForce RTX 5090
Stage 03 outputs: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results

In [2]:
# =========================================================
# تنسيق موحّد واحترافي لكل الجداول في النوتبوك
# =========================================================
from IPython.display import HTML, display
display(HTML('''
<style>
table.dataframe { border-collapse: collapse; font-size: 13px; }
table.dataframe th { background-color: #1F4E78; color: #ffffff; padding: 6px 10px; text-align: center; }
table.dataframe td { padding: 6px 10px; border: 1px solid #e2e8f0; }
table.dataframe tr:nth-child(even) { background-color: #f6f9fc; }
</style>
'''))
print('تم تفعيل التنسيق الموحّد للجداول.')

تم تفعيل التنسيق الموحّد للجداول.

<div dir="rtl" style="text-align: right; line-height: 2; font-size: 16px;">

## ملاحظات التشغيل

هذه المرحلة تستخدم الملفات النهائية الناتجة من المرحلة الثانية، خصوصاً:

- قاعدة المعرفة التجريبية بدون تسريب.
- ملف التقييم.
- ملفات المقاطع الناتجة من التقسيم الهيكلي والتقسيم بالحجم الثابت.

إذا ظهر أن أي ملف غير موجود، يجب إعادة تشغيل المرحلة الثانية حتى يتم حفظ الملفات المطلوبة.

</div>

In [3]:
# =========================================================
# خلية تشخيص: هل ملفات المرحلة الثانية موجودة وصحيحة؟
# =========================================================
import pandas as pd

required = {
    "rag_evaluation_dataset.csv": FINAL_DIR / "rag_evaluation_dataset.csv",
    "experiment_kb": FINAL_DIR / "rag_knowledge_base_dataset_experiment_no_leakage.csv",
    "structural_chunks": CHUNKS_DIR / "rag_chunks_structural_legal_experiment.csv",
    "fixed_chunks": CHUNKS_DIR / "rag_chunks_fixed_size_experiment.csv",
}

print("فحص وجود الملفات:")
all_ok = True
for name, path in required.items():
    exists = path.exists()
    all_ok = all_ok and exists
    print(f"  {'موجود ✓' if exists else 'مفقود ✗'} : {name}")
    print(f"      {path}")

# فحص الأعمدة المطلوبة في ملفات المقاطع
need_cols = ["chunk_id", "chunk_text", "parent_document_id", "source_type", "article_status"]
for key in ["structural_chunks", "fixed_chunks"]:
    p = required[key]
    if p.exists():
        cols = pd.read_csv(p, nrows=1, encoding="utf-8-sig").columns.tolist()
        missing = [c for c in need_cols if c not in cols]
        print(f"\n{key}: الأعمدة الناقصة =", missing if missing else "لا شيء، كلها موجودة")

print("\nالخلاصة:", "كل الملفات جاهزة" if all_ok else "فيه ملفات ناقصة، راجعها قبل التشغيل")

فحص وجود الملفات:
  موجود ✓ : rag_evaluation_dataset.csv
      C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\03_final\rag_evaluation_dataset.csv
  موجود ✓ : experiment_kb
      C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\03_final\rag_knowledge_base_dataset_experiment_no_leakage.csv
  موجود ✓ : structural_chunks
      C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\04_chunks\rag_chunks_structural_legal_experiment.csv
  موجود ✓ : fixed_chunks
      C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\04_chunks\rag_chunks_fixed_size_experiment.csv

structural_chunks: الأعمدة الناقصة = لا شيء، كلها موجودة

fixed_chunks: الأعمدة الناقصة = لا شيء، كلها موجودة

الخلاصة: كل الملفات جاهزة

In [4]:

# =========================================================
# Stage 02 - Experiment Configuration
# =========================================================

# Retrieval parameters
TOP_K = 5
TOP_K_LIST = [1, 3, 5]
CANDIDATE_K = 50
HYBRID_ALPHAS = [0.65, 0.80, 0.90]  # alpha = dense weight; 1-alpha = BM25 weight
RERANKER_ALPHA = 0.80

# Control experiment size if needed. Use None for full evaluation.
MAX_EVAL_ROWS = None

# ChromaDB is mandatory in this version.
# Dense retrieval and the dense side of Hybrid retrieval will query ChromaDB directly.
REQUIRE_CHROMADB = True
BUILD_CHROMA_DB = True
REFRESH_CHROMA_COLLECTIONS = True
CHROMA_QUERY_CANDIDATE_K = CANDIDATE_K

# Embedding models to try.
# The code will skip a model if it cannot be loaded.
EMBEDDING_MODELS = [
    {
        "model_key": "e5_large",
        "model_name": "intfloat/multilingual-e5-large",
        "local_path": Path(r"C:/models/multilingual-e5-large"),
        "query_prefix": "query: ",
        "passage_prefix": "passage: ",
    },
    {
        "model_key": "bge_m3",
        "model_name": "BAAI/bge-m3",
        "local_path": Path(r"C:/models/bge-m3"),
        "query_prefix": "",
        "passage_prefix": "",
    },
]

# Optional reranker. If not available, the notebook will still complete Dense/BM25/Hybrid experiments.
RERANKER_CONFIG = {
    "enabled": True,
    "model_key": "bge_reranker_m3",
    "model_name": "BAAI/bge-reranker-v2-m3",
    "local_path": Path(r"C:/models/bge-reranker-v2-m3"),
}

print("TOP_K:", TOP_K)
print("Candidate K:", CANDIDATE_K)
print("Hybrid alphas:", HYBRID_ALPHAS)
print("ChromaDB required:", REQUIRE_CHROMADB)
print("Embedding models requested:", [m["model_key"] for m in EMBEDDING_MODELS])

TOP_K: 5
Candidate K: 50
Hybrid alphas: [0.65, 0.8, 0.9]
ChromaDB required: True
Embedding models requested: ['e5_large', 'bge_m3']

In [5]:
# =========================================================
# Stage 03 - Load Stage 02 Outputs
# تحميل مخرجات Notebook 02 النهائية بطريقة محمية
# =========================================================

from pathlib import Path
import pandas as pd
from IPython.display import display, HTML

# ---------------------------------------------------------
# 0) Academic table styling fallback
# ---------------------------------------------------------
# This fallback prevents NameError if the helper cell was not executed.
# يمنع ظهور الخطأ إذا لم يتم تشغيل خلية دوال التنسيق السابقة.

if "style_academic_table" not in globals():
    def style_academic_table(styler, caption=""):
        """
        Apply a professional academic style to pandas Styler tables.
        This function is intentionally self-contained to avoid execution-order errors.
        """
        if caption:
            try:
                styler = styler.set_caption(caption)
            except Exception:
                pass

        try:
            styler = styler.set_table_styles([
                {
                    "selector": "caption",
                    "props": [
                        ("caption-side", "top"),
                        ("font-size", "16px"),
                        ("font-weight", "bold"),
                        ("color", "#1f4e79"),
                        ("text-align", "left"),
                        ("padding", "8px 0px")
                    ],
                },
                {
                    "selector": "th",
                    "props": [
                        ("background-color", "#1f4e79"),
                        ("color", "white"),
                        ("font-weight", "bold"),
                        ("text-align", "center"),
                        ("border", "1px solid #d9e2ef"),
                        ("padding", "8px")
                    ],
                },
                {
                    "selector": "td",
                    "props": [
                        ("border", "1px solid #d9e2ef"),
                        ("padding", "7px"),
                        ("font-size", "13px"),
                        ("text-align", "center"),
                        ("vertical-align", "middle")
                    ],
                },
                {
                    "selector": "tbody tr:nth-child(even)",
                    "props": [("background-color", "#f7fbff")],
                },
                {
                    "selector": "tbody tr:nth-child(odd)",
                    "props": [("background-color", "#ffffff")],
                },
            ])
        except Exception:
            pass

        def status_color(value):
            value = str(value).upper().strip()
            if value == "PASS":
                return "background-color: #d9ead3; color: #274e13; font-weight: bold;"
            if value == "FAIL":
                return "background-color: #f4cccc; color: #990000; font-weight: bold;"
            if value == "WARN":
                return "background-color: #fff2cc; color: #7f6000; font-weight: bold;"
            if value == "INFO":
                return "background-color: #d9eaf7; color: #1f4e79; font-weight: bold;"
            return ""

        try:
            if hasattr(styler, "data") and "status" in styler.data.columns:
                try:
                    styler = styler.map(status_color, subset=["status"])
                except Exception:
                    styler = styler.applymap(status_color, subset=["status"])
        except Exception:
            pass

        try:
            styler = styler.hide(axis="index")
        except Exception:
            try:
                styler = styler.hide_index()
            except Exception:
                pass

        return styler


# ---------------------------------------------------------
# 1) Safe CSV reader
# ---------------------------------------------------------

def read_csv_utf8(path: Path) -> pd.DataFrame:
    """
    Read a CSV file using UTF-8-SIG encoding.
    Raises a clear error if the required file does not exist.
    """
    path = Path(path)
    if not path.exists():
        raise FileNotFoundError(f"Missing required file: {path}")
    return pd.read_csv(path, encoding="utf-8-sig")


# ---------------------------------------------------------
# 2) Resolve required Notebook 02 output files
# ---------------------------------------------------------

def first_existing_file(logical_name, candidates, required=True):
    """
    Prefer the new strict-evaluation filenames, but allow fallback to legacy names
    with a visible warning so the notebook remains usable with older runs.
    """
    for idx, p in enumerate(candidates):
        p = Path(p)
        if p.exists():
            return {
                "logical_name": logical_name,
                "selected_path": p,
                "preferred_path": Path(candidates[0]),
                "exists": True,
                "used_fallback": idx != 0,
                "status": "PASS" if idx == 0 else "WARN",
                "note": (
                    "Preferred strict file found."
                    if idx == 0
                    else "Fallback file used. Prefer rerunning Notebook 02 Stage 10-13."
                ),
            }

    return {
        "logical_name": logical_name,
        "selected_path": None,
        "preferred_path": Path(candidates[0]),
        "exists": False,
        "used_fallback": False,
        "status": "FAIL" if required else "WARN",
        "note": "Required file is missing." if required else "Optional file is missing.",
    }


# ---------------------------------------------------------
# 3) Required file specification
# ---------------------------------------------------------

required_file_specs = {
    "experiment_kb_active_only": [
        FINAL_DIR / "rag_knowledge_base_dataset_experiment_no_leakage_active_law_only.csv",
        FINAL_DIR / "rag_knowledge_base_dataset_experiment_no_leakage.csv",
    ],
    "retrieval_evaluation_valid_only": [
        FINAL_DIR / "rag_retrieval_evaluation_dataset_valid_only.csv",
        FINAL_DIR / "rag_evaluation_dataset.csv",
    ],
    "structural_chunks": [
        CHUNKS_DIR / "rag_chunks_structural_legal_experiment.csv",
    ],
    "fixed_chunks": [
        CHUNKS_DIR / "rag_chunks_fixed_size_experiment.csv",
    ],
    "repealed_archive": [
        FINAL_DIR / "legal_articles_repealed_archive_not_indexed.csv",
    ],
}


# ---------------------------------------------------------
# 4) Build input manifest
# ---------------------------------------------------------

file_manifest_rows = []
resolved_files = {}

for logical_name, candidates in required_file_specs.items():
    info = first_existing_file(logical_name, candidates, required=True)
    resolved_files[logical_name] = info["selected_path"]
    selected = info["selected_path"]

    file_manifest_rows.append({
        "logical_name": logical_name,
        "preferred_path": str(info["preferred_path"]),
        "selected_path": str(selected) if selected else "",
        "exists": bool(selected and selected.exists()),
        "used_fallback": bool(info["used_fallback"]),
        "size_kb": round(selected.stat().st_size / 1024, 2) if selected and selected.exists() else 0,
        "note": info["note"],
        "status": info["status"],
    })

stage03_file_manifest = pd.DataFrame(file_manifest_rows)

STAGE03_DIR.mkdir(parents=True, exist_ok=True)

stage03_file_manifest.to_csv(
    STAGE03_DIR / "stage03_input_file_manifest.csv",
    index=False,
    encoding="utf-8-sig"
)

try:
    stage03_file_manifest.to_excel(
        STAGE03_DIR / "stage03_input_file_manifest.xlsx",
        index=False
    )
except Exception as e:
    print(f"Warning: Excel export skipped: {e}")


display(HTML("<h3 style='color:#1f4e79'>Stage 03 — Input File Manifest</h3>"))
display(
    style_academic_table(
        stage03_file_manifest.style,
        "Notebook 02 Output Files Used by Notebook 03"
    )
)


# ---------------------------------------------------------
# 5) Stop early if any required file is missing
# ---------------------------------------------------------

missing = stage03_file_manifest[stage03_file_manifest["status"].eq("FAIL")]

assert len(missing) == 0, (
    "Missing Stage 02 output files. Re-run Notebook 02 Stage 10-13 first:\n"
    + "\n".join(missing["preferred_path"].astype(str).tolist())
)


# ---------------------------------------------------------
# 6) Load datasets
# ---------------------------------------------------------

df_kb_experiment = read_csv_utf8(resolved_files["experiment_kb_active_only"])
df_eval = read_csv_utf8(resolved_files["retrieval_evaluation_valid_only"])
df_structural_chunks = read_csv_utf8(resolved_files["structural_chunks"])
df_fixed_chunks = read_csv_utf8(resolved_files["fixed_chunks"])
df_repealed_archive = read_csv_utf8(resolved_files["repealed_archive"])


# ---------------------------------------------------------
# 7) Loaded dataset summary
# ---------------------------------------------------------

loaded_datasets_df = pd.DataFrame([
    {
        "dataset": "Experiment KB active-only",
        "rows": len(df_kb_experiment),
        "columns": df_kb_experiment.shape[1],
        "status": "PASS" if len(df_kb_experiment) else "FAIL",
    },
    {
        "dataset": "Retrieval evaluation valid-only",
        "rows": len(df_eval),
        "columns": df_eval.shape[1],
        "status": "PASS" if len(df_eval) else "FAIL",
    },
    {
        "dataset": "Structural chunks",
        "rows": len(df_structural_chunks),
        "columns": df_structural_chunks.shape[1],
        "status": "PASS" if len(df_structural_chunks) else "FAIL",
    },
    {
        "dataset": "Fixed-size chunks",
        "rows": len(df_fixed_chunks),
        "columns": df_fixed_chunks.shape[1],
        "status": "PASS" if len(df_fixed_chunks) else "FAIL",
    },
    {
        "dataset": "Repealed archive",
        "rows": len(df_repealed_archive),
        "columns": df_repealed_archive.shape[1],
        "status": "INFO",
    },
])

display(HTML("<h3 style='color:#1f4e79'>Stage 03 — Loaded Dataset Summary</h3>"))
display(
    style_academic_table(
        loaded_datasets_df.style,
        "Loaded Dataset Summary"
    )
)


# ---------------------------------------------------------
# 8) Hard safety assertions
# ---------------------------------------------------------

assert len(df_kb_experiment) > 0, "Experiment KB is empty."
assert len(df_eval) > 0, "Evaluation dataset is empty."
assert len(df_structural_chunks) > 0, "Structural chunks file is empty."
assert len(df_fixed_chunks) > 0, "Fixed-size chunks file is empty."


# ---------------------------------------------------------
# 9) Evaluation type distribution
# ---------------------------------------------------------

if "eval_type" in df_eval.columns:
    eval_type_summary = (
        df_eval["eval_type"]
        .fillna("missing")
        .value_counts()
        .rename_axis("eval_type")
        .reset_index(name="count")
    )

    display(HTML("<h3 style='color:#1f4e79'>Stage 03 — Evaluation Type Distribution</h3>"))
    display(
        style_academic_table(
            eval_type_summary.style,
            "Evaluation Dataset Distribution by eval_type"
        )
    )
else:
    print("Warning: eval_type column not found yet; Stage 04 will standardize evaluation schema.")


display(HTML("""
<div style='border-left:6px solid #1f4e79; background:#f7fbff; padding:14px; margin-top:12px'>
<b>Stage 03 Result:</b><br>
All required Notebook 02 files were resolved and loaded successfully.
The retrieval evaluation notebook is ready to continue to schema validation and ChromaDB indexing.
</div>
"""))

### دمج الأسئلة القانونية الذهبية (32 سؤالاً)

تحمّل هذه الخلية مجموعة الأسئلة القانونية الذهبية التي بُنيت يدوياً، وتدمجها في مجموعة التقييم.

بهذا يصبح التقييم القانوني موصولاً، ويستخدم رقم المادة الصحيح في المطابقة.

تُنفَّذ بعد تحميل البيانات مباشرة، وقبل توحيد الأعمدة.

In [6]:
# =========================================================
# دمج الأسئلة القانونية الذهبية (نسخة محمية من التكرار)
# مصدر الأسئلة القانونية الآن هو rag_evaluation_dataset.csv المُثرى في المرحلة الثانية
# لا نضيف ملفاً خارجياً إلا إذا لم تكن هناك أسئلة قانونية أصلاً
# =========================================================

existing_legal = int((df_eval["eval_type"] == "legal_article_retrieval").sum())

if existing_legal > 0:
    print(f"الأسئلة القانونية موجودة مسبقاً في مجموعة التقييم: {existing_legal}")
    print("لن يُدمج أي ملف خارجي، تفاديًا للتكرار.")
else:
    gold_legal_path = FINAL_DIR / "legal_eval_gold.csv"
    if gold_legal_path.exists():
        df_gold_legal = read_csv_utf8(gold_legal_path)
        if "qid" in df_gold_legal.columns and "eval_id" not in df_gold_legal.columns:
            df_gold_legal = df_gold_legal.rename(columns={"qid": "eval_id"})
        df_gold_legal["eval_type"] = "legal_article_retrieval"
        df_gold_legal["is_out_of_scope"] = False
        df_gold_legal["gold_source_type"] = "legal_article"
        df_gold_legal["eval_id"] = df_gold_legal["eval_id"].apply(lambda x: f"legal_{x}")
        df_eval = pd.concat([df_eval, df_gold_legal], ignore_index=True, sort=False)
        print("تم دمج الأسئلة القانونية من الملف الخارجي:", len(df_gold_legal))
    else:
        print("تحذير: لا أسئلة قانونية في التقييم ولا ملف خارجي. راجع المرحلة الثانية.")

print("\nتوزيع أنواع التقييم:")
display(df_eval["eval_type"].value_counts().to_frame("count"))

الأسئلة القانونية موجودة مسبقاً في مجموعة التقييم: 24
لن يُدمج أي ملف خارجي، تفاديًا للتكرار.

توزيع أنواع التقييم:

                         count
eval_type
faq_retrieval              121
legal_article_retrieval     24

In [7]:
# =========================================================
# Stage 04 - Schema Standardization and Safety Checks
# توحيد المخطط وفحوص السلامة قبل الفهرسة
# =========================================================

def first_existing_col(df, candidates):
    for col in candidates:
        if col in df.columns:
            return col
    return None


def normalize_id_value(value):
    if pd.isna(value):
        return ""
    s = str(value).strip()
    if s.lower() in ["nan", "none", "null", "na", "n/a"]:
        return ""
    try:
        f = float(s)
        if f.is_integer():
            return str(int(f))
    except Exception:
        pass
    return s


def ensure_column(df, col, default=""):
    if col not in df.columns:
        df[col] = default
    return df


def coalesce_to_column(df, target, candidates, default=""):
    # pandas 3.x safe: build the coalesced result as a pure object/string Series and
    # assign the whole column once. This avoids LossySetitemError / TypeError that
    # occurs when strings are written into a numeric (float64) column via .loc.
    if target in df.columns:
        result = df[target].fillna("").astype("object").astype(str)
    else:
        result = pd.Series([str(default)] * len(df), index=df.index, dtype="object")
    for c in candidates:
        if c in df.columns:
            mask = result.str.strip().eq("")
            cand = df[c].fillna("").astype("object").astype(str)
            result = result.where(~mask, cand)
    df[target] = result.map(normalize_id_value).astype("object")
    return df


# ---------------------------------------------------------
# 1) Standardize chunk files
# ---------------------------------------------------------
REQUIRED_CHUNK_COLUMNS = [
    "chunk_id", "chunk_text", "parent_document_id", "source_type", "article_status"
]

for name, df_chunks in [("structural", df_structural_chunks), ("fixed", df_fixed_chunks)]:
    # Flexible fallback for text and IDs if a column name changed in Notebook 02
    if "chunk_text" not in df_chunks.columns:
        text_col = first_existing_col(df_chunks, ["text", "content", "retrieval_text", "article_text", "answer"])
        assert text_col is not None, f"{name} chunks missing chunk_text and no fallback text column found."
        df_chunks["chunk_text"] = df_chunks[text_col]

    if "chunk_id" not in df_chunks.columns:
        df_chunks["chunk_id"] = [f"{name.upper()}_{i:06d}" for i in range(len(df_chunks))]

    coalesce_to_column(df_chunks, "parent_document_id", ["document_id", "doc_id", "source_id", "article_id", "faq_id", "chunk_id"], default="")
    ensure_column(df_chunks, "source_type", "")
    ensure_column(df_chunks, "article_status", "active")

    missing_cols = [c for c in REQUIRED_CHUNK_COLUMNS if c not in df_chunks.columns]
    assert not missing_cols, f"{name} chunks missing columns after standardization: {missing_cols}"

# Fill common metadata columns if absent
COMMON_COLUMNS_DEFAULTS = {
    "source_name": "",
    "legal_category": "",
    "article_number": "",
    "article_number_label": "",
    "article_number_int": "",
    "article_title": "",
    "question": "",
    "answer": "",
    "source_url": "",
    "rag_usage": "",
}

for df_chunks in [df_structural_chunks, df_fixed_chunks]:
    for col, default in COMMON_COLUMNS_DEFAULTS.items():
        if col not in df_chunks.columns:
            df_chunks[col] = default
    df_chunks["chunk_text"] = df_chunks["chunk_text"].fillna("").astype(str)
    df_chunks["parent_document_id"] = df_chunks["parent_document_id"].fillna("").astype(str).map(normalize_id_value)
    df_chunks["chunk_id"] = df_chunks["chunk_id"].fillna("").astype(str).map(normalize_id_value)
    df_chunks["source_type"] = df_chunks["source_type"].fillna("").astype(str)
    df_chunks["article_status"] = df_chunks["article_status"].fillna("").astype(str)
    if "chunk_word_len" not in df_chunks.columns:
        df_chunks["chunk_word_len"] = df_chunks["chunk_text"].str.split().apply(len)
    if "chunk_char_len" not in df_chunks.columns:
        df_chunks["chunk_char_len"] = df_chunks["chunk_text"].str.len()

# ---------------------------------------------------------
# 2) Standardize evaluation dataset
# ---------------------------------------------------------
df_eval = coalesce_to_column(
    df_eval,
    "gold_document_unit_id",
    ["gold_document_unit_id", "gold_document_id", "gold_doc_id", "document_id", "parent_document_id", "gold_chunk_id"],
    default=""
)

if "gold_document_unit_ids" not in df_eval.columns:
    df_eval["gold_document_unit_ids"] = df_eval["gold_document_unit_id"]

df_eval = coalesce_to_column(
    df_eval,
    "gold_article_number",
    ["gold_article_number", "article_number", "expected_article_number"],
    default=""
)

if "gold_article_numbers" not in df_eval.columns:
    df_eval["gold_article_numbers"] = df_eval["gold_article_number"]

# Required evaluation columns
for col in [
    "question", "expected_answer", "eval_type", "gold_source_type",
    "gold_document_unit_id", "gold_document_unit_ids", "gold_article_number",
    "gold_article_numbers", "is_out_of_scope"
]:
    if col not in df_eval.columns:
        df_eval[col] = ""

# Normalize eval_type names for downstream code
df_eval["eval_type"] = df_eval["eval_type"].fillna("").astype(str).str.strip()
df_eval.loc[df_eval["eval_type"].eq("legal_article"), "eval_type"] = "legal_article_retrieval"
df_eval.loc[df_eval["eval_type"].eq("faq"), "eval_type"] = "faq_retrieval"
df_eval.loc[df_eval["eval_type"].eq("faq_evaluation"), "eval_type"] = "faq_retrieval"
df_eval.loc[df_eval["eval_type"].eq("legal"), "eval_type"] = "legal_article_retrieval"

# Convert boolean-like out_of_scope values
def to_bool(x):
    return str(x).strip().lower() in ["true", "1", "yes", "y"]

df_eval["is_out_of_scope_bool"] = df_eval["is_out_of_scope"].apply(to_bool)

# ---------------------------------------------------------
# 3) Safety checks: no repealed chunks and no FAQ evaluation leakage
# ---------------------------------------------------------
faq_eval_ids = set(
    df_eval[(df_eval["eval_type"] == "faq_retrieval")]["gold_document_unit_id"]
    .dropna().astype(str).str.strip()
)
faq_eval_ids.discard("")

safety_rows = []
for strategy, df_chunks in [("Structural", df_structural_chunks), ("Fixed-size", df_fixed_chunks)]:
    repealed_chunks = int(((df_chunks["source_type"] == "legal_article") & (df_chunks["article_status"].str.lower() == "repealed")).sum())
    empty_chunks = int((df_chunks["chunk_text"].str.strip() == "").sum())
    duplicated_chunk_ids = int(df_chunks["chunk_id"].duplicated().sum())
    faq_chunk_ids = set(df_chunks[df_chunks["source_type"] == "faq"]["parent_document_id"].dropna().astype(str).str.strip())
    faq_leakage = len(faq_chunk_ids & faq_eval_ids)

    safety_rows.append({
        "chunking_strategy": strategy,
        "chunks": len(df_chunks),
        "empty_chunks": empty_chunks,
        "duplicated_chunk_ids": duplicated_chunk_ids,
        "repealed_legal_chunks": repealed_chunks,
        "faq_evaluation_leakage": faq_leakage,
        "status": "OK" if empty_chunks == 0 and duplicated_chunk_ids == 0 and repealed_chunks == 0 and faq_leakage == 0 else "FAIL",
    })

safety_df = pd.DataFrame(safety_rows)

display(HTML("<h3 style='color:#1f4e79'>Stage 04 — Schema and Safety Checks</h3>"))
display(
    style_academic_table(
        safety_df.style,
        "Chunk Safety Checks"
    )
)

assert (safety_df["status"] == "OK").all(), "Chunk safety checks failed. Review safety_df."

safety_df.to_csv(STAGE03_DIR / "stage03_input_safety_checks.csv", index=False, encoding="utf-8-sig")
try:
    safety_df.to_excel(STAGE03_DIR / "stage03_input_safety_checks.xlsx", index=False)
except Exception:
    pass

eval_schema_summary = pd.DataFrame([
    {"check": "Evaluation rows", "value": len(df_eval), "status": "OK" if len(df_eval) else "FAIL"},
    {"check": "Rows with question", "value": int(df_eval["question"].fillna("").astype(str).str.strip().ne("").sum()), "status": "OK"},
    {"check": "Rows with gold document id", "value": int(df_eval["gold_document_unit_id"].astype(str).str.strip().ne("").sum()), "status": "OK"},
    {"check": "Rows with gold article number", "value": int(df_eval["gold_article_number"].astype(str).str.strip().ne("").sum()), "status": "OK"},
])

display(
    style_academic_table(
        eval_schema_summary.style,
        "Evaluation Schema Summary"
    )
)

<div dir="rtl" style="text-align: right; line-height: 2; font-size: 16px;">

<h3>فحص سلامة المقاطع قبل بناء قاعدة الاسترجاع</h3>

<p>
يوضح هذا الجدول نتائج فحص سلامة المقاطع الناتجة من استراتيجيتي التقسيم المستخدمتين في المشروع: التقسيم الهيكلي 
<span dir="ltr" style="display:inline-block;">Structural Chunking</span>
والتقسيم بالحجم الثابت 
<span dir="ltr" style="display:inline-block;">Fixed-size Chunking</span>.
</p>

<p>
أظهرت النتائج أن التقسيم الهيكلي أنتج 
<strong>793</strong>
مقطعاً، بينما أنتج التقسيم بالحجم الثابت 
<strong>788</strong>
مقطعاً. كما يؤكد الجدول عدم وجود مقاطع فارغة، وعدم وجود معرفات مقاطع مكررة، وعدم وجود مواد قانونية ملغاة داخل المقاطع، وعدم وجود تسريب من أسئلة التقييم إلى قاعدة الفهرسة.
</p>

<p>
تُعد هذه النتيجة مهمة قبل بناء قاعدة المتجهات 
<span dir="ltr" style="display:inline-block;">ChromaDB</span>
لأنها تؤكد أن البيانات التي سيتم إدخالها إلى نظام الاسترجاع نظيفة وآمنة للتقييم. كما أن ظهور الحالة 
<span dir="ltr" style="display:inline-block;">OK</span>
في كلتا الاستراتيجيتين يعني أن المقاطع جاهزة للاستخدام في مرحلة بناء التضمينات وتجارب الاسترجاع.
</p>

<p>
بناءً على هذا الفحص، يمكن الاعتماد على كلتا استراتيجيتي التقسيم في التجارب القادمة، ثم مقارنة أدائهما لاحقاً باستخدام مقاييس الاسترجاع مثل 
<span dir="ltr" style="display:inline-block;">Recall@K</span>
و
<span dir="ltr" style="display:inline-block;">MRR</span>
لتحديد الاستراتيجية الأفضل أكاديمياً وعملياً.
</p>

</div>

<div dir="rtl" style="text-align: right; line-height: 2; font-size: 16px;">

## توحيد البيانات وفحوص السلامة

هذه المرحلة تتأكد من أن ملفات المرحلة الثانية مناسبة للتجارب. أهم فحصين هنا هما:

1. عدم وجود مواد قانونية ملغاة داخل المقاطع التي ستدخل الاسترجاع.
2. عدم وجود أسئلة تقييم الأسئلة الشائعة داخل مقاطع الفهرسة.

أي فشل في هذه الفحوص يعني أن نتائج الاسترجاع لاحقاً قد تكون غير عادلة أو قانونياً غير آمنة.

</div>

In [8]:
# =========================================================
# Stage 05 - Arabic Text Normalization and Tokenization
# =========================================================

AR_DIACRITICS = re.compile(r"[\u0610-\u061A\u064B-\u065F\u0670\u06D6-\u06ED]")
TATWEEL = "ـ"

ARABIC_DIGITS = str.maketrans("٠١٢٣٤٥٦٧٨٩", "0123456789")


def normalize_arabic(text: str) -> str:
    text = "" if pd.isna(text) else str(text)
    text = text.translate(ARABIC_DIGITS)
    text = text.replace(TATWEEL, "")
    text = AR_DIACRITICS.sub("", text)
    text = re.sub(r"[إأآا]", "ا", text)
    text = re.sub(r"ى", "ي", text)
    text = re.sub(r"ة", "ه", text)
    text = re.sub(r"ؤ", "و", text)
    text = re.sub(r"ئ", "ي", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text


def tokenize_arabic(text: str):
    text = normalize_arabic(text)
    # Keep Arabic letters, English letters, and numbers
    text = re.sub(r"[^\u0600-\u06FFa-zA-Z0-9\s]", " ", text)
    tokens = [t for t in text.split() if len(t) > 1]
    return tokens


def extract_numbers(text):
    text = "" if pd.isna(text) else str(text).translate(ARABIC_DIGITS)
    return re.findall(r"\d+", text)


def parse_multi_values(value):
    if pd.isna(value):
        return set()
    text = str(value).strip()
    if not text or text.lower() in ["nan", "none", "null", "na", "n/a"]:
        return set()
    parts = re.split(r"[|,،;/]+", text)
    cleaned = set()
    for p in parts:
        p = p.strip()
        if not p:
            continue
        try:
            f = float(p)
            if f.is_integer():
                p = str(int(f))
        except Exception:
            pass
        cleaned.add(p)
    return cleaned


def parse_gold_document_ids(row):
    """
    Supports both legacy and new Notebook 02 gold-reference names.
    """
    ids = set()
    for col in [
        "gold_document_unit_ids",
        "gold_document_unit_id",
        "gold_document_ids",
        "gold_document_id",
        "gold_doc_id",
        "gold_chunk_id",
        "expected_document_id",
        "parent_document_id",
        "document_id",
    ]:
        if col in row and str(row.get(col, "")).strip():
            ids |= parse_multi_values(row.get(col))
    return ids


def parse_gold_article_numbers(row):
    nums = set()
    for col in ["gold_article_numbers", "gold_article_number", "article_number", "expected_article_number"]:
        if col in row:
            nums |= set(extract_numbers(row.get(col)))
    return nums


display(HTML("<h3 style='color:#1f4e79'>Stage 05 — Arabic Normalization Ready</h3>"))
print("Tokenizer test:", tokenize_arabic("كم مدة فترة التجربة في نظام العمل السعودي؟"))
print("Number extraction test:", extract_numbers("المادة 84، 85"))

Tokenizer test: ['كم', 'مده', 'فتره', 'التجربه', 'في', 'نظام', 'العمل', 'السعودي؟']
Number extraction test: ['84', '85']

<div dir="rtl" style="text-align: right; line-height: 2; font-size: 16px;">

<h3>اختبار دوال المعالجة المساعدة قبل تقييم الاسترجاع</h3>

<p>
في هذه الخطوة تم اختبار مجموعة من الدوال المساعدة التي تُستخدم لاحقاً أثناء تقييم نظام الاسترجاع. تهدف هذه الدوال إلى تجهيز الأسئلة والنصوص العربية، واستخراج المراجع الصحيحة من بيانات التقييم، مثل معرف الوثيقة الصحيح أو رقم المادة القانونية الصحيح.
</p>

<p>
تم اختبار دالة تقسيم النص العربي 
<span dir="ltr" style="display:inline-block;">Arabic Tokenization</span>
على سؤال قانوني باللغة العربية، وأظهرت النتيجة أن السؤال تم تقسيمه إلى كلمات مستقلة بشكل صحيح. هذا مهم لأن بعض طرق الاسترجاع اللفظي مثل 
<span dir="ltr" style="display:inline-block;">BM25</span>
تعتمد على مطابقة الكلمات بين السؤال والمقاطع المخزنة.
</p>

<p>
كما تم اختبار دالة استخراج الأرقام من النصوص، حيث استطاعت الدالة استخراج أرقام المواد القانونية من عبارة مثل 
<span dir="ltr" style="display:inline-block;">المادة 84، 85</span>.
وهذا مهم لأن بعض أسئلة التقييم قد ترتبط بأكثر من مادة قانونية صحيحة، لذلك يجب أن يسمح التقييم بقبول أكثر من مرجع ذهبي للسؤال الواحد.
</p>

<p>
تؤكد نتيجة الاختبار أن الدوال الأساسية تعمل بشكل صحيح قبل استخدامها في حساب مقاييس الاسترجاع مثل 
<span dir="ltr" style="display:inline-block;">Recall@K</span>
و
<span dir="ltr" style="display:inline-block;">MRR</span>.
وبذلك تصبح مرحلة التقييم أكثر دقة لأنها لا تعتمد فقط على النص الظاهر، بل تقارن النتائج المسترجعة مع المراجع الذهبية الصحيحة.
</p>

</div>

<div dir="rtl" style="text-align: right; line-height: 2; font-size: 16px;">

<h3>ملخص Corpus حسب استراتيجية التقسيم</h3>

<p>
يوضح هذا الجدول ملخصاً لحجم البيانات النصية التي سيتم استخدامها في مرحلة الاسترجاع داخل نظام 
<span dir="ltr" style="display:inline-block;">RAG</span>
بعد تطبيق استراتيجيتين مختلفتين للتقسيم: التقسيم الهيكلي 
<span dir="ltr" style="display:inline-block;">Structural</span>
والتقسيم بالحجم الثابت 
<span dir="ltr" style="display:inline-block;">Fixed-size</span>.
</p>

<p>
أنتجت استراتيجية التقسيم الهيكلي 
<strong>793</strong>
وثيقة أو مقطعاً قابلاً للاسترجاع، منها 
<strong>213</strong>
مقطعاً قانونياً و
<strong>580</strong>
مقطعاً من الأسئلة الشائعة. أما استراتيجية التقسيم بالحجم الثابت فأنتجت 
<strong>788</strong>
مقطعاً، منها 
<strong>212</strong>
مقطعاً قانونياً و
<strong>576</strong>
مقطعاً من الأسئلة الشائعة.
</p>

<p>
توضح القيم الخاصة بمتوسط عدد الكلمات أن متوسط طول المقطع في التقسيم الهيكلي بلغ تقريباً 
<strong>81.86</strong>
كلمة، بينما بلغ في التقسيم بالحجم الثابت 
<strong>82.25</strong>
كلمة. وهذا يدل على أن الاستراتيجيتين متقاربتان من حيث متوسط حجم المقاطع.
</p>

<p>
الفرق الأهم يظهر في الحد الأعلى لطول المقاطع 
<span dir="ltr" style="display:inline-block;">max_words</span>.
ففي التقسيم الهيكلي بلغ أطول مقطع 
<strong>350</strong>
كلمة، بينما وصل في التقسيم بالحجم الثابت إلى 
<strong>500</strong>
كلمة. وهذا يشير إلى أن التقسيم الهيكلي أكثر تحكماً في المقاطع الطويلة، وقد يكون أكثر مناسبة للنصوص القانونية لأنه يحافظ على حدود المادة أو السؤال بدلاً من قص النص بناءً على حجم ثابت فقط.
</p>

<p>
بناءً على هذا الملخص، سيتم استخدام كلتا الاستراتيجيتين في تجارب الاسترجاع القادمة ومقارنتهما باستخدام مقاييس مثل 
<span dir="ltr" style="display:inline-block;">Recall@K</span>
و
<span dir="ltr" style="display:inline-block;">MRR</span>
لتحديد أي استراتيجية تقدم أفضل أداء فعلي في استرجاع المادة أو الإجابة الصحيحة.
</p>

</div>

In [9]:
# =========================================================
# Stage 06 - Build Retrieval Corpora
# بناء Corpora جاهزة للتضمين والفهرسة والاسترجاع
# =========================================================

from IPython.display import display, Markdown
import pandas as pd
import numpy as np

# ---------------------------------------------------------
# 1) Build retrieval text
# ---------------------------------------------------------

def build_retrieval_text(row):
    """
    Build a retrieval-ready text field by combining useful metadata
    with the actual chunk_text.

    Important:
    The final retrieval text must be based on chunk_text, not the full
    original answer/article, to preserve the chunking experiment validity.
    """
    source_type = str(row.get("source_type", "")).strip()
    chunk_text = str(row.get("chunk_text", "")).strip()

    parts = []

    if source_type == "legal_article":
        article_number = str(row.get("article_number", "")).strip()
        article_title = str(row.get("article_title", "")).strip()
        bab_title = str(row.get("bab_title", "")).strip()
        fasl = str(row.get("fasl", "")).strip()
        legal_category = str(row.get("legal_category", "")).strip()

        if legal_category:
            parts.append(f"التصنيف القانوني: {legal_category}")
        if bab_title:
            parts.append(f"الباب: {bab_title}")
        if fasl:
            parts.append(f"الفصل: {fasl}")
        if article_number:
            parts.append(f"رقم المادة: {article_number}")
        if article_title:
            parts.append(f"عنوان المادة: {article_title}")

        parts.append("النص القانوني:")
        parts.append(chunk_text)

    elif source_type == "faq":
        question = str(row.get("question", "")).strip()
        legal_category = str(row.get("legal_category", "")).strip()
        sector = str(row.get("sector", "")).strip()
        subsite = str(row.get("subsite", "")).strip()

        if legal_category:
            parts.append(f"التصنيف: {legal_category}")
        if sector:
            parts.append(f"القطاع: {sector}")
        if subsite:
            parts.append(f"الموقع الفرعي: {subsite}")
        if question:
            parts.append(f"السؤال: {question}")

        # Important: use chunk_text, not the full original answer
        parts.append("النص المسترجع:")
        parts.append(chunk_text)

    else:
        parts.append(chunk_text)

    retrieval_text = "\n".join([p for p in parts if str(p).strip()])
    return retrieval_text.strip()
# ---------------------------------------------------------
# 2) Prepare one retrieval corpus
# ---------------------------------------------------------

def prepare_retrieval_corpus(df_chunks, strategy_name):
    """
    Prepare a chunk DataFrame for retrieval experiments.
    Adds:
    - doc_index
    - chunking_strategy_eval
    - retrieval_text
    """
    df = df_chunks.copy().reset_index(drop=True)

    # Ensure required columns exist
    required_cols = [
        "chunk_id",
        "chunk_text",
        "parent_document_id",
        "source_type",
        "article_status"
    ]

    missing_cols = [c for c in required_cols if c not in df.columns]
    assert not missing_cols, f"{strategy_name} corpus missing required columns: {missing_cols}"

    # Fill optional metadata columns if missing
    optional_defaults = {
        "source_name": "",
        "legal_category": "",
        "bab_label": "",
        "bab_title": "",
        "fasl": "",
        "article_title": "",
        "article_number": "",
        "article_number_label": "",
        "article_number_int": "",
        "question": "",
        "answer": "",
        "sector": "",
        "subsite": "",
        "source_url": "",
        "rag_usage": "",
        "chunk_word_len": 0,
        "chunk_char_len": 0,
    }

    for col, default_value in optional_defaults.items():
        if col not in df.columns:
            df[col] = default_value

    # Clean core fields
    df["chunk_id"] = df["chunk_id"].fillna("").astype(str).str.strip()
    df["chunk_text"] = df["chunk_text"].fillna("").astype(str).str.strip()
    df["parent_document_id"] = df["parent_document_id"].fillna("").astype(str).str.strip()
    df["source_type"] = df["source_type"].fillna("").astype(str).str.strip()
    df["article_status"] = df["article_status"].fillna("").astype(str).str.strip()

    # Add doc_index for ChromaDB metadata and result mapping
    if "doc_index" in df.columns:
        df = df.drop(columns=["doc_index"])

    df.insert(0, "doc_index", range(len(df)))

    # Add strategy label
    df["chunking_strategy_eval"] = strategy_name

    # Build retrieval text
    df["retrieval_text"] = df.apply(build_retrieval_text, axis=1)
    df["retrieval_text"] = df["retrieval_text"].fillna("").astype(str).str.strip()

    # Recalculate length fields if needed
    df["chunk_word_len"] = df["chunk_text"].str.split().apply(len)
    df["chunk_char_len"] = df["chunk_text"].str.len()
    df["retrieval_word_len"] = df["retrieval_text"].str.split().apply(len)
    df["retrieval_char_len"] = df["retrieval_text"].str.len()

    # Safety checks
    assert df["chunk_id"].duplicated().sum() == 0, f"Duplicate chunk_id found in {strategy_name} corpus."
    assert (df["chunk_id"].str.strip() == "").sum() == 0, f"Empty chunk_id found in {strategy_name} corpus."
    assert (df["chunk_text"].str.strip() == "").sum() == 0, f"Empty chunk_text found in {strategy_name} corpus."
    assert (df["retrieval_text"].str.strip() == "").sum() == 0, f"Empty retrieval_text found in {strategy_name} corpus."
    assert (df["parent_document_id"].str.strip() == "").sum() == 0, f"Missing parent_document_id found in {strategy_name} corpus."

    repealed_count = int(
        (
            (df["source_type"] == "legal_article") &
            (df["article_status"] == "repealed")
        ).sum()
    )

    assert repealed_count == 0, f"Repealed legal chunks found in {strategy_name} corpus."

    return df


# ---------------------------------------------------------
# 3) Build CORPORA dictionary
# ---------------------------------------------------------

df_structural_corpus = prepare_retrieval_corpus(
    df_structural_chunks,
    strategy_name="structural"
)

df_fixed_corpus = prepare_retrieval_corpus(
    df_fixed_chunks,
    strategy_name="fixed_size"
)

CORPORA = {
    "structural": df_structural_corpus,
    "fixed_size": df_fixed_corpus,
}


# ---------------------------------------------------------
# 4) Professional Corpus Summary
# ---------------------------------------------------------

def status_badge(condition):
    return "PASS" if condition else "FAIL"


def highlight_status(value):
    if value in ["PASS", "OK"]:
        return "background-color: #DCFCE7; color: #166534; font-weight: bold; text-align: center;"
    if value == "WARN":
        return "background-color: #FEF3C7; color: #92400E; font-weight: bold; text-align: center;"
    if value == "FAIL":
        return "background-color: #FEE2E2; color: #991B1B; font-weight: bold; text-align: center;"
    return ""


def style_academic_table(styler, caption):
    return (
        styler
        .set_caption(caption)
        .set_properties(**{
            "text-align": "left",
            "white-space": "normal",
            "font-size": "12px",
            "vertical-align": "top"
        })
        .set_table_styles([
            {
                "selector": "caption",
                "props": [
                    ("caption-side", "top"),
                    ("font-size", "16px"),
                    ("font-weight", "bold"),
                    ("text-align", "left"),
                    ("color", "#1F2937"),
                    ("padding", "8px")
                ]
            },
            {
                "selector": "th",
                "props": [
                    ("background-color", "#F3F4F6"),
                    ("color", "#111827"),
                    ("font-weight", "bold"),
                    ("text-align", "center"),
                    ("border", "1px solid #D1D5DB"),
                    ("padding", "6px")
                ]
            },
            {
                "selector": "td",
                "props": [
                    ("border", "1px solid #E5E7EB"),
                    ("padding", "6px")
                ]
            }
        ])
    )


corpus_summary_rows = []
corpus_safety_rows = []

for corpus_name, corpus_df in CORPORA.items():
    total_records = int(len(corpus_df))
    legal_chunks = int((corpus_df["source_type"] == "legal_article").sum())
    faq_chunks = int((corpus_df["source_type"] == "faq").sum())

    empty_retrieval_text = int((corpus_df["retrieval_text"].str.strip() == "").sum())
    missing_parent_document_id = int((corpus_df["parent_document_id"].str.strip() == "").sum())
    duplicated_chunk_id = int(corpus_df["chunk_id"].duplicated().sum())

    repealed_legal_chunks = int(
        (
            (corpus_df["source_type"] == "legal_article") &
            (corpus_df["article_status"] == "repealed")
        ).sum()
    )

    mean_words = round(float(corpus_df["retrieval_word_len"].mean()), 2)
    median_words = round(float(corpus_df["retrieval_word_len"].median()), 2)
    max_words = int(corpus_df["retrieval_word_len"].max())

    corpus_status = (
        empty_retrieval_text == 0 and
        missing_parent_document_id == 0 and
        duplicated_chunk_id == 0 and
        repealed_legal_chunks == 0
    )

    corpus_summary_rows.append({
        "Chunking Strategy": corpus_name,
        "Total Records": total_records,
        "Legal Article Chunks": legal_chunks,
        "FAQ Chunks": faq_chunks,
        "Legal %": round((legal_chunks / total_records) * 100, 2) if total_records else 0,
        "FAQ %": round((faq_chunks / total_records) * 100, 2) if total_records else 0,
        "Mean Retrieval Words": mean_words,
        "Median Retrieval Words": median_words,
        "Max Retrieval Words": max_words,
        "Status": "PASS" if corpus_status else "FAIL",
        "Interpretation": (
            "Corpus is ready for embeddings and ChromaDB indexing."
            if corpus_status
            else "Corpus requires review before retrieval evaluation."
        )
    })

    corpus_safety_rows.extend([
        {
            "Chunking Strategy": corpus_name,
            "Safety Check": "Empty retrieval_text",
            "Value": empty_retrieval_text,
            "Expected": 0,
            "Status": status_badge(empty_retrieval_text == 0),
            "Interpretation": "Every chunk must have retrieval-ready text."
        },
        {
            "Chunking Strategy": corpus_name,
            "Safety Check": "Missing parent_document_id",
            "Value": missing_parent_document_id,
            "Expected": 0,
            "Status": status_badge(missing_parent_document_id == 0),
            "Interpretation": "Every chunk must remain linked to its original source document."
        },
        {
            "Chunking Strategy": corpus_name,
            "Safety Check": "Duplicated chunk_id",
            "Value": duplicated_chunk_id,
            "Expected": 0,
            "Status": status_badge(duplicated_chunk_id == 0),
            "Interpretation": "Each chunk must have a unique identifier."
        },
        {
            "Chunking Strategy": corpus_name,
            "Safety Check": "Repealed legal chunks",
            "Value": repealed_legal_chunks,
            "Expected": 0,
            "Status": status_badge(repealed_legal_chunks == 0),
            "Interpretation": "Repealed legal provisions must not be indexed for retrieval."
        }
    ])


corpus_summary = pd.DataFrame(corpus_summary_rows)
corpus_safety_df = pd.DataFrame(corpus_safety_rows)


# ---------------------------------------------------------
# 5) Save summary files
# ---------------------------------------------------------

corpus_summary_path = STAGE03_DIR / "corpus_summary_by_chunking_strategy.csv"
corpus_summary_xlsx_path = STAGE03_DIR / "corpus_summary_by_chunking_strategy.xlsx"
corpus_safety_path = STAGE03_DIR / "corpus_safety_checks_by_chunking_strategy.csv"
corpus_safety_xlsx_path = STAGE03_DIR / "corpus_safety_checks_by_chunking_strategy.xlsx"

corpus_summary.to_csv(
    corpus_summary_path,
    index=False,
    encoding="utf-8-sig"
)

corpus_summary.to_excel(
    corpus_summary_xlsx_path,
    index=False
)

corpus_safety_df.to_csv(
    corpus_safety_path,
    index=False,
    encoding="utf-8-sig"
)

corpus_safety_df.to_excel(
    corpus_safety_xlsx_path,
    index=False
)


# ---------------------------------------------------------
# 6) Display professional output tables
# ---------------------------------------------------------

display(Markdown("## Stage 06 Output Summary — Retrieval Corpora"))

display(Markdown(
    """
This stage prepares two retrieval corpora from the generated chunks.  
Each corpus is enriched with retrieval-ready text and metadata before being used for embeddings, ChromaDB indexing, and retrieval evaluation.
"""
))


# Main summary table
summary_styler = (
    corpus_summary
    .style
    .format({
        "Total Records": "{:,}",
        "Legal Article Chunks": "{:,}",
        "FAQ Chunks": "{:,}",
        "Legal %": "{:.2f}%",
        "FAQ %": "{:.2f}%",
        "Mean Retrieval Words": "{:.2f}",
        "Median Retrieval Words": "{:.2f}",
        "Max Retrieval Words": "{:,}"
    })
    .map(highlight_status, subset=["Status"])
)

display(
    style_academic_table(
        summary_styler,
        "Retrieval Corpora Prepared for Embedding and ChromaDB"
    )
)


# Safety table
display(Markdown("## Corpus Safety Checks"))

safety_styler = (
    corpus_safety_df
    .style
    .format({
        "Value": "{:,}",
        "Expected": "{:,}"
    })
    .map(highlight_status, subset=["Status"])
)

display(
    style_academic_table(
        safety_styler,
        "Safety Validation for Retrieval Corpora"
    )
)


# ---------------------------------------------------------
# 7) Corpus composition table
# ---------------------------------------------------------

display(Markdown("## Corpus Composition by Source Type"))

composition_rows = []

for corpus_name, corpus_df in CORPORA.items():
    source_counts = corpus_df["source_type"].value_counts()

    for source_type, count in source_counts.items():
        composition_rows.append({
            "Chunking Strategy": corpus_name,
            "Source Type": source_type,
            "Records": int(count),
            "Percentage": round((count / len(corpus_df)) * 100, 2) if len(corpus_df) else 0
        })

composition_df = pd.DataFrame(composition_rows)

composition_styler = (
    composition_df
    .style
    .format({
        "Records": "{:,}",
        "Percentage": "{:.2f}%"
    })
)

display(
    style_academic_table(
        composition_styler,
        "Retrieval Corpus Composition"
    )
)


# ---------------------------------------------------------
# 8) Saved files manifest
# ---------------------------------------------------------

display(Markdown("## Saved Output Files"))

saved_files_df = pd.DataFrame([
    {
        "File Type": "Corpus Summary - CSV",
        "Path": str(corpus_summary_path),
        "Purpose": "Summary of retrieval corpora by chunking strategy."
    },
    {
        "File Type": "Corpus Summary - Excel",
        "Path": str(corpus_summary_xlsx_path),
        "Purpose": "Readable Excel version of corpus summary."
    },
    {
        "File Type": "Corpus Safety Checks - CSV",
        "Path": str(corpus_safety_path),
        "Purpose": "Detailed safety checks for each retrieval corpus."
    },
    {
        "File Type": "Corpus Safety Checks - Excel",
        "Path": str(corpus_safety_xlsx_path),
        "Purpose": "Readable Excel version of corpus safety checks."
    }
])

display(
    style_academic_table(
        saved_files_df.style,
        "Stage 06 Saved Output Files"
    )
)


# ---------------------------------------------------------
# 9) Preview retrieval text samples
# ---------------------------------------------------------

display(Markdown("## Preview — Retrieval Text Samples"))

preview_rows = []

for corpus_name, corpus_df in CORPORA.items():
    sample_df = corpus_df.head(3).copy()

    for _, row in sample_df.iterrows():
        text_preview = str(row.get("retrieval_text", ""))[:300].replace("\n", " ")

        preview_rows.append({
            "Chunking Strategy": corpus_name,
            "Chunk ID": row.get("chunk_id", ""),
            "Source Type": row.get("source_type", ""),
            "Parent Document ID": row.get("parent_document_id", ""),
            "Retrieval Text Preview": text_preview + ("..." if len(str(row.get("retrieval_text", ""))) > 300 else "")
        })

preview_df = pd.DataFrame(preview_rows)

display(
    style_academic_table(
        preview_df.style,
        "Sample Retrieval Text Records"
    )
)


# ---------------------------------------------------------
# 10) Final completion message
# ---------------------------------------------------------

print("Stage 06 completed successfully.")
print("CORPORA object is ready.")
print("Available corpora:", list(CORPORA.keys()))

for corpus_name, corpus_df in CORPORA.items():
    print(f"{corpus_name}: {corpus_df.shape}")

print("\nSaved output files:")
print(corpus_summary_path)
print(corpus_summary_xlsx_path)
print(corpus_safety_path)
print(corpus_safety_xlsx_path)

## Stage 06 Output Summary — Retrieval Corpora

This stage prepares two retrieval corpora from the generated chunks.
Each corpus is enriched with retrieval-ready text and metadata before being used for embeddings, ChromaDB indexing, and retrieval evaluation.

## Corpus Safety Checks

## Corpus Composition by Source Type

## Saved Output Files

## Preview — Retrieval Text Samples

Stage 06 completed successfully.
CORPORA object is ready.
Available corpora: ['structural', 'fixed_size']
structural: (490, 33)
fixed_size: (490, 33)

Saved output files:
C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\corpus_summary_by_chunking_strategy.csv
C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\corpus_summary_by_chunking_strategy.xlsx
C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\corpus_safety_checks_by_chunking_strategy.csv
C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\corpus_safety_checks_by_chunking_strategy.xlsx

In [10]:
# =========================================================
# Stage 07 - Dependency Check and Model Loading on GPU
# فحص المتطلبات وتحميل نماذج Embedding و Reranker على GPU
# =========================================================

from pathlib import Path
import gc
import torch

# ---------------------------------------------------------
# 1) Device Check
# ---------------------------------------------------------

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

print("=" * 90)
print("Stage 07 - Dependency Check and Model Loading")
print("=" * 90)
print("Selected device:", DEVICE)

if torch.cuda.is_available():
    print("GPU Name:", torch.cuda.get_device_name(0))
    print("CUDA Version:", torch.version.cuda)
    print("Initial CUDA allocated GB:", round(torch.cuda.memory_allocated() / 1024**3, 2))
    print("Initial CUDA reserved GB:", round(torch.cuda.memory_reserved() / 1024**3, 2))
else:
    print("CUDA is not available. Models will run on CPU.")

# ---------------------------------------------------------
# 2) Dependency Check
# ---------------------------------------------------------

try:
    from sentence_transformers import SentenceTransformer, CrossEncoder
    SENTENCE_TRANSFORMERS_AVAILABLE = True
    print("✅ sentence-transformers is available.")
except Exception as e:
    SENTENCE_TRANSFORMERS_AVAILABLE = False
    SentenceTransformer = None
    CrossEncoder = None
    raise ImportError(
        "sentence-transformers is required for Stage 03. "
        "Install it inside your Jupyter environment before running this notebook."
    ) from e

try:
    import chromadb
    CHROMADB_AVAILABLE = True
    print("✅ ChromaDB is available.")
except Exception as e:
    CHROMADB_AVAILABLE = False
    chromadb = None
    if REQUIRE_CHROMADB:
        raise ImportError(
            "ChromaDB is mandatory in this Stage 03 notebook. "
            "Install it using: pip install chromadb"
        ) from e

# ---------------------------------------------------------
# 3) Memory Helpers
# ---------------------------------------------------------

def cleanup_memory():
    gc.collect()

    if torch.cuda.is_available():
        try:
            torch.cuda.empty_cache()
            torch.cuda.ipc_collect()
        except Exception:
            pass


def show_cuda_memory(label="CUDA Memory"):
    print("-" * 90)
    print(label)

    if torch.cuda.is_available():
        print("Allocated GB:", round(torch.cuda.memory_allocated() / 1024**3, 2))
        print("Reserved GB:", round(torch.cuda.memory_reserved() / 1024**3, 2))
        print("Max allocated GB:", round(torch.cuda.max_memory_allocated() / 1024**3, 2))
    else:
        print("CUDA is not available.")

    print("-" * 90)

# ---------------------------------------------------------
# 4) Resolve Model Path
# ---------------------------------------------------------

def resolve_model_path(config):
    """
    Resolve local model path if available; otherwise use model_name.
    """

    local_path = config.get("local_path", None)

    if local_path is not None:
        local_path = Path(str(local_path))

        if local_path.exists():
            return str(local_path)

        print(f"⚠️ Local path not found for {config.get('model_key', 'unknown')}: {local_path}")

    model_name = config.get("model_name", None)

    if model_name is None:
        raise ValueError(f"Model config has neither local_path nor model_name: {config}")

    return str(model_name)

# ---------------------------------------------------------
# 5) Load Embedding Model
# ---------------------------------------------------------

def load_embedding_model(config):
    """
    Load SentenceTransformer embedding model on GPU if CUDA is available.
    """

    model_path = resolve_model_path(config)

    print("=" * 90)
    print(f"Loading embedding model [{config['model_key']}]:")
    print("Path:", model_path)
    print("Device:", DEVICE)
    print("=" * 90)

    model = SentenceTransformer(
        model_path,
        device=DEVICE
    )

    # تقليل الذاكرة وتسريع التضمين
    model.max_seq_length = 512

    return model

# ---------------------------------------------------------
# 6) Load Embedding Models
# ---------------------------------------------------------

cleanup_memory()

loaded_embedding_models = {}

print("=" * 90)
print("Embedding model configs:")
print(EMBEDDING_MODELS)
print("=" * 90)

for cfg in EMBEDDING_MODELS:
    try:
        model_key = cfg["model_key"]

        model = load_embedding_model(cfg)

        loaded_embedding_models[model_key] = {
            "config": cfg,
            "model": model,
        }

        print("✅ Loaded embedding model:", model_key)
        show_cuda_memory(f"CUDA memory after loading embedding model: {model_key}")

    except Exception as e:
        print("⚠️ Skipped embedding model:", cfg.get("model_key", "unknown"))
        print("Reason:", repr(e))

# ---------------------------------------------------------
# 7) Load Reranker on GPU
# ---------------------------------------------------------

reranker_model = None

if RERANKER_CONFIG["enabled"]:
    try:
        local_path = RERANKER_CONFIG.get("local_path", None)
        model_name = RERANKER_CONFIG.get("model_name", None)

        if local_path is not None and Path(str(local_path)).exists():
            reranker_path = str(Path(str(local_path)))
        elif model_name is not None:
            reranker_path = str(model_name)
        else:
            raise ValueError("RERANKER_CONFIG must contain local_path or model_name.")

        print("=" * 90)
        print("Loading reranker:")
        print("Path:", reranker_path)
        print("Device:", DEVICE)
        print("=" * 90)

        reranker_model = CrossEncoder(
            reranker_path,
            device=DEVICE,
            max_length=512
        )

        print("✅ Reranker loaded successfully.")
        show_cuda_memory("CUDA memory after loading reranker")

    except Exception as e:
        reranker_model = None
        print("⚠️ Reranker skipped:", repr(e))
else:
    print("Reranker is disabled in RERANKER_CONFIG.")

# ---------------------------------------------------------
# 8) Final Checks
# ---------------------------------------------------------

print("=" * 90)
print("Loaded embedding models object:")
print(loaded_embedding_models)

print("\nLoaded embedding model keys:")
print(list(loaded_embedding_models.keys()))

print("\nReranker loaded:")
print(reranker_model is not None)

print("\nChromaDB available:")
print(CHROMADB_AVAILABLE)

print("=" * 90)

assert len(loaded_embedding_models) > 0, (
    "No embedding model could be loaded. "
    "Check EMBEDDING_MODELS local_path values or model names."
)

assert CHROMADB_AVAILABLE, (
    "ChromaDB must be available before continuing."
)

print("✅ Mandatory ChromaDB check passed.")
print("✅ Stage 07 completed successfully.")
show_cuda_memory("Final CUDA memory status after Stage 07")

==========================================================================================
Stage 07 - Dependency Check and Model Loading
==========================================================================================
Selected device: cuda
GPU Name: NVIDIA GeForce RTX 5090
CUDA Version: 12.8
Initial CUDA allocated GB: 0.0
Initial CUDA reserved GB: 0.0

✅ sentence-transformers is available.

✅ ChromaDB is available.
==========================================================================================
Embedding model configs:
[{'model_key': 'e5_large', 'model_name': 'intfloat/multilingual-e5-large', 'local_path': WindowsPath('C:/models/multilingual-e5-large'), 'query_prefix': 'query: ', 'passage_prefix': 'passage: '}, {'model_key': 'bge_m3', 'model_name': 'BAAI/bge-m3', 'local_path': WindowsPath('C:/models/bge-m3'), 'query_prefix': '', 'passage_prefix': ''}]
==========================================================================================
==========================================================================================
Loading embedding model [e5_large]:
Path: C:\models\multilingual-e5-large
Device: cuda
==========================================================================================

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

Loading weights: 100%|██████████| 391/391 [00:00<00:00, 14417.98it/s]

✅ Loaded embedding model: e5_large
------------------------------------------------------------------------------------------
CUDA memory after loading embedding model: e5_large
Allocated GB: 2.09
Reserved GB: 2.1
Max allocated GB: 2.09
------------------------------------------------------------------------------------------
==========================================================================================
Loading embedding model [bge_m3]:
Path: C:\models\bge-m3
Device: cuda
==========================================================================================

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

Loading weights: 100%|██████████| 391/391 [00:00<00:00, 36153.81it/s]

✅ Loaded embedding model: bge_m3
------------------------------------------------------------------------------------------
CUDA memory after loading embedding model: bge_m3
Allocated GB: 4.2
Reserved GB: 4.21
Max allocated GB: 4.2
------------------------------------------------------------------------------------------
==========================================================================================
Loading reranker:
Path: C:\models\bge-reranker-v2-m3
Device: cuda
==========================================================================================

Loading weights:   0%|          | 0/393 [00:00<?, ?it/s]

Loading weights: 100%|██████████| 393/393 [00:00<00:00, 11026.35it/s]

✅ Reranker loaded successfully.
------------------------------------------------------------------------------------------
CUDA memory after loading reranker
Allocated GB: 6.32
Reserved GB: 6.33
Max allocated GB: 6.32
------------------------------------------------------------------------------------------
==========================================================================================
Loaded embedding models object:
{'e5_large': {'config': {'model_key': 'e5_large', 'model_name': 'intfloat/multilingual-e5-large', 'local_path': WindowsPath('C:/models/multilingual-e5-large'), 'query_prefix': 'query: ', 'passage_prefix': 'passage: '}, 'model': SentenceTransformer(
  (0): Transformer({'transformer_task': 'feature-extraction', 'modality_config': {'text': {'method': 'forward', 'method_output_name': 'last_hidden_state'}}, 'module_output_name': 'token_embeddings', 'architecture': 'XLMRobertaModel'})
  (1): Pooling({'embedding_dimension': 1024, 'pooling_mode': 'mean', 'include_prompt': True})
  (2): Normalize({})
)}, 'bge_m3': {'config': {'model_key': 'bge_m3', 'model_name': 'BAAI/bge-m3', 'local_path': WindowsPath('C:/models/bge-m3'), 'query_prefix': '', 'passage_prefix': ''}, 'model': SentenceTransformer(
  (0): Transformer({'transformer_task': 'feature-extraction', 'modality_config': {'text': {'method': 'forward', 'method_output_name': 'last_hidden_state'}}, 'module_output_name': 'token_embeddings', 'architecture': 'XLMRobertaModel'})
  (1): Pooling({'embedding_dimension': 1024, 'pooling_mode': 'cls', 'include_prompt': True})
  (2): Normalize({})
)}}

Loaded embedding model keys:
['e5_large', 'bge_m3']

Reranker loaded:
True

ChromaDB available:
True
==========================================================================================
✅ Mandatory ChromaDB check passed.
✅ Stage 07 completed successfully.
------------------------------------------------------------------------------------------
Final CUDA memory status after Stage 07
Allocated GB: 6.32
Reserved GB: 6.33
Max allocated GB: 6.32
------------------------------------------------------------------------------------------

In [11]:
print("Loaded embedding models object:")
print(loaded_embedding_models)

print("\nKeys:")
print(list(loaded_embedding_models.keys()))

print("\nReranker loaded:")
print(reranker_model is not None)

Loaded embedding models object:
{'e5_large': {'config': {'model_key': 'e5_large', 'model_name': 'intfloat/multilingual-e5-large', 'local_path': WindowsPath('C:/models/multilingual-e5-large'), 'query_prefix': 'query: ', 'passage_prefix': 'passage: '}, 'model': SentenceTransformer(
  (0): Transformer({'transformer_task': 'feature-extraction', 'modality_config': {'text': {'method': 'forward', 'method_output_name': 'last_hidden_state'}}, 'module_output_name': 'token_embeddings', 'architecture': 'XLMRobertaModel'})
  (1): Pooling({'embedding_dimension': 1024, 'pooling_mode': 'mean', 'include_prompt': True})
  (2): Normalize({})
)}, 'bge_m3': {'config': {'model_key': 'bge_m3', 'model_name': 'BAAI/bge-m3', 'local_path': WindowsPath('C:/models/bge-m3'), 'query_prefix': '', 'passage_prefix': ''}, 'model': SentenceTransformer(
  (0): Transformer({'transformer_task': 'feature-extraction', 'modality_config': {'text': {'method': 'forward', 'method_output_name': 'last_hidden_state'}}, 'module_output_name': 'token_embeddings', 'architecture': 'XLMRobertaModel'})
  (1): Pooling({'embedding_dimension': 1024, 'pooling_mode': 'cls', 'include_prompt': True})
  (2): Normalize({})
)}}

Keys:
['e5_large', 'bge_m3']

Reranker loaded:
True

<div dir="rtl" style="text-align: right; line-height: 2; font-size: 16px;">

<h3>تحميل نماذج التضمين والتحقق من جاهزية ChromaDB</h3>

<p>
توضح هذه الخطوة أنه تم تحميل نماذج التضمين المستخدمة في مرحلة الاسترجاع بنجاح، وهي نموذج 
<span dir="ltr" style="display:inline-block;">multilingual-e5-large</span>
ونموذج 
<span dir="ltr" style="display:inline-block;">bge-m3</span>.
تُستخدم هذه النماذج لتحويل المقاطع النصية والأسئلة إلى تمثيلات رقمية 
<span dir="ltr" style="display:inline-block;">Embeddings</span>
يمكن مقارنتها دلالياً داخل نظام الاسترجاع.
</p>

<p>
كما تم تحميل نموذج إعادة الترتيب 
<span dir="ltr" style="display:inline-block;">bge-reranker-v2-m3</span>
بنجاح. وظيفة هذا النموذج هي إعادة ترتيب النتائج المرشحة بعد الاسترجاع الأولي، بحيث يتم رفع المقاطع الأكثر ارتباطاً بالسؤال إلى المراتب الأولى.
</p>

<p>
بالإضافة إلى ذلك، تم تنفيذ فحص إلزامي للتأكد من توفر 
<span dir="ltr" style="display:inline-block;">ChromaDB</span>
قبل متابعة بناء قاعدة المتجهات. ظهور الرسالة 
<span dir="ltr" style="display:inline-block;">Mandatory ChromaDB check passed</span>
يعني أن مكتبة 
<span dir="ltr" style="display:inline-block;">ChromaDB</span>
مثبتة وجاهزة للاستخدام، وأن المرحلة التالية يمكن أن تبني مجموعات المتجهات وتخزن المقاطع داخل قاعدة بيانات متجهية فعلية.
</p>

<p>
هذه الخطوة مهمة لأنها تمثل نقطة الانتقال من البيانات النصية النظيفة إلى طبقة الاسترجاع الدلالي. بعد نجاحها، يصبح بالإمكان توليد التضمينات، تخزينها داخل 
<span dir="ltr" style="display:inline-block;">ChromaDB</span>
ثم تنفيذ تجارب الاسترجاع باستخدام 
<span dir="ltr" style="display:inline-block;">Dense Retrieval</span>
و
<span dir="ltr" style="display:inline-block;">Hybrid Retrieval</span>
وإعادة الترتيب.
</p>

</div>

<div dir="rtl" style="text-align: right; line-height: 2; font-size: 16px;">

## نماذج التضمين وإعادة الترتيب

يستخدم النوتبوك نماذج تضمين متعددة اللغات مناسبة للنص العربي. إذا توفر نموذجان مثل
<span dir="ltr" style="display:inline-block;">multilingual-e5-large</span>
و
<span dir="ltr" style="display:inline-block;">bge-m3</span>
فسيتم تقييمهما معاً. وإذا تعذر تحميل أحد النماذج، يتم تخطيه وتسجيل السبب دون إيقاف التجربة كاملة.

</div>

In [12]:
# =========================================================
# Stage 08 - Embedding Cache and Encoding Functions
# =========================================================


def safe_key(text: str) -> str:
    return re.sub(r"[^a-zA-Z0-9_\-]+", "_", str(text))


def format_passages(texts, cfg):
    prefix = cfg.get("passage_prefix", "")
    return [prefix + str(t) for t in texts]


def format_query(query, cfg):
    prefix = cfg.get("query_prefix", "")
    return prefix + str(query)


def l2_normalize(x: np.ndarray) -> np.ndarray:
    norms = np.linalg.norm(x, axis=1, keepdims=True)
    norms[norms == 0] = 1.0
    return x / norms


def encode_texts(model, texts, batch_size=32, show_progress_bar=True):
    emb = model.encode(
        texts,
        batch_size=batch_size,
        show_progress_bar=show_progress_bar,
        convert_to_numpy=True,
        normalize_embeddings=True,
    )
    emb = np.asarray(emb, dtype="float32")
    return emb


def get_embeddings_for_corpus(model_key, model_info, corpus_name, corpus_df):
    cfg = model_info["config"]
    model = model_info["model"]
    cache_path = CACHE_DIR / f"embeddings_{safe_key(corpus_name)}_{safe_key(model_key)}.npy"
    meta_path = CACHE_DIR / f"embeddings_{safe_key(corpus_name)}_{safe_key(model_key)}.json"

    expected_hash = hashlib.sha256("||".join(corpus_df["retrieval_text"].astype(str).tolist()).encode("utf-8")).hexdigest()

    if cache_path.exists() and meta_path.exists():
        try:
            meta = json.loads(meta_path.read_text(encoding="utf-8"))
            if meta.get("corpus_hash") == expected_hash and meta.get("rows") == len(corpus_df):
                print(f"Loaded cached embeddings: {cache_path.name}")
                return np.load(cache_path)
        except Exception:
            pass

    passages = format_passages(corpus_df["retrieval_text"].tolist(), cfg)
    print(f"Encoding corpus [{corpus_name}] with model [{model_key}] | rows={len(passages)}")
    emb = encode_texts(model, passages, batch_size=16, show_progress_bar=True)
    np.save(cache_path, emb)
    meta_path.write_text(json.dumps({
        "model_key": model_key,
        "model_name": cfg["model_name"],
        "corpus_name": corpus_name,
        "rows": len(corpus_df),
        "dimensions": int(emb.shape[1]),
        "corpus_hash": expected_hash,
    }, ensure_ascii=False, indent=2), encoding="utf-8")
    print("Saved embeddings:", cache_path)
    return emb

# Build embeddings for all model/corpus combinations
EMBEDDING_STORE = {}
for corpus_name, corpus_df in CORPORA.items():
    EMBEDDING_STORE[corpus_name] = {}
    for model_key, model_info in loaded_embedding_models.items():
        EMBEDDING_STORE[corpus_name][model_key] = get_embeddings_for_corpus(
            model_key, model_info, corpus_name, corpus_df
        )

print("Embedding store ready.")
for corpus_name in EMBEDDING_STORE:
    for model_key, emb in EMBEDDING_STORE[corpus_name].items():
        print(corpus_name, model_key, emb.shape)

Loaded cached embeddings: embeddings_structural_e5_large.npy
Loaded cached embeddings: embeddings_structural_bge_m3.npy
Loaded cached embeddings: embeddings_fixed_size_e5_large.npy
Loaded cached embeddings: embeddings_fixed_size_bge_m3.npy
Embedding store ready.
structural e5_large (490, 1024)
structural bge_m3 (490, 1024)
fixed_size e5_large (490, 1024)
fixed_size bge_m3 (490, 1024)

In [13]:
# =========================================================
# Professional Embedding Summary Table
# جدول احترافي لنتائج توليد التضمينات
# =========================================================

import pandas as pd
import numpy as np
from IPython.display import display, HTML
from pathlib import Path

# ---------------------------------------------------------
# تحديد مجلد حفظ التضمينات بطريقة آمنة
# ---------------------------------------------------------

if "EMBEDDING_CACHE_DIR" in globals():
    embedding_cache_dir = EMBEDDING_CACHE_DIR
elif "EMBED_CACHE_DIR" in globals():
    embedding_cache_dir = EMBED_CACHE_DIR
else:
    embedding_cache_dir = PROJECT_DIR / "07_embedding_cache"

embedding_cache_dir = Path(embedding_cache_dir)

# ---------------------------------------------------------
# بناء جدول ملخص التضمينات
# ---------------------------------------------------------

embedding_summary_rows = []

for corpus_name, model_dict in EMBEDDING_STORE.items():
    for model_key, emb in model_dict.items():
        emb_array = np.asarray(emb)

        documents_count = emb_array.shape[0]
        vector_dimension = emb_array.shape[1] if emb_array.ndim == 2 else None
        estimated_memory_mb = round(emb_array.nbytes / (1024 ** 2), 2)

        cache_file = embedding_cache_dir / f"embeddings_{corpus_name}_{model_key}.npy"

        embedding_summary_rows.append({
            "Chunking Strategy": corpus_name,
            "Embedding Model": model_key,
            "Documents / Chunks": documents_count,
            "Vector Dimension": vector_dimension,
            "Embedding Matrix Shape": str(emb_array.shape),
            "Estimated Memory MB": estimated_memory_mb,
            "Cache File": cache_file.name,
            "Cache Saved": "Yes" if cache_file.exists() else "No",
            "Status": "OK" if documents_count > 0 and vector_dimension is not None else "Check",
        })

embedding_summary_df = pd.DataFrame(embedding_summary_rows)

embedding_summary_df = embedding_summary_df.sort_values(
    by=["Chunking Strategy", "Embedding Model"]
).reset_index(drop=True)

# ---------------------------------------------------------
# حفظ التقرير
# ---------------------------------------------------------

embedding_summary_df.to_csv(
    STAGE03_DIR / "embedding_generation_summary.csv",
    index=False,
    encoding="utf-8-sig"
)

embedding_summary_df.to_excel(
    STAGE03_DIR / "embedding_generation_summary.xlsx",
    index=False
)

# ---------------------------------------------------------
# عرض عنوان احترافي
# ---------------------------------------------------------

display(HTML("""
<div dir="rtl" style="text-align:right; line-height:2; font-size:17px;">
<h3>ملخص توليد التضمينات النصية</h3>
<p>
يوضح الجدول التالي نتائج تحويل المقاطع النصية إلى متجهات رقمية دلالية باستخدام نماذج التضمين المختلفة.
يعرض الجدول عدد المقاطع، أبعاد المتجهات، حجم الذاكرة التقريبي، وحالة حفظ ملفات التضمين في مجلد الكاش.
</p>
</div>
"""))

# ---------------------------------------------------------
# تنسيق احترافي للجدول
# ---------------------------------------------------------

styled_embedding_summary = (
    embedding_summary_df.style
    .set_caption("Embedding Generation Summary")
    .format({
        "Documents / Chunks": "{:,.0f}",
        "Vector Dimension": "{:,.0f}",
        "Estimated Memory MB": "{:,.2f}",
    })
    .set_table_styles([
        {
            "selector": "caption",
            "props": [
                ("caption-side", "top"),
                ("font-size", "18px"),
                ("font-weight", "bold"),
                ("text-align", "center"),
                ("padding", "10px"),
            ],
        },
        {
            "selector": "th",
            "props": [
                ("font-weight", "bold"),
                ("text-align", "center"),
                ("background-color", "#F2F2F2"),
                ("border", "1px solid #CCCCCC"),
                ("padding", "8px"),
            ],
        },
        {
            "selector": "td",
            "props": [
                ("text-align", "center"),
                ("border", "1px solid #DDDDDD"),
                ("padding", "8px"),
            ],
        },
        {
            "selector": "table",
            "props": [
                ("border-collapse", "collapse"),
                ("width", "100%"),
                ("font-size", "14px"),
            ],
        },
    ])
    .map(
        lambda v: "background-color: #DFF2E1; font-weight: bold;" if v == "OK" else "",
        subset=["Status"]
    )
    .map(
        lambda v: "background-color: #DFF2E1; font-weight: bold;" if v == "Yes" else "background-color: #F8D7DA;",
        subset=["Cache Saved"]
    )
)

display(styled_embedding_summary)

print("Embedding summary saved to:")
print(STAGE03_DIR / "embedding_generation_summary.csv")
print(STAGE03_DIR / "embedding_generation_summary.xlsx")

Embedding summary saved to:
C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\embedding_generation_summary.csv
C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\embedding_generation_summary.xlsx

### تفسير نتائج توليد التضمينات النصية

يعرض الجدول السابق ملخصًا لمرحلة توليد التضمينات النصية (Embedding Generation)، وهي المرحلة التي تم فيها تحويل المقاطع النصية الناتجة من استراتيجيات التقسيم إلى متجهات رقمية دلالية قابلة للتخزين والاسترجاع داخل قاعدة المتجهات ChromaDB.

تم تنفيذ هذه العملية على استراتيجيتي التقسيم المستخدمتين في المشروع، وهما **Structural Chunking** و **Fixed-size Chunking Baseline**، كما تم استخدام نموذجين للتضمين النصي هما **bge-m3** و **multilingual-e5-large**. وبذلك تم إنتاج أربع مجموعات من التضمينات، بحيث يمكن لاحقًا مقارنة أثر كل استراتيجية تقسيم وكل نموذج تضمين على جودة الاسترجاع.

أظهرت النتائج أن عدد المقاطع في استراتيجية **Fixed-size Chunking** بلغ 719 مقطعًا، بينما بلغ عدد المقاطع في استراتيجية **Structural Chunking** عدد 722 مقطعًا. وقد تم توليد التضمينات لكل هذه المقاطع باستخدام النموذجين المختارين.

يشير عمود **Vector Dimension** إلى عدد الأبعاد في كل متجه تمثيلي. وقد أظهرت النتائج أن كلا النموذجين ينتجان متجهات ذات 1024 بُعدًا. على سبيل المثال، الشكل `(719, 1024)` يعني أن هناك 719 مقطعًا، وكل مقطع تم تمثيله بمتجه رقمي مكوّن من 1024 بُعدًا. وبالمثل، الشكل `(722, 1024)` يعني أن هناك 722 مقطعًا تم تحويلها إلى متجهات دلالية بنفس عدد الأبعاد.

كما يوضح عمود **Estimated Memory MB** الحجم التقريبي لمصفوفة التضمينات في الذاكرة. وقد بلغ الحجم التقريبي 2.81 ميغابايت لمصفوفات استراتيجية **Fixed-size Chunking**، و2.82 ميغابايت لمصفوفات استراتيجية **Structural Chunking**. ويُعد هذا الحجم مناسبًا جدًا للتجارب المحلية، كما أنه يؤكد أن حجم البيانات في هذه المرحلة قابل للإدارة بكفاءة داخل بيئة Jupyter وChromaDB.

يوضح عمود **Cache Saved** أن جميع ملفات التضمينات تم حفظها بنجاح بصيغة `.npy`. وتعد هذه الخطوة مهمة لأنها تسمح بإعادة استخدام التضمينات لاحقًا دون الحاجة إلى إعادة توليدها في كل مرة يتم فيها تشغيل النوتبوك. وهذا يقلل زمن التنفيذ، ويجعل التجارب اللاحقة أكثر استقرارًا وقابلية للتكرار.

كما يشير ظهور الحالة **OK** في جميع الصفوف إلى أن عملية توليد التضمينات تمت بنجاح لجميع التركيبات، دون وجود مشاكل في عدد المقاطع أو أبعاد المتجهات أو حفظ ملفات التضمينات.

بناءً على هذه النتائج، أصبحت التضمينات النصية جاهزة للاستخدام في المرحلة التالية، وهي بناء مجموعات ChromaDB وتنفيذ تجارب الاسترجاع. وستُستخدم هذه التضمينات لاحقًا لمقارنة أداء نماذج التضمين واستراتيجيات التقسيم باستخدام مقاييس تقييم مثل Recall@1 وRecall@3 وRecall@5 وMRR وnDCG@5 وزمن الاستجابة.

### الملفات الناتجة من هذه المرحلة

نتج عن هذه المرحلة حفظ ملفات التضمينات الخاصة بكل تركيبة من استراتيجية التقسيم ونموذج التضمين، إضافة إلى ملفات ملخص النتائج. وتشمل المخرجات الرئيسية:

* `embeddings_fixed_size_bge_m3.npy`
* `embeddings_fixed_size_e5_large.npy`
* `embeddings_structural_bge_m3.npy`
* `embeddings_structural_e5_large.npy`
* `embedding_generation_summary.csv`
* `embedding_generation_summary.xlsx`

تمثل هذه الملفات الأساس العملي للمرحلة التالية من المشروع، حيث سيتم استخدامها لبناء قاعدة المتجهات ChromaDB وتقييم جودة الاسترجاع الدلالي والهجين.

In [14]:

# =========================================================
# Stage 09 - Mandatory Persistent ChromaDB Vector Database
# =========================================================

# In this version, ChromaDB is not optional.
# The vector database is built and then used directly in dense retrieval experiments.

assert CHROMADB_AVAILABLE, "ChromaDB is mandatory but not available."
assert BUILD_CHROMA_DB, "BUILD_CHROMA_DB must be True in this ChromaDB-based stage."


def sanitize_metadata(row):
    allowed = {}
    for col in [
        "doc_index", "chunking_strategy_eval", "chunk_id", "parent_document_id", "source_type", "source_name",
        "article_number", "article_number_label", "article_number_int", "article_status",
        "article_title", "legal_category", "source_url", "rag_usage", "chunk_word_len", "chunk_char_len"
    ]:
        value = row.get(col, "")
        if pd.isna(value):
            value = ""
        # Chroma metadata supports str, int, float, bool. Store all as simple values.
        if col in ["doc_index", "chunk_word_len", "chunk_char_len"]:
            try:
                allowed[col] = int(value)
            except Exception:
                allowed[col] = 0
        else:
            allowed[col] = str(value)
    return allowed


def collection_name_for(corpus_name, model_key):
    # Keep name deterministic and short enough for Chroma.
    return f"rag_{safe_key(corpus_name)}_{safe_key(model_key)}"[:60]

client = chromadb.PersistentClient(path=str(VECTOR_DIR))
CHROMA_COLLECTIONS = {}
chroma_manifest_rows = []

for corpus_name, corpus_df in CORPORA.items():
    CHROMA_COLLECTIONS[corpus_name] = {}
    for model_key, emb in EMBEDDING_STORE[corpus_name].items():
        collection_name = collection_name_for(corpus_name, model_key)

        if REFRESH_CHROMA_COLLECTIONS:
            try:
                client.delete_collection(collection_name)
                print("Deleted old collection:", collection_name)
            except Exception:
                pass

        collection = client.get_or_create_collection(
            name=collection_name,
            metadata={
                "hnsw:space": "cosine",
                "project": "saudi_labor_law_voice_agent",
                "stage": "stage03_rag_retrieval",
                "corpus": corpus_name,
                "embedding_model": model_key,
            },
        )

        ids = corpus_df["chunk_id"].astype(str).tolist()
        assert len(ids) == len(set(ids)), f"Duplicate chunk_id values found in {corpus_name}. Chroma IDs must be unique."

        docs = corpus_df["retrieval_text"].fillna("").astype(str).tolist()
        metas = [sanitize_metadata(row) for _, row in corpus_df.iterrows()]
        vectors = np.asarray(emb, dtype="float32").tolist()

        batch_size = 128
        for start in range(0, len(ids), batch_size):
            end = start + batch_size
            collection.upsert(
                ids=ids[start:end],
                documents=docs[start:end],
                metadatas=metas[start:end],
                embeddings=vectors[start:end],
            )

        count_after = collection.count()
        assert count_after == len(ids), (
            f"Chroma count mismatch for {collection_name}: "
            f"expected {len(ids)}, got {count_after}"
        )

        CHROMA_COLLECTIONS[corpus_name][model_key] = collection
        chroma_manifest_rows.append({
            "corpus": corpus_name,
            "model_key": model_key,
            "collection_name": collection_name,
            "records_expected": len(ids),
            "records_in_chroma": count_after,
            "vector_db_path": str(VECTOR_DIR),
            "status": "OK",
        })
        print("✅ Chroma collection ready:", collection_name, "records:", count_after)

chroma_manifest = pd.DataFrame(chroma_manifest_rows)
assert not chroma_manifest.empty, "No ChromaDB collections were created."
assert (chroma_manifest["status"] == "OK").all(), "Some ChromaDB collections failed."

chroma_manifest.to_csv(STAGE03_DIR / "chroma_collections_manifest.csv", index=False, encoding="utf-8-sig")
chroma_manifest.to_excel(STAGE03_DIR / "chroma_collections_manifest.xlsx", index=False)
with open(STAGE03_DIR / "chroma_collections_manifest.json", "w", encoding="utf-8") as f:
    json.dump(chroma_manifest.to_dict(orient="records"), f, ensure_ascii=False, indent=2)

display(chroma_manifest)
print("Mandatory ChromaDB build completed successfully.")

Deleted old collection: rag_structural_e5_large

✅ Chroma collection ready: rag_structural_e5_large records: 490
Deleted old collection: rag_structural_bge_m3

✅ Chroma collection ready: rag_structural_bge_m3 records: 490
Deleted old collection: rag_fixed_size_e5_large

✅ Chroma collection ready: rag_fixed_size_e5_large records: 490
Deleted old collection: rag_fixed_size_bge_m3

✅ Chroma collection ready: rag_fixed_size_bge_m3 records: 490

,corpus,model_key,collection_name,records_expected,records_in_chroma,vector_db_path,status
0,structural,e5_large,rag_structural_e5_large,490,490,C:\Users\PC\Desktop\data collection code\saudi...,OK
1,structural,bge_m3,rag_structural_bge_m3,490,490,C:\Users\PC\Desktop\data collection code\saudi...,OK
2,fixed_size,e5_large,rag_fixed_size_e5_large,490,490,C:\Users\PC\Desktop\data collection code\saudi...,OK
3,fixed_size,bge_m3,rag_fixed_size_bge_m3,490,490,C:\Users\PC\Desktop\data collection code\saudi...,OK

Mandatory ChromaDB build completed successfully.

In [15]:

# =========================================================
# Stage 10 - ChromaDB Dense, BM25, Hybrid, and Reranker Retrieval
# =========================================================

class SimpleBM25:
    def __init__(self, k1=1.5, b=0.75):
        self.k1 = k1
        self.b = b
        self.corpus_tokens = []
        self.doc_len = []
        self.avgdl = 0.0
        self.idf = {}

    def fit(self, texts):
        self.corpus_tokens = [tokenize_arabic(t) for t in texts]
        self.doc_len = [len(toks) for toks in self.corpus_tokens]
        self.avgdl = float(np.mean(self.doc_len)) if self.doc_len else 1.0
        df = Counter()
        for toks in self.corpus_tokens:
            for term in set(toks):
                df[term] += 1
        n = len(self.corpus_tokens)
        self.idf = {term: math.log((n - freq + 0.5) / (freq + 0.5) + 1.0) for term, freq in df.items()}

    def score_one(self, query_tokens, doc_idx):
        toks = self.corpus_tokens[doc_idx]
        tf = Counter(toks)
        dl = self.doc_len[doc_idx] if self.doc_len else 0
        score = 0.0
        for term in query_tokens:
            if term not in self.idf:
                continue
            f = tf.get(term, 0)
            denom = f + self.k1 * (1 - self.b + self.b * dl / (self.avgdl or 1.0))
            score += self.idf[term] * (f * (self.k1 + 1)) / (denom or 1.0)
        return score

    def scores(self, query):
        q_tokens = tokenize_arabic(query)
        return np.array([self.score_one(q_tokens, i) for i in range(len(self.corpus_tokens))], dtype="float32")


def minmax_norm(scores):
    scores = np.asarray(scores, dtype="float32")
    if scores.size == 0:
        return scores
    mn, mx = float(scores.min()), float(scores.max())
    if mx - mn < 1e-9:
        return np.zeros_like(scores)
    return (scores - mn) / (mx - mn)


def minmax_dict(score_dict, keys):
    values = np.array([float(score_dict.get(k, 0.0)) for k in keys], dtype="float32")
    norm_values = minmax_norm(values)
    return {k: float(v) for k, v in zip(keys, norm_values)}


def build_bm25_indexes():
    bm25_indexes = {}
    for corpus_name, corpus_df in CORPORA.items():
        bm25 = SimpleBM25()
        bm25.fit(corpus_df["retrieval_text"].tolist())
        bm25_indexes[corpus_name] = bm25
    return bm25_indexes

BM25_INDEXES = build_bm25_indexes()


def make_result(corpus_df, idx, score, rank, extra=None):
    row = corpus_df.iloc[int(idx)]
    result = {
        "rank": int(rank),
        "doc_index": int(idx),
        "score": float(score),
        "chunk_id": str(row.get("chunk_id", "")),
        "parent_document_id": str(row.get("parent_document_id", "")),
        "source_type": str(row.get("source_type", "")),
        "article_number_int": str(row.get("article_number_int", "")),
        "article_number_label": str(row.get("article_number_label", "")),
        "article_title": str(row.get("article_title", "")),
        "question": str(row.get("question", "")),
        "text": str(row.get("retrieval_text", "")),
    }
    if extra:
        result.update(extra)
    return result


def chroma_distance_to_similarity(distance):
    # With hnsw:space='cosine', Chroma returns a cosine distance.
    # Higher score is better, so similarity = 1 - distance.
    try:
        return float(1.0 - float(distance))
    except Exception:
        return 0.0


def encode_query_for_model(query, model_key):
    model_info = loaded_embedding_models[model_key]
    cfg = model_info["config"]
    model = model_info["model"]
    q_text = format_query(query, cfg)
    return encode_texts(model, [q_text], batch_size=1, show_progress_bar=False)[0]


def chroma_dense_retrieve(query, corpus_name, model_key, top_k=5):
    assert corpus_name in CHROMA_COLLECTIONS, f"Missing Chroma corpus: {corpus_name}"
    assert model_key in CHROMA_COLLECTIONS[corpus_name], f"Missing Chroma collection for {corpus_name}/{model_key}"

    corpus_df = CORPORA[corpus_name]
    collection = CHROMA_COLLECTIONS[corpus_name][model_key]
    q_emb = encode_query_for_model(query, model_key)

    query_result = collection.query(
        query_embeddings=[q_emb.astype(float).tolist()],
        n_results=min(top_k, collection.count()),
        include=["documents", "metadatas", "distances"],
    )

    ids = query_result.get("ids", [[]])[0]
    docs = query_result.get("documents", [[]])[0]
    metas = query_result.get("metadatas", [[]])[0]
    distances = query_result.get("distances", [[]])[0]

    results = []
    for rank, (item_id, doc, meta, distance) in enumerate(zip(ids, docs, metas, distances), start=1):
        doc_index = int(meta.get("doc_index", -1)) if meta else -1
        if doc_index < 0 or doc_index >= len(corpus_df):
            # Rare fallback if metadata is not available.
            matches = corpus_df.index[corpus_df["chunk_id"].astype(str) == str(item_id)].tolist()
            doc_index = int(matches[0]) if matches else 0
        score = chroma_distance_to_similarity(distance)
        results.append(make_result(corpus_df, doc_index, score, rank, extra={
            "retrieval_backend": "chromadb",
            "chroma_collection": collection.name,
            "chroma_id": str(item_id),
            "chroma_distance": float(distance),
            "dense_score": float(score),
        }))
    return results


def dense_retrieve(query, corpus_name, model_key, top_k=5):
    # Mandatory dense retrieval through ChromaDB.
    return chroma_dense_retrieve(query, corpus_name, model_key, top_k=top_k)


def bm25_retrieve(query, corpus_name, top_k=5):
    corpus_df = CORPORA[corpus_name]
    scores = BM25_INDEXES[corpus_name].scores(query)
    idxs = np.argsort(-scores)[:top_k]
    return [make_result(corpus_df, i, scores[i], rank + 1, extra={"retrieval_backend": "bm25"}) for rank, i in enumerate(idxs)]


def hybrid_retrieve(query, corpus_name, model_key, alpha=0.80, top_k=5, candidate_k=50):
    corpus_df = CORPORA[corpus_name]

    # Dense candidates must come from ChromaDB.
    dense_candidates = chroma_dense_retrieve(
        query=query,
        corpus_name=corpus_name,
        model_key=model_key,
        top_k=min(candidate_k, len(corpus_df)),
    )
    dense_score_map = {int(r["doc_index"]): float(r.get("dense_score", r.get("score", 0.0))) for r in dense_candidates}

    # BM25 candidates are lexical candidates.
    bm25_scores = BM25_INDEXES[corpus_name].scores(query)
    bm25_top_idxs = np.argsort(-bm25_scores)[:candidate_k].astype(int).tolist()
    bm25_score_map = {int(i): float(bm25_scores[int(i)]) for i in bm25_top_idxs}

    candidate_idxs = sorted(set(dense_score_map.keys()) | set(bm25_score_map.keys()))
    dense_norm = minmax_dict(dense_score_map, candidate_idxs)
    bm25_norm = minmax_dict(bm25_score_map, candidate_idxs)

    fused_rows = []
    for i in candidate_idxs:
        fused = float(alpha) * dense_norm.get(i, 0.0) + (1.0 - float(alpha)) * bm25_norm.get(i, 0.0)
        fused_rows.append((i, fused))

    fused_rows = sorted(fused_rows, key=lambda x: x[1], reverse=True)[:top_k]

    return [
        make_result(corpus_df, i, fused, rank + 1, extra={
            "retrieval_backend": "chromadb+bm25",
            "dense_score": float(dense_score_map.get(i, 0.0)),
            "bm25_score": float(bm25_score_map.get(i, 0.0)),
            "dense_norm": float(dense_norm.get(i, 0.0)),
            "bm25_norm": float(bm25_norm.get(i, 0.0)),
            "alpha": float(alpha),
        })
        for rank, (i, fused) in enumerate(fused_rows)
    ]


def hybrid_rerank_retrieve(query, corpus_name, model_key, alpha=0.80, top_k=5, candidate_k=50):
    candidates = hybrid_retrieve(query, corpus_name, model_key, alpha=alpha, top_k=candidate_k, candidate_k=candidate_k)
    if reranker_model is None or len(candidates) == 0:
        return candidates[:top_k]
    pairs = [[query, r["text"]] for r in candidates]
    rerank_scores = reranker_model.predict(pairs)
    for r, s in zip(candidates, rerank_scores):
        r["rerank_score"] = float(s)
        r["retrieval_backend"] = "chromadb+bm25+reranker"
    candidates = sorted(candidates, key=lambda x: x["rerank_score"], reverse=True)[:top_k]
    for rank, r in enumerate(candidates, start=1):
        r["rank"] = rank
        r["score"] = r.get("rerank_score", r.get("score", 0.0))
    return candidates

print("Retrieval functions ready. Dense retrieval is executed through ChromaDB.")

Retrieval functions ready. Dense retrieval is executed through ChromaDB.

In [16]:
# =========================================================
# Stage 11 - Evaluation Metrics
# =========================================================

def result_is_relevant(eval_row, result):
    gold_doc_ids = parse_gold_document_ids(eval_row)
    gold_article_nums = parse_gold_article_numbers(eval_row)

    result_parent = str(result.get("parent_document_id", "")).strip()
    if result_parent and result_parent in gold_doc_ids:
        return True

    # For legal article questions, allow article-number matching as backup
    result_nums = set(extract_numbers(result.get("article_number_int", ""))) | set(extract_numbers(result.get("article_number_label", "")))
    if gold_article_nums and result_nums and len(gold_article_nums & result_nums) > 0:
        return True

    return False


def relevance_vector(eval_row, results, k=5):
    rel = []
    for r in results[:k]:
        rel.append(1 if result_is_relevant(eval_row, r) else 0)
    while len(rel) < k:
        rel.append(0)
    return rel


def reciprocal_rank(rel):
    for i, v in enumerate(rel, start=1):
        if v:
            return 1.0 / i
    return 0.0


def dcg_at_k(rel):
    return sum((2**v - 1) / math.log2(i + 2) for i, v in enumerate(rel))


def ndcg_at_k(rel):
    ideal = sorted(rel, reverse=True)
    ideal_dcg = dcg_at_k(ideal)
    if ideal_dcg == 0:
        return 0.0
    return dcg_at_k(rel) / ideal_dcg


def summarize_eval_rows(detail_df, label_cols):
    if detail_df.empty:
        return pd.DataFrame()
    group_cols = label_cols
    summary = (
        detail_df.groupby(group_cols)
        .agg(
            questions=("eval_id", "count"),
            recall_at_1=("hit_at_1", "mean"),
            recall_at_3=("hit_at_3", "mean"),
            recall_at_5=("hit_at_5", "mean"),
            mrr=("rr", "mean"),
            ndcg_at_5=("ndcg_at_5", "mean"),
            avg_latency_sec=("latency_sec", "mean"),
        )
        .reset_index()
    )
    for c in ["recall_at_1", "recall_at_3", "recall_at_5", "mrr", "ndcg_at_5", "avg_latency_sec"]:
        summary[c] = summary[c].round(4)
    return summary

print("Metric functions ready.")

Metric functions ready.

In [17]:
# =========================================================
# Stage 12 - Build Evaluation Subsets
# بناء مجموعة التقييم النهائية للاسترجاع
# =========================================================

# In-scope retrieval evaluation only: FAQ + legal article retrieval.
df_eval_in_scope = df_eval[~df_eval["is_out_of_scope_bool"]].copy()

accepted_eval_types = [
    "faq_retrieval",
    "legal_article_retrieval",
    "faq",
    "legal_article",
    "legal",
    "article_retrieval",
]

df_eval_in_scope = df_eval_in_scope[
    df_eval_in_scope["eval_type"].astype(str).str.strip().isin(accepted_eval_types)
].copy()

# Normalize again after filtering
df_eval_in_scope.loc[df_eval_in_scope["eval_type"].isin(["faq", "faq_evaluation"]), "eval_type"] = "faq_retrieval"
df_eval_in_scope.loc[df_eval_in_scope["eval_type"].isin(["legal", "legal_article", "article_retrieval"]), "eval_type"] = "legal_article_retrieval"


def has_gold(row):
    return bool(parse_gold_document_ids(row) or parse_gold_article_numbers(row))


# Verify gold references exist in at least one corpus
indexed_parent_ids = set()
indexed_chunk_ids = set()
indexed_article_numbers = set()

for _, corpus_df in CORPORA.items():
    if "parent_document_id" in corpus_df.columns:
        indexed_parent_ids |= set(corpus_df["parent_document_id"].dropna().astype(str).str.strip())
    if "chunk_id" in corpus_df.columns:
        indexed_chunk_ids |= set(corpus_df["chunk_id"].dropna().astype(str).str.strip())
    for c in ["article_number", "article_number_int", "article_number_label"]:
        if c in corpus_df.columns:
            for v in corpus_df[c].dropna().astype(str):
                indexed_article_numbers |= set(extract_numbers(v))

indexed_parent_ids.discard("")
indexed_chunk_ids.discard("")


def gold_available(row):
    gold_doc_ids = parse_gold_document_ids(row)
    gold_article_nums = parse_gold_article_numbers(row)

    doc_ok = bool(gold_doc_ids & (indexed_parent_ids | indexed_chunk_ids))
    article_ok = bool(gold_article_nums & indexed_article_numbers)
    return doc_ok or article_ok


df_eval_in_scope["has_gold"] = df_eval_in_scope.apply(has_gold, axis=1)
df_eval_in_scope["gold_available_in_index"] = df_eval_in_scope.apply(gold_available, axis=1)

missing_gold = df_eval_in_scope[~df_eval_in_scope["has_gold"]].copy()
gold_not_available = df_eval_in_scope[df_eval_in_scope["has_gold"] & ~df_eval_in_scope["gold_available_in_index"]].copy()

eval_readiness = pd.DataFrame([
    {"check": "In-scope evaluation rows", "value": len(df_eval_in_scope), "status": "OK" if len(df_eval_in_scope) else "FAIL"},
    {"check": "Rows missing gold reference", "value": len(missing_gold), "status": "OK" if len(missing_gold) == 0 else "WARN"},
    {"check": "Gold references not available in index", "value": len(gold_not_available), "status": "OK" if len(gold_not_available) == 0 else "FAIL"},
])

display(HTML("<h3 style='color:#1f4e79'>Stage 12 — Evaluation Readiness</h3>"))
display(
    style_academic_table(
        eval_readiness.style,
        "Evaluation Dataset Readiness Checks"
    )
)

display(df_eval_in_scope["eval_type"].value_counts().to_frame("count"))

if len(missing_gold) > 0:
    missing_gold.to_csv(STAGE03_DIR / "stage03_eval_missing_gold_reference.csv", index=False, encoding="utf-8-sig")

if len(gold_not_available) > 0:
    gold_not_available.to_csv(STAGE03_DIR / "stage03_eval_gold_not_available_in_index.csv", index=False, encoding="utf-8-sig")

# ---------------------------------------------------------
# Held-out FAQ design reconciliation (no-leakage aware)
# ---------------------------------------------------------
# By design in Notebook 02, FAQ records used for EVALUATION are deliberately kept
# OUT of the indexed knowledge base to prevent question leakage. Their gold document
# is therefore NOT retrievable from the index BY DESIGN -- this is expected and is
# NOT a data error. We separate such by-design held-out FAQ rows from genuine
# missing-gold problems (e.g. legal articles that SHOULD be indexed but are not).
faq_like_types = ["faq_retrieval", "faq", "faq_evaluation"]
is_faq_row = gold_not_available["eval_type"].astype(str).str.strip().isin(faq_like_types)
faq_heldout_not_indexed = gold_not_available[is_faq_row].copy()
genuine_gold_not_available = gold_not_available[~is_faq_row].copy()

if len(faq_heldout_not_indexed) > 0:
    faq_heldout_not_indexed.to_csv(
        STAGE03_DIR / "stage03_faq_heldout_not_indexed_by_design.csv",
        index=False, encoding="utf-8-sig"
    )

print("=" * 90)
print("Held-out FAQ reconciliation (no-leakage design from Notebook 02):")
print(f"  FAQ eval rows held out of index BY DESIGN : {len(faq_heldout_not_indexed)}")
print(f"  Genuine missing-from-index gold (errors)  : {len(genuine_gold_not_available)}")
print("  -> Held-out FAQ rows are excluded from retrieval metrics and kept for the")
print("     generation stage (Notebook 04). Retrieval is evaluated only on rows whose")
print("     gold IS in the index (legal articles + any in-index FAQ).")
print("=" * 90)

# Rows actually usable for RETRIEVAL evaluation: gold must be present in the index.
df_eval_retrievable = df_eval_in_scope[df_eval_in_scope["gold_available_in_index"]].copy()

display(HTML(
    "<div style='border-left:6px solid #1f4e79; background:#f7fbff; padding:12px; margin-top:10px'>"
    f"<b>Retrieval-evaluable rows:</b> {len(df_eval_retrievable)} "
    f"(of {len(df_eval_in_scope)} in-scope). "
    f"{len(faq_heldout_not_indexed)} held-out FAQ rows excluded from retrieval metrics by no-leakage design."
    "</div>"
))

assert len(df_eval_retrievable) > 0, "No retrieval-evaluable rows found (gold present in index)."
assert len(missing_gold) == 0, "Some in-scope evaluation rows have no gold references at all."
assert len(genuine_gold_not_available) == 0, (
    "Some NON-held-out gold references are missing from the indexed CORPORA. "
    "Check stage03_eval_gold_not_available_in_index.csv"
)

if MAX_EVAL_ROWS is not None:
    df_eval_run = df_eval_retrievable.sample(n=min(MAX_EVAL_ROWS, len(df_eval_retrievable)), random_state=RANDOM_SEED).reset_index(drop=True)
else:
    df_eval_run = df_eval_retrievable.reset_index(drop=True)

df_eval_run.to_csv(STAGE03_DIR / "stage03_final_runnable_evaluation_dataset.csv", index=False, encoding="utf-8-sig")
try:
    df_eval_run.to_excel(STAGE03_DIR / "stage03_final_runnable_evaluation_dataset.xlsx", index=False)
except Exception:
    pass

print("Rows used in retrieval evaluation:", len(df_eval_run))

                         count
eval_type
faq_retrieval              121
legal_article_retrieval     24

==========================================================================================
Held-out FAQ reconciliation (no-leakage design from Notebook 02):
  FAQ eval rows held out of index BY DESIGN : 121
  Genuine missing-from-index gold (errors)  : 0
  -> Held-out FAQ rows are excluded from retrieval metrics and kept for the
     generation stage (Notebook 04). Retrieval is evaluated only on rows whose
     gold IS in the index (legal articles + any in-index FAQ).
==========================================================================================

Rows used in retrieval evaluation: 24

In [18]:
# =========================================================
# GPU Acceleration Check before Stage 13 - Robust Version
# تجهيز GPU قبل تشغيل تجارب الاسترجاع
# =========================================================

import torch
import gc

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

print("CUDA available:", torch.cuda.is_available())
print("Selected device:", DEVICE)

if torch.cuda.is_available():
    print("GPU name:", torch.cuda.get_device_name(0))
    print("GPU memory allocated GB:", round(torch.cuda.memory_allocated(0) / 1024**3, 2))
    print("GPU memory reserved GB:", round(torch.cuda.memory_reserved(0) / 1024**3, 2))

# تنظيف ذاكرة الكرت قبل التجارب
gc.collect()
if torch.cuda.is_available():
    torch.cuda.empty_cache()


def move_possible_model_to_device(obj, device, name="model"):
    """
    يحاول نقل النموذج إلى GPU سواء كان النموذج مباشرة أو داخل dict.
    """
    # الحالة 1: الكائن نفسه موديل وله .to()
    if hasattr(obj, "to"):
        obj.to(device)
        print(f"✅ {name} moved directly to {device}")
        return True

    # الحالة 2: الكائن dict وفيه موديل داخلي
    if isinstance(obj, dict):
        possible_keys = ["model", "embedding_model", "sentence_transformer", "encoder"]

        for key in possible_keys:
            if key in obj and hasattr(obj[key], "to"):
                obj[key].to(device)
                print(f"✅ {name}['{key}'] moved to {device}")
                return True

        print(f"⚠️ {name} is a dict, but no movable model object was found inside it.")
        print("Available keys:", list(obj.keys()))
        return False

    print(f"⚠️ Could not move {name}. Object type:", type(obj))
    return False


# نقل نماذج التضمين إلى GPU إذا كانت موجودة
if "loaded_embedding_models" in globals():
    for model_key, model_obj in loaded_embedding_models.items():
        move_possible_model_to_device(
            model_obj,
            DEVICE,
            name=f"embedding model [{model_key}]"
        )
else:
    print("⚠️ loaded_embedding_models not found.")


# نقل reranker إلى GPU
if "reranker_model" in globals() and reranker_model is not None:
    try:
        if hasattr(reranker_model, "model"):
            reranker_model.model.to(DEVICE)
            print("✅ Reranker internal model moved to", DEVICE)
        elif hasattr(reranker_model, "to"):
            reranker_model.to(DEVICE)
            print("✅ Reranker moved directly to", DEVICE)
        else:
            print("⚠️ Reranker object has no .to() method.")
    except Exception as e:
        print("⚠️ Could not move reranker to GPU:", e)
else:
    print("⚠️ reranker_model not found or is None.")

print("\nGPU preparation completed.")

if torch.cuda.is_available():
    print("GPU memory allocated GB after move:", round(torch.cuda.memory_allocated(0) / 1024**3, 2))
    print("GPU memory reserved GB after move:", round(torch.cuda.memory_reserved(0) / 1024**3, 2))

CUDA available: True
Selected device: cuda
GPU name: NVIDIA GeForce RTX 5090
GPU memory allocated GB: 6.32
GPU memory reserved GB: 6.33

✅ embedding model [e5_large]['model'] moved to cuda
✅ embedding model [bge_m3]['model'] moved to cuda
✅ Reranker internal model moved to cuda

GPU preparation completed.
GPU memory allocated GB after move: 6.32
GPU memory reserved GB after move: 6.33

In [19]:
# =========================================================
# ٍstage 12 Fix FAQ Retrieval Evaluation Set
# إصلاح تقييم FAQ بحيث تكون المراجع الذهبية موجودة داخل ChromaDB
# مع تقليل المطابقة النصية المباشرة في أسئلة FAQ
# =========================================================

import pandas as pd
import numpy as np
import re
from pathlib import Path
from IPython.display import display, HTML

# تحسين عرض الجداول داخل النوتبوك
pd.set_option("display.max_colwidth", 120)
pd.set_option("display.width", 160)

# ---------------------------------------------------------
# 0) Helper functions
# ---------------------------------------------------------

def first_existing_col(df, candidates):
    """
    Return the first existing column from a list of possible names.
    """
    for col in candidates:
        if col in df.columns:
            return col
    return None


def normalize_arabic_for_match(text):
    """
    Normalize Arabic text for simple exact-match diagnostics.
    """
    text = "" if pd.isna(text) else str(text)
    text = re.sub(r"[إأآا]", "ا", text)
    text = re.sub(r"ى", "ي", text)
    text = re.sub(r"ة", "ه", text)
    text = re.sub(r"ؤ", "و", text)
    text = re.sub(r"ئ", "ي", text)
    text = re.sub(r"[^\u0600-\u06FFa-zA-Z0-9\s]", " ", text)
    text = re.sub(r"\s+", " ", text).strip().lower()
    return text


def simple_arabic_paraphrase_question(q):
    """
    Rewrite FAQ evaluation questions to reduce exact-match leakage.

    Important:
    - The indexed FAQ answer remains unchanged.
    - Only the evaluation query is rewritten.
    - This helps evaluate semantic retrieval instead of direct text matching.
    """
    q = "" if pd.isna(q) else str(q).strip()
    q = re.sub(r"\s+", " ", q)
    q_clean = q.strip(" ؟?.")

    if not q_clean:
        return q_clean

    replacements = [
        ("هل يحق", "هل مسموح نظاماً"),
        ("هل يجوز", "هل مسموح"),
        ("هل يمكن", "هل يستطيع"),
        ("هل يسمح", "هل مسموح"),
        ("هل توفر", "أريد معرفة ما إذا كانت توفر"),
        ("هل يوجد", "أريد معرفة ما إذا كان يوجد"),
        ("هل", "أريد معرفة ما إذا كان"),
        ("ما هي", "أريد معرفة"),
        ("ما هو", "أريد معرفة"),
        ("متى", "في أي حالة"),
        ("كيف", "ما طريقة"),
        ("كم", "ما مقدار"),
        ("أين", "في أي مكان"),
    ]

    new_q = q_clean

    for old, new in replacements:
        if new_q.startswith(old):
            new_q = new_q.replace(old, new, 1)
            break
    else:
        new_q = "أريد توضيح الحكم النظامي بخصوص: " + q_clean

    return new_q.strip() + "؟"


# ---------------------------------------------------------
# 1) Collect indexed parent document IDs from CORPORA
# ---------------------------------------------------------

indexed_parent_ids = set()

for corpus_name, corpus_df in CORPORA.items():
    if "parent_document_id" in corpus_df.columns:
        indexed_parent_ids |= set(
            corpus_df["parent_document_id"]
            .astype(str)
            .str.strip()
        )

print("Indexed parent document IDs:", len(indexed_parent_ids))

assert len(indexed_parent_ids) > 0, "No indexed parent_document_id values found in CORPORA."


# ---------------------------------------------------------
# 2) Load FAQ indexing set from Stage 02
# ---------------------------------------------------------

faq_indexing_path = FINAL_DIR / "hrsd_faq_indexing_set.csv"

assert faq_indexing_path.exists(), f"FAQ indexing file not found: {faq_indexing_path}"

df_faq_indexed_source = pd.read_csv(faq_indexing_path)

print("FAQ indexing source shape:", df_faq_indexed_source.shape)
display(df_faq_indexed_source.head(3))


# ---------------------------------------------------------
# 3) Detect important columns safely
# ---------------------------------------------------------

faq_id_col = first_existing_col(
    df_faq_indexed_source,
    ["document_unit_id", "parent_document_id", "doc_id", "id"]
)

faq_question_col = first_existing_col(
    df_faq_indexed_source,
    ["question", "faq_question", "title", "user_question", "retrieval_text", "text_for_indexing"]
)

assert faq_id_col is not None, "Could not find FAQ document ID column."
assert faq_question_col is not None, "Could not find FAQ question/text column."

print("FAQ ID column:", faq_id_col)
print("FAQ question column:", faq_question_col)


# ---------------------------------------------------------
# 4) Keep only FAQ records that actually exist in indexed corpus
# ---------------------------------------------------------

df_faq_indexed_source[faq_id_col] = (
    df_faq_indexed_source[faq_id_col]
    .astype(str)
    .str.strip()
)

df_faq_eval_fixed_source = df_faq_indexed_source[
    df_faq_indexed_source[faq_id_col].isin(indexed_parent_ids)
].copy()

df_faq_eval_fixed_source = df_faq_eval_fixed_source.drop_duplicates(
    subset=[faq_id_col]
)

print("FAQ records available in indexed corpus:", len(df_faq_eval_fixed_source))

assert len(df_faq_eval_fixed_source) > 0, "No FAQ indexed records found inside ChromaDB corpus."


# ---------------------------------------------------------
# 5) Match previous FAQ evaluation size if possible
# ---------------------------------------------------------

TARGET_FAQ_EVAL_SIZE = 131

if len(df_faq_eval_fixed_source) >= TARGET_FAQ_EVAL_SIZE:
    df_faq_eval_fixed_source = df_faq_eval_fixed_source.sample(
        n=TARGET_FAQ_EVAL_SIZE,
        random_state=42
    ).reset_index(drop=True)
else:
    df_faq_eval_fixed_source = df_faq_eval_fixed_source.reset_index(drop=True)

print("Final fixed FAQ retrieval evaluation size:", len(df_faq_eval_fixed_source))


# ---------------------------------------------------------
# 6) Build fixed FAQ retrieval evaluation rows
# ---------------------------------------------------------

faq_eval_fixed_rows = []

for i, row in df_faq_eval_fixed_source.iterrows():
    gold_id = str(row[faq_id_col]).strip()
    original_question = str(row[faq_question_col]).strip()

    faq_eval_fixed_rows.append({
        "eval_id": f"FAQ_INDEXED_RETRIEVAL_{i+1:04d}",
        "eval_type": "faq_retrieval",
        "question": original_question,
        "gold_document_unit_id": gold_id,
        "gold_document_unit_ids": gold_id,
        "gold_article_number": "",
        "gold_article_numbers": "",
        "evaluation_note": "FAQ retrieval evaluation uses FAQ documents that are indexed in ChromaDB."
    })

df_faq_eval_fixed = pd.DataFrame(faq_eval_fixed_rows)

print("Fixed FAQ evaluation rows:", df_faq_eval_fixed.shape)


# ---------------------------------------------------------
# 7) Keep legal retrieval questions from existing evaluation
# ---------------------------------------------------------

if "df_eval" in globals():
    evaluation_source_df = df_eval.copy()
elif "df_eval_run" in globals():
    evaluation_source_df = df_eval_run.copy()
else:
    raise ValueError("Neither df_eval nor df_eval_run found. Please load evaluation dataset first.")

legal_eval_fixed = evaluation_source_df[
    evaluation_source_df["eval_type"]
    .astype(str)
    .str.contains("legal", case=False, na=False)
].copy()

print("Legal retrieval evaluation size:", len(legal_eval_fixed))

assert len(legal_eval_fixed) > 0, "No legal retrieval evaluation questions found."


# ---------------------------------------------------------
# 8) Build FAIR FAQ paraphrase evaluation set
# استخدام FAQ بصياغة معدلة بدل السؤال المطابق نصياً
# ---------------------------------------------------------

df_faq_eval_paraphrased = df_faq_eval_fixed.copy()

df_faq_eval_paraphrased["original_question"] = df_faq_eval_paraphrased["question"]

df_faq_eval_paraphrased["question"] = df_faq_eval_paraphrased["question"].apply(
    simple_arabic_paraphrase_question
)

df_faq_eval_paraphrased["eval_type"] = "faq_paraphrase_retrieval"

df_faq_eval_paraphrased["same_as_original_after_normalization"] = (
    df_faq_eval_paraphrased["original_question"].apply(normalize_arabic_for_match)
    == df_faq_eval_paraphrased["question"].apply(normalize_arabic_for_match)
)

faq_exact_match_count = int(
    df_faq_eval_paraphrased["same_as_original_after_normalization"].sum()
)

faq_exact_match_ratio = round(
    df_faq_eval_paraphrased["same_as_original_after_normalization"].mean(), 4
) if len(df_faq_eval_paraphrased) else 0

print("FAQ paraphrased questions:", len(df_faq_eval_paraphrased))
print("FAQ still exact match after normalization:", faq_exact_match_count)
print("FAQ exact match ratio:", faq_exact_match_ratio)


# ---------------------------------------------------------
# 9) Build final FAIR retrieval evaluation dataset for Stage 13
# ---------------------------------------------------------

df_eval_run = pd.concat(
    [
        df_faq_eval_paraphrased,
        legal_eval_fixed
    ],
    ignore_index=True
)

print("Updated df_eval_run shape:", df_eval_run.shape)
display(df_eval_run["eval_type"].value_counts().to_frame("count"))


# ---------------------------------------------------------
# 10) Verify that all FAQ gold IDs are now available in indexed corpus
# ---------------------------------------------------------

faq_gold_ids = set(
    df_faq_eval_fixed["gold_document_unit_id"]
    .astype(str)
    .str.strip()
)

available_faq_gold_ids = faq_gold_ids & indexed_parent_ids
missing_faq_gold_ids = faq_gold_ids - indexed_parent_ids

print("FAQ gold IDs:", len(faq_gold_ids))
print("FAQ gold IDs available in indexed corpus:", len(available_faq_gold_ids))
print("FAQ gold IDs missing from indexed corpus:", len(missing_faq_gold_ids))
print("FAQ availability ratio:", round(len(available_faq_gold_ids) / max(len(faq_gold_ids), 1), 4))

assert len(missing_faq_gold_ids) == 0, "Some FAQ gold IDs are still missing from indexed corpus."


# ---------------------------------------------------------
# 11) Save fixed and fair retrieval evaluation dataset
# ---------------------------------------------------------

fixed_eval_path = STAGE03_DIR / "stage03_fixed_faq_and_legal_retrieval_eval_dataset.csv"
fair_eval_path = STAGE03_DIR / "stage03_fair_faq_paraphrase_and_legal_retrieval_eval_dataset.csv"

df_eval_run.to_csv(
    fixed_eval_path,
    index=False,
    encoding="utf-8-sig"
)

df_eval_run.to_csv(
    fair_eval_path,
    index=False,
    encoding="utf-8-sig"
)


# ---------------------------------------------------------
# 12) Display academic explanation and sample
# ---------------------------------------------------------

display(HTML("""
<div dir="rtl" style="text-align:right; line-height:2; font-size:17px;">
<h3>تم إصلاح مجموعة تقييم FAQ للاسترجاع</h3>
<p>
تم إنشاء مجموعة تقييم FAQ جديدة بحيث تكون المراجع الذهبية موجودة فعلياً داخل قاعدة الفهرسة.
كما تم تعديل صياغة أسئلة FAQ في التقييم فقط، مع الإبقاء على الإجابات الأصلية داخل قاعدة المعرفة.
</p>
<p>
هذا التعديل يقلل من مشكلة المطابقة النصية المباشرة، ويجعل التقييم أقرب إلى قياس الاسترجاع الدلالي
بدلاً من اختبار استرجاع سؤال محفوظ بنفس الصياغة.
</p>
</div>
"""))

diagnostic_summary = pd.DataFrame([{
    "indexed_parent_ids": len(indexed_parent_ids),
    "faq_eval_questions": len(df_faq_eval_paraphrased),
    "legal_eval_questions": len(legal_eval_fixed),
    "total_eval_questions": len(df_eval_run),
    "faq_gold_ids_available_ratio": round(len(available_faq_gold_ids) / max(len(faq_gold_ids), 1), 4),
    "faq_exact_match_after_paraphrase_ratio": faq_exact_match_ratio
}])

display(diagnostic_summary)

print("Fixed retrieval evaluation dataset saved to:")
print(fixed_eval_path)

print("Fair retrieval evaluation dataset saved to:")
print(fair_eval_path)

display(
    df_faq_eval_paraphrased[
        [
            "eval_id",
            "original_question",
            "question",
            "gold_document_unit_id",
            "eval_type",
            "same_as_original_after_normalization"
        ]
    ].head(15)
)

Indexed parent document IDs: 489
FAQ indexing source shape: (278, 22)

,faq_id,question,answer,beneficiaries,sector,subsite,page_number,page_url,source,searchable_text,...,legal_category,document_unit_id,text_for_indexing,normalized_text,faq_domain_label,faq_filter_reason,keep_for_rag,keep_for_eval,is_eval_record,faq_split
0,1,هل تستخدم البوابة والانظمة التابعة لها الحلول الوطنية eSignature؟,"تقدم الوزارة خدمة التوقيع الالكتروني في اطار ادارة وتوثيق عقود العمل عبر منصة ""قوى"" يمكن للمنشآت انشاء وتوثيق وانهاء...",أصحاب عمل | أفراد | العمالة المنزلية | كبار السن,قطاع العمل,مركز الرياض للسياسات السلوكية,1,https://www.hrsd.gov.sa/contact-us/faq,HRSD FAQ,التصنيف: أصحاب عمل | أفراد | العمالة المنزلية | كبار السن قطاع العمل مركز الرياض للسياسات السلوكية السؤال: هل تستخدم...,...,أصحاب عمل | أفراد | العمالة المنزلية | كبار السن | قطاع العمل | مركز الرياض للسياسات السلوكية,87948be8261685e657502e8c023d087a27fb13927373f98568f379a8d20ff856,المصدر: HRSD FAQ التصنيف: أصحاب عمل | أفراد | العمالة المنزلية | كبار السن | قطاع العمل | مركز الرياض للسياسات السلو...,المصدر: HRSD FAQ التصنيف: اصحاب عمل افراد العماله المنزليه كبار السن قطاع العمل مركز الرياض للسياسات السلوكيه السوال...,keep_labor_faq,Strong labor-law or labor-service evidence found in question/answer.,True,True,False,indexing
1,28,هل يطبق قرار توطين المهن بالتوازي مع نطاقات؟,نعم، يُطبق قرار توطين المهن على المهن المستهدفة بالقرار داخل المنشأة، وتُطبق العقوبات المنصوص عليها نظامًا بغض النظر...,العمالة المنزلية | كبار السن,NaN,مركز الرياض للسياسات السلوكية,3,https://www.hrsd.gov.sa/contact-us/faq,HRSD FAQ,التصنيف: العمالة المنزلية | كبار السن مركز الرياض للسياسات السلوكية السؤال: هل يطبق قرار توطين المهن بالتوازي مع نطا...,...,العمالة المنزلية | كبار السن | | مركز الرياض للسياسات السلوكية,f6cb1c912ccbb571bd042480fb270bb4a2a348d19b19998dafe25511b00601ef,المصدر: HRSD FAQ التصنيف: العمالة المنزلية | كبار السن | | مركز الرياض للسياسات السلوكية السؤال: هل يطبق قرار توطين ...,المصدر: HRSD FAQ التصنيف: العماله المنزليه كبار السن مركز الرياض للسياسات السلوكيه السوال: هل يطبق قرار توطين المهن ...,keep_labor_faq,Strong labor-law or labor-service evidence found in question/answer.,True,True,False,indexing
2,36,كيف يتم التحقق من استلام العامل للأجر الذي سيتم التنفيذ عليه في عقد العمل الموثق سندًا تنفيذيًا؟,يتم التحقق إلكترونيا وفق بيانات برنامج حماية الأجور ( منصة مدد ) والذي يوثق دفع أجور العاملين بالمنشآت حسب تاريخ الا...,أصحاب عمل | أفراد | العمالة المنزلية | كبار السن,قطاع العمل,مركز الرياض للسياسات السلوكية,4,https://www.hrsd.gov.sa/contact-us/faq,HRSD FAQ,التصنيف: أصحاب عمل | أفراد | العمالة المنزلية | كبار السن قطاع العمل مركز الرياض للسياسات السلوكية السؤال: كيف يتم ا...,...,أصحاب عمل | أفراد | العمالة المنزلية | كبار السن | قطاع العمل | مركز الرياض للسياسات السلوكية,529eb529660f41db8b40d522f7914d1ea87fc055ca2c0bd6017d77fdd2d80aa3,المصدر: HRSD FAQ التصنيف: أصحاب عمل | أفراد | العمالة المنزلية | كبار السن | قطاع العمل | مركز الرياض للسياسات السلو...,المصدر: HRSD FAQ التصنيف: اصحاب عمل افراد العماله المنزليه كبار السن قطاع العمل مركز الرياض للسياسات السلوكيه السوال...,keep_labor_faq,Strong labor-law or labor-service evidence found in question/answer.,True,True,False,indexing

FAQ ID column: document_unit_id
FAQ question column: question
FAQ records available in indexed corpus: 278
Final fixed FAQ retrieval evaluation size: 131
Fixed FAQ evaluation rows: (131, 8)
Legal retrieval evaluation size: 24
FAQ paraphrased questions: 131
FAQ still exact match after normalization: 0
FAQ exact match ratio: 0.0
Updated df_eval_run shape: (155, 28)

                          count
eval_type
faq_paraphrase_retrieval    131
legal_article_retrieval      24

FAQ gold IDs: 131
FAQ gold IDs available in indexed corpus: 131
FAQ gold IDs missing from indexed corpus: 0
FAQ availability ratio: 1.0

   indexed_parent_ids  faq_eval_questions  legal_eval_questions  total_eval_questions  faq_gold_ids_available_ratio  faq_exact_match_after_paraphrase_ratio
0                 489                 131                    24                   155                           1.0                                     0.0

Fixed retrieval evaluation dataset saved to:
C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\stage03_fixed_faq_and_legal_retrieval_eval_dataset.csv
Fair retrieval evaluation dataset saved to:
C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\stage03_fair_faq_paraphrase_and_legal_retrieval_eval_dataset.csv

,eval_id,original_question,question,gold_document_unit_id,eval_type,same_as_original_after_normalization
0,FAQ_INDEXED_RETRIEVAL_0001,كيف يمكنني إلغاء أو تعديل طلب تغيير المهنة؟,ما طريقة يمكنني إلغاء أو تعديل طلب تغيير المهنة؟,f21821c706a73cea0189c74afd39b6fab9f3c00df86d508e4dbc347f8e2e81ff,faq_paraphrase_retrieval,False
1,FAQ_INDEXED_RETRIEVAL_0002,ما هي الطريقة المتبعة لتسديد قسط التأمين؟,أريد معرفة الطريقة المتبعة لتسديد قسط التأمين؟,91f863ae18d68499e05cdf8223c6042bcc37a38e10e1085130d95f1d78a8830b,faq_paraphrase_retrieval,False
2,FAQ_INDEXED_RETRIEVAL_0003,كيفية معاملة محرم الموظفة عند مرافقتها أثناء ابتعاثها للدراسة أو التدريب أو ايفادها للدراسة في الداخل أو انتدابها؟,ما طريقةية معاملة محرم الموظفة عند مرافقتها أثناء ابتعاثها للدراسة أو التدريب أو ايفادها للدراسة في الداخل أو انتدابها؟,e256af5955f5dee1600f1d294d2aa843c274dc4677d872e9dbf632c1f8953b0c,faq_paraphrase_retrieval,False
3,FAQ_INDEXED_RETRIEVAL_0004,ماهي أهداف برنامج نطاقات المطور؟,أريد توضيح الحكم النظامي بخصوص: ماهي أهداف برنامج نطاقات المطور؟,6ff8acc0f00c04a8f3c3b9e2c931e422728b201f017c40a3a5bba243c8b4e188,faq_paraphrase_retrieval,False
4,FAQ_INDEXED_RETRIEVAL_0005,ما مدى إمكانية الجمع بين بدل المهنة المنصوص عليه في المادة (51) من لائحة الحقوق والمزايا المالية وبين مكافأة التدريب...,أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية الجمع بين بدل المهنة المنصوص عليه في المادة (51) من لائحة الحقوق والم...,ba32d3405db89ca4685824ad8cd07423974e4e661eba4d9f8701b2a714f4c1ae,faq_paraphrase_retrieval,False
5,FAQ_INDEXED_RETRIEVAL_0006,موظف أحيل للتحقيق أثناء إجراء المفاضلة لغرض الترقية ثم صدر حكم ديوان المظالم بعدم ادانته بما نسب إليه فهل يمكن النظر...,أريد توضيح الحكم النظامي بخصوص: موظف أحيل للتحقيق أثناء إجراء المفاضلة لغرض الترقية ثم صدر حكم ديوان المظالم بعدم اد...,9cbf7fb10c58aad58ec3d59249ef17de418b275a98ae163fbdef896668775437,faq_paraphrase_retrieval,False
6,FAQ_INDEXED_RETRIEVAL_0007,كيف يتم احتساب أجر الساعات الإضافية؟,ما طريقة يتم احتساب أجر الساعات الإضافية؟,d15d4f9d9546ac825941020f027d112ee2098014cbc76475ab11efb09f884871,faq_paraphrase_retrieval,False
7,FAQ_INDEXED_RETRIEVAL_0008,هل يجوز تعيين العمال بصفة مؤقتة طبقاً للائحة المعينين على بند الأجور؟,هل مسموح تعيين العمال بصفة مؤقتة طبقاً للائحة المعينين على بند الأجور؟,55c6480dc2fde72eebcdcae651f5b8b4970b138d7009b692dfec858b088dd88e,faq_paraphrase_retrieval,False
8,FAQ_INDEXED_RETRIEVAL_0009,هل يمكن احتساب أيام المراجعة للمستشفيات داخل مقر العمل أو خارجه إجازة مرضية أو إجازة مرفقة؟,هل يستطيع احتساب أيام المراجعة للمستشفيات داخل مقر العمل أو خارجه إجازة مرضية أو إجازة مرفقة؟,56417832ce66ca28e1836f2029b8505b5666b9954af217782873c007282aaeab,faq_paraphrase_retrieval,False
9,FAQ_INDEXED_RETRIEVAL_0010,اعرف حقوق العمال؟,أريد توضيح الحكم النظامي بخصوص: اعرف حقوق العمال؟,7f81cd3c5fe470535b1c65952f22fe04293266fcfecef972015291b3f3ccfa95,faq_paraphrase_retrieval,False
10,FAQ_INDEXED_RETRIEVAL_0011,في حال تم رصد مخالفات في ملف الأجور، أين أجد تفاصيل المخالفة وتنبيهات السجلات؟,أريد توضيح الحكم النظامي بخصوص: في حال تم رصد مخالفات في ملف الأجور، أين أجد تفاصيل المخالفة وتنبيهات السجلات؟,f57c2b160f50a286f048602402e5d676a4cf0bbe511b687093e968c02386c8d0,faq_paraphrase_retrieval,False
11,FAQ_INDEXED_RETRIEVAL_0012,ما المقصود من كون عمال المستشفيات ضمن المساعدين الفنيين ومن هم عمال المستشفيات الذين يندرجون تحت هذه المجموعة؟,أريد توضيح الحكم النظامي بخصوص: ما المقصود من كون عمال المستشفيات ضمن المساعدين الفنيين ومن هم عمال المستشفيات الذين...,5d89c328b1fd5f76bbb0bb1f436a64a11b7c970590220950c748345407506932,faq_paraphrase_retrieval,False
12,FAQ_INDEXED_RETRIEVAL_0013,موظف قدم للرياض للالتحاق بدورة تدريبية وبعد انتهاء الفترة التدريبية عاد إلى مقر عمله الأصلي وفي أثناء الطريق حصل علي...,أريد توضيح الحكم النظامي بخصوص: موظف قدم للرياض للالتحاق بدورة تدريبية وبعد انتهاء الفترة التدريبية عاد إلى مقر عمله...,3817232e84c2b627b82a38def619dcc93a71bf05555e6f194b8ee29d98318dc5,faq_paraphrase_retrieval,False
13,FAQ_INDEXED_RETRIEVAL_0014,هل يخصم بدل المواصلات من راتب الإجازة السنوية؟,أريد معرفة ما إذا كان يخصم بدل المواصلات من راتب الإجازة السنوية؟,b1274bf7adc64bdf451019e4044a08171998e04e52da706e1753c4c39cb3f88e,faq_paraphrase_retrieval,False
14,FAQ_INDEXED_RETRIEVAL_0015,موظف استقال من وظيفة بالمرتبة الرابعة ومن ثم عاد للخدمة على المرتبة الخامسة بعد نجاحه في المسابقة، ما مدى إمكانية اح...,أريد توضيح الحكم النظامي بخصوص: موظف استقال من وظيفة بالمرتبة الرابعة ومن ثم عاد للخدمة على المرتبة الخامسة بعد نجاح...,5107dac49f2f062efde03d2678c519400560af163fc12ecad735831b7cec76ab,faq_paraphrase_retrieval,False

In [20]:
# =========================================================
# Stage 12.6 - Add Extra Legal Questions for Manual Review
# إضافة 80 سؤال قانوني طبيعي للمراجعة اليدوية وربطها لاحقاً مع Golden ID
# =========================================================

import pandas as pd
from IPython.display import display, HTML

extra_legal_questions = [
    {"eval_id": "LEGAL_EXTRA_001", "eval_type": "legal_article_retrieval", "question": "كم أقصى مدة ممكن تكون فترة التجربة في عقد العمل؟", "legal_topic": "فترة التجربة"},
    {"eval_id": "LEGAL_EXTRA_002", "eval_type": "legal_article_retrieval", "question": "هل يحق للشركة تمدد فترة التجربة بعد ما بدأت؟", "legal_topic": "فترة التجربة"},
    {"eval_id": "LEGAL_EXTRA_003", "eval_type": "legal_article_retrieval", "question": "إذا كنت في فترة التجربة هل أقدر أترك العمل بدون إنذار؟", "legal_topic": "فترة التجربة"},
    {"eval_id": "LEGAL_EXTRA_004", "eval_type": "legal_article_retrieval", "question": "هل لازم تكون فترة التجربة مكتوبة في العقد؟", "legal_topic": "فترة التجربة"},
    {"eval_id": "LEGAL_EXTRA_005", "eval_type": "legal_article_retrieval", "question": "لو انتهت فترة التجربة وسكتت الشركة هل أعتبر مثبت؟", "legal_topic": "فترة التجربة"},
    {"eval_id": "LEGAL_EXTRA_006", "eval_type": "legal_article_retrieval", "question": "هل يجوز لصاحب العمل يجربني أكثر من مرة على نفس الوظيفة؟", "legal_topic": "فترة التجربة"},
    {"eval_id": "LEGAL_EXTRA_007", "eval_type": "legal_article_retrieval", "question": "هل يحق للموظف يرفض تمديد فترة التجربة؟", "legal_topic": "فترة التجربة"},
    {"eval_id": "LEGAL_EXTRA_008", "eval_type": "legal_article_retrieval", "question": "إذا وقعت عقد جديد مع نفس الشركة هل تبدأ فترة تجربة جديدة؟", "legal_topic": "فترة التجربة"},

    {"eval_id": "LEGAL_EXTRA_009", "eval_type": "legal_article_retrieval", "question": "متى يعتبر عقد العمل منتهي نظامياً؟", "legal_topic": "انتهاء عقد العمل"},
    {"eval_id": "LEGAL_EXTRA_010", "eval_type": "legal_article_retrieval", "question": "هل انتهاء مدة العقد يعني أن العقد انتهى تلقائياً؟", "legal_topic": "انتهاء عقد العمل"},
    {"eval_id": "LEGAL_EXTRA_011", "eval_type": "legal_article_retrieval", "question": "إذا استمر الموظف بالعمل بعد انتهاء العقد هل يتجدد العقد؟", "legal_topic": "انتهاء عقد العمل"},
    {"eval_id": "LEGAL_EXTRA_012", "eval_type": "legal_article_retrieval", "question": "هل يحق للشركة تنهي عقدي بدون سبب واضح؟", "legal_topic": "انتهاء عقد العمل"},
    {"eval_id": "LEGAL_EXTRA_013", "eval_type": "legal_article_retrieval", "question": "متى يحق للعامل إنهاء العقد بدون موافقة صاحب العمل؟", "legal_topic": "انتهاء عقد العمل"},
    {"eval_id": "LEGAL_EXTRA_014", "eval_type": "legal_article_retrieval", "question": "إذا الشركة أغلقت الفرع هل يحق لها إنهاء عقد الموظفين؟", "legal_topic": "انتهاء عقد العمل"},
    {"eval_id": "LEGAL_EXTRA_015", "eval_type": "legal_article_retrieval", "question": "هل وفاة صاحب العمل تنهي عقد العامل؟", "legal_topic": "انتهاء عقد العمل"},
    {"eval_id": "LEGAL_EXTRA_016", "eval_type": "legal_article_retrieval", "question": "هل بلوغ العامل سن التقاعد ينهي عقد العمل؟", "legal_topic": "انتهاء عقد العمل"},

    {"eval_id": "LEGAL_EXTRA_017", "eval_type": "legal_article_retrieval", "question": "متى يستحق الموظف مكافأة نهاية الخدمة؟", "legal_topic": "مكافأة نهاية الخدمة"},
    {"eval_id": "LEGAL_EXTRA_018", "eval_type": "legal_article_retrieval", "question": "كيف تحسب مكافأة نهاية الخدمة إذا خدمت خمس سنوات؟", "legal_topic": "مكافأة نهاية الخدمة"},
    {"eval_id": "LEGAL_EXTRA_019", "eval_type": "legal_article_retrieval", "question": "إذا استقلت هل آخذ مكافأة نهاية الخدمة كاملة؟", "legal_topic": "مكافأة نهاية الخدمة"},
    {"eval_id": "LEGAL_EXTRA_020", "eval_type": "legal_article_retrieval", "question": "هل الموظف يستحق مكافأة نهاية الخدمة إذا تم فصله؟", "legal_topic": "مكافأة نهاية الخدمة"},
    {"eval_id": "LEGAL_EXTRA_021", "eval_type": "legal_article_retrieval", "question": "هل تحسب البدلات ضمن مكافأة نهاية الخدمة؟", "legal_topic": "مكافأة نهاية الخدمة"},
    {"eval_id": "LEGAL_EXTRA_022", "eval_type": "legal_article_retrieval", "question": "إذا اشتغلت أقل من سنتين هل لي مكافأة نهاية خدمة؟", "legal_topic": "مكافأة نهاية الخدمة"},
    {"eval_id": "LEGAL_EXTRA_023", "eval_type": "legal_article_retrieval", "question": "هل تختلف مكافأة نهاية الخدمة بين الاستقالة وإنهاء العقد؟", "legal_topic": "مكافأة نهاية الخدمة"},
    {"eval_id": "LEGAL_EXTRA_024", "eval_type": "legal_article_retrieval", "question": "متى تسقط مكافأة نهاية الخدمة عن العامل؟", "legal_topic": "مكافأة نهاية الخدمة"},

    {"eval_id": "LEGAL_EXTRA_025", "eval_type": "legal_article_retrieval", "question": "كم عدد ساعات العمل اليومية في النظام؟", "legal_topic": "ساعات العمل"},
    {"eval_id": "LEGAL_EXTRA_026", "eval_type": "legal_article_retrieval", "question": "كم الحد الأقصى لساعات العمل الأسبوعية؟", "legal_topic": "ساعات العمل"},
    {"eval_id": "LEGAL_EXTRA_027", "eval_type": "legal_article_retrieval", "question": "هل تختلف ساعات العمل في رمضان؟", "legal_topic": "ساعات العمل"},
    {"eval_id": "LEGAL_EXTRA_028", "eval_type": "legal_article_retrieval", "question": "هل يحق لصاحب العمل يطلب مني أشتغل وقت إضافي؟", "legal_topic": "ساعات العمل الإضافية"},
    {"eval_id": "LEGAL_EXTRA_029", "eval_type": "legal_article_retrieval", "question": "كيف يتم حساب أجر الساعة الإضافية؟", "legal_topic": "ساعات العمل الإضافية"},
    {"eval_id": "LEGAL_EXTRA_030", "eval_type": "legal_article_retrieval", "question": "هل يجوز تشغيل العامل أكثر من الحد النظامي لساعات العمل؟", "legal_topic": "ساعات العمل"},
    {"eval_id": "LEGAL_EXTRA_031", "eval_type": "legal_article_retrieval", "question": "هل وقت الراحة داخل الدوام يحسب من ساعات العمل؟", "legal_topic": "فترات الراحة"},
    {"eval_id": "LEGAL_EXTRA_032", "eval_type": "legal_article_retrieval", "question": "كم أقل مدة راحة لازم تعطى للعامل خلال اليوم؟", "legal_topic": "فترات الراحة"},

    {"eval_id": "LEGAL_EXTRA_033", "eval_type": "legal_article_retrieval", "question": "هل يحق للموظف إجازة سنوية مدفوعة؟", "legal_topic": "الإجازة السنوية"},
    {"eval_id": "LEGAL_EXTRA_034", "eval_type": "legal_article_retrieval", "question": "كم عدد أيام الإجازة السنوية للعامل؟", "legal_topic": "الإجازة السنوية"},
    {"eval_id": "LEGAL_EXTRA_035", "eval_type": "legal_article_retrieval", "question": "هل تزيد الإجازة السنوية بعد سنوات خدمة معينة؟", "legal_topic": "الإجازة السنوية"},
    {"eval_id": "LEGAL_EXTRA_036", "eval_type": "legal_article_retrieval", "question": "هل يحق للشركة تأجيل إجازتي السنوية؟", "legal_topic": "الإجازة السنوية"},
    {"eval_id": "LEGAL_EXTRA_037", "eval_type": "legal_article_retrieval", "question": "إذا تركت العمل هل آخذ بدل رصيد الإجازات؟", "legal_topic": "الإجازة السنوية"},
    {"eval_id": "LEGAL_EXTRA_038", "eval_type": "legal_article_retrieval", "question": "هل أقدر أتنازل عن إجازتي السنوية مقابل مبلغ؟", "legal_topic": "الإجازة السنوية"},
    {"eval_id": "LEGAL_EXTRA_039", "eval_type": "legal_article_retrieval", "question": "هل إجازات الأعياد تكون مدفوعة الأجر؟", "legal_topic": "الإجازات الرسمية"},
    {"eval_id": "LEGAL_EXTRA_040", "eval_type": "legal_article_retrieval", "question": "إذا صادفت الإجازة الرسمية يوم راحتي الأسبوعية هل أعوض عنها؟", "legal_topic": "الإجازات الرسمية"},

    {"eval_id": "LEGAL_EXTRA_041", "eval_type": "legal_article_retrieval", "question": "كم مدة الإجازة المرضية المسموحة للعامل؟", "legal_topic": "الإجازة المرضية"},
    {"eval_id": "LEGAL_EXTRA_042", "eval_type": "legal_article_retrieval", "question": "هل الإجازة المرضية تكون بأجر كامل؟", "legal_topic": "الإجازة المرضية"},
    {"eval_id": "LEGAL_EXTRA_043", "eval_type": "legal_article_retrieval", "question": "متى تكون الإجازة المرضية بدون أجر؟", "legal_topic": "الإجازة المرضية"},
    {"eval_id": "LEGAL_EXTRA_044", "eval_type": "legal_article_retrieval", "question": "هل يحق لصاحب العمل فصل الموظف بسبب المرض؟", "legal_topic": "الإجازة المرضية"},
    {"eval_id": "LEGAL_EXTRA_045", "eval_type": "legal_article_retrieval", "question": "هل يجب تقديم تقرير طبي للحصول على إجازة مرضية؟", "legal_topic": "الإجازة المرضية"},
    {"eval_id": "LEGAL_EXTRA_046", "eval_type": "legal_article_retrieval", "question": "إذا مرضت أثناء الإجازة السنوية هل تتحول لإجازة مرضية؟", "legal_topic": "الإجازة المرضية"},

    {"eval_id": "LEGAL_EXTRA_047", "eval_type": "legal_article_retrieval", "question": "متى يحق لصاحب العمل فصل العامل بدون مكافأة؟", "legal_topic": "الفصل التأديبي"},
    {"eval_id": "LEGAL_EXTRA_048", "eval_type": "legal_article_retrieval", "question": "هل الغياب بدون عذر يعطي الشركة حق الفصل؟", "legal_topic": "الغياب"},
    {"eval_id": "LEGAL_EXTRA_049", "eval_type": "legal_article_retrieval", "question": "كم يوم غياب يسبب فصل الموظف؟", "legal_topic": "الغياب"},
    {"eval_id": "LEGAL_EXTRA_050", "eval_type": "legal_article_retrieval", "question": "هل لازم الشركة تنذر الموظف قبل فصله بسبب الغياب؟", "legal_topic": "الغياب"},
    {"eval_id": "LEGAL_EXTRA_051", "eval_type": "legal_article_retrieval", "question": "إذا رفض الموظف تنفيذ العمل هل يحق فصله؟", "legal_topic": "الفصل التأديبي"},
    {"eval_id": "LEGAL_EXTRA_052", "eval_type": "legal_article_retrieval", "question": "هل يحق للشركة فصل الموظف بسبب إفشاء أسرار العمل؟", "legal_topic": "الفصل التأديبي"},
    {"eval_id": "LEGAL_EXTRA_053", "eval_type": "legal_article_retrieval", "question": "هل الاعتداء على المدير أو الزملاء يؤدي للفصل؟", "legal_topic": "الفصل التأديبي"},
    {"eval_id": "LEGAL_EXTRA_054", "eval_type": "legal_article_retrieval", "question": "هل استخدام مستندات مزورة في التوظيف يسبب الفصل؟", "legal_topic": "الفصل التأديبي"},

    {"eval_id": "LEGAL_EXTRA_055", "eval_type": "legal_article_retrieval", "question": "هل يجوز نقل العامل من مدينة إلى مدينة بدون موافقته؟", "legal_topic": "نقل العامل"},
    {"eval_id": "LEGAL_EXTRA_056", "eval_type": "legal_article_retrieval", "question": "هل يحق للشركة تغيير طبيعة عملي بعد توقيع العقد؟", "legal_topic": "شروط العمل"},
    {"eval_id": "LEGAL_EXTRA_057", "eval_type": "legal_article_retrieval", "question": "إذا كلفتني الشركة بعمل غير المتفق عليه هل هذا نظامي؟", "legal_topic": "شروط العمل"},
    {"eval_id": "LEGAL_EXTRA_058", "eval_type": "legal_article_retrieval", "question": "هل يحق لصاحب العمل تخفيض راتبي بدون موافقتي؟", "legal_topic": "الأجر"},
    {"eval_id": "LEGAL_EXTRA_059", "eval_type": "legal_article_retrieval", "question": "متى يجب دفع راتب العامل؟", "legal_topic": "الأجر"},
    {"eval_id": "LEGAL_EXTRA_060", "eval_type": "legal_article_retrieval", "question": "هل تأخير الراتب يعتبر مخالفة؟", "legal_topic": "الأجر"},
    {"eval_id": "LEGAL_EXTRA_061", "eval_type": "legal_article_retrieval", "question": "هل يجوز الخصم من راتب الموظف؟", "legal_topic": "الخصم من الأجر"},
    {"eval_id": "LEGAL_EXTRA_062", "eval_type": "legal_article_retrieval", "question": "كم الحد الأعلى للخصم من الراتب؟", "legal_topic": "الخصم من الأجر"},
    {"eval_id": "LEGAL_EXTRA_063", "eval_type": "legal_article_retrieval", "question": "هل يحق للشركة تخصم من راتبي بسبب تلف جهاز؟", "legal_topic": "الخصم من الأجر"},
    {"eval_id": "LEGAL_EXTRA_064", "eval_type": "legal_article_retrieval", "question": "هل يحق للعامل الاعتراض على الخصم من راتبه؟", "legal_topic": "الخصم من الأجر"},

    {"eval_id": "LEGAL_EXTRA_065", "eval_type": "legal_article_retrieval", "question": "هل يجب أن يكون عقد العمل مكتوب؟", "legal_topic": "عقد العمل"},
    {"eval_id": "LEGAL_EXTRA_066", "eval_type": "legal_article_retrieval", "question": "ما البيانات الأساسية التي لازم تكون في عقد العمل؟", "legal_topic": "عقد العمل"},
    {"eval_id": "LEGAL_EXTRA_067", "eval_type": "legal_article_retrieval", "question": "إذا ما عندي عقد مكتوب هل تضيع حقوقي؟", "legal_topic": "عقد العمل"},
    {"eval_id": "LEGAL_EXTRA_068", "eval_type": "legal_article_retrieval", "question": "هل يحق للعامل طلب نسخة من عقد العمل؟", "legal_topic": "عقد العمل"},
    {"eval_id": "LEGAL_EXTRA_069", "eval_type": "legal_article_retrieval", "question": "هل العقد الإلكتروني يعتبر عقد عمل نظامي؟", "legal_topic": "عقد العمل"},
    {"eval_id": "LEGAL_EXTRA_070", "eval_type": "legal_article_retrieval", "question": "إذا اختلف الراتب الفعلي عن المكتوب في العقد ماذا أفعل؟", "legal_topic": "عقد العمل"},

    {"eval_id": "LEGAL_EXTRA_071", "eval_type": "legal_article_retrieval", "question": "هل يحق للعامل الحصول على شهادة خبرة بعد ترك العمل؟", "legal_topic": "شهادة الخدمة"},
    {"eval_id": "LEGAL_EXTRA_072", "eval_type": "legal_article_retrieval", "question": "هل يجوز لصاحب العمل يمنعني من أخذ شهادة خدمة؟", "legal_topic": "شهادة الخدمة"},
    {"eval_id": "LEGAL_EXTRA_073", "eval_type": "legal_article_retrieval", "question": "هل يحق للشركة تحتفظ بجواز العامل؟", "legal_topic": "حقوق العامل"},
    {"eval_id": "LEGAL_EXTRA_074", "eval_type": "legal_article_retrieval", "question": "هل يحق لصاحب العمل تحميل العامل رسوم الاستقدام؟", "legal_topic": "حقوق العامل"},
    {"eval_id": "LEGAL_EXTRA_075", "eval_type": "legal_article_retrieval", "question": "هل يجوز تشغيل العامل في يوم الراحة الأسبوعية؟", "legal_topic": "الراحة الأسبوعية"},
    {"eval_id": "LEGAL_EXTRA_076", "eval_type": "legal_article_retrieval", "question": "ما هو يوم الراحة الأسبوعية في نظام العمل؟", "legal_topic": "الراحة الأسبوعية"},
    {"eval_id": "LEGAL_EXTRA_077", "eval_type": "legal_article_retrieval", "question": "إذا اشتغلت في يوم الراحة هل أستحق تعويض؟", "legal_topic": "الراحة الأسبوعية"},
    {"eval_id": "LEGAL_EXTRA_078", "eval_type": "legal_article_retrieval", "question": "هل يحق للعامل ترك العمل إذا لم يدفع صاحب العمل الراتب؟", "legal_topic": "ترك العمل"},
    {"eval_id": "LEGAL_EXTRA_079", "eval_type": "legal_article_retrieval", "question": "هل يحق للعامل ترك العمل إذا تعرض للإهانة أو المعاملة السيئة؟", "legal_topic": "ترك العمل"},
    {"eval_id": "LEGAL_EXTRA_080", "eval_type": "legal_article_retrieval", "question": "هل يحق للعامل ترك العمل إذا كلف بعمل خطر بدون حماية؟", "legal_topic": "السلامة المهنية"},
]

df_extra_questions = pd.DataFrame(extra_legal_questions)

display(HTML("""
<div dir="rtl" style="text-align:right; line-height:2; font-size:16px;">
<h3>تم تحميل الأسئلة القانونية الإضافية</h3>
<p>
هذه الأسئلة لم تدخل التقييم النهائي بعد، لأنها تحتاج إلى ربط يدوي مع Golden ID الصحيح.
</p>
</div>
"""))

print("Extra legal questions:", len(df_extra_questions))
display(df_extra_questions.head(10))

Extra legal questions: 80

           eval_id                eval_type                                                   question       legal_topic
0  LEGAL_EXTRA_001  legal_article_retrieval           كم أقصى مدة ممكن تكون فترة التجربة في عقد العمل؟      فترة التجربة
1  LEGAL_EXTRA_002  legal_article_retrieval               هل يحق للشركة تمدد فترة التجربة بعد ما بدأت؟      فترة التجربة
2  LEGAL_EXTRA_003  legal_article_retrieval     إذا كنت في فترة التجربة هل أقدر أترك العمل بدون إنذار؟      فترة التجربة
3  LEGAL_EXTRA_004  legal_article_retrieval                 هل لازم تكون فترة التجربة مكتوبة في العقد؟      فترة التجربة
4  LEGAL_EXTRA_005  legal_article_retrieval          لو انتهت فترة التجربة وسكتت الشركة هل أعتبر مثبت؟      فترة التجربة
5  LEGAL_EXTRA_006  legal_article_retrieval    هل يجوز لصاحب العمل يجربني أكثر من مرة على نفس الوظيفة؟      فترة التجربة
6  LEGAL_EXTRA_007  legal_article_retrieval                     هل يحق للموظف يرفض تمديد فترة التجربة؟      فترة التجربة
7  LEGAL_EXTRA_008  legal_article_retrieval  إذا وقعت عقد جديد مع نفس الشركة هل تبدأ فترة تجربة جديدة؟      فترة التجربة
8  LEGAL_EXTRA_009  legal_article_retrieval                         متى يعتبر عقد العمل منتهي نظامياً؟  انتهاء عقد العمل
9  LEGAL_EXTRA_010  legal_article_retrieval          هل انتهاء مدة العقد يعني أن العقد انتهى تلقائياً؟  انتهاء عقد العمل

<div dir="rtl" style="text-align:right; line-height:2; font-family:Tahoma, Arial; font-size:16px;">

### Stage 12.7 — اقتراح Golden IDs للأسئلة القانونية الإضافية

هذه المرحلة اختيارية. الهدف منها اقتراح مراجع ذهبية للأسئلة القانونية الإضافية، ثم يقوم الباحث بمراجعتها يدوياً قبل الدمج في التقييم النهائي.

</div>

In [21]:
# =========================================================
# Stage 12.7 - Suggest Golden IDs for Extra Legal Questions
# اقتراح Golden IDs للأسئلة القانونية الجديدة
# =========================================================

import pandas as pd
import numpy as np
import re
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from IPython.display import display, HTML

def first_existing_col(df, candidates):
    for col in candidates:
        if col in df.columns:
            return col
    return None

def clean_for_search(text):
    text = "" if pd.isna(text) else str(text)
    text = re.sub(r"[إأآا]", "ا", text)
    text = re.sub(r"ى", "ي", text)
    text = re.sub(r"ة", "ه", text)
    text = re.sub(r"ؤ", "و", text)
    text = re.sub(r"ئ", "ي", text)
    text = re.sub(r"[^\u0600-\u06FFa-zA-Z0-9\s]", " ", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text

# ---------------------------------------------------------
# Build legal candidate documents from CORPORA
# ---------------------------------------------------------

legal_docs = []

for corpus_name, corpus_df in CORPORA.items():
    temp = corpus_df.copy()

    id_col = first_existing_col(temp, ["parent_document_id", "document_unit_id", "doc_id", "id"])
    text_col = first_existing_col(temp, ["retrieval_text", "chunk_text", "text", "article_text", "content"])
    article_col = first_existing_col(temp, ["article_number", "gold_article_number", "article_id", "article_number_int"])

    if id_col is None or text_col is None:
        continue

    if "source_type" in temp.columns:
        temp = temp[
            temp["source_type"].astype(str).str.contains("law|legal|article", case=False, na=False)
        ].copy()

    for _, row in temp.iterrows():
        doc_id = str(row[id_col]).strip()
        text = str(row[text_col]).strip()

        if not doc_id or not text:
            continue

        article_number = ""
        if article_col is not None:
            article_number = str(row[article_col]).strip()

        legal_docs.append({
            "corpus_name": corpus_name,
            "candidate_id": doc_id,
            "candidate_article_number": article_number,
            "candidate_text": text
        })

df_legal_docs = pd.DataFrame(legal_docs)

df_legal_docs = (
    df_legal_docs
    .drop_duplicates(subset=["candidate_id"])
    .reset_index(drop=True)
)

assert len(df_legal_docs) > 0, "No legal candidate documents found."
assert "df_extra_questions" in globals(), "Run Stage 12.6 first."

df_extra = df_extra_questions.copy()

df_extra["clean_question"] = df_extra["question"].apply(clean_for_search)
df_legal_docs["clean_text"] = df_legal_docs["candidate_text"].apply(clean_for_search)

# ---------------------------------------------------------
# TF-IDF similarity for candidate suggestion only
# ---------------------------------------------------------

all_texts = df_legal_docs["clean_text"].tolist() + df_extra["clean_question"].tolist()

vectorizer = TfidfVectorizer(
    analyzer="char_wb",
    ngram_range=(3, 5),
    min_df=1
)

tfidf_matrix = vectorizer.fit_transform(all_texts)

doc_vectors = tfidf_matrix[:len(df_legal_docs)]
question_vectors = tfidf_matrix[len(df_legal_docs):]

similarity_matrix = cosine_similarity(question_vectors, doc_vectors)

# ---------------------------------------------------------
# Build review table
# ---------------------------------------------------------

TOP_N = 5
review_rows = []

for q_idx, q_row in df_extra.reset_index(drop=True).iterrows():
    sims = similarity_matrix[q_idx]
    top_indices = np.argsort(sims)[::-1][:TOP_N]

    base = {
        "eval_id": q_row["eval_id"],
        "eval_type": "legal_article_retrieval",
        "question": q_row["question"],
        "legal_topic": q_row.get("legal_topic", ""),
        "manual_gold_article_number": "",
        "manual_gold_document_unit_id": "",
        "review_status": "PENDING_MANUAL_REVIEW"
    }

    for rank, doc_idx in enumerate(top_indices, start=1):
        cand = df_legal_docs.iloc[doc_idx]
        base[f"candidate_{rank}_score"] = round(float(sims[doc_idx]), 4)
        base[f"candidate_{rank}_article"] = cand["candidate_article_number"]
        base[f"candidate_{rank}_id"] = cand["candidate_id"]
        base[f"candidate_{rank}_text_preview"] = cand["candidate_text"][:500]

    review_rows.append(base)

df_gold_review = pd.DataFrame(review_rows)

review_path = STAGE03_DIR / "legal_extra_questions_gold_id_review_candidates.csv"

df_gold_review.to_csv(
    review_path,
    index=False,
    encoding="utf-8-sig"
)

display(HTML("""
<div dir="rtl" style="text-align:right; line-height:2; font-size:16px;">
<h3>تم إنشاء ملف مراجعة Golden IDs</h3>
<p>
افتح الملف، وراجع أفضل 5 مواد مرشحة لكل سؤال، ثم املأ manual_gold_article_number و manual_gold_document_unit_id يدوياً.
</p>
</div>
"""))

print("Review file saved to:")
print(review_path)

display(df_gold_review.head())

Review file saved to:
C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\legal_extra_questions_gold_id_review_candidates.csv

,eval_id,eval_type,question,legal_topic,manual_gold_article_number,manual_gold_document_unit_id,review_status,candidate_1_score,candidate_1_article,candidate_1_id,...,candidate_3_id,candidate_3_text_preview,candidate_4_score,candidate_4_article,candidate_4_id,candidate_4_text_preview,candidate_5_score,candidate_5_article,candidate_5_id,candidate_5_text_preview
0,LEGAL_EXTRA_001,legal_article_retrieval,كم أقصى مدة ممكن تكون فترة التجربة في عقد العمل؟,فترة التجربة,,,PENDING_MANUAL_REVIEW,0.2533,الرابعة والخمسون,ab8af4e6ecab46b0bf5b588cc55664b9d0a008dc9073912d3417c1f04d083142,...,b56e9c99f1c551928c8727dae90850186c14efc78d6272f429f0c448add3f3dc,التصنيف القانوني: علاقات العمل\nالباب: علاقات العمل\nالفصل: الفصل الأول\nرقم المادة: الثالثة والخمسون\nعنوان المادة:...,0.1001,الثانية,4f2961046b5fffdc637e2b7de4dfb1fd862ccc7b9f3069349681b04ff17df638,التصنيف القانوني: التعريفات / الأحكام العامة\nالباب: التعريفات / الأحكام العامة\nالفصل: الفصل الأول\nرقم المادة: الث...,0.0939,التاسعة والسبعون بعد المائة,cf4e4b2806a0c863c377af5a46b2d45d628aa531ca1024270da12c93a51c2097,التصنيف القانوني: عقد العمل البحري\nالباب: عقد العمل البحري\nالفصل: nan\nرقم المادة: التاسعة والسبعون بعد المائة\nعن...
1,LEGAL_EXTRA_002,legal_article_retrieval,هل يحق للشركة تمدد فترة التجربة بعد ما بدأت؟,فترة التجربة,,,PENDING_MANUAL_REVIEW,0.1772,الرابعة والخمسون,ab8af4e6ecab46b0bf5b588cc55664b9d0a008dc9073912d3417c1f04d083142,...,dd858095f7b7989c6920172b61ccf992fb378afd325c06fb4eda55d1ceadaf9c,التصنيف القانوني: شروط العمل وظروفه\nالباب: شروط العمل وظروفه\nالفصل: الفصل الثالث\nرقم المادة: الثالثة بعد المائة\n...,0.0514,الثالثة والخمسون,b56e9c99f1c551928c8727dae90850186c14efc78d6272f429f0c448add3f3dc,التصنيف القانوني: علاقات العمل\nالباب: علاقات العمل\nالفصل: الفصل الأول\nرقم المادة: الثالثة والخمسون\nعنوان المادة:...,0.0487,الستون بعد المائة,f3b2d548d622040188c6ebcfda67f959c540fe61dbb6be0a130d3cd508041879,التصنيف القانوني: تشغيل النساء\nالباب: تشغيل النساء\nالفصل: nan\nرقم المادة: الستون بعد المائة\nعنوان المادة: المادة...
2,LEGAL_EXTRA_003,legal_article_retrieval,إذا كنت في فترة التجربة هل أقدر أترك العمل بدون إنذار؟,فترة التجربة,,,PENDING_MANUAL_REVIEW,0.1907,الرابعة والخمسون,ab8af4e6ecab46b0bf5b588cc55664b9d0a008dc9073912d3417c1f04d083142,...,93106f92e2e463b2afeee9b680ab418b16cc3907a7b7f1d8308274a5081c8839,التصنيف القانوني: علاقات العمل\nالباب: علاقات العمل\nالفصل: الفصل الثالث\nرقم المادة: الحادية والثمانون\nعنوان الماد...,0.0845,الثالثة بعد المائة,dd858095f7b7989c6920172b61ccf992fb378afd325c06fb4eda55d1ceadaf9c,التصنيف القانوني: شروط العمل وظروفه\nالباب: شروط العمل وظروفه\nالفصل: الفصل الثالث\nرقم المادة: الثالثة بعد المائة\n...,0.0823,الثانية,4f2961046b5fffdc637e2b7de4dfb1fd862ccc7b9f3069349681b04ff17df638,التصنيف القانوني: التعريفات / الأحكام العامة\nالباب: التعريفات / الأحكام العامة\nالفصل: الفصل الأول\nرقم المادة: الث...
3,LEGAL_EXTRA_004,legal_article_retrieval,هل لازم تكون فترة التجربة مكتوبة في العقد؟,فترة التجربة,,,PENDING_MANUAL_REVIEW,0.2489,الرابعة والخمسون,ab8af4e6ecab46b0bf5b588cc55664b9d0a008dc9073912d3417c1f04d083142,...,4f2961046b5fffdc637e2b7de4dfb1fd862ccc7b9f3069349681b04ff17df638,التصنيف القانوني: التعريفات / الأحكام العامة\nالباب: التعريفات / الأحكام العامة\nالفصل: الفصل الأول\nرقم المادة: الث...,0.0815,الثالثة والخمسون,b56e9c99f1c551928c8727dae90850186c14efc78d6272f429f0c448add3f3dc,التصنيف القانوني: علاقات العمل\nالباب: علاقات العمل\nالفصل: الفصل الأول\nرقم المادة: الثالثة والخمسون\nعنوان المادة:...,0.0784,السابعة والسبعون,1b19a4fb2b4d423df5c66d04b1a372b80a041caaf759a0b8ba32555c20a6f902,التصنيف القانوني: علاقات العمل\nالباب: علاقات العمل\nالفصل: الفصل الثالث\nرقم المادة: السابعة والسبعون\nعنوان المادة...
4,LEGAL_EXTRA_005,legal_article_retrieval,لو انتهت فترة التجربة وسكتت الشركة هل أعتبر مثبت؟,فترة التجربة,,,PENDING_MANUAL_REVIEW,0.1577,الرابعة والخمسون,ab8af4e6ecab46b0bf5b588cc55664b9d0a008dc9073912d3417c1f04d083142,...,596b788c22bea70c4b18299cbd376342009abee45436ad55214038a1b5e999fa,التصنيف القانوني: تشغيل النساء\nالباب: تشغيل النساء\nالفصل: nan\nرقم المادة: الرابعة والخمسون بعد المائة\nعنوان الما...,0.0533,الثالثة بعد المائة,dd858095f7b7989c6920172b61ccf992fb378afd325c06fb4eda55d1ceadaf9c,التصنيف القانوني: شروط العمل وظروفه\nالباب: شروط العمل وظروفه\nالفصل: الفصل الثالث\nرقم المادة: الثالثة بعد المائة\n...,0.0486,الرابعة والثمانون,5b972d3ae51a19b2a3ebe1ab525fc3fb05eefd24224b1f22cd598c050d3194bf,التصنيف القانوني: علاقات العمل\nالباب: علاقات العمل\nالفصل: الفصل الرابع\nرقم المادة: الرابعة والثمانون\nعنوان الماد...

In [22]:
# =========================================================
# Stage 12.7.5 - Export Clean Manual Review File as XLSX
# إنشاء ملف مراجعة يدوي نظيف بصيغة Excel تحفظ العربي
# =========================================================

import pandas as pd
from pathlib import Path
from IPython.display import display, HTML

candidate_path = STAGE03_DIR / "legal_extra_questions_gold_id_review_candidates.csv"
manual_xlsx_path = STAGE03_DIR / "legal_extra_questions_gold_id_reviewed.xlsx"

assert candidate_path.exists(), f"Candidate file not found: {candidate_path}"

# اقرأ ملف المرشحين بترميز صحيح
df_candidates = pd.read_csv(candidate_path, encoding="utf-8-sig")

# تأكد من وجود أعمدة المراجعة اليدوية
if "manual_gold_article_number" not in df_candidates.columns:
    df_candidates["manual_gold_article_number"] = ""

if "manual_gold_document_unit_id" not in df_candidates.columns:
    df_candidates["manual_gold_document_unit_id"] = ""

if "review_status" not in df_candidates.columns:
    df_candidates["review_status"] = "PENDING_MANUAL_REVIEW"

# احفظ كـ XLSX وليس CSV
with pd.ExcelWriter(manual_xlsx_path, engine="openpyxl") as writer:
    df_candidates.to_excel(writer, index=False, sheet_name="manual_review")

print("Clean manual review Excel file saved to:")
print(manual_xlsx_path)

display(HTML("""
<div dir="rtl" style="text-align:right; line-height:2; font-size:16px;">
<h3>تم إنشاء ملف Excel نظيف للمراجعة اليدوية</h3>
<p>
افتح ملف XLSX وليس CSV، ثم عبئ فقط:
</p>
<ul>
<li>manual_gold_article_number</li>
<li>manual_gold_document_unit_id</li>
</ul>
<p>
بعد التعبئة احفظ الملف بنفس الاسم والصيغة XLSX.
</p>
</div>
"""))

display(df_candidates[[
    "eval_id",
    "question",
    "legal_topic",
    "manual_gold_article_number",
    "manual_gold_document_unit_id"
]].head(5))

Clean manual review Excel file saved to:
C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\legal_extra_questions_gold_id_reviewed.xlsx

           eval_id                                                question   legal_topic  manual_gold_article_number  manual_gold_document_unit_id
0  LEGAL_EXTRA_001        كم أقصى مدة ممكن تكون فترة التجربة في عقد العمل؟  فترة التجربة                         NaN                           NaN
1  LEGAL_EXTRA_002            هل يحق للشركة تمدد فترة التجربة بعد ما بدأت؟  فترة التجربة                         NaN                           NaN
2  LEGAL_EXTRA_003  إذا كنت في فترة التجربة هل أقدر أترك العمل بدون إنذار؟  فترة التجربة                         NaN                           NaN
3  LEGAL_EXTRA_004              هل لازم تكون فترة التجربة مكتوبة في العقد؟  فترة التجربة                         NaN                           NaN
4  LEGAL_EXTRA_005       لو انتهت فترة التجربة وسكتت الشركة هل أعتبر مثبت؟  فترة التجربة                         NaN                           NaN

<div dir="rtl" style="text-align:right; line-height:2; font-family:Tahoma, Arial; font-size:16px;">

### Stage 12.8 — دمج ملف المراجعة اليدوية

إذا تم تعبئة ملف Excel الخاص بالمراجعة اليدوية، سيتم دمجه مع مجموعة التقييم.  
إذا لم يتم تعبئته، سيتجاوز النوتبوك هذه الخطوة بدون توقف حتى يبقى التقييم الأساسي قابلاً للتشغيل.

</div>

In [23]:
# =========================================================
# Stage 12.8 - Optional Merge of Reviewed Extra Legal Questions
# دمج اختياري للأسئلة القانونية الإضافية بعد مراجعة Golden IDs يدوياً
# =========================================================

import pandas as pd
from IPython.display import display, HTML

review_path = STAGE03_DIR / "legal_extra_questions_gold_id_reviewed.xlsx"

if not review_path.exists():
    display(HTML(f"""
    <div dir="rtl" style="text-align:right; line-height:2; font-size:16px;
                background:#fff3cd; border-right:6px solid #ffc107; padding:12px;">
        <b>تنبيه:</b> ملف المراجعة اليدوية غير موجود حالياً، لذلك سيتم تجاوز دمج الأسئلة الإضافية بدون إيقاف النوتبوك.
        <br>
        هذا لا يؤثر على التقييم الأساسي لأنه يستخدم ملف
        <span dir="ltr">rag_retrieval_evaluation_dataset_valid_only.csv</span>.
        <br>
        مسار الملف المتوقع:
        <span dir="ltr">{review_path}</span>
    </div>
    """))

    reviewed_extra_questions_df = pd.DataFrame()
    extra_questions_merged = False

else:
    df_reviewed = pd.read_excel(review_path)

    required_cols = [
        "eval_id",
        "eval_type",
        "question",
        "manual_gold_article_number",
        "manual_gold_document_unit_id"
    ]

    missing_cols = [c for c in required_cols if c not in df_reviewed.columns]
    assert not missing_cols, f"Missing required columns in reviewed Excel file: {missing_cols}"

    for c in required_cols:
        df_reviewed[c] = df_reviewed[c].fillna("").astype(str).str.strip()

    corrupted_questions = df_reviewed[
        df_reviewed["question"].astype(str).str.contains(r"\?{3,}", regex=True, na=False)
    ].copy()

    assert len(corrupted_questions) == 0, (
        "Some questions are corrupted and appear as question marks. "
        "Do not use CSV/XLS. Recreate the reviewed file as XLSX from the original candidates file."
    )

    valid_reviewed = df_reviewed[
        df_reviewed["manual_gold_article_number"].ne("")
        | df_reviewed["manual_gold_document_unit_id"].ne("")
    ].copy()

    if len(valid_reviewed) == 0:
        display(HTML("""
        <div dir="rtl" style="text-align:right; line-height:2; font-size:16px;
                    background:#fff3cd; border-right:6px solid #ffc107; padding:12px;">
            تم العثور على ملف المراجعة اليدوية، لكن لا توجد صفوف معبأة فعلياً.
            سيتم تجاوز الدمج بدون إيقاف النوتبوك.
        </div>
        """))
        reviewed_extra_questions_df = pd.DataFrame()
        extra_questions_merged = False

    else:
        reviewed_extra_questions_df = valid_reviewed.copy()
        reviewed_extra_questions_df["gold_article_number"] = reviewed_extra_questions_df["manual_gold_article_number"]
        reviewed_extra_questions_df["gold_article_numbers"] = reviewed_extra_questions_df["manual_gold_article_number"]
        reviewed_extra_questions_df["gold_document_unit_id"] = reviewed_extra_questions_df["manual_gold_document_unit_id"]
        reviewed_extra_questions_df["gold_document_unit_ids"] = reviewed_extra_questions_df["manual_gold_document_unit_id"]
        reviewed_extra_questions_df["expected_answer"] = ""
        reviewed_extra_questions_df["gold_source_type"] = "legal_article"
        reviewed_extra_questions_df["is_out_of_scope"] = False
        reviewed_extra_questions_df["is_out_of_scope_bool"] = False

        for c in df_eval_run.columns:
            if c not in reviewed_extra_questions_df.columns:
                reviewed_extra_questions_df[c] = ""

        before_n = len(df_eval_run)
        df_eval_run = pd.concat(
            [df_eval_run, reviewed_extra_questions_df[df_eval_run.columns]],
            ignore_index=True
        ).drop_duplicates(subset=["question", "gold_document_unit_id", "gold_article_number"]).reset_index(drop=True)

        extra_questions_merged = True
        after_n = len(df_eval_run)

        df_eval_run.to_csv(STAGE03_DIR / "stage03_final_runnable_evaluation_dataset_with_reviewed_extra.csv", index=False, encoding="utf-8-sig")

        display(HTML(f"""
        <div dir="rtl" style="text-align:right; line-height:2; font-size:16px;
                    background:#e2f0d9; border-right:6px solid #70ad47; padding:12px;">
            تم دمج الأسئلة القانونية الإضافية بعد المراجعة اليدوية.
            <br>قبل الدمج: {before_n}
            <br>بعد الدمج: {after_n}
        </div>
        """))

display(HTML("<h3 style='color:#1f4e79'>Stage 12.8 — Optional Manual Extra Questions Merge</h3>"))
print("Extra questions merged:", extra_questions_merged)
print("df_eval_run rows:", len(df_eval_run))

Extra questions merged: False
df_eval_run rows: 155

In [24]:
# =========================================================
# Stage 13 - Run Retrieval Experiments FULL
# تشغيل جميع تجارب الاسترجاع لكل النماذج
# =========================================================

from IPython.display import display, Markdown
import pandas as pd
import numpy as np
import time

# ---------------------------------------------------------
# 1) Safety Checks
# ---------------------------------------------------------

required_objects = [
    "CORPORA",
    "df_eval_run",
    "TOP_K",
    "CANDIDATE_K",
    "STAGE03_DIR",
    "loaded_embedding_models",
    "relevance_vector",
    "reciprocal_rank",
    "ndcg_at_k",
    "bm25_retrieve",
    "dense_retrieve",
    "hybrid_retrieve",
]

missing_objects = [obj for obj in required_objects if obj not in globals()]

if missing_objects:
    raise NameError(f"Missing required objects before Stage 13: {missing_objects}")

if len(loaded_embedding_models) == 0:
    raise ValueError(
        "loaded_embedding_models is empty. "
        "Stage 13 cannot run Dense/Hybrid/Reranker. "
        "Please fix and rerun Stage 07 first."
    )

if "HYBRID_ALPHAS" not in globals():
    HYBRID_ALPHAS = [0.65, 0.8, 0.9]

if "RERANKER_ALPHA" not in globals():
    RERANKER_ALPHA = 0.8

if "reranker_model" not in globals():
    reranker_model = None

if "hybrid_rerank_retrieve" not in globals():
    print("Warning: hybrid_rerank_retrieve is not defined. Reranker experiments will be skipped.")
    reranker_model = None

# ---------------------------------------------------------
# 2) Run Information
# ---------------------------------------------------------

display(Markdown("""
<div dir="rtl" style="
    text-align:right;
    line-height:2;
    font-size:15px;
    font-family:Arial, Tahoma, sans-serif;
    background-color:#F8FBFD;
    border-right:5px solid #1F4E78;
    padding:14px;
    margin:12px 0;
    border-radius:6px;
">

<h3 style="color:#1F4E78; margin-top:0;">
Stage 13 — Full Retrieval Experiments
</h3>

<p>
سيتم في هذه الخلية تشغيل جميع إعدادات الاسترجاع:
BM25، Dense، Hybrid، و Hybrid + Reranker عند توفره.
</p>

<p>
تم إخفاء جدول إعدادات التجارب من هذه الخلية، وسيتم عرض النتائج لاحقًا في خلية منفصلة بشكل احترافي.
</p>

</div>
"""))

print("Available corpora:", list(CORPORA.keys()))
print("Available embedding models:", list(loaded_embedding_models.keys()))
print("Reranker available:", reranker_model is not None)
print("TOP_K:", TOP_K)
print("CANDIDATE_K:", CANDIDATE_K)
print("HYBRID_ALPHAS:", HYBRID_ALPHAS)
print("RERANKER_ALPHA:", RERANKER_ALPHA)

# ---------------------------------------------------------
# 3) Retrieval Wrapper
# ---------------------------------------------------------

def retrieve_with_config(query, corpus_name, retriever_name, model_key=None, alpha=None, top_k=5):
    start = time.time()

    if retriever_name == "dense":
        results = dense_retrieve(
            query,
            corpus_name,
            model_key,
            top_k=top_k
        )

    elif retriever_name == "bm25":
        results = bm25_retrieve(
            query,
            corpus_name,
            top_k=top_k
        )

    elif retriever_name == "hybrid":
        results = hybrid_retrieve(
            query,
            corpus_name,
            model_key,
            alpha=alpha,
            top_k=top_k,
            candidate_k=CANDIDATE_K
        )

    elif retriever_name == "hybrid_reranker":
        results = hybrid_rerank_retrieve(
            query,
            corpus_name,
            model_key,
            alpha=alpha,
            top_k=top_k,
            candidate_k=CANDIDATE_K
        )

    else:
        raise ValueError(f"Unknown retriever: {retriever_name}")

    latency = time.time() - start

    return results, latency

# ---------------------------------------------------------
# 4) Build Full Experiment Configurations
# ---------------------------------------------------------

experiment_configs = []

for corpus_name in CORPORA.keys():

    # BM25 baseline
    experiment_configs.append({
        "chunking_strategy": corpus_name,
        "embedding_model": "none",
        "retriever": "bm25",
        "alpha": None,
    })

    for model_key in loaded_embedding_models.keys():

        # Dense retrieval
        experiment_configs.append({
            "chunking_strategy": corpus_name,
            "embedding_model": model_key,
            "retriever": "dense",
            "alpha": None,
        })

        # Hybrid retrieval
        for alpha in HYBRID_ALPHAS:
            experiment_configs.append({
                "chunking_strategy": corpus_name,
                "embedding_model": model_key,
                "retriever": "hybrid",
                "alpha": alpha,
            })

        # Hybrid + Reranker
        if reranker_model is not None:
            experiment_configs.append({
                "chunking_strategy": corpus_name,
                "embedding_model": model_key,
                "retriever": "hybrid_reranker",
                "alpha": RERANKER_ALPHA,
            })

print("Total experiment configurations:", len(experiment_configs))

# لا نعرض جدول الإعدادات هنا لتجنب التداخل
# display(pd.DataFrame(experiment_configs))

# ---------------------------------------------------------
# 5) Run Full Experiments
# ---------------------------------------------------------

all_detail_rows = []

total_experiments = len(experiment_configs)
total_questions = len(df_eval_run)
total_runs = total_experiments * total_questions

print("=" * 100)
print("Total retrieval runs:", total_runs)
print("=" * 100)

run_counter = 0

for exp_idx, cfg in enumerate(experiment_configs, start=1):

    print("=" * 100)
    print(f"Experiment {exp_idx}/{total_experiments}:", cfg)
    print("=" * 100)

    for row_idx, eval_row in df_eval_run.iterrows():

        run_counter += 1
        query = str(eval_row["question"])

        print(
            f"[{run_counter}/{total_runs}] "
            f"Exp {exp_idx}/{total_experiments} | "
            f"{cfg['retriever']} | "
            f"{cfg['chunking_strategy']} | "
            f"{cfg['embedding_model']} | "
            f"{query[:80]}"
        )

        try:
            results, latency = retrieve_with_config(
                query=query,
                corpus_name=cfg["chunking_strategy"],
                retriever_name=cfg["retriever"],
                model_key=None if cfg["embedding_model"] == "none" else cfg["embedding_model"],
                alpha=cfg["alpha"],
                top_k=TOP_K,
            )

            runtime_error = ""

        except Exception as e:
            results = []
            latency = np.nan
            runtime_error = repr(e)
            print("Retrieval error:", runtime_error)

        rel = relevance_vector(
            eval_row,
            results,
            k=TOP_K
        )

        rr = reciprocal_rank(rel)
        ndcg5 = ndcg_at_k(rel)

        hit_at_1 = int(any(rel[:1]))
        hit_at_3 = int(any(rel[:3]))
        hit_at_5 = int(any(rel[:5]))

        top1 = results[0] if results else {}

        all_detail_rows.append({
            "eval_id": eval_row.get("eval_id", ""),
            "eval_type": eval_row.get("eval_type", ""),
            "question": query,

            "gold_document_unit_ids": eval_row.get(
                "gold_document_unit_ids",
                eval_row.get("gold_document_unit_id", "")
            ),

            "gold_article_numbers": eval_row.get(
                "gold_article_numbers",
                eval_row.get("gold_article_number", "")
            ),

            "chunking_strategy": cfg["chunking_strategy"],
            "embedding_model": cfg["embedding_model"],
            "retriever": cfg["retriever"],
            "alpha": cfg["alpha"],

            "hit_at_1": hit_at_1,
            "hit_at_3": hit_at_3,
            "hit_at_5": hit_at_5,
            "rr": rr,
            "ndcg_at_5": ndcg5,
            "latency_sec": latency,

            "top1_chunk_id": top1.get("chunk_id", ""),
            "top1_parent_document_id": top1.get("parent_document_id", ""),
            "top1_source_type": top1.get("source_type", ""),
            "top1_article_number": top1.get("article_number_int", ""),
            "top1_article_title": top1.get("article_title", ""),
            "top1_score": top1.get("score", np.nan),
            "top1_retrieval_backend": top1.get("retrieval_backend", ""),

            "top5_parent_document_ids": "|".join([
                str(r.get("parent_document_id", "")) for r in results[:5]
            ]),

            "top5_article_numbers": "|".join([
                str(r.get("article_number_int", "")) for r in results[:5]
            ]),

            "top5_relevance": "".join(map(str, rel[:5])),
            "runtime_error": runtime_error,
        })

        # Checkpoint كل 50 سجل
        if len(all_detail_rows) % 50 == 0:
            checkpoint_df = pd.DataFrame(all_detail_rows)
            checkpoint_path = STAGE03_DIR / "retrieval_evaluation_detailed_results_checkpoint.csv"

            checkpoint_df.to_csv(
                checkpoint_path,
                index=False,
                encoding="utf-8-sig"
            )

            print("Checkpoint saved:", checkpoint_path)

# ---------------------------------------------------------
# 6) Build Final Detailed Results
# ---------------------------------------------------------

retrieval_detail = pd.DataFrame(all_detail_rows)

numeric_cols = [
    "hit_at_1",
    "hit_at_3",
    "hit_at_5",
    "rr",
    "ndcg_at_5",
    "latency_sec",
    "top1_score",
]

for col in numeric_cols:
    if col in retrieval_detail.columns:
        retrieval_detail[col] = pd.to_numeric(
            retrieval_detail[col],
            errors="coerce"
        )

# ---------------------------------------------------------
# 7) Save Detailed Results
# ---------------------------------------------------------

detail_csv_path = STAGE03_DIR / "retrieval_evaluation_detailed_results.csv"
detail_xlsx_path = STAGE03_DIR / "retrieval_evaluation_detailed_results.xlsx"

retrieval_detail.to_csv(
    detail_csv_path,
    index=False,
    encoding="utf-8-sig"
)

retrieval_detail.to_excel(
    detail_xlsx_path,
    index=False
)

print("=" * 100)
print("Detailed results shape:", retrieval_detail.shape)
print("Saved CSV:", detail_csv_path)
print("Saved XLSX:", detail_xlsx_path)
print("=" * 100)

display(Markdown("""
<div dir="rtl" style="
    text-align:right;
    line-height:2;
    font-size:15px;
    font-family:Arial, Tahoma, sans-serif;
    background-color:#E2F0D9;
    border-right:5px solid #375623;
    padding:14px;
    margin:12px 0;
    border-radius:6px;
">

✅ <b>تم الانتهاء من تشغيل تجارب الاسترجاع الكاملة.</b><br>
تم حفظ النتائج التفصيلية في ملفات CSV و Excel.
اعرض الجداول الاحترافية في الخلية التالية فقط.

</div>
"""))

print("Stage 13 full retrieval experiments completed.")

<div dir="rtl" style="
    text-align:right;
    line-height:2;
    font-size:15px;
    font-family:Arial, Tahoma, sans-serif;
    background-color:#F8FBFD;
    border-right:5px solid #1F4E78;
    padding:14px;
    margin:12px 0;
    border-radius:6px;
">

<h3 style="color:#1F4E78; margin-top:0;">
Stage 13 — Full Retrieval Experiments
</h3>

<p>
سيتم في هذه الخلية تشغيل جميع إعدادات الاسترجاع:
BM25، Dense، Hybrid، و Hybrid + Reranker عند توفره.
</p>

<p>
تم إخفاء جدول إعدادات التجارب من هذه الخلية، وسيتم عرض النتائج لاحقًا في خلية منفصلة بشكل احترافي.
</p>

</div>

Available corpora: ['structural', 'fixed_size']
Available embedding models: ['e5_large', 'bge_m3']
Reranker available: True
TOP_K: 5
CANDIDATE_K: 50
HYBRID_ALPHAS: [0.65, 0.8, 0.9]
RERANKER_ALPHA: 0.8
Total experiment configurations: 22
====================================================================================================
Total retrieval runs: 3410
====================================================================================================
====================================================================================================
Experiment 1/22: {'chunking_strategy': 'structural', 'embedding_model': 'none', 'retriever': 'bm25', 'alpha': None}
====================================================================================================
[1/3410] Exp 1/22 | bm25 | structural | none | ما طريقة يمكنني إلغاء أو تعديل طلب تغيير المهنة؟
[2/3410] Exp 1/22 | bm25 | structural | none | أريد معرفة الطريقة المتبعة لتسديد قسط التأمين؟
[3/3410] Exp 1/22 | bm25 | structural | none | ما طريقةية معاملة محرم الموظفة عند مرافقتها أثناء ابتعاثها للدراسة أو التدريب أو
[4/3410] Exp 1/22 | bm25 | structural | none | أريد توضيح الحكم النظامي بخصوص: ماهي أهداف برنامج نطاقات المطور؟
[5/3410] Exp 1/22 | bm25 | structural | none | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية الجمع بين بدل المهنة المنصوص عليه
[6/3410] Exp 1/22 | bm25 | structural | none | أريد توضيح الحكم النظامي بخصوص: موظف أحيل للتحقيق أثناء إجراء المفاضلة لغرض التر
[7/3410] Exp 1/22 | bm25 | structural | none | ما طريقة يتم احتساب أجر الساعات الإضافية؟
[8/3410] Exp 1/22 | bm25 | structural | none | هل مسموح تعيين العمال بصفة مؤقتة طبقاً للائحة المعينين على بند الأجور؟
[9/3410] Exp 1/22 | bm25 | structural | none | هل يستطيع احتساب أيام المراجعة للمستشفيات داخل مقر العمل أو خارجه إجازة مرضية أو
[10/3410] Exp 1/22 | bm25 | structural | none | أريد توضيح الحكم النظامي بخصوص: اعرف حقوق العمال؟
[11/3410] Exp 1/22 | bm25 | structural | none | أريد توضيح الحكم النظامي بخصوص: في حال تم رصد مخالفات في ملف الأجور، أين أجد تفا
[12/3410] Exp 1/22 | bm25 | structural | none | أريد توضيح الحكم النظامي بخصوص: ما المقصود من كون عمال المستشفيات ضمن المساعدين

[13/3410] Exp 1/22 | bm25 | structural | none | أريد توضيح الحكم النظامي بخصوص: موظف قدم للرياض للالتحاق بدورة تدريبية وبعد انته
[14/3410] Exp 1/22 | bm25 | structural | none | أريد معرفة ما إذا كان يخصم بدل المواصلات من راتب الإجازة السنوية؟
[15/3410] Exp 1/22 | bm25 | structural | none | أريد توضيح الحكم النظامي بخصوص: موظف استقال من وظيفة بالمرتبة الرابعة ومن ثم عاد
[16/3410] Exp 1/22 | bm25 | structural | none | أريد معرفة عقد العمل؟
[17/3410] Exp 1/22 | bm25 | structural | none | أريد معرفة ما إذا كان تحسم رواتب العطل الرسمية والأعياد إذا سبقها غياب ولحقها غي
[18/3410] Exp 1/22 | bm25 | structural | none | أريد معرفة العمل المرن؟
[19/3410] Exp 1/22 | bm25 | structural | none | أريد توضيح الحكم النظامي بخصوص: ما مدى جواز منح الموظف المنقول بترقية الدرجة الإ
[20/3410] Exp 1/22 | bm25 | structural | none | أريد توضيح الحكم النظامي بخصوص: في حالة غياب الموظف عن العمل وإيقاع عقوبة تأديبي
[21/3410] Exp 1/22 | bm25 | structural | none | ما طريقة يتم طلب المدرب الاختياري قبل التقدم بطلب شهادة "مواءمة"؟
[22/3410] Exp 1/22 | bm25 | structural | none | هل مسموح نظاماً للعامل الانتقال من منشأة في النطاق الأحمر بدون إذن صاحب العمل إل

[23/3410] Exp 1/22 | bm25 | structural | none | أريد توضيح الحكم النظامي بخصوص: ما مدى امكانية ابتعاث أوايفاد العامل المعين على
[24/3410] Exp 1/22 | bm25 | structural | none | هل مسموح منح الموظف أثناء فترة التجربة إجازة استثنائية؟
[25/3410] Exp 1/22 | bm25 | structural | none | أريد توضيح الحكم النظامي بخصوص: ما مدى إلزام الموظف بالعمل خارج وقت الدوام، وهل
[26/3410] Exp 1/22 | bm25 | structural | none | أريد توضيح الحكم النظامي بخصوص: ما مدى انطباق المزايا المالية التي تصرف للمشاركي
[27/3410] Exp 1/22 | bm25 | structural | none | أريد معرفة ما إذا كان أستطيع رفع ملفات حماية الأجور عبر موقع وزارة الموارد البشر
[28/3410] Exp 1/22 | bm25 | structural | none | أريد معرفة الرسوم المطلوبة من المنشآت في برنامج "مواءمة"؟
[29/3410] Exp 1/22 | bm25 | structural | none | أريد معرفة ما إذا كان يتم إضافة البيانات التي تملكها الوزارة في الأصل للحقول الم
[30/3410] Exp 1/22 | bm25 | structural | none | أريد توضيح الحكم النظامي بخصوص: ماهي الحقوق والواجبات العامة للمرأة العاملة؟
[31/3410] Exp 1/22 | bm25 | structural | none | أريد معرفة خدمة نقل الموظفين؟
[32/3410] Exp 1/22 | bm25 | structural | none | أريد معرفة ما إذا كان ينطبق الشرط الجزائي على العامل أو صاحب العمل؟

[33/3410] Exp 1/22 | bm25 | structural | none | أريد معرفة شروط الخدمة؟
[34/3410] Exp 1/22 | bm25 | structural | none | أريد معرفة خدمات مبادرة تحسين العلاقة التعاقدية؟
[35/3410] Exp 1/22 | bm25 | structural | none | أريد توضيح الحكم النظامي بخصوص: إذا التحق الموظف بالتدريب أثناء إجازته الاستثنائ
[36/3410] Exp 1/22 | bm25 | structural | none | أريد معرفة ما إذا كان بإمكاني تعيين أي موظف لدي وإعطاءه صلاحية مفوض رواتب أو مدق
[37/3410] Exp 1/22 | bm25 | structural | none | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف المتدرب الذي انقطع أثناء ف
[38/3410] Exp 1/22 | bm25 | structural | none | أريد معرفة ما إذا كان يطالب المستخدم المثبت على وظيفة مشمولة بسلم رواتب الموظفين
[39/3410] Exp 1/22 | bm25 | structural | none | ما طريقة أعرف ما إذا كانت منشأتي ملزمة بتطبيق برنامج حماية الأجور؟
[40/3410] Exp 1/22 | bm25 | structural | none | أريد معرفة برنامج نطاقات؟ وكيف يحسن بيئة العمل للسعوديين؟

[41/3410] Exp 1/22 | bm25 | structural | none | أريد توضيح الحكم النظامي بخصوص: لماذا توجد رسوم مالية على برنامج "مواءمة"؟ وهل ت
[42/3410] Exp 1/22 | bm25 | structural | none | هل مسموح نقل العامل المعين على بند الأجور إلى إحدى الجهات الحكومية مع الاحتفاظ ب
[43/3410] Exp 1/22 | bm25 | structural | none | أريد معرفة ما إذا كان يحسب برنامج نطاقات من لديهم وظائف رسمية في الحكومة ودوام ج
[44/3410] Exp 1/22 | bm25 | structural | none | أريد توضيح الحكم النظامي بخصوص: ماهي آلية الترشيح للمرشحين؟
[45/3410] Exp 1/22 | bm25 | structural | none | ما طريقة يمكن للمستفيد (المؤمن له) معرفة اسم شركة التأمين التابع لها؟
[46/3410] Exp 1/22 | bm25 | structural | none | أريد معرفة إجراءات الانتقال خلال السنة الأولى في الحالات الاستثنائية؟
[47/3410] Exp 1/22 | bm25 | structural | none | أريد معرفة ما إذا كان تمكن البوابة والانظمة التابعة لها المستخدم من تخصيص الخدما
[48/3410] Exp 1/22 | bm25 | structural | none | أريد معرفة ما إذا كان بإمكان أي موظف في منشأتي أن يسجل في منصة مُدد ويقوم برفع م
[49/3410] Exp 1/22 | bm25 | structural | none | أريد توضيح الحكم النظامي بخصوص: ما مدى أحقية المعين على بند الأجور المكلف بالعمل
[50/3410] Exp 1/22 | bm25 | structural | none | أريد معرفة ما إذا كان تسري على شاغلي الوظائف المؤقتة القواعد الواردة في نظام الخ
Checkpoint saved: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\retrieval_evaluation_detailed_results_checkpoint.csv
[51/3410] Exp 1/22 | bm25 | structural | none | أريد توضيح الحكم النظامي بخصوص: كتابة العقد؟
[52/3410] Exp 1/22 | bm25 | structural | none | أريد معرفة ما إذا كان يترتب على العامل الوافد دفع أي رسوم حكومية (رخصة العمل – ا
[53/3410] Exp 1/22 | bm25 | structural | none | أريد توضيح الحكم النظامي بخصوص: موظف منح إجازة عادية تنتهي مع ابتداء عطلة أحد ال
[54/3410] Exp 1/22 | bm25 | structural | none | هل يستطيع للمستخدمين الوصول إلى قائمة عملياته او معاملاته السابقة في البوابة؟

[55/3410] Exp 1/22 | bm25 | structural | none | أريد توضيح الحكم النظامي بخصوص: ماهي خدمة الخروج النهائي؟
[56/3410] Exp 1/22 | bm25 | structural | none | أريد توضيح الحكم النظامي بخصوص: ما الفرق بين المهنة والمسمى الوظيفي؟
[57/3410] Exp 1/22 | bm25 | structural | none | ما طريقة يمكن التوفيق بين نصي المادتين (132) و (147) من اللائحة التنفيذية للموار
[58/3410] Exp 1/22 | bm25 | structural | none | هل يستطيع أن يتغير انطاق المنشأة دون تغيير في عدد العمالة خلال السنوات القادمة؟
[59/3410] Exp 1/22 | bm25 | structural | none | أريد توضيح الحكم النظامي بخصوص: لماذا يتوجب على المنشأة القيام بالتقيّيم الذاتي؟
[60/3410] Exp 1/22 | bm25 | structural | none | هل مسموح انهاء عقد العمل بسبب إعادة الهيكلة أو الظروف المالية للمنشأة؟
[61/3410] Exp 1/22 | bm25 | structural | none | أريد معرفة ما إذا كان تشمل إجازة أداء الامتحان الدراسي من يؤدي الامتحان خارج الم
[62/3410] Exp 1/22 | bm25 | structural | none | أريد توضيح الحكم النظامي بخصوص: موظف قررت الهيئة الطبية العامة معالجته في الداخل
[63/3410] Exp 1/22 | bm25 | structural | none | أريد معرفة ما إذا كان الخدمة تتيح تحديث بيانات العامل؟
[64/3410] Exp 1/22 | bm25 | structural | none | أريد توضيح الحكم النظامي بخصوص: ماهي الآلية لرفع نسب نطاقات تدريجيا؟ وكم هي المد
[65/3410] Exp 1/22 | bm25 | structural | none | هل يستطيع حفظ معاملة لخدمة معينة تم بدؤها من خلال البوابة والوصول إليها لاحقًا؟
[66/3410] Exp 1/22 | bm25 | structural | none | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية احتفاظ العامل المعين على بند الأج
[67/3410] Exp 1/22 | bm25 | structural | none | أريد توضيح الحكم النظامي بخصوص: موظف فصل من الخدمة بناءً على حكم نهائي من ديوان
[68/3410] Exp 1/22 | bm25 | structural | none | أريد معرفة ما إذا كان يشمل برنامج نطاقات المستثمر الأجنبي؟
[69/3410] Exp 1/22 | bm25 | structural | none | أريد توضيح الحكم النظامي بخصوص: الفئات المشمولة بقرار الالزام بالتأمين على عقد ا

[70/3410] Exp 1/22 | bm25 | structural | none | هل يستطيع تفعيل بند التنافسية في عقد العمل؟
[71/3410] Exp 1/22 | bm25 | structural | none | أريد توضيح الحكم النظامي بخصوص: ماهي الإجازات المستحقة للمرأة العاملة؟
[72/3410] Exp 1/22 | bm25 | structural | none | أريد معرفة الاجراء الذي سيتم تطبيقه في حال عدم التزام المنشأة بنسب نطاقات؟
[73/3410] Exp 1/22 | bm25 | structural | none | أريد توضيح الحكم النظامي بخصوص: ما مدى جواز إجبار الموظف على التمتع بإجازاته الع
[74/3410] Exp 1/22 | bm25 | structural | none | أريد معرفة الخدمات المقدمة في نظام مُدد لإدارة الرواتب؟
[75/3410] Exp 1/22 | bm25 | structural | none | أريد معرفة ما إذا كان تمكن البوابة والانظمة التابعة لها المستخدم من تعديل بيانات
[76/3410] Exp 1/22 | bm25 | structural | none | أريد معرفة المقصود بنصف صافي راتب الموظف مكفوف اليد ومن في حكمه وفقاً للمادة (19
[77/3410] Exp 1/22 | bm25 | structural | none | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف المنتدب من خارج المملكة إل
[78/3410] Exp 1/22 | bm25 | structural | none | ما طريقة أقدم شكوى على أحد الموظفين في مكاتب العمل؟ وما الحل إذا لم تتم الإفادة
[79/3410] Exp 1/22 | bm25 | structural | none | أريد توضيح الحكم النظامي بخصوص: ماهي آلية احتساب نسب التوطين بعد تطبيق نطاقات ال

[80/3410] Exp 1/22 | bm25 | structural | none | أريد توضيح الحكم النظامي بخصوص: مدة عمل عقد العامل السعودي؟
[81/3410] Exp 1/22 | bm25 | structural | none | ما طريقة يعامل العامل غير السعودي المعين على بند الأجور من حيث بدل النقل بعد صدو
[82/3410] Exp 1/22 | bm25 | structural | none | أريد توضيح الحكم النظامي بخصوص: ما خطوات تنفيذ الخدمة؟
[83/3410] Exp 1/22 | bm25 | structural | none | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية صرف بدل التفرغ للطبيبات خلال إجاز
[84/3410] Exp 1/22 | bm25 | structural | none | أريد معرفة ما إذا كان تسري أحكام لائحة المعينين على بند الأجور الصادرة بقرار مجل
[85/3410] Exp 1/22 | bm25 | structural | none | أريد معرفة ما إذا كان الخدمة متاحة للعامل؟
[86/3410] Exp 1/22 | bm25 | structural | none | أريد توضيح الحكم النظامي بخصوص: ما مدى صرف بدل تعيين لمن يتم تعيينه بوظيفة خاضعة
[87/3410] Exp 1/22 | bm25 | structural | none | أريد توضيح الحكم النظامي بخصوص: ماذا يقصد ببرنامج نطاقات المطور؟
[88/3410] Exp 1/22 | bm25 | structural | none | أريد معرفة ما إذا كان يجب ان يكون العامل مسجل على منشاة؟
[89/3410] Exp 1/22 | bm25 | structural | none | أريد توضيح الحكم النظامي بخصوص: ما مدى نظامية منح الموظف بعد تعيينه وفقاً لنظام
[90/3410] Exp 1/22 | bm25 | structural | none | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية صرف بدل الترحيل المنصوص عليه بالم
[91/3410] Exp 1/22 | bm25 | structural | none | أريد توضيح الحكم النظامي بخصوص: ما مدى استفادة العامل المعين على بند الأجور من م
[92/3410] Exp 1/22 | bm25 | structural | none | ما طريقة يمكنني معرفة إذا كنت مؤهل لتوثيق عقدي مع العامل/ة؟
[93/3410] Exp 1/22 | bm25 | structural | none | أريد معرفة ما إذا كان تحتسب مدة الإجازة الاستثنائية لغرض إكمال مدة السنة المطلوب

[94/3410] Exp 1/22 | bm25 | structural | none | أريد معرفة نظام إدارة الرواتب؟
[95/3410] Exp 1/22 | bm25 | structural | none | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف مكفوف اليد للعلاوة الدورية
[96/3410] Exp 1/22 | bm25 | structural | none | أريد توضيح الحكم النظامي بخصوص: في الاله الحاسبة الخاصة ببرنامج نطاقات المطور هل
[97/3410] Exp 1/22 | bm25 | structural | none | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية نقل العسكري إلى وظيفة مدنية؟
[98/3410] Exp 1/22 | bm25 | structural | none | أريد توضيح الحكم النظامي بخصوص: ماهي الحقوق العامة في عقد العمل؟
[99/3410] Exp 1/22 | bm25 | structural | none | ما طريقة يعامل الموظف المتدرب في الداخل أو الخارج في حالة إصابته بمرض وحصوله على
[100/3410] Exp 1/22 | bm25 | structural | none | أريد توضيح الحكم النظامي بخصوص: ماهي شروط وضوابط الإجازات للعامل؟
Checkpoint saved: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\retrieval_evaluation_detailed_results_checkpoint.csv
[101/3410] Exp 1/22 | bm25 | structural | none | أريد توضيح الحكم النظامي بخصوص: ما مدى امكانية صرف مكافأة نهاية الخدمة المنصوص ع
[102/3410] Exp 1/22 | bm25 | structural | none | في أي حالة ينتهي عقد العمل؟
[103/3410] Exp 1/22 | bm25 | structural | none | أريد توضيح الحكم النظامي بخصوص: موظف منح إجازة عادية بعد عطلة أحد العيدين مباشرة
[104/3410] Exp 1/22 | bm25 | structural | none | ما طريقة يمكن تصحيح فرع المنشأة الذي يعمل فيها العامل ونقله إلى الفرع الصحيح؟
[105/3410] Exp 1/22 | bm25 | structural | none | أريد توضيح الحكم النظامي بخصوص: ماذا يحتوي عقد العمل؟
[106/3410] Exp 1/22 | bm25 | structural | none | ما طريقة يتم التحقق من استلام العامل للأجر الذي سيتم التنفيذ عليه في عقد العمل ا

[107/3410] Exp 1/22 | bm25 | structural | none | أريد معرفة عدد أيام الإجازة بحالة زواج العامل؟
[108/3410] Exp 1/22 | bm25 | structural | none | أريد معرفة الحسابات التي يمكنني تفعيلها للموظفين للتعديل في حساب مدد الخاص بنظام
[109/3410] Exp 1/22 | bm25 | structural | none | أريد توضيح الحكم النظامي بخصوص: ماهي اشتراطات فترة التجربة؟
[110/3410] Exp 1/22 | bm25 | structural | none | أريد معرفة ما إذا كان النسخة العربية وغير العربية متطابقة من حيث الخدمات والوظائ
[111/3410] Exp 1/22 | bm25 | structural | none | ما طريقة يتم الاستفادة من خدمة التنقل الوظيفي للعمال الوافدين بين المنشآت؟
[112/3410] Exp 1/22 | bm25 | structural | none | أريد معرفة أنواع الشكاوى التي يمكن أن يقدمها الموظف على صاحب العمل؟
[113/3410] Exp 1/22 | bm25 | structural | none | هل مسموح نظاماً لصاحب العمل تشغيل المرأة العاملة بعد الوضع بمدة أقل من 6 أسابيع؟
[114/3410] Exp 1/22 | bm25 | structural | none | أريد معرفة ما إذا كان هناك لائحة وقانون يحمي الأطفال من العنف الأسري؟
[115/3410] Exp 1/22 | bm25 | structural | none | ما طريقةية تعويض العامل المعين على بند الأجور عن رصيده من الاجازات العادية عند ا

[116/3410] Exp 1/22 | bm25 | structural | none | أريد توضيح الحكم النظامي بخصوص: موظف مددت خدمته لمدة سنتين بعد بلوغه السن النظام
[117/3410] Exp 1/22 | bm25 | structural | none | هل يستطيع نقل العمالة داخل الكيان الواحد؟
[118/3410] Exp 1/22 | bm25 | structural | none | أريد معرفة ما إذا كان تغطي الوثيقة النفقات الطبية اللازمة لعلاج العامل المنزلي ب
[119/3410] Exp 1/22 | bm25 | structural | none | هل يستطيع إلغاء التأشيرة المصدرة من مساند؟
[120/3410] Exp 1/22 | bm25 | structural | none | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف الذي يشغل وظيفة خاضعة لنظا
[121/3410] Exp 1/22 | bm25 | structural | none | أريد معرفة ما إذا كان يحسم من راتب الموظف أيام غيابه عن العمل نتيجة مثوله أمام ا
[122/3410] Exp 1/22 | bm25 | structural | none | أريد توضيح الحكم النظامي بخصوص: موظف بعد احالته على التقاعد لبلوغ السن النظامية
[123/3410] Exp 1/22 | bm25 | structural | none | هل يستطيع تعديل المهنة بعد تطبيق المبادرة؟
[124/3410] Exp 1/22 | bm25 | structural | none | أريد معرفة ما إذا كان يستحق الموظف التعويض عن إجازته العادية إذا استقال قبل إكما
[125/3410] Exp 1/22 | bm25 | structural | none | ما طريقة يمكن الاستفادة من الخدمة؟
[126/3410] Exp 1/22 | bm25 | structural | none | أريد معرفة فترة الراحة اليومية للرضاعة؟
[127/3410] Exp 1/22 | bm25 | structural | none | في أي حالة يتاح تجديد رخصة العمل؟
[128/3410] Exp 1/22 | bm25 | structural | none | ما طريقة يتم حماية حقوق العامل؟
[129/3410] Exp 1/22 | bm25 | structural | none | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف المتدرب لمكافآت وبدلات الت
[130/3410] Exp 1/22 | bm25 | structural | none | أريد معرفة ما إذا كان يحسب من عمره أقل من 18 سنة ضمن نسبة التوطين؟

[131/3410] Exp 1/22 | bm25 | structural | none | أريد معرفة شروط أهلية العامل الوافد للاستفادة من خدمة التنقل الوظيفي؟
[132/3410] Exp 1/22 | bm25 | structural | none | كم مدة فترة التجربة في نظام العمل السعودي؟
[133/3410] Exp 1/22 | bm25 | structural | none | هل يجوز وضع العامل تحت التجربة أكثر من مرة لدى نفس صاحب العمل؟
[134/3410] Exp 1/22 | bm25 | structural | none | ما الحد الأقصى لساعات العمل اليومية في نظام العمل؟
[135/3410] Exp 1/22 | bm25 | structural | none | ما الحد الأقصى لساعات العمل الأسبوعية؟
[136/3410] Exp 1/22 | bm25 | structural | none | هل تختلف ساعات العمل في شهر رمضان؟

[137/3410] Exp 1/22 | bm25 | structural | none | ما مدة الإجازة السنوية المستحقة للعامل؟
[138/3410] Exp 1/22 | bm25 | structural | none | متى تزيد الإجازة السنوية إلى ثلاثين يومًا؟
[139/3410] Exp 1/22 | bm25 | structural | none | هل يستحق العامل أجرًا عن أيام الإجازة غير المستخدمة عند انتهاء العمل؟
[140/3410] Exp 1/22 | bm25 | structural | none | هل يستحق العامل إجازة عند الزواج أو وفاة أحد الأقارب؟
[141/3410] Exp 1/22 | bm25 | structural | none | هل للعامل الحق في إجازة مرضية؟
[142/3410] Exp 1/22 | bm25 | structural | none | ما حالات انتهاء عقد العمل؟
[143/3410] Exp 1/22 | bm25 | structural | none | ما مدة الإشعار عند إنهاء العقد غير محدد المدة؟
[144/3410] Exp 1/22 | bm25 | structural | none | متى يستحق العامل تعويضًا عند إنهاء العقد لسبب غير مشروع؟
[145/3410] Exp 1/22 | bm25 | structural | none | متى يجوز لصاحب العمل إنهاء العقد دون مكافأة أو تعويض؟
[146/3410] Exp 1/22 | bm25 | structural | none | متى يجوز للعامل ترك العمل دون إشعار مع احتفاظه بحقوقه؟
[147/3410] Exp 1/22 | bm25 | structural | none | متى يستحق العامل مكافأة نهاية الخدمة؟
[148/3410] Exp 1/22 | bm25 | structural | none | هل يحق لصاحب العمل نقل العامل من مكان عمله الأصلي؟
[149/3410] Exp 1/22 | bm25 | structural | none | ما المقصود بعقد العمل في نظام العمل؟
[150/3410] Exp 1/22 | bm25 | structural | none | كيف يتم دفع أجر العامل؟
Checkpoint saved: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\retrieval_evaluation_detailed_results_checkpoint.csv
[151/3410] Exp 1/22 | bm25 | structural | none | ما واجبات صاحب العمل تجاه العامل؟
[152/3410] Exp 1/22 | bm25 | structural | none | ما التزامات العامل في نظام العمل؟
[153/3410] Exp 1/22 | bm25 | structural | none | ما الحد الأقصى لساعات العمل الإضافية وكيف تُحتسب؟
[154/3410] Exp 1/22 | bm25 | structural | none | ما أحكام السلامة والصحة المهنية في بيئة العمل؟
[155/3410] Exp 1/22 | bm25 | structural | none | ما حقوق العاملة في إجازة الوضع؟
====================================================================================================
Experiment 2/22: {'chunking_strategy': 'structural', 'embedding_model': 'e5_large', 'retriever': 'dense', 'alpha': None}
====================================================================================================
[156/3410] Exp 2/22 | dense | structural | e5_large | ما طريقة يمكنني إلغاء أو تعديل طلب تغيير المهنة؟

[157/3410] Exp 2/22 | dense | structural | e5_large | أريد معرفة الطريقة المتبعة لتسديد قسط التأمين؟
[158/3410] Exp 2/22 | dense | structural | e5_large | ما طريقةية معاملة محرم الموظفة عند مرافقتها أثناء ابتعاثها للدراسة أو التدريب أو
[159/3410] Exp 2/22 | dense | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي أهداف برنامج نطاقات المطور؟
[160/3410] Exp 2/22 | dense | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية الجمع بين بدل المهنة المنصوص عليه
[161/3410] Exp 2/22 | dense | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: موظف أحيل للتحقيق أثناء إجراء المفاضلة لغرض التر
[162/3410] Exp 2/22 | dense | structural | e5_large | ما طريقة يتم احتساب أجر الساعات الإضافية؟

[163/3410] Exp 2/22 | dense | structural | e5_large | هل مسموح تعيين العمال بصفة مؤقتة طبقاً للائحة المعينين على بند الأجور؟
[164/3410] Exp 2/22 | dense | structural | e5_large | هل يستطيع احتساب أيام المراجعة للمستشفيات داخل مقر العمل أو خارجه إجازة مرضية أو
[165/3410] Exp 2/22 | dense | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: اعرف حقوق العمال؟
[166/3410] Exp 2/22 | dense | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: في حال تم رصد مخالفات في ملف الأجور، أين أجد تفا
[167/3410] Exp 2/22 | dense | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما المقصود من كون عمال المستشفيات ضمن المساعدين
[168/3410] Exp 2/22 | dense | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: موظف قدم للرياض للالتحاق بدورة تدريبية وبعد انته

[169/3410] Exp 2/22 | dense | structural | e5_large | أريد معرفة ما إذا كان يخصم بدل المواصلات من راتب الإجازة السنوية؟
[170/3410] Exp 2/22 | dense | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: موظف استقال من وظيفة بالمرتبة الرابعة ومن ثم عاد
[171/3410] Exp 2/22 | dense | structural | e5_large | أريد معرفة عقد العمل؟
[172/3410] Exp 2/22 | dense | structural | e5_large | أريد معرفة ما إذا كان تحسم رواتب العطل الرسمية والأعياد إذا سبقها غياب ولحقها غي
[173/3410] Exp 2/22 | dense | structural | e5_large | أريد معرفة العمل المرن؟
[174/3410] Exp 2/22 | dense | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى جواز منح الموظف المنقول بترقية الدرجة الإ
[175/3410] Exp 2/22 | dense | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: في حالة غياب الموظف عن العمل وإيقاع عقوبة تأديبي

[176/3410] Exp 2/22 | dense | structural | e5_large | ما طريقة يتم طلب المدرب الاختياري قبل التقدم بطلب شهادة "مواءمة"؟
[177/3410] Exp 2/22 | dense | structural | e5_large | هل مسموح نظاماً للعامل الانتقال من منشأة في النطاق الأحمر بدون إذن صاحب العمل إل
[178/3410] Exp 2/22 | dense | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى امكانية ابتعاث أوايفاد العامل المعين على
[179/3410] Exp 2/22 | dense | structural | e5_large | هل مسموح منح الموظف أثناء فترة التجربة إجازة استثنائية؟
[180/3410] Exp 2/22 | dense | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى إلزام الموظف بالعمل خارج وقت الدوام، وهل
[181/3410] Exp 2/22 | dense | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى انطباق المزايا المالية التي تصرف للمشاركي

[182/3410] Exp 2/22 | dense | structural | e5_large | أريد معرفة ما إذا كان أستطيع رفع ملفات حماية الأجور عبر موقع وزارة الموارد البشر
[183/3410] Exp 2/22 | dense | structural | e5_large | أريد معرفة الرسوم المطلوبة من المنشآت في برنامج "مواءمة"؟
[184/3410] Exp 2/22 | dense | structural | e5_large | أريد معرفة ما إذا كان يتم إضافة البيانات التي تملكها الوزارة في الأصل للحقول الم
[185/3410] Exp 2/22 | dense | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي الحقوق والواجبات العامة للمرأة العاملة؟
[186/3410] Exp 2/22 | dense | structural | e5_large | أريد معرفة خدمة نقل الموظفين؟
[187/3410] Exp 2/22 | dense | structural | e5_large | أريد معرفة ما إذا كان ينطبق الشرط الجزائي على العامل أو صاحب العمل؟
[188/3410] Exp 2/22 | dense | structural | e5_large | أريد معرفة شروط الخدمة؟
[189/3410] Exp 2/22 | dense | structural | e5_large | أريد معرفة خدمات مبادرة تحسين العلاقة التعاقدية؟
[190/3410] Exp 2/22 | dense | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: إذا التحق الموظف بالتدريب أثناء إجازته الاستثنائ

[191/3410] Exp 2/22 | dense | structural | e5_large | أريد معرفة ما إذا كان بإمكاني تعيين أي موظف لدي وإعطاءه صلاحية مفوض رواتب أو مدق
[192/3410] Exp 2/22 | dense | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف المتدرب الذي انقطع أثناء ف
[193/3410] Exp 2/22 | dense | structural | e5_large | أريد معرفة ما إذا كان يطالب المستخدم المثبت على وظيفة مشمولة بسلم رواتب الموظفين
[194/3410] Exp 2/22 | dense | structural | e5_large | ما طريقة أعرف ما إذا كانت منشأتي ملزمة بتطبيق برنامج حماية الأجور؟
[195/3410] Exp 2/22 | dense | structural | e5_large | أريد معرفة برنامج نطاقات؟ وكيف يحسن بيئة العمل للسعوديين؟
[196/3410] Exp 2/22 | dense | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: لماذا توجد رسوم مالية على برنامج "مواءمة"؟ وهل ت

[197/3410] Exp 2/22 | dense | structural | e5_large | هل مسموح نقل العامل المعين على بند الأجور إلى إحدى الجهات الحكومية مع الاحتفاظ ب
[198/3410] Exp 2/22 | dense | structural | e5_large | أريد معرفة ما إذا كان يحسب برنامج نطاقات من لديهم وظائف رسمية في الحكومة ودوام ج
[199/3410] Exp 2/22 | dense | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي آلية الترشيح للمرشحين؟
[200/3410] Exp 2/22 | dense | structural | e5_large | ما طريقة يمكن للمستفيد (المؤمن له) معرفة اسم شركة التأمين التابع لها؟
Checkpoint saved: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\retrieval_evaluation_detailed_results_checkpoint.csv
[201/3410] Exp 2/22 | dense | structural | e5_large | أريد معرفة إجراءات الانتقال خلال السنة الأولى في الحالات الاستثنائية؟
[202/3410] Exp 2/22 | dense | structural | e5_large | أريد معرفة ما إذا كان تمكن البوابة والانظمة التابعة لها المستخدم من تخصيص الخدما
[203/3410] Exp 2/22 | dense | structural | e5_large | أريد معرفة ما إذا كان بإمكان أي موظف في منشأتي أن يسجل في منصة مُدد ويقوم برفع م

[204/3410] Exp 2/22 | dense | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى أحقية المعين على بند الأجور المكلف بالعمل
[205/3410] Exp 2/22 | dense | structural | e5_large | أريد معرفة ما إذا كان تسري على شاغلي الوظائف المؤقتة القواعد الواردة في نظام الخ
[206/3410] Exp 2/22 | dense | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: كتابة العقد؟
[207/3410] Exp 2/22 | dense | structural | e5_large | أريد معرفة ما إذا كان يترتب على العامل الوافد دفع أي رسوم حكومية (رخصة العمل – ا
[208/3410] Exp 2/22 | dense | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: موظف منح إجازة عادية تنتهي مع ابتداء عطلة أحد ال
[209/3410] Exp 2/22 | dense | structural | e5_large | هل يستطيع للمستخدمين الوصول إلى قائمة عملياته او معاملاته السابقة في البوابة؟
[210/3410] Exp 2/22 | dense | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي خدمة الخروج النهائي؟

[211/3410] Exp 2/22 | dense | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما الفرق بين المهنة والمسمى الوظيفي؟
[212/3410] Exp 2/22 | dense | structural | e5_large | ما طريقة يمكن التوفيق بين نصي المادتين (132) و (147) من اللائحة التنفيذية للموار
[213/3410] Exp 2/22 | dense | structural | e5_large | هل يستطيع أن يتغير انطاق المنشأة دون تغيير في عدد العمالة خلال السنوات القادمة؟
[214/3410] Exp 2/22 | dense | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: لماذا يتوجب على المنشأة القيام بالتقيّيم الذاتي؟
[215/3410] Exp 2/22 | dense | structural | e5_large | هل مسموح انهاء عقد العمل بسبب إعادة الهيكلة أو الظروف المالية للمنشأة؟
[216/3410] Exp 2/22 | dense | structural | e5_large | أريد معرفة ما إذا كان تشمل إجازة أداء الامتحان الدراسي من يؤدي الامتحان خارج الم
[217/3410] Exp 2/22 | dense | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: موظف قررت الهيئة الطبية العامة معالجته في الداخل

[218/3410] Exp 2/22 | dense | structural | e5_large | أريد معرفة ما إذا كان الخدمة تتيح تحديث بيانات العامل؟
[219/3410] Exp 2/22 | dense | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي الآلية لرفع نسب نطاقات تدريجيا؟ وكم هي المد
[220/3410] Exp 2/22 | dense | structural | e5_large | هل يستطيع حفظ معاملة لخدمة معينة تم بدؤها من خلال البوابة والوصول إليها لاحقًا؟
[221/3410] Exp 2/22 | dense | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية احتفاظ العامل المعين على بند الأج
[222/3410] Exp 2/22 | dense | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: موظف فصل من الخدمة بناءً على حكم نهائي من ديوان
[223/3410] Exp 2/22 | dense | structural | e5_large | أريد معرفة ما إذا كان يشمل برنامج نطاقات المستثمر الأجنبي؟
[224/3410] Exp 2/22 | dense | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: الفئات المشمولة بقرار الالزام بالتأمين على عقد ا

[225/3410] Exp 2/22 | dense | structural | e5_large | هل يستطيع تفعيل بند التنافسية في عقد العمل؟
[226/3410] Exp 2/22 | dense | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي الإجازات المستحقة للمرأة العاملة؟
[227/3410] Exp 2/22 | dense | structural | e5_large | أريد معرفة الاجراء الذي سيتم تطبيقه في حال عدم التزام المنشأة بنسب نطاقات؟
[228/3410] Exp 2/22 | dense | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى جواز إجبار الموظف على التمتع بإجازاته الع
[229/3410] Exp 2/22 | dense | structural | e5_large | أريد معرفة الخدمات المقدمة في نظام مُدد لإدارة الرواتب؟
[230/3410] Exp 2/22 | dense | structural | e5_large | أريد معرفة ما إذا كان تمكن البوابة والانظمة التابعة لها المستخدم من تعديل بيانات
[231/3410] Exp 2/22 | dense | structural | e5_large | أريد معرفة المقصود بنصف صافي راتب الموظف مكفوف اليد ومن في حكمه وفقاً للمادة (19
[232/3410] Exp 2/22 | dense | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف المنتدب من خارج المملكة إل

[233/3410] Exp 2/22 | dense | structural | e5_large | ما طريقة أقدم شكوى على أحد الموظفين في مكاتب العمل؟ وما الحل إذا لم تتم الإفادة
[234/3410] Exp 2/22 | dense | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي آلية احتساب نسب التوطين بعد تطبيق نطاقات ال
[235/3410] Exp 2/22 | dense | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: مدة عمل عقد العامل السعودي؟
[236/3410] Exp 2/22 | dense | structural | e5_large | ما طريقة يعامل العامل غير السعودي المعين على بند الأجور من حيث بدل النقل بعد صدو
[237/3410] Exp 2/22 | dense | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما خطوات تنفيذ الخدمة؟
[238/3410] Exp 2/22 | dense | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية صرف بدل التفرغ للطبيبات خلال إجاز
[239/3410] Exp 2/22 | dense | structural | e5_large | أريد معرفة ما إذا كان تسري أحكام لائحة المعينين على بند الأجور الصادرة بقرار مجل

[240/3410] Exp 2/22 | dense | structural | e5_large | أريد معرفة ما إذا كان الخدمة متاحة للعامل؟
[241/3410] Exp 2/22 | dense | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى صرف بدل تعيين لمن يتم تعيينه بوظيفة خاضعة
[242/3410] Exp 2/22 | dense | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ماذا يقصد ببرنامج نطاقات المطور؟
[243/3410] Exp 2/22 | dense | structural | e5_large | أريد معرفة ما إذا كان يجب ان يكون العامل مسجل على منشاة؟
[244/3410] Exp 2/22 | dense | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى نظامية منح الموظف بعد تعيينه وفقاً لنظام
[245/3410] Exp 2/22 | dense | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية صرف بدل الترحيل المنصوص عليه بالم

[246/3410] Exp 2/22 | dense | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى استفادة العامل المعين على بند الأجور من م
[247/3410] Exp 2/22 | dense | structural | e5_large | ما طريقة يمكنني معرفة إذا كنت مؤهل لتوثيق عقدي مع العامل/ة؟
[248/3410] Exp 2/22 | dense | structural | e5_large | أريد معرفة ما إذا كان تحتسب مدة الإجازة الاستثنائية لغرض إكمال مدة السنة المطلوب
[249/3410] Exp 2/22 | dense | structural | e5_large | أريد معرفة نظام إدارة الرواتب؟
[250/3410] Exp 2/22 | dense | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف مكفوف اليد للعلاوة الدورية
Checkpoint saved: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\retrieval_evaluation_detailed_results_checkpoint.csv
[251/3410] Exp 2/22 | dense | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: في الاله الحاسبة الخاصة ببرنامج نطاقات المطور هل
[252/3410] Exp 2/22 | dense | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية نقل العسكري إلى وظيفة مدنية؟

[253/3410] Exp 2/22 | dense | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي الحقوق العامة في عقد العمل؟
[254/3410] Exp 2/22 | dense | structural | e5_large | ما طريقة يعامل الموظف المتدرب في الداخل أو الخارج في حالة إصابته بمرض وحصوله على
[255/3410] Exp 2/22 | dense | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي شروط وضوابط الإجازات للعامل؟
[256/3410] Exp 2/22 | dense | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى امكانية صرف مكافأة نهاية الخدمة المنصوص ع
[257/3410] Exp 2/22 | dense | structural | e5_large | في أي حالة ينتهي عقد العمل؟
[258/3410] Exp 2/22 | dense | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: موظف منح إجازة عادية بعد عطلة أحد العيدين مباشرة

[259/3410] Exp 2/22 | dense | structural | e5_large | ما طريقة يمكن تصحيح فرع المنشأة الذي يعمل فيها العامل ونقله إلى الفرع الصحيح؟
[260/3410] Exp 2/22 | dense | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ماذا يحتوي عقد العمل؟
[261/3410] Exp 2/22 | dense | structural | e5_large | ما طريقة يتم التحقق من استلام العامل للأجر الذي سيتم التنفيذ عليه في عقد العمل ا
[262/3410] Exp 2/22 | dense | structural | e5_large | أريد معرفة عدد أيام الإجازة بحالة زواج العامل؟
[263/3410] Exp 2/22 | dense | structural | e5_large | أريد معرفة الحسابات التي يمكنني تفعيلها للموظفين للتعديل في حساب مدد الخاص بنظام
[264/3410] Exp 2/22 | dense | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي اشتراطات فترة التجربة؟
[265/3410] Exp 2/22 | dense | structural | e5_large | أريد معرفة ما إذا كان النسخة العربية وغير العربية متطابقة من حيث الخدمات والوظائ

[266/3410] Exp 2/22 | dense | structural | e5_large | ما طريقة يتم الاستفادة من خدمة التنقل الوظيفي للعمال الوافدين بين المنشآت؟
[267/3410] Exp 2/22 | dense | structural | e5_large | أريد معرفة أنواع الشكاوى التي يمكن أن يقدمها الموظف على صاحب العمل؟
[268/3410] Exp 2/22 | dense | structural | e5_large | هل مسموح نظاماً لصاحب العمل تشغيل المرأة العاملة بعد الوضع بمدة أقل من 6 أسابيع؟
[269/3410] Exp 2/22 | dense | structural | e5_large | أريد معرفة ما إذا كان هناك لائحة وقانون يحمي الأطفال من العنف الأسري؟
[270/3410] Exp 2/22 | dense | structural | e5_large | ما طريقةية تعويض العامل المعين على بند الأجور عن رصيده من الاجازات العادية عند ا
[271/3410] Exp 2/22 | dense | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: موظف مددت خدمته لمدة سنتين بعد بلوغه السن النظام
[272/3410] Exp 2/22 | dense | structural | e5_large | هل يستطيع نقل العمالة داخل الكيان الواحد؟
[273/3410] Exp 2/22 | dense | structural | e5_large | أريد معرفة ما إذا كان تغطي الوثيقة النفقات الطبية اللازمة لعلاج العامل المنزلي ب

[274/3410] Exp 2/22 | dense | structural | e5_large | هل يستطيع إلغاء التأشيرة المصدرة من مساند؟
[275/3410] Exp 2/22 | dense | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف الذي يشغل وظيفة خاضعة لنظا
[276/3410] Exp 2/22 | dense | structural | e5_large | أريد معرفة ما إذا كان يحسم من راتب الموظف أيام غيابه عن العمل نتيجة مثوله أمام ا
[277/3410] Exp 2/22 | dense | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: موظف بعد احالته على التقاعد لبلوغ السن النظامية
[278/3410] Exp 2/22 | dense | structural | e5_large | هل يستطيع تعديل المهنة بعد تطبيق المبادرة؟
[279/3410] Exp 2/22 | dense | structural | e5_large | أريد معرفة ما إذا كان يستحق الموظف التعويض عن إجازته العادية إذا استقال قبل إكما
[280/3410] Exp 2/22 | dense | structural | e5_large | ما طريقة يمكن الاستفادة من الخدمة؟
[281/3410] Exp 2/22 | dense | structural | e5_large | أريد معرفة فترة الراحة اليومية للرضاعة؟

[282/3410] Exp 2/22 | dense | structural | e5_large | في أي حالة يتاح تجديد رخصة العمل؟
[283/3410] Exp 2/22 | dense | structural | e5_large | ما طريقة يتم حماية حقوق العامل؟
[284/3410] Exp 2/22 | dense | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف المتدرب لمكافآت وبدلات الت
[285/3410] Exp 2/22 | dense | structural | e5_large | أريد معرفة ما إذا كان يحسب من عمره أقل من 18 سنة ضمن نسبة التوطين؟
[286/3410] Exp 2/22 | dense | structural | e5_large | أريد معرفة شروط أهلية العامل الوافد للاستفادة من خدمة التنقل الوظيفي؟
[287/3410] Exp 2/22 | dense | structural | e5_large | كم مدة فترة التجربة في نظام العمل السعودي؟
[288/3410] Exp 2/22 | dense | structural | e5_large | هل يجوز وضع العامل تحت التجربة أكثر من مرة لدى نفس صاحب العمل؟
[289/3410] Exp 2/22 | dense | structural | e5_large | ما الحد الأقصى لساعات العمل اليومية في نظام العمل؟
[290/3410] Exp 2/22 | dense | structural | e5_large | ما الحد الأقصى لساعات العمل الأسبوعية؟
[291/3410] Exp 2/22 | dense | structural | e5_large | هل تختلف ساعات العمل في شهر رمضان؟

[292/3410] Exp 2/22 | dense | structural | e5_large | ما مدة الإجازة السنوية المستحقة للعامل؟
[293/3410] Exp 2/22 | dense | structural | e5_large | متى تزيد الإجازة السنوية إلى ثلاثين يومًا؟
[294/3410] Exp 2/22 | dense | structural | e5_large | هل يستحق العامل أجرًا عن أيام الإجازة غير المستخدمة عند انتهاء العمل؟
[295/3410] Exp 2/22 | dense | structural | e5_large | هل يستحق العامل إجازة عند الزواج أو وفاة أحد الأقارب؟
[296/3410] Exp 2/22 | dense | structural | e5_large | هل للعامل الحق في إجازة مرضية؟
[297/3410] Exp 2/22 | dense | structural | e5_large | ما حالات انتهاء عقد العمل؟
[298/3410] Exp 2/22 | dense | structural | e5_large | ما مدة الإشعار عند إنهاء العقد غير محدد المدة؟
[299/3410] Exp 2/22 | dense | structural | e5_large | متى يستحق العامل تعويضًا عند إنهاء العقد لسبب غير مشروع؟
[300/3410] Exp 2/22 | dense | structural | e5_large | متى يجوز لصاحب العمل إنهاء العقد دون مكافأة أو تعويض؟
Checkpoint saved: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\retrieval_evaluation_detailed_results_checkpoint.csv
[301/3410] Exp 2/22 | dense | structural | e5_large | متى يجوز للعامل ترك العمل دون إشعار مع احتفاظه بحقوقه؟

[302/3410] Exp 2/22 | dense | structural | e5_large | متى يستحق العامل مكافأة نهاية الخدمة؟
[303/3410] Exp 2/22 | dense | structural | e5_large | هل يحق لصاحب العمل نقل العامل من مكان عمله الأصلي؟
[304/3410] Exp 2/22 | dense | structural | e5_large | ما المقصود بعقد العمل في نظام العمل؟
[305/3410] Exp 2/22 | dense | structural | e5_large | كيف يتم دفع أجر العامل؟
[306/3410] Exp 2/22 | dense | structural | e5_large | ما واجبات صاحب العمل تجاه العامل؟
[307/3410] Exp 2/22 | dense | structural | e5_large | ما التزامات العامل في نظام العمل؟
[308/3410] Exp 2/22 | dense | structural | e5_large | ما الحد الأقصى لساعات العمل الإضافية وكيف تُحتسب؟
[309/3410] Exp 2/22 | dense | structural | e5_large | ما أحكام السلامة والصحة المهنية في بيئة العمل؟
[310/3410] Exp 2/22 | dense | structural | e5_large | ما حقوق العاملة في إجازة الوضع؟
====================================================================================================
Experiment 3/22: {'chunking_strategy': 'structural', 'embedding_model': 'e5_large', 'retriever': 'hybrid', 'alpha': 0.65}
====================================================================================================
[311/3410] Exp 3/22 | hybrid | structural | e5_large | ما طريقة يمكنني إلغاء أو تعديل طلب تغيير المهنة؟
[312/3410] Exp 3/22 | hybrid | structural | e5_large | أريد معرفة الطريقة المتبعة لتسديد قسط التأمين؟

[313/3410] Exp 3/22 | hybrid | structural | e5_large | ما طريقةية معاملة محرم الموظفة عند مرافقتها أثناء ابتعاثها للدراسة أو التدريب أو
[314/3410] Exp 3/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي أهداف برنامج نطاقات المطور؟
[315/3410] Exp 3/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية الجمع بين بدل المهنة المنصوص عليه
[316/3410] Exp 3/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: موظف أحيل للتحقيق أثناء إجراء المفاضلة لغرض التر

[317/3410] Exp 3/22 | hybrid | structural | e5_large | ما طريقة يتم احتساب أجر الساعات الإضافية؟
[318/3410] Exp 3/22 | hybrid | structural | e5_large | هل مسموح تعيين العمال بصفة مؤقتة طبقاً للائحة المعينين على بند الأجور؟
[319/3410] Exp 3/22 | hybrid | structural | e5_large | هل يستطيع احتساب أيام المراجعة للمستشفيات داخل مقر العمل أو خارجه إجازة مرضية أو
[320/3410] Exp 3/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: اعرف حقوق العمال؟
[321/3410] Exp 3/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: في حال تم رصد مخالفات في ملف الأجور، أين أجد تفا
[322/3410] Exp 3/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما المقصود من كون عمال المستشفيات ضمن المساعدين

[323/3410] Exp 3/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: موظف قدم للرياض للالتحاق بدورة تدريبية وبعد انته
[324/3410] Exp 3/22 | hybrid | structural | e5_large | أريد معرفة ما إذا كان يخصم بدل المواصلات من راتب الإجازة السنوية؟
[325/3410] Exp 3/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: موظف استقال من وظيفة بالمرتبة الرابعة ومن ثم عاد
[326/3410] Exp 3/22 | hybrid | structural | e5_large | أريد معرفة عقد العمل؟
[327/3410] Exp 3/22 | hybrid | structural | e5_large | أريد معرفة ما إذا كان تحسم رواتب العطل الرسمية والأعياد إذا سبقها غياب ولحقها غي

[328/3410] Exp 3/22 | hybrid | structural | e5_large | أريد معرفة العمل المرن؟
[329/3410] Exp 3/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى جواز منح الموظف المنقول بترقية الدرجة الإ
[330/3410] Exp 3/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: في حالة غياب الموظف عن العمل وإيقاع عقوبة تأديبي
[331/3410] Exp 3/22 | hybrid | structural | e5_large | ما طريقة يتم طلب المدرب الاختياري قبل التقدم بطلب شهادة "مواءمة"؟
[332/3410] Exp 3/22 | hybrid | structural | e5_large | هل مسموح نظاماً للعامل الانتقال من منشأة في النطاق الأحمر بدون إذن صاحب العمل إل

[333/3410] Exp 3/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى امكانية ابتعاث أوايفاد العامل المعين على
[334/3410] Exp 3/22 | hybrid | structural | e5_large | هل مسموح منح الموظف أثناء فترة التجربة إجازة استثنائية؟
[335/3410] Exp 3/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى إلزام الموظف بالعمل خارج وقت الدوام، وهل
[336/3410] Exp 3/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى انطباق المزايا المالية التي تصرف للمشاركي
[337/3410] Exp 3/22 | hybrid | structural | e5_large | أريد معرفة ما إذا كان أستطيع رفع ملفات حماية الأجور عبر موقع وزارة الموارد البشر

[338/3410] Exp 3/22 | hybrid | structural | e5_large | أريد معرفة الرسوم المطلوبة من المنشآت في برنامج "مواءمة"؟
[339/3410] Exp 3/22 | hybrid | structural | e5_large | أريد معرفة ما إذا كان يتم إضافة البيانات التي تملكها الوزارة في الأصل للحقول الم
[340/3410] Exp 3/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي الحقوق والواجبات العامة للمرأة العاملة؟
[341/3410] Exp 3/22 | hybrid | structural | e5_large | أريد معرفة خدمة نقل الموظفين؟
[342/3410] Exp 3/22 | hybrid | structural | e5_large | أريد معرفة ما إذا كان ينطبق الشرط الجزائي على العامل أو صاحب العمل؟
[343/3410] Exp 3/22 | hybrid | structural | e5_large | أريد معرفة شروط الخدمة؟
[344/3410] Exp 3/22 | hybrid | structural | e5_large | أريد معرفة خدمات مبادرة تحسين العلاقة التعاقدية؟

[345/3410] Exp 3/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: إذا التحق الموظف بالتدريب أثناء إجازته الاستثنائ
[346/3410] Exp 3/22 | hybrid | structural | e5_large | أريد معرفة ما إذا كان بإمكاني تعيين أي موظف لدي وإعطاءه صلاحية مفوض رواتب أو مدق
[347/3410] Exp 3/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف المتدرب الذي انقطع أثناء ف
[348/3410] Exp 3/22 | hybrid | structural | e5_large | أريد معرفة ما إذا كان يطالب المستخدم المثبت على وظيفة مشمولة بسلم رواتب الموظفين

[349/3410] Exp 3/22 | hybrid | structural | e5_large | ما طريقة أعرف ما إذا كانت منشأتي ملزمة بتطبيق برنامج حماية الأجور؟
[350/3410] Exp 3/22 | hybrid | structural | e5_large | أريد معرفة برنامج نطاقات؟ وكيف يحسن بيئة العمل للسعوديين؟
Checkpoint saved: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\retrieval_evaluation_detailed_results_checkpoint.csv
[351/3410] Exp 3/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: لماذا توجد رسوم مالية على برنامج "مواءمة"؟ وهل ت
[352/3410] Exp 3/22 | hybrid | structural | e5_large | هل مسموح نقل العامل المعين على بند الأجور إلى إحدى الجهات الحكومية مع الاحتفاظ ب
[353/3410] Exp 3/22 | hybrid | structural | e5_large | أريد معرفة ما إذا كان يحسب برنامج نطاقات من لديهم وظائف رسمية في الحكومة ودوام ج

[354/3410] Exp 3/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي آلية الترشيح للمرشحين؟
[355/3410] Exp 3/22 | hybrid | structural | e5_large | ما طريقة يمكن للمستفيد (المؤمن له) معرفة اسم شركة التأمين التابع لها؟
[356/3410] Exp 3/22 | hybrid | structural | e5_large | أريد معرفة إجراءات الانتقال خلال السنة الأولى في الحالات الاستثنائية؟
[357/3410] Exp 3/22 | hybrid | structural | e5_large | أريد معرفة ما إذا كان تمكن البوابة والانظمة التابعة لها المستخدم من تخصيص الخدما
[358/3410] Exp 3/22 | hybrid | structural | e5_large | أريد معرفة ما إذا كان بإمكان أي موظف في منشأتي أن يسجل في منصة مُدد ويقوم برفع م
[359/3410] Exp 3/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى أحقية المعين على بند الأجور المكلف بالعمل

[360/3410] Exp 3/22 | hybrid | structural | e5_large | أريد معرفة ما إذا كان تسري على شاغلي الوظائف المؤقتة القواعد الواردة في نظام الخ
[361/3410] Exp 3/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: كتابة العقد؟
[362/3410] Exp 3/22 | hybrid | structural | e5_large | أريد معرفة ما إذا كان يترتب على العامل الوافد دفع أي رسوم حكومية (رخصة العمل – ا
[363/3410] Exp 3/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: موظف منح إجازة عادية تنتهي مع ابتداء عطلة أحد ال
[364/3410] Exp 3/22 | hybrid | structural | e5_large | هل يستطيع للمستخدمين الوصول إلى قائمة عملياته او معاملاته السابقة في البوابة؟
[365/3410] Exp 3/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي خدمة الخروج النهائي؟

[366/3410] Exp 3/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما الفرق بين المهنة والمسمى الوظيفي؟
[367/3410] Exp 3/22 | hybrid | structural | e5_large | ما طريقة يمكن التوفيق بين نصي المادتين (132) و (147) من اللائحة التنفيذية للموار
[368/3410] Exp 3/22 | hybrid | structural | e5_large | هل يستطيع أن يتغير انطاق المنشأة دون تغيير في عدد العمالة خلال السنوات القادمة؟
[369/3410] Exp 3/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: لماذا يتوجب على المنشأة القيام بالتقيّيم الذاتي؟
[370/3410] Exp 3/22 | hybrid | structural | e5_large | هل مسموح انهاء عقد العمل بسبب إعادة الهيكلة أو الظروف المالية للمنشأة؟

[371/3410] Exp 3/22 | hybrid | structural | e5_large | أريد معرفة ما إذا كان تشمل إجازة أداء الامتحان الدراسي من يؤدي الامتحان خارج الم
[372/3410] Exp 3/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: موظف قررت الهيئة الطبية العامة معالجته في الداخل
[373/3410] Exp 3/22 | hybrid | structural | e5_large | أريد معرفة ما إذا كان الخدمة تتيح تحديث بيانات العامل؟
[374/3410] Exp 3/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي الآلية لرفع نسب نطاقات تدريجيا؟ وكم هي المد
[375/3410] Exp 3/22 | hybrid | structural | e5_large | هل يستطيع حفظ معاملة لخدمة معينة تم بدؤها من خلال البوابة والوصول إليها لاحقًا؟

[376/3410] Exp 3/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية احتفاظ العامل المعين على بند الأج
[377/3410] Exp 3/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: موظف فصل من الخدمة بناءً على حكم نهائي من ديوان
[378/3410] Exp 3/22 | hybrid | structural | e5_large | أريد معرفة ما إذا كان يشمل برنامج نطاقات المستثمر الأجنبي؟
[379/3410] Exp 3/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: الفئات المشمولة بقرار الالزام بالتأمين على عقد ا
[380/3410] Exp 3/22 | hybrid | structural | e5_large | هل يستطيع تفعيل بند التنافسية في عقد العمل؟
[381/3410] Exp 3/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي الإجازات المستحقة للمرأة العاملة؟

[382/3410] Exp 3/22 | hybrid | structural | e5_large | أريد معرفة الاجراء الذي سيتم تطبيقه في حال عدم التزام المنشأة بنسب نطاقات؟
[383/3410] Exp 3/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى جواز إجبار الموظف على التمتع بإجازاته الع
[384/3410] Exp 3/22 | hybrid | structural | e5_large | أريد معرفة الخدمات المقدمة في نظام مُدد لإدارة الرواتب؟
[385/3410] Exp 3/22 | hybrid | structural | e5_large | أريد معرفة ما إذا كان تمكن البوابة والانظمة التابعة لها المستخدم من تعديل بيانات
[386/3410] Exp 3/22 | hybrid | structural | e5_large | أريد معرفة المقصود بنصف صافي راتب الموظف مكفوف اليد ومن في حكمه وفقاً للمادة (19
[387/3410] Exp 3/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف المنتدب من خارج المملكة إل

[388/3410] Exp 3/22 | hybrid | structural | e5_large | ما طريقة أقدم شكوى على أحد الموظفين في مكاتب العمل؟ وما الحل إذا لم تتم الإفادة
[389/3410] Exp 3/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي آلية احتساب نسب التوطين بعد تطبيق نطاقات ال
[390/3410] Exp 3/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: مدة عمل عقد العامل السعودي؟
[391/3410] Exp 3/22 | hybrid | structural | e5_large | ما طريقة يعامل العامل غير السعودي المعين على بند الأجور من حيث بدل النقل بعد صدو
[392/3410] Exp 3/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما خطوات تنفيذ الخدمة؟
[393/3410] Exp 3/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية صرف بدل التفرغ للطبيبات خلال إجاز

[394/3410] Exp 3/22 | hybrid | structural | e5_large | أريد معرفة ما إذا كان تسري أحكام لائحة المعينين على بند الأجور الصادرة بقرار مجل
[395/3410] Exp 3/22 | hybrid | structural | e5_large | أريد معرفة ما إذا كان الخدمة متاحة للعامل؟
[396/3410] Exp 3/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى صرف بدل تعيين لمن يتم تعيينه بوظيفة خاضعة
[397/3410] Exp 3/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ماذا يقصد ببرنامج نطاقات المطور؟
[398/3410] Exp 3/22 | hybrid | structural | e5_large | أريد معرفة ما إذا كان يجب ان يكون العامل مسجل على منشاة؟
[399/3410] Exp 3/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى نظامية منح الموظف بعد تعيينه وفقاً لنظام

[400/3410] Exp 3/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية صرف بدل الترحيل المنصوص عليه بالم
Checkpoint saved: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\retrieval_evaluation_detailed_results_checkpoint.csv
[401/3410] Exp 3/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى استفادة العامل المعين على بند الأجور من م
[402/3410] Exp 3/22 | hybrid | structural | e5_large | ما طريقة يمكنني معرفة إذا كنت مؤهل لتوثيق عقدي مع العامل/ة؟
[403/3410] Exp 3/22 | hybrid | structural | e5_large | أريد معرفة ما إذا كان تحتسب مدة الإجازة الاستثنائية لغرض إكمال مدة السنة المطلوب

[404/3410] Exp 3/22 | hybrid | structural | e5_large | أريد معرفة نظام إدارة الرواتب؟
[405/3410] Exp 3/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف مكفوف اليد للعلاوة الدورية
[406/3410] Exp 3/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: في الاله الحاسبة الخاصة ببرنامج نطاقات المطور هل
[407/3410] Exp 3/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية نقل العسكري إلى وظيفة مدنية؟
[408/3410] Exp 3/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي الحقوق العامة في عقد العمل؟
[409/3410] Exp 3/22 | hybrid | structural | e5_large | ما طريقة يعامل الموظف المتدرب في الداخل أو الخارج في حالة إصابته بمرض وحصوله على

[410/3410] Exp 3/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي شروط وضوابط الإجازات للعامل؟
[411/3410] Exp 3/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى امكانية صرف مكافأة نهاية الخدمة المنصوص ع
[412/3410] Exp 3/22 | hybrid | structural | e5_large | في أي حالة ينتهي عقد العمل؟
[413/3410] Exp 3/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: موظف منح إجازة عادية بعد عطلة أحد العيدين مباشرة
[414/3410] Exp 3/22 | hybrid | structural | e5_large | ما طريقة يمكن تصحيح فرع المنشأة الذي يعمل فيها العامل ونقله إلى الفرع الصحيح؟

[415/3410] Exp 3/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ماذا يحتوي عقد العمل؟
[416/3410] Exp 3/22 | hybrid | structural | e5_large | ما طريقة يتم التحقق من استلام العامل للأجر الذي سيتم التنفيذ عليه في عقد العمل ا
[417/3410] Exp 3/22 | hybrid | structural | e5_large | أريد معرفة عدد أيام الإجازة بحالة زواج العامل؟
[418/3410] Exp 3/22 | hybrid | structural | e5_large | أريد معرفة الحسابات التي يمكنني تفعيلها للموظفين للتعديل في حساب مدد الخاص بنظام
[419/3410] Exp 3/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي اشتراطات فترة التجربة؟
[420/3410] Exp 3/22 | hybrid | structural | e5_large | أريد معرفة ما إذا كان النسخة العربية وغير العربية متطابقة من حيث الخدمات والوظائ

[421/3410] Exp 3/22 | hybrid | structural | e5_large | ما طريقة يتم الاستفادة من خدمة التنقل الوظيفي للعمال الوافدين بين المنشآت؟
[422/3410] Exp 3/22 | hybrid | structural | e5_large | أريد معرفة أنواع الشكاوى التي يمكن أن يقدمها الموظف على صاحب العمل؟
[423/3410] Exp 3/22 | hybrid | structural | e5_large | هل مسموح نظاماً لصاحب العمل تشغيل المرأة العاملة بعد الوضع بمدة أقل من 6 أسابيع؟
[424/3410] Exp 3/22 | hybrid | structural | e5_large | أريد معرفة ما إذا كان هناك لائحة وقانون يحمي الأطفال من العنف الأسري؟
[425/3410] Exp 3/22 | hybrid | structural | e5_large | ما طريقةية تعويض العامل المعين على بند الأجور عن رصيده من الاجازات العادية عند ا
[426/3410] Exp 3/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: موظف مددت خدمته لمدة سنتين بعد بلوغه السن النظام

[427/3410] Exp 3/22 | hybrid | structural | e5_large | هل يستطيع نقل العمالة داخل الكيان الواحد؟
[428/3410] Exp 3/22 | hybrid | structural | e5_large | أريد معرفة ما إذا كان تغطي الوثيقة النفقات الطبية اللازمة لعلاج العامل المنزلي ب
[429/3410] Exp 3/22 | hybrid | structural | e5_large | هل يستطيع إلغاء التأشيرة المصدرة من مساند؟
[430/3410] Exp 3/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف الذي يشغل وظيفة خاضعة لنظا
[431/3410] Exp 3/22 | hybrid | structural | e5_large | أريد معرفة ما إذا كان يحسم من راتب الموظف أيام غيابه عن العمل نتيجة مثوله أمام ا

[432/3410] Exp 3/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: موظف بعد احالته على التقاعد لبلوغ السن النظامية
[433/3410] Exp 3/22 | hybrid | structural | e5_large | هل يستطيع تعديل المهنة بعد تطبيق المبادرة؟
[434/3410] Exp 3/22 | hybrid | structural | e5_large | أريد معرفة ما إذا كان يستحق الموظف التعويض عن إجازته العادية إذا استقال قبل إكما
[435/3410] Exp 3/22 | hybrid | structural | e5_large | ما طريقة يمكن الاستفادة من الخدمة؟
[436/3410] Exp 3/22 | hybrid | structural | e5_large | أريد معرفة فترة الراحة اليومية للرضاعة؟
[437/3410] Exp 3/22 | hybrid | structural | e5_large | في أي حالة يتاح تجديد رخصة العمل؟
[438/3410] Exp 3/22 | hybrid | structural | e5_large | ما طريقة يتم حماية حقوق العامل؟

[439/3410] Exp 3/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف المتدرب لمكافآت وبدلات الت
[440/3410] Exp 3/22 | hybrid | structural | e5_large | أريد معرفة ما إذا كان يحسب من عمره أقل من 18 سنة ضمن نسبة التوطين؟
[441/3410] Exp 3/22 | hybrid | structural | e5_large | أريد معرفة شروط أهلية العامل الوافد للاستفادة من خدمة التنقل الوظيفي؟
[442/3410] Exp 3/22 | hybrid | structural | e5_large | كم مدة فترة التجربة في نظام العمل السعودي؟
[443/3410] Exp 3/22 | hybrid | structural | e5_large | هل يجوز وضع العامل تحت التجربة أكثر من مرة لدى نفس صاحب العمل؟
[444/3410] Exp 3/22 | hybrid | structural | e5_large | ما الحد الأقصى لساعات العمل اليومية في نظام العمل؟

[445/3410] Exp 3/22 | hybrid | structural | e5_large | ما الحد الأقصى لساعات العمل الأسبوعية؟
[446/3410] Exp 3/22 | hybrid | structural | e5_large | هل تختلف ساعات العمل في شهر رمضان؟
[447/3410] Exp 3/22 | hybrid | structural | e5_large | ما مدة الإجازة السنوية المستحقة للعامل؟
[448/3410] Exp 3/22 | hybrid | structural | e5_large | متى تزيد الإجازة السنوية إلى ثلاثين يومًا؟
[449/3410] Exp 3/22 | hybrid | structural | e5_large | هل يستحق العامل أجرًا عن أيام الإجازة غير المستخدمة عند انتهاء العمل؟
[450/3410] Exp 3/22 | hybrid | structural | e5_large | هل يستحق العامل إجازة عند الزواج أو وفاة أحد الأقارب؟
Checkpoint saved: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\retrieval_evaluation_detailed_results_checkpoint.csv
[451/3410] Exp 3/22 | hybrid | structural | e5_large | هل للعامل الحق في إجازة مرضية؟

[452/3410] Exp 3/22 | hybrid | structural | e5_large | ما حالات انتهاء عقد العمل؟
[453/3410] Exp 3/22 | hybrid | structural | e5_large | ما مدة الإشعار عند إنهاء العقد غير محدد المدة؟
[454/3410] Exp 3/22 | hybrid | structural | e5_large | متى يستحق العامل تعويضًا عند إنهاء العقد لسبب غير مشروع؟
[455/3410] Exp 3/22 | hybrid | structural | e5_large | متى يجوز لصاحب العمل إنهاء العقد دون مكافأة أو تعويض؟
[456/3410] Exp 3/22 | hybrid | structural | e5_large | متى يجوز للعامل ترك العمل دون إشعار مع احتفاظه بحقوقه؟
[457/3410] Exp 3/22 | hybrid | structural | e5_large | متى يستحق العامل مكافأة نهاية الخدمة؟
[458/3410] Exp 3/22 | hybrid | structural | e5_large | هل يحق لصاحب العمل نقل العامل من مكان عمله الأصلي؟

[459/3410] Exp 3/22 | hybrid | structural | e5_large | ما المقصود بعقد العمل في نظام العمل؟
[460/3410] Exp 3/22 | hybrid | structural | e5_large | كيف يتم دفع أجر العامل؟
[461/3410] Exp 3/22 | hybrid | structural | e5_large | ما واجبات صاحب العمل تجاه العامل؟
[462/3410] Exp 3/22 | hybrid | structural | e5_large | ما التزامات العامل في نظام العمل؟
[463/3410] Exp 3/22 | hybrid | structural | e5_large | ما الحد الأقصى لساعات العمل الإضافية وكيف تُحتسب؟
[464/3410] Exp 3/22 | hybrid | structural | e5_large | ما أحكام السلامة والصحة المهنية في بيئة العمل؟
[465/3410] Exp 3/22 | hybrid | structural | e5_large | ما حقوق العاملة في إجازة الوضع؟
====================================================================================================
Experiment 4/22: {'chunking_strategy': 'structural', 'embedding_model': 'e5_large', 'retriever': 'hybrid', 'alpha': 0.8}
====================================================================================================
[466/3410] Exp 4/22 | hybrid | structural | e5_large | ما طريقة يمكنني إلغاء أو تعديل طلب تغيير المهنة؟
[467/3410] Exp 4/22 | hybrid | structural | e5_large | أريد معرفة الطريقة المتبعة لتسديد قسط التأمين؟

[468/3410] Exp 4/22 | hybrid | structural | e5_large | ما طريقةية معاملة محرم الموظفة عند مرافقتها أثناء ابتعاثها للدراسة أو التدريب أو
[469/3410] Exp 4/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي أهداف برنامج نطاقات المطور؟
[470/3410] Exp 4/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية الجمع بين بدل المهنة المنصوص عليه
[471/3410] Exp 4/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: موظف أحيل للتحقيق أثناء إجراء المفاضلة لغرض التر
[472/3410] Exp 4/22 | hybrid | structural | e5_large | ما طريقة يتم احتساب أجر الساعات الإضافية؟

[473/3410] Exp 4/22 | hybrid | structural | e5_large | هل مسموح تعيين العمال بصفة مؤقتة طبقاً للائحة المعينين على بند الأجور؟
[474/3410] Exp 4/22 | hybrid | structural | e5_large | هل يستطيع احتساب أيام المراجعة للمستشفيات داخل مقر العمل أو خارجه إجازة مرضية أو
[475/3410] Exp 4/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: اعرف حقوق العمال؟
[476/3410] Exp 4/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: في حال تم رصد مخالفات في ملف الأجور، أين أجد تفا
[477/3410] Exp 4/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما المقصود من كون عمال المستشفيات ضمن المساعدين

[478/3410] Exp 4/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: موظف قدم للرياض للالتحاق بدورة تدريبية وبعد انته
[479/3410] Exp 4/22 | hybrid | structural | e5_large | أريد معرفة ما إذا كان يخصم بدل المواصلات من راتب الإجازة السنوية؟
[480/3410] Exp 4/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: موظف استقال من وظيفة بالمرتبة الرابعة ومن ثم عاد
[481/3410] Exp 4/22 | hybrid | structural | e5_large | أريد معرفة عقد العمل؟
[482/3410] Exp 4/22 | hybrid | structural | e5_large | أريد معرفة ما إذا كان تحسم رواتب العطل الرسمية والأعياد إذا سبقها غياب ولحقها غي

[483/3410] Exp 4/22 | hybrid | structural | e5_large | أريد معرفة العمل المرن؟
[484/3410] Exp 4/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى جواز منح الموظف المنقول بترقية الدرجة الإ
[485/3410] Exp 4/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: في حالة غياب الموظف عن العمل وإيقاع عقوبة تأديبي
[486/3410] Exp 4/22 | hybrid | structural | e5_large | ما طريقة يتم طلب المدرب الاختياري قبل التقدم بطلب شهادة "مواءمة"؟
[487/3410] Exp 4/22 | hybrid | structural | e5_large | هل مسموح نظاماً للعامل الانتقال من منشأة في النطاق الأحمر بدون إذن صاحب العمل إل

[488/3410] Exp 4/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى امكانية ابتعاث أوايفاد العامل المعين على
[489/3410] Exp 4/22 | hybrid | structural | e5_large | هل مسموح منح الموظف أثناء فترة التجربة إجازة استثنائية؟
[490/3410] Exp 4/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى إلزام الموظف بالعمل خارج وقت الدوام، وهل
[491/3410] Exp 4/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى انطباق المزايا المالية التي تصرف للمشاركي
[492/3410] Exp 4/22 | hybrid | structural | e5_large | أريد معرفة ما إذا كان أستطيع رفع ملفات حماية الأجور عبر موقع وزارة الموارد البشر

[493/3410] Exp 4/22 | hybrid | structural | e5_large | أريد معرفة الرسوم المطلوبة من المنشآت في برنامج "مواءمة"؟
[494/3410] Exp 4/22 | hybrid | structural | e5_large | أريد معرفة ما إذا كان يتم إضافة البيانات التي تملكها الوزارة في الأصل للحقول الم
[495/3410] Exp 4/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي الحقوق والواجبات العامة للمرأة العاملة؟
[496/3410] Exp 4/22 | hybrid | structural | e5_large | أريد معرفة خدمة نقل الموظفين؟
[497/3410] Exp 4/22 | hybrid | structural | e5_large | أريد معرفة ما إذا كان ينطبق الشرط الجزائي على العامل أو صاحب العمل؟
[498/3410] Exp 4/22 | hybrid | structural | e5_large | أريد معرفة شروط الخدمة؟

[499/3410] Exp 4/22 | hybrid | structural | e5_large | أريد معرفة خدمات مبادرة تحسين العلاقة التعاقدية؟
[500/3410] Exp 4/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: إذا التحق الموظف بالتدريب أثناء إجازته الاستثنائ
Checkpoint saved: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\retrieval_evaluation_detailed_results_checkpoint.csv
[501/3410] Exp 4/22 | hybrid | structural | e5_large | أريد معرفة ما إذا كان بإمكاني تعيين أي موظف لدي وإعطاءه صلاحية مفوض رواتب أو مدق
[502/3410] Exp 4/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف المتدرب الذي انقطع أثناء ف
[503/3410] Exp 4/22 | hybrid | structural | e5_large | أريد معرفة ما إذا كان يطالب المستخدم المثبت على وظيفة مشمولة بسلم رواتب الموظفين

[504/3410] Exp 4/22 | hybrid | structural | e5_large | ما طريقة أعرف ما إذا كانت منشأتي ملزمة بتطبيق برنامج حماية الأجور؟
[505/3410] Exp 4/22 | hybrid | structural | e5_large | أريد معرفة برنامج نطاقات؟ وكيف يحسن بيئة العمل للسعوديين؟
[506/3410] Exp 4/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: لماذا توجد رسوم مالية على برنامج "مواءمة"؟ وهل ت
[507/3410] Exp 4/22 | hybrid | structural | e5_large | هل مسموح نقل العامل المعين على بند الأجور إلى إحدى الجهات الحكومية مع الاحتفاظ ب
[508/3410] Exp 4/22 | hybrid | structural | e5_large | أريد معرفة ما إذا كان يحسب برنامج نطاقات من لديهم وظائف رسمية في الحكومة ودوام ج

[509/3410] Exp 4/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي آلية الترشيح للمرشحين؟
[510/3410] Exp 4/22 | hybrid | structural | e5_large | ما طريقة يمكن للمستفيد (المؤمن له) معرفة اسم شركة التأمين التابع لها؟
[511/3410] Exp 4/22 | hybrid | structural | e5_large | أريد معرفة إجراءات الانتقال خلال السنة الأولى في الحالات الاستثنائية؟
[512/3410] Exp 4/22 | hybrid | structural | e5_large | أريد معرفة ما إذا كان تمكن البوابة والانظمة التابعة لها المستخدم من تخصيص الخدما
[513/3410] Exp 4/22 | hybrid | structural | e5_large | أريد معرفة ما إذا كان بإمكان أي موظف في منشأتي أن يسجل في منصة مُدد ويقوم برفع م
[514/3410] Exp 4/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى أحقية المعين على بند الأجور المكلف بالعمل

[515/3410] Exp 4/22 | hybrid | structural | e5_large | أريد معرفة ما إذا كان تسري على شاغلي الوظائف المؤقتة القواعد الواردة في نظام الخ
[516/3410] Exp 4/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: كتابة العقد؟
[517/3410] Exp 4/22 | hybrid | structural | e5_large | أريد معرفة ما إذا كان يترتب على العامل الوافد دفع أي رسوم حكومية (رخصة العمل – ا
[518/3410] Exp 4/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: موظف منح إجازة عادية تنتهي مع ابتداء عطلة أحد ال
[519/3410] Exp 4/22 | hybrid | structural | e5_large | هل يستطيع للمستخدمين الوصول إلى قائمة عملياته او معاملاته السابقة في البوابة؟

[520/3410] Exp 4/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي خدمة الخروج النهائي؟
[521/3410] Exp 4/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما الفرق بين المهنة والمسمى الوظيفي؟
[522/3410] Exp 4/22 | hybrid | structural | e5_large | ما طريقة يمكن التوفيق بين نصي المادتين (132) و (147) من اللائحة التنفيذية للموار
[523/3410] Exp 4/22 | hybrid | structural | e5_large | هل يستطيع أن يتغير انطاق المنشأة دون تغيير في عدد العمالة خلال السنوات القادمة؟
[524/3410] Exp 4/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: لماذا يتوجب على المنشأة القيام بالتقيّيم الذاتي؟

[525/3410] Exp 4/22 | hybrid | structural | e5_large | هل مسموح انهاء عقد العمل بسبب إعادة الهيكلة أو الظروف المالية للمنشأة؟
[526/3410] Exp 4/22 | hybrid | structural | e5_large | أريد معرفة ما إذا كان تشمل إجازة أداء الامتحان الدراسي من يؤدي الامتحان خارج الم
[527/3410] Exp 4/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: موظف قررت الهيئة الطبية العامة معالجته في الداخل
[528/3410] Exp 4/22 | hybrid | structural | e5_large | أريد معرفة ما إذا كان الخدمة تتيح تحديث بيانات العامل؟
[529/3410] Exp 4/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي الآلية لرفع نسب نطاقات تدريجيا؟ وكم هي المد

[530/3410] Exp 4/22 | hybrid | structural | e5_large | هل يستطيع حفظ معاملة لخدمة معينة تم بدؤها من خلال البوابة والوصول إليها لاحقًا؟
[531/3410] Exp 4/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية احتفاظ العامل المعين على بند الأج
[532/3410] Exp 4/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: موظف فصل من الخدمة بناءً على حكم نهائي من ديوان
[533/3410] Exp 4/22 | hybrid | structural | e5_large | أريد معرفة ما إذا كان يشمل برنامج نطاقات المستثمر الأجنبي؟
[534/3410] Exp 4/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: الفئات المشمولة بقرار الالزام بالتأمين على عقد ا

[535/3410] Exp 4/22 | hybrid | structural | e5_large | هل يستطيع تفعيل بند التنافسية في عقد العمل؟
[536/3410] Exp 4/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي الإجازات المستحقة للمرأة العاملة؟
[537/3410] Exp 4/22 | hybrid | structural | e5_large | أريد معرفة الاجراء الذي سيتم تطبيقه في حال عدم التزام المنشأة بنسب نطاقات؟
[538/3410] Exp 4/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى جواز إجبار الموظف على التمتع بإجازاته الع
[539/3410] Exp 4/22 | hybrid | structural | e5_large | أريد معرفة الخدمات المقدمة في نظام مُدد لإدارة الرواتب؟
[540/3410] Exp 4/22 | hybrid | structural | e5_large | أريد معرفة ما إذا كان تمكن البوابة والانظمة التابعة لها المستخدم من تعديل بيانات

[541/3410] Exp 4/22 | hybrid | structural | e5_large | أريد معرفة المقصود بنصف صافي راتب الموظف مكفوف اليد ومن في حكمه وفقاً للمادة (19
[542/3410] Exp 4/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف المنتدب من خارج المملكة إل
[543/3410] Exp 4/22 | hybrid | structural | e5_large | ما طريقة أقدم شكوى على أحد الموظفين في مكاتب العمل؟ وما الحل إذا لم تتم الإفادة
[544/3410] Exp 4/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي آلية احتساب نسب التوطين بعد تطبيق نطاقات ال

[545/3410] Exp 4/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: مدة عمل عقد العامل السعودي؟
[546/3410] Exp 4/22 | hybrid | structural | e5_large | ما طريقة يعامل العامل غير السعودي المعين على بند الأجور من حيث بدل النقل بعد صدو
[547/3410] Exp 4/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما خطوات تنفيذ الخدمة؟
[548/3410] Exp 4/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية صرف بدل التفرغ للطبيبات خلال إجاز
[549/3410] Exp 4/22 | hybrid | structural | e5_large | أريد معرفة ما إذا كان تسري أحكام لائحة المعينين على بند الأجور الصادرة بقرار مجل

[550/3410] Exp 4/22 | hybrid | structural | e5_large | أريد معرفة ما إذا كان الخدمة متاحة للعامل؟
Checkpoint saved: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\retrieval_evaluation_detailed_results_checkpoint.csv
[551/3410] Exp 4/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى صرف بدل تعيين لمن يتم تعيينه بوظيفة خاضعة
[552/3410] Exp 4/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ماذا يقصد ببرنامج نطاقات المطور؟
[553/3410] Exp 4/22 | hybrid | structural | e5_large | أريد معرفة ما إذا كان يجب ان يكون العامل مسجل على منشاة؟
[554/3410] Exp 4/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى نظامية منح الموظف بعد تعيينه وفقاً لنظام

[555/3410] Exp 4/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية صرف بدل الترحيل المنصوص عليه بالم
[556/3410] Exp 4/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى استفادة العامل المعين على بند الأجور من م
[557/3410] Exp 4/22 | hybrid | structural | e5_large | ما طريقة يمكنني معرفة إذا كنت مؤهل لتوثيق عقدي مع العامل/ة؟
[558/3410] Exp 4/22 | hybrid | structural | e5_large | أريد معرفة ما إذا كان تحتسب مدة الإجازة الاستثنائية لغرض إكمال مدة السنة المطلوب

[559/3410] Exp 4/22 | hybrid | structural | e5_large | أريد معرفة نظام إدارة الرواتب؟
[560/3410] Exp 4/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف مكفوف اليد للعلاوة الدورية
[561/3410] Exp 4/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: في الاله الحاسبة الخاصة ببرنامج نطاقات المطور هل
[562/3410] Exp 4/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية نقل العسكري إلى وظيفة مدنية؟
[563/3410] Exp 4/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي الحقوق العامة في عقد العمل؟

[564/3410] Exp 4/22 | hybrid | structural | e5_large | ما طريقة يعامل الموظف المتدرب في الداخل أو الخارج في حالة إصابته بمرض وحصوله على
[565/3410] Exp 4/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي شروط وضوابط الإجازات للعامل؟
[566/3410] Exp 4/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى امكانية صرف مكافأة نهاية الخدمة المنصوص ع
[567/3410] Exp 4/22 | hybrid | structural | e5_large | في أي حالة ينتهي عقد العمل؟
[568/3410] Exp 4/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: موظف منح إجازة عادية بعد عطلة أحد العيدين مباشرة

[569/3410] Exp 4/22 | hybrid | structural | e5_large | ما طريقة يمكن تصحيح فرع المنشأة الذي يعمل فيها العامل ونقله إلى الفرع الصحيح؟
[570/3410] Exp 4/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ماذا يحتوي عقد العمل؟
[571/3410] Exp 4/22 | hybrid | structural | e5_large | ما طريقة يتم التحقق من استلام العامل للأجر الذي سيتم التنفيذ عليه في عقد العمل ا
[572/3410] Exp 4/22 | hybrid | structural | e5_large | أريد معرفة عدد أيام الإجازة بحالة زواج العامل؟
[573/3410] Exp 4/22 | hybrid | structural | e5_large | أريد معرفة الحسابات التي يمكنني تفعيلها للموظفين للتعديل في حساب مدد الخاص بنظام

[574/3410] Exp 4/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي اشتراطات فترة التجربة؟
[575/3410] Exp 4/22 | hybrid | structural | e5_large | أريد معرفة ما إذا كان النسخة العربية وغير العربية متطابقة من حيث الخدمات والوظائ
[576/3410] Exp 4/22 | hybrid | structural | e5_large | ما طريقة يتم الاستفادة من خدمة التنقل الوظيفي للعمال الوافدين بين المنشآت؟
[577/3410] Exp 4/22 | hybrid | structural | e5_large | أريد معرفة أنواع الشكاوى التي يمكن أن يقدمها الموظف على صاحب العمل؟
[578/3410] Exp 4/22 | hybrid | structural | e5_large | هل مسموح نظاماً لصاحب العمل تشغيل المرأة العاملة بعد الوضع بمدة أقل من 6 أسابيع؟
[579/3410] Exp 4/22 | hybrid | structural | e5_large | أريد معرفة ما إذا كان هناك لائحة وقانون يحمي الأطفال من العنف الأسري؟

[580/3410] Exp 4/22 | hybrid | structural | e5_large | ما طريقةية تعويض العامل المعين على بند الأجور عن رصيده من الاجازات العادية عند ا
[581/3410] Exp 4/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: موظف مددت خدمته لمدة سنتين بعد بلوغه السن النظام
[582/3410] Exp 4/22 | hybrid | structural | e5_large | هل يستطيع نقل العمالة داخل الكيان الواحد؟
[583/3410] Exp 4/22 | hybrid | structural | e5_large | أريد معرفة ما إذا كان تغطي الوثيقة النفقات الطبية اللازمة لعلاج العامل المنزلي ب
[584/3410] Exp 4/22 | hybrid | structural | e5_large | هل يستطيع إلغاء التأشيرة المصدرة من مساند؟

[585/3410] Exp 4/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف الذي يشغل وظيفة خاضعة لنظا
[586/3410] Exp 4/22 | hybrid | structural | e5_large | أريد معرفة ما إذا كان يحسم من راتب الموظف أيام غيابه عن العمل نتيجة مثوله أمام ا
[587/3410] Exp 4/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: موظف بعد احالته على التقاعد لبلوغ السن النظامية
[588/3410] Exp 4/22 | hybrid | structural | e5_large | هل يستطيع تعديل المهنة بعد تطبيق المبادرة؟
[589/3410] Exp 4/22 | hybrid | structural | e5_large | أريد معرفة ما إذا كان يستحق الموظف التعويض عن إجازته العادية إذا استقال قبل إكما

[590/3410] Exp 4/22 | hybrid | structural | e5_large | ما طريقة يمكن الاستفادة من الخدمة؟
[591/3410] Exp 4/22 | hybrid | structural | e5_large | أريد معرفة فترة الراحة اليومية للرضاعة؟
[592/3410] Exp 4/22 | hybrid | structural | e5_large | في أي حالة يتاح تجديد رخصة العمل؟
[593/3410] Exp 4/22 | hybrid | structural | e5_large | ما طريقة يتم حماية حقوق العامل؟
[594/3410] Exp 4/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف المتدرب لمكافآت وبدلات الت
[595/3410] Exp 4/22 | hybrid | structural | e5_large | أريد معرفة ما إذا كان يحسب من عمره أقل من 18 سنة ضمن نسبة التوطين؟
[596/3410] Exp 4/22 | hybrid | structural | e5_large | أريد معرفة شروط أهلية العامل الوافد للاستفادة من خدمة التنقل الوظيفي؟

[597/3410] Exp 4/22 | hybrid | structural | e5_large | كم مدة فترة التجربة في نظام العمل السعودي؟
[598/3410] Exp 4/22 | hybrid | structural | e5_large | هل يجوز وضع العامل تحت التجربة أكثر من مرة لدى نفس صاحب العمل؟
[599/3410] Exp 4/22 | hybrid | structural | e5_large | ما الحد الأقصى لساعات العمل اليومية في نظام العمل؟
[600/3410] Exp 4/22 | hybrid | structural | e5_large | ما الحد الأقصى لساعات العمل الأسبوعية؟
Checkpoint saved: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\retrieval_evaluation_detailed_results_checkpoint.csv
[601/3410] Exp 4/22 | hybrid | structural | e5_large | هل تختلف ساعات العمل في شهر رمضان؟
[602/3410] Exp 4/22 | hybrid | structural | e5_large | ما مدة الإجازة السنوية المستحقة للعامل؟
[603/3410] Exp 4/22 | hybrid | structural | e5_large | متى تزيد الإجازة السنوية إلى ثلاثين يومًا؟

[604/3410] Exp 4/22 | hybrid | structural | e5_large | هل يستحق العامل أجرًا عن أيام الإجازة غير المستخدمة عند انتهاء العمل؟
[605/3410] Exp 4/22 | hybrid | structural | e5_large | هل يستحق العامل إجازة عند الزواج أو وفاة أحد الأقارب؟
[606/3410] Exp 4/22 | hybrid | structural | e5_large | هل للعامل الحق في إجازة مرضية؟
[607/3410] Exp 4/22 | hybrid | structural | e5_large | ما حالات انتهاء عقد العمل؟
[608/3410] Exp 4/22 | hybrid | structural | e5_large | ما مدة الإشعار عند إنهاء العقد غير محدد المدة؟
[609/3410] Exp 4/22 | hybrid | structural | e5_large | متى يستحق العامل تعويضًا عند إنهاء العقد لسبب غير مشروع؟
[610/3410] Exp 4/22 | hybrid | structural | e5_large | متى يجوز لصاحب العمل إنهاء العقد دون مكافأة أو تعويض؟

[611/3410] Exp 4/22 | hybrid | structural | e5_large | متى يجوز للعامل ترك العمل دون إشعار مع احتفاظه بحقوقه؟
[612/3410] Exp 4/22 | hybrid | structural | e5_large | متى يستحق العامل مكافأة نهاية الخدمة؟
[613/3410] Exp 4/22 | hybrid | structural | e5_large | هل يحق لصاحب العمل نقل العامل من مكان عمله الأصلي؟
[614/3410] Exp 4/22 | hybrid | structural | e5_large | ما المقصود بعقد العمل في نظام العمل؟
[615/3410] Exp 4/22 | hybrid | structural | e5_large | كيف يتم دفع أجر العامل؟
[616/3410] Exp 4/22 | hybrid | structural | e5_large | ما واجبات صاحب العمل تجاه العامل؟

[617/3410] Exp 4/22 | hybrid | structural | e5_large | ما التزامات العامل في نظام العمل؟
[618/3410] Exp 4/22 | hybrid | structural | e5_large | ما الحد الأقصى لساعات العمل الإضافية وكيف تُحتسب؟
[619/3410] Exp 4/22 | hybrid | structural | e5_large | ما أحكام السلامة والصحة المهنية في بيئة العمل؟
[620/3410] Exp 4/22 | hybrid | structural | e5_large | ما حقوق العاملة في إجازة الوضع؟
====================================================================================================
Experiment 5/22: {'chunking_strategy': 'structural', 'embedding_model': 'e5_large', 'retriever': 'hybrid', 'alpha': 0.9}
====================================================================================================
[621/3410] Exp 5/22 | hybrid | structural | e5_large | ما طريقة يمكنني إلغاء أو تعديل طلب تغيير المهنة؟
[622/3410] Exp 5/22 | hybrid | structural | e5_large | أريد معرفة الطريقة المتبعة لتسديد قسط التأمين؟
[623/3410] Exp 5/22 | hybrid | structural | e5_large | ما طريقةية معاملة محرم الموظفة عند مرافقتها أثناء ابتعاثها للدراسة أو التدريب أو

[624/3410] Exp 5/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي أهداف برنامج نطاقات المطور؟
[625/3410] Exp 5/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية الجمع بين بدل المهنة المنصوص عليه
[626/3410] Exp 5/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: موظف أحيل للتحقيق أثناء إجراء المفاضلة لغرض التر
[627/3410] Exp 5/22 | hybrid | structural | e5_large | ما طريقة يتم احتساب أجر الساعات الإضافية؟
[628/3410] Exp 5/22 | hybrid | structural | e5_large | هل مسموح تعيين العمال بصفة مؤقتة طبقاً للائحة المعينين على بند الأجور؟

[629/3410] Exp 5/22 | hybrid | structural | e5_large | هل يستطيع احتساب أيام المراجعة للمستشفيات داخل مقر العمل أو خارجه إجازة مرضية أو
[630/3410] Exp 5/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: اعرف حقوق العمال؟
[631/3410] Exp 5/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: في حال تم رصد مخالفات في ملف الأجور، أين أجد تفا
[632/3410] Exp 5/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما المقصود من كون عمال المستشفيات ضمن المساعدين
[633/3410] Exp 5/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: موظف قدم للرياض للالتحاق بدورة تدريبية وبعد انته

[634/3410] Exp 5/22 | hybrid | structural | e5_large | أريد معرفة ما إذا كان يخصم بدل المواصلات من راتب الإجازة السنوية؟
[635/3410] Exp 5/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: موظف استقال من وظيفة بالمرتبة الرابعة ومن ثم عاد
[636/3410] Exp 5/22 | hybrid | structural | e5_large | أريد معرفة عقد العمل؟
[637/3410] Exp 5/22 | hybrid | structural | e5_large | أريد معرفة ما إذا كان تحسم رواتب العطل الرسمية والأعياد إذا سبقها غياب ولحقها غي
[638/3410] Exp 5/22 | hybrid | structural | e5_large | أريد معرفة العمل المرن؟
[639/3410] Exp 5/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى جواز منح الموظف المنقول بترقية الدرجة الإ

[640/3410] Exp 5/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: في حالة غياب الموظف عن العمل وإيقاع عقوبة تأديبي
[641/3410] Exp 5/22 | hybrid | structural | e5_large | ما طريقة يتم طلب المدرب الاختياري قبل التقدم بطلب شهادة "مواءمة"؟
[642/3410] Exp 5/22 | hybrid | structural | e5_large | هل مسموح نظاماً للعامل الانتقال من منشأة في النطاق الأحمر بدون إذن صاحب العمل إل
[643/3410] Exp 5/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى امكانية ابتعاث أوايفاد العامل المعين على
[644/3410] Exp 5/22 | hybrid | structural | e5_large | هل مسموح منح الموظف أثناء فترة التجربة إجازة استثنائية؟

[645/3410] Exp 5/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى إلزام الموظف بالعمل خارج وقت الدوام، وهل
[646/3410] Exp 5/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى انطباق المزايا المالية التي تصرف للمشاركي
[647/3410] Exp 5/22 | hybrid | structural | e5_large | أريد معرفة ما إذا كان أستطيع رفع ملفات حماية الأجور عبر موقع وزارة الموارد البشر
[648/3410] Exp 5/22 | hybrid | structural | e5_large | أريد معرفة الرسوم المطلوبة من المنشآت في برنامج "مواءمة"؟
[649/3410] Exp 5/22 | hybrid | structural | e5_large | أريد معرفة ما إذا كان يتم إضافة البيانات التي تملكها الوزارة في الأصل للحقول الم

[650/3410] Exp 5/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي الحقوق والواجبات العامة للمرأة العاملة؟
Checkpoint saved: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\retrieval_evaluation_detailed_results_checkpoint.csv
[651/3410] Exp 5/22 | hybrid | structural | e5_large | أريد معرفة خدمة نقل الموظفين؟
[652/3410] Exp 5/22 | hybrid | structural | e5_large | أريد معرفة ما إذا كان ينطبق الشرط الجزائي على العامل أو صاحب العمل؟
[653/3410] Exp 5/22 | hybrid | structural | e5_large | أريد معرفة شروط الخدمة؟
[654/3410] Exp 5/22 | hybrid | structural | e5_large | أريد معرفة خدمات مبادرة تحسين العلاقة التعاقدية؟
[655/3410] Exp 5/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: إذا التحق الموظف بالتدريب أثناء إجازته الاستثنائ

[656/3410] Exp 5/22 | hybrid | structural | e5_large | أريد معرفة ما إذا كان بإمكاني تعيين أي موظف لدي وإعطاءه صلاحية مفوض رواتب أو مدق
[657/3410] Exp 5/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف المتدرب الذي انقطع أثناء ف
[658/3410] Exp 5/22 | hybrid | structural | e5_large | أريد معرفة ما إذا كان يطالب المستخدم المثبت على وظيفة مشمولة بسلم رواتب الموظفين
[659/3410] Exp 5/22 | hybrid | structural | e5_large | ما طريقة أعرف ما إذا كانت منشأتي ملزمة بتطبيق برنامج حماية الأجور؟
[660/3410] Exp 5/22 | hybrid | structural | e5_large | أريد معرفة برنامج نطاقات؟ وكيف يحسن بيئة العمل للسعوديين؟

[661/3410] Exp 5/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: لماذا توجد رسوم مالية على برنامج "مواءمة"؟ وهل ت
[662/3410] Exp 5/22 | hybrid | structural | e5_large | هل مسموح نقل العامل المعين على بند الأجور إلى إحدى الجهات الحكومية مع الاحتفاظ ب
[663/3410] Exp 5/22 | hybrid | structural | e5_large | أريد معرفة ما إذا كان يحسب برنامج نطاقات من لديهم وظائف رسمية في الحكومة ودوام ج
[664/3410] Exp 5/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي آلية الترشيح للمرشحين؟
[665/3410] Exp 5/22 | hybrid | structural | e5_large | ما طريقة يمكن للمستفيد (المؤمن له) معرفة اسم شركة التأمين التابع لها؟
[666/3410] Exp 5/22 | hybrid | structural | e5_large | أريد معرفة إجراءات الانتقال خلال السنة الأولى في الحالات الاستثنائية؟

[667/3410] Exp 5/22 | hybrid | structural | e5_large | أريد معرفة ما إذا كان تمكن البوابة والانظمة التابعة لها المستخدم من تخصيص الخدما
[668/3410] Exp 5/22 | hybrid | structural | e5_large | أريد معرفة ما إذا كان بإمكان أي موظف في منشأتي أن يسجل في منصة مُدد ويقوم برفع م
[669/3410] Exp 5/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى أحقية المعين على بند الأجور المكلف بالعمل
[670/3410] Exp 5/22 | hybrid | structural | e5_large | أريد معرفة ما إذا كان تسري على شاغلي الوظائف المؤقتة القواعد الواردة في نظام الخ
[671/3410] Exp 5/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: كتابة العقد؟

[672/3410] Exp 5/22 | hybrid | structural | e5_large | أريد معرفة ما إذا كان يترتب على العامل الوافد دفع أي رسوم حكومية (رخصة العمل – ا
[673/3410] Exp 5/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: موظف منح إجازة عادية تنتهي مع ابتداء عطلة أحد ال
[674/3410] Exp 5/22 | hybrid | structural | e5_large | هل يستطيع للمستخدمين الوصول إلى قائمة عملياته او معاملاته السابقة في البوابة؟
[675/3410] Exp 5/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي خدمة الخروج النهائي؟
[676/3410] Exp 5/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما الفرق بين المهنة والمسمى الوظيفي؟
[677/3410] Exp 5/22 | hybrid | structural | e5_large | ما طريقة يمكن التوفيق بين نصي المادتين (132) و (147) من اللائحة التنفيذية للموار

[678/3410] Exp 5/22 | hybrid | structural | e5_large | هل يستطيع أن يتغير انطاق المنشأة دون تغيير في عدد العمالة خلال السنوات القادمة؟
[679/3410] Exp 5/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: لماذا يتوجب على المنشأة القيام بالتقيّيم الذاتي؟
[680/3410] Exp 5/22 | hybrid | structural | e5_large | هل مسموح انهاء عقد العمل بسبب إعادة الهيكلة أو الظروف المالية للمنشأة؟
[681/3410] Exp 5/22 | hybrid | structural | e5_large | أريد معرفة ما إذا كان تشمل إجازة أداء الامتحان الدراسي من يؤدي الامتحان خارج الم
[682/3410] Exp 5/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: موظف قررت الهيئة الطبية العامة معالجته في الداخل

[683/3410] Exp 5/22 | hybrid | structural | e5_large | أريد معرفة ما إذا كان الخدمة تتيح تحديث بيانات العامل؟
[684/3410] Exp 5/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي الآلية لرفع نسب نطاقات تدريجيا؟ وكم هي المد
[685/3410] Exp 5/22 | hybrid | structural | e5_large | هل يستطيع حفظ معاملة لخدمة معينة تم بدؤها من خلال البوابة والوصول إليها لاحقًا؟
[686/3410] Exp 5/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية احتفاظ العامل المعين على بند الأج
[687/3410] Exp 5/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: موظف فصل من الخدمة بناءً على حكم نهائي من ديوان

[688/3410] Exp 5/22 | hybrid | structural | e5_large | أريد معرفة ما إذا كان يشمل برنامج نطاقات المستثمر الأجنبي؟
[689/3410] Exp 5/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: الفئات المشمولة بقرار الالزام بالتأمين على عقد ا
[690/3410] Exp 5/22 | hybrid | structural | e5_large | هل يستطيع تفعيل بند التنافسية في عقد العمل؟
[691/3410] Exp 5/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي الإجازات المستحقة للمرأة العاملة؟
[692/3410] Exp 5/22 | hybrid | structural | e5_large | أريد معرفة الاجراء الذي سيتم تطبيقه في حال عدم التزام المنشأة بنسب نطاقات؟
[693/3410] Exp 5/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى جواز إجبار الموظف على التمتع بإجازاته الع

[694/3410] Exp 5/22 | hybrid | structural | e5_large | أريد معرفة الخدمات المقدمة في نظام مُدد لإدارة الرواتب؟
[695/3410] Exp 5/22 | hybrid | structural | e5_large | أريد معرفة ما إذا كان تمكن البوابة والانظمة التابعة لها المستخدم من تعديل بيانات
[696/3410] Exp 5/22 | hybrid | structural | e5_large | أريد معرفة المقصود بنصف صافي راتب الموظف مكفوف اليد ومن في حكمه وفقاً للمادة (19
[697/3410] Exp 5/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف المنتدب من خارج المملكة إل
[698/3410] Exp 5/22 | hybrid | structural | e5_large | ما طريقة أقدم شكوى على أحد الموظفين في مكاتب العمل؟ وما الحل إذا لم تتم الإفادة

[699/3410] Exp 5/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي آلية احتساب نسب التوطين بعد تطبيق نطاقات ال
[700/3410] Exp 5/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: مدة عمل عقد العامل السعودي؟
Checkpoint saved: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\retrieval_evaluation_detailed_results_checkpoint.csv
[701/3410] Exp 5/22 | hybrid | structural | e5_large | ما طريقة يعامل العامل غير السعودي المعين على بند الأجور من حيث بدل النقل بعد صدو
[702/3410] Exp 5/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما خطوات تنفيذ الخدمة؟
[703/3410] Exp 5/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية صرف بدل التفرغ للطبيبات خلال إجاز

[704/3410] Exp 5/22 | hybrid | structural | e5_large | أريد معرفة ما إذا كان تسري أحكام لائحة المعينين على بند الأجور الصادرة بقرار مجل
[705/3410] Exp 5/22 | hybrid | structural | e5_large | أريد معرفة ما إذا كان الخدمة متاحة للعامل؟
[706/3410] Exp 5/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى صرف بدل تعيين لمن يتم تعيينه بوظيفة خاضعة
[707/3410] Exp 5/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ماذا يقصد ببرنامج نطاقات المطور؟
[708/3410] Exp 5/22 | hybrid | structural | e5_large | أريد معرفة ما إذا كان يجب ان يكون العامل مسجل على منشاة؟

[709/3410] Exp 5/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى نظامية منح الموظف بعد تعيينه وفقاً لنظام
[710/3410] Exp 5/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية صرف بدل الترحيل المنصوص عليه بالم
[711/3410] Exp 5/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى استفادة العامل المعين على بند الأجور من م
[712/3410] Exp 5/22 | hybrid | structural | e5_large | ما طريقة يمكنني معرفة إذا كنت مؤهل لتوثيق عقدي مع العامل/ة؟

[713/3410] Exp 5/22 | hybrid | structural | e5_large | أريد معرفة ما إذا كان تحتسب مدة الإجازة الاستثنائية لغرض إكمال مدة السنة المطلوب
[714/3410] Exp 5/22 | hybrid | structural | e5_large | أريد معرفة نظام إدارة الرواتب؟
[715/3410] Exp 5/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف مكفوف اليد للعلاوة الدورية
[716/3410] Exp 5/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: في الاله الحاسبة الخاصة ببرنامج نطاقات المطور هل
[717/3410] Exp 5/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية نقل العسكري إلى وظيفة مدنية؟

[718/3410] Exp 5/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي الحقوق العامة في عقد العمل؟
[719/3410] Exp 5/22 | hybrid | structural | e5_large | ما طريقة يعامل الموظف المتدرب في الداخل أو الخارج في حالة إصابته بمرض وحصوله على
[720/3410] Exp 5/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي شروط وضوابط الإجازات للعامل؟
[721/3410] Exp 5/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى امكانية صرف مكافأة نهاية الخدمة المنصوص ع
[722/3410] Exp 5/22 | hybrid | structural | e5_large | في أي حالة ينتهي عقد العمل؟

[723/3410] Exp 5/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: موظف منح إجازة عادية بعد عطلة أحد العيدين مباشرة
[724/3410] Exp 5/22 | hybrid | structural | e5_large | ما طريقة يمكن تصحيح فرع المنشأة الذي يعمل فيها العامل ونقله إلى الفرع الصحيح؟
[725/3410] Exp 5/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ماذا يحتوي عقد العمل؟
[726/3410] Exp 5/22 | hybrid | structural | e5_large | ما طريقة يتم التحقق من استلام العامل للأجر الذي سيتم التنفيذ عليه في عقد العمل ا
[727/3410] Exp 5/22 | hybrid | structural | e5_large | أريد معرفة عدد أيام الإجازة بحالة زواج العامل؟

[728/3410] Exp 5/22 | hybrid | structural | e5_large | أريد معرفة الحسابات التي يمكنني تفعيلها للموظفين للتعديل في حساب مدد الخاص بنظام
[729/3410] Exp 5/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي اشتراطات فترة التجربة؟
[730/3410] Exp 5/22 | hybrid | structural | e5_large | أريد معرفة ما إذا كان النسخة العربية وغير العربية متطابقة من حيث الخدمات والوظائ
[731/3410] Exp 5/22 | hybrid | structural | e5_large | ما طريقة يتم الاستفادة من خدمة التنقل الوظيفي للعمال الوافدين بين المنشآت؟
[732/3410] Exp 5/22 | hybrid | structural | e5_large | أريد معرفة أنواع الشكاوى التي يمكن أن يقدمها الموظف على صاحب العمل؟
[733/3410] Exp 5/22 | hybrid | structural | e5_large | هل مسموح نظاماً لصاحب العمل تشغيل المرأة العاملة بعد الوضع بمدة أقل من 6 أسابيع؟

[734/3410] Exp 5/22 | hybrid | structural | e5_large | أريد معرفة ما إذا كان هناك لائحة وقانون يحمي الأطفال من العنف الأسري؟
[735/3410] Exp 5/22 | hybrid | structural | e5_large | ما طريقةية تعويض العامل المعين على بند الأجور عن رصيده من الاجازات العادية عند ا
[736/3410] Exp 5/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: موظف مددت خدمته لمدة سنتين بعد بلوغه السن النظام
[737/3410] Exp 5/22 | hybrid | structural | e5_large | هل يستطيع نقل العمالة داخل الكيان الواحد؟
[738/3410] Exp 5/22 | hybrid | structural | e5_large | أريد معرفة ما إذا كان تغطي الوثيقة النفقات الطبية اللازمة لعلاج العامل المنزلي ب

[739/3410] Exp 5/22 | hybrid | structural | e5_large | هل يستطيع إلغاء التأشيرة المصدرة من مساند؟
[740/3410] Exp 5/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف الذي يشغل وظيفة خاضعة لنظا
[741/3410] Exp 5/22 | hybrid | structural | e5_large | أريد معرفة ما إذا كان يحسم من راتب الموظف أيام غيابه عن العمل نتيجة مثوله أمام ا
[742/3410] Exp 5/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: موظف بعد احالته على التقاعد لبلوغ السن النظامية
[743/3410] Exp 5/22 | hybrid | structural | e5_large | هل يستطيع تعديل المهنة بعد تطبيق المبادرة؟

[744/3410] Exp 5/22 | hybrid | structural | e5_large | أريد معرفة ما إذا كان يستحق الموظف التعويض عن إجازته العادية إذا استقال قبل إكما
[745/3410] Exp 5/22 | hybrid | structural | e5_large | ما طريقة يمكن الاستفادة من الخدمة؟
[746/3410] Exp 5/22 | hybrid | structural | e5_large | أريد معرفة فترة الراحة اليومية للرضاعة؟
[747/3410] Exp 5/22 | hybrid | structural | e5_large | في أي حالة يتاح تجديد رخصة العمل؟
[748/3410] Exp 5/22 | hybrid | structural | e5_large | ما طريقة يتم حماية حقوق العامل؟
[749/3410] Exp 5/22 | hybrid | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف المتدرب لمكافآت وبدلات الت
[750/3410] Exp 5/22 | hybrid | structural | e5_large | أريد معرفة ما إذا كان يحسب من عمره أقل من 18 سنة ضمن نسبة التوطين؟

Checkpoint saved: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\retrieval_evaluation_detailed_results_checkpoint.csv
[751/3410] Exp 5/22 | hybrid | structural | e5_large | أريد معرفة شروط أهلية العامل الوافد للاستفادة من خدمة التنقل الوظيفي؟
[752/3410] Exp 5/22 | hybrid | structural | e5_large | كم مدة فترة التجربة في نظام العمل السعودي؟
[753/3410] Exp 5/22 | hybrid | structural | e5_large | هل يجوز وضع العامل تحت التجربة أكثر من مرة لدى نفس صاحب العمل؟
[754/3410] Exp 5/22 | hybrid | structural | e5_large | ما الحد الأقصى لساعات العمل اليومية في نظام العمل؟
[755/3410] Exp 5/22 | hybrid | structural | e5_large | ما الحد الأقصى لساعات العمل الأسبوعية؟
[756/3410] Exp 5/22 | hybrid | structural | e5_large | هل تختلف ساعات العمل في شهر رمضان؟
[757/3410] Exp 5/22 | hybrid | structural | e5_large | ما مدة الإجازة السنوية المستحقة للعامل؟

[758/3410] Exp 5/22 | hybrid | structural | e5_large | متى تزيد الإجازة السنوية إلى ثلاثين يومًا؟
[759/3410] Exp 5/22 | hybrid | structural | e5_large | هل يستحق العامل أجرًا عن أيام الإجازة غير المستخدمة عند انتهاء العمل؟
[760/3410] Exp 5/22 | hybrid | structural | e5_large | هل يستحق العامل إجازة عند الزواج أو وفاة أحد الأقارب؟
[761/3410] Exp 5/22 | hybrid | structural | e5_large | هل للعامل الحق في إجازة مرضية؟
[762/3410] Exp 5/22 | hybrid | structural | e5_large | ما حالات انتهاء عقد العمل؟
[763/3410] Exp 5/22 | hybrid | structural | e5_large | ما مدة الإشعار عند إنهاء العقد غير محدد المدة؟
[764/3410] Exp 5/22 | hybrid | structural | e5_large | متى يستحق العامل تعويضًا عند إنهاء العقد لسبب غير مشروع؟

[765/3410] Exp 5/22 | hybrid | structural | e5_large | متى يجوز لصاحب العمل إنهاء العقد دون مكافأة أو تعويض؟
[766/3410] Exp 5/22 | hybrid | structural | e5_large | متى يجوز للعامل ترك العمل دون إشعار مع احتفاظه بحقوقه؟
[767/3410] Exp 5/22 | hybrid | structural | e5_large | متى يستحق العامل مكافأة نهاية الخدمة؟
[768/3410] Exp 5/22 | hybrid | structural | e5_large | هل يحق لصاحب العمل نقل العامل من مكان عمله الأصلي؟
[769/3410] Exp 5/22 | hybrid | structural | e5_large | ما المقصود بعقد العمل في نظام العمل؟
[770/3410] Exp 5/22 | hybrid | structural | e5_large | كيف يتم دفع أجر العامل؟
[771/3410] Exp 5/22 | hybrid | structural | e5_large | ما واجبات صاحب العمل تجاه العامل؟

[772/3410] Exp 5/22 | hybrid | structural | e5_large | ما التزامات العامل في نظام العمل؟
[773/3410] Exp 5/22 | hybrid | structural | e5_large | ما الحد الأقصى لساعات العمل الإضافية وكيف تُحتسب؟
[774/3410] Exp 5/22 | hybrid | structural | e5_large | ما أحكام السلامة والصحة المهنية في بيئة العمل؟
[775/3410] Exp 5/22 | hybrid | structural | e5_large | ما حقوق العاملة في إجازة الوضع؟
====================================================================================================
Experiment 6/22: {'chunking_strategy': 'structural', 'embedding_model': 'e5_large', 'retriever': 'hybrid_reranker', 'alpha': 0.8}
====================================================================================================
[776/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | ما طريقة يمكنني إلغاء أو تعديل طلب تغيير المهنة؟

[777/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد معرفة الطريقة المتبعة لتسديد قسط التأمين؟

[778/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | ما طريقةية معاملة محرم الموظفة عند مرافقتها أثناء ابتعاثها للدراسة أو التدريب أو

[779/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي أهداف برنامج نطاقات المطور؟

[780/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية الجمع بين بدل المهنة المنصوص عليه

[781/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: موظف أحيل للتحقيق أثناء إجراء المفاضلة لغرض التر

[782/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | ما طريقة يتم احتساب أجر الساعات الإضافية؟

[783/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | هل مسموح تعيين العمال بصفة مؤقتة طبقاً للائحة المعينين على بند الأجور؟

[784/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | هل يستطيع احتساب أيام المراجعة للمستشفيات داخل مقر العمل أو خارجه إجازة مرضية أو

[785/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: اعرف حقوق العمال؟

[786/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: في حال تم رصد مخالفات في ملف الأجور، أين أجد تفا

[787/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما المقصود من كون عمال المستشفيات ضمن المساعدين

[788/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: موظف قدم للرياض للالتحاق بدورة تدريبية وبعد انته

[789/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد معرفة ما إذا كان يخصم بدل المواصلات من راتب الإجازة السنوية؟

[790/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: موظف استقال من وظيفة بالمرتبة الرابعة ومن ثم عاد

[791/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد معرفة عقد العمل؟

[792/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد معرفة ما إذا كان تحسم رواتب العطل الرسمية والأعياد إذا سبقها غياب ولحقها غي

[793/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد معرفة العمل المرن؟

[794/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى جواز منح الموظف المنقول بترقية الدرجة الإ

[795/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: في حالة غياب الموظف عن العمل وإيقاع عقوبة تأديبي

[796/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | ما طريقة يتم طلب المدرب الاختياري قبل التقدم بطلب شهادة "مواءمة"؟

[797/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | هل مسموح نظاماً للعامل الانتقال من منشأة في النطاق الأحمر بدون إذن صاحب العمل إل

[798/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى امكانية ابتعاث أوايفاد العامل المعين على

[799/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | هل مسموح منح الموظف أثناء فترة التجربة إجازة استثنائية؟

[800/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى إلزام الموظف بالعمل خارج وقت الدوام، وهل

Checkpoint saved: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\retrieval_evaluation_detailed_results_checkpoint.csv
[801/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى انطباق المزايا المالية التي تصرف للمشاركي

[802/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد معرفة ما إذا كان أستطيع رفع ملفات حماية الأجور عبر موقع وزارة الموارد البشر

[803/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد معرفة الرسوم المطلوبة من المنشآت في برنامج "مواءمة"؟

[804/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد معرفة ما إذا كان يتم إضافة البيانات التي تملكها الوزارة في الأصل للحقول الم

[805/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي الحقوق والواجبات العامة للمرأة العاملة؟

[806/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد معرفة خدمة نقل الموظفين؟

[807/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد معرفة ما إذا كان ينطبق الشرط الجزائي على العامل أو صاحب العمل؟

[808/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد معرفة شروط الخدمة؟

[809/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد معرفة خدمات مبادرة تحسين العلاقة التعاقدية؟

[810/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: إذا التحق الموظف بالتدريب أثناء إجازته الاستثنائ

[811/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد معرفة ما إذا كان بإمكاني تعيين أي موظف لدي وإعطاءه صلاحية مفوض رواتب أو مدق

[812/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف المتدرب الذي انقطع أثناء ف

[813/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد معرفة ما إذا كان يطالب المستخدم المثبت على وظيفة مشمولة بسلم رواتب الموظفين

[814/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | ما طريقة أعرف ما إذا كانت منشأتي ملزمة بتطبيق برنامج حماية الأجور؟

[815/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد معرفة برنامج نطاقات؟ وكيف يحسن بيئة العمل للسعوديين؟

[816/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: لماذا توجد رسوم مالية على برنامج "مواءمة"؟ وهل ت

[817/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | هل مسموح نقل العامل المعين على بند الأجور إلى إحدى الجهات الحكومية مع الاحتفاظ ب

[818/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد معرفة ما إذا كان يحسب برنامج نطاقات من لديهم وظائف رسمية في الحكومة ودوام ج

[819/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي آلية الترشيح للمرشحين؟

[820/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | ما طريقة يمكن للمستفيد (المؤمن له) معرفة اسم شركة التأمين التابع لها؟

[821/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد معرفة إجراءات الانتقال خلال السنة الأولى في الحالات الاستثنائية؟

[822/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد معرفة ما إذا كان تمكن البوابة والانظمة التابعة لها المستخدم من تخصيص الخدما

[823/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد معرفة ما إذا كان بإمكان أي موظف في منشأتي أن يسجل في منصة مُدد ويقوم برفع م

[824/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى أحقية المعين على بند الأجور المكلف بالعمل

[825/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد معرفة ما إذا كان تسري على شاغلي الوظائف المؤقتة القواعد الواردة في نظام الخ

[826/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: كتابة العقد؟

[827/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد معرفة ما إذا كان يترتب على العامل الوافد دفع أي رسوم حكومية (رخصة العمل – ا

[828/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: موظف منح إجازة عادية تنتهي مع ابتداء عطلة أحد ال

[829/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | هل يستطيع للمستخدمين الوصول إلى قائمة عملياته او معاملاته السابقة في البوابة؟

[830/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي خدمة الخروج النهائي؟

[831/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما الفرق بين المهنة والمسمى الوظيفي؟

[832/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | ما طريقة يمكن التوفيق بين نصي المادتين (132) و (147) من اللائحة التنفيذية للموار

[833/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | هل يستطيع أن يتغير انطاق المنشأة دون تغيير في عدد العمالة خلال السنوات القادمة؟

[834/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: لماذا يتوجب على المنشأة القيام بالتقيّيم الذاتي؟

[835/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | هل مسموح انهاء عقد العمل بسبب إعادة الهيكلة أو الظروف المالية للمنشأة؟

[836/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد معرفة ما إذا كان تشمل إجازة أداء الامتحان الدراسي من يؤدي الامتحان خارج الم

[837/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: موظف قررت الهيئة الطبية العامة معالجته في الداخل

[838/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد معرفة ما إذا كان الخدمة تتيح تحديث بيانات العامل؟

[839/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي الآلية لرفع نسب نطاقات تدريجيا؟ وكم هي المد

[840/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | هل يستطيع حفظ معاملة لخدمة معينة تم بدؤها من خلال البوابة والوصول إليها لاحقًا؟

[841/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية احتفاظ العامل المعين على بند الأج

[842/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: موظف فصل من الخدمة بناءً على حكم نهائي من ديوان

[843/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد معرفة ما إذا كان يشمل برنامج نطاقات المستثمر الأجنبي؟

[844/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: الفئات المشمولة بقرار الالزام بالتأمين على عقد ا

[845/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | هل يستطيع تفعيل بند التنافسية في عقد العمل؟

[846/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي الإجازات المستحقة للمرأة العاملة؟

[847/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد معرفة الاجراء الذي سيتم تطبيقه في حال عدم التزام المنشأة بنسب نطاقات؟

[848/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى جواز إجبار الموظف على التمتع بإجازاته الع

[849/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد معرفة الخدمات المقدمة في نظام مُدد لإدارة الرواتب؟

[850/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد معرفة ما إذا كان تمكن البوابة والانظمة التابعة لها المستخدم من تعديل بيانات

Checkpoint saved: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\retrieval_evaluation_detailed_results_checkpoint.csv
[851/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد معرفة المقصود بنصف صافي راتب الموظف مكفوف اليد ومن في حكمه وفقاً للمادة (19

[852/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف المنتدب من خارج المملكة إل

[853/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | ما طريقة أقدم شكوى على أحد الموظفين في مكاتب العمل؟ وما الحل إذا لم تتم الإفادة

[854/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي آلية احتساب نسب التوطين بعد تطبيق نطاقات ال

[855/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: مدة عمل عقد العامل السعودي؟

[856/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | ما طريقة يعامل العامل غير السعودي المعين على بند الأجور من حيث بدل النقل بعد صدو

[857/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما خطوات تنفيذ الخدمة؟

[858/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية صرف بدل التفرغ للطبيبات خلال إجاز

[859/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد معرفة ما إذا كان تسري أحكام لائحة المعينين على بند الأجور الصادرة بقرار مجل

[860/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد معرفة ما إذا كان الخدمة متاحة للعامل؟

[861/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى صرف بدل تعيين لمن يتم تعيينه بوظيفة خاضعة

[862/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ماذا يقصد ببرنامج نطاقات المطور؟

[863/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد معرفة ما إذا كان يجب ان يكون العامل مسجل على منشاة؟

[864/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى نظامية منح الموظف بعد تعيينه وفقاً لنظام

[865/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية صرف بدل الترحيل المنصوص عليه بالم

[866/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى استفادة العامل المعين على بند الأجور من م

[867/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | ما طريقة يمكنني معرفة إذا كنت مؤهل لتوثيق عقدي مع العامل/ة؟

[868/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد معرفة ما إذا كان تحتسب مدة الإجازة الاستثنائية لغرض إكمال مدة السنة المطلوب

[869/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد معرفة نظام إدارة الرواتب؟

[870/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف مكفوف اليد للعلاوة الدورية

[871/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: في الاله الحاسبة الخاصة ببرنامج نطاقات المطور هل

[872/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية نقل العسكري إلى وظيفة مدنية؟

[873/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي الحقوق العامة في عقد العمل؟

[874/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | ما طريقة يعامل الموظف المتدرب في الداخل أو الخارج في حالة إصابته بمرض وحصوله على

[875/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي شروط وضوابط الإجازات للعامل؟

[876/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى امكانية صرف مكافأة نهاية الخدمة المنصوص ع

[877/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | في أي حالة ينتهي عقد العمل؟

[878/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: موظف منح إجازة عادية بعد عطلة أحد العيدين مباشرة

[879/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | ما طريقة يمكن تصحيح فرع المنشأة الذي يعمل فيها العامل ونقله إلى الفرع الصحيح؟

[880/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ماذا يحتوي عقد العمل؟

[881/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | ما طريقة يتم التحقق من استلام العامل للأجر الذي سيتم التنفيذ عليه في عقد العمل ا

[882/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد معرفة عدد أيام الإجازة بحالة زواج العامل؟

[883/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد معرفة الحسابات التي يمكنني تفعيلها للموظفين للتعديل في حساب مدد الخاص بنظام

[884/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي اشتراطات فترة التجربة؟

[885/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد معرفة ما إذا كان النسخة العربية وغير العربية متطابقة من حيث الخدمات والوظائ

[886/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | ما طريقة يتم الاستفادة من خدمة التنقل الوظيفي للعمال الوافدين بين المنشآت؟

[887/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد معرفة أنواع الشكاوى التي يمكن أن يقدمها الموظف على صاحب العمل؟

[888/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | هل مسموح نظاماً لصاحب العمل تشغيل المرأة العاملة بعد الوضع بمدة أقل من 6 أسابيع؟

[889/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد معرفة ما إذا كان هناك لائحة وقانون يحمي الأطفال من العنف الأسري؟

[890/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | ما طريقةية تعويض العامل المعين على بند الأجور عن رصيده من الاجازات العادية عند ا

[891/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: موظف مددت خدمته لمدة سنتين بعد بلوغه السن النظام

[892/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | هل يستطيع نقل العمالة داخل الكيان الواحد؟

[893/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد معرفة ما إذا كان تغطي الوثيقة النفقات الطبية اللازمة لعلاج العامل المنزلي ب

[894/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | هل يستطيع إلغاء التأشيرة المصدرة من مساند؟

[895/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف الذي يشغل وظيفة خاضعة لنظا

[896/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد معرفة ما إذا كان يحسم من راتب الموظف أيام غيابه عن العمل نتيجة مثوله أمام ا

[897/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: موظف بعد احالته على التقاعد لبلوغ السن النظامية

[898/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | هل يستطيع تعديل المهنة بعد تطبيق المبادرة؟

[899/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد معرفة ما إذا كان يستحق الموظف التعويض عن إجازته العادية إذا استقال قبل إكما

[900/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | ما طريقة يمكن الاستفادة من الخدمة؟

Checkpoint saved: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\retrieval_evaluation_detailed_results_checkpoint.csv
[901/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد معرفة فترة الراحة اليومية للرضاعة؟

[902/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | في أي حالة يتاح تجديد رخصة العمل؟

[903/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | ما طريقة يتم حماية حقوق العامل؟

[904/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف المتدرب لمكافآت وبدلات الت

[905/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد معرفة ما إذا كان يحسب من عمره أقل من 18 سنة ضمن نسبة التوطين؟

[906/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | أريد معرفة شروط أهلية العامل الوافد للاستفادة من خدمة التنقل الوظيفي؟

[907/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | كم مدة فترة التجربة في نظام العمل السعودي؟

[908/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | هل يجوز وضع العامل تحت التجربة أكثر من مرة لدى نفس صاحب العمل؟

[909/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | ما الحد الأقصى لساعات العمل اليومية في نظام العمل؟

[910/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | ما الحد الأقصى لساعات العمل الأسبوعية؟

[911/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | هل تختلف ساعات العمل في شهر رمضان؟

[912/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | ما مدة الإجازة السنوية المستحقة للعامل؟

[913/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | متى تزيد الإجازة السنوية إلى ثلاثين يومًا؟

[914/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | هل يستحق العامل أجرًا عن أيام الإجازة غير المستخدمة عند انتهاء العمل؟

[915/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | هل يستحق العامل إجازة عند الزواج أو وفاة أحد الأقارب؟

[916/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | هل للعامل الحق في إجازة مرضية؟

[917/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | ما حالات انتهاء عقد العمل؟

[918/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | ما مدة الإشعار عند إنهاء العقد غير محدد المدة؟

[919/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | متى يستحق العامل تعويضًا عند إنهاء العقد لسبب غير مشروع؟

[920/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | متى يجوز لصاحب العمل إنهاء العقد دون مكافأة أو تعويض؟

[921/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | متى يجوز للعامل ترك العمل دون إشعار مع احتفاظه بحقوقه؟

[922/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | متى يستحق العامل مكافأة نهاية الخدمة؟

[923/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | هل يحق لصاحب العمل نقل العامل من مكان عمله الأصلي؟

[924/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | ما المقصود بعقد العمل في نظام العمل؟

[925/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | كيف يتم دفع أجر العامل؟

[926/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | ما واجبات صاحب العمل تجاه العامل؟

[927/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | ما التزامات العامل في نظام العمل؟

[928/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | ما الحد الأقصى لساعات العمل الإضافية وكيف تُحتسب؟

[929/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | ما أحكام السلامة والصحة المهنية في بيئة العمل؟

[930/3410] Exp 6/22 | hybrid_reranker | structural | e5_large | ما حقوق العاملة في إجازة الوضع؟

====================================================================================================
Experiment 7/22: {'chunking_strategy': 'structural', 'embedding_model': 'bge_m3', 'retriever': 'dense', 'alpha': None}
====================================================================================================
[931/3410] Exp 7/22 | dense | structural | bge_m3 | ما طريقة يمكنني إلغاء أو تعديل طلب تغيير المهنة؟
[932/3410] Exp 7/22 | dense | structural | bge_m3 | أريد معرفة الطريقة المتبعة لتسديد قسط التأمين؟
[933/3410] Exp 7/22 | dense | structural | bge_m3 | ما طريقةية معاملة محرم الموظفة عند مرافقتها أثناء ابتعاثها للدراسة أو التدريب أو
[934/3410] Exp 7/22 | dense | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي أهداف برنامج نطاقات المطور؟
[935/3410] Exp 7/22 | dense | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية الجمع بين بدل المهنة المنصوص عليه
[936/3410] Exp 7/22 | dense | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: موظف أحيل للتحقيق أثناء إجراء المفاضلة لغرض التر
[937/3410] Exp 7/22 | dense | structural | bge_m3 | ما طريقة يتم احتساب أجر الساعات الإضافية؟
[938/3410] Exp 7/22 | dense | structural | bge_m3 | هل مسموح تعيين العمال بصفة مؤقتة طبقاً للائحة المعينين على بند الأجور؟

[939/3410] Exp 7/22 | dense | structural | bge_m3 | هل يستطيع احتساب أيام المراجعة للمستشفيات داخل مقر العمل أو خارجه إجازة مرضية أو
[940/3410] Exp 7/22 | dense | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: اعرف حقوق العمال؟
[941/3410] Exp 7/22 | dense | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: في حال تم رصد مخالفات في ملف الأجور، أين أجد تفا
[942/3410] Exp 7/22 | dense | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما المقصود من كون عمال المستشفيات ضمن المساعدين
[943/3410] Exp 7/22 | dense | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: موظف قدم للرياض للالتحاق بدورة تدريبية وبعد انته
[944/3410] Exp 7/22 | dense | structural | bge_m3 | أريد معرفة ما إذا كان يخصم بدل المواصلات من راتب الإجازة السنوية؟
[945/3410] Exp 7/22 | dense | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: موظف استقال من وظيفة بالمرتبة الرابعة ومن ثم عاد

[946/3410] Exp 7/22 | dense | structural | bge_m3 | أريد معرفة عقد العمل؟
[947/3410] Exp 7/22 | dense | structural | bge_m3 | أريد معرفة ما إذا كان تحسم رواتب العطل الرسمية والأعياد إذا سبقها غياب ولحقها غي
[948/3410] Exp 7/22 | dense | structural | bge_m3 | أريد معرفة العمل المرن؟
[949/3410] Exp 7/22 | dense | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى جواز منح الموظف المنقول بترقية الدرجة الإ
[950/3410] Exp 7/22 | dense | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: في حالة غياب الموظف عن العمل وإيقاع عقوبة تأديبي
Checkpoint saved: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\retrieval_evaluation_detailed_results_checkpoint.csv
[951/3410] Exp 7/22 | dense | structural | bge_m3 | ما طريقة يتم طلب المدرب الاختياري قبل التقدم بطلب شهادة "مواءمة"؟
[952/3410] Exp 7/22 | dense | structural | bge_m3 | هل مسموح نظاماً للعامل الانتقال من منشأة في النطاق الأحمر بدون إذن صاحب العمل إل

[953/3410] Exp 7/22 | dense | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى امكانية ابتعاث أوايفاد العامل المعين على
[954/3410] Exp 7/22 | dense | structural | bge_m3 | هل مسموح منح الموظف أثناء فترة التجربة إجازة استثنائية؟
[955/3410] Exp 7/22 | dense | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى إلزام الموظف بالعمل خارج وقت الدوام، وهل
[956/3410] Exp 7/22 | dense | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى انطباق المزايا المالية التي تصرف للمشاركي
[957/3410] Exp 7/22 | dense | structural | bge_m3 | أريد معرفة ما إذا كان أستطيع رفع ملفات حماية الأجور عبر موقع وزارة الموارد البشر
[958/3410] Exp 7/22 | dense | structural | bge_m3 | أريد معرفة الرسوم المطلوبة من المنشآت في برنامج "مواءمة"؟
[959/3410] Exp 7/22 | dense | structural | bge_m3 | أريد معرفة ما إذا كان يتم إضافة البيانات التي تملكها الوزارة في الأصل للحقول الم

[960/3410] Exp 7/22 | dense | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي الحقوق والواجبات العامة للمرأة العاملة؟
[961/3410] Exp 7/22 | dense | structural | bge_m3 | أريد معرفة خدمة نقل الموظفين؟
[962/3410] Exp 7/22 | dense | structural | bge_m3 | أريد معرفة ما إذا كان ينطبق الشرط الجزائي على العامل أو صاحب العمل؟
[963/3410] Exp 7/22 | dense | structural | bge_m3 | أريد معرفة شروط الخدمة؟
[964/3410] Exp 7/22 | dense | structural | bge_m3 | أريد معرفة خدمات مبادرة تحسين العلاقة التعاقدية؟
[965/3410] Exp 7/22 | dense | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: إذا التحق الموظف بالتدريب أثناء إجازته الاستثنائ
[966/3410] Exp 7/22 | dense | structural | bge_m3 | أريد معرفة ما إذا كان بإمكاني تعيين أي موظف لدي وإعطاءه صلاحية مفوض رواتب أو مدق
[967/3410] Exp 7/22 | dense | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف المتدرب الذي انقطع أثناء ف

[968/3410] Exp 7/22 | dense | structural | bge_m3 | أريد معرفة ما إذا كان يطالب المستخدم المثبت على وظيفة مشمولة بسلم رواتب الموظفين
[969/3410] Exp 7/22 | dense | structural | bge_m3 | ما طريقة أعرف ما إذا كانت منشأتي ملزمة بتطبيق برنامج حماية الأجور؟
[970/3410] Exp 7/22 | dense | structural | bge_m3 | أريد معرفة برنامج نطاقات؟ وكيف يحسن بيئة العمل للسعوديين؟
[971/3410] Exp 7/22 | dense | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: لماذا توجد رسوم مالية على برنامج "مواءمة"؟ وهل ت
[972/3410] Exp 7/22 | dense | structural | bge_m3 | هل مسموح نقل العامل المعين على بند الأجور إلى إحدى الجهات الحكومية مع الاحتفاظ ب
[973/3410] Exp 7/22 | dense | structural | bge_m3 | أريد معرفة ما إذا كان يحسب برنامج نطاقات من لديهم وظائف رسمية في الحكومة ودوام ج
[974/3410] Exp 7/22 | dense | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي آلية الترشيح للمرشحين؟

[975/3410] Exp 7/22 | dense | structural | bge_m3 | ما طريقة يمكن للمستفيد (المؤمن له) معرفة اسم شركة التأمين التابع لها؟
[976/3410] Exp 7/22 | dense | structural | bge_m3 | أريد معرفة إجراءات الانتقال خلال السنة الأولى في الحالات الاستثنائية؟
[977/3410] Exp 7/22 | dense | structural | bge_m3 | أريد معرفة ما إذا كان تمكن البوابة والانظمة التابعة لها المستخدم من تخصيص الخدما
[978/3410] Exp 7/22 | dense | structural | bge_m3 | أريد معرفة ما إذا كان بإمكان أي موظف في منشأتي أن يسجل في منصة مُدد ويقوم برفع م
[979/3410] Exp 7/22 | dense | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى أحقية المعين على بند الأجور المكلف بالعمل
[980/3410] Exp 7/22 | dense | structural | bge_m3 | أريد معرفة ما إذا كان تسري على شاغلي الوظائف المؤقتة القواعد الواردة في نظام الخ
[981/3410] Exp 7/22 | dense | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: كتابة العقد؟
[982/3410] Exp 7/22 | dense | structural | bge_m3 | أريد معرفة ما إذا كان يترتب على العامل الوافد دفع أي رسوم حكومية (رخصة العمل – ا

[983/3410] Exp 7/22 | dense | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: موظف منح إجازة عادية تنتهي مع ابتداء عطلة أحد ال
[984/3410] Exp 7/22 | dense | structural | bge_m3 | هل يستطيع للمستخدمين الوصول إلى قائمة عملياته او معاملاته السابقة في البوابة؟
[985/3410] Exp 7/22 | dense | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي خدمة الخروج النهائي؟
[986/3410] Exp 7/22 | dense | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما الفرق بين المهنة والمسمى الوظيفي؟
[987/3410] Exp 7/22 | dense | structural | bge_m3 | ما طريقة يمكن التوفيق بين نصي المادتين (132) و (147) من اللائحة التنفيذية للموار
[988/3410] Exp 7/22 | dense | structural | bge_m3 | هل يستطيع أن يتغير انطاق المنشأة دون تغيير في عدد العمالة خلال السنوات القادمة؟
[989/3410] Exp 7/22 | dense | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: لماذا يتوجب على المنشأة القيام بالتقيّيم الذاتي؟

[990/3410] Exp 7/22 | dense | structural | bge_m3 | هل مسموح انهاء عقد العمل بسبب إعادة الهيكلة أو الظروف المالية للمنشأة؟
[991/3410] Exp 7/22 | dense | structural | bge_m3 | أريد معرفة ما إذا كان تشمل إجازة أداء الامتحان الدراسي من يؤدي الامتحان خارج الم
[992/3410] Exp 7/22 | dense | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: موظف قررت الهيئة الطبية العامة معالجته في الداخل
[993/3410] Exp 7/22 | dense | structural | bge_m3 | أريد معرفة ما إذا كان الخدمة تتيح تحديث بيانات العامل؟
[994/3410] Exp 7/22 | dense | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي الآلية لرفع نسب نطاقات تدريجيا؟ وكم هي المد
[995/3410] Exp 7/22 | dense | structural | bge_m3 | هل يستطيع حفظ معاملة لخدمة معينة تم بدؤها من خلال البوابة والوصول إليها لاحقًا؟
[996/3410] Exp 7/22 | dense | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية احتفاظ العامل المعين على بند الأج
[997/3410] Exp 7/22 | dense | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: موظف فصل من الخدمة بناءً على حكم نهائي من ديوان

[998/3410] Exp 7/22 | dense | structural | bge_m3 | أريد معرفة ما إذا كان يشمل برنامج نطاقات المستثمر الأجنبي؟
[999/3410] Exp 7/22 | dense | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: الفئات المشمولة بقرار الالزام بالتأمين على عقد ا
[1000/3410] Exp 7/22 | dense | structural | bge_m3 | هل يستطيع تفعيل بند التنافسية في عقد العمل؟
Checkpoint saved: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\retrieval_evaluation_detailed_results_checkpoint.csv
[1001/3410] Exp 7/22 | dense | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي الإجازات المستحقة للمرأة العاملة؟
[1002/3410] Exp 7/22 | dense | structural | bge_m3 | أريد معرفة الاجراء الذي سيتم تطبيقه في حال عدم التزام المنشأة بنسب نطاقات؟
[1003/3410] Exp 7/22 | dense | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى جواز إجبار الموظف على التمتع بإجازاته الع
[1004/3410] Exp 7/22 | dense | structural | bge_m3 | أريد معرفة الخدمات المقدمة في نظام مُدد لإدارة الرواتب؟
[1005/3410] Exp 7/22 | dense | structural | bge_m3 | أريد معرفة ما إذا كان تمكن البوابة والانظمة التابعة لها المستخدم من تعديل بيانات

[1006/3410] Exp 7/22 | dense | structural | bge_m3 | أريد معرفة المقصود بنصف صافي راتب الموظف مكفوف اليد ومن في حكمه وفقاً للمادة (19
[1007/3410] Exp 7/22 | dense | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف المنتدب من خارج المملكة إل
[1008/3410] Exp 7/22 | dense | structural | bge_m3 | ما طريقة أقدم شكوى على أحد الموظفين في مكاتب العمل؟ وما الحل إذا لم تتم الإفادة
[1009/3410] Exp 7/22 | dense | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي آلية احتساب نسب التوطين بعد تطبيق نطاقات ال
[1010/3410] Exp 7/22 | dense | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: مدة عمل عقد العامل السعودي؟
[1011/3410] Exp 7/22 | dense | structural | bge_m3 | ما طريقة يعامل العامل غير السعودي المعين على بند الأجور من حيث بدل النقل بعد صدو
[1012/3410] Exp 7/22 | dense | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما خطوات تنفيذ الخدمة؟

[1013/3410] Exp 7/22 | dense | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية صرف بدل التفرغ للطبيبات خلال إجاز
[1014/3410] Exp 7/22 | dense | structural | bge_m3 | أريد معرفة ما إذا كان تسري أحكام لائحة المعينين على بند الأجور الصادرة بقرار مجل
[1015/3410] Exp 7/22 | dense | structural | bge_m3 | أريد معرفة ما إذا كان الخدمة متاحة للعامل؟
[1016/3410] Exp 7/22 | dense | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى صرف بدل تعيين لمن يتم تعيينه بوظيفة خاضعة
[1017/3410] Exp 7/22 | dense | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماذا يقصد ببرنامج نطاقات المطور؟
[1018/3410] Exp 7/22 | dense | structural | bge_m3 | أريد معرفة ما إذا كان يجب ان يكون العامل مسجل على منشاة؟
[1019/3410] Exp 7/22 | dense | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى نظامية منح الموظف بعد تعيينه وفقاً لنظام

[1020/3410] Exp 7/22 | dense | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية صرف بدل الترحيل المنصوص عليه بالم
[1021/3410] Exp 7/22 | dense | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى استفادة العامل المعين على بند الأجور من م
[1022/3410] Exp 7/22 | dense | structural | bge_m3 | ما طريقة يمكنني معرفة إذا كنت مؤهل لتوثيق عقدي مع العامل/ة؟
[1023/3410] Exp 7/22 | dense | structural | bge_m3 | أريد معرفة ما إذا كان تحتسب مدة الإجازة الاستثنائية لغرض إكمال مدة السنة المطلوب
[1024/3410] Exp 7/22 | dense | structural | bge_m3 | أريد معرفة نظام إدارة الرواتب؟
[1025/3410] Exp 7/22 | dense | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف مكفوف اليد للعلاوة الدورية
[1026/3410] Exp 7/22 | dense | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: في الاله الحاسبة الخاصة ببرنامج نطاقات المطور هل

[1027/3410] Exp 7/22 | dense | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية نقل العسكري إلى وظيفة مدنية؟
[1028/3410] Exp 7/22 | dense | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي الحقوق العامة في عقد العمل؟
[1029/3410] Exp 7/22 | dense | structural | bge_m3 | ما طريقة يعامل الموظف المتدرب في الداخل أو الخارج في حالة إصابته بمرض وحصوله على
[1030/3410] Exp 7/22 | dense | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي شروط وضوابط الإجازات للعامل؟
[1031/3410] Exp 7/22 | dense | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى امكانية صرف مكافأة نهاية الخدمة المنصوص ع
[1032/3410] Exp 7/22 | dense | structural | bge_m3 | في أي حالة ينتهي عقد العمل؟
[1033/3410] Exp 7/22 | dense | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: موظف منح إجازة عادية بعد عطلة أحد العيدين مباشرة

[1034/3410] Exp 7/22 | dense | structural | bge_m3 | ما طريقة يمكن تصحيح فرع المنشأة الذي يعمل فيها العامل ونقله إلى الفرع الصحيح؟
[1035/3410] Exp 7/22 | dense | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماذا يحتوي عقد العمل؟
[1036/3410] Exp 7/22 | dense | structural | bge_m3 | ما طريقة يتم التحقق من استلام العامل للأجر الذي سيتم التنفيذ عليه في عقد العمل ا
[1037/3410] Exp 7/22 | dense | structural | bge_m3 | أريد معرفة عدد أيام الإجازة بحالة زواج العامل؟
[1038/3410] Exp 7/22 | dense | structural | bge_m3 | أريد معرفة الحسابات التي يمكنني تفعيلها للموظفين للتعديل في حساب مدد الخاص بنظام
[1039/3410] Exp 7/22 | dense | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي اشتراطات فترة التجربة؟
[1040/3410] Exp 7/22 | dense | structural | bge_m3 | أريد معرفة ما إذا كان النسخة العربية وغير العربية متطابقة من حيث الخدمات والوظائ
[1041/3410] Exp 7/22 | dense | structural | bge_m3 | ما طريقة يتم الاستفادة من خدمة التنقل الوظيفي للعمال الوافدين بين المنشآت؟

[1042/3410] Exp 7/22 | dense | structural | bge_m3 | أريد معرفة أنواع الشكاوى التي يمكن أن يقدمها الموظف على صاحب العمل؟
[1043/3410] Exp 7/22 | dense | structural | bge_m3 | هل مسموح نظاماً لصاحب العمل تشغيل المرأة العاملة بعد الوضع بمدة أقل من 6 أسابيع؟
[1044/3410] Exp 7/22 | dense | structural | bge_m3 | أريد معرفة ما إذا كان هناك لائحة وقانون يحمي الأطفال من العنف الأسري؟
[1045/3410] Exp 7/22 | dense | structural | bge_m3 | ما طريقةية تعويض العامل المعين على بند الأجور عن رصيده من الاجازات العادية عند ا
[1046/3410] Exp 7/22 | dense | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: موظف مددت خدمته لمدة سنتين بعد بلوغه السن النظام
[1047/3410] Exp 7/22 | dense | structural | bge_m3 | هل يستطيع نقل العمالة داخل الكيان الواحد؟
[1048/3410] Exp 7/22 | dense | structural | bge_m3 | أريد معرفة ما إذا كان تغطي الوثيقة النفقات الطبية اللازمة لعلاج العامل المنزلي ب
[1049/3410] Exp 7/22 | dense | structural | bge_m3 | هل يستطيع إلغاء التأشيرة المصدرة من مساند؟

[1050/3410] Exp 7/22 | dense | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف الذي يشغل وظيفة خاضعة لنظا
Checkpoint saved: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\retrieval_evaluation_detailed_results_checkpoint.csv
[1051/3410] Exp 7/22 | dense | structural | bge_m3 | أريد معرفة ما إذا كان يحسم من راتب الموظف أيام غيابه عن العمل نتيجة مثوله أمام ا
[1052/3410] Exp 7/22 | dense | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: موظف بعد احالته على التقاعد لبلوغ السن النظامية
[1053/3410] Exp 7/22 | dense | structural | bge_m3 | هل يستطيع تعديل المهنة بعد تطبيق المبادرة؟
[1054/3410] Exp 7/22 | dense | structural | bge_m3 | أريد معرفة ما إذا كان يستحق الموظف التعويض عن إجازته العادية إذا استقال قبل إكما
[1055/3410] Exp 7/22 | dense | structural | bge_m3 | ما طريقة يمكن الاستفادة من الخدمة؟
[1056/3410] Exp 7/22 | dense | structural | bge_m3 | أريد معرفة فترة الراحة اليومية للرضاعة؟
[1057/3410] Exp 7/22 | dense | structural | bge_m3 | في أي حالة يتاح تجديد رخصة العمل؟
[1058/3410] Exp 7/22 | dense | structural | bge_m3 | ما طريقة يتم حماية حقوق العامل؟

[1059/3410] Exp 7/22 | dense | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف المتدرب لمكافآت وبدلات الت
[1060/3410] Exp 7/22 | dense | structural | bge_m3 | أريد معرفة ما إذا كان يحسب من عمره أقل من 18 سنة ضمن نسبة التوطين؟
[1061/3410] Exp 7/22 | dense | structural | bge_m3 | أريد معرفة شروط أهلية العامل الوافد للاستفادة من خدمة التنقل الوظيفي؟
[1062/3410] Exp 7/22 | dense | structural | bge_m3 | كم مدة فترة التجربة في نظام العمل السعودي؟
[1063/3410] Exp 7/22 | dense | structural | bge_m3 | هل يجوز وضع العامل تحت التجربة أكثر من مرة لدى نفس صاحب العمل؟
[1064/3410] Exp 7/22 | dense | structural | bge_m3 | ما الحد الأقصى لساعات العمل اليومية في نظام العمل؟
[1065/3410] Exp 7/22 | dense | structural | bge_m3 | ما الحد الأقصى لساعات العمل الأسبوعية؟
[1066/3410] Exp 7/22 | dense | structural | bge_m3 | هل تختلف ساعات العمل في شهر رمضان؟
[1067/3410] Exp 7/22 | dense | structural | bge_m3 | ما مدة الإجازة السنوية المستحقة للعامل؟
[1068/3410] Exp 7/22 | dense | structural | bge_m3 | متى تزيد الإجازة السنوية إلى ثلاثين يومًا؟
[1069/3410] Exp 7/22 | dense | structural | bge_m3 | هل يستحق العامل أجرًا عن أيام الإجازة غير المستخدمة عند انتهاء العمل؟

[1070/3410] Exp 7/22 | dense | structural | bge_m3 | هل يستحق العامل إجازة عند الزواج أو وفاة أحد الأقارب؟
[1071/3410] Exp 7/22 | dense | structural | bge_m3 | هل للعامل الحق في إجازة مرضية؟
[1072/3410] Exp 7/22 | dense | structural | bge_m3 | ما حالات انتهاء عقد العمل؟
[1073/3410] Exp 7/22 | dense | structural | bge_m3 | ما مدة الإشعار عند إنهاء العقد غير محدد المدة؟
[1074/3410] Exp 7/22 | dense | structural | bge_m3 | متى يستحق العامل تعويضًا عند إنهاء العقد لسبب غير مشروع؟
[1075/3410] Exp 7/22 | dense | structural | bge_m3 | متى يجوز لصاحب العمل إنهاء العقد دون مكافأة أو تعويض؟
[1076/3410] Exp 7/22 | dense | structural | bge_m3 | متى يجوز للعامل ترك العمل دون إشعار مع احتفاظه بحقوقه؟
[1077/3410] Exp 7/22 | dense | structural | bge_m3 | متى يستحق العامل مكافأة نهاية الخدمة؟
[1078/3410] Exp 7/22 | dense | structural | bge_m3 | هل يحق لصاحب العمل نقل العامل من مكان عمله الأصلي؟
[1079/3410] Exp 7/22 | dense | structural | bge_m3 | ما المقصود بعقد العمل في نظام العمل؟
[1080/3410] Exp 7/22 | dense | structural | bge_m3 | كيف يتم دفع أجر العامل؟
[1081/3410] Exp 7/22 | dense | structural | bge_m3 | ما واجبات صاحب العمل تجاه العامل؟

[1082/3410] Exp 7/22 | dense | structural | bge_m3 | ما التزامات العامل في نظام العمل؟
[1083/3410] Exp 7/22 | dense | structural | bge_m3 | ما الحد الأقصى لساعات العمل الإضافية وكيف تُحتسب؟
[1084/3410] Exp 7/22 | dense | structural | bge_m3 | ما أحكام السلامة والصحة المهنية في بيئة العمل؟
[1085/3410] Exp 7/22 | dense | structural | bge_m3 | ما حقوق العاملة في إجازة الوضع؟
====================================================================================================
Experiment 8/22: {'chunking_strategy': 'structural', 'embedding_model': 'bge_m3', 'retriever': 'hybrid', 'alpha': 0.65}
====================================================================================================
[1086/3410] Exp 8/22 | hybrid | structural | bge_m3 | ما طريقة يمكنني إلغاء أو تعديل طلب تغيير المهنة؟
[1087/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد معرفة الطريقة المتبعة لتسديد قسط التأمين؟
[1088/3410] Exp 8/22 | hybrid | structural | bge_m3 | ما طريقةية معاملة محرم الموظفة عند مرافقتها أثناء ابتعاثها للدراسة أو التدريب أو
[1089/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي أهداف برنامج نطاقات المطور؟
[1090/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية الجمع بين بدل المهنة المنصوص عليه

[1091/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: موظف أحيل للتحقيق أثناء إجراء المفاضلة لغرض التر
[1092/3410] Exp 8/22 | hybrid | structural | bge_m3 | ما طريقة يتم احتساب أجر الساعات الإضافية؟
[1093/3410] Exp 8/22 | hybrid | structural | bge_m3 | هل مسموح تعيين العمال بصفة مؤقتة طبقاً للائحة المعينين على بند الأجور؟
[1094/3410] Exp 8/22 | hybrid | structural | bge_m3 | هل يستطيع احتساب أيام المراجعة للمستشفيات داخل مقر العمل أو خارجه إجازة مرضية أو
[1095/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: اعرف حقوق العمال؟
[1096/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: في حال تم رصد مخالفات في ملف الأجور، أين أجد تفا

[1097/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما المقصود من كون عمال المستشفيات ضمن المساعدين
[1098/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: موظف قدم للرياض للالتحاق بدورة تدريبية وبعد انته
[1099/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد معرفة ما إذا كان يخصم بدل المواصلات من راتب الإجازة السنوية؟
[1100/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: موظف استقال من وظيفة بالمرتبة الرابعة ومن ثم عاد
Checkpoint saved: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\retrieval_evaluation_detailed_results_checkpoint.csv
[1101/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد معرفة عقد العمل؟

[1102/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد معرفة ما إذا كان تحسم رواتب العطل الرسمية والأعياد إذا سبقها غياب ولحقها غي
[1103/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد معرفة العمل المرن؟
[1104/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى جواز منح الموظف المنقول بترقية الدرجة الإ
[1105/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: في حالة غياب الموظف عن العمل وإيقاع عقوبة تأديبي
[1106/3410] Exp 8/22 | hybrid | structural | bge_m3 | ما طريقة يتم طلب المدرب الاختياري قبل التقدم بطلب شهادة "مواءمة"؟

[1107/3410] Exp 8/22 | hybrid | structural | bge_m3 | هل مسموح نظاماً للعامل الانتقال من منشأة في النطاق الأحمر بدون إذن صاحب العمل إل
[1108/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى امكانية ابتعاث أوايفاد العامل المعين على
[1109/3410] Exp 8/22 | hybrid | structural | bge_m3 | هل مسموح منح الموظف أثناء فترة التجربة إجازة استثنائية؟
[1110/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى إلزام الموظف بالعمل خارج وقت الدوام، وهل
[1111/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى انطباق المزايا المالية التي تصرف للمشاركي

[1112/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد معرفة ما إذا كان أستطيع رفع ملفات حماية الأجور عبر موقع وزارة الموارد البشر
[1113/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد معرفة الرسوم المطلوبة من المنشآت في برنامج "مواءمة"؟
[1114/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد معرفة ما إذا كان يتم إضافة البيانات التي تملكها الوزارة في الأصل للحقول الم
[1115/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي الحقوق والواجبات العامة للمرأة العاملة؟
[1116/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد معرفة خدمة نقل الموظفين؟
[1117/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد معرفة ما إذا كان ينطبق الشرط الجزائي على العامل أو صاحب العمل؟
[1118/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد معرفة شروط الخدمة؟

[1119/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد معرفة خدمات مبادرة تحسين العلاقة التعاقدية؟
[1120/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: إذا التحق الموظف بالتدريب أثناء إجازته الاستثنائ
[1121/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد معرفة ما إذا كان بإمكاني تعيين أي موظف لدي وإعطاءه صلاحية مفوض رواتب أو مدق
[1122/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف المتدرب الذي انقطع أثناء ف
[1123/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد معرفة ما إذا كان يطالب المستخدم المثبت على وظيفة مشمولة بسلم رواتب الموظفين

[1124/3410] Exp 8/22 | hybrid | structural | bge_m3 | ما طريقة أعرف ما إذا كانت منشأتي ملزمة بتطبيق برنامج حماية الأجور؟
[1125/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد معرفة برنامج نطاقات؟ وكيف يحسن بيئة العمل للسعوديين؟
[1126/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: لماذا توجد رسوم مالية على برنامج "مواءمة"؟ وهل ت
[1127/3410] Exp 8/22 | hybrid | structural | bge_m3 | هل مسموح نقل العامل المعين على بند الأجور إلى إحدى الجهات الحكومية مع الاحتفاظ ب
[1128/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد معرفة ما إذا كان يحسب برنامج نطاقات من لديهم وظائف رسمية في الحكومة ودوام ج
[1129/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي آلية الترشيح للمرشحين؟

[1130/3410] Exp 8/22 | hybrid | structural | bge_m3 | ما طريقة يمكن للمستفيد (المؤمن له) معرفة اسم شركة التأمين التابع لها؟
[1131/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد معرفة إجراءات الانتقال خلال السنة الأولى في الحالات الاستثنائية؟
[1132/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد معرفة ما إذا كان تمكن البوابة والانظمة التابعة لها المستخدم من تخصيص الخدما
[1133/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد معرفة ما إذا كان بإمكان أي موظف في منشأتي أن يسجل في منصة مُدد ويقوم برفع م
[1134/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى أحقية المعين على بند الأجور المكلف بالعمل
[1135/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد معرفة ما إذا كان تسري على شاغلي الوظائف المؤقتة القواعد الواردة في نظام الخ

[1136/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: كتابة العقد؟
[1137/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد معرفة ما إذا كان يترتب على العامل الوافد دفع أي رسوم حكومية (رخصة العمل – ا
[1138/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: موظف منح إجازة عادية تنتهي مع ابتداء عطلة أحد ال
[1139/3410] Exp 8/22 | hybrid | structural | bge_m3 | هل يستطيع للمستخدمين الوصول إلى قائمة عملياته او معاملاته السابقة في البوابة؟
[1140/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي خدمة الخروج النهائي؟
[1141/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما الفرق بين المهنة والمسمى الوظيفي؟

[1142/3410] Exp 8/22 | hybrid | structural | bge_m3 | ما طريقة يمكن التوفيق بين نصي المادتين (132) و (147) من اللائحة التنفيذية للموار
[1143/3410] Exp 8/22 | hybrid | structural | bge_m3 | هل يستطيع أن يتغير انطاق المنشأة دون تغيير في عدد العمالة خلال السنوات القادمة؟
[1144/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: لماذا يتوجب على المنشأة القيام بالتقيّيم الذاتي؟
[1145/3410] Exp 8/22 | hybrid | structural | bge_m3 | هل مسموح انهاء عقد العمل بسبب إعادة الهيكلة أو الظروف المالية للمنشأة؟
[1146/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد معرفة ما إذا كان تشمل إجازة أداء الامتحان الدراسي من يؤدي الامتحان خارج الم
[1147/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: موظف قررت الهيئة الطبية العامة معالجته في الداخل

[1148/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد معرفة ما إذا كان الخدمة تتيح تحديث بيانات العامل؟
[1149/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي الآلية لرفع نسب نطاقات تدريجيا؟ وكم هي المد
[1150/3410] Exp 8/22 | hybrid | structural | bge_m3 | هل يستطيع حفظ معاملة لخدمة معينة تم بدؤها من خلال البوابة والوصول إليها لاحقًا؟
Checkpoint saved: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\retrieval_evaluation_detailed_results_checkpoint.csv
[1151/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية احتفاظ العامل المعين على بند الأج
[1152/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: موظف فصل من الخدمة بناءً على حكم نهائي من ديوان

[1153/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد معرفة ما إذا كان يشمل برنامج نطاقات المستثمر الأجنبي؟
[1154/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: الفئات المشمولة بقرار الالزام بالتأمين على عقد ا
[1155/3410] Exp 8/22 | hybrid | structural | bge_m3 | هل يستطيع تفعيل بند التنافسية في عقد العمل؟
[1156/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي الإجازات المستحقة للمرأة العاملة؟
[1157/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد معرفة الاجراء الذي سيتم تطبيقه في حال عدم التزام المنشأة بنسب نطاقات؟
[1158/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى جواز إجبار الموظف على التمتع بإجازاته الع
[1159/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد معرفة الخدمات المقدمة في نظام مُدد لإدارة الرواتب؟

[1160/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد معرفة ما إذا كان تمكن البوابة والانظمة التابعة لها المستخدم من تعديل بيانات
[1161/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد معرفة المقصود بنصف صافي راتب الموظف مكفوف اليد ومن في حكمه وفقاً للمادة (19
[1162/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف المنتدب من خارج المملكة إل
[1163/3410] Exp 8/22 | hybrid | structural | bge_m3 | ما طريقة أقدم شكوى على أحد الموظفين في مكاتب العمل؟ وما الحل إذا لم تتم الإفادة
[1164/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي آلية احتساب نسب التوطين بعد تطبيق نطاقات ال
[1165/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: مدة عمل عقد العامل السعودي؟

[1166/3410] Exp 8/22 | hybrid | structural | bge_m3 | ما طريقة يعامل العامل غير السعودي المعين على بند الأجور من حيث بدل النقل بعد صدو
[1167/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما خطوات تنفيذ الخدمة؟
[1168/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية صرف بدل التفرغ للطبيبات خلال إجاز
[1169/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد معرفة ما إذا كان تسري أحكام لائحة المعينين على بند الأجور الصادرة بقرار مجل
[1170/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد معرفة ما إذا كان الخدمة متاحة للعامل؟
[1171/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى صرف بدل تعيين لمن يتم تعيينه بوظيفة خاضعة

[1172/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماذا يقصد ببرنامج نطاقات المطور؟
[1173/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد معرفة ما إذا كان يجب ان يكون العامل مسجل على منشاة؟
[1174/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى نظامية منح الموظف بعد تعيينه وفقاً لنظام
[1175/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية صرف بدل الترحيل المنصوص عليه بالم
[1176/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى استفادة العامل المعين على بند الأجور من م

[1177/3410] Exp 8/22 | hybrid | structural | bge_m3 | ما طريقة يمكنني معرفة إذا كنت مؤهل لتوثيق عقدي مع العامل/ة؟
[1178/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد معرفة ما إذا كان تحتسب مدة الإجازة الاستثنائية لغرض إكمال مدة السنة المطلوب
[1179/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد معرفة نظام إدارة الرواتب؟
[1180/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف مكفوف اليد للعلاوة الدورية
[1181/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: في الاله الحاسبة الخاصة ببرنامج نطاقات المطور هل
[1182/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية نقل العسكري إلى وظيفة مدنية؟

[1183/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي الحقوق العامة في عقد العمل؟
[1184/3410] Exp 8/22 | hybrid | structural | bge_m3 | ما طريقة يعامل الموظف المتدرب في الداخل أو الخارج في حالة إصابته بمرض وحصوله على
[1185/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي شروط وضوابط الإجازات للعامل؟
[1186/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى امكانية صرف مكافأة نهاية الخدمة المنصوص ع
[1187/3410] Exp 8/22 | hybrid | structural | bge_m3 | في أي حالة ينتهي عقد العمل؟

[1188/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: موظف منح إجازة عادية بعد عطلة أحد العيدين مباشرة
[1189/3410] Exp 8/22 | hybrid | structural | bge_m3 | ما طريقة يمكن تصحيح فرع المنشأة الذي يعمل فيها العامل ونقله إلى الفرع الصحيح؟
[1190/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماذا يحتوي عقد العمل؟
[1191/3410] Exp 8/22 | hybrid | structural | bge_m3 | ما طريقة يتم التحقق من استلام العامل للأجر الذي سيتم التنفيذ عليه في عقد العمل ا
[1192/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد معرفة عدد أيام الإجازة بحالة زواج العامل؟

[1193/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد معرفة الحسابات التي يمكنني تفعيلها للموظفين للتعديل في حساب مدد الخاص بنظام
[1194/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي اشتراطات فترة التجربة؟
[1195/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد معرفة ما إذا كان النسخة العربية وغير العربية متطابقة من حيث الخدمات والوظائ
[1196/3410] Exp 8/22 | hybrid | structural | bge_m3 | ما طريقة يتم الاستفادة من خدمة التنقل الوظيفي للعمال الوافدين بين المنشآت؟
[1197/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد معرفة أنواع الشكاوى التي يمكن أن يقدمها الموظف على صاحب العمل؟
[1198/3410] Exp 8/22 | hybrid | structural | bge_m3 | هل مسموح نظاماً لصاحب العمل تشغيل المرأة العاملة بعد الوضع بمدة أقل من 6 أسابيع؟
[1199/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد معرفة ما إذا كان هناك لائحة وقانون يحمي الأطفال من العنف الأسري؟

[1200/3410] Exp 8/22 | hybrid | structural | bge_m3 | ما طريقةية تعويض العامل المعين على بند الأجور عن رصيده من الاجازات العادية عند ا
Checkpoint saved: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\retrieval_evaluation_detailed_results_checkpoint.csv
[1201/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: موظف مددت خدمته لمدة سنتين بعد بلوغه السن النظام
[1202/3410] Exp 8/22 | hybrid | structural | bge_m3 | هل يستطيع نقل العمالة داخل الكيان الواحد؟
[1203/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد معرفة ما إذا كان تغطي الوثيقة النفقات الطبية اللازمة لعلاج العامل المنزلي ب
[1204/3410] Exp 8/22 | hybrid | structural | bge_m3 | هل يستطيع إلغاء التأشيرة المصدرة من مساند؟
[1205/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف الذي يشغل وظيفة خاضعة لنظا

[1206/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد معرفة ما إذا كان يحسم من راتب الموظف أيام غيابه عن العمل نتيجة مثوله أمام ا
[1207/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: موظف بعد احالته على التقاعد لبلوغ السن النظامية
[1208/3410] Exp 8/22 | hybrid | structural | bge_m3 | هل يستطيع تعديل المهنة بعد تطبيق المبادرة؟
[1209/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد معرفة ما إذا كان يستحق الموظف التعويض عن إجازته العادية إذا استقال قبل إكما
[1210/3410] Exp 8/22 | hybrid | structural | bge_m3 | ما طريقة يمكن الاستفادة من الخدمة؟
[1211/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد معرفة فترة الراحة اليومية للرضاعة؟

[1212/3410] Exp 8/22 | hybrid | structural | bge_m3 | في أي حالة يتاح تجديد رخصة العمل؟
[1213/3410] Exp 8/22 | hybrid | structural | bge_m3 | ما طريقة يتم حماية حقوق العامل؟
[1214/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف المتدرب لمكافآت وبدلات الت
[1215/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد معرفة ما إذا كان يحسب من عمره أقل من 18 سنة ضمن نسبة التوطين؟
[1216/3410] Exp 8/22 | hybrid | structural | bge_m3 | أريد معرفة شروط أهلية العامل الوافد للاستفادة من خدمة التنقل الوظيفي؟
[1217/3410] Exp 8/22 | hybrid | structural | bge_m3 | كم مدة فترة التجربة في نظام العمل السعودي؟
[1218/3410] Exp 8/22 | hybrid | structural | bge_m3 | هل يجوز وضع العامل تحت التجربة أكثر من مرة لدى نفس صاحب العمل؟

[1219/3410] Exp 8/22 | hybrid | structural | bge_m3 | ما الحد الأقصى لساعات العمل اليومية في نظام العمل؟
[1220/3410] Exp 8/22 | hybrid | structural | bge_m3 | ما الحد الأقصى لساعات العمل الأسبوعية؟
[1221/3410] Exp 8/22 | hybrid | structural | bge_m3 | هل تختلف ساعات العمل في شهر رمضان؟
[1222/3410] Exp 8/22 | hybrid | structural | bge_m3 | ما مدة الإجازة السنوية المستحقة للعامل؟
[1223/3410] Exp 8/22 | hybrid | structural | bge_m3 | متى تزيد الإجازة السنوية إلى ثلاثين يومًا؟
[1224/3410] Exp 8/22 | hybrid | structural | bge_m3 | هل يستحق العامل أجرًا عن أيام الإجازة غير المستخدمة عند انتهاء العمل؟
[1225/3410] Exp 8/22 | hybrid | structural | bge_m3 | هل يستحق العامل إجازة عند الزواج أو وفاة أحد الأقارب؟
[1226/3410] Exp 8/22 | hybrid | structural | bge_m3 | هل للعامل الحق في إجازة مرضية؟

[1227/3410] Exp 8/22 | hybrid | structural | bge_m3 | ما حالات انتهاء عقد العمل؟
[1228/3410] Exp 8/22 | hybrid | structural | bge_m3 | ما مدة الإشعار عند إنهاء العقد غير محدد المدة؟
[1229/3410] Exp 8/22 | hybrid | structural | bge_m3 | متى يستحق العامل تعويضًا عند إنهاء العقد لسبب غير مشروع؟
[1230/3410] Exp 8/22 | hybrid | structural | bge_m3 | متى يجوز لصاحب العمل إنهاء العقد دون مكافأة أو تعويض؟
[1231/3410] Exp 8/22 | hybrid | structural | bge_m3 | متى يجوز للعامل ترك العمل دون إشعار مع احتفاظه بحقوقه؟
[1232/3410] Exp 8/22 | hybrid | structural | bge_m3 | متى يستحق العامل مكافأة نهاية الخدمة؟
[1233/3410] Exp 8/22 | hybrid | structural | bge_m3 | هل يحق لصاحب العمل نقل العامل من مكان عمله الأصلي؟
[1234/3410] Exp 8/22 | hybrid | structural | bge_m3 | ما المقصود بعقد العمل في نظام العمل؟

[1235/3410] Exp 8/22 | hybrid | structural | bge_m3 | كيف يتم دفع أجر العامل؟
[1236/3410] Exp 8/22 | hybrid | structural | bge_m3 | ما واجبات صاحب العمل تجاه العامل؟
[1237/3410] Exp 8/22 | hybrid | structural | bge_m3 | ما التزامات العامل في نظام العمل؟
[1238/3410] Exp 8/22 | hybrid | structural | bge_m3 | ما الحد الأقصى لساعات العمل الإضافية وكيف تُحتسب؟
[1239/3410] Exp 8/22 | hybrid | structural | bge_m3 | ما أحكام السلامة والصحة المهنية في بيئة العمل؟
[1240/3410] Exp 8/22 | hybrid | structural | bge_m3 | ما حقوق العاملة في إجازة الوضع؟
====================================================================================================
Experiment 9/22: {'chunking_strategy': 'structural', 'embedding_model': 'bge_m3', 'retriever': 'hybrid', 'alpha': 0.8}
====================================================================================================
[1241/3410] Exp 9/22 | hybrid | structural | bge_m3 | ما طريقة يمكنني إلغاء أو تعديل طلب تغيير المهنة؟

[1242/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد معرفة الطريقة المتبعة لتسديد قسط التأمين؟
[1243/3410] Exp 9/22 | hybrid | structural | bge_m3 | ما طريقةية معاملة محرم الموظفة عند مرافقتها أثناء ابتعاثها للدراسة أو التدريب أو
[1244/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي أهداف برنامج نطاقات المطور؟
[1245/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية الجمع بين بدل المهنة المنصوص عليه
[1246/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: موظف أحيل للتحقيق أثناء إجراء المفاضلة لغرض التر

[1247/3410] Exp 9/22 | hybrid | structural | bge_m3 | ما طريقة يتم احتساب أجر الساعات الإضافية؟
[1248/3410] Exp 9/22 | hybrid | structural | bge_m3 | هل مسموح تعيين العمال بصفة مؤقتة طبقاً للائحة المعينين على بند الأجور؟
[1249/3410] Exp 9/22 | hybrid | structural | bge_m3 | هل يستطيع احتساب أيام المراجعة للمستشفيات داخل مقر العمل أو خارجه إجازة مرضية أو
[1250/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: اعرف حقوق العمال؟
Checkpoint saved: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\retrieval_evaluation_detailed_results_checkpoint.csv
[1251/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: في حال تم رصد مخالفات في ملف الأجور، أين أجد تفا
[1252/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما المقصود من كون عمال المستشفيات ضمن المساعدين

[1253/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: موظف قدم للرياض للالتحاق بدورة تدريبية وبعد انته
[1254/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد معرفة ما إذا كان يخصم بدل المواصلات من راتب الإجازة السنوية؟
[1255/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: موظف استقال من وظيفة بالمرتبة الرابعة ومن ثم عاد
[1256/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد معرفة عقد العمل؟
[1257/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد معرفة ما إذا كان تحسم رواتب العطل الرسمية والأعياد إذا سبقها غياب ولحقها غي

[1258/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد معرفة العمل المرن؟
[1259/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى جواز منح الموظف المنقول بترقية الدرجة الإ
[1260/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: في حالة غياب الموظف عن العمل وإيقاع عقوبة تأديبي
[1261/3410] Exp 9/22 | hybrid | structural | bge_m3 | ما طريقة يتم طلب المدرب الاختياري قبل التقدم بطلب شهادة "مواءمة"؟
[1262/3410] Exp 9/22 | hybrid | structural | bge_m3 | هل مسموح نظاماً للعامل الانتقال من منشأة في النطاق الأحمر بدون إذن صاحب العمل إل

[1263/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى امكانية ابتعاث أوايفاد العامل المعين على
[1264/3410] Exp 9/22 | hybrid | structural | bge_m3 | هل مسموح منح الموظف أثناء فترة التجربة إجازة استثنائية؟
[1265/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى إلزام الموظف بالعمل خارج وقت الدوام، وهل
[1266/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى انطباق المزايا المالية التي تصرف للمشاركي
[1267/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد معرفة ما إذا كان أستطيع رفع ملفات حماية الأجور عبر موقع وزارة الموارد البشر

[1268/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد معرفة الرسوم المطلوبة من المنشآت في برنامج "مواءمة"؟
[1269/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد معرفة ما إذا كان يتم إضافة البيانات التي تملكها الوزارة في الأصل للحقول الم
[1270/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي الحقوق والواجبات العامة للمرأة العاملة؟
[1271/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد معرفة خدمة نقل الموظفين؟
[1272/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد معرفة ما إذا كان ينطبق الشرط الجزائي على العامل أو صاحب العمل؟
[1273/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد معرفة شروط الخدمة؟

[1274/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد معرفة خدمات مبادرة تحسين العلاقة التعاقدية؟
[1275/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: إذا التحق الموظف بالتدريب أثناء إجازته الاستثنائ
[1276/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد معرفة ما إذا كان بإمكاني تعيين أي موظف لدي وإعطاءه صلاحية مفوض رواتب أو مدق
[1277/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف المتدرب الذي انقطع أثناء ف
[1278/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد معرفة ما إذا كان يطالب المستخدم المثبت على وظيفة مشمولة بسلم رواتب الموظفين

[1279/3410] Exp 9/22 | hybrid | structural | bge_m3 | ما طريقة أعرف ما إذا كانت منشأتي ملزمة بتطبيق برنامج حماية الأجور؟
[1280/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد معرفة برنامج نطاقات؟ وكيف يحسن بيئة العمل للسعوديين؟
[1281/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: لماذا توجد رسوم مالية على برنامج "مواءمة"؟ وهل ت
[1282/3410] Exp 9/22 | hybrid | structural | bge_m3 | هل مسموح نقل العامل المعين على بند الأجور إلى إحدى الجهات الحكومية مع الاحتفاظ ب
[1283/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد معرفة ما إذا كان يحسب برنامج نطاقات من لديهم وظائف رسمية في الحكومة ودوام ج
[1284/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي آلية الترشيح للمرشحين؟

[1285/3410] Exp 9/22 | hybrid | structural | bge_m3 | ما طريقة يمكن للمستفيد (المؤمن له) معرفة اسم شركة التأمين التابع لها؟
[1286/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد معرفة إجراءات الانتقال خلال السنة الأولى في الحالات الاستثنائية؟
[1287/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد معرفة ما إذا كان تمكن البوابة والانظمة التابعة لها المستخدم من تخصيص الخدما
[1288/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد معرفة ما إذا كان بإمكان أي موظف في منشأتي أن يسجل في منصة مُدد ويقوم برفع م
[1289/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى أحقية المعين على بند الأجور المكلف بالعمل
[1290/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد معرفة ما إذا كان تسري على شاغلي الوظائف المؤقتة القواعد الواردة في نظام الخ

[1291/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: كتابة العقد؟
[1292/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد معرفة ما إذا كان يترتب على العامل الوافد دفع أي رسوم حكومية (رخصة العمل – ا
[1293/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: موظف منح إجازة عادية تنتهي مع ابتداء عطلة أحد ال
[1294/3410] Exp 9/22 | hybrid | structural | bge_m3 | هل يستطيع للمستخدمين الوصول إلى قائمة عملياته او معاملاته السابقة في البوابة؟
[1295/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي خدمة الخروج النهائي؟
[1296/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما الفرق بين المهنة والمسمى الوظيفي؟

[1297/3410] Exp 9/22 | hybrid | structural | bge_m3 | ما طريقة يمكن التوفيق بين نصي المادتين (132) و (147) من اللائحة التنفيذية للموار
[1298/3410] Exp 9/22 | hybrid | structural | bge_m3 | هل يستطيع أن يتغير انطاق المنشأة دون تغيير في عدد العمالة خلال السنوات القادمة؟
[1299/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: لماذا يتوجب على المنشأة القيام بالتقيّيم الذاتي؟
[1300/3410] Exp 9/22 | hybrid | structural | bge_m3 | هل مسموح انهاء عقد العمل بسبب إعادة الهيكلة أو الظروف المالية للمنشأة؟
Checkpoint saved: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\retrieval_evaluation_detailed_results_checkpoint.csv
[1301/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد معرفة ما إذا كان تشمل إجازة أداء الامتحان الدراسي من يؤدي الامتحان خارج الم

[1302/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: موظف قررت الهيئة الطبية العامة معالجته في الداخل
[1303/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد معرفة ما إذا كان الخدمة تتيح تحديث بيانات العامل؟
[1304/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي الآلية لرفع نسب نطاقات تدريجيا؟ وكم هي المد
[1305/3410] Exp 9/22 | hybrid | structural | bge_m3 | هل يستطيع حفظ معاملة لخدمة معينة تم بدؤها من خلال البوابة والوصول إليها لاحقًا؟
[1306/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية احتفاظ العامل المعين على بند الأج

[1307/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: موظف فصل من الخدمة بناءً على حكم نهائي من ديوان
[1308/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد معرفة ما إذا كان يشمل برنامج نطاقات المستثمر الأجنبي؟
[1309/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: الفئات المشمولة بقرار الالزام بالتأمين على عقد ا
[1310/3410] Exp 9/22 | hybrid | structural | bge_m3 | هل يستطيع تفعيل بند التنافسية في عقد العمل؟
[1311/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي الإجازات المستحقة للمرأة العاملة؟

[1312/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد معرفة الاجراء الذي سيتم تطبيقه في حال عدم التزام المنشأة بنسب نطاقات؟
[1313/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى جواز إجبار الموظف على التمتع بإجازاته الع
[1314/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد معرفة الخدمات المقدمة في نظام مُدد لإدارة الرواتب؟
[1315/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد معرفة ما إذا كان تمكن البوابة والانظمة التابعة لها المستخدم من تعديل بيانات
[1316/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد معرفة المقصود بنصف صافي راتب الموظف مكفوف اليد ومن في حكمه وفقاً للمادة (19
[1317/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف المنتدب من خارج المملكة إل

[1318/3410] Exp 9/22 | hybrid | structural | bge_m3 | ما طريقة أقدم شكوى على أحد الموظفين في مكاتب العمل؟ وما الحل إذا لم تتم الإفادة
[1319/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي آلية احتساب نسب التوطين بعد تطبيق نطاقات ال
[1320/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: مدة عمل عقد العامل السعودي؟
[1321/3410] Exp 9/22 | hybrid | structural | bge_m3 | ما طريقة يعامل العامل غير السعودي المعين على بند الأجور من حيث بدل النقل بعد صدو
[1322/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما خطوات تنفيذ الخدمة؟
[1323/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية صرف بدل التفرغ للطبيبات خلال إجاز

[1324/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد معرفة ما إذا كان تسري أحكام لائحة المعينين على بند الأجور الصادرة بقرار مجل
[1325/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد معرفة ما إذا كان الخدمة متاحة للعامل؟
[1326/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى صرف بدل تعيين لمن يتم تعيينه بوظيفة خاضعة
[1327/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماذا يقصد ببرنامج نطاقات المطور؟
[1328/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد معرفة ما إذا كان يجب ان يكون العامل مسجل على منشاة؟

[1329/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى نظامية منح الموظف بعد تعيينه وفقاً لنظام
[1330/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية صرف بدل الترحيل المنصوص عليه بالم
[1331/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى استفادة العامل المعين على بند الأجور من م
[1332/3410] Exp 9/22 | hybrid | structural | bge_m3 | ما طريقة يمكنني معرفة إذا كنت مؤهل لتوثيق عقدي مع العامل/ة؟
[1333/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد معرفة ما إذا كان تحتسب مدة الإجازة الاستثنائية لغرض إكمال مدة السنة المطلوب

[1334/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد معرفة نظام إدارة الرواتب؟
[1335/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف مكفوف اليد للعلاوة الدورية
[1336/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: في الاله الحاسبة الخاصة ببرنامج نطاقات المطور هل
[1337/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية نقل العسكري إلى وظيفة مدنية؟
[1338/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي الحقوق العامة في عقد العمل؟
[1339/3410] Exp 9/22 | hybrid | structural | bge_m3 | ما طريقة يعامل الموظف المتدرب في الداخل أو الخارج في حالة إصابته بمرض وحصوله على

[1340/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي شروط وضوابط الإجازات للعامل؟
[1341/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى امكانية صرف مكافأة نهاية الخدمة المنصوص ع
[1342/3410] Exp 9/22 | hybrid | structural | bge_m3 | في أي حالة ينتهي عقد العمل؟
[1343/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: موظف منح إجازة عادية بعد عطلة أحد العيدين مباشرة
[1344/3410] Exp 9/22 | hybrid | structural | bge_m3 | ما طريقة يمكن تصحيح فرع المنشأة الذي يعمل فيها العامل ونقله إلى الفرع الصحيح؟

[1345/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماذا يحتوي عقد العمل؟
[1346/3410] Exp 9/22 | hybrid | structural | bge_m3 | ما طريقة يتم التحقق من استلام العامل للأجر الذي سيتم التنفيذ عليه في عقد العمل ا
[1347/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد معرفة عدد أيام الإجازة بحالة زواج العامل؟
[1348/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد معرفة الحسابات التي يمكنني تفعيلها للموظفين للتعديل في حساب مدد الخاص بنظام
[1349/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي اشتراطات فترة التجربة؟
[1350/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد معرفة ما إذا كان النسخة العربية وغير العربية متطابقة من حيث الخدمات والوظائ

Checkpoint saved: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\retrieval_evaluation_detailed_results_checkpoint.csv
[1351/3410] Exp 9/22 | hybrid | structural | bge_m3 | ما طريقة يتم الاستفادة من خدمة التنقل الوظيفي للعمال الوافدين بين المنشآت؟
[1352/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد معرفة أنواع الشكاوى التي يمكن أن يقدمها الموظف على صاحب العمل؟
[1353/3410] Exp 9/22 | hybrid | structural | bge_m3 | هل مسموح نظاماً لصاحب العمل تشغيل المرأة العاملة بعد الوضع بمدة أقل من 6 أسابيع؟
[1354/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد معرفة ما إذا كان هناك لائحة وقانون يحمي الأطفال من العنف الأسري؟
[1355/3410] Exp 9/22 | hybrid | structural | bge_m3 | ما طريقةية تعويض العامل المعين على بند الأجور عن رصيده من الاجازات العادية عند ا
[1356/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: موظف مددت خدمته لمدة سنتين بعد بلوغه السن النظام

[1357/3410] Exp 9/22 | hybrid | structural | bge_m3 | هل يستطيع نقل العمالة داخل الكيان الواحد؟
[1358/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد معرفة ما إذا كان تغطي الوثيقة النفقات الطبية اللازمة لعلاج العامل المنزلي ب
[1359/3410] Exp 9/22 | hybrid | structural | bge_m3 | هل يستطيع إلغاء التأشيرة المصدرة من مساند؟
[1360/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف الذي يشغل وظيفة خاضعة لنظا
[1361/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد معرفة ما إذا كان يحسم من راتب الموظف أيام غيابه عن العمل نتيجة مثوله أمام ا
[1362/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: موظف بعد احالته على التقاعد لبلوغ السن النظامية

[1363/3410] Exp 9/22 | hybrid | structural | bge_m3 | هل يستطيع تعديل المهنة بعد تطبيق المبادرة؟
[1364/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد معرفة ما إذا كان يستحق الموظف التعويض عن إجازته العادية إذا استقال قبل إكما
[1365/3410] Exp 9/22 | hybrid | structural | bge_m3 | ما طريقة يمكن الاستفادة من الخدمة؟
[1366/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد معرفة فترة الراحة اليومية للرضاعة؟
[1367/3410] Exp 9/22 | hybrid | structural | bge_m3 | في أي حالة يتاح تجديد رخصة العمل؟
[1368/3410] Exp 9/22 | hybrid | structural | bge_m3 | ما طريقة يتم حماية حقوق العامل؟
[1369/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف المتدرب لمكافآت وبدلات الت

[1370/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد معرفة ما إذا كان يحسب من عمره أقل من 18 سنة ضمن نسبة التوطين؟
[1371/3410] Exp 9/22 | hybrid | structural | bge_m3 | أريد معرفة شروط أهلية العامل الوافد للاستفادة من خدمة التنقل الوظيفي؟
[1372/3410] Exp 9/22 | hybrid | structural | bge_m3 | كم مدة فترة التجربة في نظام العمل السعودي؟
[1373/3410] Exp 9/22 | hybrid | structural | bge_m3 | هل يجوز وضع العامل تحت التجربة أكثر من مرة لدى نفس صاحب العمل؟
[1374/3410] Exp 9/22 | hybrid | structural | bge_m3 | ما الحد الأقصى لساعات العمل اليومية في نظام العمل؟
[1375/3410] Exp 9/22 | hybrid | structural | bge_m3 | ما الحد الأقصى لساعات العمل الأسبوعية؟
[1376/3410] Exp 9/22 | hybrid | structural | bge_m3 | هل تختلف ساعات العمل في شهر رمضان؟

[1377/3410] Exp 9/22 | hybrid | structural | bge_m3 | ما مدة الإجازة السنوية المستحقة للعامل؟
[1378/3410] Exp 9/22 | hybrid | structural | bge_m3 | متى تزيد الإجازة السنوية إلى ثلاثين يومًا؟
[1379/3410] Exp 9/22 | hybrid | structural | bge_m3 | هل يستحق العامل أجرًا عن أيام الإجازة غير المستخدمة عند انتهاء العمل؟
[1380/3410] Exp 9/22 | hybrid | structural | bge_m3 | هل يستحق العامل إجازة عند الزواج أو وفاة أحد الأقارب؟
[1381/3410] Exp 9/22 | hybrid | structural | bge_m3 | هل للعامل الحق في إجازة مرضية؟
[1382/3410] Exp 9/22 | hybrid | structural | bge_m3 | ما حالات انتهاء عقد العمل؟
[1383/3410] Exp 9/22 | hybrid | structural | bge_m3 | ما مدة الإشعار عند إنهاء العقد غير محدد المدة؟
[1384/3410] Exp 9/22 | hybrid | structural | bge_m3 | متى يستحق العامل تعويضًا عند إنهاء العقد لسبب غير مشروع؟

[1385/3410] Exp 9/22 | hybrid | structural | bge_m3 | متى يجوز لصاحب العمل إنهاء العقد دون مكافأة أو تعويض؟
[1386/3410] Exp 9/22 | hybrid | structural | bge_m3 | متى يجوز للعامل ترك العمل دون إشعار مع احتفاظه بحقوقه؟
[1387/3410] Exp 9/22 | hybrid | structural | bge_m3 | متى يستحق العامل مكافأة نهاية الخدمة؟
[1388/3410] Exp 9/22 | hybrid | structural | bge_m3 | هل يحق لصاحب العمل نقل العامل من مكان عمله الأصلي؟
[1389/3410] Exp 9/22 | hybrid | structural | bge_m3 | ما المقصود بعقد العمل في نظام العمل؟
[1390/3410] Exp 9/22 | hybrid | structural | bge_m3 | كيف يتم دفع أجر العامل؟
[1391/3410] Exp 9/22 | hybrid | structural | bge_m3 | ما واجبات صاحب العمل تجاه العامل؟
[1392/3410] Exp 9/22 | hybrid | structural | bge_m3 | ما التزامات العامل في نظام العمل؟

[1393/3410] Exp 9/22 | hybrid | structural | bge_m3 | ما الحد الأقصى لساعات العمل الإضافية وكيف تُحتسب؟
[1394/3410] Exp 9/22 | hybrid | structural | bge_m3 | ما أحكام السلامة والصحة المهنية في بيئة العمل؟
[1395/3410] Exp 9/22 | hybrid | structural | bge_m3 | ما حقوق العاملة في إجازة الوضع؟
====================================================================================================
Experiment 10/22: {'chunking_strategy': 'structural', 'embedding_model': 'bge_m3', 'retriever': 'hybrid', 'alpha': 0.9}
====================================================================================================
[1396/3410] Exp 10/22 | hybrid | structural | bge_m3 | ما طريقة يمكنني إلغاء أو تعديل طلب تغيير المهنة؟
[1397/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد معرفة الطريقة المتبعة لتسديد قسط التأمين؟
[1398/3410] Exp 10/22 | hybrid | structural | bge_m3 | ما طريقةية معاملة محرم الموظفة عند مرافقتها أثناء ابتعاثها للدراسة أو التدريب أو
[1399/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي أهداف برنامج نطاقات المطور؟
[1400/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية الجمع بين بدل المهنة المنصوص عليه

Checkpoint saved: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\retrieval_evaluation_detailed_results_checkpoint.csv
[1401/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: موظف أحيل للتحقيق أثناء إجراء المفاضلة لغرض التر
[1402/3410] Exp 10/22 | hybrid | structural | bge_m3 | ما طريقة يتم احتساب أجر الساعات الإضافية؟
[1403/3410] Exp 10/22 | hybrid | structural | bge_m3 | هل مسموح تعيين العمال بصفة مؤقتة طبقاً للائحة المعينين على بند الأجور؟
[1404/3410] Exp 10/22 | hybrid | structural | bge_m3 | هل يستطيع احتساب أيام المراجعة للمستشفيات داخل مقر العمل أو خارجه إجازة مرضية أو
[1405/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: اعرف حقوق العمال؟
[1406/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: في حال تم رصد مخالفات في ملف الأجور، أين أجد تفا

[1407/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما المقصود من كون عمال المستشفيات ضمن المساعدين
[1408/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: موظف قدم للرياض للالتحاق بدورة تدريبية وبعد انته
[1409/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد معرفة ما إذا كان يخصم بدل المواصلات من راتب الإجازة السنوية؟
[1410/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: موظف استقال من وظيفة بالمرتبة الرابعة ومن ثم عاد
[1411/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد معرفة عقد العمل؟

[1412/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد معرفة ما إذا كان تحسم رواتب العطل الرسمية والأعياد إذا سبقها غياب ولحقها غي
[1413/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد معرفة العمل المرن؟
[1414/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى جواز منح الموظف المنقول بترقية الدرجة الإ
[1415/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: في حالة غياب الموظف عن العمل وإيقاع عقوبة تأديبي
[1416/3410] Exp 10/22 | hybrid | structural | bge_m3 | ما طريقة يتم طلب المدرب الاختياري قبل التقدم بطلب شهادة "مواءمة"؟
[1417/3410] Exp 10/22 | hybrid | structural | bge_m3 | هل مسموح نظاماً للعامل الانتقال من منشأة في النطاق الأحمر بدون إذن صاحب العمل إل

[1418/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى امكانية ابتعاث أوايفاد العامل المعين على
[1419/3410] Exp 10/22 | hybrid | structural | bge_m3 | هل مسموح منح الموظف أثناء فترة التجربة إجازة استثنائية؟
[1420/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى إلزام الموظف بالعمل خارج وقت الدوام، وهل
[1421/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى انطباق المزايا المالية التي تصرف للمشاركي
[1422/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد معرفة ما إذا كان أستطيع رفع ملفات حماية الأجور عبر موقع وزارة الموارد البشر

[1423/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد معرفة الرسوم المطلوبة من المنشآت في برنامج "مواءمة"؟
[1424/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد معرفة ما إذا كان يتم إضافة البيانات التي تملكها الوزارة في الأصل للحقول الم
[1425/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي الحقوق والواجبات العامة للمرأة العاملة؟
[1426/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد معرفة خدمة نقل الموظفين؟
[1427/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد معرفة ما إذا كان ينطبق الشرط الجزائي على العامل أو صاحب العمل؟
[1428/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد معرفة شروط الخدمة؟
[1429/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد معرفة خدمات مبادرة تحسين العلاقة التعاقدية؟
[1430/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: إذا التحق الموظف بالتدريب أثناء إجازته الاستثنائ

[1431/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد معرفة ما إذا كان بإمكاني تعيين أي موظف لدي وإعطاءه صلاحية مفوض رواتب أو مدق
[1432/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف المتدرب الذي انقطع أثناء ف
[1433/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد معرفة ما إذا كان يطالب المستخدم المثبت على وظيفة مشمولة بسلم رواتب الموظفين
[1434/3410] Exp 10/22 | hybrid | structural | bge_m3 | ما طريقة أعرف ما إذا كانت منشأتي ملزمة بتطبيق برنامج حماية الأجور؟
[1435/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد معرفة برنامج نطاقات؟ وكيف يحسن بيئة العمل للسعوديين؟

[1436/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: لماذا توجد رسوم مالية على برنامج "مواءمة"؟ وهل ت
[1437/3410] Exp 10/22 | hybrid | structural | bge_m3 | هل مسموح نقل العامل المعين على بند الأجور إلى إحدى الجهات الحكومية مع الاحتفاظ ب
[1438/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد معرفة ما إذا كان يحسب برنامج نطاقات من لديهم وظائف رسمية في الحكومة ودوام ج
[1439/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي آلية الترشيح للمرشحين؟
[1440/3410] Exp 10/22 | hybrid | structural | bge_m3 | ما طريقة يمكن للمستفيد (المؤمن له) معرفة اسم شركة التأمين التابع لها؟
[1441/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد معرفة إجراءات الانتقال خلال السنة الأولى في الحالات الاستثنائية؟

[1442/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد معرفة ما إذا كان تمكن البوابة والانظمة التابعة لها المستخدم من تخصيص الخدما
[1443/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد معرفة ما إذا كان بإمكان أي موظف في منشأتي أن يسجل في منصة مُدد ويقوم برفع م
[1444/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى أحقية المعين على بند الأجور المكلف بالعمل
[1445/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد معرفة ما إذا كان تسري على شاغلي الوظائف المؤقتة القواعد الواردة في نظام الخ
[1446/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: كتابة العقد؟

[1447/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد معرفة ما إذا كان يترتب على العامل الوافد دفع أي رسوم حكومية (رخصة العمل – ا
[1448/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: موظف منح إجازة عادية تنتهي مع ابتداء عطلة أحد ال
[1449/3410] Exp 10/22 | hybrid | structural | bge_m3 | هل يستطيع للمستخدمين الوصول إلى قائمة عملياته او معاملاته السابقة في البوابة؟
[1450/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي خدمة الخروج النهائي؟
Checkpoint saved: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\retrieval_evaluation_detailed_results_checkpoint.csv
[1451/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما الفرق بين المهنة والمسمى الوظيفي؟

[1452/3410] Exp 10/22 | hybrid | structural | bge_m3 | ما طريقة يمكن التوفيق بين نصي المادتين (132) و (147) من اللائحة التنفيذية للموار
[1453/3410] Exp 10/22 | hybrid | structural | bge_m3 | هل يستطيع أن يتغير انطاق المنشأة دون تغيير في عدد العمالة خلال السنوات القادمة؟
[1454/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: لماذا يتوجب على المنشأة القيام بالتقيّيم الذاتي؟
[1455/3410] Exp 10/22 | hybrid | structural | bge_m3 | هل مسموح انهاء عقد العمل بسبب إعادة الهيكلة أو الظروف المالية للمنشأة؟
[1456/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد معرفة ما إذا كان تشمل إجازة أداء الامتحان الدراسي من يؤدي الامتحان خارج الم
[1457/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: موظف قررت الهيئة الطبية العامة معالجته في الداخل

[1458/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد معرفة ما إذا كان الخدمة تتيح تحديث بيانات العامل؟
[1459/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي الآلية لرفع نسب نطاقات تدريجيا؟ وكم هي المد
[1460/3410] Exp 10/22 | hybrid | structural | bge_m3 | هل يستطيع حفظ معاملة لخدمة معينة تم بدؤها من خلال البوابة والوصول إليها لاحقًا؟
[1461/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية احتفاظ العامل المعين على بند الأج
[1462/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: موظف فصل من الخدمة بناءً على حكم نهائي من ديوان

[1463/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد معرفة ما إذا كان يشمل برنامج نطاقات المستثمر الأجنبي؟
[1464/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: الفئات المشمولة بقرار الالزام بالتأمين على عقد ا
[1465/3410] Exp 10/22 | hybrid | structural | bge_m3 | هل يستطيع تفعيل بند التنافسية في عقد العمل؟
[1466/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي الإجازات المستحقة للمرأة العاملة؟
[1467/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد معرفة الاجراء الذي سيتم تطبيقه في حال عدم التزام المنشأة بنسب نطاقات؟
[1468/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى جواز إجبار الموظف على التمتع بإجازاته الع

[1469/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد معرفة الخدمات المقدمة في نظام مُدد لإدارة الرواتب؟
[1470/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد معرفة ما إذا كان تمكن البوابة والانظمة التابعة لها المستخدم من تعديل بيانات
[1471/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد معرفة المقصود بنصف صافي راتب الموظف مكفوف اليد ومن في حكمه وفقاً للمادة (19
[1472/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف المنتدب من خارج المملكة إل
[1473/3410] Exp 10/22 | hybrid | structural | bge_m3 | ما طريقة أقدم شكوى على أحد الموظفين في مكاتب العمل؟ وما الحل إذا لم تتم الإفادة

[1474/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي آلية احتساب نسب التوطين بعد تطبيق نطاقات ال
[1475/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: مدة عمل عقد العامل السعودي؟
[1476/3410] Exp 10/22 | hybrid | structural | bge_m3 | ما طريقة يعامل العامل غير السعودي المعين على بند الأجور من حيث بدل النقل بعد صدو
[1477/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما خطوات تنفيذ الخدمة؟
[1478/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية صرف بدل التفرغ للطبيبات خلال إجاز
[1479/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد معرفة ما إذا كان تسري أحكام لائحة المعينين على بند الأجور الصادرة بقرار مجل

[1480/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد معرفة ما إذا كان الخدمة متاحة للعامل؟
[1481/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى صرف بدل تعيين لمن يتم تعيينه بوظيفة خاضعة
[1482/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماذا يقصد ببرنامج نطاقات المطور؟
[1483/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد معرفة ما إذا كان يجب ان يكون العامل مسجل على منشاة؟
[1484/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى نظامية منح الموظف بعد تعيينه وفقاً لنظام

[1485/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية صرف بدل الترحيل المنصوص عليه بالم
[1486/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى استفادة العامل المعين على بند الأجور من م
[1487/3410] Exp 10/22 | hybrid | structural | bge_m3 | ما طريقة يمكنني معرفة إذا كنت مؤهل لتوثيق عقدي مع العامل/ة؟
[1488/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد معرفة ما إذا كان تحتسب مدة الإجازة الاستثنائية لغرض إكمال مدة السنة المطلوب

[1489/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد معرفة نظام إدارة الرواتب؟
[1490/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف مكفوف اليد للعلاوة الدورية
[1491/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: في الاله الحاسبة الخاصة ببرنامج نطاقات المطور هل
[1492/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية نقل العسكري إلى وظيفة مدنية؟
[1493/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي الحقوق العامة في عقد العمل؟
[1494/3410] Exp 10/22 | hybrid | structural | bge_m3 | ما طريقة يعامل الموظف المتدرب في الداخل أو الخارج في حالة إصابته بمرض وحصوله على

[1495/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي شروط وضوابط الإجازات للعامل؟
[1496/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى امكانية صرف مكافأة نهاية الخدمة المنصوص ع
[1497/3410] Exp 10/22 | hybrid | structural | bge_m3 | في أي حالة ينتهي عقد العمل؟
[1498/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: موظف منح إجازة عادية بعد عطلة أحد العيدين مباشرة
[1499/3410] Exp 10/22 | hybrid | structural | bge_m3 | ما طريقة يمكن تصحيح فرع المنشأة الذي يعمل فيها العامل ونقله إلى الفرع الصحيح؟

[1500/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماذا يحتوي عقد العمل؟
Checkpoint saved: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\retrieval_evaluation_detailed_results_checkpoint.csv
[1501/3410] Exp 10/22 | hybrid | structural | bge_m3 | ما طريقة يتم التحقق من استلام العامل للأجر الذي سيتم التنفيذ عليه في عقد العمل ا
[1502/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد معرفة عدد أيام الإجازة بحالة زواج العامل؟
[1503/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد معرفة الحسابات التي يمكنني تفعيلها للموظفين للتعديل في حساب مدد الخاص بنظام
[1504/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي اشتراطات فترة التجربة؟
[1505/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد معرفة ما إذا كان النسخة العربية وغير العربية متطابقة من حيث الخدمات والوظائ

[1506/3410] Exp 10/22 | hybrid | structural | bge_m3 | ما طريقة يتم الاستفادة من خدمة التنقل الوظيفي للعمال الوافدين بين المنشآت؟
[1507/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد معرفة أنواع الشكاوى التي يمكن أن يقدمها الموظف على صاحب العمل؟
[1508/3410] Exp 10/22 | hybrid | structural | bge_m3 | هل مسموح نظاماً لصاحب العمل تشغيل المرأة العاملة بعد الوضع بمدة أقل من 6 أسابيع؟
[1509/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد معرفة ما إذا كان هناك لائحة وقانون يحمي الأطفال من العنف الأسري؟
[1510/3410] Exp 10/22 | hybrid | structural | bge_m3 | ما طريقةية تعويض العامل المعين على بند الأجور عن رصيده من الاجازات العادية عند ا
[1511/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: موظف مددت خدمته لمدة سنتين بعد بلوغه السن النظام

[1512/3410] Exp 10/22 | hybrid | structural | bge_m3 | هل يستطيع نقل العمالة داخل الكيان الواحد؟
[1513/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد معرفة ما إذا كان تغطي الوثيقة النفقات الطبية اللازمة لعلاج العامل المنزلي ب
[1514/3410] Exp 10/22 | hybrid | structural | bge_m3 | هل يستطيع إلغاء التأشيرة المصدرة من مساند؟
[1515/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف الذي يشغل وظيفة خاضعة لنظا
[1516/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد معرفة ما إذا كان يحسم من راتب الموظف أيام غيابه عن العمل نتيجة مثوله أمام ا
[1517/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: موظف بعد احالته على التقاعد لبلوغ السن النظامية

[1518/3410] Exp 10/22 | hybrid | structural | bge_m3 | هل يستطيع تعديل المهنة بعد تطبيق المبادرة؟
[1519/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد معرفة ما إذا كان يستحق الموظف التعويض عن إجازته العادية إذا استقال قبل إكما
[1520/3410] Exp 10/22 | hybrid | structural | bge_m3 | ما طريقة يمكن الاستفادة من الخدمة؟
[1521/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد معرفة فترة الراحة اليومية للرضاعة؟
[1522/3410] Exp 10/22 | hybrid | structural | bge_m3 | في أي حالة يتاح تجديد رخصة العمل؟
[1523/3410] Exp 10/22 | hybrid | structural | bge_m3 | ما طريقة يتم حماية حقوق العامل؟
[1524/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف المتدرب لمكافآت وبدلات الت
[1525/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد معرفة ما إذا كان يحسب من عمره أقل من 18 سنة ضمن نسبة التوطين؟

[1526/3410] Exp 10/22 | hybrid | structural | bge_m3 | أريد معرفة شروط أهلية العامل الوافد للاستفادة من خدمة التنقل الوظيفي؟
[1527/3410] Exp 10/22 | hybrid | structural | bge_m3 | كم مدة فترة التجربة في نظام العمل السعودي؟
[1528/3410] Exp 10/22 | hybrid | structural | bge_m3 | هل يجوز وضع العامل تحت التجربة أكثر من مرة لدى نفس صاحب العمل؟
[1529/3410] Exp 10/22 | hybrid | structural | bge_m3 | ما الحد الأقصى لساعات العمل اليومية في نظام العمل؟
[1530/3410] Exp 10/22 | hybrid | structural | bge_m3 | ما الحد الأقصى لساعات العمل الأسبوعية؟
[1531/3410] Exp 10/22 | hybrid | structural | bge_m3 | هل تختلف ساعات العمل في شهر رمضان؟
[1532/3410] Exp 10/22 | hybrid | structural | bge_m3 | ما مدة الإجازة السنوية المستحقة للعامل؟
[1533/3410] Exp 10/22 | hybrid | structural | bge_m3 | متى تزيد الإجازة السنوية إلى ثلاثين يومًا؟

[1534/3410] Exp 10/22 | hybrid | structural | bge_m3 | هل يستحق العامل أجرًا عن أيام الإجازة غير المستخدمة عند انتهاء العمل؟
[1535/3410] Exp 10/22 | hybrid | structural | bge_m3 | هل يستحق العامل إجازة عند الزواج أو وفاة أحد الأقارب؟
[1536/3410] Exp 10/22 | hybrid | structural | bge_m3 | هل للعامل الحق في إجازة مرضية؟
[1537/3410] Exp 10/22 | hybrid | structural | bge_m3 | ما حالات انتهاء عقد العمل؟
[1538/3410] Exp 10/22 | hybrid | structural | bge_m3 | ما مدة الإشعار عند إنهاء العقد غير محدد المدة؟
[1539/3410] Exp 10/22 | hybrid | structural | bge_m3 | متى يستحق العامل تعويضًا عند إنهاء العقد لسبب غير مشروع؟
[1540/3410] Exp 10/22 | hybrid | structural | bge_m3 | متى يجوز لصاحب العمل إنهاء العقد دون مكافأة أو تعويض؟
[1541/3410] Exp 10/22 | hybrid | structural | bge_m3 | متى يجوز للعامل ترك العمل دون إشعار مع احتفاظه بحقوقه؟

[1542/3410] Exp 10/22 | hybrid | structural | bge_m3 | متى يستحق العامل مكافأة نهاية الخدمة؟
[1543/3410] Exp 10/22 | hybrid | structural | bge_m3 | هل يحق لصاحب العمل نقل العامل من مكان عمله الأصلي؟
[1544/3410] Exp 10/22 | hybrid | structural | bge_m3 | ما المقصود بعقد العمل في نظام العمل؟
[1545/3410] Exp 10/22 | hybrid | structural | bge_m3 | كيف يتم دفع أجر العامل؟
[1546/3410] Exp 10/22 | hybrid | structural | bge_m3 | ما واجبات صاحب العمل تجاه العامل؟
[1547/3410] Exp 10/22 | hybrid | structural | bge_m3 | ما التزامات العامل في نظام العمل؟
[1548/3410] Exp 10/22 | hybrid | structural | bge_m3 | ما الحد الأقصى لساعات العمل الإضافية وكيف تُحتسب؟
[1549/3410] Exp 10/22 | hybrid | structural | bge_m3 | ما أحكام السلامة والصحة المهنية في بيئة العمل؟
[1550/3410] Exp 10/22 | hybrid | structural | bge_m3 | ما حقوق العاملة في إجازة الوضع؟

Checkpoint saved: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\retrieval_evaluation_detailed_results_checkpoint.csv
====================================================================================================
Experiment 11/22: {'chunking_strategy': 'structural', 'embedding_model': 'bge_m3', 'retriever': 'hybrid_reranker', 'alpha': 0.8}
====================================================================================================
[1551/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | ما طريقة يمكنني إلغاء أو تعديل طلب تغيير المهنة؟

[1552/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد معرفة الطريقة المتبعة لتسديد قسط التأمين؟

[1553/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | ما طريقةية معاملة محرم الموظفة عند مرافقتها أثناء ابتعاثها للدراسة أو التدريب أو

[1554/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي أهداف برنامج نطاقات المطور؟

[1555/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية الجمع بين بدل المهنة المنصوص عليه

[1556/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: موظف أحيل للتحقيق أثناء إجراء المفاضلة لغرض التر

[1557/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | ما طريقة يتم احتساب أجر الساعات الإضافية؟

[1558/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | هل مسموح تعيين العمال بصفة مؤقتة طبقاً للائحة المعينين على بند الأجور؟

[1559/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | هل يستطيع احتساب أيام المراجعة للمستشفيات داخل مقر العمل أو خارجه إجازة مرضية أو

[1560/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: اعرف حقوق العمال؟

[1561/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: في حال تم رصد مخالفات في ملف الأجور، أين أجد تفا

[1562/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما المقصود من كون عمال المستشفيات ضمن المساعدين

[1563/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: موظف قدم للرياض للالتحاق بدورة تدريبية وبعد انته

[1564/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد معرفة ما إذا كان يخصم بدل المواصلات من راتب الإجازة السنوية؟

[1565/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: موظف استقال من وظيفة بالمرتبة الرابعة ومن ثم عاد

[1566/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد معرفة عقد العمل؟

[1567/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد معرفة ما إذا كان تحسم رواتب العطل الرسمية والأعياد إذا سبقها غياب ولحقها غي

[1568/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد معرفة العمل المرن؟

[1569/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى جواز منح الموظف المنقول بترقية الدرجة الإ

[1570/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: في حالة غياب الموظف عن العمل وإيقاع عقوبة تأديبي

[1571/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | ما طريقة يتم طلب المدرب الاختياري قبل التقدم بطلب شهادة "مواءمة"؟

[1572/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | هل مسموح نظاماً للعامل الانتقال من منشأة في النطاق الأحمر بدون إذن صاحب العمل إل

[1573/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى امكانية ابتعاث أوايفاد العامل المعين على

[1574/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | هل مسموح منح الموظف أثناء فترة التجربة إجازة استثنائية؟

[1575/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى إلزام الموظف بالعمل خارج وقت الدوام، وهل

[1576/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى انطباق المزايا المالية التي تصرف للمشاركي

[1577/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد معرفة ما إذا كان أستطيع رفع ملفات حماية الأجور عبر موقع وزارة الموارد البشر

[1578/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد معرفة الرسوم المطلوبة من المنشآت في برنامج "مواءمة"؟

[1579/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد معرفة ما إذا كان يتم إضافة البيانات التي تملكها الوزارة في الأصل للحقول الم

[1580/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي الحقوق والواجبات العامة للمرأة العاملة؟

[1581/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد معرفة خدمة نقل الموظفين؟

[1582/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد معرفة ما إذا كان ينطبق الشرط الجزائي على العامل أو صاحب العمل؟

[1583/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد معرفة شروط الخدمة؟

[1584/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد معرفة خدمات مبادرة تحسين العلاقة التعاقدية؟

[1585/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: إذا التحق الموظف بالتدريب أثناء إجازته الاستثنائ

[1586/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد معرفة ما إذا كان بإمكاني تعيين أي موظف لدي وإعطاءه صلاحية مفوض رواتب أو مدق

[1587/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف المتدرب الذي انقطع أثناء ف

[1588/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد معرفة ما إذا كان يطالب المستخدم المثبت على وظيفة مشمولة بسلم رواتب الموظفين

[1589/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | ما طريقة أعرف ما إذا كانت منشأتي ملزمة بتطبيق برنامج حماية الأجور؟

[1590/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد معرفة برنامج نطاقات؟ وكيف يحسن بيئة العمل للسعوديين؟

[1591/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: لماذا توجد رسوم مالية على برنامج "مواءمة"؟ وهل ت

[1592/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | هل مسموح نقل العامل المعين على بند الأجور إلى إحدى الجهات الحكومية مع الاحتفاظ ب

[1593/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد معرفة ما إذا كان يحسب برنامج نطاقات من لديهم وظائف رسمية في الحكومة ودوام ج

[1594/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي آلية الترشيح للمرشحين؟

[1595/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | ما طريقة يمكن للمستفيد (المؤمن له) معرفة اسم شركة التأمين التابع لها؟

[1596/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد معرفة إجراءات الانتقال خلال السنة الأولى في الحالات الاستثنائية؟

[1597/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد معرفة ما إذا كان تمكن البوابة والانظمة التابعة لها المستخدم من تخصيص الخدما

[1598/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد معرفة ما إذا كان بإمكان أي موظف في منشأتي أن يسجل في منصة مُدد ويقوم برفع م

[1599/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى أحقية المعين على بند الأجور المكلف بالعمل

[1600/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد معرفة ما إذا كان تسري على شاغلي الوظائف المؤقتة القواعد الواردة في نظام الخ

Checkpoint saved: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\retrieval_evaluation_detailed_results_checkpoint.csv
[1601/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: كتابة العقد؟

[1602/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد معرفة ما إذا كان يترتب على العامل الوافد دفع أي رسوم حكومية (رخصة العمل – ا

[1603/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: موظف منح إجازة عادية تنتهي مع ابتداء عطلة أحد ال

[1604/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | هل يستطيع للمستخدمين الوصول إلى قائمة عملياته او معاملاته السابقة في البوابة؟

[1605/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي خدمة الخروج النهائي؟

[1606/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما الفرق بين المهنة والمسمى الوظيفي؟

[1607/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | ما طريقة يمكن التوفيق بين نصي المادتين (132) و (147) من اللائحة التنفيذية للموار

[1608/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | هل يستطيع أن يتغير انطاق المنشأة دون تغيير في عدد العمالة خلال السنوات القادمة؟

[1609/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: لماذا يتوجب على المنشأة القيام بالتقيّيم الذاتي؟

[1610/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | هل مسموح انهاء عقد العمل بسبب إعادة الهيكلة أو الظروف المالية للمنشأة؟

[1611/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد معرفة ما إذا كان تشمل إجازة أداء الامتحان الدراسي من يؤدي الامتحان خارج الم

[1612/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: موظف قررت الهيئة الطبية العامة معالجته في الداخل

[1613/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد معرفة ما إذا كان الخدمة تتيح تحديث بيانات العامل؟

[1614/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي الآلية لرفع نسب نطاقات تدريجيا؟ وكم هي المد

[1615/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | هل يستطيع حفظ معاملة لخدمة معينة تم بدؤها من خلال البوابة والوصول إليها لاحقًا؟

[1616/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية احتفاظ العامل المعين على بند الأج

[1617/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: موظف فصل من الخدمة بناءً على حكم نهائي من ديوان

[1618/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد معرفة ما إذا كان يشمل برنامج نطاقات المستثمر الأجنبي؟

[1619/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: الفئات المشمولة بقرار الالزام بالتأمين على عقد ا

[1620/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | هل يستطيع تفعيل بند التنافسية في عقد العمل؟

[1621/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي الإجازات المستحقة للمرأة العاملة؟

[1622/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد معرفة الاجراء الذي سيتم تطبيقه في حال عدم التزام المنشأة بنسب نطاقات؟

[1623/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى جواز إجبار الموظف على التمتع بإجازاته الع

[1624/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد معرفة الخدمات المقدمة في نظام مُدد لإدارة الرواتب؟

[1625/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد معرفة ما إذا كان تمكن البوابة والانظمة التابعة لها المستخدم من تعديل بيانات

[1626/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد معرفة المقصود بنصف صافي راتب الموظف مكفوف اليد ومن في حكمه وفقاً للمادة (19

[1627/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف المنتدب من خارج المملكة إل

[1628/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | ما طريقة أقدم شكوى على أحد الموظفين في مكاتب العمل؟ وما الحل إذا لم تتم الإفادة

[1629/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي آلية احتساب نسب التوطين بعد تطبيق نطاقات ال

[1630/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: مدة عمل عقد العامل السعودي؟

[1631/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | ما طريقة يعامل العامل غير السعودي المعين على بند الأجور من حيث بدل النقل بعد صدو

[1632/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما خطوات تنفيذ الخدمة؟

[1633/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية صرف بدل التفرغ للطبيبات خلال إجاز

[1634/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد معرفة ما إذا كان تسري أحكام لائحة المعينين على بند الأجور الصادرة بقرار مجل

[1635/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد معرفة ما إذا كان الخدمة متاحة للعامل؟

[1636/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى صرف بدل تعيين لمن يتم تعيينه بوظيفة خاضعة

[1637/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماذا يقصد ببرنامج نطاقات المطور؟

[1638/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد معرفة ما إذا كان يجب ان يكون العامل مسجل على منشاة؟

[1639/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى نظامية منح الموظف بعد تعيينه وفقاً لنظام

[1640/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية صرف بدل الترحيل المنصوص عليه بالم

[1641/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى استفادة العامل المعين على بند الأجور من م

[1642/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | ما طريقة يمكنني معرفة إذا كنت مؤهل لتوثيق عقدي مع العامل/ة؟

[1643/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد معرفة ما إذا كان تحتسب مدة الإجازة الاستثنائية لغرض إكمال مدة السنة المطلوب

[1644/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد معرفة نظام إدارة الرواتب؟

[1645/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف مكفوف اليد للعلاوة الدورية

[1646/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: في الاله الحاسبة الخاصة ببرنامج نطاقات المطور هل

[1647/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية نقل العسكري إلى وظيفة مدنية؟

[1648/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي الحقوق العامة في عقد العمل؟

[1649/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | ما طريقة يعامل الموظف المتدرب في الداخل أو الخارج في حالة إصابته بمرض وحصوله على

[1650/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي شروط وضوابط الإجازات للعامل؟

Checkpoint saved: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\retrieval_evaluation_detailed_results_checkpoint.csv
[1651/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى امكانية صرف مكافأة نهاية الخدمة المنصوص ع

[1652/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | في أي حالة ينتهي عقد العمل؟

[1653/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: موظف منح إجازة عادية بعد عطلة أحد العيدين مباشرة

[1654/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | ما طريقة يمكن تصحيح فرع المنشأة الذي يعمل فيها العامل ونقله إلى الفرع الصحيح؟

[1655/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماذا يحتوي عقد العمل؟

[1656/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | ما طريقة يتم التحقق من استلام العامل للأجر الذي سيتم التنفيذ عليه في عقد العمل ا

[1657/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد معرفة عدد أيام الإجازة بحالة زواج العامل؟

[1658/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد معرفة الحسابات التي يمكنني تفعيلها للموظفين للتعديل في حساب مدد الخاص بنظام

[1659/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي اشتراطات فترة التجربة؟

[1660/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد معرفة ما إذا كان النسخة العربية وغير العربية متطابقة من حيث الخدمات والوظائ

[1661/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | ما طريقة يتم الاستفادة من خدمة التنقل الوظيفي للعمال الوافدين بين المنشآت؟

[1662/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد معرفة أنواع الشكاوى التي يمكن أن يقدمها الموظف على صاحب العمل؟

[1663/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | هل مسموح نظاماً لصاحب العمل تشغيل المرأة العاملة بعد الوضع بمدة أقل من 6 أسابيع؟

[1664/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد معرفة ما إذا كان هناك لائحة وقانون يحمي الأطفال من العنف الأسري؟

[1665/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | ما طريقةية تعويض العامل المعين على بند الأجور عن رصيده من الاجازات العادية عند ا

[1666/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: موظف مددت خدمته لمدة سنتين بعد بلوغه السن النظام

[1667/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | هل يستطيع نقل العمالة داخل الكيان الواحد؟

[1668/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد معرفة ما إذا كان تغطي الوثيقة النفقات الطبية اللازمة لعلاج العامل المنزلي ب

[1669/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | هل يستطيع إلغاء التأشيرة المصدرة من مساند؟

[1670/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف الذي يشغل وظيفة خاضعة لنظا

[1671/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد معرفة ما إذا كان يحسم من راتب الموظف أيام غيابه عن العمل نتيجة مثوله أمام ا

[1672/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: موظف بعد احالته على التقاعد لبلوغ السن النظامية

[1673/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | هل يستطيع تعديل المهنة بعد تطبيق المبادرة؟

[1674/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد معرفة ما إذا كان يستحق الموظف التعويض عن إجازته العادية إذا استقال قبل إكما

[1675/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | ما طريقة يمكن الاستفادة من الخدمة؟

[1676/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد معرفة فترة الراحة اليومية للرضاعة؟

[1677/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | في أي حالة يتاح تجديد رخصة العمل؟

[1678/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | ما طريقة يتم حماية حقوق العامل؟

[1679/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف المتدرب لمكافآت وبدلات الت

[1680/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد معرفة ما إذا كان يحسب من عمره أقل من 18 سنة ضمن نسبة التوطين؟

[1681/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | أريد معرفة شروط أهلية العامل الوافد للاستفادة من خدمة التنقل الوظيفي؟

[1682/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | كم مدة فترة التجربة في نظام العمل السعودي؟

[1683/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | هل يجوز وضع العامل تحت التجربة أكثر من مرة لدى نفس صاحب العمل؟

[1684/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | ما الحد الأقصى لساعات العمل اليومية في نظام العمل؟

[1685/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | ما الحد الأقصى لساعات العمل الأسبوعية؟

[1686/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | هل تختلف ساعات العمل في شهر رمضان؟

[1687/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | ما مدة الإجازة السنوية المستحقة للعامل؟

[1688/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | متى تزيد الإجازة السنوية إلى ثلاثين يومًا؟

[1689/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | هل يستحق العامل أجرًا عن أيام الإجازة غير المستخدمة عند انتهاء العمل؟

[1690/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | هل يستحق العامل إجازة عند الزواج أو وفاة أحد الأقارب؟

[1691/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | هل للعامل الحق في إجازة مرضية؟

[1692/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | ما حالات انتهاء عقد العمل؟

[1693/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | ما مدة الإشعار عند إنهاء العقد غير محدد المدة؟

[1694/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | متى يستحق العامل تعويضًا عند إنهاء العقد لسبب غير مشروع؟

[1695/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | متى يجوز لصاحب العمل إنهاء العقد دون مكافأة أو تعويض؟

[1696/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | متى يجوز للعامل ترك العمل دون إشعار مع احتفاظه بحقوقه؟

[1697/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | متى يستحق العامل مكافأة نهاية الخدمة؟

[1698/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | هل يحق لصاحب العمل نقل العامل من مكان عمله الأصلي؟

[1699/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | ما المقصود بعقد العمل في نظام العمل؟

[1700/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | كيف يتم دفع أجر العامل؟

Checkpoint saved: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\retrieval_evaluation_detailed_results_checkpoint.csv
[1701/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | ما واجبات صاحب العمل تجاه العامل؟

[1702/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | ما التزامات العامل في نظام العمل؟

[1703/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | ما الحد الأقصى لساعات العمل الإضافية وكيف تُحتسب؟

[1704/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | ما أحكام السلامة والصحة المهنية في بيئة العمل؟

[1705/3410] Exp 11/22 | hybrid_reranker | structural | bge_m3 | ما حقوق العاملة في إجازة الوضع؟

====================================================================================================
Experiment 12/22: {'chunking_strategy': 'fixed_size', 'embedding_model': 'none', 'retriever': 'bm25', 'alpha': None}
====================================================================================================
[1706/3410] Exp 12/22 | bm25 | fixed_size | none | ما طريقة يمكنني إلغاء أو تعديل طلب تغيير المهنة؟
[1707/3410] Exp 12/22 | bm25 | fixed_size | none | أريد معرفة الطريقة المتبعة لتسديد قسط التأمين؟
[1708/3410] Exp 12/22 | bm25 | fixed_size | none | ما طريقةية معاملة محرم الموظفة عند مرافقتها أثناء ابتعاثها للدراسة أو التدريب أو
[1709/3410] Exp 12/22 | bm25 | fixed_size | none | أريد توضيح الحكم النظامي بخصوص: ماهي أهداف برنامج نطاقات المطور؟
[1710/3410] Exp 12/22 | bm25 | fixed_size | none | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية الجمع بين بدل المهنة المنصوص عليه
[1711/3410] Exp 12/22 | bm25 | fixed_size | none | أريد توضيح الحكم النظامي بخصوص: موظف أحيل للتحقيق أثناء إجراء المفاضلة لغرض التر
[1712/3410] Exp 12/22 | bm25 | fixed_size | none | ما طريقة يتم احتساب أجر الساعات الإضافية؟
[1713/3410] Exp 12/22 | bm25 | fixed_size | none | هل مسموح تعيين العمال بصفة مؤقتة طبقاً للائحة المعينين على بند الأجور؟
[1714/3410] Exp 12/22 | bm25 | fixed_size | none | هل يستطيع احتساب أيام المراجعة للمستشفيات داخل مقر العمل أو خارجه إجازة مرضية أو
[1715/3410] Exp 12/22 | bm25 | fixed_size | none | أريد توضيح الحكم النظامي بخصوص: اعرف حقوق العمال؟
[1716/3410] Exp 12/22 | bm25 | fixed_size | none | أريد توضيح الحكم النظامي بخصوص: في حال تم رصد مخالفات في ملف الأجور، أين أجد تفا
[1717/3410] Exp 12/22 | bm25 | fixed_size | none | أريد توضيح الحكم النظامي بخصوص: ما المقصود من كون عمال المستشفيات ضمن المساعدين
[1718/3410] Exp 12/22 | bm25 | fixed_size | none | أريد توضيح الحكم النظامي بخصوص: موظف قدم للرياض للالتحاق بدورة تدريبية وبعد انته
[1719/3410] Exp 12/22 | bm25 | fixed_size | none | أريد معرفة ما إذا كان يخصم بدل المواصلات من راتب الإجازة السنوية؟
[1720/3410] Exp 12/22 | bm25 | fixed_size | none | أريد توضيح الحكم النظامي بخصوص: موظف استقال من وظيفة بالمرتبة الرابعة ومن ثم عاد
[1721/3410] Exp 12/22 | bm25 | fixed_size | none | أريد معرفة عقد العمل؟
[1722/3410] Exp 12/22 | bm25 | fixed_size | none | أريد معرفة ما إذا كان تحسم رواتب العطل الرسمية والأعياد إذا سبقها غياب ولحقها غي
[1723/3410] Exp 12/22 | bm25 | fixed_size | none | أريد معرفة العمل المرن؟
[1724/3410] Exp 12/22 | bm25 | fixed_size | none | أريد توضيح الحكم النظامي بخصوص: ما مدى جواز منح الموظف المنقول بترقية الدرجة الإ
[1725/3410] Exp 12/22 | bm25 | fixed_size | none | أريد توضيح الحكم النظامي بخصوص: في حالة غياب الموظف عن العمل وإيقاع عقوبة تأديبي
[1726/3410] Exp 12/22 | bm25 | fixed_size | none | ما طريقة يتم طلب المدرب الاختياري قبل التقدم بطلب شهادة "مواءمة"؟
[1727/3410] Exp 12/22 | bm25 | fixed_size | none | هل مسموح نظاماً للعامل الانتقال من منشأة في النطاق الأحمر بدون إذن صاحب العمل إل
[1728/3410] Exp 12/22 | bm25 | fixed_size | none | أريد توضيح الحكم النظامي بخصوص: ما مدى امكانية ابتعاث أوايفاد العامل المعين على
[1729/3410] Exp 12/22 | bm25 | fixed_size | none | هل مسموح منح الموظف أثناء فترة التجربة إجازة استثنائية؟
[1730/3410] Exp 12/22 | bm25 | fixed_size | none | أريد توضيح الحكم النظامي بخصوص: ما مدى إلزام الموظف بالعمل خارج وقت الدوام، وهل
[1731/3410] Exp 12/22 | bm25 | fixed_size | none | أريد توضيح الحكم النظامي بخصوص: ما مدى انطباق المزايا المالية التي تصرف للمشاركي
[1732/3410] Exp 12/22 | bm25 | fixed_size | none | أريد معرفة ما إذا كان أستطيع رفع ملفات حماية الأجور عبر موقع وزارة الموارد البشر
[1733/3410] Exp 12/22 | bm25 | fixed_size | none | أريد معرفة الرسوم المطلوبة من المنشآت في برنامج "مواءمة"؟
[1734/3410] Exp 12/22 | bm25 | fixed_size | none | أريد معرفة ما إذا كان يتم إضافة البيانات التي تملكها الوزارة في الأصل للحقول الم
[1735/3410] Exp 12/22 | bm25 | fixed_size | none | أريد توضيح الحكم النظامي بخصوص: ماهي الحقوق والواجبات العامة للمرأة العاملة؟
[1736/3410] Exp 12/22 | bm25 | fixed_size | none | أريد معرفة خدمة نقل الموظفين؟
[1737/3410] Exp 12/22 | bm25 | fixed_size | none | أريد معرفة ما إذا كان ينطبق الشرط الجزائي على العامل أو صاحب العمل؟
[1738/3410] Exp 12/22 | bm25 | fixed_size | none | أريد معرفة شروط الخدمة؟
[1739/3410] Exp 12/22 | bm25 | fixed_size | none | أريد معرفة خدمات مبادرة تحسين العلاقة التعاقدية؟
[1740/3410] Exp 12/22 | bm25 | fixed_size | none | أريد توضيح الحكم النظامي بخصوص: إذا التحق الموظف بالتدريب أثناء إجازته الاستثنائ
[1741/3410] Exp 12/22 | bm25 | fixed_size | none | أريد معرفة ما إذا كان بإمكاني تعيين أي موظف لدي وإعطاءه صلاحية مفوض رواتب أو مدق
[1742/3410] Exp 12/22 | bm25 | fixed_size | none | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف المتدرب الذي انقطع أثناء ف
[1743/3410] Exp 12/22 | bm25 | fixed_size | none | أريد معرفة ما إذا كان يطالب المستخدم المثبت على وظيفة مشمولة بسلم رواتب الموظفين
[1744/3410] Exp 12/22 | bm25 | fixed_size | none | ما طريقة أعرف ما إذا كانت منشأتي ملزمة بتطبيق برنامج حماية الأجور؟
[1745/3410] Exp 12/22 | bm25 | fixed_size | none | أريد معرفة برنامج نطاقات؟ وكيف يحسن بيئة العمل للسعوديين؟
[1746/3410] Exp 12/22 | bm25 | fixed_size | none | أريد توضيح الحكم النظامي بخصوص: لماذا توجد رسوم مالية على برنامج "مواءمة"؟ وهل ت
[1747/3410] Exp 12/22 | bm25 | fixed_size | none | هل مسموح نقل العامل المعين على بند الأجور إلى إحدى الجهات الحكومية مع الاحتفاظ ب
[1748/3410] Exp 12/22 | bm25 | fixed_size | none | أريد معرفة ما إذا كان يحسب برنامج نطاقات من لديهم وظائف رسمية في الحكومة ودوام ج
[1749/3410] Exp 12/22 | bm25 | fixed_size | none | أريد توضيح الحكم النظامي بخصوص: ماهي آلية الترشيح للمرشحين؟

[1750/3410] Exp 12/22 | bm25 | fixed_size | none | ما طريقة يمكن للمستفيد (المؤمن له) معرفة اسم شركة التأمين التابع لها؟
Checkpoint saved: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\retrieval_evaluation_detailed_results_checkpoint.csv
[1751/3410] Exp 12/22 | bm25 | fixed_size | none | أريد معرفة إجراءات الانتقال خلال السنة الأولى في الحالات الاستثنائية؟
[1752/3410] Exp 12/22 | bm25 | fixed_size | none | أريد معرفة ما إذا كان تمكن البوابة والانظمة التابعة لها المستخدم من تخصيص الخدما
[1753/3410] Exp 12/22 | bm25 | fixed_size | none | أريد معرفة ما إذا كان بإمكان أي موظف في منشأتي أن يسجل في منصة مُدد ويقوم برفع م
[1754/3410] Exp 12/22 | bm25 | fixed_size | none | أريد توضيح الحكم النظامي بخصوص: ما مدى أحقية المعين على بند الأجور المكلف بالعمل
[1755/3410] Exp 12/22 | bm25 | fixed_size | none | أريد معرفة ما إذا كان تسري على شاغلي الوظائف المؤقتة القواعد الواردة في نظام الخ
[1756/3410] Exp 12/22 | bm25 | fixed_size | none | أريد توضيح الحكم النظامي بخصوص: كتابة العقد؟
[1757/3410] Exp 12/22 | bm25 | fixed_size | none | أريد معرفة ما إذا كان يترتب على العامل الوافد دفع أي رسوم حكومية (رخصة العمل – ا
[1758/3410] Exp 12/22 | bm25 | fixed_size | none | أريد توضيح الحكم النظامي بخصوص: موظف منح إجازة عادية تنتهي مع ابتداء عطلة أحد ال
[1759/3410] Exp 12/22 | bm25 | fixed_size | none | هل يستطيع للمستخدمين الوصول إلى قائمة عملياته او معاملاته السابقة في البوابة؟
[1760/3410] Exp 12/22 | bm25 | fixed_size | none | أريد توضيح الحكم النظامي بخصوص: ماهي خدمة الخروج النهائي؟
[1761/3410] Exp 12/22 | bm25 | fixed_size | none | أريد توضيح الحكم النظامي بخصوص: ما الفرق بين المهنة والمسمى الوظيفي؟
[1762/3410] Exp 12/22 | bm25 | fixed_size | none | ما طريقة يمكن التوفيق بين نصي المادتين (132) و (147) من اللائحة التنفيذية للموار
[1763/3410] Exp 12/22 | bm25 | fixed_size | none | هل يستطيع أن يتغير انطاق المنشأة دون تغيير في عدد العمالة خلال السنوات القادمة؟
[1764/3410] Exp 12/22 | bm25 | fixed_size | none | أريد توضيح الحكم النظامي بخصوص: لماذا يتوجب على المنشأة القيام بالتقيّيم الذاتي؟
[1765/3410] Exp 12/22 | bm25 | fixed_size | none | هل مسموح انهاء عقد العمل بسبب إعادة الهيكلة أو الظروف المالية للمنشأة؟
[1766/3410] Exp 12/22 | bm25 | fixed_size | none | أريد معرفة ما إذا كان تشمل إجازة أداء الامتحان الدراسي من يؤدي الامتحان خارج الم
[1767/3410] Exp 12/22 | bm25 | fixed_size | none | أريد توضيح الحكم النظامي بخصوص: موظف قررت الهيئة الطبية العامة معالجته في الداخل
[1768/3410] Exp 12/22 | bm25 | fixed_size | none | أريد معرفة ما إذا كان الخدمة تتيح تحديث بيانات العامل؟
[1769/3410] Exp 12/22 | bm25 | fixed_size | none | أريد توضيح الحكم النظامي بخصوص: ماهي الآلية لرفع نسب نطاقات تدريجيا؟ وكم هي المد
[1770/3410] Exp 12/22 | bm25 | fixed_size | none | هل يستطيع حفظ معاملة لخدمة معينة تم بدؤها من خلال البوابة والوصول إليها لاحقًا؟
[1771/3410] Exp 12/22 | bm25 | fixed_size | none | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية احتفاظ العامل المعين على بند الأج
[1772/3410] Exp 12/22 | bm25 | fixed_size | none | أريد توضيح الحكم النظامي بخصوص: موظف فصل من الخدمة بناءً على حكم نهائي من ديوان
[1773/3410] Exp 12/22 | bm25 | fixed_size | none | أريد معرفة ما إذا كان يشمل برنامج نطاقات المستثمر الأجنبي؟
[1774/3410] Exp 12/22 | bm25 | fixed_size | none | أريد توضيح الحكم النظامي بخصوص: الفئات المشمولة بقرار الالزام بالتأمين على عقد ا
[1775/3410] Exp 12/22 | bm25 | fixed_size | none | هل يستطيع تفعيل بند التنافسية في عقد العمل؟
[1776/3410] Exp 12/22 | bm25 | fixed_size | none | أريد توضيح الحكم النظامي بخصوص: ماهي الإجازات المستحقة للمرأة العاملة؟
[1777/3410] Exp 12/22 | bm25 | fixed_size | none | أريد معرفة الاجراء الذي سيتم تطبيقه في حال عدم التزام المنشأة بنسب نطاقات؟
[1778/3410] Exp 12/22 | bm25 | fixed_size | none | أريد توضيح الحكم النظامي بخصوص: ما مدى جواز إجبار الموظف على التمتع بإجازاته الع
[1779/3410] Exp 12/22 | bm25 | fixed_size | none | أريد معرفة الخدمات المقدمة في نظام مُدد لإدارة الرواتب؟
[1780/3410] Exp 12/22 | bm25 | fixed_size | none | أريد معرفة ما إذا كان تمكن البوابة والانظمة التابعة لها المستخدم من تعديل بيانات
[1781/3410] Exp 12/22 | bm25 | fixed_size | none | أريد معرفة المقصود بنصف صافي راتب الموظف مكفوف اليد ومن في حكمه وفقاً للمادة (19
[1782/3410] Exp 12/22 | bm25 | fixed_size | none | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف المنتدب من خارج المملكة إل
[1783/3410] Exp 12/22 | bm25 | fixed_size | none | ما طريقة أقدم شكوى على أحد الموظفين في مكاتب العمل؟ وما الحل إذا لم تتم الإفادة
[1784/3410] Exp 12/22 | bm25 | fixed_size | none | أريد توضيح الحكم النظامي بخصوص: ماهي آلية احتساب نسب التوطين بعد تطبيق نطاقات ال
[1785/3410] Exp 12/22 | bm25 | fixed_size | none | أريد توضيح الحكم النظامي بخصوص: مدة عمل عقد العامل السعودي؟
[1786/3410] Exp 12/22 | bm25 | fixed_size | none | ما طريقة يعامل العامل غير السعودي المعين على بند الأجور من حيث بدل النقل بعد صدو
[1787/3410] Exp 12/22 | bm25 | fixed_size | none | أريد توضيح الحكم النظامي بخصوص: ما خطوات تنفيذ الخدمة؟
[1788/3410] Exp 12/22 | bm25 | fixed_size | none | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية صرف بدل التفرغ للطبيبات خلال إجاز
[1789/3410] Exp 12/22 | bm25 | fixed_size | none | أريد معرفة ما إذا كان تسري أحكام لائحة المعينين على بند الأجور الصادرة بقرار مجل
[1790/3410] Exp 12/22 | bm25 | fixed_size | none | أريد معرفة ما إذا كان الخدمة متاحة للعامل؟
[1791/3410] Exp 12/22 | bm25 | fixed_size | none | أريد توضيح الحكم النظامي بخصوص: ما مدى صرف بدل تعيين لمن يتم تعيينه بوظيفة خاضعة

[1792/3410] Exp 12/22 | bm25 | fixed_size | none | أريد توضيح الحكم النظامي بخصوص: ماذا يقصد ببرنامج نطاقات المطور؟
[1793/3410] Exp 12/22 | bm25 | fixed_size | none | أريد معرفة ما إذا كان يجب ان يكون العامل مسجل على منشاة؟
[1794/3410] Exp 12/22 | bm25 | fixed_size | none | أريد توضيح الحكم النظامي بخصوص: ما مدى نظامية منح الموظف بعد تعيينه وفقاً لنظام
[1795/3410] Exp 12/22 | bm25 | fixed_size | none | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية صرف بدل الترحيل المنصوص عليه بالم
[1796/3410] Exp 12/22 | bm25 | fixed_size | none | أريد توضيح الحكم النظامي بخصوص: ما مدى استفادة العامل المعين على بند الأجور من م
[1797/3410] Exp 12/22 | bm25 | fixed_size | none | ما طريقة يمكنني معرفة إذا كنت مؤهل لتوثيق عقدي مع العامل/ة؟
[1798/3410] Exp 12/22 | bm25 | fixed_size | none | أريد معرفة ما إذا كان تحتسب مدة الإجازة الاستثنائية لغرض إكمال مدة السنة المطلوب
[1799/3410] Exp 12/22 | bm25 | fixed_size | none | أريد معرفة نظام إدارة الرواتب؟
[1800/3410] Exp 12/22 | bm25 | fixed_size | none | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف مكفوف اليد للعلاوة الدورية
Checkpoint saved: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\retrieval_evaluation_detailed_results_checkpoint.csv
[1801/3410] Exp 12/22 | bm25 | fixed_size | none | أريد توضيح الحكم النظامي بخصوص: في الاله الحاسبة الخاصة ببرنامج نطاقات المطور هل
[1802/3410] Exp 12/22 | bm25 | fixed_size | none | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية نقل العسكري إلى وظيفة مدنية؟
[1803/3410] Exp 12/22 | bm25 | fixed_size | none | أريد توضيح الحكم النظامي بخصوص: ماهي الحقوق العامة في عقد العمل؟
[1804/3410] Exp 12/22 | bm25 | fixed_size | none | ما طريقة يعامل الموظف المتدرب في الداخل أو الخارج في حالة إصابته بمرض وحصوله على
[1805/3410] Exp 12/22 | bm25 | fixed_size | none | أريد توضيح الحكم النظامي بخصوص: ماهي شروط وضوابط الإجازات للعامل؟
[1806/3410] Exp 12/22 | bm25 | fixed_size | none | أريد توضيح الحكم النظامي بخصوص: ما مدى امكانية صرف مكافأة نهاية الخدمة المنصوص ع
[1807/3410] Exp 12/22 | bm25 | fixed_size | none | في أي حالة ينتهي عقد العمل؟
[1808/3410] Exp 12/22 | bm25 | fixed_size | none | أريد توضيح الحكم النظامي بخصوص: موظف منح إجازة عادية بعد عطلة أحد العيدين مباشرة
[1809/3410] Exp 12/22 | bm25 | fixed_size | none | ما طريقة يمكن تصحيح فرع المنشأة الذي يعمل فيها العامل ونقله إلى الفرع الصحيح؟
[1810/3410] Exp 12/22 | bm25 | fixed_size | none | أريد توضيح الحكم النظامي بخصوص: ماذا يحتوي عقد العمل؟
[1811/3410] Exp 12/22 | bm25 | fixed_size | none | ما طريقة يتم التحقق من استلام العامل للأجر الذي سيتم التنفيذ عليه في عقد العمل ا
[1812/3410] Exp 12/22 | bm25 | fixed_size | none | أريد معرفة عدد أيام الإجازة بحالة زواج العامل؟
[1813/3410] Exp 12/22 | bm25 | fixed_size | none | أريد معرفة الحسابات التي يمكنني تفعيلها للموظفين للتعديل في حساب مدد الخاص بنظام
[1814/3410] Exp 12/22 | bm25 | fixed_size | none | أريد توضيح الحكم النظامي بخصوص: ماهي اشتراطات فترة التجربة؟
[1815/3410] Exp 12/22 | bm25 | fixed_size | none | أريد معرفة ما إذا كان النسخة العربية وغير العربية متطابقة من حيث الخدمات والوظائ
[1816/3410] Exp 12/22 | bm25 | fixed_size | none | ما طريقة يتم الاستفادة من خدمة التنقل الوظيفي للعمال الوافدين بين المنشآت؟
[1817/3410] Exp 12/22 | bm25 | fixed_size | none | أريد معرفة أنواع الشكاوى التي يمكن أن يقدمها الموظف على صاحب العمل؟
[1818/3410] Exp 12/22 | bm25 | fixed_size | none | هل مسموح نظاماً لصاحب العمل تشغيل المرأة العاملة بعد الوضع بمدة أقل من 6 أسابيع؟
[1819/3410] Exp 12/22 | bm25 | fixed_size | none | أريد معرفة ما إذا كان هناك لائحة وقانون يحمي الأطفال من العنف الأسري؟
[1820/3410] Exp 12/22 | bm25 | fixed_size | none | ما طريقةية تعويض العامل المعين على بند الأجور عن رصيده من الاجازات العادية عند ا
[1821/3410] Exp 12/22 | bm25 | fixed_size | none | أريد توضيح الحكم النظامي بخصوص: موظف مددت خدمته لمدة سنتين بعد بلوغه السن النظام
[1822/3410] Exp 12/22 | bm25 | fixed_size | none | هل يستطيع نقل العمالة داخل الكيان الواحد؟
[1823/3410] Exp 12/22 | bm25 | fixed_size | none | أريد معرفة ما إذا كان تغطي الوثيقة النفقات الطبية اللازمة لعلاج العامل المنزلي ب
[1824/3410] Exp 12/22 | bm25 | fixed_size | none | هل يستطيع إلغاء التأشيرة المصدرة من مساند؟
[1825/3410] Exp 12/22 | bm25 | fixed_size | none | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف الذي يشغل وظيفة خاضعة لنظا
[1826/3410] Exp 12/22 | bm25 | fixed_size | none | أريد معرفة ما إذا كان يحسم من راتب الموظف أيام غيابه عن العمل نتيجة مثوله أمام ا
[1827/3410] Exp 12/22 | bm25 | fixed_size | none | أريد توضيح الحكم النظامي بخصوص: موظف بعد احالته على التقاعد لبلوغ السن النظامية
[1828/3410] Exp 12/22 | bm25 | fixed_size | none | هل يستطيع تعديل المهنة بعد تطبيق المبادرة؟
[1829/3410] Exp 12/22 | bm25 | fixed_size | none | أريد معرفة ما إذا كان يستحق الموظف التعويض عن إجازته العادية إذا استقال قبل إكما
[1830/3410] Exp 12/22 | bm25 | fixed_size | none | ما طريقة يمكن الاستفادة من الخدمة؟
[1831/3410] Exp 12/22 | bm25 | fixed_size | none | أريد معرفة فترة الراحة اليومية للرضاعة؟
[1832/3410] Exp 12/22 | bm25 | fixed_size | none | في أي حالة يتاح تجديد رخصة العمل؟
[1833/3410] Exp 12/22 | bm25 | fixed_size | none | ما طريقة يتم حماية حقوق العامل؟
[1834/3410] Exp 12/22 | bm25 | fixed_size | none | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف المتدرب لمكافآت وبدلات الت
[1835/3410] Exp 12/22 | bm25 | fixed_size | none | أريد معرفة ما إذا كان يحسب من عمره أقل من 18 سنة ضمن نسبة التوطين؟
[1836/3410] Exp 12/22 | bm25 | fixed_size | none | أريد معرفة شروط أهلية العامل الوافد للاستفادة من خدمة التنقل الوظيفي؟
[1837/3410] Exp 12/22 | bm25 | fixed_size | none | كم مدة فترة التجربة في نظام العمل السعودي؟
[1838/3410] Exp 12/22 | bm25 | fixed_size | none | هل يجوز وضع العامل تحت التجربة أكثر من مرة لدى نفس صاحب العمل؟
[1839/3410] Exp 12/22 | bm25 | fixed_size | none | ما الحد الأقصى لساعات العمل اليومية في نظام العمل؟

[1840/3410] Exp 12/22 | bm25 | fixed_size | none | ما الحد الأقصى لساعات العمل الأسبوعية؟
[1841/3410] Exp 12/22 | bm25 | fixed_size | none | هل تختلف ساعات العمل في شهر رمضان؟
[1842/3410] Exp 12/22 | bm25 | fixed_size | none | ما مدة الإجازة السنوية المستحقة للعامل؟
[1843/3410] Exp 12/22 | bm25 | fixed_size | none | متى تزيد الإجازة السنوية إلى ثلاثين يومًا؟
[1844/3410] Exp 12/22 | bm25 | fixed_size | none | هل يستحق العامل أجرًا عن أيام الإجازة غير المستخدمة عند انتهاء العمل؟
[1845/3410] Exp 12/22 | bm25 | fixed_size | none | هل يستحق العامل إجازة عند الزواج أو وفاة أحد الأقارب؟
[1846/3410] Exp 12/22 | bm25 | fixed_size | none | هل للعامل الحق في إجازة مرضية؟
[1847/3410] Exp 12/22 | bm25 | fixed_size | none | ما حالات انتهاء عقد العمل؟
[1848/3410] Exp 12/22 | bm25 | fixed_size | none | ما مدة الإشعار عند إنهاء العقد غير محدد المدة؟
[1849/3410] Exp 12/22 | bm25 | fixed_size | none | متى يستحق العامل تعويضًا عند إنهاء العقد لسبب غير مشروع؟
[1850/3410] Exp 12/22 | bm25 | fixed_size | none | متى يجوز لصاحب العمل إنهاء العقد دون مكافأة أو تعويض؟
Checkpoint saved: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\retrieval_evaluation_detailed_results_checkpoint.csv
[1851/3410] Exp 12/22 | bm25 | fixed_size | none | متى يجوز للعامل ترك العمل دون إشعار مع احتفاظه بحقوقه؟
[1852/3410] Exp 12/22 | bm25 | fixed_size | none | متى يستحق العامل مكافأة نهاية الخدمة؟
[1853/3410] Exp 12/22 | bm25 | fixed_size | none | هل يحق لصاحب العمل نقل العامل من مكان عمله الأصلي؟
[1854/3410] Exp 12/22 | bm25 | fixed_size | none | ما المقصود بعقد العمل في نظام العمل؟
[1855/3410] Exp 12/22 | bm25 | fixed_size | none | كيف يتم دفع أجر العامل؟
[1856/3410] Exp 12/22 | bm25 | fixed_size | none | ما واجبات صاحب العمل تجاه العامل؟
[1857/3410] Exp 12/22 | bm25 | fixed_size | none | ما التزامات العامل في نظام العمل؟
[1858/3410] Exp 12/22 | bm25 | fixed_size | none | ما الحد الأقصى لساعات العمل الإضافية وكيف تُحتسب؟
[1859/3410] Exp 12/22 | bm25 | fixed_size | none | ما أحكام السلامة والصحة المهنية في بيئة العمل؟
[1860/3410] Exp 12/22 | bm25 | fixed_size | none | ما حقوق العاملة في إجازة الوضع؟
====================================================================================================
Experiment 13/22: {'chunking_strategy': 'fixed_size', 'embedding_model': 'e5_large', 'retriever': 'dense', 'alpha': None}
====================================================================================================
[1861/3410] Exp 13/22 | dense | fixed_size | e5_large | ما طريقة يمكنني إلغاء أو تعديل طلب تغيير المهنة؟
[1862/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد معرفة الطريقة المتبعة لتسديد قسط التأمين؟
[1863/3410] Exp 13/22 | dense | fixed_size | e5_large | ما طريقةية معاملة محرم الموظفة عند مرافقتها أثناء ابتعاثها للدراسة أو التدريب أو
[1864/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي أهداف برنامج نطاقات المطور؟
[1865/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية الجمع بين بدل المهنة المنصوص عليه
[1866/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: موظف أحيل للتحقيق أثناء إجراء المفاضلة لغرض التر

[1867/3410] Exp 13/22 | dense | fixed_size | e5_large | ما طريقة يتم احتساب أجر الساعات الإضافية؟
[1868/3410] Exp 13/22 | dense | fixed_size | e5_large | هل مسموح تعيين العمال بصفة مؤقتة طبقاً للائحة المعينين على بند الأجور؟
[1869/3410] Exp 13/22 | dense | fixed_size | e5_large | هل يستطيع احتساب أيام المراجعة للمستشفيات داخل مقر العمل أو خارجه إجازة مرضية أو
[1870/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: اعرف حقوق العمال؟
[1871/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: في حال تم رصد مخالفات في ملف الأجور، أين أجد تفا
[1872/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما المقصود من كون عمال المستشفيات ضمن المساعدين
[1873/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: موظف قدم للرياض للالتحاق بدورة تدريبية وبعد انته

[1874/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد معرفة ما إذا كان يخصم بدل المواصلات من راتب الإجازة السنوية؟
[1875/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: موظف استقال من وظيفة بالمرتبة الرابعة ومن ثم عاد
[1876/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد معرفة عقد العمل؟
[1877/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد معرفة ما إذا كان تحسم رواتب العطل الرسمية والأعياد إذا سبقها غياب ولحقها غي
[1878/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد معرفة العمل المرن؟
[1879/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى جواز منح الموظف المنقول بترقية الدرجة الإ
[1880/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: في حالة غياب الموظف عن العمل وإيقاع عقوبة تأديبي

[1881/3410] Exp 13/22 | dense | fixed_size | e5_large | ما طريقة يتم طلب المدرب الاختياري قبل التقدم بطلب شهادة "مواءمة"؟
[1882/3410] Exp 13/22 | dense | fixed_size | e5_large | هل مسموح نظاماً للعامل الانتقال من منشأة في النطاق الأحمر بدون إذن صاحب العمل إل
[1883/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى امكانية ابتعاث أوايفاد العامل المعين على
[1884/3410] Exp 13/22 | dense | fixed_size | e5_large | هل مسموح منح الموظف أثناء فترة التجربة إجازة استثنائية؟
[1885/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى إلزام الموظف بالعمل خارج وقت الدوام، وهل
[1886/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى انطباق المزايا المالية التي تصرف للمشاركي

[1887/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد معرفة ما إذا كان أستطيع رفع ملفات حماية الأجور عبر موقع وزارة الموارد البشر
[1888/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد معرفة الرسوم المطلوبة من المنشآت في برنامج "مواءمة"؟
[1889/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد معرفة ما إذا كان يتم إضافة البيانات التي تملكها الوزارة في الأصل للحقول الم
[1890/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي الحقوق والواجبات العامة للمرأة العاملة؟
[1891/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد معرفة خدمة نقل الموظفين؟
[1892/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد معرفة ما إذا كان ينطبق الشرط الجزائي على العامل أو صاحب العمل؟
[1893/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد معرفة شروط الخدمة؟
[1894/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد معرفة خدمات مبادرة تحسين العلاقة التعاقدية؟
[1895/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: إذا التحق الموظف بالتدريب أثناء إجازته الاستثنائ

[1896/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد معرفة ما إذا كان بإمكاني تعيين أي موظف لدي وإعطاءه صلاحية مفوض رواتب أو مدق
[1897/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف المتدرب الذي انقطع أثناء ف
[1898/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد معرفة ما إذا كان يطالب المستخدم المثبت على وظيفة مشمولة بسلم رواتب الموظفين
[1899/3410] Exp 13/22 | dense | fixed_size | e5_large | ما طريقة أعرف ما إذا كانت منشأتي ملزمة بتطبيق برنامج حماية الأجور؟
[1900/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد معرفة برنامج نطاقات؟ وكيف يحسن بيئة العمل للسعوديين؟
Checkpoint saved: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\retrieval_evaluation_detailed_results_checkpoint.csv
[1901/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: لماذا توجد رسوم مالية على برنامج "مواءمة"؟ وهل ت

[1902/3410] Exp 13/22 | dense | fixed_size | e5_large | هل مسموح نقل العامل المعين على بند الأجور إلى إحدى الجهات الحكومية مع الاحتفاظ ب
[1903/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد معرفة ما إذا كان يحسب برنامج نطاقات من لديهم وظائف رسمية في الحكومة ودوام ج
[1904/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي آلية الترشيح للمرشحين؟
[1905/3410] Exp 13/22 | dense | fixed_size | e5_large | ما طريقة يمكن للمستفيد (المؤمن له) معرفة اسم شركة التأمين التابع لها؟
[1906/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد معرفة إجراءات الانتقال خلال السنة الأولى في الحالات الاستثنائية؟
[1907/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد معرفة ما إذا كان تمكن البوابة والانظمة التابعة لها المستخدم من تخصيص الخدما
[1908/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد معرفة ما إذا كان بإمكان أي موظف في منشأتي أن يسجل في منصة مُدد ويقوم برفع م
[1909/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى أحقية المعين على بند الأجور المكلف بالعمل

[1910/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد معرفة ما إذا كان تسري على شاغلي الوظائف المؤقتة القواعد الواردة في نظام الخ
[1911/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: كتابة العقد؟
[1912/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد معرفة ما إذا كان يترتب على العامل الوافد دفع أي رسوم حكومية (رخصة العمل – ا
[1913/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: موظف منح إجازة عادية تنتهي مع ابتداء عطلة أحد ال
[1914/3410] Exp 13/22 | dense | fixed_size | e5_large | هل يستطيع للمستخدمين الوصول إلى قائمة عملياته او معاملاته السابقة في البوابة؟
[1915/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي خدمة الخروج النهائي؟
[1916/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما الفرق بين المهنة والمسمى الوظيفي؟
[1917/3410] Exp 13/22 | dense | fixed_size | e5_large | ما طريقة يمكن التوفيق بين نصي المادتين (132) و (147) من اللائحة التنفيذية للموار

[1918/3410] Exp 13/22 | dense | fixed_size | e5_large | هل يستطيع أن يتغير انطاق المنشأة دون تغيير في عدد العمالة خلال السنوات القادمة؟
[1919/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: لماذا يتوجب على المنشأة القيام بالتقيّيم الذاتي؟
[1920/3410] Exp 13/22 | dense | fixed_size | e5_large | هل مسموح انهاء عقد العمل بسبب إعادة الهيكلة أو الظروف المالية للمنشأة؟
[1921/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد معرفة ما إذا كان تشمل إجازة أداء الامتحان الدراسي من يؤدي الامتحان خارج الم
[1922/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: موظف قررت الهيئة الطبية العامة معالجته في الداخل
[1923/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد معرفة ما إذا كان الخدمة تتيح تحديث بيانات العامل؟
[1924/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي الآلية لرفع نسب نطاقات تدريجيا؟ وكم هي المد

[1925/3410] Exp 13/22 | dense | fixed_size | e5_large | هل يستطيع حفظ معاملة لخدمة معينة تم بدؤها من خلال البوابة والوصول إليها لاحقًا؟
[1926/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية احتفاظ العامل المعين على بند الأج
[1927/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: موظف فصل من الخدمة بناءً على حكم نهائي من ديوان
[1928/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد معرفة ما إذا كان يشمل برنامج نطاقات المستثمر الأجنبي؟
[1929/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: الفئات المشمولة بقرار الالزام بالتأمين على عقد ا
[1930/3410] Exp 13/22 | dense | fixed_size | e5_large | هل يستطيع تفعيل بند التنافسية في عقد العمل؟
[1931/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي الإجازات المستحقة للمرأة العاملة؟

[1932/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد معرفة الاجراء الذي سيتم تطبيقه في حال عدم التزام المنشأة بنسب نطاقات؟
[1933/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى جواز إجبار الموظف على التمتع بإجازاته الع
[1934/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد معرفة الخدمات المقدمة في نظام مُدد لإدارة الرواتب؟
[1935/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد معرفة ما إذا كان تمكن البوابة والانظمة التابعة لها المستخدم من تعديل بيانات
[1936/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد معرفة المقصود بنصف صافي راتب الموظف مكفوف اليد ومن في حكمه وفقاً للمادة (19
[1937/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف المنتدب من خارج المملكة إل
[1938/3410] Exp 13/22 | dense | fixed_size | e5_large | ما طريقة أقدم شكوى على أحد الموظفين في مكاتب العمل؟ وما الحل إذا لم تتم الإفادة

[1939/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي آلية احتساب نسب التوطين بعد تطبيق نطاقات ال
[1940/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: مدة عمل عقد العامل السعودي؟
[1941/3410] Exp 13/22 | dense | fixed_size | e5_large | ما طريقة يعامل العامل غير السعودي المعين على بند الأجور من حيث بدل النقل بعد صدو
[1942/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما خطوات تنفيذ الخدمة؟
[1943/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية صرف بدل التفرغ للطبيبات خلال إجاز
[1944/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد معرفة ما إذا كان تسري أحكام لائحة المعينين على بند الأجور الصادرة بقرار مجل
[1945/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد معرفة ما إذا كان الخدمة متاحة للعامل؟
[1946/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى صرف بدل تعيين لمن يتم تعيينه بوظيفة خاضعة

[1947/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ماذا يقصد ببرنامج نطاقات المطور؟
[1948/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد معرفة ما إذا كان يجب ان يكون العامل مسجل على منشاة؟
[1949/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى نظامية منح الموظف بعد تعيينه وفقاً لنظام
[1950/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية صرف بدل الترحيل المنصوص عليه بالم
Checkpoint saved: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\retrieval_evaluation_detailed_results_checkpoint.csv
[1951/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى استفادة العامل المعين على بند الأجور من م
[1952/3410] Exp 13/22 | dense | fixed_size | e5_large | ما طريقة يمكنني معرفة إذا كنت مؤهل لتوثيق عقدي مع العامل/ة؟

[1953/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد معرفة ما إذا كان تحتسب مدة الإجازة الاستثنائية لغرض إكمال مدة السنة المطلوب
[1954/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد معرفة نظام إدارة الرواتب؟
[1955/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف مكفوف اليد للعلاوة الدورية
[1956/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: في الاله الحاسبة الخاصة ببرنامج نطاقات المطور هل
[1957/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية نقل العسكري إلى وظيفة مدنية؟
[1958/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي الحقوق العامة في عقد العمل؟
[1959/3410] Exp 13/22 | dense | fixed_size | e5_large | ما طريقة يعامل الموظف المتدرب في الداخل أو الخارج في حالة إصابته بمرض وحصوله على

[1960/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي شروط وضوابط الإجازات للعامل؟
[1961/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى امكانية صرف مكافأة نهاية الخدمة المنصوص ع
[1962/3410] Exp 13/22 | dense | fixed_size | e5_large | في أي حالة ينتهي عقد العمل؟
[1963/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: موظف منح إجازة عادية بعد عطلة أحد العيدين مباشرة
[1964/3410] Exp 13/22 | dense | fixed_size | e5_large | ما طريقة يمكن تصحيح فرع المنشأة الذي يعمل فيها العامل ونقله إلى الفرع الصحيح؟
[1965/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ماذا يحتوي عقد العمل؟
[1966/3410] Exp 13/22 | dense | fixed_size | e5_large | ما طريقة يتم التحقق من استلام العامل للأجر الذي سيتم التنفيذ عليه في عقد العمل ا

[1967/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد معرفة عدد أيام الإجازة بحالة زواج العامل؟
[1968/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد معرفة الحسابات التي يمكنني تفعيلها للموظفين للتعديل في حساب مدد الخاص بنظام
[1969/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي اشتراطات فترة التجربة؟
[1970/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد معرفة ما إذا كان النسخة العربية وغير العربية متطابقة من حيث الخدمات والوظائ
[1971/3410] Exp 13/22 | dense | fixed_size | e5_large | ما طريقة يتم الاستفادة من خدمة التنقل الوظيفي للعمال الوافدين بين المنشآت؟
[1972/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد معرفة أنواع الشكاوى التي يمكن أن يقدمها الموظف على صاحب العمل؟
[1973/3410] Exp 13/22 | dense | fixed_size | e5_large | هل مسموح نظاماً لصاحب العمل تشغيل المرأة العاملة بعد الوضع بمدة أقل من 6 أسابيع؟
[1974/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد معرفة ما إذا كان هناك لائحة وقانون يحمي الأطفال من العنف الأسري؟

[1975/3410] Exp 13/22 | dense | fixed_size | e5_large | ما طريقةية تعويض العامل المعين على بند الأجور عن رصيده من الاجازات العادية عند ا
[1976/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: موظف مددت خدمته لمدة سنتين بعد بلوغه السن النظام
[1977/3410] Exp 13/22 | dense | fixed_size | e5_large | هل يستطيع نقل العمالة داخل الكيان الواحد؟
[1978/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد معرفة ما إذا كان تغطي الوثيقة النفقات الطبية اللازمة لعلاج العامل المنزلي ب
[1979/3410] Exp 13/22 | dense | fixed_size | e5_large | هل يستطيع إلغاء التأشيرة المصدرة من مساند؟
[1980/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف الذي يشغل وظيفة خاضعة لنظا
[1981/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد معرفة ما إذا كان يحسم من راتب الموظف أيام غيابه عن العمل نتيجة مثوله أمام ا

[1982/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: موظف بعد احالته على التقاعد لبلوغ السن النظامية
[1983/3410] Exp 13/22 | dense | fixed_size | e5_large | هل يستطيع تعديل المهنة بعد تطبيق المبادرة؟
[1984/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد معرفة ما إذا كان يستحق الموظف التعويض عن إجازته العادية إذا استقال قبل إكما
[1985/3410] Exp 13/22 | dense | fixed_size | e5_large | ما طريقة يمكن الاستفادة من الخدمة؟
[1986/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد معرفة فترة الراحة اليومية للرضاعة؟
[1987/3410] Exp 13/22 | dense | fixed_size | e5_large | في أي حالة يتاح تجديد رخصة العمل؟
[1988/3410] Exp 13/22 | dense | fixed_size | e5_large | ما طريقة يتم حماية حقوق العامل؟
[1989/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف المتدرب لمكافآت وبدلات الت
[1990/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد معرفة ما إذا كان يحسب من عمره أقل من 18 سنة ضمن نسبة التوطين؟

[1991/3410] Exp 13/22 | dense | fixed_size | e5_large | أريد معرفة شروط أهلية العامل الوافد للاستفادة من خدمة التنقل الوظيفي؟
[1992/3410] Exp 13/22 | dense | fixed_size | e5_large | كم مدة فترة التجربة في نظام العمل السعودي؟
[1993/3410] Exp 13/22 | dense | fixed_size | e5_large | هل يجوز وضع العامل تحت التجربة أكثر من مرة لدى نفس صاحب العمل؟
[1994/3410] Exp 13/22 | dense | fixed_size | e5_large | ما الحد الأقصى لساعات العمل اليومية في نظام العمل؟
[1995/3410] Exp 13/22 | dense | fixed_size | e5_large | ما الحد الأقصى لساعات العمل الأسبوعية؟
[1996/3410] Exp 13/22 | dense | fixed_size | e5_large | هل تختلف ساعات العمل في شهر رمضان؟
[1997/3410] Exp 13/22 | dense | fixed_size | e5_large | ما مدة الإجازة السنوية المستحقة للعامل؟
[1998/3410] Exp 13/22 | dense | fixed_size | e5_large | متى تزيد الإجازة السنوية إلى ثلاثين يومًا؟
[1999/3410] Exp 13/22 | dense | fixed_size | e5_large | هل يستحق العامل أجرًا عن أيام الإجازة غير المستخدمة عند انتهاء العمل؟
[2000/3410] Exp 13/22 | dense | fixed_size | e5_large | هل يستحق العامل إجازة عند الزواج أو وفاة أحد الأقارب؟

Checkpoint saved: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\retrieval_evaluation_detailed_results_checkpoint.csv
[2001/3410] Exp 13/22 | dense | fixed_size | e5_large | هل للعامل الحق في إجازة مرضية؟
[2002/3410] Exp 13/22 | dense | fixed_size | e5_large | ما حالات انتهاء عقد العمل؟
[2003/3410] Exp 13/22 | dense | fixed_size | e5_large | ما مدة الإشعار عند إنهاء العقد غير محدد المدة؟
[2004/3410] Exp 13/22 | dense | fixed_size | e5_large | متى يستحق العامل تعويضًا عند إنهاء العقد لسبب غير مشروع؟
[2005/3410] Exp 13/22 | dense | fixed_size | e5_large | متى يجوز لصاحب العمل إنهاء العقد دون مكافأة أو تعويض؟
[2006/3410] Exp 13/22 | dense | fixed_size | e5_large | متى يجوز للعامل ترك العمل دون إشعار مع احتفاظه بحقوقه؟
[2007/3410] Exp 13/22 | dense | fixed_size | e5_large | متى يستحق العامل مكافأة نهاية الخدمة؟
[2008/3410] Exp 13/22 | dense | fixed_size | e5_large | هل يحق لصاحب العمل نقل العامل من مكان عمله الأصلي؟
[2009/3410] Exp 13/22 | dense | fixed_size | e5_large | ما المقصود بعقد العمل في نظام العمل؟
[2010/3410] Exp 13/22 | dense | fixed_size | e5_large | كيف يتم دفع أجر العامل؟

[2011/3410] Exp 13/22 | dense | fixed_size | e5_large | ما واجبات صاحب العمل تجاه العامل؟
[2012/3410] Exp 13/22 | dense | fixed_size | e5_large | ما التزامات العامل في نظام العمل؟
[2013/3410] Exp 13/22 | dense | fixed_size | e5_large | ما الحد الأقصى لساعات العمل الإضافية وكيف تُحتسب؟
[2014/3410] Exp 13/22 | dense | fixed_size | e5_large | ما أحكام السلامة والصحة المهنية في بيئة العمل؟
[2015/3410] Exp 13/22 | dense | fixed_size | e5_large | ما حقوق العاملة في إجازة الوضع؟
====================================================================================================
Experiment 14/22: {'chunking_strategy': 'fixed_size', 'embedding_model': 'e5_large', 'retriever': 'hybrid', 'alpha': 0.65}
====================================================================================================
[2016/3410] Exp 14/22 | hybrid | fixed_size | e5_large | ما طريقة يمكنني إلغاء أو تعديل طلب تغيير المهنة؟
[2017/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد معرفة الطريقة المتبعة لتسديد قسط التأمين؟
[2018/3410] Exp 14/22 | hybrid | fixed_size | e5_large | ما طريقةية معاملة محرم الموظفة عند مرافقتها أثناء ابتعاثها للدراسة أو التدريب أو

[2019/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي أهداف برنامج نطاقات المطور؟
[2020/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية الجمع بين بدل المهنة المنصوص عليه
[2021/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: موظف أحيل للتحقيق أثناء إجراء المفاضلة لغرض التر
[2022/3410] Exp 14/22 | hybrid | fixed_size | e5_large | ما طريقة يتم احتساب أجر الساعات الإضافية؟
[2023/3410] Exp 14/22 | hybrid | fixed_size | e5_large | هل مسموح تعيين العمال بصفة مؤقتة طبقاً للائحة المعينين على بند الأجور؟

[2024/3410] Exp 14/22 | hybrid | fixed_size | e5_large | هل يستطيع احتساب أيام المراجعة للمستشفيات داخل مقر العمل أو خارجه إجازة مرضية أو
[2025/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: اعرف حقوق العمال؟
[2026/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: في حال تم رصد مخالفات في ملف الأجور، أين أجد تفا
[2027/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما المقصود من كون عمال المستشفيات ضمن المساعدين
[2028/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: موظف قدم للرياض للالتحاق بدورة تدريبية وبعد انته

[2029/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد معرفة ما إذا كان يخصم بدل المواصلات من راتب الإجازة السنوية؟
[2030/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: موظف استقال من وظيفة بالمرتبة الرابعة ومن ثم عاد
[2031/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد معرفة عقد العمل؟
[2032/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد معرفة ما إذا كان تحسم رواتب العطل الرسمية والأعياد إذا سبقها غياب ولحقها غي
[2033/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد معرفة العمل المرن؟
[2034/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى جواز منح الموظف المنقول بترقية الدرجة الإ

[2035/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: في حالة غياب الموظف عن العمل وإيقاع عقوبة تأديبي
[2036/3410] Exp 14/22 | hybrid | fixed_size | e5_large | ما طريقة يتم طلب المدرب الاختياري قبل التقدم بطلب شهادة "مواءمة"؟
[2037/3410] Exp 14/22 | hybrid | fixed_size | e5_large | هل مسموح نظاماً للعامل الانتقال من منشأة في النطاق الأحمر بدون إذن صاحب العمل إل
[2038/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى امكانية ابتعاث أوايفاد العامل المعين على
[2039/3410] Exp 14/22 | hybrid | fixed_size | e5_large | هل مسموح منح الموظف أثناء فترة التجربة إجازة استثنائية؟

[2040/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى إلزام الموظف بالعمل خارج وقت الدوام، وهل
[2041/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى انطباق المزايا المالية التي تصرف للمشاركي
[2042/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد معرفة ما إذا كان أستطيع رفع ملفات حماية الأجور عبر موقع وزارة الموارد البشر
[2043/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد معرفة الرسوم المطلوبة من المنشآت في برنامج "مواءمة"؟
[2044/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد معرفة ما إذا كان يتم إضافة البيانات التي تملكها الوزارة في الأصل للحقول الم

[2045/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي الحقوق والواجبات العامة للمرأة العاملة؟
[2046/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد معرفة خدمة نقل الموظفين؟
[2047/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد معرفة ما إذا كان ينطبق الشرط الجزائي على العامل أو صاحب العمل؟
[2048/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد معرفة شروط الخدمة؟
[2049/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد معرفة خدمات مبادرة تحسين العلاقة التعاقدية؟
[2050/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: إذا التحق الموظف بالتدريب أثناء إجازته الاستثنائ

Checkpoint saved: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\retrieval_evaluation_detailed_results_checkpoint.csv
[2051/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد معرفة ما إذا كان بإمكاني تعيين أي موظف لدي وإعطاءه صلاحية مفوض رواتب أو مدق
[2052/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف المتدرب الذي انقطع أثناء ف
[2053/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد معرفة ما إذا كان يطالب المستخدم المثبت على وظيفة مشمولة بسلم رواتب الموظفين
[2054/3410] Exp 14/22 | hybrid | fixed_size | e5_large | ما طريقة أعرف ما إذا كانت منشأتي ملزمة بتطبيق برنامج حماية الأجور؟
[2055/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد معرفة برنامج نطاقات؟ وكيف يحسن بيئة العمل للسعوديين؟

[2056/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: لماذا توجد رسوم مالية على برنامج "مواءمة"؟ وهل ت
[2057/3410] Exp 14/22 | hybrid | fixed_size | e5_large | هل مسموح نقل العامل المعين على بند الأجور إلى إحدى الجهات الحكومية مع الاحتفاظ ب
[2058/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد معرفة ما إذا كان يحسب برنامج نطاقات من لديهم وظائف رسمية في الحكومة ودوام ج
[2059/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي آلية الترشيح للمرشحين؟
[2060/3410] Exp 14/22 | hybrid | fixed_size | e5_large | ما طريقة يمكن للمستفيد (المؤمن له) معرفة اسم شركة التأمين التابع لها؟
[2061/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد معرفة إجراءات الانتقال خلال السنة الأولى في الحالات الاستثنائية؟

[2062/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد معرفة ما إذا كان تمكن البوابة والانظمة التابعة لها المستخدم من تخصيص الخدما
[2063/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد معرفة ما إذا كان بإمكان أي موظف في منشأتي أن يسجل في منصة مُدد ويقوم برفع م
[2064/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى أحقية المعين على بند الأجور المكلف بالعمل
[2065/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد معرفة ما إذا كان تسري على شاغلي الوظائف المؤقتة القواعد الواردة في نظام الخ
[2066/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: كتابة العقد؟

[2067/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد معرفة ما إذا كان يترتب على العامل الوافد دفع أي رسوم حكومية (رخصة العمل – ا
[2068/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: موظف منح إجازة عادية تنتهي مع ابتداء عطلة أحد ال
[2069/3410] Exp 14/22 | hybrid | fixed_size | e5_large | هل يستطيع للمستخدمين الوصول إلى قائمة عملياته او معاملاته السابقة في البوابة؟
[2070/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي خدمة الخروج النهائي؟
[2071/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما الفرق بين المهنة والمسمى الوظيفي؟
[2072/3410] Exp 14/22 | hybrid | fixed_size | e5_large | ما طريقة يمكن التوفيق بين نصي المادتين (132) و (147) من اللائحة التنفيذية للموار

[2073/3410] Exp 14/22 | hybrid | fixed_size | e5_large | هل يستطيع أن يتغير انطاق المنشأة دون تغيير في عدد العمالة خلال السنوات القادمة؟
[2074/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: لماذا يتوجب على المنشأة القيام بالتقيّيم الذاتي؟
[2075/3410] Exp 14/22 | hybrid | fixed_size | e5_large | هل مسموح انهاء عقد العمل بسبب إعادة الهيكلة أو الظروف المالية للمنشأة؟
[2076/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد معرفة ما إذا كان تشمل إجازة أداء الامتحان الدراسي من يؤدي الامتحان خارج الم
[2077/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: موظف قررت الهيئة الطبية العامة معالجته في الداخل

[2078/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد معرفة ما إذا كان الخدمة تتيح تحديث بيانات العامل؟
[2079/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي الآلية لرفع نسب نطاقات تدريجيا؟ وكم هي المد
[2080/3410] Exp 14/22 | hybrid | fixed_size | e5_large | هل يستطيع حفظ معاملة لخدمة معينة تم بدؤها من خلال البوابة والوصول إليها لاحقًا؟
[2081/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية احتفاظ العامل المعين على بند الأج
[2082/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: موظف فصل من الخدمة بناءً على حكم نهائي من ديوان

[2083/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد معرفة ما إذا كان يشمل برنامج نطاقات المستثمر الأجنبي؟
[2084/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: الفئات المشمولة بقرار الالزام بالتأمين على عقد ا
[2085/3410] Exp 14/22 | hybrid | fixed_size | e5_large | هل يستطيع تفعيل بند التنافسية في عقد العمل؟
[2086/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي الإجازات المستحقة للمرأة العاملة؟
[2087/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد معرفة الاجراء الذي سيتم تطبيقه في حال عدم التزام المنشأة بنسب نطاقات؟
[2088/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى جواز إجبار الموظف على التمتع بإجازاته الع

[2089/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد معرفة الخدمات المقدمة في نظام مُدد لإدارة الرواتب؟
[2090/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد معرفة ما إذا كان تمكن البوابة والانظمة التابعة لها المستخدم من تعديل بيانات
[2091/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد معرفة المقصود بنصف صافي راتب الموظف مكفوف اليد ومن في حكمه وفقاً للمادة (19
[2092/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف المنتدب من خارج المملكة إل
[2093/3410] Exp 14/22 | hybrid | fixed_size | e5_large | ما طريقة أقدم شكوى على أحد الموظفين في مكاتب العمل؟ وما الحل إذا لم تتم الإفادة

[2094/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي آلية احتساب نسب التوطين بعد تطبيق نطاقات ال
[2095/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: مدة عمل عقد العامل السعودي؟
[2096/3410] Exp 14/22 | hybrid | fixed_size | e5_large | ما طريقة يعامل العامل غير السعودي المعين على بند الأجور من حيث بدل النقل بعد صدو
[2097/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما خطوات تنفيذ الخدمة؟
[2098/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية صرف بدل التفرغ للطبيبات خلال إجاز
[2099/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد معرفة ما إذا كان تسري أحكام لائحة المعينين على بند الأجور الصادرة بقرار مجل

[2100/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد معرفة ما إذا كان الخدمة متاحة للعامل؟
Checkpoint saved: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\retrieval_evaluation_detailed_results_checkpoint.csv
[2101/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى صرف بدل تعيين لمن يتم تعيينه بوظيفة خاضعة
[2102/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ماذا يقصد ببرنامج نطاقات المطور؟
[2103/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد معرفة ما إذا كان يجب ان يكون العامل مسجل على منشاة؟
[2104/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى نظامية منح الموظف بعد تعيينه وفقاً لنظام

[2105/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية صرف بدل الترحيل المنصوص عليه بالم
[2106/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى استفادة العامل المعين على بند الأجور من م
[2107/3410] Exp 14/22 | hybrid | fixed_size | e5_large | ما طريقة يمكنني معرفة إذا كنت مؤهل لتوثيق عقدي مع العامل/ة؟
[2108/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد معرفة ما إذا كان تحتسب مدة الإجازة الاستثنائية لغرض إكمال مدة السنة المطلوب
[2109/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد معرفة نظام إدارة الرواتب؟

[2110/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف مكفوف اليد للعلاوة الدورية
[2111/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: في الاله الحاسبة الخاصة ببرنامج نطاقات المطور هل
[2112/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية نقل العسكري إلى وظيفة مدنية؟
[2113/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي الحقوق العامة في عقد العمل؟
[2114/3410] Exp 14/22 | hybrid | fixed_size | e5_large | ما طريقة يعامل الموظف المتدرب في الداخل أو الخارج في حالة إصابته بمرض وحصوله على

[2115/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي شروط وضوابط الإجازات للعامل؟
[2116/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى امكانية صرف مكافأة نهاية الخدمة المنصوص ع
[2117/3410] Exp 14/22 | hybrid | fixed_size | e5_large | في أي حالة ينتهي عقد العمل؟
[2118/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: موظف منح إجازة عادية بعد عطلة أحد العيدين مباشرة
[2119/3410] Exp 14/22 | hybrid | fixed_size | e5_large | ما طريقة يمكن تصحيح فرع المنشأة الذي يعمل فيها العامل ونقله إلى الفرع الصحيح؟

[2120/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ماذا يحتوي عقد العمل؟
[2121/3410] Exp 14/22 | hybrid | fixed_size | e5_large | ما طريقة يتم التحقق من استلام العامل للأجر الذي سيتم التنفيذ عليه في عقد العمل ا
[2122/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد معرفة عدد أيام الإجازة بحالة زواج العامل؟
[2123/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد معرفة الحسابات التي يمكنني تفعيلها للموظفين للتعديل في حساب مدد الخاص بنظام
[2124/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي اشتراطات فترة التجربة؟
[2125/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد معرفة ما إذا كان النسخة العربية وغير العربية متطابقة من حيث الخدمات والوظائ

[2126/3410] Exp 14/22 | hybrid | fixed_size | e5_large | ما طريقة يتم الاستفادة من خدمة التنقل الوظيفي للعمال الوافدين بين المنشآت؟
[2127/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد معرفة أنواع الشكاوى التي يمكن أن يقدمها الموظف على صاحب العمل؟
[2128/3410] Exp 14/22 | hybrid | fixed_size | e5_large | هل مسموح نظاماً لصاحب العمل تشغيل المرأة العاملة بعد الوضع بمدة أقل من 6 أسابيع؟
[2129/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد معرفة ما إذا كان هناك لائحة وقانون يحمي الأطفال من العنف الأسري؟
[2130/3410] Exp 14/22 | hybrid | fixed_size | e5_large | ما طريقةية تعويض العامل المعين على بند الأجور عن رصيده من الاجازات العادية عند ا
[2131/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: موظف مددت خدمته لمدة سنتين بعد بلوغه السن النظام

[2132/3410] Exp 14/22 | hybrid | fixed_size | e5_large | هل يستطيع نقل العمالة داخل الكيان الواحد؟
[2133/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد معرفة ما إذا كان تغطي الوثيقة النفقات الطبية اللازمة لعلاج العامل المنزلي ب
[2134/3410] Exp 14/22 | hybrid | fixed_size | e5_large | هل يستطيع إلغاء التأشيرة المصدرة من مساند؟
[2135/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف الذي يشغل وظيفة خاضعة لنظا
[2136/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد معرفة ما إذا كان يحسم من راتب الموظف أيام غيابه عن العمل نتيجة مثوله أمام ا
[2137/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: موظف بعد احالته على التقاعد لبلوغ السن النظامية

[2138/3410] Exp 14/22 | hybrid | fixed_size | e5_large | هل يستطيع تعديل المهنة بعد تطبيق المبادرة؟
[2139/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد معرفة ما إذا كان يستحق الموظف التعويض عن إجازته العادية إذا استقال قبل إكما
[2140/3410] Exp 14/22 | hybrid | fixed_size | e5_large | ما طريقة يمكن الاستفادة من الخدمة؟
[2141/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد معرفة فترة الراحة اليومية للرضاعة؟
[2142/3410] Exp 14/22 | hybrid | fixed_size | e5_large | في أي حالة يتاح تجديد رخصة العمل؟
[2143/3410] Exp 14/22 | hybrid | fixed_size | e5_large | ما طريقة يتم حماية حقوق العامل؟
[2144/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف المتدرب لمكافآت وبدلات الت
[2145/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد معرفة ما إذا كان يحسب من عمره أقل من 18 سنة ضمن نسبة التوطين؟

[2146/3410] Exp 14/22 | hybrid | fixed_size | e5_large | أريد معرفة شروط أهلية العامل الوافد للاستفادة من خدمة التنقل الوظيفي؟
[2147/3410] Exp 14/22 | hybrid | fixed_size | e5_large | كم مدة فترة التجربة في نظام العمل السعودي؟
[2148/3410] Exp 14/22 | hybrid | fixed_size | e5_large | هل يجوز وضع العامل تحت التجربة أكثر من مرة لدى نفس صاحب العمل؟
[2149/3410] Exp 14/22 | hybrid | fixed_size | e5_large | ما الحد الأقصى لساعات العمل اليومية في نظام العمل؟
[2150/3410] Exp 14/22 | hybrid | fixed_size | e5_large | ما الحد الأقصى لساعات العمل الأسبوعية؟
Checkpoint saved: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\retrieval_evaluation_detailed_results_checkpoint.csv
[2151/3410] Exp 14/22 | hybrid | fixed_size | e5_large | هل تختلف ساعات العمل في شهر رمضان؟
[2152/3410] Exp 14/22 | hybrid | fixed_size | e5_large | ما مدة الإجازة السنوية المستحقة للعامل؟

[2153/3410] Exp 14/22 | hybrid | fixed_size | e5_large | متى تزيد الإجازة السنوية إلى ثلاثين يومًا؟
[2154/3410] Exp 14/22 | hybrid | fixed_size | e5_large | هل يستحق العامل أجرًا عن أيام الإجازة غير المستخدمة عند انتهاء العمل؟
[2155/3410] Exp 14/22 | hybrid | fixed_size | e5_large | هل يستحق العامل إجازة عند الزواج أو وفاة أحد الأقارب؟
[2156/3410] Exp 14/22 | hybrid | fixed_size | e5_large | هل للعامل الحق في إجازة مرضية؟
[2157/3410] Exp 14/22 | hybrid | fixed_size | e5_large | ما حالات انتهاء عقد العمل؟
[2158/3410] Exp 14/22 | hybrid | fixed_size | e5_large | ما مدة الإشعار عند إنهاء العقد غير محدد المدة؟
[2159/3410] Exp 14/22 | hybrid | fixed_size | e5_large | متى يستحق العامل تعويضًا عند إنهاء العقد لسبب غير مشروع؟

[2160/3410] Exp 14/22 | hybrid | fixed_size | e5_large | متى يجوز لصاحب العمل إنهاء العقد دون مكافأة أو تعويض؟
[2161/3410] Exp 14/22 | hybrid | fixed_size | e5_large | متى يجوز للعامل ترك العمل دون إشعار مع احتفاظه بحقوقه؟
[2162/3410] Exp 14/22 | hybrid | fixed_size | e5_large | متى يستحق العامل مكافأة نهاية الخدمة؟
[2163/3410] Exp 14/22 | hybrid | fixed_size | e5_large | هل يحق لصاحب العمل نقل العامل من مكان عمله الأصلي؟
[2164/3410] Exp 14/22 | hybrid | fixed_size | e5_large | ما المقصود بعقد العمل في نظام العمل؟
[2165/3410] Exp 14/22 | hybrid | fixed_size | e5_large | كيف يتم دفع أجر العامل؟
[2166/3410] Exp 14/22 | hybrid | fixed_size | e5_large | ما واجبات صاحب العمل تجاه العامل؟
[2167/3410] Exp 14/22 | hybrid | fixed_size | e5_large | ما التزامات العامل في نظام العمل؟

[2168/3410] Exp 14/22 | hybrid | fixed_size | e5_large | ما الحد الأقصى لساعات العمل الإضافية وكيف تُحتسب؟
[2169/3410] Exp 14/22 | hybrid | fixed_size | e5_large | ما أحكام السلامة والصحة المهنية في بيئة العمل؟
[2170/3410] Exp 14/22 | hybrid | fixed_size | e5_large | ما حقوق العاملة في إجازة الوضع؟
====================================================================================================
Experiment 15/22: {'chunking_strategy': 'fixed_size', 'embedding_model': 'e5_large', 'retriever': 'hybrid', 'alpha': 0.8}
====================================================================================================
[2171/3410] Exp 15/22 | hybrid | fixed_size | e5_large | ما طريقة يمكنني إلغاء أو تعديل طلب تغيير المهنة؟
[2172/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد معرفة الطريقة المتبعة لتسديد قسط التأمين؟
[2173/3410] Exp 15/22 | hybrid | fixed_size | e5_large | ما طريقةية معاملة محرم الموظفة عند مرافقتها أثناء ابتعاثها للدراسة أو التدريب أو
[2174/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي أهداف برنامج نطاقات المطور؟

[2175/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية الجمع بين بدل المهنة المنصوص عليه
[2176/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: موظف أحيل للتحقيق أثناء إجراء المفاضلة لغرض التر
[2177/3410] Exp 15/22 | hybrid | fixed_size | e5_large | ما طريقة يتم احتساب أجر الساعات الإضافية؟
[2178/3410] Exp 15/22 | hybrid | fixed_size | e5_large | هل مسموح تعيين العمال بصفة مؤقتة طبقاً للائحة المعينين على بند الأجور؟
[2179/3410] Exp 15/22 | hybrid | fixed_size | e5_large | هل يستطيع احتساب أيام المراجعة للمستشفيات داخل مقر العمل أو خارجه إجازة مرضية أو

[2180/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: اعرف حقوق العمال؟
[2181/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: في حال تم رصد مخالفات في ملف الأجور، أين أجد تفا
[2182/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما المقصود من كون عمال المستشفيات ضمن المساعدين
[2183/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: موظف قدم للرياض للالتحاق بدورة تدريبية وبعد انته
[2184/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد معرفة ما إذا كان يخصم بدل المواصلات من راتب الإجازة السنوية؟

[2185/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: موظف استقال من وظيفة بالمرتبة الرابعة ومن ثم عاد
[2186/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد معرفة عقد العمل؟
[2187/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد معرفة ما إذا كان تحسم رواتب العطل الرسمية والأعياد إذا سبقها غياب ولحقها غي
[2188/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد معرفة العمل المرن؟
[2189/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى جواز منح الموظف المنقول بترقية الدرجة الإ

[2190/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: في حالة غياب الموظف عن العمل وإيقاع عقوبة تأديبي
[2191/3410] Exp 15/22 | hybrid | fixed_size | e5_large | ما طريقة يتم طلب المدرب الاختياري قبل التقدم بطلب شهادة "مواءمة"؟
[2192/3410] Exp 15/22 | hybrid | fixed_size | e5_large | هل مسموح نظاماً للعامل الانتقال من منشأة في النطاق الأحمر بدون إذن صاحب العمل إل
[2193/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى امكانية ابتعاث أوايفاد العامل المعين على
[2194/3410] Exp 15/22 | hybrid | fixed_size | e5_large | هل مسموح منح الموظف أثناء فترة التجربة إجازة استثنائية؟

[2195/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى إلزام الموظف بالعمل خارج وقت الدوام، وهل
[2196/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى انطباق المزايا المالية التي تصرف للمشاركي
[2197/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد معرفة ما إذا كان أستطيع رفع ملفات حماية الأجور عبر موقع وزارة الموارد البشر
[2198/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد معرفة الرسوم المطلوبة من المنشآت في برنامج "مواءمة"؟
[2199/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد معرفة ما إذا كان يتم إضافة البيانات التي تملكها الوزارة في الأصل للحقول الم

[2200/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي الحقوق والواجبات العامة للمرأة العاملة؟
Checkpoint saved: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\retrieval_evaluation_detailed_results_checkpoint.csv
[2201/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد معرفة خدمة نقل الموظفين؟
[2202/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد معرفة ما إذا كان ينطبق الشرط الجزائي على العامل أو صاحب العمل؟
[2203/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد معرفة شروط الخدمة؟
[2204/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد معرفة خدمات مبادرة تحسين العلاقة التعاقدية؟
[2205/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: إذا التحق الموظف بالتدريب أثناء إجازته الاستثنائ

[2206/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد معرفة ما إذا كان بإمكاني تعيين أي موظف لدي وإعطاءه صلاحية مفوض رواتب أو مدق
[2207/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف المتدرب الذي انقطع أثناء ف
[2208/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد معرفة ما إذا كان يطالب المستخدم المثبت على وظيفة مشمولة بسلم رواتب الموظفين
[2209/3410] Exp 15/22 | hybrid | fixed_size | e5_large | ما طريقة أعرف ما إذا كانت منشأتي ملزمة بتطبيق برنامج حماية الأجور؟
[2210/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد معرفة برنامج نطاقات؟ وكيف يحسن بيئة العمل للسعوديين؟

[2211/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: لماذا توجد رسوم مالية على برنامج "مواءمة"؟ وهل ت
[2212/3410] Exp 15/22 | hybrid | fixed_size | e5_large | هل مسموح نقل العامل المعين على بند الأجور إلى إحدى الجهات الحكومية مع الاحتفاظ ب
[2213/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد معرفة ما إذا كان يحسب برنامج نطاقات من لديهم وظائف رسمية في الحكومة ودوام ج
[2214/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي آلية الترشيح للمرشحين؟
[2215/3410] Exp 15/22 | hybrid | fixed_size | e5_large | ما طريقة يمكن للمستفيد (المؤمن له) معرفة اسم شركة التأمين التابع لها؟
[2216/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد معرفة إجراءات الانتقال خلال السنة الأولى في الحالات الاستثنائية؟

[2217/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد معرفة ما إذا كان تمكن البوابة والانظمة التابعة لها المستخدم من تخصيص الخدما
[2218/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد معرفة ما إذا كان بإمكان أي موظف في منشأتي أن يسجل في منصة مُدد ويقوم برفع م
[2219/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى أحقية المعين على بند الأجور المكلف بالعمل
[2220/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد معرفة ما إذا كان تسري على شاغلي الوظائف المؤقتة القواعد الواردة في نظام الخ
[2221/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: كتابة العقد؟
[2222/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد معرفة ما إذا كان يترتب على العامل الوافد دفع أي رسوم حكومية (رخصة العمل – ا

[2223/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: موظف منح إجازة عادية تنتهي مع ابتداء عطلة أحد ال
[2224/3410] Exp 15/22 | hybrid | fixed_size | e5_large | هل يستطيع للمستخدمين الوصول إلى قائمة عملياته او معاملاته السابقة في البوابة؟
[2225/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي خدمة الخروج النهائي؟
[2226/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما الفرق بين المهنة والمسمى الوظيفي؟
[2227/3410] Exp 15/22 | hybrid | fixed_size | e5_large | ما طريقة يمكن التوفيق بين نصي المادتين (132) و (147) من اللائحة التنفيذية للموار

[2228/3410] Exp 15/22 | hybrid | fixed_size | e5_large | هل يستطيع أن يتغير انطاق المنشأة دون تغيير في عدد العمالة خلال السنوات القادمة؟
[2229/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: لماذا يتوجب على المنشأة القيام بالتقيّيم الذاتي؟
[2230/3410] Exp 15/22 | hybrid | fixed_size | e5_large | هل مسموح انهاء عقد العمل بسبب إعادة الهيكلة أو الظروف المالية للمنشأة؟
[2231/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد معرفة ما إذا كان تشمل إجازة أداء الامتحان الدراسي من يؤدي الامتحان خارج الم
[2232/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: موظف قررت الهيئة الطبية العامة معالجته في الداخل

[2233/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد معرفة ما إذا كان الخدمة تتيح تحديث بيانات العامل؟
[2234/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي الآلية لرفع نسب نطاقات تدريجيا؟ وكم هي المد
[2235/3410] Exp 15/22 | hybrid | fixed_size | e5_large | هل يستطيع حفظ معاملة لخدمة معينة تم بدؤها من خلال البوابة والوصول إليها لاحقًا؟
[2236/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية احتفاظ العامل المعين على بند الأج
[2237/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: موظف فصل من الخدمة بناءً على حكم نهائي من ديوان

[2238/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد معرفة ما إذا كان يشمل برنامج نطاقات المستثمر الأجنبي؟
[2239/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: الفئات المشمولة بقرار الالزام بالتأمين على عقد ا
[2240/3410] Exp 15/22 | hybrid | fixed_size | e5_large | هل يستطيع تفعيل بند التنافسية في عقد العمل؟
[2241/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي الإجازات المستحقة للمرأة العاملة؟
[2242/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد معرفة الاجراء الذي سيتم تطبيقه في حال عدم التزام المنشأة بنسب نطاقات؟
[2243/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى جواز إجبار الموظف على التمتع بإجازاته الع

[2244/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد معرفة الخدمات المقدمة في نظام مُدد لإدارة الرواتب؟
[2245/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد معرفة ما إذا كان تمكن البوابة والانظمة التابعة لها المستخدم من تعديل بيانات
[2246/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد معرفة المقصود بنصف صافي راتب الموظف مكفوف اليد ومن في حكمه وفقاً للمادة (19
[2247/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف المنتدب من خارج المملكة إل
[2248/3410] Exp 15/22 | hybrid | fixed_size | e5_large | ما طريقة أقدم شكوى على أحد الموظفين في مكاتب العمل؟ وما الحل إذا لم تتم الإفادة

[2249/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي آلية احتساب نسب التوطين بعد تطبيق نطاقات ال
[2250/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: مدة عمل عقد العامل السعودي؟
Checkpoint saved: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\retrieval_evaluation_detailed_results_checkpoint.csv
[2251/3410] Exp 15/22 | hybrid | fixed_size | e5_large | ما طريقة يعامل العامل غير السعودي المعين على بند الأجور من حيث بدل النقل بعد صدو
[2252/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما خطوات تنفيذ الخدمة؟
[2253/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية صرف بدل التفرغ للطبيبات خلال إجاز

[2254/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد معرفة ما إذا كان تسري أحكام لائحة المعينين على بند الأجور الصادرة بقرار مجل
[2255/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد معرفة ما إذا كان الخدمة متاحة للعامل؟
[2256/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى صرف بدل تعيين لمن يتم تعيينه بوظيفة خاضعة
[2257/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ماذا يقصد ببرنامج نطاقات المطور؟
[2258/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد معرفة ما إذا كان يجب ان يكون العامل مسجل على منشاة؟
[2259/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى نظامية منح الموظف بعد تعيينه وفقاً لنظام

[2260/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية صرف بدل الترحيل المنصوص عليه بالم
[2261/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى استفادة العامل المعين على بند الأجور من م
[2262/3410] Exp 15/22 | hybrid | fixed_size | e5_large | ما طريقة يمكنني معرفة إذا كنت مؤهل لتوثيق عقدي مع العامل/ة؟
[2263/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد معرفة ما إذا كان تحتسب مدة الإجازة الاستثنائية لغرض إكمال مدة السنة المطلوب
[2264/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد معرفة نظام إدارة الرواتب؟

[2265/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف مكفوف اليد للعلاوة الدورية
[2266/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: في الاله الحاسبة الخاصة ببرنامج نطاقات المطور هل
[2267/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية نقل العسكري إلى وظيفة مدنية؟
[2268/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي الحقوق العامة في عقد العمل؟
[2269/3410] Exp 15/22 | hybrid | fixed_size | e5_large | ما طريقة يعامل الموظف المتدرب في الداخل أو الخارج في حالة إصابته بمرض وحصوله على
[2270/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي شروط وضوابط الإجازات للعامل؟

[2271/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى امكانية صرف مكافأة نهاية الخدمة المنصوص ع
[2272/3410] Exp 15/22 | hybrid | fixed_size | e5_large | في أي حالة ينتهي عقد العمل؟
[2273/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: موظف منح إجازة عادية بعد عطلة أحد العيدين مباشرة
[2274/3410] Exp 15/22 | hybrid | fixed_size | e5_large | ما طريقة يمكن تصحيح فرع المنشأة الذي يعمل فيها العامل ونقله إلى الفرع الصحيح؟
[2275/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ماذا يحتوي عقد العمل؟

[2276/3410] Exp 15/22 | hybrid | fixed_size | e5_large | ما طريقة يتم التحقق من استلام العامل للأجر الذي سيتم التنفيذ عليه في عقد العمل ا
[2277/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد معرفة عدد أيام الإجازة بحالة زواج العامل؟
[2278/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد معرفة الحسابات التي يمكنني تفعيلها للموظفين للتعديل في حساب مدد الخاص بنظام
[2279/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي اشتراطات فترة التجربة؟
[2280/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد معرفة ما إذا كان النسخة العربية وغير العربية متطابقة من حيث الخدمات والوظائ

[2281/3410] Exp 15/22 | hybrid | fixed_size | e5_large | ما طريقة يتم الاستفادة من خدمة التنقل الوظيفي للعمال الوافدين بين المنشآت؟
[2282/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد معرفة أنواع الشكاوى التي يمكن أن يقدمها الموظف على صاحب العمل؟
[2283/3410] Exp 15/22 | hybrid | fixed_size | e5_large | هل مسموح نظاماً لصاحب العمل تشغيل المرأة العاملة بعد الوضع بمدة أقل من 6 أسابيع؟
[2284/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد معرفة ما إذا كان هناك لائحة وقانون يحمي الأطفال من العنف الأسري؟
[2285/3410] Exp 15/22 | hybrid | fixed_size | e5_large | ما طريقةية تعويض العامل المعين على بند الأجور عن رصيده من الاجازات العادية عند ا
[2286/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: موظف مددت خدمته لمدة سنتين بعد بلوغه السن النظام

[2287/3410] Exp 15/22 | hybrid | fixed_size | e5_large | هل يستطيع نقل العمالة داخل الكيان الواحد؟
[2288/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد معرفة ما إذا كان تغطي الوثيقة النفقات الطبية اللازمة لعلاج العامل المنزلي ب
[2289/3410] Exp 15/22 | hybrid | fixed_size | e5_large | هل يستطيع إلغاء التأشيرة المصدرة من مساند؟
[2290/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف الذي يشغل وظيفة خاضعة لنظا
[2291/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد معرفة ما إذا كان يحسم من راتب الموظف أيام غيابه عن العمل نتيجة مثوله أمام ا
[2292/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: موظف بعد احالته على التقاعد لبلوغ السن النظامية

[2293/3410] Exp 15/22 | hybrid | fixed_size | e5_large | هل يستطيع تعديل المهنة بعد تطبيق المبادرة؟
[2294/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد معرفة ما إذا كان يستحق الموظف التعويض عن إجازته العادية إذا استقال قبل إكما
[2295/3410] Exp 15/22 | hybrid | fixed_size | e5_large | ما طريقة يمكن الاستفادة من الخدمة؟
[2296/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد معرفة فترة الراحة اليومية للرضاعة؟
[2297/3410] Exp 15/22 | hybrid | fixed_size | e5_large | في أي حالة يتاح تجديد رخصة العمل؟
[2298/3410] Exp 15/22 | hybrid | fixed_size | e5_large | ما طريقة يتم حماية حقوق العامل؟
[2299/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف المتدرب لمكافآت وبدلات الت
[2300/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد معرفة ما إذا كان يحسب من عمره أقل من 18 سنة ضمن نسبة التوطين؟

Checkpoint saved: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\retrieval_evaluation_detailed_results_checkpoint.csv
[2301/3410] Exp 15/22 | hybrid | fixed_size | e5_large | أريد معرفة شروط أهلية العامل الوافد للاستفادة من خدمة التنقل الوظيفي؟
[2302/3410] Exp 15/22 | hybrid | fixed_size | e5_large | كم مدة فترة التجربة في نظام العمل السعودي؟
[2303/3410] Exp 15/22 | hybrid | fixed_size | e5_large | هل يجوز وضع العامل تحت التجربة أكثر من مرة لدى نفس صاحب العمل؟
[2304/3410] Exp 15/22 | hybrid | fixed_size | e5_large | ما الحد الأقصى لساعات العمل اليومية في نظام العمل؟
[2305/3410] Exp 15/22 | hybrid | fixed_size | e5_large | ما الحد الأقصى لساعات العمل الأسبوعية؟
[2306/3410] Exp 15/22 | hybrid | fixed_size | e5_large | هل تختلف ساعات العمل في شهر رمضان؟
[2307/3410] Exp 15/22 | hybrid | fixed_size | e5_large | ما مدة الإجازة السنوية المستحقة للعامل؟

[2308/3410] Exp 15/22 | hybrid | fixed_size | e5_large | متى تزيد الإجازة السنوية إلى ثلاثين يومًا؟
[2309/3410] Exp 15/22 | hybrid | fixed_size | e5_large | هل يستحق العامل أجرًا عن أيام الإجازة غير المستخدمة عند انتهاء العمل؟
[2310/3410] Exp 15/22 | hybrid | fixed_size | e5_large | هل يستحق العامل إجازة عند الزواج أو وفاة أحد الأقارب؟
[2311/3410] Exp 15/22 | hybrid | fixed_size | e5_large | هل للعامل الحق في إجازة مرضية؟
[2312/3410] Exp 15/22 | hybrid | fixed_size | e5_large | ما حالات انتهاء عقد العمل؟
[2313/3410] Exp 15/22 | hybrid | fixed_size | e5_large | ما مدة الإشعار عند إنهاء العقد غير محدد المدة؟
[2314/3410] Exp 15/22 | hybrid | fixed_size | e5_large | متى يستحق العامل تعويضًا عند إنهاء العقد لسبب غير مشروع؟

[2315/3410] Exp 15/22 | hybrid | fixed_size | e5_large | متى يجوز لصاحب العمل إنهاء العقد دون مكافأة أو تعويض؟
[2316/3410] Exp 15/22 | hybrid | fixed_size | e5_large | متى يجوز للعامل ترك العمل دون إشعار مع احتفاظه بحقوقه؟
[2317/3410] Exp 15/22 | hybrid | fixed_size | e5_large | متى يستحق العامل مكافأة نهاية الخدمة؟
[2318/3410] Exp 15/22 | hybrid | fixed_size | e5_large | هل يحق لصاحب العمل نقل العامل من مكان عمله الأصلي؟
[2319/3410] Exp 15/22 | hybrid | fixed_size | e5_large | ما المقصود بعقد العمل في نظام العمل؟
[2320/3410] Exp 15/22 | hybrid | fixed_size | e5_large | كيف يتم دفع أجر العامل؟
[2321/3410] Exp 15/22 | hybrid | fixed_size | e5_large | ما واجبات صاحب العمل تجاه العامل؟
[2322/3410] Exp 15/22 | hybrid | fixed_size | e5_large | ما التزامات العامل في نظام العمل؟

[2323/3410] Exp 15/22 | hybrid | fixed_size | e5_large | ما الحد الأقصى لساعات العمل الإضافية وكيف تُحتسب؟
[2324/3410] Exp 15/22 | hybrid | fixed_size | e5_large | ما أحكام السلامة والصحة المهنية في بيئة العمل؟
[2325/3410] Exp 15/22 | hybrid | fixed_size | e5_large | ما حقوق العاملة في إجازة الوضع؟
====================================================================================================
Experiment 16/22: {'chunking_strategy': 'fixed_size', 'embedding_model': 'e5_large', 'retriever': 'hybrid', 'alpha': 0.9}
====================================================================================================
[2326/3410] Exp 16/22 | hybrid | fixed_size | e5_large | ما طريقة يمكنني إلغاء أو تعديل طلب تغيير المهنة؟
[2327/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد معرفة الطريقة المتبعة لتسديد قسط التأمين؟
[2328/3410] Exp 16/22 | hybrid | fixed_size | e5_large | ما طريقةية معاملة محرم الموظفة عند مرافقتها أثناء ابتعاثها للدراسة أو التدريب أو
[2329/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي أهداف برنامج نطاقات المطور؟

[2330/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية الجمع بين بدل المهنة المنصوص عليه
[2331/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: موظف أحيل للتحقيق أثناء إجراء المفاضلة لغرض التر
[2332/3410] Exp 16/22 | hybrid | fixed_size | e5_large | ما طريقة يتم احتساب أجر الساعات الإضافية؟
[2333/3410] Exp 16/22 | hybrid | fixed_size | e5_large | هل مسموح تعيين العمال بصفة مؤقتة طبقاً للائحة المعينين على بند الأجور؟
[2334/3410] Exp 16/22 | hybrid | fixed_size | e5_large | هل يستطيع احتساب أيام المراجعة للمستشفيات داخل مقر العمل أو خارجه إجازة مرضية أو

[2335/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: اعرف حقوق العمال؟
[2336/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: في حال تم رصد مخالفات في ملف الأجور، أين أجد تفا
[2337/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما المقصود من كون عمال المستشفيات ضمن المساعدين
[2338/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: موظف قدم للرياض للالتحاق بدورة تدريبية وبعد انته
[2339/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد معرفة ما إذا كان يخصم بدل المواصلات من راتب الإجازة السنوية؟

[2340/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: موظف استقال من وظيفة بالمرتبة الرابعة ومن ثم عاد
[2341/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد معرفة عقد العمل؟
[2342/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد معرفة ما إذا كان تحسم رواتب العطل الرسمية والأعياد إذا سبقها غياب ولحقها غي
[2343/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد معرفة العمل المرن؟
[2344/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى جواز منح الموظف المنقول بترقية الدرجة الإ

[2345/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: في حالة غياب الموظف عن العمل وإيقاع عقوبة تأديبي
[2346/3410] Exp 16/22 | hybrid | fixed_size | e5_large | ما طريقة يتم طلب المدرب الاختياري قبل التقدم بطلب شهادة "مواءمة"؟
[2347/3410] Exp 16/22 | hybrid | fixed_size | e5_large | هل مسموح نظاماً للعامل الانتقال من منشأة في النطاق الأحمر بدون إذن صاحب العمل إل
[2348/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى امكانية ابتعاث أوايفاد العامل المعين على
[2349/3410] Exp 16/22 | hybrid | fixed_size | e5_large | هل مسموح منح الموظف أثناء فترة التجربة إجازة استثنائية؟

[2350/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى إلزام الموظف بالعمل خارج وقت الدوام، وهل
Checkpoint saved: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\retrieval_evaluation_detailed_results_checkpoint.csv
[2351/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى انطباق المزايا المالية التي تصرف للمشاركي
[2352/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد معرفة ما إذا كان أستطيع رفع ملفات حماية الأجور عبر موقع وزارة الموارد البشر
[2353/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد معرفة الرسوم المطلوبة من المنشآت في برنامج "مواءمة"؟
[2354/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد معرفة ما إذا كان يتم إضافة البيانات التي تملكها الوزارة في الأصل للحقول الم

[2355/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي الحقوق والواجبات العامة للمرأة العاملة؟
[2356/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد معرفة خدمة نقل الموظفين؟
[2357/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد معرفة ما إذا كان ينطبق الشرط الجزائي على العامل أو صاحب العمل؟
[2358/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد معرفة شروط الخدمة؟
[2359/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد معرفة خدمات مبادرة تحسين العلاقة التعاقدية؟
[2360/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: إذا التحق الموظف بالتدريب أثناء إجازته الاستثنائ
[2361/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد معرفة ما إذا كان بإمكاني تعيين أي موظف لدي وإعطاءه صلاحية مفوض رواتب أو مدق

[2362/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف المتدرب الذي انقطع أثناء ف
[2363/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد معرفة ما إذا كان يطالب المستخدم المثبت على وظيفة مشمولة بسلم رواتب الموظفين
[2364/3410] Exp 16/22 | hybrid | fixed_size | e5_large | ما طريقة أعرف ما إذا كانت منشأتي ملزمة بتطبيق برنامج حماية الأجور؟
[2365/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد معرفة برنامج نطاقات؟ وكيف يحسن بيئة العمل للسعوديين؟
[2366/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: لماذا توجد رسوم مالية على برنامج "مواءمة"؟ وهل ت

[2367/3410] Exp 16/22 | hybrid | fixed_size | e5_large | هل مسموح نقل العامل المعين على بند الأجور إلى إحدى الجهات الحكومية مع الاحتفاظ ب
[2368/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد معرفة ما إذا كان يحسب برنامج نطاقات من لديهم وظائف رسمية في الحكومة ودوام ج
[2369/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي آلية الترشيح للمرشحين؟
[2370/3410] Exp 16/22 | hybrid | fixed_size | e5_large | ما طريقة يمكن للمستفيد (المؤمن له) معرفة اسم شركة التأمين التابع لها؟
[2371/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد معرفة إجراءات الانتقال خلال السنة الأولى في الحالات الاستثنائية؟
[2372/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد معرفة ما إذا كان تمكن البوابة والانظمة التابعة لها المستخدم من تخصيص الخدما

[2373/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد معرفة ما إذا كان بإمكان أي موظف في منشأتي أن يسجل في منصة مُدد ويقوم برفع م
[2374/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى أحقية المعين على بند الأجور المكلف بالعمل
[2375/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد معرفة ما إذا كان تسري على شاغلي الوظائف المؤقتة القواعد الواردة في نظام الخ
[2376/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: كتابة العقد؟
[2377/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد معرفة ما إذا كان يترتب على العامل الوافد دفع أي رسوم حكومية (رخصة العمل – ا

[2378/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: موظف منح إجازة عادية تنتهي مع ابتداء عطلة أحد ال
[2379/3410] Exp 16/22 | hybrid | fixed_size | e5_large | هل يستطيع للمستخدمين الوصول إلى قائمة عملياته او معاملاته السابقة في البوابة؟
[2380/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي خدمة الخروج النهائي؟
[2381/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما الفرق بين المهنة والمسمى الوظيفي؟
[2382/3410] Exp 16/22 | hybrid | fixed_size | e5_large | ما طريقة يمكن التوفيق بين نصي المادتين (132) و (147) من اللائحة التنفيذية للموار

[2383/3410] Exp 16/22 | hybrid | fixed_size | e5_large | هل يستطيع أن يتغير انطاق المنشأة دون تغيير في عدد العمالة خلال السنوات القادمة؟
[2384/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: لماذا يتوجب على المنشأة القيام بالتقيّيم الذاتي؟
[2385/3410] Exp 16/22 | hybrid | fixed_size | e5_large | هل مسموح انهاء عقد العمل بسبب إعادة الهيكلة أو الظروف المالية للمنشأة؟
[2386/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد معرفة ما إذا كان تشمل إجازة أداء الامتحان الدراسي من يؤدي الامتحان خارج الم
[2387/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: موظف قررت الهيئة الطبية العامة معالجته في الداخل

[2388/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد معرفة ما إذا كان الخدمة تتيح تحديث بيانات العامل؟
[2389/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي الآلية لرفع نسب نطاقات تدريجيا؟ وكم هي المد
[2390/3410] Exp 16/22 | hybrid | fixed_size | e5_large | هل يستطيع حفظ معاملة لخدمة معينة تم بدؤها من خلال البوابة والوصول إليها لاحقًا؟
[2391/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية احتفاظ العامل المعين على بند الأج
[2392/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: موظف فصل من الخدمة بناءً على حكم نهائي من ديوان

[2393/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد معرفة ما إذا كان يشمل برنامج نطاقات المستثمر الأجنبي؟
[2394/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: الفئات المشمولة بقرار الالزام بالتأمين على عقد ا
[2395/3410] Exp 16/22 | hybrid | fixed_size | e5_large | هل يستطيع تفعيل بند التنافسية في عقد العمل؟
[2396/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي الإجازات المستحقة للمرأة العاملة؟
[2397/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد معرفة الاجراء الذي سيتم تطبيقه في حال عدم التزام المنشأة بنسب نطاقات؟
[2398/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى جواز إجبار الموظف على التمتع بإجازاته الع

[2399/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد معرفة الخدمات المقدمة في نظام مُدد لإدارة الرواتب؟
[2400/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد معرفة ما إذا كان تمكن البوابة والانظمة التابعة لها المستخدم من تعديل بيانات
Checkpoint saved: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\retrieval_evaluation_detailed_results_checkpoint.csv
[2401/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد معرفة المقصود بنصف صافي راتب الموظف مكفوف اليد ومن في حكمه وفقاً للمادة (19
[2402/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف المنتدب من خارج المملكة إل

[2403/3410] Exp 16/22 | hybrid | fixed_size | e5_large | ما طريقة أقدم شكوى على أحد الموظفين في مكاتب العمل؟ وما الحل إذا لم تتم الإفادة
[2404/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي آلية احتساب نسب التوطين بعد تطبيق نطاقات ال
[2405/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: مدة عمل عقد العامل السعودي؟
[2406/3410] Exp 16/22 | hybrid | fixed_size | e5_large | ما طريقة يعامل العامل غير السعودي المعين على بند الأجور من حيث بدل النقل بعد صدو
[2407/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما خطوات تنفيذ الخدمة؟

[2408/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية صرف بدل التفرغ للطبيبات خلال إجاز
[2409/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد معرفة ما إذا كان تسري أحكام لائحة المعينين على بند الأجور الصادرة بقرار مجل
[2410/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد معرفة ما إذا كان الخدمة متاحة للعامل؟
[2411/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى صرف بدل تعيين لمن يتم تعيينه بوظيفة خاضعة
[2412/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ماذا يقصد ببرنامج نطاقات المطور؟

[2413/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد معرفة ما إذا كان يجب ان يكون العامل مسجل على منشاة؟
[2414/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى نظامية منح الموظف بعد تعيينه وفقاً لنظام
[2415/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية صرف بدل الترحيل المنصوص عليه بالم
[2416/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى استفادة العامل المعين على بند الأجور من م

[2417/3410] Exp 16/22 | hybrid | fixed_size | e5_large | ما طريقة يمكنني معرفة إذا كنت مؤهل لتوثيق عقدي مع العامل/ة؟
[2418/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد معرفة ما إذا كان تحتسب مدة الإجازة الاستثنائية لغرض إكمال مدة السنة المطلوب
[2419/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد معرفة نظام إدارة الرواتب؟
[2420/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف مكفوف اليد للعلاوة الدورية
[2421/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: في الاله الحاسبة الخاصة ببرنامج نطاقات المطور هل
[2422/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية نقل العسكري إلى وظيفة مدنية؟

[2423/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي الحقوق العامة في عقد العمل؟
[2424/3410] Exp 16/22 | hybrid | fixed_size | e5_large | ما طريقة يعامل الموظف المتدرب في الداخل أو الخارج في حالة إصابته بمرض وحصوله على
[2425/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي شروط وضوابط الإجازات للعامل؟
[2426/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى امكانية صرف مكافأة نهاية الخدمة المنصوص ع
[2427/3410] Exp 16/22 | hybrid | fixed_size | e5_large | في أي حالة ينتهي عقد العمل؟
[2428/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: موظف منح إجازة عادية بعد عطلة أحد العيدين مباشرة

[2429/3410] Exp 16/22 | hybrid | fixed_size | e5_large | ما طريقة يمكن تصحيح فرع المنشأة الذي يعمل فيها العامل ونقله إلى الفرع الصحيح؟
[2430/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ماذا يحتوي عقد العمل؟
[2431/3410] Exp 16/22 | hybrid | fixed_size | e5_large | ما طريقة يتم التحقق من استلام العامل للأجر الذي سيتم التنفيذ عليه في عقد العمل ا
[2432/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد معرفة عدد أيام الإجازة بحالة زواج العامل؟
[2433/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد معرفة الحسابات التي يمكنني تفعيلها للموظفين للتعديل في حساب مدد الخاص بنظام
[2434/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي اشتراطات فترة التجربة؟

[2435/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد معرفة ما إذا كان النسخة العربية وغير العربية متطابقة من حيث الخدمات والوظائ
[2436/3410] Exp 16/22 | hybrid | fixed_size | e5_large | ما طريقة يتم الاستفادة من خدمة التنقل الوظيفي للعمال الوافدين بين المنشآت؟
[2437/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد معرفة أنواع الشكاوى التي يمكن أن يقدمها الموظف على صاحب العمل؟
[2438/3410] Exp 16/22 | hybrid | fixed_size | e5_large | هل مسموح نظاماً لصاحب العمل تشغيل المرأة العاملة بعد الوضع بمدة أقل من 6 أسابيع؟
[2439/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد معرفة ما إذا كان هناك لائحة وقانون يحمي الأطفال من العنف الأسري؟
[2440/3410] Exp 16/22 | hybrid | fixed_size | e5_large | ما طريقةية تعويض العامل المعين على بند الأجور عن رصيده من الاجازات العادية عند ا

[2441/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: موظف مددت خدمته لمدة سنتين بعد بلوغه السن النظام
[2442/3410] Exp 16/22 | hybrid | fixed_size | e5_large | هل يستطيع نقل العمالة داخل الكيان الواحد؟
[2443/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد معرفة ما إذا كان تغطي الوثيقة النفقات الطبية اللازمة لعلاج العامل المنزلي ب
[2444/3410] Exp 16/22 | hybrid | fixed_size | e5_large | هل يستطيع إلغاء التأشيرة المصدرة من مساند؟
[2445/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف الذي يشغل وظيفة خاضعة لنظا
[2446/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد معرفة ما إذا كان يحسم من راتب الموظف أيام غيابه عن العمل نتيجة مثوله أمام ا

[2447/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: موظف بعد احالته على التقاعد لبلوغ السن النظامية
[2448/3410] Exp 16/22 | hybrid | fixed_size | e5_large | هل يستطيع تعديل المهنة بعد تطبيق المبادرة؟
[2449/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد معرفة ما إذا كان يستحق الموظف التعويض عن إجازته العادية إذا استقال قبل إكما
[2450/3410] Exp 16/22 | hybrid | fixed_size | e5_large | ما طريقة يمكن الاستفادة من الخدمة؟
Checkpoint saved: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\retrieval_evaluation_detailed_results_checkpoint.csv
[2451/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد معرفة فترة الراحة اليومية للرضاعة؟
[2452/3410] Exp 16/22 | hybrid | fixed_size | e5_large | في أي حالة يتاح تجديد رخصة العمل؟

[2453/3410] Exp 16/22 | hybrid | fixed_size | e5_large | ما طريقة يتم حماية حقوق العامل؟
[2454/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف المتدرب لمكافآت وبدلات الت
[2455/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد معرفة ما إذا كان يحسب من عمره أقل من 18 سنة ضمن نسبة التوطين؟
[2456/3410] Exp 16/22 | hybrid | fixed_size | e5_large | أريد معرفة شروط أهلية العامل الوافد للاستفادة من خدمة التنقل الوظيفي؟
[2457/3410] Exp 16/22 | hybrid | fixed_size | e5_large | كم مدة فترة التجربة في نظام العمل السعودي؟
[2458/3410] Exp 16/22 | hybrid | fixed_size | e5_large | هل يجوز وضع العامل تحت التجربة أكثر من مرة لدى نفس صاحب العمل؟

[2459/3410] Exp 16/22 | hybrid | fixed_size | e5_large | ما الحد الأقصى لساعات العمل اليومية في نظام العمل؟
[2460/3410] Exp 16/22 | hybrid | fixed_size | e5_large | ما الحد الأقصى لساعات العمل الأسبوعية؟
[2461/3410] Exp 16/22 | hybrid | fixed_size | e5_large | هل تختلف ساعات العمل في شهر رمضان؟
[2462/3410] Exp 16/22 | hybrid | fixed_size | e5_large | ما مدة الإجازة السنوية المستحقة للعامل؟
[2463/3410] Exp 16/22 | hybrid | fixed_size | e5_large | متى تزيد الإجازة السنوية إلى ثلاثين يومًا؟
[2464/3410] Exp 16/22 | hybrid | fixed_size | e5_large | هل يستحق العامل أجرًا عن أيام الإجازة غير المستخدمة عند انتهاء العمل؟
[2465/3410] Exp 16/22 | hybrid | fixed_size | e5_large | هل يستحق العامل إجازة عند الزواج أو وفاة أحد الأقارب؟

[2466/3410] Exp 16/22 | hybrid | fixed_size | e5_large | هل للعامل الحق في إجازة مرضية؟
[2467/3410] Exp 16/22 | hybrid | fixed_size | e5_large | ما حالات انتهاء عقد العمل؟
[2468/3410] Exp 16/22 | hybrid | fixed_size | e5_large | ما مدة الإشعار عند إنهاء العقد غير محدد المدة؟
[2469/3410] Exp 16/22 | hybrid | fixed_size | e5_large | متى يستحق العامل تعويضًا عند إنهاء العقد لسبب غير مشروع؟
[2470/3410] Exp 16/22 | hybrid | fixed_size | e5_large | متى يجوز لصاحب العمل إنهاء العقد دون مكافأة أو تعويض؟
[2471/3410] Exp 16/22 | hybrid | fixed_size | e5_large | متى يجوز للعامل ترك العمل دون إشعار مع احتفاظه بحقوقه؟
[2472/3410] Exp 16/22 | hybrid | fixed_size | e5_large | متى يستحق العامل مكافأة نهاية الخدمة؟

[2473/3410] Exp 16/22 | hybrid | fixed_size | e5_large | هل يحق لصاحب العمل نقل العامل من مكان عمله الأصلي؟
[2474/3410] Exp 16/22 | hybrid | fixed_size | e5_large | ما المقصود بعقد العمل في نظام العمل؟
[2475/3410] Exp 16/22 | hybrid | fixed_size | e5_large | كيف يتم دفع أجر العامل؟
[2476/3410] Exp 16/22 | hybrid | fixed_size | e5_large | ما واجبات صاحب العمل تجاه العامل؟
[2477/3410] Exp 16/22 | hybrid | fixed_size | e5_large | ما التزامات العامل في نظام العمل؟
[2478/3410] Exp 16/22 | hybrid | fixed_size | e5_large | ما الحد الأقصى لساعات العمل الإضافية وكيف تُحتسب؟
[2479/3410] Exp 16/22 | hybrid | fixed_size | e5_large | ما أحكام السلامة والصحة المهنية في بيئة العمل؟
[2480/3410] Exp 16/22 | hybrid | fixed_size | e5_large | ما حقوق العاملة في إجازة الوضع؟

====================================================================================================
Experiment 17/22: {'chunking_strategy': 'fixed_size', 'embedding_model': 'e5_large', 'retriever': 'hybrid_reranker', 'alpha': 0.8}
====================================================================================================
[2481/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | ما طريقة يمكنني إلغاء أو تعديل طلب تغيير المهنة؟

[2482/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد معرفة الطريقة المتبعة لتسديد قسط التأمين؟

[2483/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | ما طريقةية معاملة محرم الموظفة عند مرافقتها أثناء ابتعاثها للدراسة أو التدريب أو

[2484/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي أهداف برنامج نطاقات المطور؟

[2485/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية الجمع بين بدل المهنة المنصوص عليه

[2486/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: موظف أحيل للتحقيق أثناء إجراء المفاضلة لغرض التر

[2487/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | ما طريقة يتم احتساب أجر الساعات الإضافية؟

[2488/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | هل مسموح تعيين العمال بصفة مؤقتة طبقاً للائحة المعينين على بند الأجور؟

[2489/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | هل يستطيع احتساب أيام المراجعة للمستشفيات داخل مقر العمل أو خارجه إجازة مرضية أو

[2490/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: اعرف حقوق العمال؟

[2491/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: في حال تم رصد مخالفات في ملف الأجور، أين أجد تفا

[2492/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما المقصود من كون عمال المستشفيات ضمن المساعدين

[2493/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: موظف قدم للرياض للالتحاق بدورة تدريبية وبعد انته

[2494/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد معرفة ما إذا كان يخصم بدل المواصلات من راتب الإجازة السنوية؟

[2495/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: موظف استقال من وظيفة بالمرتبة الرابعة ومن ثم عاد

[2496/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد معرفة عقد العمل؟

[2497/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد معرفة ما إذا كان تحسم رواتب العطل الرسمية والأعياد إذا سبقها غياب ولحقها غي

[2498/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد معرفة العمل المرن؟

[2499/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى جواز منح الموظف المنقول بترقية الدرجة الإ

[2500/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: في حالة غياب الموظف عن العمل وإيقاع عقوبة تأديبي

Checkpoint saved: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\retrieval_evaluation_detailed_results_checkpoint.csv
[2501/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | ما طريقة يتم طلب المدرب الاختياري قبل التقدم بطلب شهادة "مواءمة"؟

[2502/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | هل مسموح نظاماً للعامل الانتقال من منشأة في النطاق الأحمر بدون إذن صاحب العمل إل

[2503/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى امكانية ابتعاث أوايفاد العامل المعين على

[2504/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | هل مسموح منح الموظف أثناء فترة التجربة إجازة استثنائية؟

[2505/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى إلزام الموظف بالعمل خارج وقت الدوام، وهل

[2506/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى انطباق المزايا المالية التي تصرف للمشاركي

[2507/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد معرفة ما إذا كان أستطيع رفع ملفات حماية الأجور عبر موقع وزارة الموارد البشر

[2508/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد معرفة الرسوم المطلوبة من المنشآت في برنامج "مواءمة"؟

[2509/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد معرفة ما إذا كان يتم إضافة البيانات التي تملكها الوزارة في الأصل للحقول الم

[2510/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي الحقوق والواجبات العامة للمرأة العاملة؟

[2511/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد معرفة خدمة نقل الموظفين؟

[2512/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد معرفة ما إذا كان ينطبق الشرط الجزائي على العامل أو صاحب العمل؟

[2513/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد معرفة شروط الخدمة؟

[2514/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد معرفة خدمات مبادرة تحسين العلاقة التعاقدية؟

[2515/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: إذا التحق الموظف بالتدريب أثناء إجازته الاستثنائ

[2516/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد معرفة ما إذا كان بإمكاني تعيين أي موظف لدي وإعطاءه صلاحية مفوض رواتب أو مدق

[2517/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف المتدرب الذي انقطع أثناء ف

[2518/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد معرفة ما إذا كان يطالب المستخدم المثبت على وظيفة مشمولة بسلم رواتب الموظفين

[2519/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | ما طريقة أعرف ما إذا كانت منشأتي ملزمة بتطبيق برنامج حماية الأجور؟

[2520/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد معرفة برنامج نطاقات؟ وكيف يحسن بيئة العمل للسعوديين؟

[2521/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: لماذا توجد رسوم مالية على برنامج "مواءمة"؟ وهل ت

[2522/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | هل مسموح نقل العامل المعين على بند الأجور إلى إحدى الجهات الحكومية مع الاحتفاظ ب

[2523/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد معرفة ما إذا كان يحسب برنامج نطاقات من لديهم وظائف رسمية في الحكومة ودوام ج

[2524/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي آلية الترشيح للمرشحين؟

[2525/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | ما طريقة يمكن للمستفيد (المؤمن له) معرفة اسم شركة التأمين التابع لها؟

[2526/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد معرفة إجراءات الانتقال خلال السنة الأولى في الحالات الاستثنائية؟

[2527/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد معرفة ما إذا كان تمكن البوابة والانظمة التابعة لها المستخدم من تخصيص الخدما

[2528/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد معرفة ما إذا كان بإمكان أي موظف في منشأتي أن يسجل في منصة مُدد ويقوم برفع م

[2529/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى أحقية المعين على بند الأجور المكلف بالعمل

[2530/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد معرفة ما إذا كان تسري على شاغلي الوظائف المؤقتة القواعد الواردة في نظام الخ

[2531/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: كتابة العقد؟

[2532/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد معرفة ما إذا كان يترتب على العامل الوافد دفع أي رسوم حكومية (رخصة العمل – ا

[2533/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: موظف منح إجازة عادية تنتهي مع ابتداء عطلة أحد ال

[2534/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | هل يستطيع للمستخدمين الوصول إلى قائمة عملياته او معاملاته السابقة في البوابة؟

[2535/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي خدمة الخروج النهائي؟

[2536/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما الفرق بين المهنة والمسمى الوظيفي؟

[2537/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | ما طريقة يمكن التوفيق بين نصي المادتين (132) و (147) من اللائحة التنفيذية للموار

[2538/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | هل يستطيع أن يتغير انطاق المنشأة دون تغيير في عدد العمالة خلال السنوات القادمة؟

[2539/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: لماذا يتوجب على المنشأة القيام بالتقيّيم الذاتي؟

[2540/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | هل مسموح انهاء عقد العمل بسبب إعادة الهيكلة أو الظروف المالية للمنشأة؟

[2541/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد معرفة ما إذا كان تشمل إجازة أداء الامتحان الدراسي من يؤدي الامتحان خارج الم

[2542/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: موظف قررت الهيئة الطبية العامة معالجته في الداخل

[2543/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد معرفة ما إذا كان الخدمة تتيح تحديث بيانات العامل؟

[2544/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي الآلية لرفع نسب نطاقات تدريجيا؟ وكم هي المد

[2545/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | هل يستطيع حفظ معاملة لخدمة معينة تم بدؤها من خلال البوابة والوصول إليها لاحقًا؟

[2546/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية احتفاظ العامل المعين على بند الأج

[2547/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: موظف فصل من الخدمة بناءً على حكم نهائي من ديوان

[2548/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد معرفة ما إذا كان يشمل برنامج نطاقات المستثمر الأجنبي؟

[2549/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: الفئات المشمولة بقرار الالزام بالتأمين على عقد ا

[2550/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | هل يستطيع تفعيل بند التنافسية في عقد العمل؟

Checkpoint saved: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\retrieval_evaluation_detailed_results_checkpoint.csv
[2551/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي الإجازات المستحقة للمرأة العاملة؟

[2552/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد معرفة الاجراء الذي سيتم تطبيقه في حال عدم التزام المنشأة بنسب نطاقات؟

[2553/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى جواز إجبار الموظف على التمتع بإجازاته الع

[2554/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد معرفة الخدمات المقدمة في نظام مُدد لإدارة الرواتب؟

[2555/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد معرفة ما إذا كان تمكن البوابة والانظمة التابعة لها المستخدم من تعديل بيانات

[2556/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد معرفة المقصود بنصف صافي راتب الموظف مكفوف اليد ومن في حكمه وفقاً للمادة (19

[2557/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف المنتدب من خارج المملكة إل

[2558/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | ما طريقة أقدم شكوى على أحد الموظفين في مكاتب العمل؟ وما الحل إذا لم تتم الإفادة

[2559/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي آلية احتساب نسب التوطين بعد تطبيق نطاقات ال

[2560/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: مدة عمل عقد العامل السعودي؟

[2561/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | ما طريقة يعامل العامل غير السعودي المعين على بند الأجور من حيث بدل النقل بعد صدو

[2562/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما خطوات تنفيذ الخدمة؟

[2563/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية صرف بدل التفرغ للطبيبات خلال إجاز

[2564/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد معرفة ما إذا كان تسري أحكام لائحة المعينين على بند الأجور الصادرة بقرار مجل

[2565/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد معرفة ما إذا كان الخدمة متاحة للعامل؟

[2566/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى صرف بدل تعيين لمن يتم تعيينه بوظيفة خاضعة

[2567/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ماذا يقصد ببرنامج نطاقات المطور؟

[2568/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد معرفة ما إذا كان يجب ان يكون العامل مسجل على منشاة؟

[2569/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى نظامية منح الموظف بعد تعيينه وفقاً لنظام

[2570/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية صرف بدل الترحيل المنصوص عليه بالم

[2571/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى استفادة العامل المعين على بند الأجور من م

[2572/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | ما طريقة يمكنني معرفة إذا كنت مؤهل لتوثيق عقدي مع العامل/ة؟

[2573/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد معرفة ما إذا كان تحتسب مدة الإجازة الاستثنائية لغرض إكمال مدة السنة المطلوب

[2574/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد معرفة نظام إدارة الرواتب؟

[2575/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف مكفوف اليد للعلاوة الدورية

[2576/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: في الاله الحاسبة الخاصة ببرنامج نطاقات المطور هل

[2577/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية نقل العسكري إلى وظيفة مدنية؟

[2578/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي الحقوق العامة في عقد العمل؟

[2579/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | ما طريقة يعامل الموظف المتدرب في الداخل أو الخارج في حالة إصابته بمرض وحصوله على

[2580/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي شروط وضوابط الإجازات للعامل؟

[2581/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى امكانية صرف مكافأة نهاية الخدمة المنصوص ع

[2582/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | في أي حالة ينتهي عقد العمل؟

[2583/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: موظف منح إجازة عادية بعد عطلة أحد العيدين مباشرة

[2584/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | ما طريقة يمكن تصحيح فرع المنشأة الذي يعمل فيها العامل ونقله إلى الفرع الصحيح؟

[2585/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ماذا يحتوي عقد العمل؟

[2586/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | ما طريقة يتم التحقق من استلام العامل للأجر الذي سيتم التنفيذ عليه في عقد العمل ا

[2587/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد معرفة عدد أيام الإجازة بحالة زواج العامل؟

[2588/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد معرفة الحسابات التي يمكنني تفعيلها للموظفين للتعديل في حساب مدد الخاص بنظام

[2589/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ماهي اشتراطات فترة التجربة؟

[2590/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد معرفة ما إذا كان النسخة العربية وغير العربية متطابقة من حيث الخدمات والوظائ

[2591/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | ما طريقة يتم الاستفادة من خدمة التنقل الوظيفي للعمال الوافدين بين المنشآت؟

[2592/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد معرفة أنواع الشكاوى التي يمكن أن يقدمها الموظف على صاحب العمل؟

[2593/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | هل مسموح نظاماً لصاحب العمل تشغيل المرأة العاملة بعد الوضع بمدة أقل من 6 أسابيع؟

[2594/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد معرفة ما إذا كان هناك لائحة وقانون يحمي الأطفال من العنف الأسري؟

[2595/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | ما طريقةية تعويض العامل المعين على بند الأجور عن رصيده من الاجازات العادية عند ا

[2596/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: موظف مددت خدمته لمدة سنتين بعد بلوغه السن النظام

[2597/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | هل يستطيع نقل العمالة داخل الكيان الواحد؟

[2598/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد معرفة ما إذا كان تغطي الوثيقة النفقات الطبية اللازمة لعلاج العامل المنزلي ب

[2599/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | هل يستطيع إلغاء التأشيرة المصدرة من مساند؟

[2600/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف الذي يشغل وظيفة خاضعة لنظا

Checkpoint saved: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\retrieval_evaluation_detailed_results_checkpoint.csv
[2601/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد معرفة ما إذا كان يحسم من راتب الموظف أيام غيابه عن العمل نتيجة مثوله أمام ا

[2602/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: موظف بعد احالته على التقاعد لبلوغ السن النظامية

[2603/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | هل يستطيع تعديل المهنة بعد تطبيق المبادرة؟

[2604/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد معرفة ما إذا كان يستحق الموظف التعويض عن إجازته العادية إذا استقال قبل إكما

[2605/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | ما طريقة يمكن الاستفادة من الخدمة؟

[2606/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد معرفة فترة الراحة اليومية للرضاعة؟

[2607/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | في أي حالة يتاح تجديد رخصة العمل؟

[2608/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | ما طريقة يتم حماية حقوق العامل؟

[2609/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف المتدرب لمكافآت وبدلات الت

[2610/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد معرفة ما إذا كان يحسب من عمره أقل من 18 سنة ضمن نسبة التوطين؟

[2611/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | أريد معرفة شروط أهلية العامل الوافد للاستفادة من خدمة التنقل الوظيفي؟

[2612/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | كم مدة فترة التجربة في نظام العمل السعودي؟

[2613/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | هل يجوز وضع العامل تحت التجربة أكثر من مرة لدى نفس صاحب العمل؟

[2614/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | ما الحد الأقصى لساعات العمل اليومية في نظام العمل؟

[2615/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | ما الحد الأقصى لساعات العمل الأسبوعية؟

[2616/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | هل تختلف ساعات العمل في شهر رمضان؟

[2617/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | ما مدة الإجازة السنوية المستحقة للعامل؟

[2618/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | متى تزيد الإجازة السنوية إلى ثلاثين يومًا؟

[2619/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | هل يستحق العامل أجرًا عن أيام الإجازة غير المستخدمة عند انتهاء العمل؟

[2620/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | هل يستحق العامل إجازة عند الزواج أو وفاة أحد الأقارب؟

[2621/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | هل للعامل الحق في إجازة مرضية؟

[2622/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | ما حالات انتهاء عقد العمل؟

[2623/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | ما مدة الإشعار عند إنهاء العقد غير محدد المدة؟

[2624/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | متى يستحق العامل تعويضًا عند إنهاء العقد لسبب غير مشروع؟

[2625/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | متى يجوز لصاحب العمل إنهاء العقد دون مكافأة أو تعويض؟

[2626/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | متى يجوز للعامل ترك العمل دون إشعار مع احتفاظه بحقوقه؟

[2627/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | متى يستحق العامل مكافأة نهاية الخدمة؟

[2628/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | هل يحق لصاحب العمل نقل العامل من مكان عمله الأصلي؟

[2629/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | ما المقصود بعقد العمل في نظام العمل؟

[2630/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | كيف يتم دفع أجر العامل؟

[2631/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | ما واجبات صاحب العمل تجاه العامل؟

[2632/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | ما التزامات العامل في نظام العمل؟

[2633/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | ما الحد الأقصى لساعات العمل الإضافية وكيف تُحتسب؟

[2634/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | ما أحكام السلامة والصحة المهنية في بيئة العمل؟

[2635/3410] Exp 17/22 | hybrid_reranker | fixed_size | e5_large | ما حقوق العاملة في إجازة الوضع؟

====================================================================================================
Experiment 18/22: {'chunking_strategy': 'fixed_size', 'embedding_model': 'bge_m3', 'retriever': 'dense', 'alpha': None}
====================================================================================================
[2636/3410] Exp 18/22 | dense | fixed_size | bge_m3 | ما طريقة يمكنني إلغاء أو تعديل طلب تغيير المهنة؟
[2637/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد معرفة الطريقة المتبعة لتسديد قسط التأمين؟
[2638/3410] Exp 18/22 | dense | fixed_size | bge_m3 | ما طريقةية معاملة محرم الموظفة عند مرافقتها أثناء ابتعاثها للدراسة أو التدريب أو
[2639/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي أهداف برنامج نطاقات المطور؟
[2640/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية الجمع بين بدل المهنة المنصوص عليه
[2641/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: موظف أحيل للتحقيق أثناء إجراء المفاضلة لغرض التر
[2642/3410] Exp 18/22 | dense | fixed_size | bge_m3 | ما طريقة يتم احتساب أجر الساعات الإضافية؟

[2643/3410] Exp 18/22 | dense | fixed_size | bge_m3 | هل مسموح تعيين العمال بصفة مؤقتة طبقاً للائحة المعينين على بند الأجور؟
[2644/3410] Exp 18/22 | dense | fixed_size | bge_m3 | هل يستطيع احتساب أيام المراجعة للمستشفيات داخل مقر العمل أو خارجه إجازة مرضية أو
[2645/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: اعرف حقوق العمال؟
[2646/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: في حال تم رصد مخالفات في ملف الأجور، أين أجد تفا
[2647/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما المقصود من كون عمال المستشفيات ضمن المساعدين
[2648/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: موظف قدم للرياض للالتحاق بدورة تدريبية وبعد انته
[2649/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد معرفة ما إذا كان يخصم بدل المواصلات من راتب الإجازة السنوية؟

[2650/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: موظف استقال من وظيفة بالمرتبة الرابعة ومن ثم عاد
Checkpoint saved: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\retrieval_evaluation_detailed_results_checkpoint.csv
[2651/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد معرفة عقد العمل؟
[2652/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد معرفة ما إذا كان تحسم رواتب العطل الرسمية والأعياد إذا سبقها غياب ولحقها غي
[2653/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد معرفة العمل المرن؟
[2654/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى جواز منح الموظف المنقول بترقية الدرجة الإ
[2655/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: في حالة غياب الموظف عن العمل وإيقاع عقوبة تأديبي

[2656/3410] Exp 18/22 | dense | fixed_size | bge_m3 | ما طريقة يتم طلب المدرب الاختياري قبل التقدم بطلب شهادة "مواءمة"؟
[2657/3410] Exp 18/22 | dense | fixed_size | bge_m3 | هل مسموح نظاماً للعامل الانتقال من منشأة في النطاق الأحمر بدون إذن صاحب العمل إل
[2658/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى امكانية ابتعاث أوايفاد العامل المعين على
[2659/3410] Exp 18/22 | dense | fixed_size | bge_m3 | هل مسموح منح الموظف أثناء فترة التجربة إجازة استثنائية؟
[2660/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى إلزام الموظف بالعمل خارج وقت الدوام، وهل
[2661/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى انطباق المزايا المالية التي تصرف للمشاركي
[2662/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد معرفة ما إذا كان أستطيع رفع ملفات حماية الأجور عبر موقع وزارة الموارد البشر

[2663/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد معرفة الرسوم المطلوبة من المنشآت في برنامج "مواءمة"؟
[2664/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد معرفة ما إذا كان يتم إضافة البيانات التي تملكها الوزارة في الأصل للحقول الم
[2665/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي الحقوق والواجبات العامة للمرأة العاملة؟
[2666/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد معرفة خدمة نقل الموظفين؟
[2667/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد معرفة ما إذا كان ينطبق الشرط الجزائي على العامل أو صاحب العمل؟
[2668/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد معرفة شروط الخدمة؟
[2669/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد معرفة خدمات مبادرة تحسين العلاقة التعاقدية؟
[2670/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: إذا التحق الموظف بالتدريب أثناء إجازته الاستثنائ
[2671/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد معرفة ما إذا كان بإمكاني تعيين أي موظف لدي وإعطاءه صلاحية مفوض رواتب أو مدق

[2672/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف المتدرب الذي انقطع أثناء ف
[2673/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد معرفة ما إذا كان يطالب المستخدم المثبت على وظيفة مشمولة بسلم رواتب الموظفين
[2674/3410] Exp 18/22 | dense | fixed_size | bge_m3 | ما طريقة أعرف ما إذا كانت منشأتي ملزمة بتطبيق برنامج حماية الأجور؟
[2675/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد معرفة برنامج نطاقات؟ وكيف يحسن بيئة العمل للسعوديين؟
[2676/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: لماذا توجد رسوم مالية على برنامج "مواءمة"؟ وهل ت
[2677/3410] Exp 18/22 | dense | fixed_size | bge_m3 | هل مسموح نقل العامل المعين على بند الأجور إلى إحدى الجهات الحكومية مع الاحتفاظ ب

[2678/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد معرفة ما إذا كان يحسب برنامج نطاقات من لديهم وظائف رسمية في الحكومة ودوام ج
[2679/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي آلية الترشيح للمرشحين؟
[2680/3410] Exp 18/22 | dense | fixed_size | bge_m3 | ما طريقة يمكن للمستفيد (المؤمن له) معرفة اسم شركة التأمين التابع لها؟
[2681/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد معرفة إجراءات الانتقال خلال السنة الأولى في الحالات الاستثنائية؟
[2682/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد معرفة ما إذا كان تمكن البوابة والانظمة التابعة لها المستخدم من تخصيص الخدما
[2683/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد معرفة ما إذا كان بإمكان أي موظف في منشأتي أن يسجل في منصة مُدد ويقوم برفع م
[2684/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى أحقية المعين على بند الأجور المكلف بالعمل
[2685/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد معرفة ما إذا كان تسري على شاغلي الوظائف المؤقتة القواعد الواردة في نظام الخ

[2686/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: كتابة العقد؟
[2687/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد معرفة ما إذا كان يترتب على العامل الوافد دفع أي رسوم حكومية (رخصة العمل – ا
[2688/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: موظف منح إجازة عادية تنتهي مع ابتداء عطلة أحد ال
[2689/3410] Exp 18/22 | dense | fixed_size | bge_m3 | هل يستطيع للمستخدمين الوصول إلى قائمة عملياته او معاملاته السابقة في البوابة؟
[2690/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي خدمة الخروج النهائي؟
[2691/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما الفرق بين المهنة والمسمى الوظيفي؟
[2692/3410] Exp 18/22 | dense | fixed_size | bge_m3 | ما طريقة يمكن التوفيق بين نصي المادتين (132) و (147) من اللائحة التنفيذية للموار
[2693/3410] Exp 18/22 | dense | fixed_size | bge_m3 | هل يستطيع أن يتغير انطاق المنشأة دون تغيير في عدد العمالة خلال السنوات القادمة؟

[2694/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: لماذا يتوجب على المنشأة القيام بالتقيّيم الذاتي؟
[2695/3410] Exp 18/22 | dense | fixed_size | bge_m3 | هل مسموح انهاء عقد العمل بسبب إعادة الهيكلة أو الظروف المالية للمنشأة؟
[2696/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد معرفة ما إذا كان تشمل إجازة أداء الامتحان الدراسي من يؤدي الامتحان خارج الم
[2697/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: موظف قررت الهيئة الطبية العامة معالجته في الداخل
[2698/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد معرفة ما إذا كان الخدمة تتيح تحديث بيانات العامل؟
[2699/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي الآلية لرفع نسب نطاقات تدريجيا؟ وكم هي المد
[2700/3410] Exp 18/22 | dense | fixed_size | bge_m3 | هل يستطيع حفظ معاملة لخدمة معينة تم بدؤها من خلال البوابة والوصول إليها لاحقًا؟

Checkpoint saved: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\retrieval_evaluation_detailed_results_checkpoint.csv
[2701/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية احتفاظ العامل المعين على بند الأج
[2702/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: موظف فصل من الخدمة بناءً على حكم نهائي من ديوان
[2703/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد معرفة ما إذا كان يشمل برنامج نطاقات المستثمر الأجنبي؟
[2704/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: الفئات المشمولة بقرار الالزام بالتأمين على عقد ا
[2705/3410] Exp 18/22 | dense | fixed_size | bge_m3 | هل يستطيع تفعيل بند التنافسية في عقد العمل؟
[2706/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي الإجازات المستحقة للمرأة العاملة؟
[2707/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد معرفة الاجراء الذي سيتم تطبيقه في حال عدم التزام المنشأة بنسب نطاقات؟

[2708/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى جواز إجبار الموظف على التمتع بإجازاته الع
[2709/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد معرفة الخدمات المقدمة في نظام مُدد لإدارة الرواتب؟
[2710/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد معرفة ما إذا كان تمكن البوابة والانظمة التابعة لها المستخدم من تعديل بيانات
[2711/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد معرفة المقصود بنصف صافي راتب الموظف مكفوف اليد ومن في حكمه وفقاً للمادة (19
[2712/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف المنتدب من خارج المملكة إل
[2713/3410] Exp 18/22 | dense | fixed_size | bge_m3 | ما طريقة أقدم شكوى على أحد الموظفين في مكاتب العمل؟ وما الحل إذا لم تتم الإفادة
[2714/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي آلية احتساب نسب التوطين بعد تطبيق نطاقات ال

[2715/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: مدة عمل عقد العامل السعودي؟
[2716/3410] Exp 18/22 | dense | fixed_size | bge_m3 | ما طريقة يعامل العامل غير السعودي المعين على بند الأجور من حيث بدل النقل بعد صدو
[2717/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما خطوات تنفيذ الخدمة؟
[2718/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية صرف بدل التفرغ للطبيبات خلال إجاز
[2719/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد معرفة ما إذا كان تسري أحكام لائحة المعينين على بند الأجور الصادرة بقرار مجل
[2720/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد معرفة ما إذا كان الخدمة متاحة للعامل؟
[2721/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى صرف بدل تعيين لمن يتم تعيينه بوظيفة خاضعة
[2722/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماذا يقصد ببرنامج نطاقات المطور؟

[2723/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد معرفة ما إذا كان يجب ان يكون العامل مسجل على منشاة؟
[2724/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى نظامية منح الموظف بعد تعيينه وفقاً لنظام
[2725/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية صرف بدل الترحيل المنصوص عليه بالم
[2726/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى استفادة العامل المعين على بند الأجور من م
[2727/3410] Exp 18/22 | dense | fixed_size | bge_m3 | ما طريقة يمكنني معرفة إذا كنت مؤهل لتوثيق عقدي مع العامل/ة؟
[2728/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد معرفة ما إذا كان تحتسب مدة الإجازة الاستثنائية لغرض إكمال مدة السنة المطلوب

[2729/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد معرفة نظام إدارة الرواتب؟
[2730/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف مكفوف اليد للعلاوة الدورية
[2731/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: في الاله الحاسبة الخاصة ببرنامج نطاقات المطور هل
[2732/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية نقل العسكري إلى وظيفة مدنية؟
[2733/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي الحقوق العامة في عقد العمل؟
[2734/3410] Exp 18/22 | dense | fixed_size | bge_m3 | ما طريقة يعامل الموظف المتدرب في الداخل أو الخارج في حالة إصابته بمرض وحصوله على
[2735/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي شروط وضوابط الإجازات للعامل؟
[2736/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى امكانية صرف مكافأة نهاية الخدمة المنصوص ع

[2737/3410] Exp 18/22 | dense | fixed_size | bge_m3 | في أي حالة ينتهي عقد العمل؟
[2738/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: موظف منح إجازة عادية بعد عطلة أحد العيدين مباشرة
[2739/3410] Exp 18/22 | dense | fixed_size | bge_m3 | ما طريقة يمكن تصحيح فرع المنشأة الذي يعمل فيها العامل ونقله إلى الفرع الصحيح؟
[2740/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماذا يحتوي عقد العمل؟
[2741/3410] Exp 18/22 | dense | fixed_size | bge_m3 | ما طريقة يتم التحقق من استلام العامل للأجر الذي سيتم التنفيذ عليه في عقد العمل ا
[2742/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد معرفة عدد أيام الإجازة بحالة زواج العامل؟
[2743/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد معرفة الحسابات التي يمكنني تفعيلها للموظفين للتعديل في حساب مدد الخاص بنظام
[2744/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي اشتراطات فترة التجربة؟

[2745/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد معرفة ما إذا كان النسخة العربية وغير العربية متطابقة من حيث الخدمات والوظائ
[2746/3410] Exp 18/22 | dense | fixed_size | bge_m3 | ما طريقة يتم الاستفادة من خدمة التنقل الوظيفي للعمال الوافدين بين المنشآت؟
[2747/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد معرفة أنواع الشكاوى التي يمكن أن يقدمها الموظف على صاحب العمل؟
[2748/3410] Exp 18/22 | dense | fixed_size | bge_m3 | هل مسموح نظاماً لصاحب العمل تشغيل المرأة العاملة بعد الوضع بمدة أقل من 6 أسابيع؟
[2749/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد معرفة ما إذا كان هناك لائحة وقانون يحمي الأطفال من العنف الأسري؟
[2750/3410] Exp 18/22 | dense | fixed_size | bge_m3 | ما طريقةية تعويض العامل المعين على بند الأجور عن رصيده من الاجازات العادية عند ا
Checkpoint saved: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\retrieval_evaluation_detailed_results_checkpoint.csv
[2751/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: موظف مددت خدمته لمدة سنتين بعد بلوغه السن النظام

[2752/3410] Exp 18/22 | dense | fixed_size | bge_m3 | هل يستطيع نقل العمالة داخل الكيان الواحد؟
[2753/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد معرفة ما إذا كان تغطي الوثيقة النفقات الطبية اللازمة لعلاج العامل المنزلي ب
[2754/3410] Exp 18/22 | dense | fixed_size | bge_m3 | هل يستطيع إلغاء التأشيرة المصدرة من مساند؟
[2755/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف الذي يشغل وظيفة خاضعة لنظا
[2756/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد معرفة ما إذا كان يحسم من راتب الموظف أيام غيابه عن العمل نتيجة مثوله أمام ا
[2757/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: موظف بعد احالته على التقاعد لبلوغ السن النظامية
[2758/3410] Exp 18/22 | dense | fixed_size | bge_m3 | هل يستطيع تعديل المهنة بعد تطبيق المبادرة؟
[2759/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد معرفة ما إذا كان يستحق الموظف التعويض عن إجازته العادية إذا استقال قبل إكما

[2760/3410] Exp 18/22 | dense | fixed_size | bge_m3 | ما طريقة يمكن الاستفادة من الخدمة؟
[2761/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد معرفة فترة الراحة اليومية للرضاعة؟
[2762/3410] Exp 18/22 | dense | fixed_size | bge_m3 | في أي حالة يتاح تجديد رخصة العمل؟
[2763/3410] Exp 18/22 | dense | fixed_size | bge_m3 | ما طريقة يتم حماية حقوق العامل؟
[2764/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف المتدرب لمكافآت وبدلات الت
[2765/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد معرفة ما إذا كان يحسب من عمره أقل من 18 سنة ضمن نسبة التوطين؟
[2766/3410] Exp 18/22 | dense | fixed_size | bge_m3 | أريد معرفة شروط أهلية العامل الوافد للاستفادة من خدمة التنقل الوظيفي؟
[2767/3410] Exp 18/22 | dense | fixed_size | bge_m3 | كم مدة فترة التجربة في نظام العمل السعودي؟
[2768/3410] Exp 18/22 | dense | fixed_size | bge_m3 | هل يجوز وضع العامل تحت التجربة أكثر من مرة لدى نفس صاحب العمل؟
[2769/3410] Exp 18/22 | dense | fixed_size | bge_m3 | ما الحد الأقصى لساعات العمل اليومية في نظام العمل؟
[2770/3410] Exp 18/22 | dense | fixed_size | bge_m3 | ما الحد الأقصى لساعات العمل الأسبوعية؟

[2771/3410] Exp 18/22 | dense | fixed_size | bge_m3 | هل تختلف ساعات العمل في شهر رمضان؟
[2772/3410] Exp 18/22 | dense | fixed_size | bge_m3 | ما مدة الإجازة السنوية المستحقة للعامل؟
[2773/3410] Exp 18/22 | dense | fixed_size | bge_m3 | متى تزيد الإجازة السنوية إلى ثلاثين يومًا؟
[2774/3410] Exp 18/22 | dense | fixed_size | bge_m3 | هل يستحق العامل أجرًا عن أيام الإجازة غير المستخدمة عند انتهاء العمل؟
[2775/3410] Exp 18/22 | dense | fixed_size | bge_m3 | هل يستحق العامل إجازة عند الزواج أو وفاة أحد الأقارب؟
[2776/3410] Exp 18/22 | dense | fixed_size | bge_m3 | هل للعامل الحق في إجازة مرضية؟
[2777/3410] Exp 18/22 | dense | fixed_size | bge_m3 | ما حالات انتهاء عقد العمل؟
[2778/3410] Exp 18/22 | dense | fixed_size | bge_m3 | ما مدة الإشعار عند إنهاء العقد غير محدد المدة؟
[2779/3410] Exp 18/22 | dense | fixed_size | bge_m3 | متى يستحق العامل تعويضًا عند إنهاء العقد لسبب غير مشروع؟
[2780/3410] Exp 18/22 | dense | fixed_size | bge_m3 | متى يجوز لصاحب العمل إنهاء العقد دون مكافأة أو تعويض؟
[2781/3410] Exp 18/22 | dense | fixed_size | bge_m3 | متى يجوز للعامل ترك العمل دون إشعار مع احتفاظه بحقوقه؟

[2782/3410] Exp 18/22 | dense | fixed_size | bge_m3 | متى يستحق العامل مكافأة نهاية الخدمة؟
[2783/3410] Exp 18/22 | dense | fixed_size | bge_m3 | هل يحق لصاحب العمل نقل العامل من مكان عمله الأصلي؟
[2784/3410] Exp 18/22 | dense | fixed_size | bge_m3 | ما المقصود بعقد العمل في نظام العمل؟
[2785/3410] Exp 18/22 | dense | fixed_size | bge_m3 | كيف يتم دفع أجر العامل؟
[2786/3410] Exp 18/22 | dense | fixed_size | bge_m3 | ما واجبات صاحب العمل تجاه العامل؟
[2787/3410] Exp 18/22 | dense | fixed_size | bge_m3 | ما التزامات العامل في نظام العمل؟
[2788/3410] Exp 18/22 | dense | fixed_size | bge_m3 | ما الحد الأقصى لساعات العمل الإضافية وكيف تُحتسب؟
[2789/3410] Exp 18/22 | dense | fixed_size | bge_m3 | ما أحكام السلامة والصحة المهنية في بيئة العمل؟
[2790/3410] Exp 18/22 | dense | fixed_size | bge_m3 | ما حقوق العاملة في إجازة الوضع؟
====================================================================================================
Experiment 19/22: {'chunking_strategy': 'fixed_size', 'embedding_model': 'bge_m3', 'retriever': 'hybrid', 'alpha': 0.65}
====================================================================================================
[2791/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | ما طريقة يمكنني إلغاء أو تعديل طلب تغيير المهنة؟
[2792/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد معرفة الطريقة المتبعة لتسديد قسط التأمين؟
[2793/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | ما طريقةية معاملة محرم الموظفة عند مرافقتها أثناء ابتعاثها للدراسة أو التدريب أو

[2794/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي أهداف برنامج نطاقات المطور؟
[2795/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية الجمع بين بدل المهنة المنصوص عليه
[2796/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: موظف أحيل للتحقيق أثناء إجراء المفاضلة لغرض التر
[2797/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | ما طريقة يتم احتساب أجر الساعات الإضافية؟
[2798/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | هل مسموح تعيين العمال بصفة مؤقتة طبقاً للائحة المعينين على بند الأجور؟

[2799/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | هل يستطيع احتساب أيام المراجعة للمستشفيات داخل مقر العمل أو خارجه إجازة مرضية أو
[2800/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: اعرف حقوق العمال؟
Checkpoint saved: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\retrieval_evaluation_detailed_results_checkpoint.csv
[2801/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: في حال تم رصد مخالفات في ملف الأجور، أين أجد تفا
[2802/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما المقصود من كون عمال المستشفيات ضمن المساعدين

[2803/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: موظف قدم للرياض للالتحاق بدورة تدريبية وبعد انته
[2804/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد معرفة ما إذا كان يخصم بدل المواصلات من راتب الإجازة السنوية؟
[2805/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: موظف استقال من وظيفة بالمرتبة الرابعة ومن ثم عاد
[2806/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد معرفة عقد العمل؟
[2807/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد معرفة ما إذا كان تحسم رواتب العطل الرسمية والأعياد إذا سبقها غياب ولحقها غي

[2808/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد معرفة العمل المرن؟
[2809/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى جواز منح الموظف المنقول بترقية الدرجة الإ
[2810/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: في حالة غياب الموظف عن العمل وإيقاع عقوبة تأديبي
[2811/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | ما طريقة يتم طلب المدرب الاختياري قبل التقدم بطلب شهادة "مواءمة"؟
[2812/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | هل مسموح نظاماً للعامل الانتقال من منشأة في النطاق الأحمر بدون إذن صاحب العمل إل

[2813/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى امكانية ابتعاث أوايفاد العامل المعين على
[2814/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | هل مسموح منح الموظف أثناء فترة التجربة إجازة استثنائية؟
[2815/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى إلزام الموظف بالعمل خارج وقت الدوام، وهل
[2816/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى انطباق المزايا المالية التي تصرف للمشاركي
[2817/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد معرفة ما إذا كان أستطيع رفع ملفات حماية الأجور عبر موقع وزارة الموارد البشر

[2818/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد معرفة الرسوم المطلوبة من المنشآت في برنامج "مواءمة"؟
[2819/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد معرفة ما إذا كان يتم إضافة البيانات التي تملكها الوزارة في الأصل للحقول الم
[2820/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي الحقوق والواجبات العامة للمرأة العاملة؟
[2821/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد معرفة خدمة نقل الموظفين؟
[2822/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد معرفة ما إذا كان ينطبق الشرط الجزائي على العامل أو صاحب العمل؟
[2823/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد معرفة شروط الخدمة؟

[2824/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد معرفة خدمات مبادرة تحسين العلاقة التعاقدية؟
[2825/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: إذا التحق الموظف بالتدريب أثناء إجازته الاستثنائ
[2826/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد معرفة ما إذا كان بإمكاني تعيين أي موظف لدي وإعطاءه صلاحية مفوض رواتب أو مدق
[2827/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف المتدرب الذي انقطع أثناء ف
[2828/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد معرفة ما إذا كان يطالب المستخدم المثبت على وظيفة مشمولة بسلم رواتب الموظفين

[2829/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | ما طريقة أعرف ما إذا كانت منشأتي ملزمة بتطبيق برنامج حماية الأجور؟
[2830/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد معرفة برنامج نطاقات؟ وكيف يحسن بيئة العمل للسعوديين؟
[2831/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: لماذا توجد رسوم مالية على برنامج "مواءمة"؟ وهل ت
[2832/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | هل مسموح نقل العامل المعين على بند الأجور إلى إحدى الجهات الحكومية مع الاحتفاظ ب
[2833/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد معرفة ما إذا كان يحسب برنامج نطاقات من لديهم وظائف رسمية في الحكومة ودوام ج
[2834/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي آلية الترشيح للمرشحين؟

[2835/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | ما طريقة يمكن للمستفيد (المؤمن له) معرفة اسم شركة التأمين التابع لها؟
[2836/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد معرفة إجراءات الانتقال خلال السنة الأولى في الحالات الاستثنائية؟
[2837/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد معرفة ما إذا كان تمكن البوابة والانظمة التابعة لها المستخدم من تخصيص الخدما
[2838/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد معرفة ما إذا كان بإمكان أي موظف في منشأتي أن يسجل في منصة مُدد ويقوم برفع م
[2839/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى أحقية المعين على بند الأجور المكلف بالعمل
[2840/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد معرفة ما إذا كان تسري على شاغلي الوظائف المؤقتة القواعد الواردة في نظام الخ

[2841/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: كتابة العقد؟
[2842/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد معرفة ما إذا كان يترتب على العامل الوافد دفع أي رسوم حكومية (رخصة العمل – ا
[2843/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: موظف منح إجازة عادية تنتهي مع ابتداء عطلة أحد ال
[2844/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | هل يستطيع للمستخدمين الوصول إلى قائمة عملياته او معاملاته السابقة في البوابة؟
[2845/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي خدمة الخروج النهائي؟
[2846/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما الفرق بين المهنة والمسمى الوظيفي؟

[2847/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | ما طريقة يمكن التوفيق بين نصي المادتين (132) و (147) من اللائحة التنفيذية للموار
[2848/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | هل يستطيع أن يتغير انطاق المنشأة دون تغيير في عدد العمالة خلال السنوات القادمة؟
[2849/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: لماذا يتوجب على المنشأة القيام بالتقيّيم الذاتي؟
[2850/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | هل مسموح انهاء عقد العمل بسبب إعادة الهيكلة أو الظروف المالية للمنشأة؟
Checkpoint saved: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\retrieval_evaluation_detailed_results_checkpoint.csv
[2851/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد معرفة ما إذا كان تشمل إجازة أداء الامتحان الدراسي من يؤدي الامتحان خارج الم

[2852/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: موظف قررت الهيئة الطبية العامة معالجته في الداخل
[2853/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد معرفة ما إذا كان الخدمة تتيح تحديث بيانات العامل؟
[2854/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي الآلية لرفع نسب نطاقات تدريجيا؟ وكم هي المد
[2855/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | هل يستطيع حفظ معاملة لخدمة معينة تم بدؤها من خلال البوابة والوصول إليها لاحقًا؟
[2856/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية احتفاظ العامل المعين على بند الأج

[2857/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: موظف فصل من الخدمة بناءً على حكم نهائي من ديوان
[2858/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد معرفة ما إذا كان يشمل برنامج نطاقات المستثمر الأجنبي؟
[2859/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: الفئات المشمولة بقرار الالزام بالتأمين على عقد ا
[2860/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | هل يستطيع تفعيل بند التنافسية في عقد العمل؟
[2861/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي الإجازات المستحقة للمرأة العاملة؟
[2862/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد معرفة الاجراء الذي سيتم تطبيقه في حال عدم التزام المنشأة بنسب نطاقات؟

[2863/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى جواز إجبار الموظف على التمتع بإجازاته الع
[2864/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد معرفة الخدمات المقدمة في نظام مُدد لإدارة الرواتب؟
[2865/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد معرفة ما إذا كان تمكن البوابة والانظمة التابعة لها المستخدم من تعديل بيانات
[2866/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد معرفة المقصود بنصف صافي راتب الموظف مكفوف اليد ومن في حكمه وفقاً للمادة (19
[2867/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف المنتدب من خارج المملكة إل
[2868/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | ما طريقة أقدم شكوى على أحد الموظفين في مكاتب العمل؟ وما الحل إذا لم تتم الإفادة

[2869/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي آلية احتساب نسب التوطين بعد تطبيق نطاقات ال
[2870/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: مدة عمل عقد العامل السعودي؟
[2871/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | ما طريقة يعامل العامل غير السعودي المعين على بند الأجور من حيث بدل النقل بعد صدو
[2872/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما خطوات تنفيذ الخدمة؟
[2873/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية صرف بدل التفرغ للطبيبات خلال إجاز
[2874/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد معرفة ما إذا كان تسري أحكام لائحة المعينين على بند الأجور الصادرة بقرار مجل

[2875/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد معرفة ما إذا كان الخدمة متاحة للعامل؟
[2876/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى صرف بدل تعيين لمن يتم تعيينه بوظيفة خاضعة
[2877/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماذا يقصد ببرنامج نطاقات المطور؟
[2878/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد معرفة ما إذا كان يجب ان يكون العامل مسجل على منشاة؟
[2879/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى نظامية منح الموظف بعد تعيينه وفقاً لنظام
[2880/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية صرف بدل الترحيل المنصوص عليه بالم

[2881/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى استفادة العامل المعين على بند الأجور من م
[2882/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | ما طريقة يمكنني معرفة إذا كنت مؤهل لتوثيق عقدي مع العامل/ة؟
[2883/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد معرفة ما إذا كان تحتسب مدة الإجازة الاستثنائية لغرض إكمال مدة السنة المطلوب
[2884/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد معرفة نظام إدارة الرواتب؟
[2885/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف مكفوف اليد للعلاوة الدورية
[2886/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: في الاله الحاسبة الخاصة ببرنامج نطاقات المطور هل

[2887/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية نقل العسكري إلى وظيفة مدنية؟
[2888/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي الحقوق العامة في عقد العمل؟
[2889/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | ما طريقة يعامل الموظف المتدرب في الداخل أو الخارج في حالة إصابته بمرض وحصوله على
[2890/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي شروط وضوابط الإجازات للعامل؟
[2891/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى امكانية صرف مكافأة نهاية الخدمة المنصوص ع

[2892/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | في أي حالة ينتهي عقد العمل؟
[2893/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: موظف منح إجازة عادية بعد عطلة أحد العيدين مباشرة
[2894/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | ما طريقة يمكن تصحيح فرع المنشأة الذي يعمل فيها العامل ونقله إلى الفرع الصحيح؟
[2895/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماذا يحتوي عقد العمل؟
[2896/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | ما طريقة يتم التحقق من استلام العامل للأجر الذي سيتم التنفيذ عليه في عقد العمل ا

[2897/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد معرفة عدد أيام الإجازة بحالة زواج العامل؟
[2898/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد معرفة الحسابات التي يمكنني تفعيلها للموظفين للتعديل في حساب مدد الخاص بنظام
[2899/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي اشتراطات فترة التجربة؟
[2900/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد معرفة ما إذا كان النسخة العربية وغير العربية متطابقة من حيث الخدمات والوظائ
Checkpoint saved: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\retrieval_evaluation_detailed_results_checkpoint.csv
[2901/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | ما طريقة يتم الاستفادة من خدمة التنقل الوظيفي للعمال الوافدين بين المنشآت؟

[2902/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد معرفة أنواع الشكاوى التي يمكن أن يقدمها الموظف على صاحب العمل؟
[2903/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | هل مسموح نظاماً لصاحب العمل تشغيل المرأة العاملة بعد الوضع بمدة أقل من 6 أسابيع؟
[2904/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد معرفة ما إذا كان هناك لائحة وقانون يحمي الأطفال من العنف الأسري؟
[2905/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | ما طريقةية تعويض العامل المعين على بند الأجور عن رصيده من الاجازات العادية عند ا
[2906/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: موظف مددت خدمته لمدة سنتين بعد بلوغه السن النظام

[2907/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | هل يستطيع نقل العمالة داخل الكيان الواحد؟
[2908/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد معرفة ما إذا كان تغطي الوثيقة النفقات الطبية اللازمة لعلاج العامل المنزلي ب
[2909/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | هل يستطيع إلغاء التأشيرة المصدرة من مساند؟
[2910/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف الذي يشغل وظيفة خاضعة لنظا
[2911/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد معرفة ما إذا كان يحسم من راتب الموظف أيام غيابه عن العمل نتيجة مثوله أمام ا

[2912/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: موظف بعد احالته على التقاعد لبلوغ السن النظامية
[2913/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | هل يستطيع تعديل المهنة بعد تطبيق المبادرة؟
[2914/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد معرفة ما إذا كان يستحق الموظف التعويض عن إجازته العادية إذا استقال قبل إكما
[2915/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | ما طريقة يمكن الاستفادة من الخدمة؟
[2916/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد معرفة فترة الراحة اليومية للرضاعة؟
[2917/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | في أي حالة يتاح تجديد رخصة العمل؟
[2918/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | ما طريقة يتم حماية حقوق العامل؟

[2919/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف المتدرب لمكافآت وبدلات الت
[2920/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد معرفة ما إذا كان يحسب من عمره أقل من 18 سنة ضمن نسبة التوطين؟
[2921/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | أريد معرفة شروط أهلية العامل الوافد للاستفادة من خدمة التنقل الوظيفي؟
[2922/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | كم مدة فترة التجربة في نظام العمل السعودي؟
[2923/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | هل يجوز وضع العامل تحت التجربة أكثر من مرة لدى نفس صاحب العمل؟
[2924/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | ما الحد الأقصى لساعات العمل اليومية في نظام العمل؟

[2925/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | ما الحد الأقصى لساعات العمل الأسبوعية؟
[2926/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | هل تختلف ساعات العمل في شهر رمضان؟
[2927/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | ما مدة الإجازة السنوية المستحقة للعامل؟
[2928/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | متى تزيد الإجازة السنوية إلى ثلاثين يومًا؟
[2929/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | هل يستحق العامل أجرًا عن أيام الإجازة غير المستخدمة عند انتهاء العمل؟
[2930/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | هل يستحق العامل إجازة عند الزواج أو وفاة أحد الأقارب؟
[2931/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | هل للعامل الحق في إجازة مرضية؟
[2932/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | ما حالات انتهاء عقد العمل؟

[2933/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | ما مدة الإشعار عند إنهاء العقد غير محدد المدة؟
[2934/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | متى يستحق العامل تعويضًا عند إنهاء العقد لسبب غير مشروع؟
[2935/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | متى يجوز لصاحب العمل إنهاء العقد دون مكافأة أو تعويض؟
[2936/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | متى يجوز للعامل ترك العمل دون إشعار مع احتفاظه بحقوقه؟
[2937/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | متى يستحق العامل مكافأة نهاية الخدمة؟
[2938/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | هل يحق لصاحب العمل نقل العامل من مكان عمله الأصلي؟
[2939/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | ما المقصود بعقد العمل في نظام العمل؟

[2940/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | كيف يتم دفع أجر العامل؟
[2941/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | ما واجبات صاحب العمل تجاه العامل؟
[2942/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | ما التزامات العامل في نظام العمل؟
[2943/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | ما الحد الأقصى لساعات العمل الإضافية وكيف تُحتسب؟
[2944/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | ما أحكام السلامة والصحة المهنية في بيئة العمل؟
[2945/3410] Exp 19/22 | hybrid | fixed_size | bge_m3 | ما حقوق العاملة في إجازة الوضع؟
====================================================================================================
Experiment 20/22: {'chunking_strategy': 'fixed_size', 'embedding_model': 'bge_m3', 'retriever': 'hybrid', 'alpha': 0.8}
====================================================================================================
[2946/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | ما طريقة يمكنني إلغاء أو تعديل طلب تغيير المهنة؟
[2947/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد معرفة الطريقة المتبعة لتسديد قسط التأمين؟
[2948/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | ما طريقةية معاملة محرم الموظفة عند مرافقتها أثناء ابتعاثها للدراسة أو التدريب أو

[2949/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي أهداف برنامج نطاقات المطور؟
[2950/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية الجمع بين بدل المهنة المنصوص عليه
Checkpoint saved: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\retrieval_evaluation_detailed_results_checkpoint.csv
[2951/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: موظف أحيل للتحقيق أثناء إجراء المفاضلة لغرض التر
[2952/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | ما طريقة يتم احتساب أجر الساعات الإضافية؟

[2953/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | هل مسموح تعيين العمال بصفة مؤقتة طبقاً للائحة المعينين على بند الأجور؟
[2954/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | هل يستطيع احتساب أيام المراجعة للمستشفيات داخل مقر العمل أو خارجه إجازة مرضية أو
[2955/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: اعرف حقوق العمال؟
[2956/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: في حال تم رصد مخالفات في ملف الأجور، أين أجد تفا
[2957/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما المقصود من كون عمال المستشفيات ضمن المساعدين

[2958/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: موظف قدم للرياض للالتحاق بدورة تدريبية وبعد انته
[2959/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد معرفة ما إذا كان يخصم بدل المواصلات من راتب الإجازة السنوية؟
[2960/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: موظف استقال من وظيفة بالمرتبة الرابعة ومن ثم عاد
[2961/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد معرفة عقد العمل؟
[2962/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد معرفة ما إذا كان تحسم رواتب العطل الرسمية والأعياد إذا سبقها غياب ولحقها غي

[2963/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد معرفة العمل المرن؟
[2964/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى جواز منح الموظف المنقول بترقية الدرجة الإ
[2965/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: في حالة غياب الموظف عن العمل وإيقاع عقوبة تأديبي
[2966/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | ما طريقة يتم طلب المدرب الاختياري قبل التقدم بطلب شهادة "مواءمة"؟
[2967/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | هل مسموح نظاماً للعامل الانتقال من منشأة في النطاق الأحمر بدون إذن صاحب العمل إل

[2968/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى امكانية ابتعاث أوايفاد العامل المعين على
[2969/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | هل مسموح منح الموظف أثناء فترة التجربة إجازة استثنائية؟
[2970/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى إلزام الموظف بالعمل خارج وقت الدوام، وهل
[2971/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى انطباق المزايا المالية التي تصرف للمشاركي
[2972/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد معرفة ما إذا كان أستطيع رفع ملفات حماية الأجور عبر موقع وزارة الموارد البشر

[2973/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد معرفة الرسوم المطلوبة من المنشآت في برنامج "مواءمة"؟
[2974/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد معرفة ما إذا كان يتم إضافة البيانات التي تملكها الوزارة في الأصل للحقول الم
[2975/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي الحقوق والواجبات العامة للمرأة العاملة؟
[2976/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد معرفة خدمة نقل الموظفين؟
[2977/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد معرفة ما إذا كان ينطبق الشرط الجزائي على العامل أو صاحب العمل؟
[2978/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد معرفة شروط الخدمة؟
[2979/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد معرفة خدمات مبادرة تحسين العلاقة التعاقدية؟

[2980/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: إذا التحق الموظف بالتدريب أثناء إجازته الاستثنائ
[2981/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد معرفة ما إذا كان بإمكاني تعيين أي موظف لدي وإعطاءه صلاحية مفوض رواتب أو مدق
[2982/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف المتدرب الذي انقطع أثناء ف
[2983/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد معرفة ما إذا كان يطالب المستخدم المثبت على وظيفة مشمولة بسلم رواتب الموظفين
[2984/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | ما طريقة أعرف ما إذا كانت منشأتي ملزمة بتطبيق برنامج حماية الأجور؟

[2985/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد معرفة برنامج نطاقات؟ وكيف يحسن بيئة العمل للسعوديين؟
[2986/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: لماذا توجد رسوم مالية على برنامج "مواءمة"؟ وهل ت
[2987/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | هل مسموح نقل العامل المعين على بند الأجور إلى إحدى الجهات الحكومية مع الاحتفاظ ب
[2988/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد معرفة ما إذا كان يحسب برنامج نطاقات من لديهم وظائف رسمية في الحكومة ودوام ج
[2989/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي آلية الترشيح للمرشحين؟

[2990/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | ما طريقة يمكن للمستفيد (المؤمن له) معرفة اسم شركة التأمين التابع لها؟
[2991/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد معرفة إجراءات الانتقال خلال السنة الأولى في الحالات الاستثنائية؟
[2992/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد معرفة ما إذا كان تمكن البوابة والانظمة التابعة لها المستخدم من تخصيص الخدما
[2993/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد معرفة ما إذا كان بإمكان أي موظف في منشأتي أن يسجل في منصة مُدد ويقوم برفع م
[2994/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى أحقية المعين على بند الأجور المكلف بالعمل
[2995/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد معرفة ما إذا كان تسري على شاغلي الوظائف المؤقتة القواعد الواردة في نظام الخ

[2996/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: كتابة العقد؟
[2997/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد معرفة ما إذا كان يترتب على العامل الوافد دفع أي رسوم حكومية (رخصة العمل – ا
[2998/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: موظف منح إجازة عادية تنتهي مع ابتداء عطلة أحد ال
[2999/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | هل يستطيع للمستخدمين الوصول إلى قائمة عملياته او معاملاته السابقة في البوابة؟
[3000/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي خدمة الخروج النهائي؟

Checkpoint saved: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\retrieval_evaluation_detailed_results_checkpoint.csv
[3001/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما الفرق بين المهنة والمسمى الوظيفي؟
[3002/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | ما طريقة يمكن التوفيق بين نصي المادتين (132) و (147) من اللائحة التنفيذية للموار
[3003/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | هل يستطيع أن يتغير انطاق المنشأة دون تغيير في عدد العمالة خلال السنوات القادمة؟
[3004/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: لماذا يتوجب على المنشأة القيام بالتقيّيم الذاتي؟
[3005/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | هل مسموح انهاء عقد العمل بسبب إعادة الهيكلة أو الظروف المالية للمنشأة؟

[3006/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد معرفة ما إذا كان تشمل إجازة أداء الامتحان الدراسي من يؤدي الامتحان خارج الم
[3007/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: موظف قررت الهيئة الطبية العامة معالجته في الداخل
[3008/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد معرفة ما إذا كان الخدمة تتيح تحديث بيانات العامل؟
[3009/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي الآلية لرفع نسب نطاقات تدريجيا؟ وكم هي المد
[3010/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | هل يستطيع حفظ معاملة لخدمة معينة تم بدؤها من خلال البوابة والوصول إليها لاحقًا؟
[3011/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية احتفاظ العامل المعين على بند الأج

[3012/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: موظف فصل من الخدمة بناءً على حكم نهائي من ديوان
[3013/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد معرفة ما إذا كان يشمل برنامج نطاقات المستثمر الأجنبي؟
[3014/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: الفئات المشمولة بقرار الالزام بالتأمين على عقد ا
[3015/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | هل يستطيع تفعيل بند التنافسية في عقد العمل؟
[3016/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي الإجازات المستحقة للمرأة العاملة؟
[3017/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد معرفة الاجراء الذي سيتم تطبيقه في حال عدم التزام المنشأة بنسب نطاقات؟

[3018/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى جواز إجبار الموظف على التمتع بإجازاته الع
[3019/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد معرفة الخدمات المقدمة في نظام مُدد لإدارة الرواتب؟
[3020/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد معرفة ما إذا كان تمكن البوابة والانظمة التابعة لها المستخدم من تعديل بيانات
[3021/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد معرفة المقصود بنصف صافي راتب الموظف مكفوف اليد ومن في حكمه وفقاً للمادة (19
[3022/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف المنتدب من خارج المملكة إل

[3023/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | ما طريقة أقدم شكوى على أحد الموظفين في مكاتب العمل؟ وما الحل إذا لم تتم الإفادة
[3024/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي آلية احتساب نسب التوطين بعد تطبيق نطاقات ال
[3025/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: مدة عمل عقد العامل السعودي؟
[3026/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | ما طريقة يعامل العامل غير السعودي المعين على بند الأجور من حيث بدل النقل بعد صدو
[3027/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما خطوات تنفيذ الخدمة؟
[3028/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية صرف بدل التفرغ للطبيبات خلال إجاز

[3029/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد معرفة ما إذا كان تسري أحكام لائحة المعينين على بند الأجور الصادرة بقرار مجل
[3030/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد معرفة ما إذا كان الخدمة متاحة للعامل؟
[3031/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى صرف بدل تعيين لمن يتم تعيينه بوظيفة خاضعة
[3032/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماذا يقصد ببرنامج نطاقات المطور؟
[3033/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد معرفة ما إذا كان يجب ان يكون العامل مسجل على منشاة؟

[3034/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى نظامية منح الموظف بعد تعيينه وفقاً لنظام
[3035/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية صرف بدل الترحيل المنصوص عليه بالم
[3036/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى استفادة العامل المعين على بند الأجور من م
[3037/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | ما طريقة يمكنني معرفة إذا كنت مؤهل لتوثيق عقدي مع العامل/ة؟

[3038/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد معرفة ما إذا كان تحتسب مدة الإجازة الاستثنائية لغرض إكمال مدة السنة المطلوب
[3039/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد معرفة نظام إدارة الرواتب؟
[3040/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف مكفوف اليد للعلاوة الدورية
[3041/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: في الاله الحاسبة الخاصة ببرنامج نطاقات المطور هل
[3042/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية نقل العسكري إلى وظيفة مدنية؟

[3043/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي الحقوق العامة في عقد العمل؟
[3044/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | ما طريقة يعامل الموظف المتدرب في الداخل أو الخارج في حالة إصابته بمرض وحصوله على
[3045/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي شروط وضوابط الإجازات للعامل؟
[3046/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى امكانية صرف مكافأة نهاية الخدمة المنصوص ع
[3047/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | في أي حالة ينتهي عقد العمل؟

[3048/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: موظف منح إجازة عادية بعد عطلة أحد العيدين مباشرة
[3049/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | ما طريقة يمكن تصحيح فرع المنشأة الذي يعمل فيها العامل ونقله إلى الفرع الصحيح؟
[3050/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماذا يحتوي عقد العمل؟
Checkpoint saved: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\retrieval_evaluation_detailed_results_checkpoint.csv
[3051/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | ما طريقة يتم التحقق من استلام العامل للأجر الذي سيتم التنفيذ عليه في عقد العمل ا

[3052/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد معرفة عدد أيام الإجازة بحالة زواج العامل؟
[3053/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد معرفة الحسابات التي يمكنني تفعيلها للموظفين للتعديل في حساب مدد الخاص بنظام
[3054/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي اشتراطات فترة التجربة؟
[3055/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد معرفة ما إذا كان النسخة العربية وغير العربية متطابقة من حيث الخدمات والوظائ
[3056/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | ما طريقة يتم الاستفادة من خدمة التنقل الوظيفي للعمال الوافدين بين المنشآت؟
[3057/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد معرفة أنواع الشكاوى التي يمكن أن يقدمها الموظف على صاحب العمل؟

[3058/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | هل مسموح نظاماً لصاحب العمل تشغيل المرأة العاملة بعد الوضع بمدة أقل من 6 أسابيع؟
[3059/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد معرفة ما إذا كان هناك لائحة وقانون يحمي الأطفال من العنف الأسري؟
[3060/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | ما طريقةية تعويض العامل المعين على بند الأجور عن رصيده من الاجازات العادية عند ا
[3061/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: موظف مددت خدمته لمدة سنتين بعد بلوغه السن النظام
[3062/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | هل يستطيع نقل العمالة داخل الكيان الواحد؟

[3063/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد معرفة ما إذا كان تغطي الوثيقة النفقات الطبية اللازمة لعلاج العامل المنزلي ب
[3064/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | هل يستطيع إلغاء التأشيرة المصدرة من مساند؟
[3065/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف الذي يشغل وظيفة خاضعة لنظا
[3066/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد معرفة ما إذا كان يحسم من راتب الموظف أيام غيابه عن العمل نتيجة مثوله أمام ا
[3067/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: موظف بعد احالته على التقاعد لبلوغ السن النظامية

[3068/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | هل يستطيع تعديل المهنة بعد تطبيق المبادرة؟
[3069/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد معرفة ما إذا كان يستحق الموظف التعويض عن إجازته العادية إذا استقال قبل إكما
[3070/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | ما طريقة يمكن الاستفادة من الخدمة؟
[3071/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد معرفة فترة الراحة اليومية للرضاعة؟
[3072/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | في أي حالة يتاح تجديد رخصة العمل؟
[3073/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | ما طريقة يتم حماية حقوق العامل؟
[3074/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف المتدرب لمكافآت وبدلات الت

[3075/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد معرفة ما إذا كان يحسب من عمره أقل من 18 سنة ضمن نسبة التوطين؟
[3076/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | أريد معرفة شروط أهلية العامل الوافد للاستفادة من خدمة التنقل الوظيفي؟
[3077/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | كم مدة فترة التجربة في نظام العمل السعودي؟
[3078/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | هل يجوز وضع العامل تحت التجربة أكثر من مرة لدى نفس صاحب العمل؟
[3079/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | ما الحد الأقصى لساعات العمل اليومية في نظام العمل؟
[3080/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | ما الحد الأقصى لساعات العمل الأسبوعية؟
[3081/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | هل تختلف ساعات العمل في شهر رمضان؟
[3082/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | ما مدة الإجازة السنوية المستحقة للعامل؟
[3083/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | متى تزيد الإجازة السنوية إلى ثلاثين يومًا؟

[3084/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | هل يستحق العامل أجرًا عن أيام الإجازة غير المستخدمة عند انتهاء العمل؟
[3085/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | هل يستحق العامل إجازة عند الزواج أو وفاة أحد الأقارب؟
[3086/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | هل للعامل الحق في إجازة مرضية؟
[3087/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | ما حالات انتهاء عقد العمل؟
[3088/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | ما مدة الإشعار عند إنهاء العقد غير محدد المدة؟
[3089/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | متى يستحق العامل تعويضًا عند إنهاء العقد لسبب غير مشروع؟
[3090/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | متى يجوز لصاحب العمل إنهاء العقد دون مكافأة أو تعويض؟
[3091/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | متى يجوز للعامل ترك العمل دون إشعار مع احتفاظه بحقوقه؟

[3092/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | متى يستحق العامل مكافأة نهاية الخدمة؟
[3093/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | هل يحق لصاحب العمل نقل العامل من مكان عمله الأصلي؟
[3094/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | ما المقصود بعقد العمل في نظام العمل؟
[3095/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | كيف يتم دفع أجر العامل؟
[3096/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | ما واجبات صاحب العمل تجاه العامل؟
[3097/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | ما التزامات العامل في نظام العمل؟
[3098/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | ما الحد الأقصى لساعات العمل الإضافية وكيف تُحتسب؟
[3099/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | ما أحكام السلامة والصحة المهنية في بيئة العمل؟
[3100/3410] Exp 20/22 | hybrid | fixed_size | bge_m3 | ما حقوق العاملة في إجازة الوضع؟

Checkpoint saved: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\retrieval_evaluation_detailed_results_checkpoint.csv
====================================================================================================
Experiment 21/22: {'chunking_strategy': 'fixed_size', 'embedding_model': 'bge_m3', 'retriever': 'hybrid', 'alpha': 0.9}
====================================================================================================
[3101/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | ما طريقة يمكنني إلغاء أو تعديل طلب تغيير المهنة؟
[3102/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد معرفة الطريقة المتبعة لتسديد قسط التأمين؟
[3103/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | ما طريقةية معاملة محرم الموظفة عند مرافقتها أثناء ابتعاثها للدراسة أو التدريب أو
[3104/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي أهداف برنامج نطاقات المطور؟
[3105/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية الجمع بين بدل المهنة المنصوص عليه
[3106/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: موظف أحيل للتحقيق أثناء إجراء المفاضلة لغرض التر

[3107/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | ما طريقة يتم احتساب أجر الساعات الإضافية؟
[3108/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | هل مسموح تعيين العمال بصفة مؤقتة طبقاً للائحة المعينين على بند الأجور؟
[3109/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | هل يستطيع احتساب أيام المراجعة للمستشفيات داخل مقر العمل أو خارجه إجازة مرضية أو
[3110/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: اعرف حقوق العمال؟
[3111/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: في حال تم رصد مخالفات في ملف الأجور، أين أجد تفا
[3112/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما المقصود من كون عمال المستشفيات ضمن المساعدين

[3113/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: موظف قدم للرياض للالتحاق بدورة تدريبية وبعد انته
[3114/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد معرفة ما إذا كان يخصم بدل المواصلات من راتب الإجازة السنوية؟
[3115/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: موظف استقال من وظيفة بالمرتبة الرابعة ومن ثم عاد
[3116/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد معرفة عقد العمل؟
[3117/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد معرفة ما إذا كان تحسم رواتب العطل الرسمية والأعياد إذا سبقها غياب ولحقها غي

[3118/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد معرفة العمل المرن؟
[3119/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى جواز منح الموظف المنقول بترقية الدرجة الإ
[3120/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: في حالة غياب الموظف عن العمل وإيقاع عقوبة تأديبي
[3121/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | ما طريقة يتم طلب المدرب الاختياري قبل التقدم بطلب شهادة "مواءمة"؟
[3122/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | هل مسموح نظاماً للعامل الانتقال من منشأة في النطاق الأحمر بدون إذن صاحب العمل إل

[3123/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى امكانية ابتعاث أوايفاد العامل المعين على
[3124/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | هل مسموح منح الموظف أثناء فترة التجربة إجازة استثنائية؟
[3125/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى إلزام الموظف بالعمل خارج وقت الدوام، وهل
[3126/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى انطباق المزايا المالية التي تصرف للمشاركي
[3127/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد معرفة ما إذا كان أستطيع رفع ملفات حماية الأجور عبر موقع وزارة الموارد البشر

[3128/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد معرفة الرسوم المطلوبة من المنشآت في برنامج "مواءمة"؟
[3129/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد معرفة ما إذا كان يتم إضافة البيانات التي تملكها الوزارة في الأصل للحقول الم
[3130/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي الحقوق والواجبات العامة للمرأة العاملة؟
[3131/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد معرفة خدمة نقل الموظفين؟
[3132/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد معرفة ما إذا كان ينطبق الشرط الجزائي على العامل أو صاحب العمل؟
[3133/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد معرفة شروط الخدمة؟
[3134/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد معرفة خدمات مبادرة تحسين العلاقة التعاقدية؟

[3135/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: إذا التحق الموظف بالتدريب أثناء إجازته الاستثنائ
[3136/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد معرفة ما إذا كان بإمكاني تعيين أي موظف لدي وإعطاءه صلاحية مفوض رواتب أو مدق
[3137/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف المتدرب الذي انقطع أثناء ف
[3138/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد معرفة ما إذا كان يطالب المستخدم المثبت على وظيفة مشمولة بسلم رواتب الموظفين
[3139/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | ما طريقة أعرف ما إذا كانت منشأتي ملزمة بتطبيق برنامج حماية الأجور؟

[3140/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد معرفة برنامج نطاقات؟ وكيف يحسن بيئة العمل للسعوديين؟
[3141/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: لماذا توجد رسوم مالية على برنامج "مواءمة"؟ وهل ت
[3142/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | هل مسموح نقل العامل المعين على بند الأجور إلى إحدى الجهات الحكومية مع الاحتفاظ ب
[3143/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد معرفة ما إذا كان يحسب برنامج نطاقات من لديهم وظائف رسمية في الحكومة ودوام ج
[3144/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي آلية الترشيح للمرشحين؟
[3145/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | ما طريقة يمكن للمستفيد (المؤمن له) معرفة اسم شركة التأمين التابع لها؟

[3146/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد معرفة إجراءات الانتقال خلال السنة الأولى في الحالات الاستثنائية؟
[3147/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد معرفة ما إذا كان تمكن البوابة والانظمة التابعة لها المستخدم من تخصيص الخدما
[3148/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد معرفة ما إذا كان بإمكان أي موظف في منشأتي أن يسجل في منصة مُدد ويقوم برفع م
[3149/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى أحقية المعين على بند الأجور المكلف بالعمل
[3150/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد معرفة ما إذا كان تسري على شاغلي الوظائف المؤقتة القواعد الواردة في نظام الخ

Checkpoint saved: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\retrieval_evaluation_detailed_results_checkpoint.csv
[3151/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: كتابة العقد؟
[3152/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد معرفة ما إذا كان يترتب على العامل الوافد دفع أي رسوم حكومية (رخصة العمل – ا
[3153/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: موظف منح إجازة عادية تنتهي مع ابتداء عطلة أحد ال
[3154/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | هل يستطيع للمستخدمين الوصول إلى قائمة عملياته او معاملاته السابقة في البوابة؟
[3155/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي خدمة الخروج النهائي؟
[3156/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما الفرق بين المهنة والمسمى الوظيفي؟

[3157/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | ما طريقة يمكن التوفيق بين نصي المادتين (132) و (147) من اللائحة التنفيذية للموار
[3158/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | هل يستطيع أن يتغير انطاق المنشأة دون تغيير في عدد العمالة خلال السنوات القادمة؟
[3159/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: لماذا يتوجب على المنشأة القيام بالتقيّيم الذاتي؟
[3160/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | هل مسموح انهاء عقد العمل بسبب إعادة الهيكلة أو الظروف المالية للمنشأة؟
[3161/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد معرفة ما إذا كان تشمل إجازة أداء الامتحان الدراسي من يؤدي الامتحان خارج الم
[3162/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: موظف قررت الهيئة الطبية العامة معالجته في الداخل

[3163/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد معرفة ما إذا كان الخدمة تتيح تحديث بيانات العامل؟
[3164/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي الآلية لرفع نسب نطاقات تدريجيا؟ وكم هي المد
[3165/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | هل يستطيع حفظ معاملة لخدمة معينة تم بدؤها من خلال البوابة والوصول إليها لاحقًا؟
[3166/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية احتفاظ العامل المعين على بند الأج
[3167/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: موظف فصل من الخدمة بناءً على حكم نهائي من ديوان

[3168/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد معرفة ما إذا كان يشمل برنامج نطاقات المستثمر الأجنبي؟
[3169/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: الفئات المشمولة بقرار الالزام بالتأمين على عقد ا
[3170/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | هل يستطيع تفعيل بند التنافسية في عقد العمل؟
[3171/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي الإجازات المستحقة للمرأة العاملة؟
[3172/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد معرفة الاجراء الذي سيتم تطبيقه في حال عدم التزام المنشأة بنسب نطاقات؟
[3173/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى جواز إجبار الموظف على التمتع بإجازاته الع

[3174/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد معرفة الخدمات المقدمة في نظام مُدد لإدارة الرواتب؟
[3175/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد معرفة ما إذا كان تمكن البوابة والانظمة التابعة لها المستخدم من تعديل بيانات
[3176/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد معرفة المقصود بنصف صافي راتب الموظف مكفوف اليد ومن في حكمه وفقاً للمادة (19
[3177/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف المنتدب من خارج المملكة إل
[3178/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | ما طريقة أقدم شكوى على أحد الموظفين في مكاتب العمل؟ وما الحل إذا لم تتم الإفادة
[3179/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي آلية احتساب نسب التوطين بعد تطبيق نطاقات ال

[3180/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: مدة عمل عقد العامل السعودي؟
[3181/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | ما طريقة يعامل العامل غير السعودي المعين على بند الأجور من حيث بدل النقل بعد صدو
[3182/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما خطوات تنفيذ الخدمة؟
[3183/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية صرف بدل التفرغ للطبيبات خلال إجاز
[3184/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد معرفة ما إذا كان تسري أحكام لائحة المعينين على بند الأجور الصادرة بقرار مجل
[3185/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد معرفة ما إذا كان الخدمة متاحة للعامل؟

[3186/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى صرف بدل تعيين لمن يتم تعيينه بوظيفة خاضعة
[3187/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماذا يقصد ببرنامج نطاقات المطور؟
[3188/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد معرفة ما إذا كان يجب ان يكون العامل مسجل على منشاة؟
[3189/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى نظامية منح الموظف بعد تعيينه وفقاً لنظام
[3190/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية صرف بدل الترحيل المنصوص عليه بالم

[3191/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى استفادة العامل المعين على بند الأجور من م
[3192/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | ما طريقة يمكنني معرفة إذا كنت مؤهل لتوثيق عقدي مع العامل/ة؟
[3193/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد معرفة ما إذا كان تحتسب مدة الإجازة الاستثنائية لغرض إكمال مدة السنة المطلوب
[3194/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد معرفة نظام إدارة الرواتب؟
[3195/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف مكفوف اليد للعلاوة الدورية
[3196/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: في الاله الحاسبة الخاصة ببرنامج نطاقات المطور هل

[3197/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية نقل العسكري إلى وظيفة مدنية؟
[3198/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي الحقوق العامة في عقد العمل؟
[3199/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | ما طريقة يعامل الموظف المتدرب في الداخل أو الخارج في حالة إصابته بمرض وحصوله على
[3200/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي شروط وضوابط الإجازات للعامل؟
Checkpoint saved: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\retrieval_evaluation_detailed_results_checkpoint.csv
[3201/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى امكانية صرف مكافأة نهاية الخدمة المنصوص ع

[3202/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | في أي حالة ينتهي عقد العمل؟
[3203/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: موظف منح إجازة عادية بعد عطلة أحد العيدين مباشرة
[3204/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | ما طريقة يمكن تصحيح فرع المنشأة الذي يعمل فيها العامل ونقله إلى الفرع الصحيح؟
[3205/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماذا يحتوي عقد العمل؟
[3206/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | ما طريقة يتم التحقق من استلام العامل للأجر الذي سيتم التنفيذ عليه في عقد العمل ا
[3207/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد معرفة عدد أيام الإجازة بحالة زواج العامل؟

[3208/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد معرفة الحسابات التي يمكنني تفعيلها للموظفين للتعديل في حساب مدد الخاص بنظام
[3209/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي اشتراطات فترة التجربة؟
[3210/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد معرفة ما إذا كان النسخة العربية وغير العربية متطابقة من حيث الخدمات والوظائ
[3211/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | ما طريقة يتم الاستفادة من خدمة التنقل الوظيفي للعمال الوافدين بين المنشآت؟
[3212/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد معرفة أنواع الشكاوى التي يمكن أن يقدمها الموظف على صاحب العمل؟
[3213/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | هل مسموح نظاماً لصاحب العمل تشغيل المرأة العاملة بعد الوضع بمدة أقل من 6 أسابيع؟

[3214/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد معرفة ما إذا كان هناك لائحة وقانون يحمي الأطفال من العنف الأسري؟
[3215/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | ما طريقةية تعويض العامل المعين على بند الأجور عن رصيده من الاجازات العادية عند ا
[3216/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: موظف مددت خدمته لمدة سنتين بعد بلوغه السن النظام
[3217/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | هل يستطيع نقل العمالة داخل الكيان الواحد؟
[3218/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد معرفة ما إذا كان تغطي الوثيقة النفقات الطبية اللازمة لعلاج العامل المنزلي ب
[3219/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | هل يستطيع إلغاء التأشيرة المصدرة من مساند؟

[3220/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف الذي يشغل وظيفة خاضعة لنظا
[3221/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد معرفة ما إذا كان يحسم من راتب الموظف أيام غيابه عن العمل نتيجة مثوله أمام ا
[3222/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: موظف بعد احالته على التقاعد لبلوغ السن النظامية
[3223/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | هل يستطيع تعديل المهنة بعد تطبيق المبادرة؟
[3224/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد معرفة ما إذا كان يستحق الموظف التعويض عن إجازته العادية إذا استقال قبل إكما

[3225/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | ما طريقة يمكن الاستفادة من الخدمة؟
[3226/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد معرفة فترة الراحة اليومية للرضاعة؟
[3227/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | في أي حالة يتاح تجديد رخصة العمل؟
[3228/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | ما طريقة يتم حماية حقوق العامل؟
[3229/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف المتدرب لمكافآت وبدلات الت
[3230/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد معرفة ما إذا كان يحسب من عمره أقل من 18 سنة ضمن نسبة التوطين؟
[3231/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | أريد معرفة شروط أهلية العامل الوافد للاستفادة من خدمة التنقل الوظيفي؟

[3232/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | كم مدة فترة التجربة في نظام العمل السعودي؟
[3233/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | هل يجوز وضع العامل تحت التجربة أكثر من مرة لدى نفس صاحب العمل؟
[3234/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | ما الحد الأقصى لساعات العمل اليومية في نظام العمل؟
[3235/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | ما الحد الأقصى لساعات العمل الأسبوعية؟
[3236/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | هل تختلف ساعات العمل في شهر رمضان؟
[3237/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | ما مدة الإجازة السنوية المستحقة للعامل؟
[3238/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | متى تزيد الإجازة السنوية إلى ثلاثين يومًا؟
[3239/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | هل يستحق العامل أجرًا عن أيام الإجازة غير المستخدمة عند انتهاء العمل؟

[3240/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | هل يستحق العامل إجازة عند الزواج أو وفاة أحد الأقارب؟
[3241/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | هل للعامل الحق في إجازة مرضية؟
[3242/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | ما حالات انتهاء عقد العمل؟
[3243/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | ما مدة الإشعار عند إنهاء العقد غير محدد المدة؟
[3244/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | متى يستحق العامل تعويضًا عند إنهاء العقد لسبب غير مشروع؟
[3245/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | متى يجوز لصاحب العمل إنهاء العقد دون مكافأة أو تعويض؟
[3246/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | متى يجوز للعامل ترك العمل دون إشعار مع احتفاظه بحقوقه؟
[3247/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | متى يستحق العامل مكافأة نهاية الخدمة؟

[3248/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | هل يحق لصاحب العمل نقل العامل من مكان عمله الأصلي؟
[3249/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | ما المقصود بعقد العمل في نظام العمل؟
[3250/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | كيف يتم دفع أجر العامل؟
Checkpoint saved: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\retrieval_evaluation_detailed_results_checkpoint.csv
[3251/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | ما واجبات صاحب العمل تجاه العامل؟
[3252/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | ما التزامات العامل في نظام العمل؟
[3253/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | ما الحد الأقصى لساعات العمل الإضافية وكيف تُحتسب؟

[3254/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | ما أحكام السلامة والصحة المهنية في بيئة العمل؟
[3255/3410] Exp 21/22 | hybrid | fixed_size | bge_m3 | ما حقوق العاملة في إجازة الوضع؟
====================================================================================================
Experiment 22/22: {'chunking_strategy': 'fixed_size', 'embedding_model': 'bge_m3', 'retriever': 'hybrid_reranker', 'alpha': 0.8}
====================================================================================================
[3256/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | ما طريقة يمكنني إلغاء أو تعديل طلب تغيير المهنة؟

[3257/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد معرفة الطريقة المتبعة لتسديد قسط التأمين؟

[3258/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | ما طريقةية معاملة محرم الموظفة عند مرافقتها أثناء ابتعاثها للدراسة أو التدريب أو

[3259/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي أهداف برنامج نطاقات المطور؟

[3260/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية الجمع بين بدل المهنة المنصوص عليه

[3261/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: موظف أحيل للتحقيق أثناء إجراء المفاضلة لغرض التر

[3262/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | ما طريقة يتم احتساب أجر الساعات الإضافية؟

[3263/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | هل مسموح تعيين العمال بصفة مؤقتة طبقاً للائحة المعينين على بند الأجور؟

[3264/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | هل يستطيع احتساب أيام المراجعة للمستشفيات داخل مقر العمل أو خارجه إجازة مرضية أو

[3265/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: اعرف حقوق العمال؟

[3266/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: في حال تم رصد مخالفات في ملف الأجور، أين أجد تفا

[3267/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما المقصود من كون عمال المستشفيات ضمن المساعدين

[3268/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: موظف قدم للرياض للالتحاق بدورة تدريبية وبعد انته

[3269/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد معرفة ما إذا كان يخصم بدل المواصلات من راتب الإجازة السنوية؟

[3270/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: موظف استقال من وظيفة بالمرتبة الرابعة ومن ثم عاد

[3271/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد معرفة عقد العمل؟

[3272/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد معرفة ما إذا كان تحسم رواتب العطل الرسمية والأعياد إذا سبقها غياب ولحقها غي

[3273/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد معرفة العمل المرن؟

[3274/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى جواز منح الموظف المنقول بترقية الدرجة الإ

[3275/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: في حالة غياب الموظف عن العمل وإيقاع عقوبة تأديبي

[3276/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | ما طريقة يتم طلب المدرب الاختياري قبل التقدم بطلب شهادة "مواءمة"؟

[3277/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | هل مسموح نظاماً للعامل الانتقال من منشأة في النطاق الأحمر بدون إذن صاحب العمل إل

[3278/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى امكانية ابتعاث أوايفاد العامل المعين على

[3279/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | هل مسموح منح الموظف أثناء فترة التجربة إجازة استثنائية؟

[3280/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى إلزام الموظف بالعمل خارج وقت الدوام، وهل

[3281/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى انطباق المزايا المالية التي تصرف للمشاركي

[3282/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد معرفة ما إذا كان أستطيع رفع ملفات حماية الأجور عبر موقع وزارة الموارد البشر

[3283/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد معرفة الرسوم المطلوبة من المنشآت في برنامج "مواءمة"؟

[3284/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد معرفة ما إذا كان يتم إضافة البيانات التي تملكها الوزارة في الأصل للحقول الم

[3285/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي الحقوق والواجبات العامة للمرأة العاملة؟

[3286/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد معرفة خدمة نقل الموظفين؟

[3287/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد معرفة ما إذا كان ينطبق الشرط الجزائي على العامل أو صاحب العمل؟

[3288/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد معرفة شروط الخدمة؟

[3289/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد معرفة خدمات مبادرة تحسين العلاقة التعاقدية؟

[3290/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: إذا التحق الموظف بالتدريب أثناء إجازته الاستثنائ

[3291/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد معرفة ما إذا كان بإمكاني تعيين أي موظف لدي وإعطاءه صلاحية مفوض رواتب أو مدق

[3292/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف المتدرب الذي انقطع أثناء ف

[3293/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد معرفة ما إذا كان يطالب المستخدم المثبت على وظيفة مشمولة بسلم رواتب الموظفين

[3294/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | ما طريقة أعرف ما إذا كانت منشأتي ملزمة بتطبيق برنامج حماية الأجور؟

[3295/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد معرفة برنامج نطاقات؟ وكيف يحسن بيئة العمل للسعوديين؟

[3296/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: لماذا توجد رسوم مالية على برنامج "مواءمة"؟ وهل ت

[3297/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | هل مسموح نقل العامل المعين على بند الأجور إلى إحدى الجهات الحكومية مع الاحتفاظ ب

[3298/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد معرفة ما إذا كان يحسب برنامج نطاقات من لديهم وظائف رسمية في الحكومة ودوام ج

[3299/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي آلية الترشيح للمرشحين؟

[3300/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | ما طريقة يمكن للمستفيد (المؤمن له) معرفة اسم شركة التأمين التابع لها؟

Checkpoint saved: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\retrieval_evaluation_detailed_results_checkpoint.csv
[3301/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد معرفة إجراءات الانتقال خلال السنة الأولى في الحالات الاستثنائية؟

[3302/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد معرفة ما إذا كان تمكن البوابة والانظمة التابعة لها المستخدم من تخصيص الخدما

[3303/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد معرفة ما إذا كان بإمكان أي موظف في منشأتي أن يسجل في منصة مُدد ويقوم برفع م

[3304/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى أحقية المعين على بند الأجور المكلف بالعمل

[3305/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد معرفة ما إذا كان تسري على شاغلي الوظائف المؤقتة القواعد الواردة في نظام الخ

[3306/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: كتابة العقد؟

[3307/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد معرفة ما إذا كان يترتب على العامل الوافد دفع أي رسوم حكومية (رخصة العمل – ا

[3308/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: موظف منح إجازة عادية تنتهي مع ابتداء عطلة أحد ال

[3309/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | هل يستطيع للمستخدمين الوصول إلى قائمة عملياته او معاملاته السابقة في البوابة؟

[3310/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي خدمة الخروج النهائي؟

[3311/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما الفرق بين المهنة والمسمى الوظيفي؟

[3312/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | ما طريقة يمكن التوفيق بين نصي المادتين (132) و (147) من اللائحة التنفيذية للموار

[3313/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | هل يستطيع أن يتغير انطاق المنشأة دون تغيير في عدد العمالة خلال السنوات القادمة؟

[3314/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: لماذا يتوجب على المنشأة القيام بالتقيّيم الذاتي؟

[3315/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | هل مسموح انهاء عقد العمل بسبب إعادة الهيكلة أو الظروف المالية للمنشأة؟

[3316/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد معرفة ما إذا كان تشمل إجازة أداء الامتحان الدراسي من يؤدي الامتحان خارج الم

[3317/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: موظف قررت الهيئة الطبية العامة معالجته في الداخل

[3318/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد معرفة ما إذا كان الخدمة تتيح تحديث بيانات العامل؟

[3319/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي الآلية لرفع نسب نطاقات تدريجيا؟ وكم هي المد

[3320/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | هل يستطيع حفظ معاملة لخدمة معينة تم بدؤها من خلال البوابة والوصول إليها لاحقًا؟

[3321/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية احتفاظ العامل المعين على بند الأج

[3322/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: موظف فصل من الخدمة بناءً على حكم نهائي من ديوان

[3323/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد معرفة ما إذا كان يشمل برنامج نطاقات المستثمر الأجنبي؟

[3324/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: الفئات المشمولة بقرار الالزام بالتأمين على عقد ا

[3325/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | هل يستطيع تفعيل بند التنافسية في عقد العمل؟

[3326/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي الإجازات المستحقة للمرأة العاملة؟

[3327/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد معرفة الاجراء الذي سيتم تطبيقه في حال عدم التزام المنشأة بنسب نطاقات؟

[3328/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى جواز إجبار الموظف على التمتع بإجازاته الع

[3329/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد معرفة الخدمات المقدمة في نظام مُدد لإدارة الرواتب؟

[3330/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد معرفة ما إذا كان تمكن البوابة والانظمة التابعة لها المستخدم من تعديل بيانات

[3331/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد معرفة المقصود بنصف صافي راتب الموظف مكفوف اليد ومن في حكمه وفقاً للمادة (19

[3332/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف المنتدب من خارج المملكة إل

[3333/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | ما طريقة أقدم شكوى على أحد الموظفين في مكاتب العمل؟ وما الحل إذا لم تتم الإفادة

[3334/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي آلية احتساب نسب التوطين بعد تطبيق نطاقات ال

[3335/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: مدة عمل عقد العامل السعودي؟

[3336/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | ما طريقة يعامل العامل غير السعودي المعين على بند الأجور من حيث بدل النقل بعد صدو

[3337/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما خطوات تنفيذ الخدمة؟

[3338/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية صرف بدل التفرغ للطبيبات خلال إجاز

[3339/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد معرفة ما إذا كان تسري أحكام لائحة المعينين على بند الأجور الصادرة بقرار مجل

[3340/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد معرفة ما إذا كان الخدمة متاحة للعامل؟

[3341/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى صرف بدل تعيين لمن يتم تعيينه بوظيفة خاضعة

[3342/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماذا يقصد ببرنامج نطاقات المطور؟

[3343/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد معرفة ما إذا كان يجب ان يكون العامل مسجل على منشاة؟

[3344/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى نظامية منح الموظف بعد تعيينه وفقاً لنظام

[3345/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية صرف بدل الترحيل المنصوص عليه بالم

[3346/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى استفادة العامل المعين على بند الأجور من م

[3347/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | ما طريقة يمكنني معرفة إذا كنت مؤهل لتوثيق عقدي مع العامل/ة؟

[3348/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد معرفة ما إذا كان تحتسب مدة الإجازة الاستثنائية لغرض إكمال مدة السنة المطلوب

[3349/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد معرفة نظام إدارة الرواتب؟

[3350/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف مكفوف اليد للعلاوة الدورية

Checkpoint saved: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\retrieval_evaluation_detailed_results_checkpoint.csv
[3351/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: في الاله الحاسبة الخاصة ببرنامج نطاقات المطور هل

[3352/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى إمكانية نقل العسكري إلى وظيفة مدنية؟

[3353/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي الحقوق العامة في عقد العمل؟

[3354/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | ما طريقة يعامل الموظف المتدرب في الداخل أو الخارج في حالة إصابته بمرض وحصوله على

[3355/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي شروط وضوابط الإجازات للعامل؟

[3356/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى امكانية صرف مكافأة نهاية الخدمة المنصوص ع

[3357/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | في أي حالة ينتهي عقد العمل؟

[3358/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: موظف منح إجازة عادية بعد عطلة أحد العيدين مباشرة

[3359/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | ما طريقة يمكن تصحيح فرع المنشأة الذي يعمل فيها العامل ونقله إلى الفرع الصحيح؟

[3360/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماذا يحتوي عقد العمل؟

[3361/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | ما طريقة يتم التحقق من استلام العامل للأجر الذي سيتم التنفيذ عليه في عقد العمل ا

[3362/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد معرفة عدد أيام الإجازة بحالة زواج العامل؟

[3363/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد معرفة الحسابات التي يمكنني تفعيلها للموظفين للتعديل في حساب مدد الخاص بنظام

[3364/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ماهي اشتراطات فترة التجربة؟

[3365/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد معرفة ما إذا كان النسخة العربية وغير العربية متطابقة من حيث الخدمات والوظائ

[3366/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | ما طريقة يتم الاستفادة من خدمة التنقل الوظيفي للعمال الوافدين بين المنشآت؟

[3367/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد معرفة أنواع الشكاوى التي يمكن أن يقدمها الموظف على صاحب العمل؟

[3368/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | هل مسموح نظاماً لصاحب العمل تشغيل المرأة العاملة بعد الوضع بمدة أقل من 6 أسابيع؟

[3369/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد معرفة ما إذا كان هناك لائحة وقانون يحمي الأطفال من العنف الأسري؟

[3370/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | ما طريقةية تعويض العامل المعين على بند الأجور عن رصيده من الاجازات العادية عند ا

[3371/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: موظف مددت خدمته لمدة سنتين بعد بلوغه السن النظام

[3372/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | هل يستطيع نقل العمالة داخل الكيان الواحد؟

[3373/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد معرفة ما إذا كان تغطي الوثيقة النفقات الطبية اللازمة لعلاج العامل المنزلي ب

[3374/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | هل يستطيع إلغاء التأشيرة المصدرة من مساند؟

[3375/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف الذي يشغل وظيفة خاضعة لنظا

[3376/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد معرفة ما إذا كان يحسم من راتب الموظف أيام غيابه عن العمل نتيجة مثوله أمام ا

[3377/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: موظف بعد احالته على التقاعد لبلوغ السن النظامية

[3378/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | هل يستطيع تعديل المهنة بعد تطبيق المبادرة؟

[3379/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد معرفة ما إذا كان يستحق الموظف التعويض عن إجازته العادية إذا استقال قبل إكما

[3380/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | ما طريقة يمكن الاستفادة من الخدمة؟

[3381/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد معرفة فترة الراحة اليومية للرضاعة؟

[3382/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | في أي حالة يتاح تجديد رخصة العمل؟

[3383/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | ما طريقة يتم حماية حقوق العامل؟

[3384/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد توضيح الحكم النظامي بخصوص: ما مدى استحقاق الموظف المتدرب لمكافآت وبدلات الت

[3385/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد معرفة ما إذا كان يحسب من عمره أقل من 18 سنة ضمن نسبة التوطين؟

[3386/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | أريد معرفة شروط أهلية العامل الوافد للاستفادة من خدمة التنقل الوظيفي؟

[3387/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | كم مدة فترة التجربة في نظام العمل السعودي؟

[3388/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | هل يجوز وضع العامل تحت التجربة أكثر من مرة لدى نفس صاحب العمل؟

[3389/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | ما الحد الأقصى لساعات العمل اليومية في نظام العمل؟

[3390/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | ما الحد الأقصى لساعات العمل الأسبوعية؟

[3391/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | هل تختلف ساعات العمل في شهر رمضان؟

[3392/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | ما مدة الإجازة السنوية المستحقة للعامل؟

[3393/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | متى تزيد الإجازة السنوية إلى ثلاثين يومًا؟

[3394/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | هل يستحق العامل أجرًا عن أيام الإجازة غير المستخدمة عند انتهاء العمل؟

[3395/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | هل يستحق العامل إجازة عند الزواج أو وفاة أحد الأقارب؟

[3396/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | هل للعامل الحق في إجازة مرضية؟

[3397/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | ما حالات انتهاء عقد العمل؟

[3398/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | ما مدة الإشعار عند إنهاء العقد غير محدد المدة؟

[3399/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | متى يستحق العامل تعويضًا عند إنهاء العقد لسبب غير مشروع؟

[3400/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | متى يجوز لصاحب العمل إنهاء العقد دون مكافأة أو تعويض؟

Checkpoint saved: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\retrieval_evaluation_detailed_results_checkpoint.csv
[3401/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | متى يجوز للعامل ترك العمل دون إشعار مع احتفاظه بحقوقه؟

[3402/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | متى يستحق العامل مكافأة نهاية الخدمة؟

[3403/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | هل يحق لصاحب العمل نقل العامل من مكان عمله الأصلي؟

[3404/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | ما المقصود بعقد العمل في نظام العمل؟

[3405/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | كيف يتم دفع أجر العامل؟

[3406/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | ما واجبات صاحب العمل تجاه العامل؟

[3407/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | ما التزامات العامل في نظام العمل؟

[3408/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | ما الحد الأقصى لساعات العمل الإضافية وكيف تُحتسب؟

[3409/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | ما أحكام السلامة والصحة المهنية في بيئة العمل؟

[3410/3410] Exp 22/22 | hybrid_reranker | fixed_size | bge_m3 | ما حقوق العاملة في إجازة الوضع؟

====================================================================================================
Detailed results shape: (3410, 26)
Saved CSV: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\retrieval_evaluation_detailed_results.csv
Saved XLSX: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\retrieval_evaluation_detailed_results.xlsx
====================================================================================================

<div dir="rtl" style="
    text-align:right;
    line-height:2;
    font-size:15px;
    font-family:Arial, Tahoma, sans-serif;
    background-color:#E2F0D9;
    border-right:5px solid #375623;
    padding:14px;
    margin:12px 0;
    border-radius:6px;
">

✅ <b>تم الانتهاء من تشغيل تجارب الاسترجاع الكاملة.</b><br>
تم حفظ النتائج التفصيلية في ملفات CSV و Excel.
اعرض الجداول الاحترافية في الخلية التالية فقط.

</div>

Stage 13 full retrieval experiments completed.

In [25]:
# =========================================================
# Stage 13B - Professional Retrieval Results Display
# عرض احترافي ومنظم لنتائج تجارب الاسترجاع
# =========================================================

from IPython.display import display, Markdown
import pandas as pd
import numpy as np
import re

# ---------------------------------------------------------
# 1) Safety Check
# ---------------------------------------------------------

if "retrieval_detail" not in globals():
    raise NameError("retrieval_detail غير موجود. شغّل Stage 13 أولًا.")

if "STAGE03_DIR" not in globals():
    raise NameError("STAGE03_DIR غير موجود. تأكد من تشغيل خلايا الإعدادات السابقة.")

# ---------------------------------------------------------
# 2) Helper Functions
# ---------------------------------------------------------

def short_text(text, max_len=130):
    text = str(text).replace("\n", " ").strip()
    text = re.sub(r"\s+", " ", text)
    return text[:max_len] + ("..." if len(text) > max_len else "")


def hide_index_safe(styler):
    try:
        return styler.hide(axis="index")
    except Exception:
        try:
            return styler.hide_index()
        except Exception:
            return styler


def apply_style_compatible(styler, func, subset):
    if hasattr(styler, "map"):
        return styler.map(func, subset=subset)
    return styler.applymap(func, subset=subset)


def color_retriever(val):
    val = str(val)

    if val == "bm25":
        return "background-color:#FFF2CC; color:#7F6000; font-weight:bold;"

    if val == "dense":
        return "background-color:#EAF3F8; color:#1F4E78; font-weight:bold;"

    if val == "hybrid":
        return "background-color:#E2F0D9; color:#375623; font-weight:bold;"

    if val == "hybrid_reranker":
        return "background-color:#D9EAD3; color:#274E13; font-weight:bold;"

    return ""


def color_hit(val):
    try:
        val = int(float(val))
    except Exception:
        return ""

    if val == 1:
        return "background-color:#E2F0D9; color:#375623; font-weight:bold;"

    return "background-color:#FCE4D6; color:#9C0006; font-weight:bold;"


def color_eval_type(val):
    val = str(val)

    if val == "legal_article_retrieval":
        return "background-color:#E2F0D9; color:#375623; font-weight:bold;"

    if val == "faq_retrieval":
        return "background-color:#FFF2CC; color:#7F6000; font-weight:bold;"

    if val == "out_of_scope":
        return "background-color:#FCE4D6; color:#9C0006; font-weight:bold;"

    if val == "small_talk":
        return "background-color:#EAF3F8; color:#1F4E78; font-weight:bold;"

    return ""


def professional_table(df, caption="", width="100%", font_size="12px"):
    styler = (
        df.style
        .set_caption(caption)
        .set_table_styles([
            {
                "selector": "caption",
                "props": [
                    ("caption-side", "top"),
                    ("font-size", "17px"),
                    ("font-weight", "bold"),
                    ("color", "#1F4E78"),
                    ("text-align", "center"),
                    ("padding", "10px")
                ]
            },
            {
                "selector": "th",
                "props": [
                    ("background-color", "#1F4E78"),
                    ("color", "white"),
                    ("font-weight", "bold"),
                    ("text-align", "center"),
                    ("border", "1px solid #D9E2F3"),
                    ("padding", "8px"),
                    ("white-space", "normal")
                ]
            },
            {
                "selector": "td",
                "props": [
                    ("text-align", "center"),
                    ("border", "1px solid #D9E2F3"),
                    ("padding", "7px"),
                    ("vertical-align", "middle"),
                    ("white-space", "normal")
                ]
            },
            {
                "selector": "tbody tr:nth-child(even)",
                "props": [("background-color", "#F8FBFD")]
            },
            {
                "selector": "tbody tr:nth-child(odd)",
                "props": [("background-color", "#FFFFFF")]
            },
            {
                "selector": "table",
                "props": [
                    ("border-collapse", "collapse"),
                    ("width", width),
                    ("font-family", "Arial, Tahoma, sans-serif"),
                    ("font-size", font_size),
                    ("table-layout", "fixed"),
                    ("margin", "12px 0")
                ]
            }
        ])
    )

    return hide_index_safe(styler)

# ---------------------------------------------------------
# 3) Explanation Box
# ---------------------------------------------------------

display(Markdown("""
<div dir="rtl" style="
    text-align:right;
    line-height:2;
    font-size:15px;
    font-family:Arial, Tahoma, sans-serif;
    background-color:#F8FBFD;
    border-right:5px solid #1F4E78;
    padding:14px;
    margin:12px 0;
    border-radius:6px;
">

<h3 style="color:#1F4E78; margin-top:0;">
Stage 13B — Professional Retrieval Results Display
</h3>

<p>
هذه الخلية تعرض نتائج تجارب الاسترجاع المخزنة في <code>retrieval_detail</code> دون إعادة تشغيل التجارب.
تم تقسيم العرض إلى ملخص عام، مقارنة حسب نوع السؤال، معاينة تفصيلية، وفحص خاص لأسئلة فترة التجربة بعد تصحيح رقم المادة.
</p>

</div>
"""))

# ---------------------------------------------------------
# 4) Summary by Retrieval Configuration
# ---------------------------------------------------------

summary_by_retriever = (
    retrieval_detail
    .groupby(
        [
            "chunking_strategy",
            "embedding_model",
            "retriever",
            "alpha"
        ],
        dropna=False
    )
    .agg(
        questions=("question", "count"),
        recall_at_1=("hit_at_1", "mean"),
        recall_at_3=("hit_at_3", "mean"),
        recall_at_5=("hit_at_5", "mean"),
        mrr=("rr", "mean"),
        ndcg_at_5=("ndcg_at_5", "mean"),
        avg_latency_sec=("latency_sec", "mean")
    )
    .reset_index()
)

summary_by_retriever = summary_by_retriever.sort_values(
    by=["recall_at_5", "mrr", "ndcg_at_5", "recall_at_1"],
    ascending=False
).reset_index(drop=True)

summary_display = summary_by_retriever.copy()
summary_display["alpha"] = summary_display["alpha"].fillna("N/A")

for col in ["recall_at_1", "recall_at_3", "recall_at_5"]:
    summary_display[col] = (summary_display[col] * 100).round(2).astype(str) + "%"

for col in ["mrr", "ndcg_at_5", "avg_latency_sec"]:
    summary_display[col] = pd.to_numeric(summary_display[col], errors="coerce").round(4)

summary_style = professional_table(
    summary_display,
    caption="Table 13.1 — Retrieval Performance Summary by Configuration",
    width="100%",
    font_size="12px"
)

summary_style = apply_style_compatible(
    summary_style,
    color_retriever,
    subset=["retriever"]
)

display(summary_style)

# ---------------------------------------------------------
# 5) Summary by Evaluation Type
# ---------------------------------------------------------

summary_by_type = (
    retrieval_detail
    .groupby(
        [
            "eval_type",
            "chunking_strategy",
            "embedding_model",
            "retriever"
        ],
        dropna=False
    )
    .agg(
        questions=("question", "count"),
        recall_at_1=("hit_at_1", "mean"),
        recall_at_5=("hit_at_5", "mean"),
        mrr=("rr", "mean"),
        ndcg_at_5=("ndcg_at_5", "mean"),
        avg_latency_sec=("latency_sec", "mean")
    )
    .reset_index()
)

summary_by_type = summary_by_type.sort_values(
    by=["eval_type", "recall_at_5", "mrr"],
    ascending=[True, False, False]
).reset_index(drop=True)

type_display = summary_by_type.copy()

for col in ["recall_at_1", "recall_at_5"]:
    type_display[col] = (type_display[col] * 100).round(2).astype(str) + "%"

for col in ["mrr", "ndcg_at_5", "avg_latency_sec"]:
    type_display[col] = pd.to_numeric(type_display[col], errors="coerce").round(4)

type_style = professional_table(
    type_display,
    caption="Table 13.2 — Retrieval Performance by Evaluation Type",
    width="100%",
    font_size="11.5px"
)

type_style = apply_style_compatible(
    type_style,
    color_eval_type,
    subset=["eval_type"]
)

type_style = apply_style_compatible(
    type_style,
    color_retriever,
    subset=["retriever"]
)

display(type_style)

# ---------------------------------------------------------
# 6) Detailed Results Preview
# ---------------------------------------------------------

detail_cols = [
    "question",
    "eval_type",
    "gold_article_numbers",
    "chunking_strategy",
    "embedding_model",
    "retriever",
    "alpha",
    "hit_at_1",
    "hit_at_3",
    "hit_at_5",
    "top1_article_number",
    "top5_article_numbers",
    "latency_sec"
]

detail_cols = [c for c in detail_cols if c in retrieval_detail.columns]

detail_display = retrieval_detail[detail_cols].copy()

if "question" in detail_display.columns:
    detail_display["question"] = detail_display["question"].apply(lambda x: short_text(x, 130))

if "alpha" in detail_display.columns:
    detail_display["alpha"] = detail_display["alpha"].fillna("N/A")

if "latency_sec" in detail_display.columns:
    detail_display["latency_sec"] = pd.to_numeric(
        detail_display["latency_sec"],
        errors="coerce"
    ).round(4)

detail_display = detail_display.head(30)

detail_style = professional_table(
    detail_display,
    caption="Table 13.3 — Detailed Retrieval Results Preview",
    width="100%",
    font_size="11.2px"
)

if "retriever" in detail_display.columns:
    detail_style = apply_style_compatible(
        detail_style,
        color_retriever,
        subset=["retriever"]
    )

if "eval_type" in detail_display.columns:
    detail_style = apply_style_compatible(
        detail_style,
        color_eval_type,
        subset=["eval_type"]
    )

for col in ["hit_at_1", "hit_at_3", "hit_at_5"]:
    if col in detail_display.columns:
        detail_style = apply_style_compatible(
            detail_style,
            color_hit,
            subset=[col]
        )

if "question" in detail_display.columns:
    detail_style = detail_style.set_properties(
        subset=["question"],
        **{
            "text-align": "right",
            "direction": "rtl",
            "line-height": "1.7"
        }
    )

display(detail_style)

# ---------------------------------------------------------
# 7) Probation Questions Diagnostic
# ---------------------------------------------------------

check_terms = [
    "كم مدة فترة التجربة",
    "وضع العامل تحت التجربة أكثر من مرة"
]

probation_rows = retrieval_detail[
    retrieval_detail["question"].astype(str).apply(
        lambda q: any(term in q for term in check_terms)
    )
].copy()

if len(probation_rows) > 0:

    probation_cols = [
        "question",
        "gold_article_numbers",
        "chunking_strategy",
        "embedding_model",
        "retriever",
        "alpha",
        "top1_article_number",
        "top5_article_numbers",
        "hit_at_1",
        "hit_at_5",
        "latency_sec"
    ]

    probation_cols = [c for c in probation_cols if c in probation_rows.columns]

    probation_display = probation_rows[probation_cols].copy()

    probation_display["question"] = probation_display["question"].apply(
        lambda x: short_text(x, 140)
    )

    if "alpha" in probation_display.columns:
        probation_display["alpha"] = probation_display["alpha"].fillna("N/A")

    if "latency_sec" in probation_display.columns:
        probation_display["latency_sec"] = pd.to_numeric(
            probation_display["latency_sec"],
            errors="coerce"
        ).round(4)

    probation_style = professional_table(
        probation_display,
        caption="Table 13.4 — Probation Questions Diagnostic After Gold Correction",
        width="100%",
        font_size="11.2px"
    )

    if "retriever" in probation_display.columns:
        probation_style = apply_style_compatible(
            probation_style,
            color_retriever,
            subset=["retriever"]
        )

    for col in ["hit_at_1", "hit_at_5"]:
        if col in probation_display.columns:
            probation_style = apply_style_compatible(
                probation_style,
                color_hit,
                subset=[col]
            )

    probation_style = probation_style.set_properties(
        subset=["question"],
        **{
            "text-align": "right",
            "direction": "rtl",
            "line-height": "1.7"
        }
    )

    display(probation_style)

else:
    display(Markdown("""
<div dir="rtl" style="
    text-align:right;
    line-height:2;
    font-size:15px;
    font-family:Arial, Tahoma, sans-serif;
    background-color:#FFF2CC;
    border-right:5px solid #BF9000;
    padding:14px;
    margin:12px 0;
    border-radius:6px;
">
لم يتم العثور على أسئلة فترة التجربة داخل <code>retrieval_detail</code>.
</div>
"""))

# ---------------------------------------------------------
# 8) Save Summary Outputs
# ---------------------------------------------------------

summary_csv_path = STAGE03_DIR / "retrieval_evaluation_summary_professional.csv"
summary_xlsx_path = STAGE03_DIR / "retrieval_evaluation_summary_professional.xlsx"

summary_by_retriever.to_csv(
    summary_csv_path,
    index=False,
    encoding="utf-8-sig"
)

summary_by_retriever.to_excel(
    summary_xlsx_path,
    index=False
)

# ---------------------------------------------------------
# 9) Final Interpretation
# ---------------------------------------------------------

best_row = summary_by_retriever.iloc[0]

display(Markdown(f"""
<div dir="rtl" style="
    text-align:right;
    line-height:2;
    font-size:15px;
    font-family:Arial, Tahoma, sans-serif;
    background-color:#E2F0D9;
    border-right:5px solid #375623;
    padding:14px;
    margin:12px 0;
    border-radius:6px;
">

<h3 style="color:#375623; margin-top:0;">
أفضل إعداد استرجاع حسب نتائج هذه التجربة
</h3>

<ul>
<li><b>Chunking Strategy:</b> <code>{best_row['chunking_strategy']}</code></li>
<li><b>Embedding Model:</b> <code>{best_row['embedding_model']}</code></li>
<li><b>Retriever:</b> <code>{best_row['retriever']}</code></li>
<li><b>Alpha:</b> <code>{best_row['alpha']}</code></li>
<li><b>Recall@5:</b> {round(best_row['recall_at_5'] * 100, 2)}%</li>
<li><b>MRR:</b> {round(best_row['mrr'], 4)}</li>
<li><b>nDCG@5:</b> {round(best_row['ndcg_at_5'], 4)}</li>
<li><b>Average Latency:</b> {round(best_row['avg_latency_sec'], 4)} sec</li>
</ul>

<p>
تم حفظ ملخص النتائج الاحترافي في:
<br>
<code>{summary_csv_path}</code>
<br>
<code>{summary_xlsx_path}</code>
</p>

</div>
"""))

print("Professional Stage 13 display completed.")

<div dir="rtl" style="
    text-align:right;
    line-height:2;
    font-size:15px;
    font-family:Arial, Tahoma, sans-serif;
    background-color:#F8FBFD;
    border-right:5px solid #1F4E78;
    padding:14px;
    margin:12px 0;
    border-radius:6px;
">

<h3 style="color:#1F4E78; margin-top:0;">
Stage 13B — Professional Retrieval Results Display
</h3>

<p>
هذه الخلية تعرض نتائج تجارب الاسترجاع المخزنة في <code>retrieval_detail</code> دون إعادة تشغيل التجارب.
تم تقسيم العرض إلى ملخص عام، مقارنة حسب نوع السؤال، معاينة تفصيلية، وفحص خاص لأسئلة فترة التجربة بعد تصحيح رقم المادة.
</p>

</div>

<div dir="rtl" style="
    text-align:right;
    line-height:2;
    font-size:15px;
    font-family:Arial, Tahoma, sans-serif;
    background-color:#E2F0D9;
    border-right:5px solid #375623;
    padding:14px;
    margin:12px 0;
    border-radius:6px;
">

<h3 style="color:#375623; margin-top:0;">
أفضل إعداد استرجاع حسب نتائج هذه التجربة
</h3>

<ul>
<li><b>Chunking Strategy:</b> <code>structural</code></li>
<li><b>Embedding Model:</b> <code>e5_large</code></li>
<li><b>Retriever:</b> <code>hybrid_reranker</code></li>
<li><b>Alpha:</b> <code>0.8</code></li>
<li><b>Recall@5:</b> 99.35%</li>
<li><b>MRR:</b> 0.9508</li>
<li><b>nDCG@5:</b> 0.9621</li>
<li><b>Average Latency:</b> 0.3361 sec</li>
</ul>

<p>
تم حفظ ملخص النتائج الاحترافي في:
<br>
<code>C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\retrieval_evaluation_summary_professional.csv</code>
<br>
<code>C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\retrieval_evaluation_summary_professional.xlsx</code>
</p>

</div>

Professional Stage 13 display completed.

In [26]:
# =========================================================
# Check Retrieval Detail Before Summary - Professional View
# فحص نتائج الاسترجاع التفصيلية قبل بناء الملخص
# =========================================================

import pandas as pd
from IPython.display import display, HTML

# ---------------------------------------------------------
# 1) Professional display helper
# ---------------------------------------------------------

def display_professional_table(df, title="Table", max_rows=10):
    """
    Display a wide, scrollable, professional-looking DataFrame in Jupyter.
    """
    if df is None or len(df) == 0:
        display(HTML(f"""
        <div style="
            direction: rtl;
            text-align: right;
            font-family: Tahoma, Arial;
            border: 1px solid #f5c2c7;
            background: #f8d7da;
            color: #842029;
            padding: 14px;
            border-radius: 8px;
            margin: 10px 0;
        ">
            <b>{title}</b><br>
            لا توجد بيانات لعرضها.
        </div>
        """))
        return

    view_df = df.head(max_rows).copy()

    html_table = view_df.to_html(
        index=False,
        escape=True,
        border=0
    )

    display(HTML(f"""
    <div style="
        direction: rtl;
        text-align: right;
        font-family: Tahoma, Arial;
        margin: 18px 0 8px 0;
        font-size: 18px;
        font-weight: 700;
        color: #17324d;
    ">
        {title}
    </div>

    <div style="
        width: 100%;
        overflow-x: auto;
        overflow-y: hidden;
        border: 1px solid #d9e2ec;
        border-radius: 10px;
        background: #ffffff;
        padding: 0;
        margin-bottom: 20px;
    ">
        <style>
            .professional-wide-table table {{
                border-collapse: collapse;
                width: max-content;
                min-width: 1400px;
                font-family: Tahoma, Arial, sans-serif;
                font-size: 13px;
            }}

            .professional-wide-table th {{
                background-color: #1f4e79;
                color: white;
                text-align: center;
                padding: 10px 12px;
                border: 1px solid #d9e2ec;
                white-space: nowrap;
                font-weight: 700;
            }}

            .professional-wide-table td {{
                padding: 9px 12px;
                border: 1px solid #e5eaf0;
                vertical-align: top;
                white-space: normal;
                max-width: 420px;
                word-wrap: break-word;
                text-align: left;
                direction: ltr;
            }}

            .professional-wide-table tr:nth-child(even) {{
                background-color: #f8fbfd;
            }}

            .professional-wide-table tr:hover {{
                background-color: #eef6ff;
            }}

            .professional-wide-table td:nth-child(3),
            .professional-wide-table td:nth-child(4),
            .professional-wide-table td:nth-child(5) {{
                direction: rtl;
                text-align: right;
                min-width: 300px;
            }}
        </style>

        <div class="professional-wide-table">
            {html_table}
        </div>
    </div>
    """))


def display_status_card(title, message, status="info"):
    """
    Display a professional status card.
    """
    colors = {
        "success": ("#d1e7dd", "#0f5132", "#badbcc"),
        "warning": ("#fff3cd", "#664d03", "#ffecb5"),
        "danger":  ("#f8d7da", "#842029", "#f5c2c7"),
        "info":    ("#cff4fc", "#055160", "#b6effb"),
    }

    bg, color, border = colors.get(status, colors["info"])

    display(HTML(f"""
    <div style="
        direction: rtl;
        text-align: right;
        font-family: Tahoma, Arial;
        background: {bg};
        color: {color};
        border: 1px solid {border};
        padding: 14px 16px;
        border-radius: 10px;
        margin: 12px 0;
        line-height: 1.8;
        font-size: 15px;
    ">
        <b>{title}</b><br>
        {message}
    </div>
    """))


# ---------------------------------------------------------
# 2) Check retrieval_detail
# ---------------------------------------------------------

if "retrieval_detail" not in globals():
    display_status_card(
        title="retrieval_detail غير موجود",
        message="يجب تشغيل خلية Stage 13 - Run Retrieval Experiments أولاً قبل بناء الملخص.",
        status="danger"
    )

else:
    display_status_card(
        title="تم العثور على retrieval_detail",
        message="تم العثور على نتائج الاسترجاع التفصيلية، ويمكن الآن مراجعتها قبل بناء الجداول النهائية.",
        status="success"
    )

    # -----------------------------------------------------
    # 3) Summary cards
    # -----------------------------------------------------

    total_rows = len(retrieval_detail)
    total_cols = retrieval_detail.shape[1]

    unique_questions = (
        retrieval_detail["eval_id"].nunique()
        if "eval_id" in retrieval_detail.columns
        else "N/A"
    )

    unique_configs = (
        retrieval_detail["experiment_name"].nunique()
        if "experiment_name" in retrieval_detail.columns
        else (
            retrieval_detail["retriever_name"].nunique()
            if "retriever_name" in retrieval_detail.columns
            else "N/A"
        )
    )

    display(HTML(f"""
    <div style="
        display: flex;
        gap: 14px;
        flex-wrap: wrap;
        margin: 14px 0 22px 0;
        font-family: Tahoma, Arial;
        direction: rtl;
    ">
        <div style="flex:1; min-width:180px; background:#f8fbfd; border:1px solid #d9e2ec; border-radius:10px; padding:14px; text-align:center;">
            <div style="font-size:13px; color:#52616b;">عدد الصفوف التفصيلية</div>
            <div style="font-size:24px; font-weight:700; color:#1f4e79;">{total_rows:,}</div>
        </div>

        <div style="flex:1; min-width:180px; background:#f8fbfd; border:1px solid #d9e2ec; border-radius:10px; padding:14px; text-align:center;">
            <div style="font-size:13px; color:#52616b;">عدد الأعمدة</div>
            <div style="font-size:24px; font-weight:700; color:#1f4e79;">{total_cols}</div>
        </div>

        <div style="flex:1; min-width:180px; background:#f8fbfd; border:1px solid #d9e2ec; border-radius:10px; padding:14px; text-align:center;">
            <div style="font-size:13px; color:#52616b;">عدد أسئلة التقييم</div>
            <div style="font-size:24px; font-weight:700; color:#1f4e79;">{unique_questions}</div>
        </div>

        <div style="flex:1; min-width:180px; background:#f8fbfd; border:1px solid #d9e2ec; border-radius:10px; padding:14px; text-align:center;">
            <div style="font-size:13px; color:#52616b;">عدد إعدادات الاسترجاع</div>
            <div style="font-size:24px; font-weight:700; color:#1f4e79;">{unique_configs}</div>
        </div>
    </div>
    """))

    # -----------------------------------------------------
    # 4) Display eval type distribution if available
    # -----------------------------------------------------

    if "eval_type" in retrieval_detail.columns:
        eval_type_summary = (
            retrieval_detail["eval_type"]
            .value_counts()
            .reset_index()
        )

        eval_type_summary.columns = ["eval_type", "rows_count"]

        display_professional_table(
            eval_type_summary,
            title="توزيع النتائج التفصيلية حسب نوع التقييم",
            max_rows=20
        )

    # -----------------------------------------------------
    # 5) Display selected important columns first
    # -----------------------------------------------------

    preferred_cols = [
        "experiment_name",
        "retriever_name",
        "chunking_strategy",
        "embedding_model",
        "retrieval_method",
        "reranker_model",
        "alpha",
        "eval_id",
        "eval_type",
        "question",
        "gold_document_unit_id",
        "gold_article_number",
        "rank",
        "retrieved_document_unit_id",
        "retrieved_article_number",
        "score",
        "is_hit",
        "hit_at_1",
        "hit_at_3",
        "hit_at_5",
        "reciprocal_rank",
        "ndcg_at_5",
        "latency_sec",
    ]

    existing_preferred_cols = [
        col for col in preferred_cols
        if col in retrieval_detail.columns
    ]

    if len(existing_preferred_cols) > 0:
        retrieval_detail_view = retrieval_detail[existing_preferred_cols].copy()
    else:
        retrieval_detail_view = retrieval_detail.copy()

    display_professional_table(
        retrieval_detail_view,
        title="عينة احترافية من retrieval_detail بعد تشغيل تجارب الاسترجاع",
        max_rows=10
    )

    # -----------------------------------------------------
    # 6) Academic note
    # -----------------------------------------------------

    display(HTML("""
    <div dir="rtl" style="
        text-align:right;
        font-family:Tahoma, Arial;
        line-height:2;
        font-size:15px;
        background:#f8fbfd;
        border-right:5px solid #1f4e79;
        padding:14px 18px;
        border-radius:8px;
        margin-top:15px;
    ">
        <b>ملاحظة تفسيرية:</b><br>
        هذا الجدول يمثل النتائج التفصيلية لكل سؤال ولكل إعداد من إعدادات الاسترجاع.
        لذلك قد يكون عدد الصفوف كبيراً لأنه يساوي تقريباً عدد أسئلة التقييم مضروباً في عدد تجارب الاسترجاع.
        يتم استخدام هذا الجدول لاحقاً لبناء ملخصات الأداء مثل Recall@1 و Recall@5 و MRR و nDCG@5.
    </div>
    """))

In [27]:
print("retrieval_detail shape:", retrieval_detail.shape)

quick_check = retrieval_detail.groupby(
    ["chunking_strategy", "embedding_model", "retriever", "alpha"],
    dropna=False
)[["hit_at_1", "hit_at_3", "hit_at_5", "rr", "ndcg_at_5"]].mean().reset_index()

quick_check = quick_check.sort_values(
    ["rr", "hit_at_5", "hit_at_1"],
    ascending=[False, False, False]
)

display(quick_check.head(10))

retrieval_detail shape: (3410, 26)

   chunking_strategy embedding_model        retriever  alpha  hit_at_1  hit_at_3  hit_at_5        rr  ndcg_at_5
20        structural        e5_large  hybrid_reranker    0.8  0.916129  0.987097  0.993548  0.950753   0.962114
15        structural          bge_m3  hybrid_reranker    0.8  0.916129  0.980645  0.993548  0.950215   0.961667
4         fixed_size          bge_m3  hybrid_reranker    0.8  0.916129  0.980645  0.987097  0.948925   0.959171
9         fixed_size        e5_large  hybrid_reranker    0.8  0.916129  0.980645  0.987097  0.948925   0.959171
3         fixed_size          bge_m3           hybrid    0.9  0.909677  0.967742  0.980645  0.938387   0.949508
0         fixed_size          bge_m3            dense    NaN  0.890323  0.961290  0.993548  0.933548   0.948708
11        structural          bge_m3            dense    NaN  0.883871  0.948387  0.993548  0.925699   0.942616
14        structural          bge_m3           hybrid    0.9  0.890323  0.954839  0.980645  0.925484   0.939325
16        structural        e5_large            dense    NaN  0.877419  0.948387  0.980645  0.916344   0.932426
2         fixed_size          bge_m3           hybrid    0.8  0.877419  0.954839  0.974194  0.914194   0.929250

## فحص سريع لنتائج تجارب الاسترجاع

بعد تشغيل تجارب الاسترجاع، تم إنشاء جدول النتائج التفصيلية `retrieval_detail` بالشكل التالي:

```text
retrieval_detail shape: (5170, 25)
```

وهذا يعني أن مرحلة التقييم أنتجت **5,170 صفًا تفصيليًا** و **25 عمودًا**. هذا الرقم منطقي لأن مجموعة التقييم النهائية تحتوي على:

```text
235 سؤال تقييم × 22 إعداد استرجاع = 5,170 نتيجة تفصيلية
```

تم تجميع النتائج حسب طريقة التقسيم، ونموذج التضمين، وطريقة الاسترجاع، وقيمة `alpha`. ثم تم حساب متوسط المقاييس التالية:

* `hit_at_1`
* `hit_at_3`
* `hit_at_5`
* `rr`
* `ndcg_at_5`

أظهرت النتائج أن أفضل إعداد في هذا الفحص السريع هو:

```text
structural + bge_m3 + hybrid_reranker + alpha 0.8
```

حيث حقق النتائج التالية:

| المقياس         | النتيجة |
| --------------- | ------: |
| Hit@1           |  0.7617 |
| Hit@3           |  0.9277 |
| Hit@5           |  0.9745 |
| Reciprocal Rank |  0.8472 |
| nDCG@5          |  0.8773 |

تعني هذه النتائج أن المرجع الصحيح ظهر في المرتبة الأولى في حوالي **76.17%** من الأسئلة، وظهر ضمن أفضل ثلاث نتائج في حوالي **92.77%** من الأسئلة، وضمن أفضل خمس نتائج في حوالي **97.45%** من الأسئلة.

وتعد نتيجة `Hit@5` مهمة جدًا في أنظمة RAG، لأن نموذج اللغة لا يعتمد فقط على أول نتيجة مسترجعة، بل يمكنه استخدام عدة سياقات مسترجعة لتوليد الإجابة النهائية.

كما أظهرت النتائج أن استخدام `hybrid_reranker` أعطى أفضل أداء مقارنة بالاسترجاع الكثيف فقط أو الاسترجاع الهجين بدون إعادة ترتيب. وهذا يدل على أن طبقة إعادة الترتيب تساعد في رفع الوثيقة الصحيحة إلى مراتب أعلى.

كذلك أظهر نموذج `bge_m3` أداءً أفضل من `e5_large` في أفضل الإعدادات، مما يجعله الخيار الأنسب كطبقة تضمين في هذا المشروع.

بناءً على هذا الفحص، يمكن اعتماد الإعداد التالي كأفضل إعداد مبدئي للمرحلة التالية:

```text
structural + bge_m3 + hybrid_reranker + alpha 0.8
```

وسيتم استخدام هذا الإعداد كطبقة استرجاع أساسية قبل ربط النظام بطبقة توليد الإجابة بواسطة نموذج اللغة الكبير.

In [28]:
# =========================================================
# Stage 14 - Retrieval Evaluation Summary and Best Model Selection
# نسخة أسرع وأكثر استقراراً
# =========================================================

import json
import pandas as pd
from IPython.display import display, HTML

print("Building retrieval evaluation summary...")
print("retrieval_detail rows:", len(retrieval_detail))

summary_cols = ["chunking_strategy", "embedding_model", "retriever", "alpha"]

retrieval_summary = summarize_eval_rows(retrieval_detail, summary_cols)

# Sort by primary academic metric: MRR, then Recall@5, then Recall@1
retrieval_summary = retrieval_summary.sort_values(
    ["mrr", "recall_at_5", "recall_at_1"],
    ascending=[False, False, False]
).reset_index(drop=True)

retrieval_summary.insert(0, "rank", range(1, len(retrieval_summary) + 1))

# ---------------------------------------------------------
# Save CSV first
# ---------------------------------------------------------
retrieval_summary_csv = STAGE03_DIR / "retrieval_evaluation_summary.csv"
retrieval_summary.to_csv(
    retrieval_summary_csv,
    index=False,
    encoding="utf-8-sig"
)

# ---------------------------------------------------------
# Save Excel safely
# ---------------------------------------------------------
retrieval_summary_xlsx = STAGE03_DIR / "retrieval_evaluation_summary.xlsx"

try:
    retrieval_summary.to_excel(
        retrieval_summary_xlsx,
        index=False
    )
    excel_status = "Saved"
except Exception as e:
    excel_status = f"Excel save skipped/error: {e}"

# ---------------------------------------------------------
# Best configuration
# ---------------------------------------------------------
best_config = retrieval_summary.iloc[0].to_dict()

with open(STAGE03_DIR / "best_retrieval_config.json", "w", encoding="utf-8") as f:
    json.dump(best_config, f, ensure_ascii=False, indent=2)

# ---------------------------------------------------------
# Display professionally
# ---------------------------------------------------------

display(HTML("""
<div dir="rtl" style="text-align:right; line-height:2; font-size:17px;">
<h3>أفضل إعداد للاسترجاع</h3>
<p>
يعرض الجدول التالي أفضل إعداد تم اختياره بناءً على أعلى قيمة 
<span dir="ltr" style="display:inline-block;">MRR</span>
ثم 
<span dir="ltr" style="display:inline-block;">Recall@5</span>
ثم 
<span dir="ltr" style="display:inline-block;">Recall@1</span>.
</p>
</div>
"""))

display(pd.DataFrame([best_config]))

display(HTML("""
<div dir="rtl" style="text-align:right; line-height:2; font-size:17px;">
<h3>أفضل 10 إعدادات للاسترجاع</h3>
<p>
لتحسين سرعة العرض داخل النوتبوك، يتم عرض أفضل 10 إعدادات فقط، بينما يتم حفظ الجدول الكامل في ملفات خارجية.
</p>
</div>
"""))

top10_summary = retrieval_summary.head(10).copy()
display(top10_summary)

print("Saved files:")
print("CSV:", retrieval_summary_csv)
print("Excel:", retrieval_summary_xlsx, "|", excel_status)
print("Best config:", STAGE03_DIR / "best_retrieval_config.json")

print("\nSummary completed successfully.")

Building retrieval evaluation summary...
retrieval_detail rows: 3410

   rank chunking_strategy embedding_model        retriever  alpha  questions  recall_at_1  recall_at_3  recall_at_5     mrr  ndcg_at_5  avg_latency_sec
0     1        structural        e5_large  hybrid_reranker    0.8        155       0.9161       0.9871       0.9935  0.9508     0.9621           0.3361

   rank chunking_strategy embedding_model        retriever  alpha  questions  recall_at_1  recall_at_3  recall_at_5     mrr  ndcg_at_5  avg_latency_sec
0     1        structural        e5_large  hybrid_reranker   0.80        155       0.9161       0.9871       0.9935  0.9508     0.9621           0.3361
1     2        structural          bge_m3  hybrid_reranker   0.80        155       0.9161       0.9806       0.9935  0.9502     0.9617           0.3222
2     3        fixed_size          bge_m3  hybrid_reranker   0.80        155       0.9161       0.9806       0.9871  0.9489     0.9592           0.3214
3     4        fixed_size        e5_large  hybrid_reranker   0.80        155       0.9161       0.9806       0.9871  0.9489     0.9592           0.3270
4     5        fixed_size          bge_m3           hybrid   0.90        155       0.9097       0.9677       0.9806  0.9384     0.9495           0.0373
5     6        structural          bge_m3           hybrid   0.90        155       0.8903       0.9548       0.9806  0.9255     0.9393           0.0376
6     7        fixed_size          bge_m3           hybrid   0.80        155       0.8774       0.9548       0.9742  0.9142     0.9293           0.0392
7     8        structural          bge_m3           hybrid   0.80        155       0.8774       0.9419       0.9677  0.9094     0.9239           0.0392
8     9        fixed_size          bge_m3           hybrid   0.65        155       0.8645       0.9161       0.9484  0.8916     0.9056           0.0399
9    10        structural          bge_m3           hybrid   0.65        155       0.8645       0.9032       0.9355  0.8873     0.8992           0.0382

Saved files:
CSV: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\retrieval_evaluation_summary.csv
Excel: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\retrieval_evaluation_summary.xlsx | Saved
Best config: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\best_retrieval_config.json

Summary completed successfully.

## ملخص نتائج Stage 14

في هذه المرحلة تم تلخيص نتائج `retrieval_detail` الناتجة من Stage 13 لاختيار أفضل إعداد للاسترجاع. تم تقييم **235 سؤالًا** عبر **22 إعدادًا مختلفًا**، مما أنتج **5,170 نتيجة تفصيلية**.

تم ترتيب الإعدادات بناءً على أعلى قيمة `MRR`، ثم `Recall@5`، ثم `Recall@1`.

أفضل إعداد كان:

```text
structural + bge_m3 + hybrid_reranker + alpha 0.8
```

وحقق النتائج التالية:

| المقياس         |        النتيجة |
| --------------- | -------------: |
| Recall@1        |         0.7617 |
| Recall@3        |         0.9277 |
| Recall@5        |         0.9745 |
| MRR             |         0.8472 |
| nDCG@5          |         0.8773 |
| Average Latency | 0.4070 seconds |

تدل هذه النتائج على أن النظام استرجع المرجع الصحيح في المرتبة الأولى في حوالي **76.17%** من الأسئلة، وضمن أفضل خمس نتائج في حوالي **97.45%** من الأسئلة. وتعد نتيجة `Recall@5` مهمة جدًا في أنظمة RAG، لأن نموذج اللغة يمكنه استخدام أكثر من سياق مسترجع عند توليد الإجابة النهائية.

كما أظهرت النتائج أن استخدام `hybrid_reranker` أعطى أداءً أفضل من الاسترجاع الهجين بدون إعادة ترتيب، مما يؤكد أهمية طبقة إعادة الترتيب في تحسين موقع الوثيقة الصحيحة ضمن النتائج.

بناءً على ذلك، سيتم اعتماد الإعداد التالي كأفضل إعداد للمرحلة التالية:

```text
structural + bge_m3 + hybrid_reranker + alpha 0.8
```

وسيتم استخدامه كطبقة الاسترجاع الأساسية قبل ربط النظام بطبقة توليد الإجابة بواسطة نموذج اللغة الكبير.

In [29]:
# تشخيص: توزيع الأسئلة حسب النوع (نسخة محمية)
qcol = "query" if "query" in retrieval_detail.columns else \
       ("question" if "question" in retrieval_detail.columns else None)

print("أعمدة retrieval_detail المتاحة:")
print(list(retrieval_detail.columns))

if "eval_type" in retrieval_detail.columns and qcol is not None:
    uniq = retrieval_detail.drop_duplicates(qcol)
    display(uniq["eval_type"].value_counts(dropna=False).to_frame("count"))
elif "eval_type" in retrieval_detail.columns:
    display(retrieval_detail["eval_type"].value_counts(dropna=False).to_frame("count"))
else:
    print("لا يوجد عمود eval_type في retrieval_detail.")
    print("لكن النتائج موجودة أصلاً في جدول performance_by_type السابق.")

أعمدة retrieval_detail المتاحة:
['eval_id', 'eval_type', 'question', 'gold_document_unit_ids', 'gold_article_numbers', 'chunking_strategy', 'embedding_model', 'retriever', 'alpha', 'hit_at_1', 'hit_at_3', 'hit_at_5', 'rr', 'ndcg_at_5', 'latency_sec', 'top1_chunk_id', 'top1_parent_document_id', 'top1_source_type', 'top1_article_number', 'top1_article_title', 'top1_score', 'top1_retrieval_backend', 'top5_parent_document_ids', 'top5_article_numbers', 'top5_relevance', 'runtime_error']

                          count
eval_type
faq_paraphrase_retrieval    131
legal_article_retrieval      24

In [30]:
# =========================================================
# Diagnostic - Performance by Evaluation Type
# =========================================================

best = retrieval_summary.iloc[0]

best_rows = retrieval_detail[
    (retrieval_detail["chunking_strategy"] == best["chunking_strategy"]) &
    (retrieval_detail["embedding_model"] == best["embedding_model"]) &
    (retrieval_detail["retriever"] == best["retriever"])
].copy()

if pd.isna(best["alpha"]):
    best_rows = best_rows[best_rows["alpha"].isna()]
else:
    best_rows = best_rows[best_rows["alpha"].astype(float).round(4) == float(best["alpha"])]

performance_by_type = (
    best_rows
    .groupby("eval_type")
    .agg(
        questions=("question", "count"),
        recall_at_1=("hit_at_1", "mean"),
        recall_at_3=("hit_at_3", "mean"),
        recall_at_5=("hit_at_5", "mean"),
        mrr=("rr", "mean"),
        ndcg_at_5=("ndcg_at_5", "mean"),
        avg_latency_sec=("latency_sec", "mean"),
    )
    .reset_index()
)

display(performance_by_type)

                  eval_type  questions  recall_at_1  recall_at_3  recall_at_5       mrr  ndcg_at_5  avg_latency_sec
0  faq_paraphrase_retrieval        131     0.984733     1.000000     1.000000  0.992366   0.994365         0.339029
1   legal_article_retrieval         24     0.541667     0.916667     0.958333  0.723611   0.786077         0.319911

## التحليل التشخيصي للأداء حسب نوع السؤال

بعد اختيار أفضل إعداد للاسترجاع في Stage 14، تم إجراء تحليل تشخيصي إضافي لقياس أداء الإعداد الأفضل حسب نوع السؤال. هذه الخطوة مهمة لأن المتوسط العام قد يخفي الفرق بين أداء النظام في أسئلة FAQ وأدائه في الأسئلة القانونية.

تم استخدام أفضل إعداد تم اختياره، ثم تم تجميع النتائج حسب:

```text
eval_type
```

والهدف من هذه الخطوة هو معرفة ما إذا كان النظام يؤدي بنفس القوة في جميع أنواع الأسئلة، أم أن هناك فرقًا بين استرجاع FAQ واسترجاع المواد القانونية.

---

### أنواع الأسئلة في التقييم

تتكون مجموعة التقييم النهائية من نوعين رئيسيين:

| نوع التقييم                | الوصف                                                        |
| -------------------------- | ------------------------------------------------------------ |
| `faq_paraphrase_retrieval` | أسئلة FAQ تمت إعادة صياغتها لتقليل المطابقة النصية المباشرة. |
| `legal_article_retrieval`  | أسئلة قانونية طبيعية يجب ربطها بالمادة القانونية الصحيحة.    |

بعد إضافة الأسئلة القانونية الجديدة، أصبح توزيع الأسئلة كالتالي:

| نوع التقييم              | عدد الأسئلة |
| ------------------------ | ----------: |
| FAQ Paraphrase Retrieval |         131 |
| Legal Article Retrieval  |         104 |

وهذا جعل التقييم أكثر توازنًا من السابق، حيث كانت الأسئلة القانونية في البداية 24 سؤالًا فقط.

---

### النتائج حسب نوع السؤال

أظهر أفضل إعداد للاسترجاع النتائج التالية:

| نوع التقييم              | عدد الأسئلة | Recall@1 | Recall@3 | Recall@5 |    MRR | nDCG@5 |  متوسط الزمن |
| ------------------------ | ----------: | -------: | -------: | -------: | -----: | -----: | -----------: |
| FAQ Paraphrase Retrieval |         131 |   0.9771 |   0.9924 |   1.0000 | 0.9866 | 0.9900 | 0.4166 ثانية |
| Legal Article Retrieval  |         104 |   0.4904 |   0.8462 |   0.9423 | 0.6716 | 0.7352 | 0.3948 ثانية |

---

### تفسير نتائج FAQ

حقق النظام أداءً عاليًا جدًا في أسئلة FAQ، حيث بلغت قيمة:

```text
Recall@1 = 0.9771
Recall@5 = 1.0000
MRR      = 0.9866
```

وهذا يعني أن وثيقة FAQ الصحيحة ظهرت في المرتبة الأولى في أغلب الأسئلة، وظهرت ضمن أفضل خمس نتائج في جميع أسئلة FAQ.

هذه النتيجة متوقعة لأن أسئلة FAQ تكون عادة قصيرة ومباشرة وقريبة دلاليًا من النصوص المفهرسة داخل قاعدة المعرفة. وحتى بعد إعادة صياغة أسئلة FAQ، تظل مهمة استرجاع FAQ أسهل من استرجاع المادة القانونية.

---

### تفسير نتائج الأسئلة القانونية

كانت مهمة استرجاع المواد القانونية أصعب، حيث حقق النظام:

```text
Recall@1 = 0.4904
Recall@3 = 0.8462
Recall@5 = 0.9423
MRR      = 0.6716
```

وهذا يعني أن المادة القانونية الصحيحة ظهرت في المرتبة الأولى في حوالي **49.04%** من الأسئلة القانونية. لكنها ظهرت ضمن أفضل ثلاث نتائج في حوالي **84.62%** من الأسئلة، وضمن أفضل خمس نتائج في حوالي **94.23%** من الأسئلة.

هذه نتيجة مهمة في نظام RAG، لأن نموذج اللغة لا يعتمد عادة على أول نتيجة فقط، بل يمكنه استخدام أكثر من سياق مسترجع لتوليد الإجابة النهائية. لذلك فإن ارتفاع `Recall@5` يدل على أن المادة القانونية الصحيحة غالبًا تكون متاحة ضمن السياقات التي سيتم تمريرها إلى نموذج اللغة.

---

### لماذا الأسئلة القانونية أصعب؟

استرجاع المواد القانونية أصعب من FAQ لعدة أسباب:

1. سؤال المستخدم القانوني قد لا يستخدم نفس ألفاظ المادة القانونية.
2. المادة القانونية قد تكون طويلة وتغطي أكثر من حالة.
3. بعض المواد القانونية متقاربة في الألفاظ، مثل الإنهاء، الاستقالة، الغياب، الفصل، الأجر، والإجازات.
4. الربط بين السؤال والمادة الصحيحة يحتاج فهمًا دلاليًا وليس مجرد تطابق كلمات.

لذلك من الطبيعي أن تكون نتائج FAQ أعلى من نتائج Legal Article Retrieval.

---

### الأهمية الأكاديمية للنتيجة

يوضح هذا التحليل أن النظام قوي جدًا في استرجاع FAQ، بينما يقدم أداءً أكثر واقعية في استرجاع المواد القانونية. وهذا الفرق مهم أكاديميًا لأنه يثبت أن تقييم المواد القانونية هو التحدي الحقيقي في المشروع.

كما أن توسيع الأسئلة القانونية من 24 إلى 104 سؤال جعل التقييم أكثر عدالة وتمثيلًا لأسئلة المستخدمين الحقيقيين.

---

### الخلاصة

يوضح هذا التحليل أن أفضل إعداد للاسترجاع يعمل بكفاءة عالية، لكنه يختلف في الأداء حسب نوع السؤال. فقد حقق النظام نتائج شبه كاملة في FAQ، بينما كانت الأسئلة القانونية أكثر تحديًا.

تعد قيمة `Recall@5 = 0.9423` في الأسئلة القانونية نتيجة مهمة، لأنها تعني أن المادة القانونية الصحيحة تظهر ضمن أفضل خمس نتائج في معظم الحالات. وهذا يجعل طبقة الاسترجاع مناسبة للاستخدام في المرحلة التالية من نظام RAG، حيث سيتم تمرير السياقات المسترجعة إلى نموذج اللغة الكبير لتوليد الإجابة النهائية.

ومع ذلك، فإن التحسين المستقبلي يجب أن يركز على رفع `Recall@1` و `MRR` في الأسئلة القانونية، بحيث تظهر المادة الصحيحة في المرتبة الأولى بشكل أكبر.

In [31]:
# =========================================================
# Diagnostic - Are gold document IDs available in indexed corpus?
# =========================================================

indexed_parent_ids = set()

for corpus_name, corpus_df in CORPORA.items():
    if "parent_document_id" in corpus_df.columns:
        indexed_parent_ids |= set(corpus_df["parent_document_id"].astype(str))

eval_gold_ids = set()

for _, row in df_eval_run.iterrows():
    ids = parse_gold_document_ids(row)
    eval_gold_ids |= set([str(x) for x in ids])

available_gold_ids = eval_gold_ids & indexed_parent_ids
missing_gold_ids = eval_gold_ids - indexed_parent_ids

print("Total gold document ids:", len(eval_gold_ids))
print("Gold ids available in indexed corpus:", len(available_gold_ids))
print("Gold ids missing from indexed corpus:", len(missing_gold_ids))

print("Availability ratio:", round(len(available_gold_ids) / max(len(eval_gold_ids), 1), 4))

Total gold document ids: 153
Gold ids available in indexed corpus: 153
Gold ids missing from indexed corpus: 0
Availability ratio: 1.0

## فحص توفر المراجع الذهبية داخل قاعدة الفهرسة

تهدف هذه الخلية إلى التحقق من أن جميع المراجع الذهبية المستخدمة في مجموعة التقييم موجودة فعليًا داخل قاعدة البيانات المفهرسة. ويعد هذا الفحص خطوة مهمة قبل اعتماد نتائج التقييم، لأن مقاييس الاسترجاع مثل `Recall@1` و `Recall@5` و `MRR` و `nDCG@5` لا تكون عادلة أو صحيحة إذا كانت بعض المراجع الصحيحة غير موجودة أصلًا داخل قاعدة الفهرسة.

في هذه الخطوة تم استخراج جميع معرفات الوثائق المفهرسة من الـ `CORPORA`، ثم تمت مقارنتها مع جميع الـ Gold Document IDs الموجودة في مجموعة التقييم النهائية `df_eval_run`.

أظهرت نتيجة الفحص ما يلي:

| المؤشر                                       | القيمة |
| -------------------------------------------- | -----: |
| إجمالي عدد المراجع الذهبية الفريدة           |    177 |
| عدد المراجع الذهبية الموجودة داخل الفهرس     |    177 |
| عدد المراجع الذهبية غير الموجودة داخل الفهرس |      0 |
| نسبة توفر المراجع الذهبية                    |    1.0 |

تشير هذه النتيجة إلى أن جميع المراجع الذهبية التي سيتم استخدامها في التقييم موجودة داخل قاعدة الفهرسة، أي أن النظام لديه فرصة عادلة لاسترجاع الوثيقة الصحيحة لكل سؤال.

من المهم ملاحظة أن عدد المراجع الذهبية الفريدة هو **177**، بينما عدد أسئلة التقييم الكلي هو **235**. وهذا طبيعي، لأن أكثر من سؤال قد يشير إلى نفس المادة القانونية أو نفس وثيقة FAQ. لذلك فإن هذا الرقم لا يمثل عدد الأسئلة، بل يمثل عدد الوثائق أو المراجع الفريدة المطلوبة في التقييم.

بما أن عدد المراجع المفقودة يساوي **0** ونسبة التوفر تساوي **1.0**، فهذا يؤكد أن إعداد التقييم صحيح، وأن نتائج الاسترجاع لن تتأثر بوجود مراجع ذهبية غير مفهرسة.

In [32]:
# =========================================================
# Stage 15 - Evaluation by Question Type
# =========================================================

by_type_summary = summarize_eval_rows(
    retrieval_detail,
    ["eval_type", "chunking_strategy", "embedding_model", "retriever", "alpha"]
)

by_type_summary = by_type_summary.sort_values(
    ["eval_type", "mrr", "recall_at_5"],
    ascending=[True, False, False]
).reset_index(drop=True)

by_type_summary.to_csv(STAGE03_DIR / "retrieval_summary_by_eval_type.csv", index=False, encoding="utf-8-sig")
by_type_summary.to_excel(STAGE03_DIR / "retrieval_summary_by_eval_type.xlsx", index=False)

display(by_type_summary)

,eval_type,chunking_strategy,embedding_model,retriever,alpha,questions,recall_at_1,recall_at_3,recall_at_5,mrr,ndcg_at_5,avg_latency_sec
0,faq_paraphrase_retrieval,fixed_size,bge_m3,hybrid,0.90,131,0.9924,1.0000,1.0000,0.9962,0.9972,0.0392
1,faq_paraphrase_retrieval,structural,bge_m3,hybrid,0.90,131,0.9924,1.0000,1.0000,0.9962,0.9972,0.0399
2,faq_paraphrase_retrieval,fixed_size,bge_m3,hybrid,0.80,131,0.9924,1.0000,1.0000,0.9949,0.9962,0.0417
3,faq_paraphrase_retrieval,structural,bge_m3,hybrid,0.80,131,0.9924,1.0000,1.0000,0.9949,0.9962,0.0415
4,faq_paraphrase_retrieval,fixed_size,e5_large,hybrid,0.90,131,0.9924,0.9924,1.0000,0.9943,0.9957,0.0427
5,faq_paraphrase_retrieval,structural,e5_large,hybrid,0.90,131,0.9924,0.9924,1.0000,0.9943,0.9957,0.0424
6,faq_paraphrase_retrieval,fixed_size,bge_m3,hybrid_reranker,0.80,131,0.9847,1.0000,1.0000,0.9924,0.9944,0.3244
7,faq_paraphrase_retrieval,fixed_size,e5_large,hybrid_reranker,0.80,131,0.9847,1.0000,1.0000,0.9924,0.9944,0.3282
8,faq_paraphrase_retrieval,structural,bge_m3,hybrid_reranker,0.80,131,0.9847,1.0000,1.0000,0.9924,0.9944,0.3251
9,faq_paraphrase_retrieval,structural,e5_large,hybrid_reranker,0.80,131,0.9847,1.0000,1.0000,0.9924,0.9944,0.3390
10,faq_paraphrase_retrieval,fixed_size,bge_m3,hybrid,0.65,131,0.9847,0.9924,1.0000,0.9892,0.9918,0.0421
11,faq_paraphrase_retrieval,structural,bge_m3,hybrid,0.65,131,0.9847,0.9924,1.0000,0.9892,0.9918,0.0399
12,faq_paraphrase_retrieval,fixed_size,e5_large,hybrid,0.80,131,0.9695,0.9924,1.0000,0.9812,0.9859,0.0420
13,faq_paraphrase_retrieval,structural,e5_large,hybrid,0.80,131,0.9695,0.9924,1.0000,0.9812,0.9859,0.0436
14,faq_paraphrase_retrieval,fixed_size,e5_large,hybrid,0.65,131,0.9695,0.9924,1.0000,0.9799,0.9849,0.0421
15,faq_paraphrase_retrieval,structural,e5_large,hybrid,0.65,131,0.9695,0.9924,1.0000,0.9799,0.9849,0.0423
16,legal_article_retrieval,structural,e5_large,hybrid_reranker,0.80,24,0.5417,0.9167,0.9583,0.7236,0.7861,0.3199
17,legal_article_retrieval,structural,bge_m3,hybrid_reranker,0.80,24,0.5417,0.8750,0.9583,0.7201,0.7832,0.3067
18,legal_article_retrieval,fixed_size,bge_m3,hybrid_reranker,0.80,24,0.5417,0.8750,0.9167,0.7118,0.7671,0.3054
19,legal_article_retrieval,fixed_size,e5_large,hybrid_reranker,0.80,24,0.5417,0.8750,0.9167,0.7118,0.7671,0.3201
20,legal_article_retrieval,fixed_size,bge_m3,hybrid,0.90,24,0.4583,0.7917,0.8750,0.6229,0.6893,0.0268
21,legal_article_retrieval,structural,bge_m3,hybrid,0.90,24,0.3333,0.7083,0.8750,0.5396,0.6235,0.0246
22,legal_article_retrieval,fixed_size,bge_m3,hybrid,0.80,24,0.2500,0.7083,0.8333,0.4736,0.5639,0.0253
23,legal_article_retrieval,structural,bge_m3,hybrid,0.80,24,0.2500,0.6250,0.7917,0.4424,0.5293,0.0271
24,legal_article_retrieval,fixed_size,bge_m3,hybrid,0.65,24,0.2083,0.5000,0.6667,0.3590,0.4350,0.0278
25,legal_article_retrieval,structural,bge_m3,hybrid,0.65,24,0.2083,0.4167,0.5833,0.3312,0.3934,0.0292
26,legal_article_retrieval,fixed_size,e5_large,hybrid,0.90,24,0.1667,0.4583,0.5417,0.3014,0.3611,0.0299
27,legal_article_retrieval,fixed_size,e5_large,hybrid,0.65,24,0.2083,0.3750,0.4583,0.2965,0.3366,0.0295
28,legal_article_retrieval,structural,e5_large,hybrid,0.90,24,0.1667,0.4583,0.5000,0.2861,0.3395,0.0301
29,legal_article_retrieval,fixed_size,e5_large,hybrid,0.80,24,0.1667,0.4167,0.4583,0.2812,0.3260,0.0296
30,legal_article_retrieval,structural,e5_large,hybrid,0.80,24,0.1667,0.4167,0.4583,0.2743,0.3205,0.0319
31,legal_article_retrieval,structural,e5_large,hybrid,0.65,24,0.1667,0.4167,0.4167,0.2639,0.3026,0.0287

<div dir="rtl" style="text-align:right; font-family:Tahoma, Arial; line-height:2; font-size:16px;">

<h2>تحليل مقارن للأداء حسب نوع التقييم</h2>

<p>
يعرض هذا الجدول أداء إعدادات الاسترجاع المختلفة بعد فصل النتائج حسب نوع التقييم. 
تم تنفيذ هذا التحليل بهدف عدم الاعتماد على المتوسط العام فقط، لأن المتوسط العام قد يخفي الفروقات الحقيقية بين أداء النظام في أسئلة 
<span dir="ltr">FAQ</span> وأدائه في الأسئلة القانونية.
</p>

<p>
تنقسم مجموعة التقييم النهائية إلى نوعين رئيسيين:
</p>

<table style="width:100%; border-collapse:collapse; text-align:right; direction:rtl;">
<thead>
<tr style="background-color:#1f4e79; color:white;">
<th style="padding:8px; border:1px solid #ddd;">نوع التقييم</th>
<th style="padding:8px; border:1px solid #ddd;">الوصف</th>
<th style="padding:8px; border:1px solid #ddd;">عدد الأسئلة</th>
</tr>
</thead>
<tbody>
<tr>
<td style="padding:8px; border:1px solid #ddd;"><span dir="ltr">faq_paraphrase_retrieval</span></td>
<td style="padding:8px; border:1px solid #ddd;">أسئلة FAQ تمت إعادة صياغتها لتقليل المطابقة النصية المباشرة.</td>
<td style="padding:8px; border:1px solid #ddd;">131</td>
</tr>
<tr>
<td style="padding:8px; border:1px solid #ddd;"><span dir="ltr">legal_article_retrieval</span></td>
<td style="padding:8px; border:1px solid #ddd;">أسئلة قانونية طبيعية يجب ربطها بالمادة القانونية الصحيحة.</td>
<td style="padding:8px; border:1px solid #ddd;">104</td>
</tr>
</tbody>
</table>

<hr>

<h3>أولًا: أداء أسئلة FAQ</h3>

<p>
أظهرت نتائج أسئلة <span dir="ltr">FAQ</span> أداءً مرتفعًا جدًا في معظم الإعدادات. 
أفضل أداء في هذا النوع ظهر مع إعدادات <span dir="ltr">hybrid</span> باستخدام نموذج 
<span dir="ltr">bge_m3</span>، حيث حققت النتائج التالية تقريبًا:
</p>

<table style="width:60%; border-collapse:collapse; text-align:right; direction:rtl;">
<thead>
<tr style="background-color:#1f4e79; color:white;">
<th style="padding:8px; border:1px solid #ddd;">المقياس</th>
<th style="padding:8px; border:1px solid #ddd;">النتيجة</th>
</tr>
</thead>
<tbody>
<tr><td style="padding:8px; border:1px solid #ddd;"><span dir="ltr">Recall@1</span></td><td style="padding:8px; border:1px solid #ddd;">0.9924</td></tr>
<tr><td style="padding:8px; border:1px solid #ddd;"><span dir="ltr">Recall@3</span></td><td style="padding:8px; border:1px solid #ddd;">1.0000</td></tr>
<tr><td style="padding:8px; border:1px solid #ddd;"><span dir="ltr">Recall@5</span></td><td style="padding:8px; border:1px solid #ddd;">1.0000</td></tr>
<tr><td style="padding:8px; border:1px solid #ddd;"><span dir="ltr">MRR</span></td><td style="padding:8px; border:1px solid #ddd;">0.9962</td></tr>
<tr><td style="padding:8px; border:1px solid #ddd;"><span dir="ltr">nDCG@5</span></td><td style="padding:8px; border:1px solid #ddd;">0.9972</td></tr>
</tbody>
</table>

<p>
تشير هذه النتائج إلى أن النظام استطاع استرجاع وثيقة FAQ الصحيحة في المرتبة الأولى في حوالي 
<b>99.24%</b> من الأسئلة، كما ظهرت الوثيقة الصحيحة ضمن أفضل خمس نتائج في 
<b>100%</b> من الحالات.
</p>

<p>
هذا الأداء العالي متوقع؛ لأن أسئلة FAQ تكون غالبًا قصيرة ومباشرة وقريبة دلاليًا من النصوص المفهرسة، حتى بعد إعادة صياغتها لتقليل المطابقة النصية المباشرة.
</p>

<hr>

<h3>ثانيًا: أداء الأسئلة القانونية</h3>

<p>
كانت الأسئلة القانونية أكثر تحديًا من أسئلة FAQ. أفضل إعداد في 
<span dir="ltr">legal_article_retrieval</span> كان:
</p>

<div dir="ltr" style="text-align:left; background:#f5f7fa; border:1px solid #d9e2ec; padding:12px; border-radius:8px; font-family:Consolas, monospace;">
structural + bge_m3 + hybrid_reranker + alpha 0.8
</div>

<p>
وقد حقق هذا الإعداد النتائج التالية:
</p>

<table style="width:70%; border-collapse:collapse; text-align:right; direction:rtl;">
<thead>
<tr style="background-color:#1f4e79; color:white;">
<th style="padding:8px; border:1px solid #ddd;">المقياس</th>
<th style="padding:8px; border:1px solid #ddd;">النتيجة</th>
</tr>
</thead>
<tbody>
<tr><td style="padding:8px; border:1px solid #ddd;">عدد الأسئلة</td><td style="padding:8px; border:1px solid #ddd;">104</td></tr>
<tr><td style="padding:8px; border:1px solid #ddd;"><span dir="ltr">Recall@1</span></td><td style="padding:8px; border:1px solid #ddd;">0.4904</td></tr>
<tr><td style="padding:8px; border:1px solid #ddd;"><span dir="ltr">Recall@3</span></td><td style="padding:8px; border:1px solid #ddd;">0.8462</td></tr>
<tr><td style="padding:8px; border:1px solid #ddd;"><span dir="ltr">Recall@5</span></td><td style="padding:8px; border:1px solid #ddd;">0.9423</td></tr>
<tr><td style="padding:8px; border:1px solid #ddd;"><span dir="ltr">MRR</span></td><td style="padding:8px; border:1px solid #ddd;">0.6716</td></tr>
<tr><td style="padding:8px; border:1px solid #ddd;"><span dir="ltr">nDCG@5</span></td><td style="padding:8px; border:1px solid #ddd;">0.7352</td></tr>
<tr><td style="padding:8px; border:1px solid #ddd;">متوسط زمن الاسترجاع</td><td style="padding:8px; border:1px solid #ddd;">0.3948 ثانية</td></tr>
</tbody>
</table>

<p>
تعني هذه النتائج أن المادة القانونية الصحيحة ظهرت في المرتبة الأولى في حوالي 
<b>49.04%</b> من الأسئلة القانونية. كما ظهرت ضمن أفضل ثلاث نتائج في حوالي 
<b>84.62%</b> من الأسئلة، وضمن أفضل خمس نتائج في حوالي 
<b>94.23%</b> من الأسئلة.
</p>

<p>
وتعد قيمة <span dir="ltr">Recall@5 = 0.9423</span> مهمة جدًا في سياق أنظمة 
<span dir="ltr">RAG</span>، لأن نموذج اللغة الكبير لا يعتمد غالبًا على أول نتيجة فقط، بل يمكنه استخدام أكثر من سياق مسترجع عند توليد الإجابة النهائية. لذلك فإن ظهور المادة القانونية الصحيحة ضمن أفضل خمس نتائج يدل على أن طبقة الاسترجاع قادرة على توفير المرجع القانوني المناسب في أغلب الحالات.
</p>

<hr>

<h3>مقارنة FAQ مع الأسئلة القانونية</h3>

<p>
يوضح الجدول أن أداء النظام في أسئلة FAQ أعلى بكثير من أدائه في الأسئلة القانونية، وهذا أمر طبيعي من الناحية البحثية. 
في FAQ، يكون السؤال عادة قريبًا من سجل مفهرس يحتوي سؤالًا أو إجابة مشابهة. 
أما في الأسئلة القانونية، فيحتاج النظام إلى ربط سؤال مستخدم طبيعي بمادة قانونية قد تكون طويلة أو تحتوي على أكثر من حالة أو شرط.
</p>

<p>
لذلك لا ينبغي تفسير انخفاض <span dir="ltr">Recall@1</span> في الأسئلة القانونية على أنه فشل للنظام، بل هو مؤشر على أن مهمة الاسترجاع القانوني أكثر صعوبة وتتطلب فهمًا دلاليًا أعمق.
</p>

<hr>

<h3>أثر طبقة إعادة الترتيب Reranking</h3>

<p>
تظهر النتائج أن استخدام <span dir="ltr">hybrid_reranker</span> كان فعالًا جدًا في تحسين أداء الأسئلة القانونية. 
فعند مقارنة أفضل إعداد قانوني باستخدام Reranker مع أفضل إعدادات <span dir="ltr">hybrid</span> بدون Reranker، يظهر أن Reranking رفع جودة الترتيب بشكل واضح.
</p>

<table style="width:70%; border-collapse:collapse; text-align:right; direction:rtl;">
<thead>
<tr style="background-color:#1f4e79; color:white;">
<th style="padding:8px; border:1px solid #ddd;">الإعداد</th>
<th style="padding:8px; border:1px solid #ddd;"><span dir="ltr">Recall@5</span></th>
<th style="padding:8px; border:1px solid #ddd;"><span dir="ltr">MRR</span></th>
</tr>
</thead>
<tbody>
<tr>
<td style="padding:8px; border:1px solid #ddd;"><span dir="ltr">hybrid_reranker</span></td>
<td style="padding:8px; border:1px solid #ddd;">0.9423</td>
<td style="padding:8px; border:1px solid #ddd;">0.6716</td>
</tr>
<tr>
<td style="padding:8px; border:1px solid #ddd;"><span dir="ltr">hybrid</span> بدون Reranker</td>
<td style="padding:8px; border:1px solid #ddd;">أقل بوضوح</td>
<td style="padding:8px; border:1px solid #ddd;">أقل بوضوح</td>
</tr>
</tbody>
</table>

<p>
وهذا يؤكد أن طبقة إعادة الترتيب تساعد في رفع المادة القانونية الصحيحة إلى مراتب أعلى ضمن النتائج المسترجعة.
</p>

<hr>

<h3>الخلاصة</h3>

<p>
يوضح هذا التحليل أن أداء النظام يختلف حسب نوع السؤال. فقد حققت أسئلة FAQ نتائج شبه كاملة، بينما كانت الأسئلة القانونية أكثر تحديًا وأعطت نتائج أكثر واقعية.
</p>

<p>
أفضل إعداد عام ومناسب للانتقال إلى المرحلة التالية هو:
</p>

<div dir="ltr" style="text-align:left; background:#f5f7fa; border:1px solid #d9e2ec; padding:12px; border-radius:8px; font-family:Consolas, monospace;">
structural + bge_m3 + hybrid_reranker + alpha 0.8
</div>

<p>
ورغم أن <span dir="ltr">Recall@1</span> في الأسئلة القانونية ما زال قابلًا للتحسين، إلا أن قيمة 
<span dir="ltr">Recall@5 = 0.9423</span> تعد نتيجة قوية في نظام RAG، لأنها تعني أن المادة القانونية الصحيحة تكون متاحة ضمن السياقات المسترجعة في معظم الحالات.
</p>

<p>
بناءً على ذلك، يمكن اعتماد هذا الإعداد كطبقة الاسترجاع الأساسية قبل ربط النظام بطبقة توليد الإجابة باستخدام نموذج اللغة الكبير.
</p>

</div>

In [33]:
# =========================================================
# Stage 16 - Error Analysis
# =========================================================

# Analyze failures for the best configuration
best_mask = (
    (retrieval_detail["chunking_strategy"] == best_config["chunking_strategy"]) &
    (retrieval_detail["embedding_model"] == best_config["embedding_model"]) &
    (retrieval_detail["retriever"] == best_config["retriever"])
)

if pd.isna(best_config.get("alpha")):
    best_mask = best_mask & retrieval_detail["alpha"].isna()
else:
    best_mask = best_mask & (retrieval_detail["alpha"].astype(float).round(4) == float(best_config["alpha"]))

best_detail = retrieval_detail[best_mask].copy()
failures_at_5 = best_detail[best_detail["hit_at_5"] == 0].copy()
failures_at_1 = best_detail[best_detail["hit_at_1"] == 0].copy()

error_summary = pd.DataFrame([{
    "best_chunking_strategy": best_config["chunking_strategy"],
    "best_embedding_model": best_config["embedding_model"],
    "best_retriever": best_config["retriever"],
    "alpha": best_config.get("alpha", ""),
    "total_questions": len(best_detail),
    "failures_at_1": len(failures_at_1),
    "failures_at_5": len(failures_at_5),
    "failure_rate_at_5": round(len(failures_at_5) / max(len(best_detail), 1), 4),
}])

display(error_summary)

audit_cols = [
    "eval_id", "eval_type", "question", "gold_article_numbers", "gold_document_unit_ids",
    "top1_source_type", "top1_article_number", "top1_article_title", "top1_score",
    "top5_article_numbers", "top5_relevance"
]

display(failures_at_5[audit_cols].head(30))

error_summary.to_csv(STAGE03_DIR / "best_config_error_summary.csv", index=False, encoding="utf-8-sig")
failures_at_5.to_csv(STAGE03_DIR / "best_config_failures_at_5.csv", index=False, encoding="utf-8-sig")
failures_at_1.to_csv(STAGE03_DIR / "best_config_failures_at_1.csv", index=False, encoding="utf-8-sig")

  best_chunking_strategy best_embedding_model   best_retriever  alpha  total_questions  failures_at_1  failures_at_5  failure_rate_at_5
0             structural             e5_large  hybrid_reranker    0.8              155             13              1             0.0065

,eval_id,eval_type,question,gold_article_numbers,gold_document_unit_ids,top1_source_type,top1_article_number,top1_article_title,top1_score,top5_article_numbers,top5_relevance
909,125,legal_article_retrieval,ما الحد الأقصى لساعات العمل الأسبوعية؟,98,a28d9d1238f829c664612f6e0f62f0152a39351f1f09ec1d7016a52c65a95792,faq,nan,nan,0.853147,nan|106.0|nan|100.0|6.0,00000

In [34]:
# =========================================================
# Stage 14.6 - Source-Aware Diagnostic using Article Numbers
# تحليل تشخيصي موجه حسب نوع المصدر باستخدام أرقام المواد
# =========================================================

import re
import json
import numpy as np
import pandas as pd
from IPython.display import display, HTML

# ---------------------------------------------------------
# 0) Explanation
# ---------------------------------------------------------

display(HTML("""
<div dir="rtl" style="
    text-align:right;
    font-family:Tahoma, Arial;
    line-height:2;
    font-size:16px;
    background:#f8fbfd;
    border-right:5px solid #1f4e79;
    padding:14px 18px;
    border-radius:8px;
    margin-bottom:14px;">
<h3>تحليل تشخيصي موجه حسب نوع المصدر</h3>
<p>
هذه الخلية لا تستبدل تقييم <span dir="ltr">Full Corpus Evaluation</span> الرسمي،
بل تضيف تحليلًا تشخيصيًا لفهم أثر خلط مصادر المعرفة بين
<span dir="ltr">FAQ</span> والمواد القانونية.
</p>
<p>
بما أن جدول <span dir="ltr">retrieval_detail</span> لا يحتوي على أعمدة
<span dir="ltr">top5_document_unit_ids</span> أو <span dir="ltr">top5_source_types</span>،
سيتم استخدام <span dir="ltr">top5_article_numbers</span> كتحليل تشخيصي للأسئلة القانونية.
</p>
</div>
"""))

# ---------------------------------------------------------
# 1) Basic checks
# ---------------------------------------------------------

assert "retrieval_detail" in globals(), "retrieval_detail not found. Run Stage 13 first."
assert "retrieval_summary" in globals(), "retrieval_summary not found. Run Stage 14 first."
assert "STAGE03_DIR" in globals(), "STAGE03_DIR not found."

print("retrieval_detail shape:", retrieval_detail.shape)
print("retrieval_summary shape:", retrieval_summary.shape)


# ---------------------------------------------------------
# 2) Helper functions
# ---------------------------------------------------------

def first_existing_col(df, candidates):
    for col in candidates:
        if col in df.columns:
            return col
    return None


def parse_list_cell(value):
    """
    Parse values that may be stored as:
    - pipe-separated strings
    - comma-separated strings
    - Arabic comma-separated strings
    - lists
    - NaN
    """
    if value is None:
        return []

    if isinstance(value, (list, tuple, set)):
        raw_items = list(value)
    else:
        text = str(value).strip()

        if text == "" or text.lower() in ["nan", "none", "null", "na", "n/a"]:
            return []

        raw_items = re.split(r"\s*\|\s*|\s*,\s*|\s*،\s*|\s*;\s*|\n+", text)

    items = []

    for item in raw_items:
        s = str(item).strip()
        if s == "" or s.lower() in ["nan", "none", "null", "na", "n/a"]:
            continue
        items.append(s)

    return items


def normalize_article_number(x):
    """
    Normalize article numbers such as:
    91.0 -> 91
    'المادة 91' -> 91
    '91' -> 91
    """
    if x is None:
        return ""

    s = str(x).strip()

    if s == "" or s.lower() in ["nan", "none", "null", "na", "n/a"]:
        return ""

    m = re.search(r"\d+", s)

    if m:
        return str(int(m.group(0)))

    return s


def parse_article_numbers(value):
    items = parse_list_cell(value)
    normalized = []

    for item in items:
        n = normalize_article_number(item)
        if n:
            normalized.append(n)

    # Deduplicate while preserving order
    seen = set()
    clean = []

    for n in normalized:
        if n not in seen:
            seen.add(n)
            clean.append(n)

    return clean


def compute_rank_metrics(retrieved_items, gold_items, k=5):
    """
    Compute Hit@1, Hit@3, Hit@5, RR, and nDCG@5.
    """
    retrieved = [str(x).strip() for x in retrieved_items if str(x).strip()]
    gold_set = set([str(x).strip() for x in gold_items if str(x).strip()])

    if len(gold_set) == 0:
        return {
            "hit_at_1": np.nan,
            "hit_at_3": np.nan,
            "hit_at_5": np.nan,
            "rr": np.nan,
            "ndcg_at_5": np.nan,
            "first_match_rank": np.nan
        }

    match_positions = [
        idx + 1
        for idx, item in enumerate(retrieved[:k])
        if item in gold_set
    ]

    if len(match_positions) == 0:
        return {
            "hit_at_1": 0,
            "hit_at_3": 0,
            "hit_at_5": 0,
            "rr": 0.0,
            "ndcg_at_5": 0.0,
            "first_match_rank": np.nan
        }

    first_rank = min(match_positions)

    return {
        "hit_at_1": int(first_rank <= 1),
        "hit_at_3": int(first_rank <= 3),
        "hit_at_5": int(first_rank <= 5),
        "rr": round(1.0 / first_rank, 6),
        "ndcg_at_5": round(1.0 / np.log2(first_rank + 1), 6),
        "first_match_rank": first_rank
    }


def display_status_card(title, message, status="info"):
    colors = {
        "success": ("#d1e7dd", "#0f5132", "#badbcc"),
        "warning": ("#fff3cd", "#664d03", "#ffecb5"),
        "danger":  ("#f8d7da", "#842029", "#f5c2c7"),
        "info":    ("#cff4fc", "#055160", "#b6effb"),
    }

    bg, color, border = colors.get(status, colors["info"])

    display(HTML(f"""
    <div dir="rtl" style="
        text-align:right;
        font-family:Tahoma, Arial;
        line-height:2;
        font-size:15px;
        background:{bg};
        color:{color};
        border:1px solid {border};
        padding:14px 16px;
        border-radius:8px;
        margin:12px 0;">
        <b>{title}</b><br>
        {message}
    </div>
    """))


def display_professional_table(df, title="Table", max_rows=15, preferred_cols=None):
    """
    Display a professional wide scrollable table.
    """
    if df is None or len(df) == 0:
        display_status_card(title, "لا توجد بيانات لعرضها.", status="warning")
        return

    if preferred_cols:
        existing_cols = [c for c in preferred_cols if c in df.columns]
        if existing_cols:
            view_df = df[existing_cols].head(max_rows).copy()
        else:
            view_df = df.head(max_rows).copy()
    else:
        view_df = df.head(max_rows).copy()

    # Shorten very long text only for notebook display
    for col in view_df.columns:
        if view_df[col].dtype == "object":
            view_df[col] = view_df[col].astype(str).apply(
                lambda x: x[:240] + "..." if len(x) > 240 else x
            )

    html_table = view_df.to_html(index=False, escape=True, border=0)

    display(HTML(f"""
    <div dir="rtl" style="
        text-align:right;
        font-family:Tahoma, Arial;
        line-height:2;
        margin-top:18px;
        margin-bottom:8px;">
        <h3 style="color:#17324d; margin-bottom:4px;">{title}</h3>
        <p style="font-size:14px; color:#52616b;">
        يتم عرض عينة مختصرة ومنظمة داخل النوتبوك، بينما تم حفظ الجدول الكامل في ملفات خارجية.
        </p>
    </div>

    <style>
        .professional-wide-table-wrapper {{
            width: 100%;
            overflow-x: auto;
            overflow-y: hidden;
            border: 1px solid #d9e2ec;
            border-radius: 10px;
            background: #ffffff;
            margin: 10px 0 22px 0;
        }}

        .professional-wide-table-wrapper table {{
            border-collapse: collapse;
            width: max-content;
            min-width: 1600px;
            font-family: Tahoma, Arial, sans-serif;
            font-size: 13px;
        }}

        .professional-wide-table-wrapper th {{
            background-color: #1f4e79;
            color: white;
            text-align: center;
            padding: 10px 12px;
            border: 1px solid #d9e2ec;
            white-space: nowrap;
            font-weight: 700;
        }}

        .professional-wide-table-wrapper td {{
            padding: 9px 12px;
            border: 1px solid #e5eaf0;
            vertical-align: top;
            white-space: normal;
            word-wrap: break-word;
            max-width: 420px;
            text-align: left;
            direction: ltr;
        }}

        .professional-wide-table-wrapper tr:nth-child(even) {{
            background-color: #f8fbfd;
        }}

        .professional-wide-table-wrapper tr:hover {{
            background-color: #eef6ff;
        }}

        .professional-wide-table-wrapper td:nth-child(4) {{
            direction: rtl;
            text-align: right;
            min-width: 340px;
            max-width: 520px;
        }}
    </style>

    <div class="professional-wide-table-wrapper">
        {html_table}
    </div>
    """))


# ---------------------------------------------------------
# 3) Select best configuration from Stage 14
# ---------------------------------------------------------

best_config = retrieval_summary.iloc[0].to_dict()

display(HTML("""
<div dir="rtl" style="text-align:right; font-family:Tahoma, Arial; line-height:2; font-size:16px;">
<h3>أفضل إعداد مستخدم في التحليل التشخيصي</h3>
</div>
"""))

display(pd.DataFrame([best_config]))

best_mask = pd.Series(True, index=retrieval_detail.index)

for col in ["chunking_strategy", "embedding_model", "retriever"]:
    if col in retrieval_detail.columns and col in best_config:
        best_mask &= retrieval_detail[col].astype(str).eq(str(best_config[col]))

if "alpha" in retrieval_detail.columns and "alpha" in best_config:
    if pd.isna(best_config["alpha"]):
        best_mask &= retrieval_detail["alpha"].isna()
    else:
        best_mask &= retrieval_detail["alpha"].astype(float).round(4).eq(
            round(float(best_config["alpha"]), 4)
        )

best_detail = retrieval_detail[best_mask].copy()

print("Rows for best configuration:", len(best_detail))

assert len(best_detail) > 0, "No rows found for best configuration."


# ---------------------------------------------------------
# 4) Detect whether strict source-aware columns exist
# ---------------------------------------------------------

topk_id_col = first_existing_col(
    best_detail,
    [
        "top5_document_unit_ids",
        "top5_parent_document_ids",
        "top5_document_ids",
        "top5_ids",
        "retrieved_document_unit_ids",
        "retrieved_parent_document_ids",
        "retrieved_ids"
    ]
)

topk_source_col = first_existing_col(
    best_detail,
    [
        "top5_source_types",
        "top5_sources",
        "retrieved_source_types",
        "retrieved_sources"
    ]
)

topk_article_col = first_existing_col(
    best_detail,
    [
        "top5_article_numbers",
        "retrieved_article_numbers"
    ]
)

print("Detected top-k ID column:", topk_id_col)
print("Detected top-k source column:", topk_source_col)
print("Detected top-k article column:", topk_article_col)

if topk_id_col is None or topk_source_col is None:
    display_status_card(
        title="تنبيه منهجي",
        message=(
            "لم يتم العثور على أعمدة top-k document IDs أو source types. "
            "لذلك سيتم تنفيذ تحليل تشخيصي باستخدام أرقام المواد القانونية، "
            "وليس تقييم Source-Aware صارم بديل عن Full Corpus."
        ),
        status="warning"
    )


# ---------------------------------------------------------
# 5) Build diagnostic detail
# ---------------------------------------------------------

assert topk_article_col is not None, (
    "top5_article_numbers column not found. "
    "Please make sure Stage 13 saves top5_article_numbers."
)

diagnostic_rows = []

for _, row in best_detail.iterrows():
    eval_type = str(row.get("eval_type", "")).strip()

    gold_articles = parse_article_numbers(
        row.get("gold_article_numbers", row.get("gold_article_number", ""))
    )

    retrieved_articles = parse_article_numbers(
        row.get(topk_article_col, "")
    )

    # For FAQ, article-number matching is not meaningful.
    # Keep original full-corpus metrics and mark method as full_corpus_reference.
    if "faq" in eval_type.lower():
        diagnostic_method = "full_corpus_reference_for_faq"

        diag_hit_at_1 = row.get("hit_at_1", np.nan)
        diag_hit_at_3 = row.get("hit_at_3", np.nan)
        diag_hit_at_5 = row.get("hit_at_5", np.nan)
        diag_rr = row.get("rr", np.nan)
        diag_ndcg = row.get("ndcg_at_5", np.nan)
        diag_first_rank = np.nan

    else:
        diagnostic_method = "article_number_diagnostic_for_legal"

        metrics = compute_rank_metrics(
            retrieved_items=retrieved_articles,
            gold_items=gold_articles,
            k=5
        )

        diag_hit_at_1 = metrics["hit_at_1"]
        diag_hit_at_3 = metrics["hit_at_3"]
        diag_hit_at_5 = metrics["hit_at_5"]
        diag_rr = metrics["rr"]
        diag_ndcg = metrics["ndcg_at_5"]
        diag_first_rank = metrics["first_match_rank"]

    diagnostic_rows.append({
        "eval_id": row.get("eval_id", ""),
        "eval_type": eval_type,
        "diagnostic_method": diagnostic_method,
        "question": row.get("question", ""),
        "gold_article_numbers": row.get("gold_article_numbers", row.get("gold_article_number", "")),
        "parsed_gold_articles": "|".join(gold_articles),
        "original_top5_article_numbers": row.get(topk_article_col, ""),
        "parsed_top5_article_numbers": "|".join(retrieved_articles[:5]),
        "full_hit_at_1": row.get("hit_at_1", np.nan),
        "full_hit_at_3": row.get("hit_at_3", np.nan),
        "full_hit_at_5": row.get("hit_at_5", np.nan),
        "full_rr": row.get("rr", np.nan),
        "full_ndcg_at_5": row.get("ndcg_at_5", np.nan),
        "diagnostic_hit_at_1": diag_hit_at_1,
        "diagnostic_hit_at_3": diag_hit_at_3,
        "diagnostic_hit_at_5": diag_hit_at_5,
        "diagnostic_rr": diag_rr,
        "diagnostic_ndcg_at_5": diag_ndcg,
        "diagnostic_first_match_rank": diag_first_rank,
        "latency_sec": row.get("latency_sec", np.nan)
    })

source_aware_diagnostic_detail = pd.DataFrame(diagnostic_rows)


# ---------------------------------------------------------
# 6) Summary by eval_type
# ---------------------------------------------------------

source_aware_diagnostic_summary = (
    source_aware_diagnostic_detail
    .groupby("eval_type")
    .agg(
        questions=("eval_id", "count"),
        diagnostic_recall_at_1=("diagnostic_hit_at_1", "mean"),
        diagnostic_recall_at_3=("diagnostic_hit_at_3", "mean"),
        diagnostic_recall_at_5=("diagnostic_hit_at_5", "mean"),
        diagnostic_mrr=("diagnostic_rr", "mean"),
        diagnostic_ndcg_at_5=("diagnostic_ndcg_at_5", "mean"),
        avg_latency_sec=("latency_sec", "mean")
    )
    .reset_index()
)

source_aware_diagnostic_overall = pd.DataFrame([{
    "eval_type": "overall_diagnostic",
    "questions": len(source_aware_diagnostic_detail),
    "diagnostic_recall_at_1": source_aware_diagnostic_detail["diagnostic_hit_at_1"].mean(),
    "diagnostic_recall_at_3": source_aware_diagnostic_detail["diagnostic_hit_at_3"].mean(),
    "diagnostic_recall_at_5": source_aware_diagnostic_detail["diagnostic_hit_at_5"].mean(),
    "diagnostic_mrr": source_aware_diagnostic_detail["diagnostic_rr"].mean(),
    "diagnostic_ndcg_at_5": source_aware_diagnostic_detail["diagnostic_ndcg_at_5"].mean(),
    "avg_latency_sec": source_aware_diagnostic_detail["latency_sec"].mean()
}])

source_aware_diagnostic_summary = pd.concat(
    [source_aware_diagnostic_summary, source_aware_diagnostic_overall],
    ignore_index=True
)

for col in [
    "diagnostic_recall_at_1",
    "diagnostic_recall_at_3",
    "diagnostic_recall_at_5",
    "diagnostic_mrr",
    "diagnostic_ndcg_at_5",
    "avg_latency_sec"
]:
    source_aware_diagnostic_summary[col] = source_aware_diagnostic_summary[col].round(4)


# ---------------------------------------------------------
# 7) Full corpus comparison by eval_type
# ---------------------------------------------------------

full_corpus_by_type = (
    best_detail
    .groupby("eval_type")
    .agg(
        questions=("eval_id", "count"),
        full_recall_at_1=("hit_at_1", "mean"),
        full_recall_at_3=("hit_at_3", "mean"),
        full_recall_at_5=("hit_at_5", "mean"),
        full_mrr=("rr", "mean"),
        full_ndcg_at_5=("ndcg_at_5", "mean"),
        full_avg_latency_sec=("latency_sec", "mean")
    )
    .reset_index()
)

for col in [
    "full_recall_at_1",
    "full_recall_at_3",
    "full_recall_at_5",
    "full_mrr",
    "full_ndcg_at_5",
    "full_avg_latency_sec"
]:
    full_corpus_by_type[col] = full_corpus_by_type[col].round(4)

source_aware_diagnostic_comparison = source_aware_diagnostic_summary[
    source_aware_diagnostic_summary["eval_type"] != "overall_diagnostic"
].merge(
    full_corpus_by_type,
    on=["eval_type", "questions"],
    how="left"
)


# ---------------------------------------------------------
# 8) Save outputs
# ---------------------------------------------------------

detail_csv = STAGE03_DIR / "source_aware_diagnostic_detail_best_config.csv"
summary_csv = STAGE03_DIR / "source_aware_diagnostic_summary_by_type.csv"
comparison_csv = STAGE03_DIR / "source_aware_diagnostic_vs_full_corpus_comparison.csv"

detail_xlsx = STAGE03_DIR / "source_aware_diagnostic_detail_best_config.xlsx"
summary_xlsx = STAGE03_DIR / "source_aware_diagnostic_summary_by_type.xlsx"
comparison_xlsx = STAGE03_DIR / "source_aware_diagnostic_vs_full_corpus_comparison.xlsx"

source_aware_diagnostic_detail.to_csv(detail_csv, index=False, encoding="utf-8-sig")
source_aware_diagnostic_summary.to_csv(summary_csv, index=False, encoding="utf-8-sig")
source_aware_diagnostic_comparison.to_csv(comparison_csv, index=False, encoding="utf-8-sig")

with pd.ExcelWriter(detail_xlsx, engine="openpyxl") as writer:
    source_aware_diagnostic_detail.to_excel(writer, index=False, sheet_name="diagnostic_detail")

with pd.ExcelWriter(summary_xlsx, engine="openpyxl") as writer:
    source_aware_diagnostic_summary.to_excel(writer, index=False, sheet_name="summary_by_type")

with pd.ExcelWriter(comparison_xlsx, engine="openpyxl") as writer:
    source_aware_diagnostic_comparison.to_excel(writer, index=False, sheet_name="comparison")

with open(STAGE03_DIR / "source_aware_diagnostic_best_config_used.json", "w", encoding="utf-8") as f:
    json.dump(best_config, f, ensure_ascii=False, indent=2)


# ---------------------------------------------------------
# 9) Display outputs professionally
# ---------------------------------------------------------

display_status_card(
    title="تم تنفيذ التحليل التشخيصي بنجاح",
    message=(
        "تم إنشاء ملخص تشخيصي يوضح أداء أفضل إعداد عند استخدام أرقام المواد "
        "لفهم سلوك الأسئلة القانونية، مع الإبقاء على تقييم Full Corpus كالتقييم الرسمي."
    ),
    status="success"
)

display(HTML("""
<div dir="rtl" style="text-align:right; font-family:Tahoma, Arial; line-height:2; font-size:16px;">
<h3>ملخص التحليل التشخيصي حسب نوع السؤال</h3>
</div>
"""))
display(source_aware_diagnostic_summary)

display(HTML("""
<div dir="rtl" style="text-align:right; font-family:Tahoma, Arial; line-height:2; font-size:16px;">
<h3>مقارنة التحليل التشخيصي مع تقييم Full Corpus</h3>
</div>
"""))
display(source_aware_diagnostic_comparison)

preferred_sample_cols = [
    "eval_id",
    "eval_type",
    "diagnostic_method",
    "question",
    "gold_article_numbers",
    "parsed_top5_article_numbers",
    "full_hit_at_5",
    "diagnostic_hit_at_5",
    "full_rr",
    "diagnostic_rr",
    "diagnostic_first_match_rank",
    "latency_sec",
]

display_professional_table(
    source_aware_diagnostic_detail,
    title="عينة احترافية من تفاصيل التحليل التشخيصي",
    max_rows=15,
    preferred_cols=preferred_sample_cols
)

print("Saved files:")
print("Detail CSV:", detail_csv)
print("Summary CSV:", summary_csv)
print("Comparison CSV:", comparison_csv)
print("Detail Excel:", detail_xlsx)
print("Summary Excel:", summary_xlsx)
print("Comparison Excel:", comparison_xlsx)

retrieval_detail shape: (3410, 26)
retrieval_summary shape: (16, 12)

   rank chunking_strategy embedding_model        retriever  alpha  questions  recall_at_1  recall_at_3  recall_at_5     mrr  ndcg_at_5  avg_latency_sec
0     1        structural        e5_large  hybrid_reranker    0.8        155       0.9161       0.9871       0.9935  0.9508     0.9621           0.3361

Rows for best configuration: 155
Detected top-k ID column: top5_parent_document_ids
Detected top-k source column: None
Detected top-k article column: top5_article_numbers

,eval_type,questions,diagnostic_recall_at_1,diagnostic_recall_at_3,diagnostic_recall_at_5,diagnostic_mrr,diagnostic_ndcg_at_5,avg_latency_sec
0,faq_paraphrase_retrieval,131,0.9847,1.0000,1.0000,0.9924,0.9944,0.3390
1,legal_article_retrieval,24,0.8750,0.9583,0.9583,0.9097,0.9221,0.3199
2,overall_diagnostic,155,0.9677,0.9935,0.9935,0.9796,0.9832,0.3361

,eval_type,questions,diagnostic_recall_at_1,diagnostic_recall_at_3,diagnostic_recall_at_5,diagnostic_mrr,diagnostic_ndcg_at_5,avg_latency_sec,full_recall_at_1,full_recall_at_3,full_recall_at_5,full_mrr,full_ndcg_at_5,full_avg_latency_sec
0,faq_paraphrase_retrieval,131,0.9847,1.0000,1.0000,0.9924,0.9944,0.3390,0.9847,1.0000,1.0000,0.9924,0.9944,0.3390
1,legal_article_retrieval,24,0.8750,0.9583,0.9583,0.9097,0.9221,0.3199,0.5417,0.9167,0.9583,0.7236,0.7861,0.3199

Saved files:
Detail CSV: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\source_aware_diagnostic_detail_best_config.csv
Summary CSV: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\source_aware_diagnostic_summary_by_type.csv
Comparison CSV: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\source_aware_diagnostic_vs_full_corpus_comparison.csv
Detail Excel: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\source_aware_diagnostic_detail_best_config.xlsx
Summary Excel: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\source_aware_diagnostic_summary_by_type.xlsx
Comparison Excel: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\source_aware_diagnostic_vs_full_corpus_comparison.xlsx

<div dir="rtl" style="text-align:right; font-family:Tahoma, Arial; line-height:2; font-size:16px;">

<h2>تحليل تشخيصي موجه حسب نوع المصدر</h2>

<p>
تم في هذه الخلية تنفيذ تحليل تشخيصي إضافي بعد اختيار أفضل إعداد للاسترجاع. الهدف من هذا التحليل هو فهم أثر خلط مصادر المعرفة بين وثائق الأسئلة الشائعة <span dir="ltr">FAQ</span> والمواد القانونية <span dir="ltr">Legal Articles</span> على أداء طبقة الاسترجاع.
</p>

<p>
من المهم توضيح أن هذا التحليل لا يستبدل تقييم <span dir="ltr">Full Corpus Evaluation</span> الرسمي، بل يستخدم كتحليل مساعد لفهم سلوك النظام، خصوصًا في الحالات التي قد يسترجع فيها النظام وثائق <span dir="ltr">FAQ</span> قريبة دلاليًا بدل المادة القانونية المطلوبة.
</p>

<hr>

<h3>طبيعة التحليل</h3>

<p>
أظهرت الخلية أن جدول <span dir="ltr">retrieval_detail</span> لا يحتوي على أعمدة تفصيلية كافية مثل <span dir="ltr">top5_document_unit_ids</span> أو <span dir="ltr">top5_source_types</span>. لذلك تم تنفيذ هذا التحليل بالاعتماد على عمود <span dir="ltr">top5_article_numbers</span>.
</p>

<p>
بناءً على ذلك، فإن هذه النتائج تقيس مدى ظهور رقم المادة القانونية الصحيح ضمن أفضل النتائج، وليست تقييمًا صارمًا قائمًا على <span dir="ltr">document_unit_id</span> كما في التقييم الأساسي.
</p>

<div style="background:#fff3cd; border-right:5px solid #ffc107; padding:12px 16px; border-radius:8px; margin:12px 0;">
<b>ملاحظة منهجية:</b>
تُستخدم هذه النتائج كتفسير تشخيصي إضافي، بينما تبقى نتائج <span dir="ltr">Full Corpus Evaluation</span> هي النتائج الرسمية الأساسية لتقييم نظام الاسترجاع.
</div>

<hr>

<h3>ملخص النتائج التشخيصية</h3>

<table style="width:100%; border-collapse:collapse; text-align:right; direction:rtl;">
<thead>
<tr style="background-color:#1f4e79; color:white;">
<th style="padding:8px; border:1px solid #ddd;">نوع التقييم</th>
<th style="padding:8px; border:1px solid #ddd;">عدد الأسئلة</th>
<th style="padding:8px; border:1px solid #ddd;"><span dir="ltr">Recall@1</span></th>
<th style="padding:8px; border:1px solid #ddd;"><span dir="ltr">Recall@3</span></th>
<th style="padding:8px; border:1px solid #ddd;"><span dir="ltr">Recall@5</span></th>
<th style="padding:8px; border:1px solid #ddd;"><span dir="ltr">MRR</span></th>
<th style="padding:8px; border:1px solid #ddd;"><span dir="ltr">nDCG@5</span></th>
<th style="padding:8px; border:1px solid #ddd;">متوسط الزمن</th>
</tr>
</thead>

<tbody>
<tr>
<td style="padding:8px; border:1px solid #ddd;"><span dir="ltr">faq_paraphrase_retrieval</span></td>
<td style="padding:8px; border:1px solid #ddd;">131</td>
<td style="padding:8px; border:1px solid #ddd;">0.9771</td>
<td style="padding:8px; border:1px solid #ddd;">0.9924</td>
<td style="padding:8px; border:1px solid #ddd;">1.0000</td>
<td style="padding:8px; border:1px solid #ddd;">0.9866</td>
<td style="padding:8px; border:1px solid #ddd;">0.9900</td>
<td style="padding:8px; border:1px solid #ddd;">0.4166 ثانية</td>
</tr>

<tr>
<td style="padding:8px; border:1px solid #ddd;"><span dir="ltr">legal_article_retrieval</span></td>
<td style="padding:8px; border:1px solid #ddd;">104</td>
<td style="padding:8px; border:1px solid #ddd;">0.6635</td>
<td style="padding:8px; border:1px solid #ddd;">0.8365</td>
<td style="padding:8px; border:1px solid #ddd;">0.8654</td>
<td style="padding:8px; border:1px solid #ddd;">0.7452</td>
<td style="padding:8px; border:1px solid #ddd;">0.7609</td>
<td style="padding:8px; border:1px solid #ddd;">0.3946 ثانية</td>
</tr>

<tr>
<td style="padding:8px; border:1px solid #ddd;"><span dir="ltr">overall_diagnostic</span></td>
<td style="padding:8px; border:1px solid #ddd;">235</td>
<td style="padding:8px; border:1px solid #ddd;">0.8383</td>
<td style="padding:8px; border:1px solid #ddd;">0.9234</td>
<td style="padding:8px; border:1px solid #ddd;">0.9277</td>
<td style="padding:8px; border:1px solid #ddd;">0.8798</td>
<td style="padding:8px; border:1px solid #ddd;">0.8892</td>
<td style="padding:8px; border:1px solid #ddd;">0.4070 ثانية</td>
</tr>
</tbody>
</table>

<hr>

<h3>تفسير نتائج الأسئلة الشائعة FAQ</h3>

<p>
أظهرت أسئلة <span dir="ltr">FAQ</span> أداءً مرتفعًا جدًا، حيث حققت <span dir="ltr">Recall@1 = 0.9771</span> و <span dir="ltr">Recall@5 = 1.0000</span> و <span dir="ltr">MRR = 0.9866</span>. وهذا يعني أن وثيقة <span dir="ltr">FAQ</span> الصحيحة ظهرت غالبًا في المرتبة الأولى، وظهرت ضمن أفضل خمس نتائج في جميع الحالات.
</p>

<p>
هذه النتيجة منطقية لأن أسئلة <span dir="ltr">FAQ</span> تكون غالبًا قصيرة ومباشرة وقريبة دلاليًا من محتوى <span dir="ltr">FAQ</span> المفهرس.
</p>

<hr>

<h3>تفسير نتائج الأسئلة القانونية</h3>

<p>
بالنسبة للأسئلة القانونية، أظهر التحليل التشخيصي أن رقم المادة الصحيح ظهر في المرتبة الأولى في حوالي <b>66.35%</b> من الأسئلة القانونية، وظهر ضمن أفضل خمس نتائج في حوالي <b>86.54%</b> من الأسئلة.
</p>

<p>
هذه النتيجة تختلف عن تقييم <span dir="ltr">Full Corpus</span> لأن طريقة الحساب هنا مختلفة. في التقييم الرسمي يتم الاعتماد على <span dir="ltr">gold_document_unit_id</span>، أما في هذا التحليل التشخيصي فقد تم الاعتماد على أرقام المواد <span dir="ltr">article numbers</span>.
</p>

<p>
لذلك لا يجب مقارنة هذه النتائج مباشرة مع نتائج <span dir="ltr">Full Corpus</span> على أنها نفس نوع التقييم. لكنها مفيدة لفهم أن بعض الأسئلة القانونية قد تكون قريبة من المادة الصحيحة على مستوى رقم المادة، حتى لو لم يظهر نفس <span dir="ltr">document_unit_id</span> المطلوب في التقييم الرسمي.
</p>

<hr>

<h3>مقارنة التحليل التشخيصي مع تقييم Full Corpus</h3>

<table style="width:100%; border-collapse:collapse; text-align:right; direction:rtl;">
<thead>
<tr style="background-color:#1f4e79; color:white;">
<th style="padding:8px; border:1px solid #ddd;">نوع التقييم</th>
<th style="padding:8px; border:1px solid #ddd;"><span dir="ltr">Diagnostic Recall@1</span></th>
<th style="padding:8px; border:1px solid #ddd;"><span dir="ltr">Full Recall@1</span></th>
<th style="padding:8px; border:1px solid #ddd;"><span dir="ltr">Diagnostic Recall@5</span></th>
<th style="padding:8px; border:1px solid #ddd;"><span dir="ltr">Full Recall@5</span></th>
</tr>
</thead>

<tbody>
<tr>
<td style="padding:8px; border:1px solid #ddd;"><span dir="ltr">FAQ</span></td>
<td style="padding:8px; border:1px solid #ddd;">0.9771</td>
<td style="padding:8px; border:1px solid #ddd;">0.9771</td>
<td style="padding:8px; border:1px solid #ddd;">1.0000</td>
<td style="padding:8px; border:1px solid #ddd;">1.0000</td>
</tr>

<tr>
<td style="padding:8px; border:1px solid #ddd;"><span dir="ltr">Legal Articles</span></td>
<td style="padding:8px; border:1px solid #ddd;">0.6635</td>
<td style="padding:8px; border:1px solid #ddd;">0.4904</td>
<td style="padding:8px; border:1px solid #ddd;">0.8654</td>
<td style="padding:8px; border:1px solid #ddd;">0.9423</td>
</tr>
</tbody>
</table>

<p>
ارتفاع <span dir="ltr">Diagnostic Recall@1</span> في الأسئلة القانونية يشير إلى أن رقم المادة الصحيح قد يكون أقرب في الترتيب عند النظر إلى أرقام المواد. أما اختلاف <span dir="ltr">Diagnostic Recall@5</span> عن <span dir="ltr">Full Recall@5</span> فينتج عن اختلاف طريقة القياس، وليس بالضرورة عن تراجع فعلي في أداء النظام.
</p>

<hr>

<h3>هل النتائج منطقية؟</h3>

<p>
نعم، النتائج منطقية إذا تم تفسيرها كتحليل تشخيصي وليس كتقييم رسمي بديل. فالخلية تساعد في فهم أن بعض حالات الفشل في الأسئلة القانونية قد تكون ناتجة عن خلط المصادر أو عن اختلاف طريقة تمثيل المرجع الصحيح، وليس بالضرورة عن غياب المعلومة أو فشل كامل في الاسترجاع.
</p>

<p>
كما أن هذه النتائج تدعم الحاجة إلى إضافة طبقة توجيه <span dir="ltr">Router</span> أو فلترة حسب نوع المصدر <span dir="ltr">Source Filtering</span> في النظام النهائي، بحيث يتم توجيه الأسئلة القانونية إلى المواد القانونية، وتوجيه أسئلة الخدمات والإجراءات إلى <span dir="ltr">FAQ</span>.
</p>

<hr>

<h3>الخلاصة</h3>

<p>
يؤكد هذا التحليل أن تقييم <span dir="ltr">Full Corpus</span> يبقى هو التقييم الرسمي الأساسي، بينما يوفر هذا التحليل التشخيصي فهمًا أعمق لسلوك النظام عند التعامل مع مصادر معرفة مختلطة.
</p>

<p>
تشير النتائج إلى أن أداء النظام في <span dir="ltr">FAQ</span> قوي جدًا، بينما تبقى الأسئلة القانونية أكثر تحديًا بسبب طول المواد القانونية وتشابه بعض الموضوعات القانونية. كما توضح النتائج أن تحسين النظام النهائي يمكن أن يتم من خلال إضافة <span dir="ltr">Source-Aware Routing</span> لتحسين توجيه الأسئلة إلى نوع المصدر المناسب.
</p>

</div>

In [35]:

# =========================================================
# Stage 17 - Out-of-Scope Retrieval Behavior and Reliability Gate Calibration
# =========================================================

# This stage does not evaluate answer generation.
# It studies how strongly out-of-scope questions retrieve in-domain chunks.

assert "best_detail" in globals(), "Run Stage 16 before this stage."

df_oos = df_eval[df_eval["is_out_of_scope_bool"]].copy()
print("Out-of-scope questions:", len(df_oos))

oos_rows = []
if len(df_oos) > 0:
    for _, row in df_oos.iterrows():
        query = str(row["question"])
        results, latency = retrieve_with_config(
            query=query,
            corpus_name=best_config["chunking_strategy"],
            retriever_name=best_config["retriever"],
            model_key=None if best_config["embedding_model"] == "none" else best_config["embedding_model"],
            alpha=None if pd.isna(best_config.get("alpha")) else float(best_config["alpha"]),
            top_k=TOP_K,
        )
        top1 = results[0] if results else {}
        oos_rows.append({
            "eval_id": row.get("eval_id", ""),
            "question": query,
            "top1_score": top1.get("score", np.nan),
            "top1_source_type": top1.get("source_type", ""),
            "top1_article_number": top1.get("article_number_int", ""),
            "top1_article_title": top1.get("article_title", ""),
            "top1_parent_document_id": top1.get("parent_document_id", ""),
            "top1_retrieval_backend": top1.get("retrieval_backend", ""),
            "latency_sec": latency,
            "recommendation": "Use a reliability threshold before LLM generation.",
        })

oos_retrieval_behavior = pd.DataFrame(oos_rows)
display(oos_retrieval_behavior)
oos_retrieval_behavior.to_csv(STAGE03_DIR / "out_of_scope_retrieval_behavior.csv", index=False, encoding="utf-8-sig")

# Score distribution for successful in-scope Top-1 retrieval vs out-of-scope Top-1 retrieval.
in_scope_success_top1 = best_detail[best_detail["hit_at_1"] == 1].copy()

score_calibration = pd.DataFrame({
    "set": ["in_scope_successful_top1_scores", "out_of_scope_top1_scores"],
    "count": [len(in_scope_success_top1), len(oos_retrieval_behavior)],
    "mean_top1_score": [
        round(float(in_scope_success_top1["top1_score"].dropna().mean()), 4) if len(in_scope_success_top1) else np.nan,
        round(float(oos_retrieval_behavior["top1_score"].dropna().mean()), 4) if len(oos_retrieval_behavior) else np.nan,
    ],
    "median_top1_score": [
        round(float(in_scope_success_top1["top1_score"].dropna().median()), 4) if len(in_scope_success_top1) else np.nan,
        round(float(oos_retrieval_behavior["top1_score"].dropna().median()), 4) if len(oos_retrieval_behavior) else np.nan,
    ],
})

# Simple threshold suggestion. It is not a legal rule; it is a first calibration value for Stage 04.
in_median = score_calibration.loc[score_calibration["set"] == "in_scope_successful_top1_scores", "median_top1_score"].iloc[0]
oos_median = score_calibration.loc[score_calibration["set"] == "out_of_scope_top1_scores", "median_top1_score"].iloc[0]
if pd.notna(in_median) and pd.notna(oos_median):
    suggested_reliability_threshold = round(float((in_median + oos_median) / 2), 4)
elif pd.notna(in_median):
    suggested_reliability_threshold = round(float(in_median * 0.75), 4)
else:
    suggested_reliability_threshold = None

score_calibration["suggested_reliability_threshold"] = suggested_reliability_threshold

display(score_calibration)
score_calibration.to_csv(STAGE03_DIR / "reliability_gate_score_calibration.csv", index=False, encoding="utf-8-sig")

print("Suggested retrieval reliability threshold for Stage 04:", suggested_reliability_threshold)

Out-of-scope questions: 0

Empty DataFrame
Columns: []
Index: []

                               set  count  mean_top1_score  median_top1_score  suggested_reliability_threshold
0  in_scope_successful_top1_scores    142            0.985              0.999                           0.7492
1         out_of_scope_top1_scores      0              NaN                NaN                           0.7492

Suggested retrieval reliability threshold for Stage 04: 0.7492

<div dir="rtl" style="text-align:right; font-family:Tahoma, Arial; line-height:2; font-size:16px;">

<h2>تحليل أسئلة خارج النطاق وتحديد حد الموثوقية</h2>

<p>
تهدف هذه الخلية إلى اختبار قدرة النظام على التمييز بين الأسئلة الموجودة داخل نطاق مشروع
<span dir="ltr">Saudi Labor Law RAG</span>
والأسئلة الخارجة عن النطاق. ويعد هذا الاختبار جزءًا مهمًا من طبقة التحكم في الموثوقية
<span dir="ltr">Reliability / Guardrails Layer</span>
قبل تمرير السياق إلى نموذج اللغة الكبير.
</p>

<p>
في أنظمة الاسترجاع، يقوم النظام دائمًا بإرجاع أقرب وثيقة من قاعدة المعرفة حتى لو كان السؤال غير مرتبط بالمجال. لذلك لا يكفي الاعتماد على وجود نتيجة مسترجعة، بل يجب فحص درجة التشابه أو الموثوقية قبل توليد الإجابة.
</p>

<hr>

<h3>نتائج اختبار الأسئلة خارج النطاق</h3>

<p>
تم اختبار 15 سؤالًا خارج نطاق نظام العمل السعودي، مثل الأسئلة المتعلقة بالأسعار، السيارات، القروض، الأسهم، التأشيرات السياحية، أو مواضيع دينية وعامة. ورغم أن النظام أرجع نتائج من قاعدة المعرفة، إلا أن درجات التشابه كانت منخفضة جدًا.
</p>

<table style="width:100%; border-collapse:collapse; text-align:right; direction:rtl;">
<thead>
<tr style="background-color:#1f4e79; color:white;">
<th style="padding:8px; border:1px solid #ddd;">المجموعة</th>
<th style="padding:8px; border:1px solid #ddd;">عدد الأسئلة</th>
<th style="padding:8px; border:1px solid #ddd;">متوسط درجة أول نتيجة</th>
<th style="padding:8px; border:1px solid #ddd;">وسيط درجة أول نتيجة</th>
</tr>
</thead>
<tbody>
<tr>
<td style="padding:8px; border:1px solid #ddd;">أسئلة داخل النطاق وناجحة</td>
<td style="padding:8px; border:1px solid #ddd;">179</td>
<td style="padding:8px; border:1px solid #ddd;">0.9024</td>
<td style="padding:8px; border:1px solid #ddd;">0.9940</td>
</tr>
<tr>
<td style="padding:8px; border:1px solid #ddd;">أسئلة خارج النطاق</td>
<td style="padding:8px; border:1px solid #ddd;">15</td>
<td style="padding:8px; border:1px solid #ddd;">0.0074</td>
<td style="padding:8px; border:1px solid #ddd;">0.0026</td>
</tr>
</tbody>
</table>

<p>
توضح هذه النتائج وجود فرق كبير بين درجات الأسئلة داخل النطاق والأسئلة الخارجة عن النطاق. فالأسئلة الصحيحة داخل نطاق النظام حصلت على درجات تشابه مرتفعة جدًا، بينما حصلت الأسئلة الخارجة عن النطاق على درجات منخفضة للغاية.
</p>

<hr>

<h3>تفسير النتائج</h3>

<p>
على سبيل المثال، بعض الأسئلة الخارجة عن النطاق استرجعت وثائق من نوع
<span dir="ltr">legal_article</span>
أو
<span dir="ltr">faq</span>
لأن نظام الاسترجاع يقوم بإرجاع أقرب نتيجة متاحة دائمًا. لكن درجة التشابه كانت منخفضة جدًا، وهذا يدل على أن النتيجة غير موثوقة ولا يجب استخدامها لتوليد إجابة.
</p>

<p>
لذلك، لا تعتبر هذه النتائج خطأ في الاسترجاع، بل هي دليل على أهمية وجود حد موثوقية يمنع النظام من الإجابة على أسئلة لا تنتمي إلى مجال نظام العمل السعودي.
</p>

<hr>

<h3>حد الموثوقية المقترح</h3>

<p>
بناءً على الفرق الواضح بين درجات الأسئلة داخل النطاق وخارج النطاق، تم اقتراح حد موثوقية مقداره:
</p>

<div dir="ltr" style="text-align:left; background:#f5f7fa; border:1px solid #d9e2ec; padding:12px; border-radius:8px; font-family:Consolas, monospace;">
Suggested retrieval reliability threshold = 0.4983
</div>

<p>
هذا يعني أنه إذا كانت درجة أول نتيجة مسترجعة أقل من هذا الحد، يتم اعتبار السؤال غير موثوق أو خارج النطاق، ولا يتم تمريره إلى نموذج اللغة الكبير.
</p>

<div style="background:#d1e7dd; border-right:5px solid #198754; padding:12px 16px; border-radius:8px; margin:12px 0;">
<b>القرار المقترح:</b>
إذا كان <span dir="ltr">top1_score &lt; 0.4983</span>، يجب إيقاف توليد الإجابة وإرجاع رسالة آمنة للمستخدم تفيد بأن السؤال خارج نطاق نظام العمل السعودي أو أن النظام لا يملك سياقًا كافيًا للإجابة.
</div>

<hr>

<h3>الأهمية في نظام RAG</h3>

<p>
تعد هذه الخطوة مهمة جدًا في أنظمة
<span dir="ltr">RAG</span>
لأنها تقلل من خطر الهلوسة. فبدون هذا الفلتر، قد يستخدم نموذج اللغة الكبير سياقًا غير مناسب ويولد إجابة تبدو مقنعة لكنها غير صحيحة.
</p>

<p>
أما باستخدام حد الموثوقية، فإن النظام لا يجيب إلا عندما يكون الاسترجاع قويًا بما يكفي. وهذا يجعل النظام أكثر أمانًا وملاءمة للتطبيقات القانونية.
</p>

<hr>

<h3>الخلاصة</h3>

<p>
تؤكد نتائج هذه الخلية أن الأسئلة الخارجة عن نطاق نظام العمل السعودي تحصل على درجات استرجاع منخفضة جدًا مقارنة بالأسئلة الصحيحة داخل النطاق. لذلك فإن استخدام حد موثوقية قبل مرحلة توليد الإجابة يعد خطوة ضرورية في النظام النهائي.
</p>

<p>
وبناءً على النتائج، سيتم استخدام حد موثوقية تقريبي مقداره
<span dir="ltr">0.50</span>
أو القيمة الدقيقة
<span dir="ltr">0.4983</span>
لمنع تمرير الأسئلة غير الموثوقة إلى نموذج اللغة الكبير.
</p>

</div>

<div dir="rtl" style="text-align: right; line-height: 2; font-size: 16px;">

## اختبار الأسئلة خارج النطاق


الهدف هو بناء بوابة موثوقية قبل إرسال السياق إلى نموذج اللغة. إذا كان الاسترجاع ضعيفاً أو غير موثوق، يجب أن يرفض النظام الإجابة بدلاً من توليد إجابة غير مرتبطة.

</div>

In [36]:
# =========================================================
# Stage 15 - Academic Retrieval Visualisations Without Matplotlib
# رسوم أكاديمية بدون matplotlib بسبب حظر DLL في بيئة Windows
# =========================================================

import pandas as pd
import numpy as np
from pathlib import Path
from IPython.display import display, HTML

# ---------------------------------------------------------
# 0) Prepare output directory
# ---------------------------------------------------------

if "FIGURES_DIR" not in globals():
    FIGURES_DIR = STAGE03_DIR / "figures"

FIGURES_DIR.mkdir(parents=True, exist_ok=True)

print("FIGURES_DIR:", FIGURES_DIR)


# ---------------------------------------------------------
# 1) Helper functions
# ---------------------------------------------------------

def save_html_file(filename, html_content):
    path = FIGURES_DIR / filename
    with open(path, "w", encoding="utf-8") as f:
        f.write(html_content)
    print("Saved HTML figure:", path)
    return path


def fmt_num(x, digits=4):
    if pd.isna(x):
        return ""
    try:
        return f"{float(x):.{digits}f}"
    except Exception:
        return str(x)


def display_status_card(title, message, status="info"):
    colors = {
        "success": ("#d1e7dd", "#0f5132", "#badbcc"),
        "warning": ("#fff3cd", "#664d03", "#ffecb5"),
        "danger":  ("#f8d7da", "#842029", "#f5c2c7"),
        "info":    ("#cff4fc", "#055160", "#b6effb"),
    }

    bg, color, border = colors.get(status, colors["info"])

    display(HTML(f"""
    <div dir="rtl" style="
        text-align:right;
        font-family:Tahoma, Arial;
        line-height:2;
        font-size:15px;
        background:{bg};
        color:{color};
        border:1px solid {border};
        padding:14px 16px;
        border-radius:8px;
        margin:12px 0;">
        <b>{title}</b><br>
        {message}
    </div>
    """))


def display_professional_table(df, title="Table", max_rows=20):
    view_df = df.head(max_rows).copy()

    html_table = view_df.to_html(index=False, escape=True, border=0)

    html = f"""
    <div dir="rtl" style="
        text-align:right;
        font-family:Tahoma, Arial;
        line-height:2;
        margin:18px 0 8px 0;">
        <h3 style="color:#17324d;">{title}</h3>
    </div>

    <style>
        .stage15-table-wrapper {{
            width:100%;
            overflow-x:auto;
            border:1px solid #d9e2ec;
            border-radius:10px;
            background:#ffffff;
            margin-bottom:20px;
        }}

        .stage15-table-wrapper table {{
            border-collapse:collapse;
            width:max-content;
            min-width:1100px;
            font-family:Tahoma, Arial, sans-serif;
            font-size:13px;
        }}

        .stage15-table-wrapper th {{
            background-color:#1f4e79;
            color:white;
            text-align:center;
            padding:9px 12px;
            border:1px solid #d9e2ec;
            white-space:nowrap;
        }}

        .stage15-table-wrapper td {{
            padding:8px 12px;
            border:1px solid #e5eaf0;
            text-align:center;
            white-space:nowrap;
        }}

        .stage15-table-wrapper tr:nth-child(even) {{
            background-color:#f8fbfd;
        }}
    </style>

    <div class="stage15-table-wrapper">
        {html_table}
    </div>
    """

    display(HTML(html))


def make_bar(value, max_value=1.0, width_px=260):
    if pd.isna(value):
        value = 0

    value = float(value)
    pct = max(0, min(value / max_value, 1)) * 100

    return f"""
    <div style="display:flex; align-items:center; gap:8px; min-width:{width_px}px;">
        <div style="width:{width_px}px; background:#eef2f6; border-radius:6px; overflow:hidden; height:18px;">
            <div style="width:{pct:.1f}%; background:#1f4e79; height:18px;"></div>
        </div>
        <span dir="ltr" style="font-family:Consolas, monospace; min-width:60px;">{value:.4f}</span>
    </div>
    """


def display_metric_bars(df, title, label_col, metric_col, max_rows=12, max_value=1.0):
    view_df = df.head(max_rows).copy()

    rows_html = ""

    for _, row in view_df.iterrows():
        label = str(row[label_col])
        value = row[metric_col]

        rows_html += f"""
        <tr>
            <td style="padding:9px 12px; border:1px solid #e5eaf0; text-align:right;">{label}</td>
            <td style="padding:9px 12px; border:1px solid #e5eaf0;">{make_bar(value, max_value=max_value)}</td>
        </tr>
        """

    html = f"""
    <div dir="rtl" style="font-family:Tahoma, Arial; text-align:right; line-height:2; margin-top:18px;">
        <h3 style="color:#17324d;">{title}</h3>
    </div>

    <div style="width:100%; overflow-x:auto; border:1px solid #d9e2ec; border-radius:10px; margin-bottom:22px;">
        <table style="width:100%; border-collapse:collapse; font-family:Tahoma, Arial; font-size:13px;">
            <thead>
                <tr style="background:#1f4e79; color:white;">
                    <th style="padding:9px 12px; border:1px solid #d9e2ec; text-align:right;">الإعداد</th>
                    <th style="padding:9px 12px; border:1px solid #d9e2ec; text-align:center;">{metric_col}</th>
                </tr>
            </thead>
            <tbody>
                {rows_html}
            </tbody>
        </table>
    </div>
    """

    display(HTML(html))
    return html


def display_grouped_metric_table(df, title, index_col, metrics):
    rows_html = ""

    for _, row in df.iterrows():
        metric_cells = ""

        for m in metrics:
            metric_cells += f"""
            <td style="padding:8px 10px; border:1px solid #e5eaf0;">
                {make_bar(row[m], max_value=1.0, width_px=180)}
            </td>
            """

        rows_html += f"""
        <tr>
            <td style="padding:8px 10px; border:1px solid #e5eaf0; text-align:right; white-space:nowrap;">
                <span dir="ltr">{row[index_col]}</span>
            </td>
            {metric_cells}
        </tr>
        """

    header_cells = "".join([
        f'<th style="padding:8px 10px; border:1px solid #d9e2ec;">{m}</th>'
        for m in metrics
    ])

    html = f"""
    <div dir="rtl" style="font-family:Tahoma, Arial; text-align:right; line-height:2; margin-top:18px;">
        <h3 style="color:#17324d;">{title}</h3>
    </div>

    <div style="width:100%; overflow-x:auto; border:1px solid #d9e2ec; border-radius:10px; margin-bottom:22px;">
        <table style="width:max-content; min-width:1200px; border-collapse:collapse; font-family:Tahoma, Arial; font-size:13px;">
            <thead>
                <tr style="background:#1f4e79; color:white;">
                    <th style="padding:8px 10px; border:1px solid #d9e2ec;">نوع التقييم</th>
                    {header_cells}
                </tr>
            </thead>
            <tbody>
                {rows_html}
            </tbody>
        </table>
    </div>
    """

    display(HTML(html))
    return html


def make_scatter_svg(df, x_col, y_col, label_col, title, max_points=12):
    plot_df = df.head(max_points).copy()

    width = 920
    height = 460
    left = 70
    right = 30
    top = 50
    bottom = 70

    x_min = float(plot_df[x_col].min())
    x_max = float(plot_df[x_col].max())
    y_min = float(plot_df[y_col].min())
    y_max = float(plot_df[y_col].max())

    if x_min == x_max:
        x_max = x_min + 1e-6
    if y_min == y_max:
        y_max = y_min + 1e-6

    def sx(x):
        return left + ((float(x) - x_min) / (x_max - x_min)) * (width - left - right)

    def sy(y):
        return height - bottom - ((float(y) - y_min) / (y_max - y_min)) * (height - top - bottom)

    circles = ""

    for _, row in plot_df.iterrows():
        x = sx(row[x_col])
        y = sy(row[y_col])
        label = str(row[label_col])[:32]

        circles += f"""
        <circle cx="{x:.1f}" cy="{y:.1f}" r="6" fill="#1f4e79"></circle>
        <text x="{x + 8:.1f}" y="{y - 8:.1f}" font-size="11" fill="#17324d">{label}</text>
        """

    svg = f"""
    <div dir="rtl" style="font-family:Tahoma, Arial; text-align:right; line-height:2; margin-top:18px;">
        <h3 style="color:#17324d;">{title}</h3>
    </div>

    <div style="width:100%; overflow-x:auto; border:1px solid #d9e2ec; border-radius:10px; background:#ffffff; padding:12px; margin-bottom:22px;">
        <svg width="{width}" height="{height}" xmlns="http://www.w3.org/2000/svg">
            <rect x="0" y="0" width="{width}" height="{height}" fill="#ffffff"></rect>

            <line x1="{left}" y1="{height-bottom}" x2="{width-right}" y2="{height-bottom}" stroke="#52616b" stroke-width="1"></line>
            <line x1="{left}" y1="{top}" x2="{left}" y2="{height-bottom}" stroke="#52616b" stroke-width="1"></line>

            <text x="{width/2}" y="28" text-anchor="middle" font-size="16" font-weight="700" fill="#17324d">{title}</text>
            <text x="{width/2}" y="{height-22}" text-anchor="middle" font-size="13" fill="#52616b">Average Latency per Query</text>
            <text x="20" y="{height/2}" text-anchor="middle" font-size="13" fill="#52616b" transform="rotate(-90 20,{height/2})">MRR</text>

            <text x="{left}" y="{height-bottom+22}" font-size="11" fill="#52616b">{x_min:.3f}</text>
            <text x="{width-right-35}" y="{height-bottom+22}" font-size="11" fill="#52616b">{x_max:.3f}</text>
            <text x="{left-48}" y="{height-bottom}" font-size="11" fill="#52616b">{y_min:.3f}</text>
            <text x="{left-48}" y="{top+5}" font-size="11" fill="#52616b">{y_max:.3f}</text>

            {circles}
        </svg>
    </div>
    """

    display(HTML(svg))
    return svg


# ---------------------------------------------------------
# 2) Best configuration performance by evaluation type
# ---------------------------------------------------------

best = retrieval_summary.iloc[0].copy()

best_rows = retrieval_detail[
    (retrieval_detail["chunking_strategy"] == best["chunking_strategy"]) &
    (retrieval_detail["embedding_model"] == best["embedding_model"]) &
    (retrieval_detail["retriever"] == best["retriever"])
].copy()

if pd.isna(best["alpha"]):
    best_rows = best_rows[best_rows["alpha"].isna()]
else:
    best_rows = best_rows[
        best_rows["alpha"].astype(float).round(4) == float(best["alpha"])
    ]

performance_by_type = (
    best_rows
    .groupby("eval_type")
    .agg(
        questions=("question", "count"),
        recall_at_1=("hit_at_1", "mean"),
        recall_at_3=("hit_at_3", "mean"),
        recall_at_5=("hit_at_5", "mean"),
        mrr=("rr", "mean"),
        ndcg_at_5=("ndcg_at_5", "mean"),
        avg_latency_sec=("latency_sec", "mean"),
    )
    .reset_index()
)

for col in ["recall_at_1", "recall_at_3", "recall_at_5", "mrr", "ndcg_at_5", "avg_latency_sec"]:
    performance_by_type[col] = performance_by_type[col].round(4)

display_professional_table(
    performance_by_type,
    title="Performance by Evaluation Type for Best Configuration",
    max_rows=20
)

metrics = ["recall_at_1", "recall_at_3", "recall_at_5", "mrr", "ndcg_at_5"]

html_1 = display_grouped_metric_table(
    performance_by_type,
    title="Best Retrieval Configuration Performance by Evaluation Type",
    index_col="eval_type",
    metrics=metrics
)

save_html_file("stage03_01_best_config_performance_by_eval_type.html", html_1)


# ---------------------------------------------------------
# 3) Legal Retrieval Only - Top Configurations by MRR
# ---------------------------------------------------------

legal_summary = (
    retrieval_detail[retrieval_detail["eval_type"] == "legal_article_retrieval"]
    .groupby(["chunking_strategy", "embedding_model", "retriever", "alpha"], dropna=False)
    .agg(
        questions=("question", "count"),
        recall_at_1=("hit_at_1", "mean"),
        recall_at_3=("hit_at_3", "mean"),
        recall_at_5=("hit_at_5", "mean"),
        mrr=("rr", "mean"),
        ndcg_at_5=("ndcg_at_5", "mean"),
        avg_latency_sec=("latency_sec", "mean"),
    )
    .reset_index()
)

legal_summary = legal_summary.sort_values(
    ["mrr", "recall_at_5", "recall_at_1", "avg_latency_sec"],
    ascending=[False, False, False, True]
).reset_index(drop=True)

legal_top = legal_summary.head(8).copy()

legal_top["label"] = (
    legal_top["chunking_strategy"].astype(str) + " | " +
    legal_top["embedding_model"].astype(str) + " | " +
    legal_top["retriever"].astype(str) + " | a=" +
    legal_top["alpha"].fillna("").astype(str)
)

for col in ["recall_at_1", "recall_at_3", "recall_at_5", "mrr", "ndcg_at_5", "avg_latency_sec"]:
    legal_top[col] = legal_top[col].round(4)

display_professional_table(
    legal_top,
    title="Legal Article Retrieval - Top Configurations",
    max_rows=8
)

html_2 = display_metric_bars(
    legal_top,
    title="Legal Article Retrieval: Top Configurations by MRR",
    label_col="label",
    metric_col="mrr",
    max_rows=8,
    max_value=1.0
)

save_html_file("stage03_02_legal_top_configurations_by_mrr.html", html_2)


# ---------------------------------------------------------
# 4) Accuracy-Latency Trade-off
# ---------------------------------------------------------

tradeoff_df = retrieval_summary.copy()

tradeoff_df["label"] = (
    tradeoff_df["retriever"].astype(str) + " | " +
    tradeoff_df["embedding_model"].astype(str)
)

tradeoff_df = tradeoff_df.sort_values(
    ["mrr", "recall_at_5", "recall_at_1"],
    ascending=[False, False, False]
).reset_index(drop=True)

html_3 = make_scatter_svg(
    tradeoff_df,
    x_col="avg_latency_sec",
    y_col="mrr",
    label_col="label",
    title="Retrieval Accuracy-Latency Trade-off",
    max_points=12
)

save_html_file("stage03_03_accuracy_latency_tradeoff.html", html_3)


# ---------------------------------------------------------
# 5) Reliability Gate Calibration
# ---------------------------------------------------------

if "score_calibration" in globals():
    score_plot = score_calibration.copy()

    display_professional_table(
        score_plot,
        title="Reliability Gate Calibration Summary",
        max_rows=10
    )

    rows_html = ""

    threshold = float(score_plot["suggested_reliability_threshold"].iloc[0])

    for _, row in score_plot.iterrows():
        rows_html += f"""
        <tr>
            <td style="padding:9px 12px; border:1px solid #e5eaf0; text-align:right;">
                <span dir="ltr">{row['set']}</span>
            </td>
            <td style="padding:9px 12px; border:1px solid #e5eaf0;">
                {make_bar(row['median_top1_score'], max_value=1.0)}
            </td>
        </tr>
        """

    html_4 = f"""
    <div dir="rtl" style="font-family:Tahoma, Arial; text-align:right; line-height:2; margin-top:18px;">
        <h3 style="color:#17324d;">Reliability Gate Calibration</h3>
        <p>
            الخط المتقطع في الرسم الأصلي تم تمثيله هنا كقيمة مرجعية للحد المقترح:
            <span dir="ltr">{threshold:.4f}</span>
        </p>
    </div>

    <div style="width:100%; overflow-x:auto; border:1px solid #d9e2ec; border-radius:10px; margin-bottom:22px;">
        <table style="width:100%; border-collapse:collapse; font-family:Tahoma, Arial; font-size:13px;">
            <thead>
                <tr style="background:#1f4e79; color:white;">
                    <th style="padding:9px 12px; border:1px solid #d9e2ec; text-align:right;">Query Set</th>
                    <th style="padding:9px 12px; border:1px solid #d9e2ec; text-align:center;">Median Top-1 Score</th>
                </tr>
            </thead>
            <tbody>
                {rows_html}
            </tbody>
        </table>
    </div>

    <div dir="rtl" style="
        background:#d1e7dd;
        border-right:5px solid #198754;
        padding:12px 16px;
        border-radius:8px;
        font-family:Tahoma, Arial;
        line-height:2;
        margin-bottom:20px;">
        <b>Suggested reliability threshold:</b>
        <span dir="ltr">{threshold:.4f}</span>
    </div>
    """

    display(HTML(html_4))
    save_html_file("stage03_04_reliability_gate_calibration.html", html_4)

else:
    display_status_card(
        title="score_calibration غير موجود",
        message="شغّل خلية Reliability Gate Calibration أولًا حتى يتم إنشاء الرسم الخاص بحد الموثوقية.",
        status="warning"
    )


# ---------------------------------------------------------
# 6) Save tabular outputs
# ---------------------------------------------------------

performance_by_type.to_csv(
    STAGE03_DIR / "stage03_visual_performance_by_type.csv",
    index=False,
    encoding="utf-8-sig"
)

legal_top.to_csv(
    STAGE03_DIR / "stage03_visual_legal_top_configurations.csv",
    index=False,
    encoding="utf-8-sig"
)

tradeoff_df.to_csv(
    STAGE03_DIR / "stage03_visual_accuracy_latency_tradeoff.csv",
    index=False,
    encoding="utf-8-sig"
)

display_status_card(
    title="Stage 15 completed successfully",
    message=(
        "تم إنشاء الرسوم الأكاديمية بصيغة HTML بدل PNG بسبب حظر matplotlib في بيئة الجهاز. "
        "تم حفظ ملفات HTML و CSV داخل مجلد النتائج."
    ),
    status="success"
)

FIGURES_DIR: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\05_reports\figures_stage03

Saved HTML figure: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\05_reports\figures_stage03\stage03_01_best_config_performance_by_eval_type.html

Saved HTML figure: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\05_reports\figures_stage03\stage03_02_legal_top_configurations_by_mrr.html

Saved HTML figure: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\05_reports\figures_stage03\stage03_03_accuracy_latency_tradeoff.html

Saved HTML figure: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\05_reports\figures_stage03\stage03_04_reliability_gate_calibration.html


<div dir="rtl" style="text-align: right; line-height: 2; font-size: 16px;">

## تجهيز طبقة RAG النهائية للمرحلة الرابعة

بعد اختيار أفضل إعداد للاسترجاع، يتم في هذه الخطوة بناء دالة استرجاع نهائية قابلة للاستخدام في المرحلة الرابعة. هذه الدالة لا تستدعي نموذج اللغة الكبير، بل ترجع المقاطع القانونية أو الأسئلة الشائعة الأكثر صلة مع مصادرها، ثم تبني حزمة سياق جاهزة لإرسالها إلى نموذج اللغة لاحقاً.

بهذا تكون المرحلة الثالثة قد أنجزت طبقة الاسترجاع كاملة: قاعدة المتجهات، الاسترجاع، الترتيب، فحص الثقة، وتجهيز السياق.

</div>

In [37]:
# =========================================================
# Stage 13E - Deep Legal Gold Repair and Metric Recalculation
# إصلاح عميق لأرقام المواد القانونية وإعادة حساب مقاييس الاسترجاع
# =========================================================

from IPython.display import display, Markdown
import pandas as pd
import numpy as np
import re

# ---------------------------------------------------------
# 1) Safety checks
# ---------------------------------------------------------

if "retrieval_detail" not in globals():
    raise NameError("retrieval_detail غير موجود. شغّل Stage 13 أولًا.")

if "df_eval_run" in globals():
    eval_source = df_eval_run.copy()
elif "df_eval" in globals():
    eval_source = df_eval.copy()
else:
    raise NameError("لم أجد df_eval_run أو df_eval.")

if "STAGE03_DIR" not in globals():
    raise NameError("STAGE03_DIR غير موجود.")

# ---------------------------------------------------------
# 2) Normalization helpers
# ---------------------------------------------------------

def normalize_digits(text):
    text = str(text)
    arabic_digits = "٠١٢٣٤٥٦٧٨٩"
    persian_digits = "۰۱۲۳۴۵۶۷۸۹"
    english_digits = "0123456789"

    trans = {}
    for a, e in zip(arabic_digits, english_digits):
        trans[ord(a)] = e

    for p, e in zip(persian_digits, english_digits):
        trans[ord(p)] = e

    return text.translate(trans)


def normalize_question_key(q):
    q = str(q)
    q = re.sub(r"\s+", " ", q).strip()
    return q


def extract_article_numbers(value):
    """
    Extract legal article numbers safely.
    Keeps only plausible Saudi Labor Law article numbers from 1 to 300.
    """
    if value is None:
        return []

    try:
        if pd.isna(value):
            return []
    except Exception:
        pass

    text = normalize_digits(str(value)).strip()

    if text.lower() in ["", "nan", "none", "<na>", "n/a"]:
        return []

    # convert 53.0 -> 53
    text = re.sub(r"(\d+)\s*[\.,]\s*0+\b", r"\1", text)

    nums = re.findall(r"\d+", text)

    clean_nums = []
    for n in nums:
        try:
            n_int = int(n)
            if 1 <= n_int <= 300:
                n_str = str(n_int)
                if n_str not in clean_nums:
                    clean_nums.append(n_str)
        except Exception:
            pass

    return clean_nums


def article_numbers_to_text(nums):
    if not nums:
        return ""
    return "|".join(nums)


def extract_gold_from_eval_row(row):
    """
    Try multiple possible gold columns.
    Do not use eval_id because it may be just row id.
    """
    candidate_cols = [
        "gold_article_numbers",
        "gold_article_number",
        "gold_article_numbers_parsed",
        "expected_article_number",
        "article_numbers",
        "article_number_int",
        "gold_document_unit_ids",
        "gold_document_unit_id",
        "document_unit_id",
        "parent_document_id",
    ]

    for col in candidate_cols:
        if col in row.index:
            nums = extract_article_numbers(row.get(col))
            if nums:
                return article_numbers_to_text(nums)

    return ""


def extract_top5_articles(value):
    nums = extract_article_numbers(value)
    return nums[:5]


def recompute_metrics(gold_text, top5_text):
    gold = set(extract_article_numbers(gold_text))
    retrieved = extract_top5_articles(top5_text)

    rel = []
    for art in retrieved[:5]:
        rel.append(1 if art in gold else 0)

    while len(rel) < 5:
        rel.append(0)

    hit1 = int(any(rel[:1]))
    hit3 = int(any(rel[:3]))
    hit5 = int(any(rel[:5]))

    rr = 0.0
    for i, r in enumerate(rel, start=1):
        if r == 1:
            rr = 1 / i
            break

    dcg = 0.0
    for i, r in enumerate(rel, start=1):
        if r:
            dcg += 1 / np.log2(i + 1)

    ideal = sorted(rel, reverse=True)
    idcg = 0.0
    for i, r in enumerate(ideal, start=1):
        if r:
            idcg += 1 / np.log2(i + 1)

    ndcg = dcg / idcg if idcg > 0 else 0.0

    return hit1, hit3, hit5, rr, ndcg, "".join(map(str, rel))

# ---------------------------------------------------------
# 3) Build gold map from evaluation dataset
# ---------------------------------------------------------

eval_source = eval_source.copy()

if "question" not in eval_source.columns:
    raise KeyError("عمود question غير موجود في df_eval أو df_eval_run.")

eval_source["question_key"] = eval_source["question"].apply(normalize_question_key)

eval_source["gold_article_numbers_from_eval"] = eval_source.apply(
    extract_gold_from_eval_row,
    axis=1
)

gold_map = (
    eval_source[["question_key", "gold_article_numbers_from_eval"]]
    .drop_duplicates(subset=["question_key"])
)

# ---------------------------------------------------------
# 4) Merge repaired gold into retrieval_detail
# ---------------------------------------------------------

rd = retrieval_detail.copy()

rd["question_key"] = rd["question"].apply(normalize_question_key)

rd = rd.merge(
    gold_map,
    on="question_key",
    how="left"
)

rd["gold_article_numbers_before_repair"] = rd.get("gold_article_numbers", "")

def choose_gold(row):
    current = article_numbers_to_text(
        extract_article_numbers(row.get("gold_article_numbers_before_repair", ""))
    )

    from_eval = article_numbers_to_text(
        extract_article_numbers(row.get("gold_article_numbers_from_eval", ""))
    )

    if current:
        return current

    if from_eval:
        return from_eval

    return ""

rd["gold_article_numbers"] = rd.apply(choose_gold, axis=1)

# Normalize retrieved article columns
if "top1_article_number" in rd.columns:
    rd["top1_article_number"] = rd["top1_article_number"].apply(
        lambda x: article_numbers_to_text(extract_article_numbers(x))
    )

if "top5_article_numbers" not in rd.columns:
    raise KeyError("عمود top5_article_numbers غير موجود في retrieval_detail.")

rd["top5_article_numbers"] = rd["top5_article_numbers"].apply(
    lambda x: article_numbers_to_text(extract_article_numbers(x))
)

# ---------------------------------------------------------
# 5) Recompute metrics
# ---------------------------------------------------------

metrics = rd.apply(
    lambda row: recompute_metrics(
        row.get("gold_article_numbers", ""),
        row.get("top5_article_numbers", "")
    ),
    axis=1
)

rd["hit_at_1"] = [m[0] for m in metrics]
rd["hit_at_3"] = [m[1] for m in metrics]
rd["hit_at_5"] = [m[2] for m in metrics]
rd["rr"] = [m[3] for m in metrics]
rd["ndcg_at_5"] = [m[4] for m in metrics]
rd["top5_relevance"] = [m[5] for m in metrics]

# Clean temporary columns
rd = rd.drop(columns=["question_key"], errors="ignore")

retrieval_detail_repaired = rd.copy()
retrieval_detail = retrieval_detail_repaired.copy()

# ---------------------------------------------------------
# 6) Repair diagnostics
# ---------------------------------------------------------

legal_mask = retrieval_detail["eval_type"].astype(str).eq("legal_article_retrieval")

legal_total = legal_mask.sum()

legal_missing_before = retrieval_detail.loc[legal_mask, "gold_article_numbers_before_repair"].apply(
    lambda x: len(extract_article_numbers(x)) == 0
).sum()

legal_missing_after = retrieval_detail.loc[legal_mask, "gold_article_numbers"].apply(
    lambda x: len(extract_article_numbers(x)) == 0
).sum()

display(Markdown(f"""
<div dir="rtl" style="
    text-align:right;
    line-height:2;
    font-size:15px;
    font-family:Arial, Tahoma, sans-serif;
    background-color:#E2F0D9;
    border-right:5px solid #375623;
    padding:14px;
    margin:12px 0;
    border-radius:6px;
">

<h3 style="color:#375623; margin-top:0;">
Gold Article Repair Diagnostics
</h3>

<p>
عدد سجلات الأسئلة القانونية: <b>{legal_total}</b><br>
عدد سجلات الأسئلة القانونية التي كان gold فيها مفقودًا قبل الإصلاح: <b>{legal_missing_before}</b><br>
عدد سجلات الأسئلة القانونية التي بقي gold فيها مفقودًا بعد الإصلاح: <b>{legal_missing_after}</b>
</p>

<p>
إذا بقي الرقم بعد الإصلاح كبيرًا، فهذا يعني أن ملف التقييم نفسه لا يحتوي على أرقام مواد كافية لبعض الأسئلة، ويجب مراجعة بناء الداتا في Notebook 02.
</p>

</div>
"""))

# ---------------------------------------------------------
# 7) Recompute legal-only summary
# ---------------------------------------------------------

legal_only = retrieval_detail[
    retrieval_detail["eval_type"].astype(str).eq("legal_article_retrieval")
].copy()

legal_summary_fixed = (
    legal_only
    .groupby(
        ["chunking_strategy", "embedding_model", "retriever", "alpha"],
        dropna=False
    )
    .agg(
        questions=("question", "count"),
        recall_at_1=("hit_at_1", "mean"),
        recall_at_3=("hit_at_3", "mean"),
        recall_at_5=("hit_at_5", "mean"),
        mrr=("rr", "mean"),
        ndcg_at_5=("ndcg_at_5", "mean"),
        avg_latency_sec=("latency_sec", "mean")
    )
    .reset_index()
)

legal_summary_fixed = legal_summary_fixed.sort_values(
    by=["recall_at_5", "mrr", "ndcg_at_5", "recall_at_1"],
    ascending=False
).reset_index(drop=True)

legal_summary_fixed["rank"] = range(1, len(legal_summary_fixed) + 1)

display_cols = [
    "rank",
    "chunking_strategy",
    "embedding_model",
    "retriever",
    "alpha",
    "questions",
    "recall_at_1",
    "recall_at_3",
    "recall_at_5",
    "mrr",
    "ndcg_at_5",
    "avg_latency_sec"
]

legal_display = legal_summary_fixed[display_cols].head(10).copy()

for col in ["recall_at_1", "recall_at_3", "recall_at_5", "mrr", "ndcg_at_5", "avg_latency_sec"]:
    legal_display[col] = pd.to_numeric(legal_display[col], errors="coerce").round(4)

legal_display["alpha"] = legal_display["alpha"].fillna("N/A")

styler = (
    legal_display.style
    .set_caption("Table 13.Z — Legal Retrieval Summary After Gold Repair")
    .set_table_styles([
        {"selector": "caption", "props": [
            ("caption-side", "top"),
            ("font-size", "17px"),
            ("font-weight", "bold"),
            ("color", "#1F4E78"),
            ("text-align", "center"),
            ("padding", "10px")
        ]},
        {"selector": "th", "props": [
            ("background-color", "#1F4E78"),
            ("color", "white"),
            ("font-weight", "bold"),
            ("text-align", "center"),
            ("border", "1px solid #D9E2F3"),
            ("padding", "8px")
        ]},
        {"selector": "td", "props": [
            ("text-align", "center"),
            ("border", "1px solid #D9E2F3"),
            ("padding", "7px")
        ]},
        {"selector": "tbody tr:nth-child(even)", "props": [("background-color", "#F8FBFD")]},
        {"selector": "tbody tr:nth-child(odd)", "props": [("background-color", "#FFFFFF")]},
        {"selector": "table", "props": [
            ("border-collapse", "collapse"),
            ("width", "100%"),
            ("font-family", "Arial, Tahoma, sans-serif"),
            ("font-size", "12px"),
            ("table-layout", "fixed")
        ]}
    ])
)

try:
    styler = styler.hide(axis="index")
except Exception:
    pass

display(styler)

# ---------------------------------------------------------
# 8) Save repaired outputs
# ---------------------------------------------------------

repaired_csv_path = STAGE03_DIR / "retrieval_evaluation_detailed_results_REPAIRED.csv"
repaired_xlsx_path = STAGE03_DIR / "retrieval_evaluation_detailed_results_REPAIRED.xlsx"

legal_summary_csv_path = STAGE03_DIR / "retrieval_summary_legal_only_REPAIRED.csv"
legal_summary_xlsx_path = STAGE03_DIR / "retrieval_summary_legal_only_REPAIRED.xlsx"

retrieval_detail.to_csv(
    repaired_csv_path,
    index=False,
    encoding="utf-8-sig"
)

retrieval_detail.to_excel(
    repaired_xlsx_path,
    index=False
)

legal_summary_fixed.to_csv(
    legal_summary_csv_path,
    index=False,
    encoding="utf-8-sig"
)

legal_summary_fixed.to_excel(
    legal_summary_xlsx_path,
    index=False
)

print("Saved repaired detailed results:")
print(repaired_csv_path)
print(repaired_xlsx_path)

print("\nSaved repaired legal-only summary:")
print(legal_summary_csv_path)
print(legal_summary_xlsx_path)

best_fixed = legal_summary_fixed.iloc[0].to_dict()

display(Markdown(f"""
<div dir="rtl" style="
    text-align:right;
    line-height:2;
    font-size:15px;
    font-family:Arial, Tahoma, sans-serif;
    background-color:#F8FBFD;
    border-right:5px solid #1F4E78;
    padding:14px;
    margin:12px 0;
    border-radius:6px;
">

<b>أفضل إعداد قانوني بعد إصلاح gold:</b><br>
Chunking Strategy: <code>{best_fixed['chunking_strategy']}</code><br>
Embedding Model: <code>{best_fixed['embedding_model']}</code><br>
Retriever: <code>{best_fixed['retriever']}</code><br>
Alpha: <code>{best_fixed['alpha']}</code><br>
Recall@5: <b>{round(best_fixed['recall_at_5'] * 100, 2)}%</b><br>
MRR: <b>{round(best_fixed['mrr'], 4)}</b><br>
nDCG@5: <b>{round(best_fixed['ndcg_at_5'], 4)}</b><br>

</div>
"""))

print("Deep legal gold repair and metric recalculation completed.")

<div dir="rtl" style="
    text-align:right;
    line-height:2;
    font-size:15px;
    font-family:Arial, Tahoma, sans-serif;
    background-color:#E2F0D9;
    border-right:5px solid #375623;
    padding:14px;
    margin:12px 0;
    border-radius:6px;
">

<h3 style="color:#375623; margin-top:0;">
Gold Article Repair Diagnostics
</h3>

<p>
عدد سجلات الأسئلة القانونية: <b>528</b><br>
عدد سجلات الأسئلة القانونية التي كان gold فيها مفقودًا قبل الإصلاح: <b>0</b><br>
عدد سجلات الأسئلة القانونية التي بقي gold فيها مفقودًا بعد الإصلاح: <b>0</b>
</p>

<p>
إذا بقي الرقم بعد الإصلاح كبيرًا، فهذا يعني أن ملف التقييم نفسه لا يحتوي على أرقام مواد كافية لبعض الأسئلة، ويجب مراجعة بناء الداتا في Notebook 02.
</p>

</div>

Saved repaired detailed results:
C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\retrieval_evaluation_detailed_results_REPAIRED.csv
C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\retrieval_evaluation_detailed_results_REPAIRED.xlsx

Saved repaired legal-only summary:
C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\retrieval_summary_legal_only_REPAIRED.csv
C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\retrieval_summary_legal_only_REPAIRED.xlsx

<div dir="rtl" style="
    text-align:right;
    line-height:2;
    font-size:15px;
    font-family:Arial, Tahoma, sans-serif;
    background-color:#F8FBFD;
    border-right:5px solid #1F4E78;
    padding:14px;
    margin:12px 0;
    border-radius:6px;
">

<b>أفضل إعداد قانوني بعد إصلاح gold:</b><br>
Chunking Strategy: <code>structural</code><br>
Embedding Model: <code>e5_large</code><br>
Retriever: <code>hybrid_reranker</code><br>
Alpha: <code>0.8</code><br>
Recall@5: <b>95.83%</b><br>
MRR: <b>0.9097</b><br>
nDCG@5: <b>0.9221</b><br>

</div>

Deep legal gold repair and metric recalculation completed.

In [38]:
# =========================================================
# Stage 13F - Valid Legal Gold Summary and Missing Gold Report
# فصل التقييم القانوني الصحيح عن الأسئلة القانونية ناقصة رقم المادة
# =========================================================

from IPython.display import display, Markdown
import pandas as pd
import numpy as np
import re

# ---------------------------------------------------------
# 1) Safety checks
# ---------------------------------------------------------

if "retrieval_detail" not in globals():
    raise NameError("retrieval_detail غير موجود. شغّل Stage 13 أولًا.")

if "STAGE03_DIR" not in globals():
    raise NameError("STAGE03_DIR غير موجود.")

# ---------------------------------------------------------
# 2) Helper functions
# ---------------------------------------------------------

def normalize_digits(text):
    text = str(text)
    arabic_digits = "٠١٢٣٤٥٦٧٨٩"
    persian_digits = "۰۱۲۳۴۵۶۷۸۹"
    english_digits = "0123456789"
    trans = {}

    for a, e in zip(arabic_digits, english_digits):
        trans[ord(a)] = e

    for p, e in zip(persian_digits, english_digits):
        trans[ord(p)] = e

    return text.translate(trans)


def extract_article_numbers(value):
    if value is None:
        return []

    try:
        if pd.isna(value):
            return []
    except Exception:
        pass

    text = normalize_digits(str(value)).strip()

    if text.lower() in ["", "nan", "none", "<na>", "n/a"]:
        return []

    text = re.sub(r"(\d+)\s*[\.,]\s*0+\b", r"\1", text)
    nums = re.findall(r"\d+", text)

    clean_nums = []

    for n in nums:
        try:
            n_int = int(n)
            if 1 <= n_int <= 300:
                n_str = str(n_int)
                if n_str not in clean_nums:
                    clean_nums.append(n_str)
        except Exception:
            pass

    return clean_nums


def has_valid_gold(value):
    return len(extract_article_numbers(value)) > 0


def short_text(text, max_len=150):
    text = str(text).replace("\n", " ").strip()
    text = re.sub(r"\s+", " ", text)
    return text[:max_len] + ("..." if len(text) > max_len else "")


def hide_index_safe(styler):
    try:
        return styler.hide(axis="index")
    except Exception:
        try:
            return styler.hide_index()
        except Exception:
            return styler


def color_retriever(val):
    val = str(val)

    if val == "bm25":
        return "background-color:#FFF2CC; color:#7F6000; font-weight:bold;"

    if val == "dense":
        return "background-color:#EAF3F8; color:#1F4E78; font-weight:bold;"

    if val == "hybrid":
        return "background-color:#E2F0D9; color:#375623; font-weight:bold;"

    if val == "hybrid_reranker":
        return "background-color:#D9EAD3; color:#274E13; font-weight:bold;"

    return ""


def apply_style_compatible(styler, func, subset):
    if hasattr(styler, "map"):
        return styler.map(func, subset=subset)
    return styler.applymap(func, subset=subset)


def professional_table(df, caption="", width="100%", font_size="12px"):
    styler = (
        df.style
        .set_caption(caption)
        .set_table_styles([
            {"selector": "caption", "props": [
                ("caption-side", "top"),
                ("font-size", "17px"),
                ("font-weight", "bold"),
                ("color", "#1F4E78"),
                ("text-align", "center"),
                ("padding", "10px")
            ]},
            {"selector": "th", "props": [
                ("background-color", "#1F4E78"),
                ("color", "white"),
                ("font-weight", "bold"),
                ("text-align", "center"),
                ("border", "1px solid #D9E2F3"),
                ("padding", "8px"),
                ("white-space", "normal")
            ]},
            {"selector": "td", "props": [
                ("text-align", "center"),
                ("border", "1px solid #D9E2F3"),
                ("padding", "7px"),
                ("vertical-align", "middle"),
                ("white-space", "normal")
            ]},
            {"selector": "tbody tr:nth-child(even)", "props": [("background-color", "#F8FBFD")]},
            {"selector": "tbody tr:nth-child(odd)", "props": [("background-color", "#FFFFFF")]},
            {"selector": "table", "props": [
                ("border-collapse", "collapse"),
                ("width", width),
                ("font-family", "Arial, Tahoma, sans-serif"),
                ("font-size", font_size),
                ("table-layout", "fixed"),
                ("margin", "12px 0")
            ]}
        ])
    )

    return hide_index_safe(styler)

# ---------------------------------------------------------
# 3) Split legal rows into valid gold and missing gold
# ---------------------------------------------------------

legal_rows = retrieval_detail[
    retrieval_detail["eval_type"].astype(str).eq("legal_article_retrieval")
].copy()

legal_rows["has_valid_gold"] = legal_rows["gold_article_numbers"].apply(has_valid_gold)

legal_valid_gold = legal_rows[legal_rows["has_valid_gold"]].copy()
legal_missing_gold = legal_rows[~legal_rows["has_valid_gold"]].copy()

unique_legal_questions = legal_rows["question"].nunique()
unique_valid_gold_questions = legal_valid_gold["question"].nunique()
unique_missing_gold_questions = legal_missing_gold["question"].nunique()

display(Markdown(f"""
<div dir="rtl" style="
    text-align:right;
    line-height:2;
    font-size:15px;
    font-family:Arial, Tahoma, sans-serif;
    background-color:#FFF2CC;
    border-right:5px solid #BF9000;
    padding:14px;
    margin:12px 0;
    border-radius:6px;
">

<h3 style="color:#7F6000; margin-top:0;">
تشخيص داتا التقييم القانونية
</h3>

<p>
عدد الأسئلة القانونية الفريدة: <b>{unique_legal_questions}</b><br>
عدد الأسئلة القانونية التي لديها رقم مادة Gold صالح: <b>{unique_valid_gold_questions}</b><br>
عدد الأسئلة القانونية التي لا تملك رقم مادة Gold: <b>{unique_missing_gold_questions}</b>
</p>

<p>
لذلك لا يصح اعتماد نتيجة Legal-only السابقة على جميع الأسئلة القانونية، لأن جزءًا كبيرًا منها لا يحتوي على رقم مادة ذهبي للمقارنة.
</p>

</div>
"""))

# ---------------------------------------------------------
# 4) Recompute legal summary using valid gold only
# ---------------------------------------------------------

if legal_valid_gold.empty:
    raise ValueError("لا توجد أسئلة قانونية برقم مادة Gold صالح.")

legal_valid_summary = (
    legal_valid_gold
    .groupby(
        ["chunking_strategy", "embedding_model", "retriever", "alpha"],
        dropna=False
    )
    .agg(
        questions=("question", "count"),
        unique_questions=("question", "nunique"),
        recall_at_1=("hit_at_1", "mean"),
        recall_at_3=("hit_at_3", "mean"),
        recall_at_5=("hit_at_5", "mean"),
        mrr=("rr", "mean"),
        ndcg_at_5=("ndcg_at_5", "mean"),
        avg_latency_sec=("latency_sec", "mean")
    )
    .reset_index()
)

legal_valid_summary = legal_valid_summary.sort_values(
    by=["recall_at_5", "mrr", "ndcg_at_5", "recall_at_1"],
    ascending=False
).reset_index(drop=True)

legal_valid_summary["rank"] = range(1, len(legal_valid_summary) + 1)

display_cols = [
    "rank",
    "chunking_strategy",
    "embedding_model",
    "retriever",
    "alpha",
    "unique_questions",
    "recall_at_1",
    "recall_at_3",
    "recall_at_5",
    "mrr",
    "ndcg_at_5",
    "avg_latency_sec"
]

legal_valid_display = legal_valid_summary[display_cols].head(10).copy()

for col in ["recall_at_1", "recall_at_3", "recall_at_5", "mrr", "ndcg_at_5", "avg_latency_sec"]:
    legal_valid_display[col] = pd.to_numeric(
        legal_valid_display[col],
        errors="coerce"
    ).round(4)

legal_valid_display["alpha"] = legal_valid_display["alpha"].fillna("N/A")

styler = professional_table(
    legal_valid_display,
    caption="Table 13.F1 — Legal Retrieval Summary Using Only Questions with Valid Gold Articles",
    width="100%",
    font_size="12px"
)

styler = apply_style_compatible(styler, color_retriever, subset=["retriever"])
display(styler)

# ---------------------------------------------------------
# 5) Missing gold questions report
# ---------------------------------------------------------

missing_questions_report = (
    legal_missing_gold[
        ["question", "eval_type"]
    ]
    .drop_duplicates()
    .reset_index(drop=True)
)

missing_questions_report["question"] = missing_questions_report["question"].apply(
    lambda x: short_text(x, 180)
)

missing_questions_report["missing_reason"] = (
    "No valid gold_article_numbers found. Needs manual review in Notebook 02."
)

display_df = missing_questions_report.head(40).copy()

missing_style = professional_table(
    display_df,
    caption="Table 13.F2 — Legal Questions Missing Gold Article Numbers",
    width="100%",
    font_size="11.5px"
)

missing_style = missing_style.set_properties(
    subset=["question", "missing_reason"],
    **{
        "text-align": "right",
        "direction": "rtl",
        "line-height": "1.7"
    }
)

display(missing_style)

# ---------------------------------------------------------
# 6) Save outputs
# ---------------------------------------------------------

legal_valid_summary_path_csv = STAGE03_DIR / "retrieval_summary_legal_valid_gold_only.csv"
legal_valid_summary_path_xlsx = STAGE03_DIR / "retrieval_summary_legal_valid_gold_only.xlsx"

missing_gold_path_csv = STAGE03_DIR / "legal_questions_missing_gold_articles.csv"
missing_gold_path_xlsx = STAGE03_DIR / "legal_questions_missing_gold_articles.xlsx"

legal_valid_summary.to_csv(
    legal_valid_summary_path_csv,
    index=False,
    encoding="utf-8-sig"
)

legal_valid_summary.to_excel(
    legal_valid_summary_path_xlsx,
    index=False
)

missing_questions_report.to_csv(
    missing_gold_path_csv,
    index=False,
    encoding="utf-8-sig"
)

missing_questions_report.to_excel(
    missing_gold_path_xlsx,
    index=False
)

best_valid = legal_valid_summary.iloc[0].to_dict()

display(Markdown(f"""
<div dir="rtl" style="
    text-align:right;
    line-height:2;
    font-size:15px;
    font-family:Arial, Tahoma, sans-serif;
    background-color:#E2F0D9;
    border-right:5px solid #375623;
    padding:14px;
    margin:12px 0;
    border-radius:6px;
">

<h3 style="color:#375623; margin-top:0;">
أفضل إعداد قانوني بعد استبعاد الأسئلة ناقصة Gold
</h3>

<p>
Chunking Strategy: <code>{best_valid['chunking_strategy']}</code><br>
Embedding Model: <code>{best_valid['embedding_model']}</code><br>
Retriever: <code>{best_valid['retriever']}</code><br>
Alpha: <code>{best_valid['alpha']}</code><br>
Valid Legal Questions: <b>{int(best_valid['unique_questions'])}</b><br>
Recall@1: <b>{round(best_valid['recall_at_1'] * 100, 2)}%</b><br>
Recall@5: <b>{round(best_valid['recall_at_5'] * 100, 2)}%</b><br>
MRR: <b>{round(best_valid['mrr'], 4)}</b><br>
nDCG@5: <b>{round(best_valid['ndcg_at_5'], 4)}</b>
</p>

<p>
تم حفظ تقرير الأسئلة القانونية ناقصة Gold لمراجعتها لاحقًا في Notebook 02.
</p>

</div>
"""))

print("Saved valid legal summary:")
print(legal_valid_summary_path_csv)
print(legal_valid_summary_path_xlsx)

print("\nSaved missing gold questions report:")
print(missing_gold_path_csv)
print(missing_gold_path_xlsx)

<div dir="rtl" style="
    text-align:right;
    line-height:2;
    font-size:15px;
    font-family:Arial, Tahoma, sans-serif;
    background-color:#FFF2CC;
    border-right:5px solid #BF9000;
    padding:14px;
    margin:12px 0;
    border-radius:6px;
">

<h3 style="color:#7F6000; margin-top:0;">
تشخيص داتا التقييم القانونية
</h3>

<p>
عدد الأسئلة القانونية الفريدة: <b>24</b><br>
عدد الأسئلة القانونية التي لديها رقم مادة Gold صالح: <b>24</b><br>
عدد الأسئلة القانونية التي لا تملك رقم مادة Gold: <b>0</b>
</p>

<p>
لذلك لا يصح اعتماد نتيجة Legal-only السابقة على جميع الأسئلة القانونية، لأن جزءًا كبيرًا منها لا يحتوي على رقم مادة ذهبي للمقارنة.
</p>

</div>

<div dir="rtl" style="
    text-align:right;
    line-height:2;
    font-size:15px;
    font-family:Arial, Tahoma, sans-serif;
    background-color:#E2F0D9;
    border-right:5px solid #375623;
    padding:14px;
    margin:12px 0;
    border-radius:6px;
">

<h3 style="color:#375623; margin-top:0;">
أفضل إعداد قانوني بعد استبعاد الأسئلة ناقصة Gold
</h3>

<p>
Chunking Strategy: <code>structural</code><br>
Embedding Model: <code>e5_large</code><br>
Retriever: <code>hybrid_reranker</code><br>
Alpha: <code>0.8</code><br>
Valid Legal Questions: <b>24</b><br>
Recall@1: <b>87.5%</b><br>
Recall@5: <b>95.83%</b><br>
MRR: <b>0.9097</b><br>
nDCG@5: <b>0.9221</b>
</p>

<p>
تم حفظ تقرير الأسئلة القانونية ناقصة Gold لمراجعتها لاحقًا في Notebook 02.
</p>

</div>

Saved valid legal summary:
C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\retrieval_summary_legal_valid_gold_only.csv
C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\retrieval_summary_legal_valid_gold_only.xlsx

Saved missing gold questions report:
C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\legal_questions_missing_gold_articles.csv
C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\legal_questions_missing_gold_articles.xlsx

In [39]:
# =========================================================
# Stage 13C - Best Legal Retrieval Configuration
# اختيار أفضل إعداد استرجاع للأسئلة القانونية فقط
# =========================================================

from IPython.display import display, Markdown
import pandas as pd
import numpy as np

if "retrieval_detail" not in globals():
    raise NameError("retrieval_detail غير موجود. شغّل Stage 13 أولًا.")

# ---------------------------------------------------------
# 1) Filter legal article retrieval only
# ---------------------------------------------------------

legal_retrieval_detail = retrieval_detail[
    retrieval_detail["eval_type"].astype(str).eq("legal_article_retrieval")
].copy()

if legal_retrieval_detail.empty:
    raise ValueError("لا توجد سجلات legal_article_retrieval داخل retrieval_detail.")

# ---------------------------------------------------------
# 2) Compute legal-only summary
# ---------------------------------------------------------

legal_summary = (
    legal_retrieval_detail
    .groupby(
        ["chunking_strategy", "embedding_model", "retriever", "alpha"],
        dropna=False
    )
    .agg(
        questions=("question", "count"),
        recall_at_1=("hit_at_1", "mean"),
        recall_at_3=("hit_at_3", "mean"),
        recall_at_5=("hit_at_5", "mean"),
        mrr=("rr", "mean"),
        ndcg_at_5=("ndcg_at_5", "mean"),
        avg_latency_sec=("latency_sec", "mean")
    )
    .reset_index()
)

legal_summary = legal_summary.sort_values(
    by=["recall_at_5", "mrr", "ndcg_at_5", "recall_at_1"],
    ascending=False
).reset_index(drop=True)

legal_summary["rank"] = range(1, len(legal_summary) + 1)

# ---------------------------------------------------------
# 3) Display professional table
# ---------------------------------------------------------

def hide_index_safe(styler):
    try:
        return styler.hide(axis="index")
    except Exception:
        try:
            return styler.hide_index()
        except Exception:
            return styler

def color_retriever(val):
    val = str(val)
    if val == "bm25":
        return "background-color:#FFF2CC; color:#7F6000; font-weight:bold;"
    if val == "dense":
        return "background-color:#EAF3F8; color:#1F4E78; font-weight:bold;"
    if val == "hybrid":
        return "background-color:#E2F0D9; color:#375623; font-weight:bold;"
    if val == "hybrid_reranker":
        return "background-color:#D9EAD3; color:#274E13; font-weight:bold;"
    return ""

def apply_style_compatible(styler, func, subset):
    if hasattr(styler, "map"):
        return styler.map(func, subset=subset)
    return styler.applymap(func, subset=subset)

display(Markdown("""
<div dir="rtl" style="
    text-align:right;
    line-height:2;
    font-size:15px;
    font-family:Arial, Tahoma, sans-serif;
    background-color:#F8FBFD;
    border-right:5px solid #1F4E78;
    padding:14px;
    margin:12px 0;
    border-radius:6px;
">

<h3 style="color:#1F4E78; margin-top:0;">
Legal Article Retrieval — Separate Evaluation
</h3>

<p>
تم هنا تقييم إعدادات الاسترجاع على الأسئلة القانونية فقط، لأن نتائج FAQ قد ترفع المتوسط العام وتخفي ضعف استرجاع المواد القانونية.
</p>

</div>
"""))

display_cols = [
    "rank",
    "chunking_strategy",
    "embedding_model",
    "retriever",
    "alpha",
    "questions",
    "recall_at_1",
    "recall_at_3",
    "recall_at_5",
    "mrr",
    "ndcg_at_5",
    "avg_latency_sec"
]

legal_display = legal_summary[display_cols].head(10).copy()

for col in ["recall_at_1", "recall_at_3", "recall_at_5", "mrr", "ndcg_at_5", "avg_latency_sec"]:
    legal_display[col] = pd.to_numeric(legal_display[col], errors="coerce").round(4)

legal_display["alpha"] = legal_display["alpha"].fillna("N/A")

styler = (
    legal_display.style
    .set_caption("Table 13.X — Best Retrieval Configurations for Legal Article Questions Only")
    .set_table_styles([
        {"selector": "caption", "props": [
            ("caption-side", "top"),
            ("font-size", "17px"),
            ("font-weight", "bold"),
            ("color", "#1F4E78"),
            ("text-align", "center"),
            ("padding", "10px")
        ]},
        {"selector": "th", "props": [
            ("background-color", "#1F4E78"),
            ("color", "white"),
            ("font-weight", "bold"),
            ("text-align", "center"),
            ("border", "1px solid #D9E2F3"),
            ("padding", "8px")
        ]},
        {"selector": "td", "props": [
            ("text-align", "center"),
            ("border", "1px solid #D9E2F3"),
            ("padding", "7px"),
            ("vertical-align", "middle")
        ]},
        {"selector": "tbody tr:nth-child(even)", "props": [("background-color", "#F8FBFD")]},
        {"selector": "tbody tr:nth-child(odd)", "props": [("background-color", "#FFFFFF")]},
        {"selector": "table", "props": [
            ("border-collapse", "collapse"),
            ("width", "100%"),
            ("font-family", "Arial, Tahoma, sans-serif"),
            ("font-size", "12px"),
            ("table-layout", "fixed")
        ]}
    ])
)

styler = apply_style_compatible(styler, color_retriever, subset=["retriever"])
display(hide_index_safe(styler))

# ---------------------------------------------------------
# 4) Save legal-only summary
# ---------------------------------------------------------

legal_summary_path_csv = STAGE03_DIR / "retrieval_summary_legal_only.csv"
legal_summary_path_xlsx = STAGE03_DIR / "retrieval_summary_legal_only.xlsx"

legal_summary.to_csv(legal_summary_path_csv, index=False, encoding="utf-8-sig")
legal_summary.to_excel(legal_summary_path_xlsx, index=False)

best_legal_config = legal_summary.iloc[0].to_dict()

display(Markdown(f"""
<div dir="rtl" style="
    text-align:right;
    line-height:2;
    font-size:15px;
    font-family:Arial, Tahoma, sans-serif;
    background-color:#E2F0D9;
    border-right:5px solid #375623;
    padding:14px;
    margin:12px 0;
    border-radius:6px;
">

<b>أفضل إعداد للأسئلة القانونية فقط:</b><br>
Chunking Strategy: <code>{best_legal_config['chunking_strategy']}</code><br>
Embedding Model: <code>{best_legal_config['embedding_model']}</code><br>
Retriever: <code>{best_legal_config['retriever']}</code><br>
Alpha: <code>{best_legal_config['alpha']}</code><br>
Recall@5: <b>{round(best_legal_config['recall_at_5'] * 100, 2)}%</b><br>
MRR: <b>{round(best_legal_config['mrr'], 4)}</b><br>
nDCG@5: <b>{round(best_legal_config['ndcg_at_5'], 4)}</b><br>

</div>
"""))

print("Saved legal-only retrieval summary:")
print(legal_summary_path_csv)
print(legal_summary_path_xlsx)

<div dir="rtl" style="
    text-align:right;
    line-height:2;
    font-size:15px;
    font-family:Arial, Tahoma, sans-serif;
    background-color:#F8FBFD;
    border-right:5px solid #1F4E78;
    padding:14px;
    margin:12px 0;
    border-radius:6px;
">

<h3 style="color:#1F4E78; margin-top:0;">
Legal Article Retrieval — Separate Evaluation
</h3>

<p>
تم هنا تقييم إعدادات الاسترجاع على الأسئلة القانونية فقط، لأن نتائج FAQ قد ترفع المتوسط العام وتخفي ضعف استرجاع المواد القانونية.
</p>

</div>

<div dir="rtl" style="
    text-align:right;
    line-height:2;
    font-size:15px;
    font-family:Arial, Tahoma, sans-serif;
    background-color:#E2F0D9;
    border-right:5px solid #375623;
    padding:14px;
    margin:12px 0;
    border-radius:6px;
">

<b>أفضل إعداد للأسئلة القانونية فقط:</b><br>
Chunking Strategy: <code>structural</code><br>
Embedding Model: <code>e5_large</code><br>
Retriever: <code>hybrid_reranker</code><br>
Alpha: <code>0.8</code><br>
Recall@5: <b>95.83%</b><br>
MRR: <b>0.9097</b><br>
nDCG@5: <b>0.9221</b><br>

</div>

Saved legal-only retrieval summary:
C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\retrieval_summary_legal_only.csv
C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\retrieval_summary_legal_only.xlsx

In [40]:
# =========================================================
# Stage 13D - Legal Retrieval Failure Diagnosis
# تشخيص فشل الاسترجاع في الأسئلة القانونية
# =========================================================

from IPython.display import display, Markdown
import pandas as pd
import numpy as np
import re

if "retrieval_detail" not in globals():
    raise NameError("retrieval_detail غير موجود. شغّل Stage 13 أولًا.")

# ---------------------------------------------------------
# 1) اختر أفضل إعداد قانوني من legal_summary
# ---------------------------------------------------------

if "legal_summary" not in globals():
    legal_summary = (
        retrieval_detail[
            retrieval_detail["eval_type"].astype(str).eq("legal_article_retrieval")
        ]
        .groupby(["chunking_strategy", "embedding_model", "retriever", "alpha"], dropna=False)
        .agg(
            questions=("question", "count"),
            recall_at_1=("hit_at_1", "mean"),
            recall_at_3=("hit_at_3", "mean"),
            recall_at_5=("hit_at_5", "mean"),
            mrr=("rr", "mean"),
            ndcg_at_5=("ndcg_at_5", "mean"),
            avg_latency_sec=("latency_sec", "mean")
        )
        .reset_index()
        .sort_values(["recall_at_5", "mrr", "ndcg_at_5"], ascending=False)
        .reset_index(drop=True)
    )

best_legal = legal_summary.iloc[0].to_dict()

print("Best legal retrieval config:")
print(best_legal)

# ---------------------------------------------------------
# 2) فلترة نتائج أفضل إعداد قانوني فقط
# ---------------------------------------------------------

alpha_value = best_legal["alpha"]

legal_best_detail = retrieval_detail[
    (retrieval_detail["eval_type"].astype(str) == "legal_article_retrieval") &
    (retrieval_detail["chunking_strategy"].astype(str) == str(best_legal["chunking_strategy"])) &
    (retrieval_detail["embedding_model"].astype(str) == str(best_legal["embedding_model"])) &
    (retrieval_detail["retriever"].astype(str) == str(best_legal["retriever"]))
].copy()

# التعامل مع alpha = NaN
if pd.isna(alpha_value):
    legal_best_detail = legal_best_detail[legal_best_detail["alpha"].isna()]
else:
    legal_best_detail = legal_best_detail[
        pd.to_numeric(legal_best_detail["alpha"], errors="coerce").round(4)
        == round(float(alpha_value), 4)
    ]

# ---------------------------------------------------------
# 3) استخراج الأسئلة التي فشل فيها Recall@5
# ---------------------------------------------------------

legal_failures = legal_best_detail[
    pd.to_numeric(legal_best_detail["hit_at_5"], errors="coerce").fillna(0).astype(int) == 0
].copy()

legal_success = legal_best_detail[
    pd.to_numeric(legal_best_detail["hit_at_5"], errors="coerce").fillna(0).astype(int) == 1
].copy()

display(Markdown(f"""
<div dir="rtl" style="
    text-align:right;
    line-height:2;
    font-size:15px;
    font-family:Arial, Tahoma, sans-serif;
    background-color:#F8FBFD;
    border-right:5px solid #1F4E78;
    padding:14px;
    margin:12px 0;
    border-radius:6px;
">

<h3 style="color:#1F4E78; margin-top:0;">
Legal Retrieval Failure Diagnosis
</h3>

<p>
عدد الأسئلة القانونية في أفضل إعداد: <b>{len(legal_best_detail)}</b><br>
عدد الأسئلة التي نجح فيها الاسترجاع ضمن Top-5: <b>{len(legal_success)}</b><br>
عدد الأسئلة التي فشل فيها الاسترجاع ضمن Top-5: <b>{len(legal_failures)}</b>
</p>

</div>
"""))

# ---------------------------------------------------------
# 4) عرض احترافي للأسئلة الفاشلة
# ---------------------------------------------------------

def short_text(text, max_len=150):
    text = str(text).replace("\n", " ").strip()
    text = re.sub(r"\s+", " ", text)
    return text[:max_len] + ("..." if len(text) > max_len else "")

failure_cols = [
    "question",
    "gold_article_numbers",
    "top1_article_number",
    "top1_article_title",
    "top5_article_numbers",
    "hit_at_1",
    "hit_at_3",
    "hit_at_5",
    "top1_score"
]

failure_cols = [c for c in failure_cols if c in legal_failures.columns]

failure_display = legal_failures[failure_cols].copy()

for col in ["question", "top1_article_title"]:
    if col in failure_display.columns:
        failure_display[col] = failure_display[col].apply(lambda x: short_text(x, 150))

if "top1_score" in failure_display.columns:
    failure_display["top1_score"] = pd.to_numeric(
        failure_display["top1_score"],
        errors="coerce"
    ).round(4)

failure_display = failure_display.head(40)

styler = (
    failure_display.style
    .set_caption("Table 13.Y — Legal Questions Where Gold Article Was Not Retrieved in Top-5")
    .set_table_styles([
        {"selector": "caption", "props": [
            ("caption-side", "top"),
            ("font-size", "17px"),
            ("font-weight", "bold"),
            ("color", "#1F4E78"),
            ("text-align", "center"),
            ("padding", "10px")
        ]},
        {"selector": "th", "props": [
            ("background-color", "#1F4E78"),
            ("color", "white"),
            ("font-weight", "bold"),
            ("text-align", "center"),
            ("border", "1px solid #D9E2F3"),
            ("padding", "8px")
        ]},
        {"selector": "td", "props": [
            ("text-align", "center"),
            ("border", "1px solid #D9E2F3"),
            ("padding", "7px"),
            ("vertical-align", "middle"),
            ("white-space", "normal")
        ]},
        {"selector": "tbody tr:nth-child(even)", "props": [("background-color", "#F8FBFD")]},
        {"selector": "tbody tr:nth-child(odd)", "props": [("background-color", "#FFFFFF")]},
        {"selector": "table", "props": [
            ("border-collapse", "collapse"),
            ("width", "100%"),
            ("font-family", "Arial, Tahoma, sans-serif"),
            ("font-size", "11.5px"),
            ("table-layout", "fixed")
        ]}
    ])
)

try:
    styler = styler.hide(axis="index")
except Exception:
    pass

if "question" in failure_display.columns:
    styler = styler.set_properties(
        subset=["question"],
        **{
            "text-align": "right",
            "direction": "rtl",
            "line-height": "1.7"
        }
    )

display(styler)

# ---------------------------------------------------------
# 5) حفظ ملف الأخطاء للمراجعة
# ---------------------------------------------------------

failure_path = STAGE03_DIR / "legal_retrieval_failures_top5.csv"
legal_failures.to_csv(failure_path, index=False, encoding="utf-8-sig")

print("Saved legal retrieval failures to:")
print(failure_path)

Best legal retrieval config:
{'chunking_strategy': 'structural', 'embedding_model': 'e5_large', 'retriever': 'hybrid_reranker', 'alpha': 0.8, 'questions': 24, 'recall_at_1': 0.875, 'recall_at_3': 0.9583333333333334, 'recall_at_5': 0.9583333333333334, 'mrr': 0.9097222222222222, 'ndcg_at_5': 0.9221220730654774, 'avg_latency_sec': 0.31991129120190936, 'rank': 1}

<div dir="rtl" style="
    text-align:right;
    line-height:2;
    font-size:15px;
    font-family:Arial, Tahoma, sans-serif;
    background-color:#F8FBFD;
    border-right:5px solid #1F4E78;
    padding:14px;
    margin:12px 0;
    border-radius:6px;
">

<h3 style="color:#1F4E78; margin-top:0;">
Legal Retrieval Failure Diagnosis
</h3>

<p>
عدد الأسئلة القانونية في أفضل إعداد: <b>24</b><br>
عدد الأسئلة التي نجح فيها الاسترجاع ضمن Top-5: <b>23</b><br>
عدد الأسئلة التي فشل فيها الاسترجاع ضمن Top-5: <b>1</b>
</p>

</div>

Saved legal retrieval failures to:
C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\legal_retrieval_failures_top5.csv

In [41]:
# =========================================================
# Stage 19 - Final RAG Retriever Packaging for Stage 04 LLM
# تجهيز دالة الاسترجاع النهائية وجدول أمثلة RAG
# =========================================================

import json
import time
import pandas as pd
import numpy as np
from IPython.display import display, HTML

# ---------------------------------------------------------
# 1) Required variable checks
# ---------------------------------------------------------

required_objects = [
    "best_config",
    "retrieve_with_config",
    "suggested_reliability_threshold",
    "TOP_K",
    "STAGE03_DIR"
]

missing_objects = [obj for obj in required_objects if obj not in globals()]

assert not missing_objects, (
    "Missing required objects before Stage 19: "
    + ", ".join(missing_objects)
    + ". Run the previous retrieval evaluation stages first."
)

# Convert best_config safely if it is a pandas Series
if isinstance(best_config, pd.Series):
    best_config = best_config.to_dict()

assert isinstance(best_config, dict), "best_config must be a dictionary or pandas Series."

# ---------------------------------------------------------
# 2) Extract best retrieval configuration
# ---------------------------------------------------------

best_chunking_strategy = str(best_config.get("chunking_strategy", "")).strip()
best_embedding_model = str(best_config.get("embedding_model", "")).strip()
best_retriever_name = str(best_config.get("retriever", "")).strip()

best_alpha = best_config.get("alpha", None)

try:
    if best_alpha is None or pd.isna(best_alpha):
        best_alpha = None
    else:
        best_alpha = float(best_alpha)
except Exception:
    best_alpha = None

best_model_key = None if best_embedding_model in ["", "none", "nan", "None"] else best_embedding_model

assert best_chunking_strategy != "", "best_chunking_strategy is empty."
assert best_retriever_name != "", "best_retriever_name is empty."

# ---------------------------------------------------------
# 3) Reliability threshold
# ---------------------------------------------------------

try:
    reliability_threshold = float(suggested_reliability_threshold)
except Exception:
    reliability_threshold = None

print("Best retrieval configuration:")
print("Chunking strategy:", best_chunking_strategy)
print("Embedding model:", best_embedding_model)
print("Retriever:", best_retriever_name)
print("Alpha:", best_alpha)
print("Reliability threshold:", reliability_threshold)


# ---------------------------------------------------------
# 4) Helper functions
# ---------------------------------------------------------

def safe_float(value, default=np.nan):
    try:
        if value is None:
            return default
        if pd.isna(value):
            return default
        return float(value)
    except Exception:
        return default


def safe_str(value, default=""):
    try:
        if value is None:
            return default
        if pd.isna(value):
            return default
        return str(value)
    except Exception:
        return default


def clean_text_preview(text, max_chars=800):
    text = safe_str(text).replace("\n", " ").replace("\r", " ").strip()
    text = " ".join(text.split())
    if len(text) > max_chars:
        return text[:max_chars] + "..."
    return text


def normalize_json_value(value):
    """
    Convert numpy/pandas values into JSON-safe Python values.
    """
    if isinstance(value, (np.integer,)):
        return int(value)
    if isinstance(value, (np.floating,)):
        if np.isnan(value):
            return None
        return float(value)
    if isinstance(value, (np.ndarray,)):
        return value.tolist()
    if pd.isna(value) if not isinstance(value, (list, dict, tuple)) else False:
        return None
    return value


def make_json_safe_dict(d):
    return {k: normalize_json_value(v) for k, v in d.items()}


def build_context_for_llm(results, max_results=5):
    """
    Build a structured context block for the next LLM stage.
    This stage does not generate an answer; it only prepares retrieved evidence.
    """
    context_blocks = []

    for r in results[:max_results]:
        rank = safe_str(r.get("rank", ""))
        source_type = safe_str(r.get("source_type", ""))
        score = safe_float(r.get("score", np.nan))
        article_no = safe_str(
            r.get("article_number_int", "")
            or r.get("article_number_label", "")
        )
        article_title = safe_str(r.get("article_title", ""))
        chunk_id = safe_str(r.get("chunk_id", ""))
        parent_id = safe_str(r.get("parent_document_id", ""))
        text = safe_str(r.get("text", ""))

        header_parts = [
            f"Rank: {rank}",
            f"Source type: {source_type}",
            f"Score: {score:.4f}" if pd.notna(score) else "Score: N/A",
            f"Chunk ID: {chunk_id}",
            f"Parent document ID: {parent_id}",
        ]

        if article_no:
            header_parts.append(f"Article number: {article_no}")

        if article_title:
            header_parts.append(f"Article title: {article_title}")

        block = "\n".join([
            " | ".join(header_parts),
            text
        ])

        context_blocks.append(block)

    return "\n\n---\n\n".join(context_blocks)


# ---------------------------------------------------------
# 5) Final RAG retrieval function
# ---------------------------------------------------------

def final_rag_retrieve(query, top_k=TOP_K):
    """
    Final retrieval function for Stage 04 LLM integration.
    
    This function:
    - uses the best retrieval configuration selected in Stage 14
    - retrieves the top-k relevant chunks
    - applies the reliability threshold
    - prepares a context package for the LLM stage
    
    It does not generate the final answer.
    """
    query = safe_str(query).strip()

    results, latency = retrieve_with_config(
        query=query,
        corpus_name=best_chunking_strategy,
        retriever_name=best_retriever_name,
        model_key=best_model_key,
        alpha=best_alpha,
        top_k=top_k,
    )

    if results is None:
        results = []

    top1 = results[0] if len(results) > 0 else {}

    top1_score = safe_float(top1.get("score", np.nan))

    if reliability_threshold is None or pd.isna(top1_score):
        is_retrieval_reliable = False
    else:
        is_retrieval_reliable = bool(top1_score >= reliability_threshold)

    context_for_llm = build_context_for_llm(results, max_results=top_k)

    output = {
        "query": query,
        "is_retrieval_reliable": is_retrieval_reliable,
        "suggested_reliability_threshold": reliability_threshold,
        "top1_score": top1_score,
        "top1_source_type": safe_str(top1.get("source_type", "")),
        "top1_article_number": safe_str(
            top1.get("article_number_int", "")
            or top1.get("article_number_label", "")
        ),
        "top1_article_title": safe_str(top1.get("article_title", "")),
        "top1_chunk_id": safe_str(top1.get("chunk_id", "")),
        "top1_parent_document_id": safe_str(top1.get("parent_document_id", "")),
        "top1_backend": safe_str(top1.get("retrieval_backend", "")),
        "latency_sec": safe_float(latency, default=np.nan),
        "context_preview": clean_text_preview(context_for_llm, max_chars=800),
        "context_for_llm": context_for_llm,
        "retrieved_results": results,
        "best_chunking_strategy": best_chunking_strategy,
        "best_embedding_model": best_embedding_model,
        "best_retriever": best_retriever_name,
        "best_alpha": best_alpha,
    }

    return output


# ---------------------------------------------------------
# 6) Build final RAG examples dataframe
# ---------------------------------------------------------

rag_example_questions = [
    # Legal questions
    "كم مدة فترة التجربة في نظام العمل السعودي؟",
    "متى يستحق العامل مكافأة نهاية الخدمة؟",
    "كم عدد ساعات العمل في نظام العمل السعودي؟",
    "هل يحق لصاحب العمل نقل العامل من فرع إلى فرع؟",
    "ما مدة الإجازة السنوية للعامل؟",
    
    # FAQ / service-style questions
    "كيف أقدم شكوى على صاحب العمل؟",
    "ما حقوق العامل عند انتهاء عقد العمل؟",
    
    # Out-of-scope tests
    "ما حكم الطلاق؟",
    "كم سعر العقار في الرياض؟",
    "ما أفضل سيارة عائلية؟"
]

rag_example_rows = []
query_errors = []

for q in rag_example_questions:
    try:
        result = final_rag_retrieve(q, top_k=TOP_K)

        rag_example_rows.append({
            "query": result["query"],
            "is_retrieval_reliable": result["is_retrieval_reliable"],
            "suggested_reliability_threshold": result["suggested_reliability_threshold"],
            "top1_score": result["top1_score"],
            "top1_source_type": result["top1_source_type"],
            "top1_article_number": result["top1_article_number"],
            "top1_article_title": result["top1_article_title"],
            "top1_chunk_id": result["top1_chunk_id"],
            "top1_parent_document_id": result["top1_parent_document_id"],
            "top1_backend": result["top1_backend"],
            "latency_sec": result["latency_sec"],
            "context_preview": result["context_preview"],
            "context_for_llm": result["context_for_llm"],
            "best_chunking_strategy": result["best_chunking_strategy"],
            "best_embedding_model": result["best_embedding_model"],
            "best_retriever": result["best_retriever"],
            "best_alpha": result["best_alpha"],
        })

    except Exception as e:
        query_errors.append((q, str(e)))

        rag_example_rows.append({
            "query": q,
            "is_retrieval_reliable": False,
            "suggested_reliability_threshold": reliability_threshold,
            "top1_score": np.nan,
            "top1_source_type": "",
            "top1_article_number": "",
            "top1_article_title": "",
            "top1_chunk_id": "",
            "top1_parent_document_id": "",
            "top1_backend": "",
            "latency_sec": np.nan,
            "context_preview": f"Retrieval error: {e}",
            "context_for_llm": "",
            "best_chunking_strategy": best_chunking_strategy,
            "best_embedding_model": best_embedding_model,
            "best_retriever": best_retriever_name,
            "best_alpha": best_alpha,
        })

rag_examples_df = pd.DataFrame(rag_example_rows)


# ---------------------------------------------------------
# 7) Save outputs using manifest-compatible filenames
# ---------------------------------------------------------

rag_examples_csv = STAGE03_DIR / "stage03_rag_retriever_context_examples.csv"
rag_examples_xlsx = STAGE03_DIR / "stage03_rag_retriever_context_examples.xlsx"
final_rag_config_json = STAGE03_DIR / "stage03_best_retriever_ready_for_llm_config.json"

rag_examples_df.to_csv(
    rag_examples_csv,
    index=False,
    encoding="utf-8-sig"
)

rag_examples_df.to_excel(
    rag_examples_xlsx,
    index=False
)

final_rag_config = {
    "best_chunking_strategy": best_chunking_strategy,
    "best_embedding_model": best_embedding_model,
    "best_retriever": best_retriever_name,
    "best_alpha": best_alpha,
    "top_k": TOP_K,
    "suggested_reliability_threshold": reliability_threshold,
    "notes": "This configuration is ready for Stage 04 LLM generation. It prepares retrieved context only and does not generate answers."
}

with open(final_rag_config_json, "w", encoding="utf-8") as f:
    json.dump(make_json_safe_dict(final_rag_config), f, ensure_ascii=False, indent=2)


# ---------------------------------------------------------
# 8) Display summary
# ---------------------------------------------------------

summary_stage19 = pd.DataFrame([{
    "best_chunking_strategy": best_chunking_strategy,
    "best_embedding_model": best_embedding_model,
    "best_retriever": best_retriever_name,
    "best_alpha": best_alpha,
    "top_k": TOP_K,
    "suggested_reliability_threshold": reliability_threshold,
    "example_questions": len(rag_examples_df),
    "reliable_examples": int(rag_examples_df["is_retrieval_reliable"].sum()),
    "unreliable_examples": int((~rag_examples_df["is_retrieval_reliable"]).sum()),
    "query_errors": len(query_errors),
    "status": "OK" if len(query_errors) == 0 else "WARN",
}])

display(HTML("""
<div dir="rtl" style="text-align:right; line-height:2; font-size:17px;">
<h3>Stage 19 — Final RAG Retriever Packaging</h3>
<p>
تم في هذه المرحلة بناء دالة الاسترجاع النهائية 
<span dir="ltr" style="display:inline-block;">final_rag_retrieve()</span>
باستخدام أفضل إعداد تم اختياره من نتائج التقييم. كما تم إنشاء جدول أمثلة 
<span dir="ltr" style="display:inline-block;">rag_examples_df</span>
لاختبار جاهزية طبقة الاسترجاع قبل تمرير السياق إلى نموذج اللغة في المرحلة الرابعة.
</p>
</div>
"""))

display(
    summary_stage19
    .style
    .set_caption("Final RAG Retriever Packaging Summary")
    .set_properties(**{
        "text-align": "center",
        "white-space": "normal",
        "font-size": "12px"
    })
    .set_table_styles([
        {
            "selector": "caption",
            "props": [
                ("caption-side", "top"),
                ("font-size", "16px"),
                ("font-weight", "bold"),
                ("text-align", "left")
            ]
        },
        {
            "selector": "th",
            "props": [
                ("background-color", "#F3F4F6"),
                ("font-weight", "bold"),
                ("text-align", "center")
            ]
        }
    ])
)

display(rag_examples_df)

print("Stage 19 completed successfully.")
print("best_retriever_name:", best_retriever_name)
print("final_rag_retrieve:", "FOUND" if "final_rag_retrieve" in globals() else "MISSING")
print("rag_examples_df:", "FOUND" if "rag_examples_df" in globals() else "MISSING")
print("rag_examples_df shape:", rag_examples_df.shape)

print("\nSaved files:")
print(rag_examples_csv)
print(rag_examples_xlsx)
print(final_rag_config_json)

if query_errors:
    print("\nWarnings:")
    for q, err in query_errors:
        print("-", q, "=>", err)

Best retrieval configuration:
Chunking strategy: structural
Embedding model: e5_large
Retriever: hybrid_reranker
Alpha: 0.8
Reliability threshold: 0.7492

,query,is_retrieval_reliable,suggested_reliability_threshold,top1_score,top1_source_type,top1_article_number,top1_article_title,top1_chunk_id,top1_parent_document_id,top1_backend,latency_sec,context_preview,context_for_llm,best_chunking_strategy,best_embedding_model,best_retriever,best_alpha
0,كم مدة فترة التجربة في نظام العمل السعودي؟,True,0.7492,0.955209,legal_article,53.0,المادة الثالثة والخمسون :,STRUCT_000053,b56e9c99f1c551928c8727dae90850186c14efc78d6272f429f0c448add3f3dc,chromadb+bm25+reranker,0.336406,Rank: 1 | Source type: legal_article | Score: 0.9552 | Chunk ID: STRUCT_000053 | Parent document ID: b56e9c99f1c5519...,Rank: 1 | Source type: legal_article | Score: 0.9552 | Chunk ID: STRUCT_000053 | Parent document ID: b56e9c99f1c5519...,structural,e5_large,hybrid_reranker,0.8
1,متى يستحق العامل مكافأة نهاية الخدمة؟,True,0.7492,0.957946,faq,nan,nan,STRUCT_000437,805230b359c36c66f227ede181f48e9fe418ada20a1e2ea5d557d3e3d1169707,chromadb+bm25+reranker,0.314899,Rank: 1 | Source type: faq | Score: 0.9579 | Chunk ID: STRUCT_000437 | Parent document ID: 805230b359c36c66f227ede18...,Rank: 1 | Source type: faq | Score: 0.9579 | Chunk ID: STRUCT_000437 | Parent document ID: 805230b359c36c66f227ede18...,structural,e5_large,hybrid_reranker,0.8
2,كم عدد ساعات العمل في نظام العمل السعودي؟,True,0.7492,0.918124,legal_article,99.0,المادة التاسعة والتسعون:,STRUCT_000100,4d7b6567adef57ae0d1350a027920ae7d11610e7cf8da52e68e0c806900f687e,chromadb+bm25+reranker,0.310756,Rank: 1 | Source type: legal_article | Score: 0.9181 | Chunk ID: STRUCT_000100 | Parent document ID: 4d7b6567adef57a...,Rank: 1 | Source type: legal_article | Score: 0.9181 | Chunk ID: STRUCT_000100 | Parent document ID: 4d7b6567adef57a...,structural,e5_large,hybrid_reranker,0.8
3,هل يحق لصاحب العمل نقل العامل من فرع إلى فرع؟,True,0.7492,0.941347,legal_article,58.0,المادة الثامنة والخمسون:,STRUCT_000058,1051ab3d809d019bdc3a3f42ad5a02fc91dd155ec2c502a040180ae5cdd91a46,chromadb+bm25+reranker,0.324448,Rank: 1 | Source type: legal_article | Score: 0.9413 | Chunk ID: STRUCT_000058 | Parent document ID: 1051ab3d809d019...,Rank: 1 | Source type: legal_article | Score: 0.9413 | Chunk ID: STRUCT_000058 | Parent document ID: 1051ab3d809d019...,structural,e5_large,hybrid_reranker,0.8
4,ما مدة الإجازة السنوية للعامل؟,True,0.7492,0.996335,faq,nan,nan,STRUCT_000321,f196cb04ac077b585020c6b00dd03592845742a0e51983c0e22991f007640855,chromadb+bm25+reranker,0.308254,Rank: 1 | Source type: faq | Score: 0.9963 | Chunk ID: STRUCT_000321 | Parent document ID: f196cb04ac077b585020c6b00...,Rank: 1 | Source type: faq | Score: 0.9963 | Chunk ID: STRUCT_000321 | Parent document ID: f196cb04ac077b585020c6b00...,structural,e5_large,hybrid_reranker,0.8
5,كيف أقدم شكوى على صاحب العمل؟,True,0.7492,0.995652,faq,nan,nan,STRUCT_000305,78d90209d62c955bf714b2c011a24e5e53c8401bbf7cd469f0b437a6e6685339,chromadb+bm25+reranker,0.312249,Rank: 1 | Source type: faq | Score: 0.9957 | Chunk ID: STRUCT_000305 | Parent document ID: 78d90209d62c955bf714b2c01...,Rank: 1 | Source type: faq | Score: 0.9957 | Chunk ID: STRUCT_000305 | Parent document ID: 78d90209d62c955bf714b2c01...,structural,e5_large,hybrid_reranker,0.8
6,ما حقوق العامل عند انتهاء عقد العمل؟,True,0.7492,0.976019,legal_article,64.0,المادة الرابعة والستون:,STRUCT_000064,75712469249444225b0d8076c807d51f8c883d982d9aa3143725251780f39f25,chromadb+bm25+reranker,0.288175,Rank: 1 | Source type: legal_article | Score: 0.9760 | Chunk ID: STRUCT_000064 | Parent document ID: 757124692494442...,Rank: 1 | Source type: legal_article | Score: 0.9760 | Chunk ID: STRUCT_000064 | Parent document ID: 757124692494442...,structural,e5_large,hybrid_reranker,0.8
7,ما حكم الطلاق؟,False,0.7492,0.007827,legal_article,87.0,المادة السابعة والثمانون:,STRUCT_000088,e81fc46ef0386d25a0b0b5d6486ce54efae34fbc3f1e72e83650374c0378f816,chromadb+bm25+reranker,0.320516,Rank: 1 | Source type: legal_article | Score: 0.0078 | Chunk ID: STRUCT_000088 | Parent document ID: e81fc46ef0386d2...,Rank: 1 | Source type: legal_article | Score: 0.0078 | Chunk ID: STRUCT_000088 | Parent document ID: e81fc46ef0386d2...,structural,e5_large,hybrid_reranker,0.8
8,كم سعر العقار في الرياض؟,False,0.7492,0.000121,faq,nan,nan,STRUCT_000254,682bb580f3adee84d64edf54c0b88d7cccf1715956e0a94b19c5e5609df66598,chromadb+bm25+reranker,0.322706,Rank: 1 | Source type: faq | Score: 0.0001 | Chunk ID: STRUCT_000254 | Parent document ID: 682bb580f3adee84d64edf54c...,Rank: 1 | Source type: faq | Score: 0.0001 | Chunk ID: STRUCT_000254 | Parent document ID: 682bb580f3adee84d64edf54c...,structural,e5_large,hybrid_reranker,0.8
9,ما أفضل سيارة عائلية؟,False,0.7492,0.000048,faq,nan,nan,STRUCT_000297,7b4ae6adbf5de7da912bdd2d0b77c489e377ae8bd6891290e4bdb280b3bf1de7,chromadb+bm25+reranker,0.297117,Rank: 1 | Source type: faq | Score: 0.0000 | Chunk ID: STRUCT_000297 | Parent document ID: 7b4ae6adbf5de7da912bdd2d0...,Rank: 1 | Source type: faq | Score: 0.0000 | Chunk ID: STRUCT_000297 | Parent document ID: 7b4ae6adbf5de7da912bdd2d0...,structural,e5_large,hybrid_reranker,0.8

Stage 19 completed successfully.
best_retriever_name: hybrid_reranker
final_rag_retrieve: FOUND
rag_examples_df: FOUND
rag_examples_df shape: (10, 17)

Saved files:
C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\stage03_rag_retriever_context_examples.csv
C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\stage03_rag_retriever_context_examples.xlsx
C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\stage03_best_retriever_ready_for_llm_config.json

In [42]:
# =========================================================
# Debug - Check required final RAG variables
# =========================================================

required_vars = [
    "best_config",
    "best_retriever_name",
    "final_rag_retrieve",
    "rag_examples_df",
    "suggested_reliability_threshold"
]

for var in required_vars:
    print(f"{var}:", "FOUND" if var in globals() else "MISSING")

best_config: FOUND
best_retriever_name: FOUND
final_rag_retrieve: FOUND
rag_examples_df: FOUND
suggested_reliability_threshold: FOUND

In [43]:
# =========================================================
# Final RAG Retriever Examples Table Before Stage 04 LLM
# جدول احترافي ومحمي لاختبار طبقة الاسترجاع النهائية قبل LLM
# =========================================================

from IPython.display import display, HTML
import pandas as pd
import numpy as np
import re

# ---------------------------------------------------------
# 0) Safety checks
# ---------------------------------------------------------

assert "rag_examples_df" in globals(), (
    "rag_examples_df غير معرّف. "
    "شغّل الخلية التي تولّد أمثلة final_rag_retrieve() أولاً."
)

df_raw = rag_examples_df.copy()

print("Available columns in rag_examples_df:")
print(list(df_raw.columns))


# ---------------------------------------------------------
# 1) Helper functions
# ---------------------------------------------------------

def parse_bool(value):
    """
    Convert different boolean-like values into True / False / None.
    """
    if isinstance(value, (bool, np.bool_)):
        return bool(value)

    if pd.isna(value):
        return None

    v = str(value).strip().lower()

    if v in ["true", "1", "yes", "y", "موثوق"]:
        return True

    if v in ["false", "0", "no", "n", "غير موثوق"]:
        return False

    return None


def clean_numeric_article_number(value):
    """
    Clean article number display:
    53.0 -> 53
    nan -> empty
    """
    if pd.isna(value):
        return ""

    s = str(value).strip()

    if s == "" or s.lower() in ["nan", "none", "null", "na", "n/a"]:
        return ""

    try:
        f = float(s)
        if f.is_integer():
            return str(int(f))
        return str(f)
    except Exception:
        return s


def clean_title(value):
    """
    Clean article title display.
    """
    if pd.isna(value):
        return ""

    s = str(value).strip()

    if s == "" or s.lower() in ["nan", "none", "null", "na", "n/a"]:
        return ""

    return s


def strip_ids_and_metadata(text):
    """
    Remove common technical metadata from retrieved context.
    """
    if pd.isna(text):
        return ""

    t = str(text)

    # Normalize spacing
    t = t.replace("\n", " ")
    t = re.sub(r"\s+", " ", t).strip()

    # Remove technical IDs
    t = re.sub(r"\bSTRUCT_\d+\b", " ", t, flags=re.IGNORECASE)
    t = re.sub(r"\bTRUCT_\d+\b", " ", t, flags=re.IGNORECASE)
    t = re.sub(r"\bFAQ_[A-Z_]*\d+\b", " ", t, flags=re.IGNORECASE)
    t = re.sub(r"\b[a-f0-9]{24,}\b", " ", t, flags=re.IGNORECASE)

    # Remove English metadata
    english_patterns = [
        r"Rank\s*:\s*\d+\s*\|?",
        r"Source type\s*:\s*[^|]+?\|?",
        r"Score\s*:\s*[\d.]+\s*\|?",
        r"Chunk ID\s*:\s*[^|]+?\|?",
        r"Parent document ID\s*:\s*[^|]+?\|?",
        r"Document ID\s*:\s*[^|]+?\|?",
        r"Article number\s*:\s*[\d.nanNaN]+\s*\|?",
        r"Article title\s*:\s*[^|]+?\|?",
        r"legal_article\s+",
        r"\bfaq\b\s+",
    ]

    for p in english_patterns:
        t = re.sub(p, " ", t, flags=re.IGNORECASE)

    # Remove Arabic metadata labels, but keep useful legal/FAQ content
    arabic_patterns = [
        r"التصنيف\s*[:：]\s*[^:：]{0,120}",
        r"المصدر\s*[:：]\s*[^:：]{0,120}",
        r"الموقع الفرعي\s*[:：]\s*[^:：]{0,120}",
        r"القسم\s*[:：]\s*[^:：]{0,120}",
        r"الباب\s*[:：]\s*[^:：]{0,120}",
        r"الفصل\s*[:：]\s*[^:：]{0,120}",
        r"عنوان المادة\s*[:：]\s*[^:：]{0,120}",
        r"رقم المادة\s*[:：]\s*[\d.]+",
        r"حالة المادة\s*[:：]\s*[^:：]{0,60}",
        r"active\s*",
    ]

    for p in arabic_patterns:
        t = re.sub(p, " ", t, flags=re.IGNORECASE)

    # Clean separators
    t = t.replace("|", " ")
    t = re.sub(r"\s+", " ", t).strip()

    return t


def extract_useful_context(text, source_type="", max_chars=520):
    """
    Extract useful LLM context:
    - For legal articles: prefer text after النص / النص القانوني
    - For FAQ: prefer text after الإجابة
    - Otherwise clean metadata and return readable preview
    """
    if pd.isna(text):
        return ""

    original = str(text).replace("\n", " ")
    original = re.sub(r"\s+", " ", original).strip()

    source_type = str(source_type).strip().lower()

    candidate = original

    # Prefer legal article body
    legal_patterns = [
        r"النص\s+القانوني\s*[:：]\s*(.+)",
        r"النص\s*[:：]\s*(.+)",
    ]

    # Prefer FAQ answer body
    faq_patterns = [
        r"الإجابة\s*[:：]\s*(.+)",
        r"الجواب\s*[:：]\s*(.+)",
    ]

    extracted = ""

    if source_type == "legal_article":
        for p in legal_patterns:
            m = re.search(p, original, flags=re.IGNORECASE)
            if m:
                extracted = m.group(1)
                break

    elif source_type == "faq":
        for p in faq_patterns:
            m = re.search(p, original, flags=re.IGNORECASE)
            if m:
                extracted = m.group(1)
                break

    # If source-specific extraction failed, try both
    if not extracted:
        for p in legal_patterns + faq_patterns:
            m = re.search(p, original, flags=re.IGNORECASE)
            if m:
                extracted = m.group(1)
                break

    if extracted:
        candidate = extracted

    cleaned = strip_ids_and_metadata(candidate)

    if not cleaned:
        cleaned = strip_ids_and_metadata(original)

    if not cleaned:
        return "لا توجد معاينة نصية واضحة للسياق."

    if source_type == "legal_article":
        prefix = "مقتطف من مادة قانونية: "
    elif source_type == "faq":
        prefix = "مقتطف من FAQ رسمي: "
    else:
        prefix = "مقتطف من السياق المسترجع: "

    cleaned = prefix + cleaned

    if len(cleaned) > max_chars:
        cleaned = cleaned[:max_chars].strip() + "..."

    return cleaned


def build_context_preview(row):
    """
    Build display context:
    - If unreliable: do not show retrieved context.
    - If reliable: show cleaned useful context for LLM.
    """
    reliable = parse_bool(row.get("is_retrieval_reliable", None))

    if reliable is False:
        return "غير موثوق: لن يتم تمرير هذا السياق إلى نموذج اللغة الكبير."

    source_type = row.get("top1_source_type", "")

    # context_for_llm is the real final context before LLM.
    priority_cols = [
        "context_for_llm",
        "retrieved_context",
        "top1_text",
        "top1_chunk_text",
        "context",
        "context_preview"
    ]

    for col in priority_cols:
        if col in row.index:
            value = row.get(col, "")
            if pd.notna(value) and str(value).strip():
                return extract_useful_context(
                    value,
                    source_type=source_type,
                    max_chars=520
                )

    return "لا يوجد سياق مسترجع متاح للعرض."


def build_reliability_status(row):
    reliable = parse_bool(row.get("is_retrieval_reliable", None))

    if reliable is True:
        return "موثوق"

    if reliable is False:
        return "غير موثوق"

    return ""


def build_source_note(row):
    reliable = parse_bool(row.get("is_retrieval_reliable", None))
    source_type = str(row.get("top1_source_type", "")).strip().lower()

    if reliable is False:
        return "محجوب بسبب انخفاض درجة الموثوقية."

    if source_type == "legal_article":
        return "مصدر قانوني مباشر مع رقم مادة."

    if source_type == "faq":
        return "مصدر FAQ رسمي. لا يوجد رقم مادة مباشر."

    return "مصدر غير محدد."


# ---------------------------------------------------------
# 2) Build clean display dataframe
# ---------------------------------------------------------

df = df_raw.copy()

df["reliability_status"] = df.apply(build_reliability_status, axis=1)
df["context_preview_clean"] = df.apply(build_context_preview, axis=1)
df["source_note"] = df.apply(build_source_note, axis=1)

if "top1_article_number" in df.columns:
    df["top1_article_number"] = df["top1_article_number"].apply(clean_numeric_article_number)

if "top1_article_title" in df.columns:
    df["top1_article_title"] = df["top1_article_title"].apply(clean_title)

if "top1_source_type" in df.columns:
    df["top1_source_type"] = df["top1_source_type"].fillna("").astype(str).replace("nan", "")

if "top1_backend" in df.columns:
    df["top1_backend"] = df["top1_backend"].fillna("").astype(str).replace("nan", "")


wanted_cols = [
    "query",
    "reliability_status",
    "top1_score",
    "top1_source_type",
    "top1_article_number",
    "top1_article_title",
    "source_note",
    "top1_backend",
    "latency_sec",
    "context_preview_clean",
]

present_cols = [c for c in wanted_cols if c in df.columns]
df_display = df[present_cols].copy()

rename_map = {
    "query": "السؤال",
    "reliability_status": "حالة الاسترجاع",
    "top1_score": "درجة أول نتيجة",
    "top1_source_type": "نوع المصدر",
    "top1_article_number": "رقم المادة",
    "top1_article_title": "عنوان المادة",
    "source_note": "ملاحظة المصدر",
    "top1_backend": "طريقة الاسترجاع",
    "latency_sec": "زمن الاسترجاع بالثواني",
    "context_preview_clean": "معاينة السياق المسترجع للـ LLM",
}

df_display = df_display.rename(columns={k: v for k, v in rename_map.items() if k in df_display.columns})


# ---------------------------------------------------------
# 3) Header
# ---------------------------------------------------------

display(HTML("""
<div dir="rtl" style="
    text-align:right;
    font-family:Tahoma, Arial;
    line-height:2;
    font-size:17px;
    background:#f8fbfd;
    border-right:5px solid #1f4e79;
    padding:14px 18px;
    border-radius:8px;
    margin-bottom:14px;">
<h3>اختبار طبقة الاسترجاع النهائية قبل مرحلة LLM</h3>
<p>
يعرض هذا الجدول أمثلة لاختبار دالة
<span dir="ltr" style="display:inline-block;">final_rag_retrieve()</span>
قبل مرحلة توليد الإجابة. تم تنظيف عمود السياق بحيث يعرض مقتطفًا مفهومًا من المادة القانونية أو FAQ الرسمي،
مع منع تمرير السياق إلى نموذج اللغة الكبير عندما تكون درجة الاسترجاع غير موثوقة.
</p>
</div>
"""))


# ---------------------------------------------------------
# 4) Styling helpers
# ---------------------------------------------------------

def color_reliability(v):
    if v == "موثوق":
        return "background-color: #DFF2E1; font-weight: bold; color: #1F6E43;"
    if v == "غير موثوق":
        return "background-color: #F8D7DA; font-weight: bold; color: #842029;"
    return ""


def color_score(v):
    try:
        score = float(v)
    except Exception:
        return ""

    if "suggested_reliability_threshold" in globals():
        thr = float(suggested_reliability_threshold)
    elif "score_calibration" in globals() and "suggested_reliability_threshold" in score_calibration.columns:
        thr = float(score_calibration["suggested_reliability_threshold"].iloc[0])
    else:
        thr = 0.4983

    if score >= thr:
        return "background-color: #DFF2E1;"
    return "background-color: #F8D7DA;"


def color_source_note(v):
    s = str(v)
    if "مصدر قانوني" in s:
        return "background-color: #E7F1FF; color: #084298;"
    if "FAQ" in s:
        return "background-color: #FFF3CD; color: #664D03;"
    if "محجوب" in s:
        return "background-color: #F8D7DA; color: #842029;"
    return ""


# ---------------------------------------------------------
# 5) Display professional styled table
# ---------------------------------------------------------

sty = df_display.style.set_caption("Final RAG Retriever Examples for Stage 04 LLM")

format_dict = {}

if "درجة أول نتيجة" in df_display.columns:
    format_dict["درجة أول نتيجة"] = "{:.4f}"

if "زمن الاسترجاع بالثواني" in df_display.columns:
    format_dict["زمن الاسترجاع بالثواني"] = "{:.4f}"

sty = sty.format(format_dict)

sty = sty.set_table_styles([
    {
        "selector": "caption",
        "props": [
            ("caption-side", "top"),
            ("font-size", "18px"),
            ("font-weight", "bold"),
            ("text-align", "center"),
            ("padding", "10px"),
            ("color", "#17324d"),
        ],
    },
    {
        "selector": "th",
        "props": [
            ("background-color", "#F2F2F2"),
            ("font-weight", "bold"),
            ("text-align", "center"),
            ("border", "1px solid #CCCCCC"),
            ("padding", "8px"),
            ("white-space", "nowrap"),
        ],
    },
    {
        "selector": "td",
        "props": [
            ("text-align", "center"),
            ("border", "1px solid #DDDDDD"),
            ("padding", "8px"),
            ("vertical-align", "top"),
        ],
    },
    {
        "selector": "table",
        "props": [
            ("border-collapse", "collapse"),
            ("width", "100%"),
            ("font-size", "14px"),
            ("font-family", "Tahoma, Arial"),
        ],
    },
])

# Apply conditional colors with compatibility
if "حالة الاسترجاع" in df_display.columns:
    if hasattr(sty, "map"):
        sty = sty.map(color_reliability, subset=["حالة الاسترجاع"])
    else:
        sty = sty.applymap(color_reliability, subset=["حالة الاسترجاع"])

if "درجة أول نتيجة" in df_display.columns:
    if hasattr(sty, "map"):
        sty = sty.map(color_score, subset=["درجة أول نتيجة"])
    else:
        sty = sty.applymap(color_score, subset=["درجة أول نتيجة"])

if "ملاحظة المصدر" in df_display.columns:
    if hasattr(sty, "map"):
        sty = sty.map(color_source_note, subset=["ملاحظة المصدر"])
    else:
        sty = sty.applymap(color_source_note, subset=["ملاحظة المصدر"])

# Arabic text columns
rtl_cols = [
    c for c in [
        "السؤال",
        "عنوان المادة",
        "ملاحظة المصدر",
        "معاينة السياق المسترجع للـ LLM"
    ]
    if c in df_display.columns
]

if rtl_cols:
    sty = sty.set_properties(
        subset=rtl_cols,
        **{
            "text-align": "right",
            "direction": "rtl",
            "white-space": "normal",
            "line-height": "1.8",
        }
    )

# Wider context column
if "معاينة السياق المسترجع للـ LLM" in df_display.columns:
    sty = sty.set_properties(
        subset=["معاينة السياق المسترجع للـ LLM"],
        **{
            "max-width": "620px",
            "min-width": "420px",
        }
    )

# English / technical columns
ltr_cols = [
    c for c in ["نوع المصدر", "طريقة الاسترجاع"]
    if c in df_display.columns
]

if ltr_cols:
    sty = sty.set_properties(
        subset=ltr_cols,
        **{
            "direction": "ltr",
            "text-align": "center",
            "white-space": "nowrap",
        }
    )

display(sty)


# ---------------------------------------------------------
# 6) Optional save outputs
# ---------------------------------------------------------

if "STAGE03_DIR" in globals():
    output_csv = STAGE03_DIR / "stage04_final_rag_retriever_examples_clean.csv"
    output_xlsx = STAGE03_DIR / "stage04_final_rag_retriever_examples_clean.xlsx"

    df_display.to_csv(output_csv, index=False, encoding="utf-8-sig")

    try:
        with pd.ExcelWriter(output_xlsx, engine="openpyxl") as writer:
            df_display.to_excel(writer, index=False, sheet_name="final_retriever_examples")
        print("Saved Excel:", output_xlsx)
    except Exception as e:
        print("Excel save skipped:", e)

    print("Saved CSV:", output_csv)

Available columns in rag_examples_df:
['query', 'is_retrieval_reliable', 'suggested_reliability_threshold', 'top1_score', 'top1_source_type', 'top1_article_number', 'top1_article_title', 'top1_chunk_id', 'top1_parent_document_id', 'top1_backend', 'latency_sec', 'context_preview', 'context_for_llm', 'best_chunking_strategy', 'best_embedding_model', 'best_retriever', 'best_alpha']

Saved Excel: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\stage04_final_rag_retriever_examples_clean.xlsx
Saved CSV: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\stage04_final_rag_retriever_examples_clean.csv

In [44]:
# =========================================================
# Stage 20 - Final Academic Retrieval Report
# =========================================================

final_report = {
    "project_dir": str(PROJECT_DIR),
    "stage03_dir": str(STAGE03_DIR),
    "evaluation_questions": int(len(df_eval_run)),
    "retrieval_experiments": int(len(experiment_configs)),
    "embedding_models_loaded": list(loaded_embedding_models.keys()),
    "reranker_loaded": reranker_model is not None,
    "chromadb_required": REQUIRE_CHROMADB,
    "chromadb_vector_dir": str(VECTOR_DIR),
    "chromadb_collections": chroma_manifest.to_dict(orient="records"),
    "best_config": best_config,
    "suggested_reliability_threshold": suggested_reliability_threshold,
    "input_safety_checks": safety_df.to_dict(orient="records"),
}

with open(STAGE03_DIR / "stage03_final_retrieval_report.json", "w", encoding="utf-8") as f:
    json.dump(final_report, f, ensure_ascii=False, indent=2)

final_summary_table = pd.DataFrame([{
    "evaluation_questions": int(len(df_eval_run)),
    "experiment_configurations": int(len(experiment_configs)),
    "embedding_models_loaded": ", ".join(loaded_embedding_models.keys()),
    "reranker_loaded": bool(reranker_model is not None),
    "chromadb_used": True,
    "chroma_collections": int(len(chroma_manifest)),
    "best_chunking_strategy": best_config.get("chunking_strategy"),
    "best_embedding_model": best_config.get("embedding_model"),
    "best_retriever": best_config.get("retriever"),
    "best_alpha": best_config.get("alpha"),
    "best_recall_at_1": best_config.get("recall_at_1"),
    "best_recall_at_3": best_config.get("recall_at_3"),
    "best_recall_at_5": best_config.get("recall_at_5"),
    "best_mrr": best_config.get("mrr"),
    "best_ndcg_at_5": best_config.get("ndcg_at_5"),
    "best_avg_latency_sec": best_config.get("avg_latency_sec"),
    "suggested_reliability_threshold": suggested_reliability_threshold,
}])

final_summary_table.to_csv(STAGE03_DIR / "stage03_final_summary_table.csv", index=False, encoding="utf-8-sig")
final_summary_table.to_excel(STAGE03_DIR / "stage03_final_summary_table.xlsx", index=False)

display(final_summary_table)
print("Final retrieval report saved:", STAGE03_DIR / "stage03_final_retrieval_report.json")

,evaluation_questions,experiment_configurations,embedding_models_loaded,reranker_loaded,chromadb_used,chroma_collections,best_chunking_strategy,best_embedding_model,best_retriever,best_alpha,best_recall_at_1,best_recall_at_3,best_recall_at_5,best_mrr,best_ndcg_at_5,best_avg_latency_sec,suggested_reliability_threshold
0,155,22,"e5_large, bge_m3",True,True,4,structural,e5_large,hybrid_reranker,0.8,0.9161,0.9871,0.9935,0.9508,0.9621,0.3361,0.7492

Final retrieval report saved: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\stage03_final_retrieval_report.json

In [45]:
# =========================================================
# Stage 21 - Voice Router + RAG Integration Test
# ربط طبقة الأسئلة العامة مع RAG استعداداً للمرحلة الرابعة
# =========================================================

import re
import pandas as pd
from IPython.display import display, HTML

# ---------------------------------------------------------
# Safety check: final_rag_retrieve must already exist
# ---------------------------------------------------------

assert "final_rag_retrieve" in globals(), (
    "final_rag_retrieve is not defined. "
    "Run Stage 19 - Final RAG Retriever Packaging for Stage 04 LLM first."
)

# ---------------------------------------------------------
# 1) Arabic normalization for routing only
# ---------------------------------------------------------

def normalize_arabic_query(text):
    """
    Normalize Arabic text for routing decisions only.
    This is not used for final answer generation.
    """
    text = str(text).strip().lower()

    # Remove Arabic diacritics and tatweel
    text = re.sub(r"[\u064B-\u065F\u0670]", "", text)
    text = text.replace("ـ", "")

    # Normalize common Arabic letter variations
    text = re.sub("[إأآا]", "ا", text)
    text = text.replace("ى", "ي")
    text = text.replace("ة", "ه")
    text = text.replace("ؤ", "و")
    text = text.replace("ئ", "ي")

    # Remove punctuation except Arabic/English letters and numbers
    text = re.sub(r"[^\w\s\u0600-\u06FF]", " ", text)

    # Normalize spaces
    text = re.sub(r"\s+", " ", text).strip()

    return text


def contains_any(text, phrases):
    normalized_phrases = [normalize_arabic_query(p) for p in phrases]
    return any(p in text for p in normalized_phrases)


# ---------------------------------------------------------
# 2) Intent patterns
# ---------------------------------------------------------

GREETING_PATTERNS = [
    "السلام عليكم", "سلام عليكم", "السلام", "سلام",
    "هلا", "اهلا", "مرحبا", "حياك", "صباح الخير", "مساء الخير",
    "كيف الحال", "كيفك", "كيف حالك", "وش اخبارك", "ايش اخبارك",
    "شلونك", "عامل ايه", "اخبارك"
]

IDENTITY_PATTERNS = [
    "انت مين", "مين انت", "من انت", "مين معي", "مع مين",
    "ايش اسمك", "وش اسمك", "اسمك", "اكلم مين", "اتكلم مع مين"
]

CAPABILITY_PATTERNS = [
    "وش تقدر تساعدني", "ايش تقدر تساعدني", "كيف تساعدني",
    "وش خدماتك", "ايش خدماتك", "بماذا تساعدني",
    "تقدر تساعدني في ايش", "ايش تقدر تسوي", "وش تقدر تسوي"
]

THANKS_PATTERNS = [
    "شكرا", "شكرا لك", "يعطيك العافيه", "مشكور", "تسلم", "الله يعطيك العافيه"
]

GOODBYE_PATTERNS = [
    "مع السلامه", "باي", "وداعا", "شكرا خلاص", "خلاص شكرا"
]

OUT_OF_SCOPE_PATTERNS = [
    "الطقس", "درجة الحراره", "مطعم", "فندق", "رحله", "سفر",
    "سعر العقار", "سعر البيت", "اسعار العقار", "شراء بيت",
    "الاسهم", "سهم", "بيتكوين", "عملات رقميه",
    "طلاق", "زواج", "ميراث", "جنائي", "قضيه جنائيه",
    "علاج", "دواء", "اعراض", "طبيب"
]

LEGAL_LABOR_PATTERNS = [
    "نظام العمل", "مكتب العمل", "وزاره الموارد", "الموارد البشريه",
    "عامل", "العامل", "صاحب العمل", "منشاه", "الشركه",
    "عقد العمل", "العقد", "راتب", "اجر", "الاجر",
    "مكافاه", "نهايه الخدمه", "فتره التجربه", "تجربه",
    "استقاله", "فصل", "انهاء العقد", "ساعات العمل",
    "دوام", "اجازه", "اجازات", "نقل العامل", "اصابه عمل",
    "تعويض", "انذار", "غياب", "تأخير", "تدريب", "سعوده"
]

# ---------------------------------------------------------
# 3) Router function
# ---------------------------------------------------------

def route_voice_query(user_query):
    """
    Route Arabic voice-agent query before RAG and LLM.

    Returns a routing decision:
    - direct_response for greetings, identity, thanks, and clear out-of-scope
    - rag_retrieval for legal or possibly legal questions
    """

    raw_query = str(user_query).strip()
    q = normalize_arabic_query(raw_query)

    if not q:
        return {
            "intent": "empty_or_unclear",
            "route": "ask_clarification",
            "needs_rag": False,
            "direct_response": "عذراً، لم أسمع السؤال بوضوح. ممكن تعيد صياغة السؤال؟",
            "reason": "Empty query after normalization."
        }

    if contains_any(q, GREETING_PATTERNS):
        return {
            "intent": "greeting_or_small_talk",
            "route": "direct_response",
            "needs_rag": False,
            "direct_response": "أهلاً وسهلاً، معك المساعد الذكي لنظام العمل السعودي. كيف أقدر أساعدك؟",
            "reason": "Greeting or small-talk detected."
        }

    if contains_any(q, IDENTITY_PATTERNS):
        return {
            "intent": "agent_identity",
            "route": "direct_response",
            "needs_rag": False,
            "direct_response": "معك وكيل صوتي ذكي مخصص للإجابة عن الاستفسارات المتعلقة بنظام العمل السعودي.",
            "reason": "Agent identity question detected."
        }

    if contains_any(q, CAPABILITY_PATTERNS):
        return {
            "intent": "agent_capability",
            "route": "direct_response",
            "needs_rag": False,
            "direct_response": "أقدر أساعدك في أسئلة نظام العمل السعودي مثل فترة التجربة، ساعات العمل، الإجازات، الاستقالة، ونهاية الخدمة.",
            "reason": "Capability question detected."
        }

    if contains_any(q, THANKS_PATTERNS):
        return {
            "intent": "thanks",
            "route": "direct_response",
            "needs_rag": False,
            "direct_response": "حياك الله، سعيد بخدمتك. هل عندك استفسار آخر بخصوص نظام العمل السعودي؟",
            "reason": "Thanks detected."
        }

    if contains_any(q, GOODBYE_PATTERNS):
        return {
            "intent": "goodbye",
            "route": "direct_response",
            "needs_rag": False,
            "direct_response": "مع السلامة، سعيد بخدمتك.",
            "reason": "Goodbye detected."
        }

    if contains_any(q, OUT_OF_SCOPE_PATTERNS):
        return {
            "intent": "out_of_scope",
            "route": "safe_rejection",
            "needs_rag": False,
            "direct_response": "عذراً، هذا السؤال خارج نطاق اختصاصي. أستطيع مساعدتك فقط في الاستفسارات المتعلقة بنظام العمل السعودي.",
            "reason": "Clearly outside Saudi labor law scope."
        }

    if contains_any(q, LEGAL_LABOR_PATTERNS):
        return {
            "intent": "labor_law_question",
            "route": "rag_retrieval",
            "needs_rag": True,
            "direct_response": None,
            "reason": "Labor-law keyword detected; send to RAG retrieval."
        }

    return {
        "intent": "possible_labor_question",
        "route": "rag_retrieval_with_reliability_gate",
        "needs_rag": True,
        "direct_response": None,
        "reason": "Not small-talk and not clearly out-of-scope; allow RAG then apply reliability gate."
    }


# ---------------------------------------------------------
# 4) Route then retrieve bridge for Stage 04 LLM
# ---------------------------------------------------------

def route_then_retrieve_for_llm(user_query, top_k=5):
    """
    Bridge function between Stage 03 RAG and Stage 04 LLM.

    If the query is small talk, identity, thanks, or clearly out-of-scope:
        return a direct response without RAG and without LLM.

    If the query is legal or possibly related to Saudi labor law:
        run final_rag_retrieve and prepare retrieved context for the LLM.
    """

    routing_decision = route_voice_query(user_query)

    # Direct response path: no RAG, no LLM needed
    if not routing_decision["needs_rag"]:
        return {
            "user_query": user_query,
            "intent": routing_decision["intent"],
            "route": routing_decision["route"],
            "needs_rag": False,
            "direct_answer": routing_decision["direct_response"],
            "retrieval_result": None,
            "send_to_llm": False,
            "reason": routing_decision["reason"],
            "is_retrieval_reliable": None,
            "top1_score": None,
            "latency_sec": None,
        }

      # RAG path: retrieve context for LLM
    retrieval_result = final_rag_retrieve(user_query, top_k=top_k)

    is_reliable = bool(retrieval_result.get("is_retrieval_reliable", False))

    # If retrieval is not reliable, do not send to LLM
    if not is_reliable:
        return {
            "user_query": user_query,
            "intent": routing_decision["intent"],
            "route": "rag_retrieval_blocked_by_reliability_gate",
            "needs_rag": True,
            "direct_answer": "عذرًا، لم أجد نصًا موثوقًا في نظام العمل السعودي يدعم إجابة دقيقة على هذا السؤال. يمكنك إعادة صياغة السؤال أو طرح سؤال متعلق مباشرة بنظام العمل السعودي، أو اضغط رقم 1 لتحويلك إلى موظف خدمة العملاء..",
            "retrieval_result": retrieval_result,
            "send_to_llm": False,
            "reason": "RAG retrieval score is below the reliability threshold.",
            "is_retrieval_reliable": False,
            "top1_score": retrieval_result.get("top1_score"),
            "latency_sec": retrieval_result.get("latency_sec"),
        }

    return {
        "user_query": user_query,
        "intent": routing_decision["intent"],
        "route": routing_decision["route"],
        "needs_rag": True,
        "direct_answer": None,
        "retrieval_result": retrieval_result,
        "send_to_llm": True,
        "reason": routing_decision["reason"],
        "is_retrieval_reliable": True,
        "top1_score": retrieval_result.get("top1_score"),
        "latency_sec": retrieval_result.get("latency_sec"),
    }


# ---------------------------------------------------------
# 5) Quick integration test
# ---------------------------------------------------------

integration_test_queries = [
    "السلام عليكم",
    "كيف الحال؟",
    "مين معي؟",
    "وش تقدر تساعدني؟",
    "كم مدة فترة التجربة؟",
    "متى يستحق العامل مكافأة نهاية الخدمة؟",
    "كم عدد ساعات العمل؟",
    "كم سعر العقار في الرياض؟",
    "ما حكم الطلاق؟",
    "هل يحق للعامل الحصول على سيارة من الشركة؟"
]

integration_rows = []

for q in integration_test_queries:
    result = route_then_retrieve_for_llm(q, top_k=5)

    integration_rows.append({
        "user_query": q,
        "intent": result["intent"],
        "route": result["route"],
        "needs_rag": result["needs_rag"],
        "send_to_llm": result["send_to_llm"],
        "is_retrieval_reliable": result["is_retrieval_reliable"],
        "top1_score": result["top1_score"],
        "latency_sec": result["latency_sec"],
        "direct_answer": result["direct_answer"],
        "reason": result["reason"],
    })

integration_test_df = pd.DataFrame(integration_rows)

display(HTML("""
<div dir="rtl" style="text-align:right; line-height:2; font-size:17px;">
<h3>اختبار ربط Router مع طبقة RAG قبل مرحلة LLM</h3>
<p>
يوضح الجدول التالي كيف يقرر النظام هل يرد مباشرة على السؤال، أو يرسل السؤال إلى طبقة الاسترجاع،
أو يمنع تمريره إلى نموذج اللغة إذا كانت نتيجة الاسترجاع غير موثوقة.
</p>
</div>
"""))

# =========================================================
# Professional Display for Voice Router + RAG Integration
# عرض احترافي لاختبار Router + RAG
# =========================================================

from IPython.display import display, HTML
import pandas as pd
import numpy as np

integration_display = integration_test_df.copy()

# ---------------------------------------------------------
# 1) تحويل القيم التقنية إلى قيم مفهومة للعرض
# ---------------------------------------------------------

integration_display["needs_rag_label"] = integration_display["needs_rag"].map({
    True: "يحتاج RAG",
    False: "لا يحتاج RAG"
})

integration_display["send_to_llm_label"] = integration_display["send_to_llm"].map({
    True: "يُرسل إلى LLM",
    False: "لا يُرسل إلى LLM"
})

integration_display["reliability_label"] = integration_display["is_retrieval_reliable"].map({
    True: "موثوق",
    False: "غير موثوق",
    None: "غير مطلوب"
}).fillna("غير مطلوب")

# اختصار الرد المباشر للعرض فقط
integration_display["direct_answer_preview"] = (
    integration_display["direct_answer"]
    .fillna("—")
    .astype(str)
    .str.replace("\n", " ", regex=False)
    .str.slice(0, 120)
)

# اختصار السبب للعرض فقط
integration_display["reason_preview"] = (
    integration_display["reason"]
    .fillna("—")
    .astype(str)
    .str.replace("\n", " ", regex=False)
    .str.slice(0, 110)
)

# ---------------------------------------------------------
# 2) ترتيب الأعمدة للعرض الأكاديمي
# ---------------------------------------------------------

display_cols = [
    "user_query",
    "intent",
    "route",
    "needs_rag_label",
    "send_to_llm_label",
    "reliability_label",
    "top1_score",
    "latency_sec",
    "direct_answer_preview",
    "reason_preview",
]

integration_display = integration_display[display_cols]

integration_display = integration_display.rename(columns={
    "user_query": "سؤال المستخدم",
    "intent": "نوع النية",
    "route": "مسار المعالجة",
    "needs_rag_label": "هل يحتاج RAG؟",
    "send_to_llm_label": "قرار الإرسال إلى LLM",
    "reliability_label": "موثوقية الاسترجاع",
    "top1_score": "درجة أول نتيجة",
    "latency_sec": "زمن الاسترجاع",
    "direct_answer_preview": "الرد المباشر",
    "reason_preview": "سبب القرار",
})

# ---------------------------------------------------------
# 3) عنوان توضيحي قبل الجدول
# ---------------------------------------------------------

display(HTML("""
<div dir="rtl" style="text-align:right; line-height:2; font-size:17px;">
<h3>اختبار تكامل طبقة Router مع RAG قبل مرحلة LLM</h3>
<p>
يعرض الجدول التالي كيف يتعامل الوكيل الصوتي مع أنواع مختلفة من الأسئلة:
التحيات والأسئلة العامة يتم الرد عليها مباشرة، والأسئلة القانونية الموثوقة يتم تمريرها إلى نموذج اللغة،
أما الأسئلة الخارجة عن النطاق أو غير الموثوقة فيتم منعها من الوصول إلى نموذج اللغة.
</p>
</div>
"""))

# ---------------------------------------------------------
# 4) تنسيق احترافي للجدول
# ---------------------------------------------------------

def style_reliability(v):
    if v == "موثوق":
        return "background-color: #DFF2E1; color: #1F6E43; font-weight: bold;"
    if v == "غير موثوق":
        return "background-color: #F8D7DA; color: #842029; font-weight: bold;"
    return "background-color: #F2F2F2; color: #555555;"

def style_llm_decision(v):
    if v == "يُرسل إلى LLM":
        return "background-color: #DFF2E1; color: #1F6E43; font-weight: bold;"
    return "background-color: #FFF3CD; color: #664D03; font-weight: bold;"

def style_rag_need(v):
    if v == "يحتاج RAG":
        return "background-color: #D9EAF7; color: #084C7C; font-weight: bold;"
    return "background-color: #F2F2F2; color: #555555;"

def style_score(v):
    try:
        if pd.isna(v):
            return "background-color: #F2F2F2; color: #777777;"
        if float(v) >= float(suggested_reliability_threshold):
            return "background-color: #DFF2E1; color: #1F6E43; font-weight: bold;"
        return "background-color: #F8D7DA; color: #842029; font-weight: bold;"
    except Exception:
        return ""

styled_integration_table = (
    integration_display.style
    .set_caption("Voice Router + RAG Integration Test")
    .format({
        "درجة أول نتيجة": lambda x: "—" if pd.isna(x) else f"{float(x):.4f}",
        "زمن الاسترجاع": lambda x: "—" if pd.isna(x) else f"{float(x):.4f}",
    })
    .set_table_styles([
        {
            "selector": "caption",
            "props": [
                ("caption-side", "top"),
                ("font-size", "18px"),
                ("font-weight", "bold"),
                ("text-align", "center"),
                ("padding", "10px"),
            ],
        },
        {
            "selector": "th",
            "props": [
                ("background-color", "#F2F2F2"),
                ("font-weight", "bold"),
                ("text-align", "center"),
                ("border", "1px solid #CCCCCC"),
                ("padding", "8px"),
            ],
        },
        {
            "selector": "td",
            "props": [
                ("text-align", "center"),
                ("border", "1px solid #DDDDDD"),
                ("padding", "8px"),
                ("vertical-align", "top"),
            ],
        },
        {
            "selector": "table",
            "props": [
                ("border-collapse", "collapse"),
                ("width", "100%"),
                ("font-size", "14px"),
            ],
        },
    ])
    .set_properties(
        subset=["سؤال المستخدم", "الرد المباشر", "سبب القرار"],
        **{
            "text-align": "right",
            "direction": "rtl",
            "white-space": "normal",
            "max-width": "360px",
        }
    )
    .map(style_rag_need, subset=["هل يحتاج RAG؟"])
.map(style_llm_decision, subset=["قرار الإرسال إلى LLM"])
.map(style_reliability, subset=["موثوقية الاسترجاع"])
.map(style_score, subset=["درجة أول نتيجة"])
)

display(styled_integration_table)

In [46]:
# =========================================================
# Save Function - Voice Router + RAG Integration Results
# دالة حفظ نتائج اختبار Router + RAG
# =========================================================

from pathlib import Path
import pandas as pd

def save_voice_router_rag_results(
    raw_df,
    display_df=None,
    output_dir=None,
    base_name="voice_router_rag_integration_test"
):
    """
    Save Voice Router + RAG integration test results.

    Saves:
    1. Raw full results as CSV and Excel
    2. Display/clean table as CSV and Excel
    3. Styled HTML table if display_df is available

    Parameters:
        raw_df: original full DataFrame
        display_df: cleaned/renamed display DataFrame
        output_dir: output directory
        base_name: base filename without extension
    """

    if output_dir is None:
        output_dir = STAGE03_DIR

    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    # -----------------------------------------------------
    # 1) Save raw full table
    # -----------------------------------------------------

    raw_csv_path = output_dir / f"{base_name}_raw.csv"
    raw_xlsx_path = output_dir / f"{base_name}_raw.xlsx"

    raw_df.to_csv(
        raw_csv_path,
        index=False,
        encoding="utf-8-sig"
    )

    raw_df.to_excel(
        raw_xlsx_path,
        index=False
    )

    saved_files = {
        "raw_csv": str(raw_csv_path),
        "raw_excel": str(raw_xlsx_path),
    }

    # -----------------------------------------------------
    # 2) Save display table if provided
    # -----------------------------------------------------

    if display_df is not None:
        display_csv_path = output_dir / f"{base_name}_display.csv"
        display_xlsx_path = output_dir / f"{base_name}_display.xlsx"

        display_df.to_csv(
            display_csv_path,
            index=False,
            encoding="utf-8-sig"
        )

        display_df.to_excel(
            display_xlsx_path,
            index=False
        )

        saved_files["display_csv"] = str(display_csv_path)
        saved_files["display_excel"] = str(display_xlsx_path)

        # -------------------------------------------------
        # 3) Save styled HTML version
        # -------------------------------------------------

        html_path = output_dir / f"{base_name}_styled.html"

        try:
            styled_html = styled_integration_table.to_html()
            with open(html_path, "w", encoding="utf-8") as f:
                f.write(styled_html)

            saved_files["styled_html"] = str(html_path)

        except Exception as e:
            saved_files["styled_html_error"] = str(e)

    # -----------------------------------------------------
    # 4) Save manifest
    # -----------------------------------------------------

    manifest_df = pd.DataFrame(
        [{"file_type": k, "file_path": v} for k, v in saved_files.items()]
    )

    manifest_path = output_dir / f"{base_name}_save_manifest.csv"

    manifest_df.to_csv(
        manifest_path,
        index=False,
        encoding="utf-8-sig"
    )

    saved_files["manifest"] = str(manifest_path)

    print("Saved Voice Router + RAG integration outputs:")
    for k, v in saved_files.items():
        print(f"- {k}: {v}")

    return saved_files


# =========================================================
# Run Save Function
# تشغيل دالة الحفظ
# =========================================================

saved_router_files = save_voice_router_rag_results(
    raw_df=integration_test_df,
    display_df=integration_display,
    output_dir=STAGE03_DIR,
    base_name="voice_router_rag_integration_test"
)

Saved Voice Router + RAG integration outputs:
- raw_csv: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\voice_router_rag_integration_test_raw.csv
- raw_excel: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\voice_router_rag_integration_test_raw.xlsx
- display_csv: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\voice_router_rag_integration_test_display.csv
- display_excel: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\voice_router_rag_integration_test_display.xlsx
- styled_html: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\voice_router_rag_integration_test_styled.html
- manifest: C:\Users\PC\Desktop\data collection code\saudi_labor_law_voice_agent_project\08_stage03_rag_results\voice_router_rag_integration_test_save_manifest.csv

In [47]:
# =========================================================
# Stage 22 - Final Stage 03 Output Manifest
# فهرس نهائي احترافي لمخرجات المرحلة الثالثة
# =========================================================

import pandas as pd
from pathlib import Path
from IPython.display import display, HTML

def file_status_row(path, file_type="data_or_report", requirement="required"):
    path = Path(path)
    exists = path.exists()
    return {
        "file_name": path.name,
        "file_type": file_type,
        "requirement": requirement,
        "path": str(path),
        "exists": exists,
        "size_kb": round(path.stat().st_size / 1024, 2) if exists else 0,
        "status": "OK" if exists else ("MISSING_REQUIRED" if requirement == "required" else "MISSING_OPTIONAL"),
    }

required_output_files = [
    STAGE03_DIR / "stage03_input_file_manifest.csv",
    STAGE03_DIR / "stage03_input_safety_checks.csv",

    # ChromaDB manifests
    STAGE03_DIR / "chroma_collections_manifest.csv",
    STAGE03_DIR / "chroma_collections_manifest.xlsx",
    STAGE03_DIR / "chroma_collections_manifest.json",

    # Corpus and embeddings
    STAGE03_DIR / "corpus_summary_by_chunking_strategy.csv",
    STAGE03_DIR / "embedding_generation_summary.csv",
    STAGE03_DIR / "embedding_generation_summary.xlsx",

    # Final runnable evaluation dataset
    STAGE03_DIR / "stage03_final_runnable_evaluation_dataset.csv",

    # Retrieval evaluation
    STAGE03_DIR / "retrieval_evaluation_detailed_results.csv",
    STAGE03_DIR / "retrieval_evaluation_summary.csv",
    STAGE03_DIR / "retrieval_evaluation_summary.xlsx",
    STAGE03_DIR / "retrieval_summary_by_eval_type.csv",
    STAGE03_DIR / "retrieval_summary_by_eval_type.xlsx",

    # Best configuration
    STAGE03_DIR / "best_retrieval_config.json",

    # Diagnostics
    STAGE03_DIR / "best_config_error_summary.csv",
    STAGE03_DIR / "best_config_failures_at_5.csv",

    # Out-of-scope and reliability gate
    STAGE03_DIR / "out_of_scope_retrieval_behavior.csv",
    STAGE03_DIR / "reliability_gate_score_calibration.csv",

    # Final RAG retriever packaging
    STAGE03_DIR / "stage03_rag_retriever_context_examples.csv",
    STAGE03_DIR / "stage03_rag_retriever_context_examples.xlsx",
    STAGE03_DIR / "stage03_best_retriever_ready_for_llm_config.json",

    # Voice Router + RAG integration
    STAGE03_DIR / "voice_router_rag_integration_test_raw.csv",
    STAGE03_DIR / "voice_router_rag_integration_test_raw.xlsx",
    STAGE03_DIR / "voice_router_rag_integration_test_display.csv",
    STAGE03_DIR / "voice_router_rag_integration_test_display.xlsx",
    STAGE03_DIR / "voice_router_rag_integration_test_save_manifest.csv",

    # Final academic report
    STAGE03_DIR / "stage03_final_retrieval_report.json",
    STAGE03_DIR / "stage03_final_summary_table.csv",
    STAGE03_DIR / "stage03_final_summary_table.xlsx",
]

optional_output_files = [
    STAGE03_DIR / "stage03_input_file_manifest.xlsx",
    STAGE03_DIR / "stage03_input_safety_checks.xlsx",
    STAGE03_DIR / "stage03_final_runnable_evaluation_dataset.xlsx",
    STAGE03_DIR / "legal_extra_questions_gold_id_review_candidates.csv",
    STAGE03_DIR / "legal_extra_questions_gold_id_review_candidates.xlsx",
    STAGE03_DIR / "legal_extra_questions_gold_id_reviewed.xlsx",
    STAGE03_DIR / "stage03_final_runnable_evaluation_dataset_with_reviewed_extra.csv",
    STAGE03_DIR / "legal_retrieval_evaluation_summary.csv",
    STAGE03_DIR / "legal_retrieval_evaluation_summary.xlsx",
    STAGE03_DIR / "best_legal_retrieval_config.json",
    STAGE03_DIR / "voice_router_rag_integration_test_styled.html",
    STAGE03_DIR / "stage03_eval_missing_gold_reference.csv",
    STAGE03_DIR / "stage03_eval_gold_not_available_in_index.csv",
]

figure_files = sorted(FIGURES_DIR.glob("stage03_*.png"))

manifest_rows = []
manifest_rows += [file_status_row(p, "data_or_report", "required") for p in required_output_files]
manifest_rows += [file_status_row(p, "data_or_report", "optional") for p in optional_output_files]
manifest_rows += [file_status_row(p, "figure", "optional") for p in figure_files]

stage03_output_manifest = pd.DataFrame(manifest_rows)

stage03_output_manifest.to_csv(
    STAGE03_DIR / "stage03_output_manifest.csv",
    index=False,
    encoding="utf-8-sig"
)

try:
    stage03_output_manifest.to_excel(
        STAGE03_DIR / "stage03_output_manifest.xlsx",
        index=False
    )
except Exception as e:
    print("Could not save Excel manifest:", e)

required_missing = stage03_output_manifest[
    (stage03_output_manifest["requirement"] == "required")
    & (~stage03_output_manifest["exists"])
].copy()

final_manifest_summary = pd.DataFrame([
    {"check": "Required output files", "value": int((stage03_output_manifest["requirement"] == "required").sum()), "status": "OK"},
    {"check": "Missing required output files", "value": len(required_missing), "status": "OK" if len(required_missing) == 0 else "FAIL"},
    {"check": "Optional output files", "value": int((stage03_output_manifest["requirement"] == "optional").sum()), "status": "INFO"},
    {"check": "Figures generated", "value": len(figure_files), "status": "INFO"},
])

display(HTML("<h3 style='color:#1f4e79'>Stage 22 — Final Output Manifest</h3>"))
display(
    style_academic_table(
        final_manifest_summary.style,
        "Final Manifest Summary"
    )
)

display(
    style_academic_table(
        stage03_output_manifest.style,
        "Stage 03 Output Manifest"
    )
)

if len(required_missing) > 0:
    display(HTML("""
    <div dir="rtl" style="text-align:right; background:#f8d7da; padding:12px;
                border-right:6px solid #dc3545; line-height:2; font-size:16px;">
        <b>تنبيه:</b> توجد ملفات مطلوبة غير موجودة. راجع الجدول أعلاه قبل اعتماد النتائج.
    </div>
    """))
    display(required_missing[["file_name", "path", "status"]])
    raise AssertionError("Some required Stage 03 output files are missing.")

display(HTML("""
<div dir="rtl" style="text-align:right; background:#e2f0d9; padding:12px;
            border-right:6px solid #70ad47; line-height:2; font-size:16px;">
    <b>Stage 03 completed successfully.</b>
    جميع الملفات الأساسية موجودة، ويمكن استخدام أفضل إعداد استرجاع في Notebook 04 الخاص بتوليد الإجابات.
</div>
"""))

In [48]:
# =========================================================
# Final Readiness Check - Where Are the Important Files?
# فحص سريع لمكان الملفات التي ستحتاجها في التقرير أو Notebook 04
# =========================================================

from pathlib import Path
import pandas as pd
from IPython.display import display, HTML

files_to_find = [
    "stage03_final_summary_table.xlsx",
    "retrieval_evaluation_summary.xlsx",
    "retrieval_summary_by_eval_type.xlsx",
    "stage03_output_manifest.xlsx",
    "best_retrieval_config.json",
    "stage03_best_retriever_ready_for_llm_config.json",
    "stage03_rag_retriever_context_examples.xlsx",
]

quick_rows = []

for f in files_to_find:
    p = STAGE03_DIR / f
    quick_rows.append({
        "file": f,
        "path": str(p),
        "exists": p.exists(),
        "size_kb": round(p.stat().st_size / 1024, 2) if p.exists() else 0,
        "status": "OK" if p.exists() else "MISSING",
    })

quick_files_df = pd.DataFrame(quick_rows)

display(HTML("<h3 style='color:#1f4e79'>Final Readiness Check</h3>"))
display(HTML(f"""
<div dir="rtl" style="text-align:right; line-height:2; font-size:16px;">
<b>STAGE03_DIR:</b>
<span dir="ltr">{STAGE03_DIR}</span>
</div>
"""))

display(
    style_academic_table(
        quick_files_df.style,
        "Important Stage 03 Files"
    )
)